In [1]:
#Starts from here
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression  # LogisticRegression is not used for regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from scipy.stats import pearsonr, spearmanr
from sklearn.model_selection import train_test_split
from tqdm import tqdm

def remove_low_variance_columns(df, threshold=0.005):
    # df = df.drop(['ID','SMILES','Permeability'],axis=1)
    variances = df.var()
    
    # Identify columns with variance below the threshold
    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

def features(df, target_column='Permeability', threshold=0.9):
    correlation_matrix = df.corr()
    
    features_to_drop = set()
    
    for feature in correlation_matrix.columns:
        if feature == target_column:
            continue 
        target_corr = correlation_matrix[target_column][feature]
        
        for other_feature in correlation_matrix.columns:
            if other_feature == feature or other_feature == target_column:
                continue
            
            if abs(correlation_matrix[feature][other_feature]) > threshold:
                other_target_corr = correlation_matrix[target_column][other_feature]

                if abs(other_target_corr) < abs(target_corr):
                    features_to_drop.add(other_feature)
                else:
                    features_to_drop.add(feature)
    selected_features = [col for col in df.columns if col not in features_to_drop and col != target_column]
    
    return selected_features

In [2]:
df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Train_2d_3d_all_descriptors_Caco2.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Test_2d_3d_all_descriptors_Caco2.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/All_fingerprints_train_Caco2.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/All_fingerprints_test_Caco2.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings_caco2.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings_caco2.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_all_atomic_desc_Caco2.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_all_atomic_desc_Caco2.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

/tmp/ipykernel_3168279/1550735325.py:1: DtypeWarning: Columns (1275,1277,1280,1285,1298,1354,1356,1359,1364,1377,1579,1580,1581,1583,1584,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Train_2d_3d_all_descriptors_Caco2.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(1007, 264)
(252, 264)
(1007, 868)
(252, 868)
(1007, 759)
(252, 759)
(1007, 12)
(252, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [3]:
merge_keys = ['ID', 'SMILES', 'Permeability']

merged_train = df_desc_train.merge(df_fp_train, on=merge_keys)
merged_train = merged_train.merge(df_emb_train, on=merge_keys)
merged_train = merged_train.merge(df_atomic_train, on=merge_keys)

merged_test = df_desc_test.merge(df_fp_test, on=merge_keys)
merged_test = merged_test.merge(df_emb_test, on=merge_keys)
merged_test = merged_test.merge(df_atomic_test, on=merge_keys)

In [4]:
X_train = merged_train.drop(columns=['ID', 'SMILES']).select_dtypes(include=['number'])
selected_final_features = features(X_train, target_column='Permeability')

train = pd.concat([merged_train[['ID', 'SMILES', 'Permeability']], X_train[selected_final_features]], axis=1)
test = merged_test[train.columns] 

print('selected_final_features', selected_final_features )
print("Final Train shape:", train.shape)
print("Final Test shape:", test.shape)

selected_final_features ['qed', 'SPS', 'FpDensityMorgan1', 'BCUT2D_MRHI', 'AvgIpc', 'BalabanJ_x', 'Ipc', 'EState_VSA11', 'NumSaturatedHeterocycles', 'NumUnspecifiedAtomStereoCenters', 'fr_Al_OH_noTert', 'fr_Ar_N', 'fr_aryl_methyl', 'fr_bicyclic', 'fr_methoxy', 'fr_morpholine', 'fr_para_hydroxylation', 'fr_piperdine', 'fr_unbrch_alkane', 'BasicGroupCount', 'AdjacencyMatrix.6', 'AdjacencyMatrix.9', 'AATS', 'AATS.4', 'AATS.23', 'AATS.90', 'AATS.95', 'AATS.96', 'ATSC.2', 'ATSC.5', 'ATSC.8', 'ATSC.11', 'ATSC.13', 'ATSC.14', 'ATSC.16', 'ATSC.17', 'ATSC.20', 'ATSC.21', 'ATSC.22', 'ATSC.23', 'ATSC.24', 'ATSC.25', 'ATSC.26', 'ATSC.28', 'ATSC.34', 'ATSC.35', 'ATSC.41', 'ATSC.42', 'ATSC.43', 'ATSC.46', 'ATSC.53', 'ATSC.64', 'ATSC.67', 'ATSC.74', 'ATSC.82', 'ATSC.84', 'ATSC.87', 'ATSC.95', 'ATSC.98', 'AATSC.9', 'AATSC.11', 'AATSC.12', 'AATSC.15', 'AATSC.16', 'AATSC.35', 'AATSC.37', 'AATSC.42', 'AATSC.47', 'AATSC.52', 'AATSC.53', 'AATSC.54', 'AATSC.58', 'AATSC.100', 'GATS.1', 'GATS.3', 'GATS.6', 'GATS.7', 'GATS.13', 'GATS.18', 'GATS.30', 'GATS.67', 'GATS.80', 'GATS.88', 'BCUT.3', 'BCUT.7', 'AtomTypeEState.16', 'AtomTypeEState.87', 'AtomTypeEState.89', 'AtomTypeEState.95', 'AtomTypeEState.110', 'AtomTypeEState.115', 'AtomTypeEState.127', 'AtomTypeEState.131', 'AtomTypeEState.132', 'AtomTypeEState.170', 'AtomTypeEState.173', 'AtomTypeEState.181', 'AtomTypeEState.249', 'AtomTypeEState.252', 'EtaVEMCount.6', 'InformationContent.1', 'ModifiedIC.5', 'MolecularDistanceEdge.7', 'RingCount.52', 'RingCount.63', 'ALogP', 'AATS3i', 'AATS4i', 'AATS7i', 'AATS8i', 'AATS4s', 'ATSC5c', 'ATSC6c', 'ATSC7c', 'ATSC3m', 'ATSC8v', 'ATSC5e', 'ATSC8e', 'ATSC3p', 'ATSC6p', 'ATSC7p', 'ATSC3i', 'ATSC6i', 'ATSC7i', 'ATSC3s', 'ATSC6s', 'AATSC3v', 'AATSC5v', 'AATSC6v', 'AATSC7v', 'AATSC8v', 'AATSC2i', 'AATSC5s', 'GATS5c', 'GATS6c', 'GATS4s', 'GATS8s', 'VE3_Dzm', 'VR1_Dzm', 'VE1_Dzv', 'VE3_Dzv', 'VE3_Dzs', 'VR1_Dzs', 'BCUTp-1l', 'BCUTp-1h', 'SpMax1_Bhm', 'SpMax4_Bhs', 'SpMax6_Bhs', 'VE3_Dt', 'VR1_Dt', 'nHBint3', 'nHBint4', 'nHBint5', 'nHBint7', 'nHBint8', 'nHBint9', 'nssO', 'SHBd', 'SHBint3', 'SHBint4', 'SHBint5', 'SHBint7', 'SHBint9', 'SHBint10', 'minHBa', 'minHBint2', 'minHBint3', 'minHBint4', 'minHBint5', 'minHBint6', 'minHBint7', 'minHBint8', 'minHBint9', 'minHBint10', 'minsCH3', 'minssCH2', 'minssssC', 'minssNH', 'mindsN', 'minsssN', 'mindO', 'maxHBd', 'maxHBint2', 'maxHBint3', 'maxHBint4', 'maxHBint5', 'maxHBint6', 'maxHBint8', 'maxHBint9', 'maxHBint10', 'maxHsOH', 'maxsCH3', 'maxssCH2', 'maxdssC', 'meanI', 'hmax', 'LipoaffinityIndex', 'nAtomLC', 'nAtomP', 'nAtomLAC', 'MDEC-11', 'MDEC-12', 'MDEC-13', 'MDEC-22', 'MDEC-23', 'MDEC-33', 'MDEC-34', 'MDEN-12', 'MLFER_A', 'R_TpiPCTPC', 'nTRing', 'LipinskiFailures', 'VE3_D', 'XLogP', '3d_rdkit_10', '3d_rdkit_11', 'TDB7u', 'TDB9u', 'TDB10u', 'TDB5m', 'TDB7m', 'TDB9m', 'TDB3e', 'TDB5e', 'TDB6e', 'TDB7e', 'TDB8e', 'TDB9e', 'TDB10e', 'TDB5p', 'TDB1i', 'TDB2i', 'TDB3i', 'TDB4i', 'TDB5i', 'TDB6i', 'TDB7i', 'TDB8i', 'TDB1s', 'TDB6s', 'TDB7s', 'TDB8s', 'TDB9s', 'RPCS', 'RNCS', 'LOBMAX', 'LOBMIN', 'MOMI-XY', 'MOMI-YZ', 'geomShape', 'Dm', 'Dv', 'L3p', 'Morgan_fp_5', 'Morgan_fp_19', 'Morgan_fp_65', 'Morgan_fp_84', 'Morgan_fp_109', 'Morgan_fp_115', 'Morgan_fp_119', 'Morgan_fp_130', 'Morgan_fp_140', 'Morgan_fp_231', 'Morgan_fp_253', 'Morgan_fp_269', 'Morgan_fp_305', 'Morgan_fp_310', 'Morgan_fp_325', 'Morgan_fp_328', 'Morgan_fp_334', 'Morgan_fp_370', 'Morgan_fp_473', 'Morgan_fp_476', 'Morgan_fp_534', 'Morgan_fp_552', 'Morgan_fp_562', 'Morgan_fp_585', 'Morgan_fp_598', 'Morgan_fp_634', 'Morgan_fp_675', 'Morgan_fp_684', 'Morgan_fp_692', 'Morgan_fp_713', 'Morgan_fp_725', 'Morgan_fp_739', 'Morgan_fp_745', 'Morgan_fp_749', 'Morgan_fp_784', 'Morgan_fp_798', 'Morgan_fp_820', 'Morgan_fp_832', 'Morgan_fp_878', 'Morgan_fp_890', 'Morgan_fp_893', 'Morgan_fp_926', 'Morgan_fp_1001', 'Morgan_fp_1028', 'Morgan_fp_1052', 'Morgan_fp_1088', 'Morgan_fp_1089', 'Morgan_fp_1162', 'Morgan_fp_1248', 'Morgan_fp_1313', 'Morgan_fp_1325', 'Morgan_fp_1345', 'Morgan_fp_1349', 'Morgan_fp_1352', 'Morgan_fp_1456', 'Morgan_fp_1495', 'Morgan_fp_1516', 'Morgan_fp_1543', 'Morgan_fp_1545', 'Morgan_fp_1562', 'Morgan_fp_1596', 'Morgan_fp_1613', 'Morgan_fp_1662', 'Morgan_fp_1689', 'Morgan_fp_1693', 'Morgan_fp_1765', 'Morgan_fp_1783', 'Morgan_fp_1898', 'Morgan_fp_1911', 'Morgan_fp_1920', 'Morgan_fp_1946', 'Morgan_fp_2008', 'count_fp_2', 'count_fp_19', 'count_fp_79', 'count_fp_80', 'count_fp_84', 'count_fp_94', 'count_fp_126', 'count_fp_160', 'count_fp_167', 'count_fp_173', 'count_fp_174', 'count_fp_216', 'count_fp_219', 'count_fp_231', 'count_fp_235', 'count_fp_269', 'count_fp_296', 'count_fp_310', 'count_fp_340', 'count_fp_358', 'count_fp_362', 'count_fp_369', 'count_fp_458', 'count_fp_476', 'count_fp_638', 'count_fp_654', 'count_fp_684', 'count_fp_798', 'count_fp_807', 'count_fp_811', 'count_fp_857', 'count_fp_870', 'count_fp_875', 'count_fp_881', 'count_fp_893', 'count_fp_914', 'count_fp_919', 'count_fp_926', 'count_fp_950', 'count_fp_957', 'count_fp_958', 'count_fp_963', 'count_fp_979', 'count_fp_998', 'count_fp_999', 'count_fp_1006', 'count_fp_1045', 'count_fp_1060', 'count_fp_1118', 'count_fp_1139', 'count_fp_1208', 'count_fp_1240', 'count_fp_1260', 'count_fp_1274', 'count_fp_1315', 'count_fp_1325', 'count_fp_1345', 'count_fp_1373', 'count_fp_1396', 'count_fp_1421', 'count_fp_1454', 'count_fp_1480', 'count_fp_1495', 'count_fp_1506', 'count_fp_1516', 'count_fp_1527', 'count_fp_1531', 'count_fp_1535', 'count_fp_1562', 'count_fp_1597', 'count_fp_1599', 'count_fp_1607', 'count_fp_1613', 'count_fp_1620', 'count_fp_1662', 'count_fp_1676', 'count_fp_1689', 'count_fp_1693', 'count_fp_1709', 'count_fp_1734', 'count_fp_1739', 'count_fp_1750', 'count_fp_1783', 'count_fp_1840', 'count_fp_1853', 'count_fp_1876', 'count_fp_1879', 'count_fp_1937', 'count_fp_1946', 'count_fp_1949', 'AD2D183', 'AD2D189', 'AD2D492', 'AD2D495', 'AD2D579', 'AD2D638', 'AD2D647', 'AD2D651', 'AD2D657', 'AD2D716', 'APC2D4_N_O', 'APC2D4_F_F', 'APC2D5_N_N', 'APC2D5_O_S', 'APC2D6_N_F', 'APC2D7_N_F', 'APC2D7_N_X', 'APC2D7_O_X', 'APC2D8_C_X', 'APC2D8_N_N', 'APC2D8_N_X', 'APC2D8_O_F', 'APC2D8_O_X', 'APC2D9_C_F', 'APC2D9_O_O', 'APC2D9_O_S', 'APC2D10_C_F', 'APC2D10_N_O', 'APC2D10_N_F', 'APC2D10_N_X', 'ExtFP3', 'ExtFP4', 'ExtFP6', 'ExtFP13', 'ExtFP21', 'ExtFP26', 'ExtFP28', 'ExtFP29', 'ExtFP37', 'ExtFP40', 'ExtFP46', 'ExtFP65', 'ExtFP66', 'ExtFP69', 'ExtFP71', 'ExtFP76', 'ExtFP86', 'ExtFP89', 'ExtFP90', 'ExtFP91', 'ExtFP97', 'ExtFP98', 'ExtFP106', 'ExtFP108', 'ExtFP110', 'ExtFP111', 'ExtFP118', 'ExtFP135', 'ExtFP136', 'ExtFP138', 'ExtFP145', 'ExtFP148', 'ExtFP150', 'ExtFP152', 'ExtFP155', 'ExtFP160', 'ExtFP168', 'ExtFP171', 'ExtFP181', 'ExtFP187', 'ExtFP188', 'ExtFP195', 'ExtFP204', 'ExtFP205', 'ExtFP208', 'ExtFP211', 'ExtFP214', 'ExtFP217', 'ExtFP221', 'ExtFP223', 'ExtFP224', 'ExtFP227', 'ExtFP233', 'ExtFP234', 'ExtFP236', 'ExtFP250', 'ExtFP266', 'ExtFP267', 'ExtFP268', 'ExtFP269', 'ExtFP275', 'ExtFP278', 'ExtFP281', 'ExtFP286', 'ExtFP287', 'ExtFP289', 'ExtFP294', 'ExtFP303', 'ExtFP311', 'ExtFP312', 'ExtFP314', 'ExtFP316', 'ExtFP318', 'ExtFP322', 'ExtFP323', 'ExtFP327', 'ExtFP328', 'ExtFP329', 'ExtFP331', 'ExtFP333', 'ExtFP336', 'ExtFP341', 'ExtFP347', 'ExtFP348', 'ExtFP351', 'ExtFP352', 'ExtFP353', 'ExtFP368', 'ExtFP370', 'ExtFP373', 'ExtFP374', 'ExtFP375', 'ExtFP376', 'ExtFP382', 'ExtFP384', 'ExtFP386', 'ExtFP387', 'ExtFP388', 'ExtFP401', 'ExtFP405', 'ExtFP407', 'ExtFP409', 'ExtFP413', 'ExtFP417', 'ExtFP423', 'ExtFP430', 'ExtFP434', 'ExtFP441', 'ExtFP442', 'ExtFP449', 'ExtFP452', 'ExtFP458', 'ExtFP459', 'ExtFP464', 'ExtFP465', 'ExtFP467', 'ExtFP470', 'ExtFP471', 'ExtFP472', 'ExtFP474', 'ExtFP475', 'ExtFP484', 'ExtFP486', 'ExtFP487', 'ExtFP500', 'ExtFP501', 'ExtFP507', 'ExtFP510', 'ExtFP517', 'ExtFP527', 'ExtFP530', 'ExtFP545', 'ExtFP551', 'ExtFP552', 'ExtFP560', 'ExtFP564', 'ExtFP568', 'ExtFP574', 'ExtFP575', 'ExtFP576', 'ExtFP583', 'ExtFP586', 'ExtFP587', 'ExtFP589', 'ExtFP592', 'ExtFP596', 'ExtFP602', 'ExtFP605', 'ExtFP612', 'ExtFP618', 'ExtFP620', 'ExtFP630', 'ExtFP632', 'ExtFP638', 'ExtFP639', 'ExtFP643', 'ExtFP645', 'ExtFP649', 'ExtFP656', 'ExtFP661', 'ExtFP672', 'ExtFP679', 'ExtFP688', 'ExtFP694', 'ExtFP698', 'ExtFP707', 'ExtFP711', 'ExtFP728', 'ExtFP731', 'ExtFP738', 'ExtFP745', 'ExtFP749', 'ExtFP754', 'ExtFP760', 'ExtFP767', 'ExtFP776', 'ExtFP781', 'ExtFP785', 'ExtFP786', 'ExtFP789', 'ExtFP792', 'ExtFP795', 'ExtFP797', 'ExtFP800', 'ExtFP801', 'ExtFP802', 'ExtFP805', 'ExtFP806', 'ExtFP807', 'ExtFP808', 'ExtFP809', 'ExtFP813', 'ExtFP818', 'ExtFP819', 'ExtFP820', 'ExtFP827', 'ExtFP828', 'ExtFP830', 'ExtFP833', 'ExtFP834', 'ExtFP846', 'ExtFP848', 'ExtFP849', 'ExtFP852', 'ExtFP853', 'ExtFP855', 'ExtFP857', 'ExtFP859', 'ExtFP862', 'ExtFP864', 'ExtFP866', 'ExtFP867', 'ExtFP868', 'ExtFP870', 'ExtFP873', 'ExtFP875', 'ExtFP882', 'ExtFP894', 'ExtFP898', 'ExtFP900', 'ExtFP902', 'ExtFP903', 'ExtFP905', 'ExtFP906', 'ExtFP908', 'ExtFP913', 'ExtFP926', 'ExtFP931', 'ExtFP936', 'ExtFP943', 'ExtFP948', 'ExtFP949', 'ExtFP952', 'ExtFP953', 'ExtFP954', 'ExtFP960', 'ExtFP963', 'ExtFP966', 'ExtFP974', 'ExtFP976', 'ExtFP981', 'ExtFP988', 'ExtFP997', 'ExtFP999', 'ExtFP1012', 'ExtFP1013', 'ExtFP1016', 'ExtFP1017', 'FP5', 'FP10', 'FP13', 'FP14', 'FP16', 'FP21', 'FP25', 'FP26', 'FP30', 'FP31', 'FP36', 'FP43', 'FP44', 'FP47', 'FP49', 'FP50', 'FP56', 'FP60', 'FP63', 'FP66', 'FP70', 'FP71', 'FP75', 'FP76', 'FP77', 'FP80', 'FP84', 'FP89', 'FP91', 'FP97', 'FP98', 'FP114', 'FP121', 'FP127', 'FP137', 'FP142', 'FP146', 'FP157', 'FP164', 'FP170', 'FP171', 'FP173', 'FP184', 'FP193', 'FP197', 'FP200', 'FP215', 'FP216', 'FP218', 'FP220', 'FP225', 'FP227', 'FP230', 'FP234', 'FP244', 'FP247', 'FP249', 'FP251', 'FP265', 'FP266', 'FP268', 'FP274', 'FP275', 'FP276', 'FP278', 'FP284', 'FP286', 'FP292', 'FP302', 'FP305', 'FP310', 'FP311', 'FP316', 'FP321', 'FP324', 'FP331', 'FP334', 'FP337', 'FP340', 'FP341', 'FP342', 'FP343', 'FP344', 'FP345', 'FP352', 'FP354', 'FP355', 'FP363', 'FP376', 'FP379', 'FP389', 'FP390', 'FP413', 'FP415', 'FP416', 'FP422', 'FP425', 'FP427', 'FP430', 'FP431', 'FP442', 'FP444', 'FP448', 'FP454', 'FP459', 'FP461', 'FP463', 'FP464', 'FP466', 'FP473', 'FP475', 'FP483', 'FP488', 'FP489', 'FP493', 'FP497', 'FP498', 'FP500', 'FP509', 'FP525', 'FP531', 'FP535', 'FP539', 'FP546', 'FP547', 'FP548', 'FP553', 'FP560', 'FP563', 'FP564', 'FP566', 'FP569', 'FP571', 'FP576', 'FP582', 'FP583', 'FP600', 'FP601', 'FP614', 'FP618', 'FP619', 'FP620', 'FP622', 'FP623', 'FP624', 'FP633', 'FP634', 'FP635', 'FP636', 'FP646', 'FP659', 'FP664', 'FP691', 'FP692', 'FP708', 'FP720', 'FP726', 'FP728', 'FP735', 'FP737', 'FP738', 'FP748', 'FP757', 'FP762', 'FP764', 'FP765', 'FP766', 'FP773', 'FP777', 'FP808', 'FP809', 'FP810', 'FP811', 'FP815', 'FP819', 'FP820', 'FP822', 'FP831', 'FP833', 'FP836', 'FP837', 'FP839', 'FP841', 'FP849', 'FP852', 'FP855', 'FP862', 'FP870', 'FP876', 'FP879', 'FP893', 'FP904', 'FP908', 'FP911', 'FP915', 'FP919', 'FP920', 'FP922', 'FP933', 'FP935', 'FP944', 'FP950', 'FP952', 'FP958', 'FP959', 'FP961', 'FP963', 'FP967', 'FP969', 'FP970', 'FP973', 'FP977', 'FP980', 'FP982', 'FP984', 'FP994', 'FP998', 'FP1001', 'FP1009', 'FP1011', 'FP1013', 'FP1015', 'FP1016', 'FP1017', 'FP1019', 'FP1022', 'GraphFP6', 'GraphFP23', 'GraphFP44', 'GraphFP47', 'GraphFP59', 'GraphFP64', 'GraphFP73', 'GraphFP83', 'GraphFP124', 'GraphFP130', 'GraphFP170', 'GraphFP175', 'GraphFP214', 'GraphFP241', 'GraphFP251', 'GraphFP255', 'GraphFP259', 'GraphFP264', 'GraphFP268', 'GraphFP270', 'GraphFP303', 'GraphFP305', 'GraphFP311', 'GraphFP320', 'GraphFP335', 'GraphFP363', 'GraphFP380', 'GraphFP404', 'GraphFP411', 'GraphFP427', 'GraphFP443', 'GraphFP455', 'GraphFP465', 'GraphFP487', 'GraphFP499', 'GraphFP500', 'GraphFP522', 'GraphFP523', 'GraphFP534', 'GraphFP551', 'GraphFP553', 'GraphFP563', 'GraphFP586', 'GraphFP632', 'GraphFP641', 'GraphFP714', 'GraphFP723', 'GraphFP744', 'GraphFP754', 'GraphFP765', 'GraphFP768', 'GraphFP772', 'GraphFP777', 'GraphFP790', 'GraphFP808', 'GraphFP817', 'GraphFP833', 'GraphFP834', 'GraphFP836', 'GraphFP837', 'GraphFP850', 'GraphFP852', 'GraphFP882', 'GraphFP894', 'GraphFP899', 'GraphFP905', 'GraphFP909', 'GraphFP910', 'GraphFP911', 'GraphFP913', 'GraphFP914', 'GraphFP920', 'GraphFP926', 'GraphFP929', 'GraphFP937', 'GraphFP940', 'GraphFP965', 'GraphFP983', 'KRFP2', 'KRFP92', 'KRFP98', 'KRFP218', 'KRFP303', 'KRFP314', 'KRFP344', 'KRFP362', 'KRFP363', 'KRFP504', 'KRFP507', 'KRFP555', 'KRFP608', 'KRFP610', 'KRFP648', 'KRFP682', 'KRFP841', 'KRFP842', 'KRFP3058', 'KRFP3393', 'KRFP3659', 'KRFP3662', 'KRFP3734', 'KRFP3753', 'KRFP3764', 'KRFPC2', 'KRFPC14', 'KRFPC98', 'KRFPC297', 'KRFPC299', 'KRFPC302', 'KRFPC303', 'KRFPC309', 'KRFPC314', 'KRFPC346', 'KRFPC401', 'KRFPC421', 'KRFPC435', 'KRFPC466', 'KRFPC467', 'KRFPC504', 'KRFPC506', 'KRFPC508', 'KRFPC555', 'KRFPC608', 'KRFPC610', 'KRFPC697', 'KRFPC707', 'KRFPC840', 'KRFPC842', 'KRFPC848', 'KRFPC1566', 'KRFPC2277', 'KRFPC3058', 'KRFPC3149', 'KRFPC3375', 'KRFPC3660', 'KRFPC3692', 'KRFPC3704', 'KRFPC3726', 'KRFPC3729', 'KRFPC3767', 'KRFPC3778', 'KRFPC3897', 'KRFPC4291', 'MACCSFP53', 'MACCSFP54', 'MACCSFP74', 'MACCSFP82', 'MACCSFP86', 'MACCSFP90', 'MACCSFP91', 'MACCSFP100', 'MACCSFP104', 'MACCSFP105', 'MACCSFP106', 'MACCSFP108', 'MACCSFP115', 'MACCSFP116', 'MACCSFP128', 'MACCSFP129', 'MACCSFP133', 'MACCSFP135', 'MACCSFP138', 'MACCSFP141', 'MACCSFP144', 'MACCSFP149', 'PubchemFP0', 'PubchemFP1', 'PubchemFP13', 'PubchemFP21', 'PubchemFP22', 'PubchemFP38', 'PubchemFP145', 'PubchemFP150', 'PubchemFP157', 'PubchemFP186', 'PubchemFP192', 'PubchemFP193', 'PubchemFP199', 'PubchemFP200', 'PubchemFP206', 'PubchemFP256', 'PubchemFP259', 'PubchemFP261', 'PubchemFP379', 'PubchemFP389', 'PubchemFP596', 'PubchemFP617', 'PubchemFP637', 'PubchemFP697', 'PubchemFP704', 'PubchemFP710', 'SubFPC179', 'SubFPC181', 'x_fine_emb_MFXL0', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL3', 'x_fine_emb_MFXL4', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL6', 'x_fine_emb_MFXL7', 'x_fine_emb_MFXL8', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL10', 'x_fine_emb_MFXL11', 'x_fine_emb_MFXL12', 'x_fine_emb_MFXL13', 'x_fine_emb_MFXL14', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL16', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL18', 'x_fine_emb_MFXL19', 'x_fine_emb_MFXL20', 'x_fine_emb_MFXL21', 'x_fine_emb_MFXL22', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL26', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL29', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL31', 'x_fine_emb_MFXL32', 'x_fine_emb_MFXL33', 'x_fine_emb_MFXL34', 'x_fine_emb_MFXL35', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL37', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL43', 'x_fine_emb_MFXL44', 'x_fine_emb_MFXL45', 'x_fine_emb_MFXL46', 'x_fine_emb_MFXL47', 'x_fine_emb_MFXL48', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL51', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL53', 'x_fine_emb_MFXL54', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL58', 'x_fine_emb_MFXL59', 'x_fine_emb_MFXL60', 'x_fine_emb_MFXL61', 'x_fine_emb_MFXL62', 'x_fine_emb_MFXL63', 'x_fine_emb_MFXL64', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL66', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL68', 'x_fine_emb_MFXL69', 'x_fine_emb_MFXL70', 'x_fine_emb_MFXL71', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL73', 'x_fine_emb_MFXL74', 'x_fine_emb_MFXL75', 'x_fine_emb_MFXL76', 'x_fine_emb_MFXL77', 'x_fine_emb_MFXL78', 'x_fine_emb_MFXL79', 'x_fine_emb_MFXL80', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL83', 'x_fine_emb_MFXL84', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL86', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL88', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL94', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL96', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL98', 'x_fine_emb_MFXL99', 'x_fine_emb_MFXL100', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL102', 'x_fine_emb_MFXL103', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL105', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL107', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL110', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL112', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL116', 'x_fine_emb_MFXL117', 'x_fine_emb_MFXL118', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL120', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL122', 'x_fine_emb_MFXL123', 'x_fine_emb_MFXL124', 'x_fine_emb_MFXL125', 'x_fine_emb_MFXL126', 'x_fine_emb_MFXL127', 'x_fine_emb_MFXL128', 'x_fine_emb_MFXL129', 'x_fine_emb_MFXL130', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL133', 'x_fine_emb_MFXL134', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL137', 'x_fine_emb_MFXL138', 'x_fine_emb_MFXL139', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL142', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL144', 'x_fine_emb_MFXL145', 'x_fine_emb_MFXL146', 'x_fine_emb_MFXL147', 'x_fine_emb_MFXL148', 'x_fine_emb_MFXL149', 'x_fine_emb_MFXL150', 'x_fine_emb_MFXL151', 'x_fine_emb_MFXL152', 'x_fine_emb_MFXL153', 'x_fine_emb_MFXL154', 'x_fine_emb_MFXL155', 'x_fine_emb_MFXL156', 'x_fine_emb_MFXL157', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL160', 'x_fine_emb_MFXL161', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL163', 'x_fine_emb_MFXL164', 'x_fine_emb_MFXL165', 'x_fine_emb_MFXL166', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL168', 'x_fine_emb_MFXL169', 'x_fine_emb_MFXL171', 'x_fine_emb_MFXL172', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL175', 'x_fine_emb_MFXL176', 'x_fine_emb_MFXL177', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL179', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL181', 'x_fine_emb_MFXL182', 'x_fine_emb_MFXL183', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL185', 'x_fine_emb_MFXL186', 'x_fine_emb_MFXL187', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL192', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL194', 'x_fine_emb_MFXL195', 'x_fine_emb_MFXL196', 'x_fine_emb_MFXL197', 'x_fine_emb_MFXL198', 'x_fine_emb_MFXL199', 'x_fine_emb_MFXL200', 'x_fine_emb_MFXL201', 'x_fine_emb_MFXL202', 'x_fine_emb_MFXL203', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL205', 'x_fine_emb_MFXL206', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL208', 'x_fine_emb_MFXL209', 'x_fine_emb_MFXL210', 'x_fine_emb_MFXL211', 'x_fine_emb_MFXL212', 'x_fine_emb_MFXL213', 'x_fine_emb_MFXL214', 'x_fine_emb_MFXL215', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL218', 'x_fine_emb_MFXL219', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL221', 'x_fine_emb_MFXL222', 'x_fine_emb_MFXL223', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL225', 'x_fine_emb_MFXL226', 'x_fine_emb_MFXL227', 'x_fine_emb_MFXL228', 'x_fine_emb_MFXL229', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL231', 'x_fine_emb_MFXL232', 'x_fine_emb_MFXL233', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL236', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL238', 'x_fine_emb_MFXL239', 'x_fine_emb_MFXL240', 'x_fine_emb_MFXL241', 'x_fine_emb_MFXL242', 'x_fine_emb_MFXL243', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL245', 'x_fine_emb_MFXL246', 'x_fine_emb_MFXL247', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL249', 'x_fine_emb_MFXL250', 'x_fine_emb_MFXL251', 'x_fine_emb_MFXL252', 'x_fine_emb_MFXL253', 'x_fine_emb_MFXL254', 'x_fine_emb_MFXL255', 'x_fine_emb_MFXL256', 'x_fine_emb_MFXL257', 'x_fine_emb_MFXL258', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL260', 'x_fine_emb_MFXL261', 'x_fine_emb_MFXL262', 'x_fine_emb_MFXL263', 'x_fine_emb_MFXL264', 'x_fine_emb_MFXL265', 'x_fine_emb_MFXL266', 'x_fine_emb_MFXL267', 'x_fine_emb_MFXL268', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL272', 'x_fine_emb_MFXL273', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL275', 'x_fine_emb_MFXL276', 'x_fine_emb_MFXL277', 'x_fine_emb_MFXL278', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL282', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL284', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL286', 'x_fine_emb_MFXL287', 'x_fine_emb_MFXL288', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL290', 'x_fine_emb_MFXL291

In [5]:
def train_and_test_predict(models, X_train, y_train, X_test, y_test):
    kf = KFold(n_splits=5, shuffle=True, random_state=101)
    results = {}
    predictions = []  

    for model in models:
        model_name = model.__class__.__name__
        predictions_train = []
        actual_y_train = []

        test_predictions_folds = []

        

        for train_index, val_index in kf.split(X_train):
            X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
            y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

            model.fit(X_train_fold, y_train_fold)

            y_pred_fold = model.predict(X_val_fold)
            y_pred_fold = np.clip(y_pred_fold, -10, -3.4)
            predictions_train.extend(y_pred_fold)
            actual_y_train.extend(y_val_fold)

            predictions_test_fold = model.predict(X_test)
            predictions_test_fold = np.clip(predictions_test_fold, -10, -3.4)
            test_predictions_folds.append(predictions_test_fold)


        mse_train = mean_squared_error(actual_y_train, predictions_train)
        mae_train = mean_absolute_error(actual_y_train, predictions_train)
        rmse_train = np.sqrt(mse_train)
        r2_train = r2_score(actual_y_train, predictions_train)
        pearson_train, _ = pearsonr(actual_y_train, predictions_train)
        spearman_train, _ = spearmanr(actual_y_train, predictions_train)


        predictions_test_mean = np.mean(test_predictions_folds, axis=0)
        predictions_test_std = np.std(test_predictions_folds, axis=0)

        mse_test = mean_squared_error(y_test, predictions_test_mean)
        mae_test = mean_absolute_error(y_test, predictions_test_mean)
        rmse_test = np.sqrt(mse_test)
        r2_test = r2_score(y_test, predictions_test_mean)
        print(r2_test)
        pearson_test, _ = pearsonr(y_test, predictions_test_mean)
        spearman_test, _ = spearmanr(y_test, predictions_test_mean)
        
        

        predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_test,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

        results[model_name] = {
            'Train MSE (5 fold cv)': f"{mse_train:.4f}",
            'Train MAE (5 fold cv)': f"{mae_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train R2 (5 fold cv)': f"{r2_train:.4f}",
            'Train PCC (5 fold cv)': f"{pearson_train:.4f}",
            'Train SCC (5 fold cv)': f"{spearman_train:.4f}",
            'Test MSE': f"{mse_test:.4f}",
            'Test MAE': f"{mae_test:.4f}",
            'Test RMSE': f"{rmse_test:.4f}",
            'Test R2': f"{r2_test:.4f}",
            'Test Pearson Correlation': f"{pearson_test:.4f}",
            'Test Spearman Correlation': f"{spearman_test:.4f}",
        }

    results_df = pd.DataFrame(results).T
    predictions_df = pd.DataFrame(predictions)

    return results_df, predictions_df

In [6]:
X_train = train.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test[X_train.columns]
y_test = test['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 1871)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 1871)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.056083 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 248675
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 1647
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.055022 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 248632
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 1643
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.058240 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 248648
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 1642
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.056430 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 248692
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 1656
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.057974 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 248613
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 1636
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.702277096484049
0.6530007661568759
0.7021639465098453
0.6933440586110404
0.6547198646344686
0.7060351075924183
0.7208885074226481
0.014005023740639055
0.7173051101208878
0.7368878681342734
0.18807622392089296

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1493,0.2904,0.3864,0.7670,0.8758,0.8698,0.1855,0.3198,0.4307,0.7023,0.8382,0.7966
DecisionTreeRegressor,0.3054,0.4175,0.5526,0.5235,0.7616,0.7475,0.2162,0.3495,0.4650,0.6530,0.8129,0.7734
RandomForestRegressor,0.1492,0.2936,0.3862,0.7672,0.8768,0.8679,0.1856,0.3249,0.4308,0.7022,0.8384,0.7948
GradientBoostingRegressor,0.1510,0.2936,0.3886,0.7644,0.8743,0.8652,0.1911,0.3273,0.4371,0.6933,0.8330,0.7925
AdaBoostRegressor,0.1609,0.3180,0.4012,0.7489,0.8683,0.8586,0.2151,0.3643,0.4638,0.6547,0.8116,0.7624
XGBRegressor,0.1689,0.3146,0.4110,0.7364,0.8587,0.8520,0.1832,0.3164,0.4280,0.7060,0.8403,0.8024
ExtraTreesRegressor,0.1439,0.2873,0.3793,0.7755,0.8818,0.8757,0.1739,0.3149,0.4170,0.7209,0.8497,0.8136
LinearRegression,1.3241,0.8678,1.1507,-1.0661,0.4775,0.4951,0.6144,0.6193,0.7838,0.0140,0.6071,0.5999
KNeighborsRegressor,0.1901,0.3255,0.4360,0.7035,0.8409,0.8258,0.1761,0.3183,0.4197,0.7173,0.8482,0.8142
SVR,0.1458,0.2926,0.3818,0.7725,0.8796,0.8791,0.1639,0.3096,0.4049,0.7369,0.8610,0.8411
MLPRegressor,0.7170,0.6202,0.8468,-0.1188,0.6494,0.6676,0.5059,0.5150,0.7113,0.1881,0.6882,0.6796

In [7]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_features_caco2.csv')

In [8]:
X = train.drop(columns=['ID', 'SMILES', 'Permeability'])
y = train['Permeability']

rf = RandomForestRegressor(n_estimators=100, random_state=101, n_jobs=-1)
rf.fit(X, y)

importances = rf.feature_importances_
feature_names = X.columns

In [9]:
#Top 10 features
n = 10  
top_10_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_10_features = feature_names[top_10_indices].tolist() 

# Output the list
print("Top", 10, "features:\n")
print(top_10_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_10_features]], axis=1)
test_df = test[train.columns]

Top 10 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s']

In [10]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 10)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 10)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000408 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 10
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000413 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 10
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000417 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 10
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000424 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 10
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000403 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 10
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.6408906301023312
0.574611129351633
0.6467632420336152
0.6502815030169191
0.6094009706870867
0.6238062145537269
0.6586136283305952
0.5904133654577121
0.647880845348226
0.6679746779710605

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.3775978496640814

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1672,0.3140,0.4089,0.7391,0.8600,0.8464,0.2238,0.3586,0.4730,0.6409,0.8025,0.7602
DecisionTreeRegressor,0.2983,0.4145,0.5462,0.5345,0.7734,0.7608,0.2651,0.3934,0.5148,0.5746,0.7652,0.7184
RandomForestRegressor,0.1639,0.3121,0.4048,0.7443,0.8628,0.8490,0.2201,0.3569,0.4692,0.6468,0.8046,0.7588
GradientBoostingRegressor,0.1618,0.3076,0.4023,0.7475,0.8647,0.8514,0.2179,0.3574,0.4668,0.6503,0.8072,0.7601
AdaBoostRegressor,0.1809,0.3361,0.4254,0.7177,0.8504,0.8342,0.2434,0.3944,0.4933,0.6094,0.7842,0.7270
XGBRegressor,0.1879,0.3335,0.4334,0.7068,0.8425,0.8327,0.2344,0.3661,0.4842,0.6238,0.7917,0.7489
ExtraTreesRegressor,0.1658,0.3104,0.4071,0.7414,0.8611,0.8512,0.2127,0.3504,0.4612,0.6586,0.8120,0.7662
LinearRegression,0.1697,0.3262,0.4120,0.7352,0.8574,0.8503,0.2552,0.3969,0.5052,0.5904,0.7708,0.7295
KNeighborsRegressor,0.1903,0.3341,0.4363,0.7030,0.8406,0.8299,0.2194,0.3581,0.4684,0.6479,0.8093,0.7620
SVR,0.1599,0.3039,0.3999,0.7505,0.8665,0.8558,0.2069,0.3423,0.4548,0.6680,0.8179,0.7754
MLPRegressor,0.2857,0.4178,0.5345,0.5543,0.7606,0.7625,0.3878,0.4836,0.6228,0.3776,0.6500,0.6357

In [11]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_10_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_10_features_caco2.csv')

In [12]:
#Top 20 features
n = 20  
top_20_indices = importances.argsort()[::-1][:n]  
top_20_features = feature_names[top_20_indices].tolist()  # convert to list

# Output the list
print("Top", 20, "features:\n")
print(top_20_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_20_features]], axis=1)
test_df = test[train.columns]

Top 20 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL352']

In [13]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 20)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 20)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001105 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 20
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000623 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 20
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000616 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 20
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000632 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 20
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000620 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 20
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.6620041642634948
0.6000557853161069
0.6803858050493776
0.6739476913830451
0.6256699350148556
0.6698851065373622
0.6946496479507454
0.6114723292031525
0.6823010621033619
0.6858924649514994

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.18162550020626778

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1538,0.2987,0.3921,0.7601,0.8719,0.8596,0.2106,0.3476,0.4589,0.6620,0.8150,0.7645
DecisionTreeRegressor,0.2953,0.4086,0.5435,0.5392,0.7680,0.7628,0.2492,0.3724,0.4992,0.6001,0.7790,0.7313
RandomForestRegressor,0.1505,0.2954,0.3880,0.7651,0.8748,0.8639,0.1992,0.3379,0.4463,0.6804,0.8249,0.7744
GradientBoostingRegressor,0.1597,0.3029,0.3996,0.7508,0.8666,0.8546,0.2032,0.3431,0.4507,0.6739,0.8215,0.7686
AdaBoostRegressor,0.1701,0.3245,0.4124,0.7346,0.8603,0.8468,0.2332,0.3780,0.4830,0.6257,0.7941,0.7407
XGBRegressor,0.1730,0.3146,0.4159,0.7301,0.8558,0.8457,0.2057,0.3425,0.4535,0.6699,0.8194,0.7708
ExtraTreesRegressor,0.1516,0.2952,0.3894,0.7634,0.8738,0.8650,0.1903,0.3290,0.4362,0.6946,0.8335,0.7864
LinearRegression,0.1571,0.3100,0.3964,0.7548,0.8688,0.8633,0.2421,0.3791,0.4920,0.6115,0.7849,0.7470
KNeighborsRegressor,0.1850,0.3303,0.4302,0.7113,0.8466,0.8324,0.1980,0.3337,0.4449,0.6823,0.8286,0.7838
SVR,0.1530,0.2955,0.3912,0.7612,0.8728,0.8641,0.1957,0.3344,0.4424,0.6859,0.8291,0.7831
MLPRegressor,0.3952,0.4963,0.6287,0.3833,0.7255,0.7090,0.5099,0.5496,0.7141,0.1816,0.6190,0.5903

In [14]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_20_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_20_features_caco2.csv')

In [15]:
#Top 50 features
n = 50  
top_50_indices = importances.argsort()[::-1][:n] 
top_50_features = feature_names[top_50_indices].tolist()  # convert to list

# Output the list
print("Top", 50, "features:\n")
print(top_50_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_50_features]], axis=1)
test_df = test[train.columns]

Top 50 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL352', 'AATS.4', 'x_fine_emb_MFXL617', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL512', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL533', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL447', 'AATS.23', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL732', 'AtomTypeEState.252', 'TDB8s', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL391', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL510', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL45', 'meanI', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL292', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL634']

In [16]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 50)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 50)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001954 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 50
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001240 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12749
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 50
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001205 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12749
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 50
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001218 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12749
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 50
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001249 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12749
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 50
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.6894266770035757
0.6419690014508836
0.6862232695818655
0.6826139270317431
0.646886542224753
0.6814044173956775
0.7019725033193407
0.6490513708457226
0.7049264006754081
0.7046035630947369

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.25685018099685064

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1524,0.2946,0.3904,0.7622,0.8731,0.8659,0.1935,0.3331,0.4399,0.6894,0.8308,0.7859
DecisionTreeRegressor,0.3012,0.4153,0.5489,0.5300,0.7635,0.7544,0.2231,0.3497,0.4723,0.6420,0.8038,0.7572
RandomForestRegressor,0.1452,0.2921,0.3811,0.7734,0.8797,0.8707,0.1955,0.3339,0.4422,0.6862,0.8284,0.7835
GradientBoostingRegressor,0.1523,0.2930,0.3903,0.7623,0.8731,0.8631,0.1978,0.3401,0.4447,0.6826,0.8266,0.7796
AdaBoostRegressor,0.1595,0.3168,0.3993,0.7512,0.8690,0.8553,0.2200,0.3705,0.4691,0.6469,0.8058,0.7523
XGBRegressor,0.1697,0.3091,0.4120,0.7352,0.8584,0.8510,0.1985,0.3396,0.4456,0.6814,0.8258,0.7828
ExtraTreesRegressor,0.1462,0.2913,0.3823,0.7719,0.8787,0.8720,0.1857,0.3257,0.4309,0.7020,0.8379,0.7921
LinearRegression,0.1509,0.3081,0.3884,0.7646,0.8746,0.8700,0.2187,0.3607,0.4676,0.6491,0.8087,0.7755
KNeighborsRegressor,0.1696,0.3104,0.4119,0.7353,0.8593,0.8487,0.1839,0.3273,0.4288,0.7049,0.8413,0.7939
SVR,0.1469,0.2908,0.3833,0.7708,0.8781,0.8725,0.1841,0.3261,0.4290,0.7046,0.8406,0.8029
MLPRegressor,0.4260,0.5106,0.6527,0.3353,0.7048,0.6981,0.4631,0.5128,0.6805,0.2569,0.6518,0.6414

In [17]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_50_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_50_features_caco2.csv')

In [18]:
#Top 100 features
n = 100  
top_100_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_100_features = feature_names[top_100_indices].tolist()  # convert to list

# Output the list
print("Top", 100, "features:\n")
print(top_100_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_100_features]], axis=1)
test_df = test[train.columns]

Top 100 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL352', 'AATS.4', 'x_fine_emb_MFXL617', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL512', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL533', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL447', 'AATS.23', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL732', 'AtomTypeEState.252', 'TDB8s', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL391', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL510', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL45', 'meanI', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL292', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL634', 'x_fine_emb_MFXL179', 'x_fine_emb_MFXL619', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL731', 'AtomTypeEState.87', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL42', 'maxHBd', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL415', 'ATSC.28', 'x_fine_emb_MFXL706', 'x_fine_emb_MFXL760', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL211', 'x_fine_emb_MFXL287', 'x_fine_emb_MFXL618', 'maxHBint9', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL343', 'x_fine_emb_MFXL185', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL542', 'x_fine_emb_MFXL532', 'TDB5m', 'x_fine_emb_MFXL112', 'MLFER_A', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL597', 'x_fine_emb_MFXL592', 'x_fine_emb_MFXL471', 'x_fine_emb_MFXL669', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL441', 'x_fine_emb_MFXL719', 'AtomTypeEState.173', 'x_fine_emb_MFXL337', 'x_fine_emb_MFXL355', 'x_fine_emb_MFXL678', 'ATSC5c', 'VE3_Dt', 'x_fine_emb_MFXL374', 'AATSC.9', 'x_fine_emb_MFXL473']

In [19]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 100)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 100)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003419 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25330
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 100
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002013 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25332
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 100
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002086 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25334
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 100
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001990 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25330
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 100
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001988 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25332
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 100
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.6950131381944857
0.6444185562071777
0.6934590901336977
0.6978975699030541
0.6484955796367196
0.6910869877200736
0.7045193385487158
0.6578732569439655
0.7077182326577084
0.713399691843458

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.2214725837399104

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1473,0.2892,0.3838,0.7702,0.8776,0.8684,0.1900,0.3253,0.4359,0.6950,0.8339,0.7942
DecisionTreeRegressor,0.2779,0.3997,0.5271,0.5664,0.7769,0.7622,0.2216,0.3474,0.4707,0.6444,0.8050,0.7714
RandomForestRegressor,0.1419,0.2883,0.3767,0.7785,0.8827,0.8722,0.1910,0.3278,0.4370,0.6935,0.8328,0.7889
GradientBoostingRegressor,0.1452,0.2886,0.3810,0.7735,0.8795,0.8688,0.1882,0.3289,0.4339,0.6979,0.8356,0.7946
AdaBoostRegressor,0.1541,0.3116,0.3926,0.7595,0.8740,0.8621,0.2190,0.3682,0.4680,0.6485,0.8070,0.7575
XGBRegressor,0.1623,0.3088,0.4029,0.7467,0.8645,0.8545,0.1925,0.3308,0.4387,0.6911,0.8314,0.7946
ExtraTreesRegressor,0.1426,0.2864,0.3776,0.7775,0.8821,0.8761,0.1841,0.3230,0.4291,0.7045,0.8395,0.7967
LinearRegression,0.1527,0.3088,0.3908,0.7617,0.8736,0.8707,0.2132,0.3511,0.4617,0.6579,0.8146,0.7873
KNeighborsRegressor,0.1732,0.3120,0.4162,0.7297,0.8567,0.8479,0.1821,0.3148,0.4268,0.7077,0.8436,0.8055
SVR,0.1425,0.2877,0.3775,0.7777,0.8819,0.8779,0.1786,0.3167,0.4226,0.7134,0.8454,0.8125
MLPRegressor,0.4189,0.5091,0.6472,0.3464,0.7129,0.7050,0.4851,0.5243,0.6965,0.2215,0.6584,0.6414

In [20]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_100_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_100_features_caco2.csv')

In [21]:
#Top 200 features
n = 200  
top_200_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_200_features = feature_names[top_200_indices].tolist()  # convert to list

# Output the list
print("Top", 200, "features:\n")
print(top_200_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_200_features]], axis=1)
test_df = test[train.columns]

Top 200 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL352', 'AATS.4', 'x_fine_emb_MFXL617', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL512', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL533', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL447', 'AATS.23', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL732', 'AtomTypeEState.252', 'TDB8s', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL391', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL510', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL45', 'meanI', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL292', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL634', 'x_fine_emb_MFXL179', 'x_fine_emb_MFXL619', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL731', 'AtomTypeEState.87', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL42', 'maxHBd', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL415', 'ATSC.28', 'x_fine_emb_MFXL706', 'x_fine_emb_MFXL760', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL211', 'x_fine_emb_MFXL287', 'x_fine_emb_MFXL618', 'maxHBint9', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL343', 'x_fine_emb_MFXL185', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL542', 'x_fine_emb_MFXL532', 'TDB5m', 'x_fine_emb_MFXL112', 'MLFER_A', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL597', 'x_fine_emb_MFXL592', 'x_fine_emb_MFXL471', 'x_fine_emb_MFXL669', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL441', 'x_fine_emb_MFXL719', 'AtomTypeEState.173', 'x_fine_emb_MFXL337', 'x_fine_emb_MFXL355', 'x_fine_emb_MFXL678', 'ATSC5c', 'VE3_Dt', 'x_fine_emb_MFXL374', 'AATSC.9', 'x_fine_emb_MFXL473', 'x_fine_emb_MFXL250', 'x_fine_emb_MFXL255', 'x_fine_emb_MFXL613', 'x_fine_emb_MFXL357', 'x_fine_emb_MFXL302', 'x_fine_emb_MFXL517', 'x_fine_emb_MFXL435', 'x_fine_emb_MFXL231', 'x_fine_emb_MFXL743', 'x_fine_emb_MFXL368', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL679', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL630', 'TDB1i', 'x_fine_emb_MFXL477', 'x_fine_emb_MFXL458', 'x_fine_emb_MFXL598', 'x_fine_emb_MFXL400', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL19', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL442', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL463', 'Dm', 'x_fine_emb_MFXL575', 'x_fine_emb_MFXL426', 'x_fine_emb_MFXL103', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL693', 'x_fine_emb_MFXL764', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL233', 'x_fine_emb_MFXL305', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL635', 'x_fine_emb_MFXL661', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL466', 'x_fine_emb_MFXL728', 'x_fine_emb_MFXL454', 'BCUTp-1l', 'x_fine_emb_MFXL467', 'x_fine_emb_MFXL229', 'x_fine_emb_MFXL356', 'ATSC.5', 'x_fine_emb_MFXL378', 'x_fine_emb_MFXL476', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL142', 'MOMI-XY', 'x_fine_emb_MFXL342', 'minHBint4', 'x_fine_emb_MFXL159', 'TDB3i', 'TDB6s', 'x_fine_emb_MFXL554', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL121', 'ATSC.13', 'x_fine_emb_MFXL714', 'x_fine_emb_MFXL84', 'x_fine_emb_MFXL740', 'x_fine_emb_MFXL518', 'x_fine_emb_MFXL376', '3d_rdkit_10', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL32', 'x_fine_emb_MFXL290', 'x_fine_emb_MFXL500', 'x_fine_emb_MFXL113', 'Dv', 'x_fine_emb_MFXL673', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL240', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL614', 'TDB7e', 'x_fine_emb_MFXL214', 'x_fine_emb_MFXL470', 'x_fine_emb_MFXL15', 'SHBd', 'x_fine_emb_MFXL649', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL741', 'x_fine_emb_MFXL489', 'ATSC.16', 'x_fine_emb_MFXL169', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL520', 'x_fine_emb_MFXL164', 'x_fine_emb_MFXL707', 'SHBint9']

In [22]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 200)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 200)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006840 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50830
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 200
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.072256 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50832
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 200
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003722 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50834
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 200
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003752 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50830
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 200
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004345 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50832
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 200
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.6973454759231166
0.6249157151212643
0.6962371576406182
0.6947534619652891
0.6486282478436585
0.683836276245968
0.7075842028768957
0.640505567435973
0.6881483416985203
0.7217242196178851

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.20940397623399531

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1451,0.2876,0.3809,0.7736,0.8795,0.8718,0.1886,0.3217,0.4343,0.6973,0.8354,0.7928
DecisionTreeRegressor,0.2877,0.3929,0.5364,0.5511,0.7723,0.7614,0.2337,0.3685,0.4834,0.6249,0.7941,0.7607
RandomForestRegressor,0.1423,0.2869,0.3772,0.7780,0.8826,0.8731,0.1893,0.3273,0.4351,0.6962,0.8345,0.7911
GradientBoostingRegressor,0.1464,0.2883,0.3827,0.7715,0.8784,0.8682,0.1902,0.3253,0.4361,0.6948,0.8340,0.7905
AdaBoostRegressor,0.1581,0.3136,0.3977,0.7533,0.8704,0.8601,0.2189,0.3653,0.4679,0.6486,0.8067,0.7583
XGBRegressor,0.1645,0.3085,0.4056,0.7433,0.8627,0.8542,0.1970,0.3326,0.4439,0.6838,0.8270,0.7886
ExtraTreesRegressor,0.1417,0.2859,0.3765,0.7788,0.8832,0.8762,0.1822,0.3186,0.4269,0.7076,0.8414,0.8007
LinearRegression,0.1682,0.3232,0.4101,0.7376,0.8614,0.8590,0.2240,0.3680,0.4733,0.6405,0.8077,0.7803
KNeighborsRegressor,0.1815,0.3239,0.4260,0.7168,0.8487,0.8372,0.1943,0.3216,0.4408,0.6881,0.8324,0.7910
SVR,0.1419,0.2863,0.3766,0.7787,0.8825,0.8815,0.1734,0.3127,0.4164,0.7217,0.8504,0.8194
MLPRegressor,0.3659,0.4727,0.6049,0.4290,0.7653,0.7586,0.4926,0.5125,0.7019,0.2094,0.6806,0.6564

In [23]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_200_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_200_features_caco2.csv')

In [24]:
#Top 500 features
n = 500  
top_500_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_500_features = feature_names[top_500_indices].tolist()  # convert to list

# Output the list
print("Top", 500, "features:\n")
print(top_500_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_500_features]], axis=1)
test_df = test[train.columns]

Top 500 features:

['x_fine_emb_MFXL33', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL495', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL632', 'TDB9s', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL279', 'x_fine_emb_MFXL352', 'AATS.4', 'x_fine_emb_MFXL617', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL512', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL533', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL447', 'AATS.23', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL732', 'AtomTypeEState.252', 'TDB8s', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL391', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL510', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL45', 'meanI', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL292', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL634', 'x_fine_emb_MFXL179', 'x_fine_emb_MFXL619', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL731', 'AtomTypeEState.87', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL42', 'maxHBd', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL415', 'ATSC.28', 'x_fine_emb_MFXL706', 'x_fine_emb_MFXL760', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL211', 'x_fine_emb_MFXL287', 'x_fine_emb_MFXL618', 'maxHBint9', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL343', 'x_fine_emb_MFXL185', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL542', 'x_fine_emb_MFXL532', 'TDB5m', 'x_fine_emb_MFXL112', 'MLFER_A', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL597', 'x_fine_emb_MFXL592', 'x_fine_emb_MFXL471', 'x_fine_emb_MFXL669', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL441', 'x_fine_emb_MFXL719', 'AtomTypeEState.173', 'x_fine_emb_MFXL337', 'x_fine_emb_MFXL355', 'x_fine_emb_MFXL678', 'ATSC5c', 'VE3_Dt', 'x_fine_emb_MFXL374', 'AATSC.9', 'x_fine_emb_MFXL473', 'x_fine_emb_MFXL250', 'x_fine_emb_MFXL255', 'x_fine_emb_MFXL613', 'x_fine_emb_MFXL357', 'x_fine_emb_MFXL302', 'x_fine_emb_MFXL517', 'x_fine_emb_MFXL435', 'x_fine_emb_MFXL231', 'x_fine_emb_MFXL743', 'x_fine_emb_MFXL368', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL679', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL630', 'TDB1i', 'x_fine_emb_MFXL477', 'x_fine_emb_MFXL458', 'x_fine_emb_MFXL598', 'x_fine_emb_MFXL400', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL19', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL442', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL463', 'Dm', 'x_fine_emb_MFXL575', 'x_fine_emb_MFXL426', 'x_fine_emb_MFXL103', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL693', 'x_fine_emb_MFXL764', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL233', 'x_fine_emb_MFXL305', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL635', 'x_fine_emb_MFXL661', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL466', 'x_fine_emb_MFXL728', 'x_fine_emb_MFXL454', 'BCUTp-1l', 'x_fine_emb_MFXL467', 'x_fine_emb_MFXL229', 'x_fine_emb_MFXL356', 'ATSC.5', 'x_fine_emb_MFXL378', 'x_fine_emb_MFXL476', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL142', 'MOMI-XY', 'x_fine_emb_MFXL342', 'minHBint4', 'x_fine_emb_MFXL159', 'TDB3i', 'TDB6s', 'x_fine_emb_MFXL554', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL121', 'ATSC.13', 'x_fine_emb_MFXL714', 'x_fine_emb_MFXL84', 'x_fine_emb_MFXL740', 'x_fine_emb_MFXL518', 'x_fine_emb_MFXL376', '3d_rdkit_10', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL32', 'x_fine_emb_MFXL290', 'x_fine_emb_MFXL500', 'x_fine_emb_MFXL113', 'Dv', 'x_fine_emb_MFXL673', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL240', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL614', 'TDB7e', 'x_fine_emb_MFXL214', 'x_fine_emb_MFXL470', 'x_fine_emb_MFXL15', 'SHBd', 'x_fine_emb_MFXL649', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL741', 'x_fine_emb_MFXL489', 'ATSC.16', 'x_fine_emb_MFXL169', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL520', 'x_fine_emb_MFXL164', 'x_fine_emb_MFXL707', 'SHBint9', 'SHBint4', 'x_fine_emb_MFXL724', 'x_fine_emb_MFXL659', 'x_fine_emb_MFXL239', 'x_fine_emb_MFXL16', 'x_fine_emb_MFXL46', 'ATSC6i', 'x_fine_emb_MFXL407', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL419', 'AATSC.47', 'minHBint10', 'x_fine_emb_MFXL682', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL60', 'x_fine_emb_MFXL763', 'minHBint8', 'GATS6c', 'x_fine_emb_MFXL580', 'x_fine_emb_MFXL675', 'x_fine_emb_MFXL622', 'x_fine_emb_MFXL751', 'x_fine_emb_MFXL665', 'x_fine_emb_MFXL438', 'TDB7i', 'x_fine_emb_MFXL371', 'x_fine_emb_MFXL14', 'SHBint3', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL636', 'x_fine_emb_MFXL698', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL456', 'x_fine_emb_MFXL650', 'VE3_Dzm', 'x_fine_emb_MFXL171', 'x_fine_emb_MFXL624', 'qed', 'x_fine_emb_MFXL257', 'x_fine_emb_MFXL354', 'x_fine_emb_MFXL384', 'ATSC.26', 'x_fine_emb_MFXL294', 'AATSC.35', 'x_fine_emb_MFXL165', 'x_fine_emb_MFXL351', 'x_fine_emb_MFXL413', 'x_fine_emb_MFXL38', 'L3p', 'x_fine_emb_MFXL80', 'ATSC.43', 'x_fine_emb_MFXL497', 'x_fine_emb_MFXL474', 'LOBMIN', 'x_fine_emb_MFXL320', 'x_fine_emb_MFXL696', 'x_fine_emb_MFXL278', 'x_fine_emb_MFXL385', 'x_fine_emb_MFXL735', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL63', 'x_fine_emb_MFXL254', 'x_fine_emb_MFXL739', 'x_fine_emb_MFXL716', 'x_fine_emb_MFXL12', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL468', 'x_fine_emb_MFXL398', 'x_fine_emb_MFXL526', 'x_fine_emb_MFXL537', 'x_fine_emb_MFXL372', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL308', 'x_fine_emb_MFXL708', 'GATS.7', 'x_fine_emb_MFXL192', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL223', 'x_fine_emb_MFXL480', 'ModifiedIC.5', 'x_fine_emb_MFXL172', 'x_fine_emb_MFXL182', 'AdjacencyMatrix.9', 'x_fine_emb_MFXL129', 'ATSC.24', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL541', 'x_fine_emb_MFXL363', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL232', 'x_fine_emb_MFXL199', 'x_fine_emb_MFXL723', 'maxHBint8', 'x_fine_emb_MFXL503', 'GATS.1', 'x_fine_emb_MFXL715', 'x_fine_emb_MFXL560', 'x_fine_emb_MFXL174', 'minsCH3', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL249', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL76', 'x_fine_emb_MFXL395', 'x_fine_emb_MFXL202', 'x_fine_emb_MFXL70', 'x_fine_emb_MFXL460', 'x_fine_emb_MFXL194', 'ATSC.34', 'x_fine_emb_MFXL318', 'x_fine_emb_MFXL551', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL222', 'x_fine_emb_MFXL494', 'x_fine_emb_MFXL344', 'maxHBint6', 'VR1_Dt', 'x_fine_emb_MFXL574', 'x_fine_emb_MFXL43', 'x_fine_emb_MFXL633', 'x_fine_emb_MFXL263', 'x_fine_emb_MFXL529', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL265', 'ATSC.23', 'x_fine_emb_MFXL62', 'x_fine_emb_MFXL405', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL414', 'x_fine_emb_MFXL282', 'x_fine_emb_MFXL314', 'minHBa', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL657', 'x_fine_emb_MFXL552', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL58', 'x_fine_emb_MFXL729', 'x_fine_emb_MFXL127', 'x_fine_emb_MFXL319', 'x_fine_emb_MFXL7', 'x_fine_emb_MFXL519', 'x_fine_emb_MFXL51', 'x_fine_emb_MFXL508', 'x_fine_emb_MFXL330', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL219', 'x_fine_emb_MFXL295', 'x_fine_emb_MFXL358', 'GATS.6', 'R_TpiPCTPC', 'TDB2i', 'SpMax1_Bhm', 'ATSC.64', 'x_fine_emb_MFXL277', 'x_fine_emb_MFXL652', 'x_fine_emb_MFXL288', 'x_fine_emb_MFXL98', 'ATSC.8', 'x_fine_emb_MFXL404', 'x_fine_emb_MFXL261', 'x_fine_emb_MFXL13', 'x_fine_emb_MFXL275', 'x_fine_emb_MFXL491', 'x_fine_emb_MFXL409', 'x_fine_emb_MFXL701', 'geomShape', 'x_fine_emb_MFXL245', 'x_fine_emb_MFXL609', 'x_fine_emb_MFXL394', 'x_fine_emb_MFXL572', 'x_fine_emb_MFXL276', 'x_fine_emb_MFXL340', 'x_fine_emb_MFXL727', 'x_fine_emb_MFXL676', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL267', 'mindO', 'x_fine_emb_MFXL653', 'x_fine_emb_MFXL457', 'x_fine_emb_MFXL547', 'x_fine_emb_MFXL521', 'x_fine_emb_MFXL304', 'AATSC.37', 'x_fine_emb_MFXL543', 'x_fine_emb_MFXL607', 'VR1_Dzs', 'x_fine_emb_MFXL553', 'x_fine_emb_MFXL349', 'x_fine_emb_MFXL298', 'AATSC.15', 'minssNH', 'x_fine_emb_MFXL702', 'x_fine_emb_MFXL568', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL623', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL513', 'BCUT.7', 'x_fine_emb_MFXL210', 'x_fine_emb_MFXL762', 'SHBint10', 'x_fine_emb_MFXL348', 'x_fine_emb_MFXL530', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL176', 'x_fine_emb_MFXL323', 'x_fine_emb_MFXL565', 'GATS.3', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL545', 'x_fine_emb_MFXL584', 'x_fine_emb_MFXL175', 'TDB3e', 'TDB6i', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL83', 'x_fine_emb_MFXL29', 'x_fine_emb_MFXL65', 'ATSC.53', 'x_fine_emb_MFXL747', 'x_fine_emb_MFXL525', 'x_fine_emb_MFXL364', 'AATSC5s', 'x_fine_emb_MFXL493', 'TDB8e', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL325', 'AATSC3v', 'FpDensityMorgan1', 'ATSC.22', 'x_fine_emb_MFXL242', 'TDB9m', 'TDB10e', 'ATSC.17', 'x_fine_emb_MFXL326', 'x_fine_emb_MFXL390', 'x_fine_emb_MFXL272', 'x_fine_emb_MFXL585', 'x_fine_emb_MFXL3', 'x_fine_emb_MFXL311', 'x_fine_emb_MFXL562', 'ATSC3m', 'x_fine_emb_MFXL453', 'x_fine_emb_MFXL688', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL420', 'x_fine_emb_MFXL498', 'x_fine_emb_MFXL203', 'x_fine_emb_MFXL684', 'AATSC.16', 'x_fine_emb_MFXL247', 'x_fine_emb_MFXL421', 'AATSC.53', 'minHBint9', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL148', 'GATS.13', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL694', 'x_fine_emb_MFXL197', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL445', 'TDB5i', 'maxHsOH', 'x_fine_emb_MFXL511', 'MOMI-YZ', 'TDB10u', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL654', 'x_fine_emb_MFXL66', 'x_fine_emb_MFXL296', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL431', 'x_fine_emb_MFXL329', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL126', 'x_fine_emb_MFXL713', 'TDB1s', 'minsssN', 'x_fine_emb_MFXL564', 'x_fine_emb_MFXL566', 'VR1_Dzm', 'x_fine_emb_MFXL725', 'x_fine_emb_MFXL755', 'ATSC8e', 'ATSC.25', 'x_fine_emb_MFXL200', 'x_fine_emb_MFXL733', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL753', 'x_fine_emb_MFXL745', 'x_fine_emb_MFXL228']

In [25]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (1007, 500)
y_train shape:  (1007,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (252, 500)
y_test shape:  (252,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010584 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127316
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 500
[LightGBM] [Info] Start training from score -6.187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009087 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127319
[LightGBM] [Info] Number of data points in the train set: 805, number of used features: 500
[LightGBM] [Info] Start training from score -6.199749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009234 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127321
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 500
[LightGBM] [Info] Start training from score -6.194212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010410 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127319
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 500
[LightGBM] [Info] Start training from score -6.189756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009698 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127315
[LightGBM] [Info] Number of data points in the train set: 806, number of used features: 500
[LightGBM] [Info] Start training from score -6.173113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
0.7098067724917203
0.6675637389314792
0.6971611559656798
0.6940891670305577
0.6499116133752285
0.6979281593934141
0.7142937967756158
0.46935648294325405
0.7003309125712935
0.7205585668130953
0.3525869998668202

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1476,0.2908,0.3842,0.7697,0.8774,0.8692,0.1808,0.3174,0.4252,0.7098,0.8427,0.8022
DecisionTreeRegressor,0.3135,0.4223,0.5599,0.5108,0.7525,0.7379,0.2071,0.3504,0.4551,0.6676,0.8194,0.7812
RandomForestRegressor,0.1454,0.2901,0.3813,0.7731,0.8801,0.8713,0.1887,0.3285,0.4344,0.6972,0.8352,0.7928
GradientBoostingRegressor,0.1470,0.2896,0.3834,0.7706,0.8778,0.8697,0.1906,0.3254,0.4366,0.6941,0.8335,0.7924
AdaBoostRegressor,0.1601,0.3158,0.4001,0.7502,0.8688,0.8558,0.2181,0.3660,0.4671,0.6499,0.8083,0.7604
XGBRegressor,0.1718,0.3145,0.4145,0.7319,0.8560,0.8486,0.1882,0.3252,0.4338,0.6979,0.8354,0.8007
ExtraTreesRegressor,0.1453,0.2895,0.3812,0.7733,0.8803,0.8736,0.1780,0.3145,0.4219,0.7143,0.8455,0.8037
LinearRegression,0.4130,0.4749,0.6426,0.3556,0.7127,0.7226,0.3306,0.4563,0.5750,0.4694,0.7373,0.6901
KNeighborsRegressor,0.1906,0.3279,0.4366,0.7026,0.8409,0.8290,0.1867,0.3182,0.4321,0.7003,0.8386,0.8003
SVR,0.1451,0.2922,0.3809,0.7736,0.8797,0.8792,0.1741,0.3169,0.4173,0.7206,0.8500,0.8195
MLPRegressor,0.5161,0.5584,0.7184,0.1946,0.6457,0.6335,0.4034,0.4916,0.6351,0.3526,0.6871,0.6558

In [26]:
result_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/combined_top_500_features_caco2.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/Caco2/results/combined_features/prediction_combined_top_500_features_caco2.csv')