In [1]:
#Monomeric features
import pandas as pd
import numpy as np
import ast

In [2]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,"['Me_Bal', 'meF', 'meL', 'meA', 'meF', 'I', 'm...",1664.156
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,"['dA', 'T', 'meF', 'I', 'meA', 'meL', 'meF', '...",1650.129
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,"['dL', 'Me_Phe(3-Cl)', 'L', 'meL', 'T', 'Bu_Gl...",1587.863
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,"['Me_dA', 'meA', 'meF', 'T', 'meA', 'meL', 'I'...",1574.031
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,"['Bu_Gly', 'Me_Phe(3-Cl)', 'Gln(Mes)', 'meL', ...",1567.445
...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,"['Sar', 'L', 'F', '5-Ava']",430.549
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,"['A', 'L', 'F', '5-Ava']",430.549
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,"['A', 'L', 'Mono76']",402.539
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,"['A', 'L', 'Mono75']",388.512
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,"['A', 'L', 'H2NEt_Phe']",374.485

In [3]:
df_train = df_train[['ID','SMILES','Sequence','Permeability']]
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)

In [4]:
symbol_list = []

with open('/home/users/akshay/PCPpred/Caco2/data/monomer_list.txt', 'r') as file:
    for line in file:
        symbol_list.append(line.strip())
print(symbol_list)
print(len(symbol_list))

['A', 'dA', 'meA', 'Me_dA', 'Ala(tBu)', 'Ala(indol-2-yl)', 'dAla(indol-2-yl)', 'Me_Ala(indol-2-yl)', 'Ala(5-Tet)', 'Abu', 'dAbu', 'Me_Abu', 'Me_dAbu', 'Me_Abu(morpholino)', '2Abz', 'Aib', 'Aoc(2)', '5-Ava', 'Bal', 'Me_Bal', 'HOCOCH2_Bal', 'Cys(EtO2H)_NH2', 'Cha', 'dCha', 'Me_Cha', 'D', 'meD', 'Asp_piperidide', 'Asp(OMe)', 'Asp(Ph(2-NH2))', 'dAsp(pyrrol-1-yl)', 'E', 'Glu_NH2', 'Glu(3R-Me)', 'Glu(OMe)', 'dGlu(OMe)', 'F', 'dF', 'meF', 'Me_dF', 'Phe(4-F)', 'dPhe(4-F)', 'Phe(4-CF3)', 'Phe(4-NO2)', 'Phe(CHF2)', 'dPhe(3,4-diF)', 'Et_Phe', 'H2NEt_Phe', 'Me_Phe(3-Cl)', 'Me_Phe(4-Cl)', 'Me_Phe(a,b-dehydro)', 'G', 'Bn_Gly', 'Bn(4-Cl)_Gly', 'Bn(4-OH)_Gly', 'Bu_Gly', 'iBu_Gly', 'Et_Gly', 'EtOEt_Gly', 'HOCOCH2_Gly_ol', 'MeOEt_Gly', 'NH2Bu_Gly', 'Pr_Gly', 'PhEt_Gly', 'PhPr_Gly', 'cHexCH2_Gly', 'isoamyl_Gly', 'pentyl_Gly', '3-pyridylethyl_Gly', '2-pyridylmethyl_Gly', 'd(N->O)Gly(allyl)', 'GABA', 'H', 'Hph', 'Me_Hph', 'bHph', 'Hph(2-Cl)', 'Hph(3-Cl)', 'Hph(4-Cl)', 'Hse(Et)', 'dHyp', 'Hyp(Et)', 'I', 'dI', 'meI', 'Me_dI', '(N->O)xiIle', 'd(N->O)aIle', 'K', 'dK', 'meK', 'Me_dK', 'Lys(Ac)', 'Lys(Cbz)', 'Lys(iPr)', 'Lys(Me)', 'Me_Lys(Me)', 'Lys(Me2)', 'Lys(Tfa)', 'L', 'dL', 'meL', 'Me_dL', 'aMeLeu', 'dLeu(3R-OH)', '(N->O)Leu', 'd(N->O)Leu', 'M', 'meM', 'Met(O2)', 'N', 'dN', 'meN', 'dAsn(Me2)', 'Nal', '1-Nal', 'd1-Nal', 'Nle', 'Me_Nle', 'Me_dNle', 'Nle(CHF2)', 'Nle(OH)', 'Nva', 'dNva', 'Me_Nva', 'Me_dNva', 'Nva(Ph)', 'Orn', 'P', 'dP', '3Pal', '4Pal', 'Phg', 'Pip', 'dPip', 'Pye', 'dPye', 'Q', 'meQ', 'Gln(Me)', 'Gln(Me2)', 'dGln(Me2)', 'Gln(Mes)', 'R', 'dR', 'Arg(Me,Me)', 'S', 'dS', 'meS', 'Ser(Ac)', 'Ser(Bn)', 'Ser(EtNMe2)', 'Ser(EtOH)', 'Ser(isoamyl)', 'Ser(Me)', 'dSer(Me)', 'Ser(Ph(2-Cl))', 'Ser(Ph(3-Cl))', 'Ser(Pr)', 'Ser(tBu)', 'Me_Ser(isoamyl)', 'Me_Ser(Pr)', 'Sar', 'Sta', 'Sta(3R,4R)', 'T', 'dT', 'meT', 'Me_Bmt(E)', 'Tle', 'Tza', 'Me_Tza', 'V', 'dV', 'meV', 'Me_dV', '(N->O)Val', 'd(N->O)Val', '(N->O)Val(3-OH)', 'W', 'meW', 'Me_dW', 'Trp(5-Br)', 'Trp(6-Br)', 'Trp(7-Br)', 'Y', 'dY', 'meY', 'Me_dY', 'Tyr(3-F)', 'Tyr(CHF2)', 'Tyr(Me)', 'Me_Tyr(Me)', 'dTyr(bR-OMe)', '(N->O)Tyr', 'Mono1', 'Mono2', 'Mono3', 'Mono4', 'Mono5', 'Mono6', 'Bal(3-Me)', 'Bal(d3-CF3)', 'Mono9', 'Mono10', 'Mono11', 'Mono12', 'Mono13', 'Mono14', 'Mono15', 'Mono16', 'Mono17', 'Mono18', 'Mono19', 'Mono20', 'Mono23', 'Mono24', 'Mono25', 'Mono26', 'Mono27', 'Mono28', 'Mono29', 'Mono30', 'Mono31', 'Mono32', 'Mono33', 'Mono34', 'Mono35', 'Mono36', 'Mono37', 'Mono38', 'Mono39', 'Mono40', 'Mono41', 'Mono42', 'Mono43', 'Mono44', 'Mono45', 'Mono46', 'Mono47', 'Mono48', 'Mono49', 'Mono50', 'Mono51', 'Mono52', 'Mono53', 'Mono54', 'Mono55', 'Mono56', 'Mono57', 'Mono58', 'Mono59', 'Mono60', 'Mono61', 'Mono62', 'Mono63', 'Mono64', 'Mono65', 'Mono66', 'Mono67', 'Mono68', 'Mono69', 'Mono70', 'Mono71', 'Mono72', 'Mono73', 'Mono74', 'Mono75', 'Mono76', 'Mono77', 'Mono78', 'Mono79', 'Mono80', 'Mono81', 'Mono82', 'Mono83', 'Mono84', 'Mono85', 'Mono86', 'Mono87', 'Mono88', 'Mono89', 'Mono90', 'Mono91', 'Mono92', 'Mono93', 'Mono94', 'Mono95', 'Mono96', 'Mono97', 'Mono98', 'Mono99', 'Mono100', 'Mono101', 'Mono102', 'Mono103', 'Mono104', 'Mono105', 'Mono106', 'Mono107', 'Mono108', 'Mono109', 'Mono110', 'Mono111', 'Mono112', 'ac-', 'deca-', 'glyco-', 'medl-', '-pip', 'Mono21-', 'Mono22-', 'dW', 'Ala(O->S)', 'dAla(O->S)', 'Phe(O->S)', 'Ile(O->S)', 'Lys(O->S)', 'Leu(O->S)', 'dLeu(O->S)', 'Pro(O->S)', 'dPro(O->S)', 'Thr(O->S)', 'dTrp(O->S)', 'Tyr(O->S)', 'Ac3c', 'Abu(5-Tet)', 'Gly(allyl)', '-pyrro', 'Aze', 'Bal(d3-Me)', 'Me_Bal(d3-Me)', 'Bal(d3-EtPh)', 'meH', 'Phe(3-Cl)', 'Phe(3-F)', 'Phe(4-Cl)', 'Mono113', 'Ser(tBuOH)', 'Val(3-OH)', 'Mono114', 'Ac5c', 'Hph(4-CF3,3,5-diF)', 'Hph(4-Me)', 'Phe(3,5-diCl)', 'Hph(4-CF3,3-Cl)', 'Me_Phe(4-Me)', 'Hph(4-tBu)', 'Hph(3,4-diCl)', 'Hch', 'Phe(3-Cl,5-F)', 'Me_Gly(cPent)', 'Phe(3-CF3)', 'Et_Phe(4-Me)', 'Hph(4-CF3)', '-nme2', 'Mono115', 'Chg', 'Me_Chg', 'Et_Leu', 'Me_Ser(Me)', 'Me_Hse(Me)', 'Gly(cPr)', 'Me_Gly(cPr)', 'Gly(cBu)', 'Me_Gly(cBu)', 'Gly(cPent)', 'Ala(cPr)', 'Ala(cBu)', 'Ala(cPent)', 'Me_Nva(F2)', '-mor', '-aze', 'Mono116', 'Mono117', 'Mono118', 'Mono119', 'Mono120', 'Mono121', 'Mono122', 'Mono123', 'Mono124', 'Mono125', 'Mono126', 'Mono127']
385

In [5]:
def calculate_monomer_composition(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [6]:
df_train_mc = calculate_monomer_composition(df_train, symbol_list)
df_train_mc.shape

(1007, 388)

In [7]:
df_train_mc

,ID,SMILES,Permeability,A,dA,meA,Me_dA,Ala(tBu),Ala(indol-2-yl),dAla(indol-2-yl),...,Mono118,Mono119,Mono120,Mono121,Mono122,Mono123,Mono124,Mono125,Mono126,Mono127
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0.071429,0.000000,0.071429,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0.071429,0.071429,0.071429,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0.071429,0.000000,0.142857,0.071429,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0.250000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_train_mc.to_csv("/home/users/akshay/PCPpred/Caco2/features/Monomeric/Train_mon_comp_caco2.csv", index=False)

In [9]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')

df_test = df_test[['ID','SMILES','Sequence','Permeability']]
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)

df_test_mc = calculate_monomer_composition(df_test, symbol_list)
df_test_mc.shape

df_test_mc.to_csv("/home/users/akshay/PCPpred/Caco2/features/Monomeric/Test_mon_comp_Caco2.csv", index=False)
df_test_mc

,ID,SMILES,Permeability,A,dA,meA,Me_dA,Ala(tBu),Ala(indol-2-yl),dAla(indol-2-yl),...,Mono118,Mono119,Mono120,Mono121,Mono122,Mono123,Mono124,Mono125,Mono126,Mono127
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.071429,0.000000,0.142857,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.000000,0.000000,0.000000,0.083333,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.000000,0.090909,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.333333,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
#Amino acid composition 20 natural and X as non natural amino acids

In [11]:
mono = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/CycPeptMPDB_Monomer_All.csv')
mono = mono[['Symbol','Natural_Analog']]
mono_dict = mono.set_index('Symbol')['Natural_Analog'].to_dict()
mono_dict

{'A': 'A',
 'dA': 'A',
 'meA': 'A',
 'Me_dA': 'A',
 'Ala(tBu)': 'A',
 'Ala(indol-2-yl)': 'A',
 'dAla(indol-2-yl)': 'A',
 'Me_Ala(indol-2-yl)': 'A',
 'Ala(5-Tet)': 'A',
 'Abu': 'X',
 'dAbu': 'X',
 'Me_Abu': 'X',
 'Me_dAbu': 'X',
 'Me_Abu(morpholino)': 'X',
 '2Abz': 'X',
 'Aib': 'X',
 'Aoc(2)': 'L',
 '5-Ava': 'X',
 'Bal': 'A',
 'Me_Bal': 'A',
 'HOCOCH2_Bal': 'A',
 'Cys(EtO2H)_NH2': 'C',
 'Cha': 'A',
 'dCha': 'A',
 'Me_Cha': 'A',
 'D': 'D',
 'meD': 'D',
 'Asp_piperidide': 'D',
 'Asp(OMe)': 'D',
 'Asp(Ph(2-NH2))': 'D',
 'dAsp(pyrrol-1-yl)': 'D',
 'E': 'E',
 'Glu_NH2': 'E',
 'Glu(3R-Me)': 'E',
 'Glu(OMe)': 'E',
 'dGlu(OMe)': 'E',
 'F': 'F',
 'dF': 'F',
 'meF': 'F',
 'Me_dF': 'F',
 'Phe(4-F)': 'F',
 'dPhe(4-F)': 'F',
 'Phe(4-CF3)': 'F',
 'Phe(4-NO2)': 'F',
 'Phe(CHF2)': 'F',
 'dPhe(3,4-diF)': 'F',
 'Et_Phe': 'F',
 'H2NEt_Phe': 'F',
 'Me_Phe(3-Cl)': 'F',
 'Me_Phe(4-Cl)': 'F',
 'Me_Phe(a,b-dehydro)': 'F',
 'G': 'G',
 'Bn_Gly': 'G',
 'Bn(4-Cl)_Gly': 'G',
 'Bn(4-OH)_Gly': 'G',
 'Bu_Gly': 'G',
 'iBu_Gly': 'G',
 'Et_Gly': 'G',
 'EtOEt_Gly': 'G',
 'HOCOCH2_Gly_ol': 'G',
 'MeOEt_Gly': 'G',
 'NH2Bu_Gly': 'G',
 'Pr_Gly': 'G',
 'PhEt_Gly': 'G',
 'PhPr_Gly': 'G',
 'cHexCH2_Gly': 'G',
 'isoamyl_Gly': 'G',
 'pentyl_Gly': 'G',
 '3-pyridylethyl_Gly': 'G',
 '2-pyridylmethyl_Gly': 'G',
 'd(N->O)Gly(allyl)': 'G',
 'GABA': 'X',
 'H': 'H',
 'Hph': 'F',
 'Me_Hph': 'F',
 'bHph': 'F',
 'Hph(2-Cl)': 'F',
 'Hph(3-Cl)': 'F',
 'Hph(4-Cl)': 'F',
 'Hse(Et)': 'S',
 'dHyp': 'P',
 'Hyp(Et)': 'P',
 'I': 'I',
 'dI': 'I',
 'meI': 'I',
 'Me_dI': 'I',
 '(N->O)xiIle': 'I',
 'd(N->O)aIle': 'I',
 'K': 'K',
 'dK': 'K',
 'meK': 'K',
 'Me_dK': 'K',
 'Lys(Ac)': 'K',
 'Lys(Cbz)': 'K',
 'Lys(iPr)': 'K',
 'Lys(Me)': 'K',
 'Me_Lys(Me)': 'K',
 'Lys(Me2)': 'K',
 'Lys(Tfa)': 'K',
 'L': 'L',
 'dL': 'L',
 'meL': 'L',
 'Me_dL': 'L',
 'aMeLeu': 'L',
 'dLeu(3R-OH)': 'L',
 '(N->O)Leu': 'L',
 'd(N->O)Leu': 'L',
 'M': 'M',
 'meM': 'M',
 'Met(O2)': 'M',
 'N': 'N',
 'dN': 'N',
 'meN': 'N',
 'dAsn(Me2)': 'N',
 'Nal': 'A',
 '1-Nal': 'A',
 'd1-Nal': 'A',
 'Nle': 'L',
 'Me_Nle': 'L',
 'Me_dNle': 'L',
 'Nle(CHF2)': 'L',
 'Nle(OH)': 'L',
 'Nva': 'V',
 'dNva': 'V',
 'Me_Nva': 'V',
 'Me_dNva': 'V',
 'Nva(Ph)': 'V',
 'Orn': 'K',
 'P': 'P',
 'dP': 'P',
 '3Pal': 'A',
 '4Pal': 'A',
 'Phg': 'G',
 'Pip': 'X',
 'dPip': 'X',
 'Pye': 'Q',
 'dPye': 'Q',
 'Q': 'Q',
 'meQ': 'Q',
 'Gln(Me)': 'Q',
 'Gln(Me2)': 'Q',
 'dGln(Me2)': 'Q',
 'Gln(Mes)': 'Q',
 'R': 'R',
 'dR': 'R',
 'Arg(Me,Me)': 'R',
 'S': 'S',
 'dS': 'S',
 'meS': 'S',
 'Ser(Ac)': 'S',
 'Ser(Bn)': 'S',
 'Ser(EtNMe2)': 'S',
 'Ser(EtOH)': 'S',
 'Ser(isoamyl)': 'S',
 'Ser(Me)': 'S',
 'dSer(Me)': 'S',
 'Ser(Ph(2-Cl))': 'S',
 'Ser(Ph(3-Cl))': 'S',
 'Ser(Pr)': 'S',
 'Ser(tBu)': 'S',
 'Me_Ser(isoamyl)': 'S',
 'Me_Ser(Pr)': 'S',
 'Sar': 'G',
 'Sta': 'X',
 'Sta(3R,4R)': 'X',
 'T': 'T',
 'dT': 'T',
 'meT': 'T',
 'Me_Bmt(E)': 'T',
 'Tle': 'G',
 'Tza': 'A',
 'Me_Tza': 'A',
 'V': 'V',
 'dV': 'V',
 'meV': 'V',
 'Me_dV': 'V',
 '(N->O)Val': 'V',
 'd(N->O)Val': 'V',
 '(N->O)Val(3-OH)': 'V',
 'W': 'W',
 'meW': 'W',
 'Me_dW': 'W',
 'Trp(5-Br)': 'W',
 'Trp(6-Br)': 'W',
 'Trp(7-Br)': 'W',
 'Y': 'Y',
 'dY': 'Y',
 'meY': 'Y',
 'Me_dY': 'Y',
 'Tyr(3-F)': 'Y',
 'Tyr(CHF2)': 'Y',
 'Tyr(Me)': 'Y',
 'Me_Tyr(Me)': 'Y',
 'dTyr(bR-OMe)': 'Y',
 '(N->O)Tyr': 'Y',
 'Mono1': 'G',
 'Mono2': 'P',
 'Mono3': 'X',
 'Mono4': 'N',
 'Mono5': 'N',
 'Mono6': 'X',
 'Bal(3-Me)': 'A',
 'Bal(d3-CF3)': 'A',
 'Mono9': 'F',
 'Mono10': 'F',
 'Mono11': 'F',
 'Mono12': 'F',
 'Mono13': 'P',
 'Mono14': 'X',
 'Mono15': 'T',
 'Mono16': 'X',
 'Mono17': 'X',
 'Mono18': 'X',
 'Mono19': 'X',
 'Mono20': 'X',
 'Mono23': 'X',
 'Mono24': 'Q',
 'Mono25': 'X',
 'Mono26': 'I',
 'Mono27': 'V',
 'Mono28': 'X',
 'Mono29': 'X',
 'Mono30': 'X',
 'Mono31': 'X',
 'Mono32': 'G',
 'Mono33': 'G',
 'Mono34': 'G',
 'Mono35': 'X',
 'Mono36': 'X',
 'Mono37': 'X',
 'Mono38': 'G',
 'Mono39': 'G',
 'Mono40': 'G',
 'Mono41': 'G',
 'Mono42': 'G',
 'Mono43': 'G',
 'Mono44': 'G',
 'Mono45': 'G',
 'Mono46': 'P',
 'Mono47': 'P',
 'Mono48': 'X',
 'Mono49': 'S',
 'Mono50': 'S',
 'Mono51': 'X',
 'Mono52': 'X',
 'Mono53': 'X',
 'Mono54': 'S',
 'Mono55': 'S',
 'Mono56': 'S',
 'Mono57': 'S',
 'Mono58': 'G',
 'Mono59': 'P',
 'Mono60': 'P',
 'Mono61': 'X',
 'Mono62': 'S',
 'Mono63': 'X',
 'Mono64': 'S',
 'Mono65': 'X',
 'Mono66': 'S',
 'Mono67': 'X',
 'Mono68': 'X',
 'Mono69': 'X',
 'Mono70': 'X',
 'Mono71': 'H',
 'Mono72': 'Q',
 'Mono73': 'N',
 'Mono74': 'R',
 'Mono75': 'F',
 'Mono76': 'F',
 'Mono77': 'F',
 'Mono78': 'F',
 'Mono79': 'F',
 'Mono80': 'F',
 'Mono81': 'F',
 'Mono82': 'F',
 'Mono83': 'G',
 'Mono84': 'A',
 'Mono85': 'A',
 'Mono86': 'L',
 'Mono87': 'F',
 'Mono88': 'F',
 'Mono89': 'F',
 'Mono90': 'F',
 'Mono91': 'F',
 'Mono92': 'X',
 'Mono93': 'X',
 'Mono94': 'X',
 'Mono95': 'X',
 'Mono96': 'X',
 'Mono97': 'X',
 'Mono98': 'X',
 'Mono99': 'X',
 'Mono100': 'C',
 'Mono101': 'C',
 'Mono102': 'X',
 'Mono103': 'X',
 'Mono104': 'X',
 'Mono105': 'X',
 'Mono106': 'X',
 'Mono107': 'X',
 'Mono108': 'X',
 'Mono109': 'X',
 'Mono110': 'X',
 'Mono111': 'X',
 'Mono112': 'X',
 'ac-': 'X',
 'deca-': 'X',
 'glyco-': 'G',
 'medl-': 'L',
 '-pip': 'X',
 'Mono21-': 'X',
 'Mono22-': 'X',
 'dW': 'W',
 'Ala(O->S)': 'A',
 'dAla(O->S)': 'A',
 'Phe(O->S)': 'F',
 'Ile(O->S)': 'I',
 'Lys(O->S)': 'K',
 'Leu(O->S)': 'L',
 'dLeu(O->S)': 'L',
 'Pro(O->S)': 'P',
 'dPro(O->S)': 'P',
 'Thr(O->S)': 'T',
 'dTrp(O->S)': 'W',
 'Tyr(O->S)': 'Y',
 'Ac3c': 'X',
 'Abu(5-Tet)': 'X',
 'Gly(allyl)': 'G',
 '-pyrro': 'X',
 'Aze': 'X',
 'Bal(d3-Me)': 'A',
 'Me_Bal(d3-Me)': 'A',
 'Bal(d3-EtPh)': 'A',
 'meH': 'H',
 'Phe(3-Cl)': 'F',
 'Phe(3-F)': 'F',
 'Phe(4-Cl)': 'F',
 'Mono113': 'X',
 'Ser(tBuOH)': 'S',
 'Val(3-OH)': 'V',
 'Mono114': 'X',
 'Ac5c': 'X',
 'Hph(4-CF3,3,5-diF)': 'F',
 'Hph(4-Me)': 'F',
 'Phe(3,5-diCl)': 'F',
 'Hph(4-CF3,3-Cl)': 'F',
 'Me_Phe(4-Me)': 'F',
 'Hph(4-tBu)': 'F',
 'Hph(3,4-diCl)': 'F',
 'Hch': 'F',
 'Phe(3-Cl,5-F)': 'F',
 'Me_Gly(cPent)': 'G',
 'Phe(3-CF3)': 'F',
 'Et_Phe(4-Me)': 'F',
 'Hph(4-CF3)': 'F',
 '-nme2': 'X',
 'Mono115': 'C',
 'Chg': 'G',
 'Me_Chg': 'G',
 'Et_Leu': 'L',
 'Me_Ser(Me)': 'S',
 'Me_Hse(Me)': 'S',
 'Gly(cPr)': 'G',
 'Me_Gly(cPr)': 'G',
 'Gly(cBu)': 'G',
 'Me_Gly(cBu)': 'G',
 'Gly(cPent)': 'G',
 'Ala(cPr)': 'A',
 'Ala(cBu)': 'A',
 'Ala(cPent)': 'A',
 'Me_Nva(F2)': 'V',
 '-mor': 'X',
 '-aze': 'X',
 'Mono116': 'X',
 'Mono117': 'F',
 'Mono118': 'F',
 'Mono119': 'F',
 'Mono120': 'F',
 'Mono121': 'F',
 'Mono122': 'F',
 'Mono123': 'F',
 'Mono124': 'F',
 'Mono125': 'F',
 'Mono126': 'X',
 'Mono127': 'X'}

In [12]:
amino_acid_list =  list(set(mono['Natural_Analog'].to_list()))
amino_acid_list

['S',
 'T',
 'Y',
 'N',
 'Q',
 'E',
 'K',
 'H',
 'G',
 'A',
 'C',
 'D',
 'X',
 'P',
 'V',
 'R',
 'M',
 'W',
 'F',
 'I',
 'L']

In [13]:
def seq2seq(sequence):
    seq = ''
    for s in sequence:
        if s in mono_dict.keys():
            seq += mono_dict[s]
    return seq

In [14]:
def calculate_aac(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Natural_analog_sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Natural_analog_sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [15]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)
df_train.loc[:, 'Natural_analog_sequence'] = df_train['Sequence'].apply(lambda x :seq2seq(x))
df_train = calculate_aac(df_train, amino_acid_list)
print('Shape',df_train.shape)
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Monomeric/Train_aac_Caco2.csv',index=False)
df_train

Shape (1007, 24)

,ID,SMILES,Permeability,S,T,Y,N,Q,E,K,...,D,X,P,V,R,M,W,F,I,L
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0.0,0.071429,0.0,0.0,0.000000,0.0,0.0,...,0.071429,0.071429,0.0,0.000000,0.0,0.0,0.0,0.285714,0.071429,0.214286
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0.0,0.071429,0.0,0.0,0.000000,0.0,0.0,...,0.071429,0.071429,0.0,0.000000,0.0,0.0,0.0,0.285714,0.071429,0.214286
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0.0,0.090909,0.0,0.0,0.090909,0.0,0.0,...,0.090909,0.000000,0.0,0.090909,0.0,0.0,0.0,0.181818,0.000000,0.363636
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0.0,0.071429,0.0,0.0,0.000000,0.0,0.0,...,0.071429,0.071429,0.0,0.071429,0.0,0.0,0.0,0.214286,0.071429,0.142857
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0.0,0.090909,0.0,0.0,0.090909,0.0,0.0,...,0.090909,0.000000,0.0,0.000000,0.0,0.0,0.0,0.181818,0.000000,0.363636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.250000,0.0,0.000000,0.0,0.0,0.0,0.250000,0.000000,0.250000
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.250000,0.0,0.000000,0.0,0.0,0.0,0.250000,0.000000,0.250000
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,...,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333

In [16]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)
df_test.loc[:, 'Natural_analog_sequence'] = df_test['Sequence'].apply(lambda x :seq2seq(x))
df_test = calculate_aac(df_test, amino_acid_list)
print('Shape',df_test.shape)
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Monomeric/Test_aac_Caco2.csv',index=False)
df_test

Shape (252, 24)

,ID,SMILES,Permeability,S,T,Y,N,Q,E,K,...,D,X,P,V,R,M,W,F,I,L
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.000000,0.071429,0.0,0.0,0.0,0.0,0.0,...,0.071429,0.071429,0.000000,0.000000,0.0,0.0,0.0,0.285714,0.071429,0.214286
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.416667,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.083333,0.166667,0.000000,0.000000,0.0,0.0,0.0,0.083333,0.000000,0.166667
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.090909,0.090909,0.0,0.0,0.0,0.0,0.0,...,0.090909,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.363636,0.000000,0.363636
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.090909,0.090909,0.0,0.0,0.0,0.0,0.0,...,0.090909,0.000000,0.090909,0.181818,0.0,0.0,0.0,0.181818,0.000000,0.181818
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.090909,0.090909,0.0,0.0,0.0,0.0,0.0,...,0.090909,0.000000,0.090909,0.000000,0.0,0.0,0.0,0.181818,0.000000,0.363636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.000000
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.333333,0.000000,0.333333

In [17]:
#Atomic features
import pandas as pd
import numpy as np
from rdkit import Chem

In [18]:
def get_unique_atoms(smiles_list):
    unique_atoms = set()
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        if mol is not None:  # Check if the molecule was created successfully
            for atom in mol.GetAtoms():
                unique_atoms.add(atom.GetSymbol())  # Add atomic symbol to the set
    
    return unique_atoms

In [19]:
def get_atomic_composition_frequency(smiles_list):
    atomic_frequencies = []
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        composition = {'Br': 0, 'C': 0, 'Cl': 0, 'F': 0, 'N': 0, 'O': 0, 'S': 0}  
        
        if mol is not None:  # Check if the molecule was created successfully
            total_atoms = mol.GetNumAtoms()  # Get total number of atoms in the molecule
            
            for atom in mol.GetAtoms():
                composition[atom.GetSymbol()] += 1  # Count occurrences of each atom
            
            # Calculate frequency
            frequency = {atom: count / total_atoms for atom, count in composition.items()}
            atomic_frequencies.append(frequency)  # Append the frequency for this SMILES
    
    return atomic_frequencies

In [20]:
#Degree of atoms
target_atoms = {'Br', 'C', 'Cl', 'F', 'N', 'O', 'S'}
def compute_target_atom_degrees(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    # Initialize a dictionary to hold the highest degrees for target atoms
    degrees_dict = {atom: 0 for atom in target_atoms}

    # Get the degree of each atom and update the dictionary for target atoms
    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        if atom_symbol in target_atoms:
            current_degree = atom.GetDegree()
            # Update the degree if the current one is higher
            if current_degree > degrees_dict[atom_symbol]:
                degrees_dict[atom_symbol] = current_degree

    return degrees_dict

In [21]:
#Bond type
def compute_bond_types_for_cyclic_peptides(df):
    
    def compute_bond_types(smiles):
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None  # Handle invalid SMILES

        bond_types = {
            'Single': 0,
            'Double': 0,
            'Triple': 0,
            'Aromatic': 0,
            'Conjugated': 0,
            'No-bond': 0
        }

        # Iterate through the bonds in the molecule
        for bond in mol.GetBonds():
            bond_order = bond.GetBondTypeAsDouble()
            if bond_order == 1.0:
                bond_types['Single'] += 1
            elif bond_order == 2.0:
                bond_types['Double'] += 1
            elif bond_order == 3.0:
                bond_types['Triple'] += 1
            elif bond_order == 1.5:
                bond_types['Aromatic'] += 1
            elif bond_order == 1.4:
                bond_types['Conjugated'] += 1
            else:
                bond_types['No-bond'] += 1

        return bond_types

    df['Bond_Types'] = df['SMILES'].apply(compute_bond_types)

    bond_types_df = df['Bond_Types'].apply(pd.Series)

    df = pd.concat([df, bond_types_df], axis=1)

    df.drop(columns=['Bond_Types'], inplace=True)

    return df

In [22]:
#Formal charges
def calculate_overall_formal_charge(smiles):
   
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    overall_charge = 0
    
    # Define valence electrons for common atoms
    valence_electrons = {
        'C': 4,
        'N': 5,
        'O': 6,
        'S': 6,
        'P': 5,
        'F': 7,
        'Cl': 7,
        'Br': 7,
        'I': 7,
    }

    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        valence = valence_electrons.get(atom_symbol, 0)
        non_bonding = atom.GetNumImplicitHs() 
        bonding = atom.GetDegree() * 2  # 2 electrons for each bond

        # Calculate formal charge
        formal_charge = valence - (non_bonding + bonding // 2)
        overall_charge += formal_charge

    return overall_charge

In [23]:
def check_aromatic_and_ring(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return (None, None)  # Handle invalid SMILES

    # Check if the molecule is aromatic
    is_aromatic = any(atom.GetIsAromatic() for atom in mol.GetAtoms())

    # Check if the molecule contains a ring
    ring_info = mol.GetRingInfo()
    is_in_ring = ring_info.NumRings() > 0

    return (int(is_aromatic), int(is_in_ring))

In [24]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,"['Me_Bal', 'meF', 'meL', 'meA', 'meF', 'I', 'm...",1664.156
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,"['dA', 'T', 'meF', 'I', 'meA', 'meL', 'meF', '...",1650.129
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,"['dL', 'Me_Phe(3-Cl)', 'L', 'meL', 'T', 'Bu_Gl...",1587.863
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,"['Me_dA', 'meA', 'meF', 'T', 'meA', 'meL', 'I'...",1574.031
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,"['Bu_Gly', 'Me_Phe(3-Cl)', 'Gln(Mes)', 'meL', ...",1567.445
...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,"['Sar', 'L', 'F', '5-Ava']",430.549
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,"['A', 'L', 'F', '5-Ava']",430.549
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,"['A', 'L', 'Mono76']",402.539
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,"['A', 'L', 'Mono75']",388.512
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,"['A', 'L', 'H2NEt_Phe']",374.485

In [25]:
unique_atoms = get_unique_atoms(df_train['SMILES'])
unique_atoms

{'C', 'Cl', 'F', 'N', 'O', 'S'}

In [26]:
atomic_frequencies = get_atomic_composition_frequency(df_train['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

       Br         C        Cl    F         N         O         S
0     0.0  0.758333  0.000000  0.0  0.116667  0.125000  0.000000
1     0.0  0.756303  0.000000  0.0  0.117647  0.126050  0.000000
2     0.0  0.706422  0.018349  0.0  0.119266  0.146789  0.009174
3     0.0  0.743363  0.000000  0.0  0.123894  0.132743  0.000000
4     0.0  0.715596  0.009174  0.0  0.119266  0.146789  0.009174
...   ...       ...       ...  ...       ...       ...       ...
1002  0.0  0.741935  0.000000  0.0  0.129032  0.129032  0.000000
1003  0.0  0.741935  0.000000  0.0  0.129032  0.129032  0.000000
1004  0.0  0.758621  0.000000  0.0  0.137931  0.103448  0.000000
1005  0.0  0.750000  0.000000  0.0  0.142857  0.107143  0.000000
1006  0.0  0.740741  0.000000  0.0  0.148148  0.111111  0.000000

[1007 rows x 7 columns]

In [27]:
df_train_atomic_comp = pd.concat([df_train[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_train_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0.0,0.758333,0.000000,0.0,0.116667,0.125000,0.000000
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0.0,0.756303,0.000000,0.0,0.117647,0.126050,0.000000
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0.0,0.706422,0.018349,0.0,0.119266,0.146789,0.009174
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0.0,0.743363,0.000000,0.0,0.123894,0.132743,0.000000
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0.0,0.715596,0.009174,0.0,0.119266,0.146789,0.009174
...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0.0,0.758621,0.000000,0.0,0.137931,0.103448,0.000000
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0.0,0.750000,0.000000,0.0,0.142857,0.107143,0.000000
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0.0,0.740741,0.000000,0.0,0.148148,0.111111,0.000000

In [28]:
df_train_atomic_comp.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_atomic_comp_Caco2.csv', index=False)

In [29]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')
atomic_frequencies = get_atomic_composition_frequency(df_test['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

      Br         C        Cl         F         N         O    S
0    0.0  0.758333  0.000000  0.000000  0.116667  0.125000  0.0
1    0.0  0.720721  0.000000  0.000000  0.108108  0.171171  0.0
2    0.0  0.767857  0.000000  0.000000  0.107143  0.125000  0.0
3    0.0  0.722222  0.009259  0.018519  0.120370  0.129630  0.0
4    0.0  0.733945  0.000000  0.018349  0.119266  0.128440  0.0
..   ...       ...       ...       ...       ...       ...  ...
247  0.0  0.774194  0.000000  0.000000  0.129032  0.096774  0.0
248  0.0  0.774194  0.000000  0.000000  0.129032  0.096774  0.0
249  0.0  0.774194  0.000000  0.000000  0.129032  0.096774  0.0
250  0.0  0.774194  0.000000  0.000000  0.129032  0.096774  0.0
251  0.0  0.766667  0.000000  0.000000  0.133333  0.100000  0.0

[252 rows x 7 columns]

In [30]:
df_test_atomic_comp = pd.concat([df_test[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_test_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.0,0.758333,0.000000,0.000000,0.116667,0.125000,0.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.0,0.720721,0.000000,0.000000,0.108108,0.171171,0.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.0,0.767857,0.000000,0.000000,0.107143,0.125000,0.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.0,0.722222,0.009259,0.018519,0.120370,0.129630,0.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.0,0.733945,0.000000,0.018349,0.119266,0.128440,0.0
...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.0,0.766667,0.000000,0.000000,0.133333,0.100000,0.0

In [31]:
df_test_atomic_comp.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_atomic_comp_Caco2.csv', index=False)

In [32]:
#Degree of atoms
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_atomic_comp_Caco2.csv')
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_atomic_comp_Caco2.csv')

In [33]:
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_atomic_comp_and_degree_Caco2.csv",index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_O,Degree_C,Degree_Br,Degree_N,Degree_Cl,Degree_S,Degree_F
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0.0,0.758333,0.000000,0.0,0.116667,0.125000,0.000000,1,3,0,3,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0.0,0.756303,0.000000,0.0,0.117647,0.126050,0.000000,1,3,0,3,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0.0,0.706422,0.018349,0.0,0.119266,0.146789,0.009174,1,3,0,3,1,4,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0.0,0.743363,0.000000,0.0,0.123894,0.132743,0.000000,1,3,0,3,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0.0,0.715596,0.009174,0.0,0.119266,0.146789,0.009174,1,3,0,3,1,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000,1,3,0,3,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000,1,3,0,2,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0.0,0.758621,0.000000,0.0,0.137931,0.103448,0.000000,1,3,0,2,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0.0,0.750000,0.000000,0.0,0.142857,0.107143,0.000000,1,3,0,2,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0.0,0.740741,0.000000,0.0,0.148148,0.111111,0.000000,1,3,0,2,0,0,0

In [34]:
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_atomic_comp_and_degree_Caco2.csv",index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_O,Degree_C,Degree_Br,Degree_N,Degree_Cl,Degree_S,Degree_F
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.0,0.758333,0.000000,0.000000,0.116667,0.125000,0.0,1,3,0,3,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.0,0.720721,0.000000,0.000000,0.108108,0.171171,0.0,2,4,0,3,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.0,0.767857,0.000000,0.000000,0.107143,0.125000,0.0,2,4,0,3,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.0,0.722222,0.009259,0.018519,0.120370,0.129630,0.0,2,4,0,3,1,0,1
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.0,0.733945,0.000000,0.018349,0.119266,0.128440,0.0,2,4,0,3,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,1,3,0,2,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,1,3,0,3,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,1,3,0,2,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,1,3,0,2,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.0,0.766667,0.000000,0.000000,0.133333,0.100000,0.0,1,3,0,2,0,0,0

In [35]:
#CSV with only degree columns
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_atomic_degrees_Caco2.csv",index=False)
df_train

,ID,SMILES,Permeability,Degree_O,Degree_C,Degree_Br,Degree_N,Degree_Cl,Degree_S,Degree_F
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,3,0,3,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,3,0,3,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,3,0,3,1,4,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,3,0,3,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,3,0,3,1,4,0
...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,1,3,0,3,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,1,3,0,2,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,3,0,2,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,3,0,2,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,3,0,2,0,0,0

In [36]:
#CSV with only degree columns
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

# Rename the columns to include the atom symbols
degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

# Concatenate the original DataFrame with the new degrees DataFrame
df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_atomic_degrees_Caco2.csv",index=False)
df_test

,ID,SMILES,Permeability,Degree_O,Degree_C,Degree_Br,Degree_N,Degree_Cl,Degree_S,Degree_F
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,3,0,3,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,2,4,0,3,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,2,4,0,3,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,2,4,0,3,1,0,1
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,2,4,0,3,0,0,1
...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,3,0,2,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,3,0,3,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,3,0,2,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,3,0,2,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,3,0,2,0,0,0

In [37]:
#Bond_type
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_bonds_type_Caco2.csv', index=False)

In [38]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_atomic_comp_and_degree_Caco2.csv')
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_Caco2.csv', index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_N,Degree_Cl,Degree_S,Degree_F,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0.0,0.758333,0.000000,0.0,0.116667,0.125000,0.000000,...,3,0,0,0,87,14,0,24,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0.0,0.756303,0.000000,0.0,0.117647,0.126050,0.000000,...,3,0,0,0,86,14,0,24,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0.0,0.706422,0.018349,0.0,0.119266,0.146789,0.009174,...,3,1,4,0,85,15,0,12,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0.0,0.743363,0.000000,0.0,0.123894,0.132743,0.000000,...,3,0,0,0,85,14,0,18,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0.0,0.715596,0.009174,0.0,0.119266,0.146789,0.009174,...,3,1,4,0,85,15,0,12,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000,...,3,0,0,0,22,4,0,6,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0.0,0.741935,0.000000,0.0,0.129032,0.129032,0.000000,...,2,0,0,0,22,4,0,6,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0.0,0.758621,0.000000,0.0,0.137931,0.103448,0.000000,...,2,0,0,0,21,3,0,6,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0.0,0.750000,0.000000,0.0,0.142857,0.107143,0.000000,...,2,0,0,0,20,3,0,6,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0.0,0.740741,0.000000,0.0,0.148148,0.111111,0.000000,...,2,0,0,0,19,3,0,6,0,0

In [39]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_bonds_type_Caco2.csv', index=False)
df_test

,ID,SMILES,Permeability,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,87,14,0,24,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,95,12,0,6,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,81,12,0,24,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,89,12,0,12,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,90,12,0,12,0,0
...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,23,3,0,6,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,23,3,0,6,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,23,3,0,6,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,23,3,0,6,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,22,3,0,6,0,0

In [40]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_atomic_comp_and_degree_Caco2.csv')
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_Caco2.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_N,Degree_Cl,Degree_S,Degree_F,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.0,0.758333,0.000000,0.000000,0.116667,0.125000,0.0,...,3,0,0,0,87,14,0,24,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.0,0.720721,0.000000,0.000000,0.108108,0.171171,0.0,...,3,0,0,0,95,12,0,6,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.0,0.767857,0.000000,0.000000,0.107143,0.125000,0.0,...,3,0,0,0,81,12,0,24,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.0,0.722222,0.009259,0.018519,0.120370,0.129630,0.0,...,3,1,0,1,89,12,0,12,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.0,0.733945,0.000000,0.018349,0.119266,0.128440,0.0,...,3,0,0,1,90,12,0,12,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,2,0,0,0,23,3,0,6,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,3,0,0,0,23,3,0,6,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,2,0,0,0,23,3,0,6,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,2,0,0,0,23,3,0,6,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.0,0.766667,0.000000,0.000000,0.133333,0.100000,0.0,...,2,0,0,0,22,3,0,6,0,0

In [41]:
#Overall formal charge
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Overall_Formal_Charge'] = df_train['SMILES'].apply(calculate_overall_formal_charge)
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_formal_charge_Caco2.csv', index=False)
df_train

,ID,SMILES,Permeability,Overall_Formal_Charge
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,154
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,155
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,155
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,149
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,148
...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,40
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,41
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,35
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,35
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,35

In [42]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Overall_Formal_Charge'] = df_test['SMILES'].apply(calculate_overall_formal_charge)
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_formal_charge_Caco2.csv', index=False)
df_test

,ID,SMILES,Permeability,Overall_Formal_Charge
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,155
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,141
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,140
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,148
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,143
...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,35
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,34
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,35
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,35
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,35

In [43]:
#Aromatic and ring
df_train = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train[['Is_Aromatic', 'Is_In_Ring']] = df_train['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_is_ring_is_aromatic_Caco2.csv', index=False)
df_train

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,1
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,1
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,1
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,1
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,1
...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,1,1
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,1,1
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,1
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,1
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,1

In [44]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test[['Is_Aromatic', 'Is_In_Ring']] = df_test['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_is_ring_is_aromatic_Caco2.csv', index=False)
df_test

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,1
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,1,1
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,1,1
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,1,1
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,1,1
...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,1
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,1
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,1
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,1
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,1

In [45]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_Caco2.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_formal_charge_Caco2.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_is_ring_is_aromatic_Caco2.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_train = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Train_all_atomic_desc_Caco2.csv', index=False)

In [46]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_Caco2.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_formal_charge_Caco2.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_is_ring_is_aromatic_Caco2.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_test = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Atomic/Test_all_atomic_desc_Caco2.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_F,Single,Double,Triple,Aromatic,Conjugated,No-bond,Overall_Formal_Charge,Is_Aromatic,Is_In_Ring
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0.0,0.758333,0.000000,0.000000,0.116667,0.125000,0.0,...,0,87,14,0,24,0,0,155,1,1
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0.0,0.720721,0.000000,0.000000,0.108108,0.171171,0.0,...,0,95,12,0,6,0,0,141,1,1
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0.0,0.767857,0.000000,0.000000,0.107143,0.125000,0.0,...,0,81,12,0,24,0,0,140,1,1
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0.0,0.722222,0.009259,0.018519,0.120370,0.129630,0.0,...,1,89,12,0,12,0,0,148,1,1
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0.0,0.733945,0.000000,0.018349,0.119266,0.128440,0.0,...,1,90,12,0,12,0,0,143,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,0,23,3,0,6,0,0,35,1,1
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,0,23,3,0,6,0,0,34,1,1
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,0,23,3,0,6,0,0,35,1,1
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0.0,0.774194,0.000000,0.000000,0.129032,0.096774,0.0,...,0,23,3,0,6,0,0,35,1,1
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0.0,0.766667,0.000000,0.000000,0.133333,0.100000,0.0,...,0,22,3,0,6,0,0,35,1,1

In [47]:
#Fingerprints

In [48]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, rdFingerprintGenerator, rdMolDescriptors
from padelpy import padeldescriptor

In [49]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,"['Me_Bal', 'meF', 'meL', 'meA', 'meF', 'I', 'm...",1664.156
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,"['dA', 'T', 'meF', 'I', 'meA', 'meL', 'meF', '...",1650.129
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,"['dL', 'Me_Phe(3-Cl)', 'L', 'meL', 'T', 'Bu_Gl...",1587.863
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,"['Me_dA', 'meA', 'meF', 'T', 'meA', 'meL', 'I'...",1574.031
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,"['Bu_Gly', 'Me_Phe(3-Cl)', 'Gln(Mes)', 'meL', ...",1567.445
...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,"['Sar', 'L', 'F', '5-Ava']",430.549
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,"['A', 'L', 'F', '5-Ava']",430.549
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,"['A', 'L', 'Mono76']",402.539
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,"['A', 'L', 'Mono75']",388.512
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,"['A', 'L', 'H2NEt_Phe']",374.485

In [50]:
df_train_cmfp = df_train[['ID','SMILES','Permeability']]
df_train_cmfp

        ID                                             SMILES  Permeability
0     2064  CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...         -7.19
1     2067  CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...         -7.24
2     1914  CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...         -8.00
3     2026  CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...         -5.64
4     1920  CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...         -7.05
...    ...                                                ...           ...
1002  5605  CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...         -5.32
1003  5602  CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...         -5.45
1004  2469  CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...         -5.19
1005  2468  CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...         -5.11
1006  2467  CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...         -5.33

[1007 rows x 3 columns]

In [51]:
def generate_count_morgan_fp(smiles, radius=2, nBits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Count Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=nBits)
        count_fp = mfpgen.GetCountFingerprint(mol)
        
        # Convert the count fingerprint to a dense array
        dense_fp = np.zeros((nBits,), dtype=int)
        for bit, count in count_fp.GetNonzeroElements().items():
            dense_fp[bit] = count
            
        return dense_fp
    else:
        return None

In [52]:
df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_train_cmfp['count_morgan_fp']

/tmp/ipykernel_1783265/1551993060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)

0       [0, 8, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1       [0, 8, 1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2       [0, 6, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3       [0, 8, 1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4       [0, 5, 1, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                              ...
1002    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1003    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1004    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1005    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1006    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: count_morgan_fp, Length: 1007, dtype: object

In [53]:
df = pd.DataFrame(df_train_cmfp['count_morgan_fp'].tolist(), index=df_train_cmfp.index)

df_train_cmfp = pd.concat([df_train_cmfp, df.add_prefix('count_fp_')], axis=1)
df_train_cmfp.shape

(1007, 2052)

In [54]:
df_train_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_train_cmfp.shape

(1007, 2051)

In [55]:
df_train_cmfp.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/count_morgan_fp_train_Caco2.csv', index=False)

In [56]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
df_test_cmfp = df_test[['ID','SMILES','Permeability']]
df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_test_cmfp['count_morgan_fp']
df = pd.DataFrame(df_test_cmfp['count_morgan_fp'].tolist(), index=df_test_cmfp.index)

df_test_cmfp = pd.concat([df_test_cmfp, df.add_prefix('count_fp_')], axis=1)
df_test_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_test_cmfp.shape

/tmp/ipykernel_1783265/1072159945.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)

(252, 2051)

In [57]:
df_test_cmfp.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/count_morgan_fp_test_Caco2.csv', index=False)

In [58]:
def generate_fingerprints(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Create a Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
        
        # Generate the Morgan fingerprint as a bit vector
        morgan_fp = mfpgen.GetFingerprint(mol)
        
        # Convert the bit vector to a dense array
        dense_fp = np.zeros((2048,), dtype=int)
        for bit in range(2048):
            dense_fp[bit] = morgan_fp[bit]
        
        return dense_fp
    else:
        print("Invalid SMILES string.")
        return None

In [59]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
df_mfp_train = df_train[['ID','SMILES','Permeability']]
df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_train['Morganfingerprints'].tolist(), index=df_mfp_train.index)

df_mfp_train = pd.concat([df_mfp_train, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_train.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/morgan_fp_train_Caco2.csv', index=False)
print(df_mfp_train.shape)
df_mfp_train

/tmp/ipykernel_1783265/3544633016.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)

(1007, 2051)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
df_mfp_test = df_test[['ID','SMILES','Permeability']]
df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_test['Morganfingerprints'].tolist(), index=df_mfp_test.index)

df_mfp_test = pd.concat([df_mfp_test, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_test.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/morgan_fp_test_Caco2.csv', index=False)
print(df_mfp_test.shape)
df_mfp_test

/tmp/ipykernel_1783265/261239065.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)

(252, 2051)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [61]:
#Padel fingerprints
import glob
import os
directory = '/home/users/akshay/PCPpred/fingerprints_xml'
pattern = '*.xml'  

xml_files = glob.glob(os.path.join(directory, pattern))
xml_files.sort()
xml_files

['/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml']

In [62]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'Extended',
 'Fingerprinter',
 'Graphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [63]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 'EState': '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 'Extended': '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 'Fingerprinter': '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 'Graphonly': '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 'MACCS': '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 'PubChem': '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 'SubstructureCount': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 'Substructure': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml'}

In [64]:
# df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
# df_smi = df_train[['SMILES','ID']]
# df_smi.to_csv('/home/users/akshay/PCPpred/Caco2/data/train.smi', sep='\t', index=False, header=False)
# df_smi

In [65]:
#Substructure
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2064,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2067,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1914,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2026,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,1920,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1003,5602,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1004,2469,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1005,2468,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1006,2467,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [66]:
df_Substructure_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_Substructure_train.head()

,ID,SMILES,Permeability,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,2064,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,2067,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1914,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,2026,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1920,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [67]:
df_Substructure_train.drop(['Name'],axis=1,inplace=True)
df_Substructure_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Substructure_train_Caco2.csv', index=False)
df_Substructure_train

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [68]:
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_Substructure_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
# df_Substructure_train.head()
df_Substructure_test.drop(['Name'],axis=1,inplace=True)
df_Substructure_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Substructure_test_Caco2.csv', index=False)
df_Substructure_test

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [69]:
#CountSubstructure
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_train.head()

,ID,SMILES,Permeability,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,2064,11.0,13.0,4.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,69.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,2067,12.0,12.0,4.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,70.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1914,12.0,14.0,5.0,0.0,0.0,0.0,...,0.0,0.0,76.0,76.0,24.0,0.0,0.0,0.0,0.0,55.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,2026,13.0,10.0,4.0,0.0,0.0,0.0,...,0.0,0.0,75.0,75.0,25.0,0.0,0.0,0.0,0.0,64.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1920,11.0,16.0,4.0,0.0,0.0,0.0,...,0.0,0.0,76.0,76.0,26.0,0.0,0.0,0.0,0.0,53.0

In [70]:
df_SubstructureCount_train.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/SubstructureCount_train_Caco2.csv', index=False)
df_SubstructureCount_train

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,11.0,13.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,69.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,12.0,12.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,70.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,12.0,14.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,76.0,76.0,24.0,0.0,0.0,0.0,0.0,55.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,13.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,75.0,75.0,25.0,0.0,0.0,0.0,0.0,64.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,11.0,16.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,76.0,76.0,26.0,0.0,0.0,0.0,0.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,2.0,5.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,21.0,21.0,4.0,0.0,0.0,0.0,0.0,17.0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,3.0,5.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,18.0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,3.0,4.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,21.0,21.0,4.0,0.0,0.0,0.0,0.0,17.0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,3.0,3.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,20.0,20.0,4.0,0.0,0.0,0.0,0.0,17.0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,3.0,2.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,19.0,19.0,4.0,0.0,0.0,0.0,0.0,17.0

In [71]:
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_test.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/SubstructureCount_test_Caco2.csv', index=False)
df_SubstructureCount_test

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,12.0,12.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,70.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,16.0,11.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,89.0,89.0,32.0,0.0,0.0,0.0,0.0,48.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,12.0,12.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,73.0,73.0,22.0,0.0,0.0,0.0,0.0,65.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,12.0,11.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,77.0,17.0,0.0,0.0,0.0,0.0,55.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,13.0,13.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,80.0,80.0,19.0,0.0,0.0,0.0,0.0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,3.0,6.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,3.0,5.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,16.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,3.0,6.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,3.0,6.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,3.0,5.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,17.0

In [72]:
#MACCS
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_train.head()
df_MACCS_train.drop(['Name'],axis=1,inplace=True)
df_MACCS_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/MACCS_train_Caco2.csv', index=False)
df_MACCS_train

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0

In [73]:
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_test.drop(['Name'],axis=1,inplace=True)
df_MACCS_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/MACCS_test_Caco2.csv', index=False)
df_MACCS_test

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0

In [74]:
#PubChem
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_train.drop(['Name'],axis=1,inplace=True)
df_PubChem_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/PubChem_train_Caco2.csv', index=False)
df_PubChem_train

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [75]:
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_test.drop(['Name'],axis=1,inplace=True)
df_PubChem_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/PubChem_test_Caco2.csv', index=False)
df_PubChem_test

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
#AtomPairs2DCount
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/AtomPairs2DCount_train_Caco2.csv', index=False)
df_AtomPairs2DCount_train

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,72.0,38.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,72.0,37.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,60.0,32.0,14.0,1.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,64.0,38.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,60.0,33.0,14.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,19.0,9.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,20.0,8.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,19.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,18.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,17.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/AtomPairs2DCount_test_Caco2.csv', index=False)
df_AtomPairs2DCount_test

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,72.0,38.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,59.0,30.0,24.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,71.0,31.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,60.0,35.0,15.0,0.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,63.0,34.0,15.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,21.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,20.0,9.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,21.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,21.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,20.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
#AtomPairs2D
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/AtomPairs2D_train_Caco2.csv', index=False)
df_AtomPairs2D_train

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [79]:
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/AtomPairs2D_test_Caco2.csv', index=False)
df_AtomPairs2D_test

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,1,1,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,1,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [80]:
#EState
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_train.drop(['Name'],axis=1,inplace=True)
EState_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/EState_train_Caco2.csv', index=False)
EState_train

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [81]:
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_test.drop(['Name'],axis=1,inplace=True)
EState_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/EState_test_Caco2.csv', index=False)
EState_test

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [82]:
#Extended
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_train.drop(['Name'],axis=1,inplace=True)
Extended_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Extended_train_Caco2.csv', index=False)
Extended_train

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_test.drop(['Name'],axis=1,inplace=True)
Extended_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Extended_test_Caco2.csv', index=False)
Extended_test

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [84]:
#Fingerprinter
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_train.drop(['Name'],axis=1,inplace=True)
Fingerprinter_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Fingerprinter_train_Caco2.csv', index=False)
Fingerprinter_train

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [85]:
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_test.drop(['Name'],axis=1,inplace=True)
Fingerprinter_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Fingerprinter_test_Caco2.csv', index=False)
Fingerprinter_test

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0

In [86]:
#GraphOnly
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_train.drop(['Name'],axis=1,inplace=True)
Graphonly_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Graphonly_train_Caco2.csv', index=False)
Graphonly_train

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_test.drop(['Name'],axis=1,inplace=True)
Graphonly_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Graphonly_test_Caco2.csv', index=False)
Graphonly_test

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
#KlekotaRothCount
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_train.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/KlekotaRothCount_train_Caco2.csv', index=False)
KlekotaRothCount_train

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,17.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,18.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,16.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,18.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,14.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_test.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/KlekotaRothCount_test_Caco2.csv', index=False)
KlekotaRothCount_test

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,18.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,16.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,16.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,17.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,3.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [91]:
#KlekotaRoth
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_train.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_train.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/KlekotaRoth_train_Caco2.csv', index=False)
KlekotaRoth_train

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [92]:
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/Caco2/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_test.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_test.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/KlekotaRoth_test_Caco2.csv', index=False)
KlekotaRoth_test

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
df_train_morgan = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/morgan_fp_train_Caco2.csv')
df_train_morganCount = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/count_morgan_fp_train_Caco2.csv')
df_train_AP2d = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/AtomPairs2D_train_Caco2.csv')
df_train_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/AtomPairs2DCount_train_Caco2.csv')
df_train_EState = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/EState_train_Caco2.csv')
df_train_Extended = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Extended_train_Caco2.csv')
df_train_fp= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Fingerprinter_train_Caco2.csv')
df_train_graph= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Graphonly_train_Caco2.csv')
df_train_kr= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/KlekotaRoth_train_Caco2.csv')
df_train_krcount= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/KlekotaRothCount_train_Caco2.csv')
df_train_maccs= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/MACCS_train_Caco2.csv')
df_train_pubchem= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/PubChem_train_Caco2.csv')
df_train_Substr= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/Substructure_train_Caco2.csv')
df_train_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/SubstructureCount_train_Caco2.csv')

df = df_train_morgan.merge(df_train_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,0,1,1,0,0,1,0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,69.0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,0,1,1,0,0,1,0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,70.0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,0,1,1,0,0,1,0,...,0.0,0.0,76.0,76.0,24.0,0.0,0.0,0.0,0.0,55.0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,0,1,1,0,0,1,0,...,0.0,0.0,75.0,75.0,25.0,0.0,0.0,0.0,0.0,64.0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,0,1,1,0,0,1,0,...,0.0,0.0,76.0,76.0,26.0,0.0,0.0,0.0,0.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,0,1,0,0,0,0,0,...,0.0,0.0,21.0,21.0,4.0,0.0,0.0,0.0,0.0,17.0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,0,1,0,0,0,0,0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,18.0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,0,1,0,0,0,0,0,...,0.0,0.0,21.0,21.0,4.0,0.0,0.0,0.0,0.0,17.0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,0,1,0,0,0,0,0,...,0.0,0.0,20.0,20.0,4.0,0.0,0.0,0.0,0.0,17.0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,0,1,0,0,0,0,0,...,0.0,0.0,19.0,19.0,4.0,0.0,0.0,0.0,0.0,17.0

In [94]:
df.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Train/All_fingerprints_train_Caco2.csv',index=False)

In [95]:
df_test_morgan = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/morgan_fp_test_Caco2.csv')
df_test_morganCount = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/count_morgan_fp_test_Caco2.csv')
df_test_AP2d = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/AtomPairs2D_test_Caco2.csv')
df_test_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/AtomPairs2DCount_test_Caco2.csv')
df_test_EState = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/EState_test_Caco2.csv')
df_test_Extended = pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Extended_test_Caco2.csv')
df_test_fp= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Fingerprinter_test_Caco2.csv')
df_test_graph= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Graphonly_test_Caco2.csv')
df_test_kr= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/KlekotaRoth_test_Caco2.csv')
df_test_krcount= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/KlekotaRothCount_test_Caco2.csv')
df_test_maccs= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/MACCS_test_Caco2.csv')
df_test_pubchem= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/PubChem_test_Caco2.csv')
df_test_Substr= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/Substructure_test_Caco2.csv')
df_test_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/SubstructureCount_test_Caco2.csv')

df = df_test_morgan.merge(df_test_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,0,1,1,0,0,1,0,...,0.0,0.0,77.0,77.0,28.0,0.0,0.0,0.0,0.0,70.0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,0,1,1,0,0,1,0,...,0.0,0.0,89.0,89.0,32.0,0.0,0.0,0.0,0.0,48.0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,0,1,1,0,0,1,0,...,0.0,0.0,73.0,73.0,22.0,0.0,0.0,0.0,0.0,65.0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,0,1,1,0,0,1,0,...,0.0,0.0,77.0,77.0,17.0,0.0,0.0,0.0,0.0,55.0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,0,1,1,0,0,1,0,...,0.0,0.0,80.0,80.0,19.0,0.0,0.0,0.0,0.0,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,0,1,1,0,0,0,0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,0,1,1,0,0,1,0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,16.0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,0,1,1,0,0,0,0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,0,1,1,0,0,0,0,...,0.0,0.0,23.0,23.0,4.0,0.0,0.0,0.0,0.0,17.0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,0,1,1,0,0,0,0,...,0.0,0.0,22.0,22.0,4.0,0.0,0.0,0.0,0.0,17.0

In [96]:
df.to_csv('/home/users/akshay/PCPpred/Caco2/features/Fingerprints/Test/All_fingerprints_test_Caco2.csv',index=False)

In [97]:
#Descriptors
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors, Descriptors3D
from rdkit.ML.Descriptors import MoleculeDescriptors
from tqdm import tqdm

In [98]:
calc = MoleculeDescriptors.MolecularDescriptorCalculator([desc[0] for desc in Chem.Descriptors._descList])

def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None 
    return calc.CalcDescriptors(mol)

In [99]:
#2D RDKit train dataset descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
train_2d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_2d_rdkit.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Train_2d_RDKit_des_Caco2.csv',index=False)
print("Shape: ",train_2d_rdkit.shape, '\n')
train_2d_rdkit

Shape:  (1007, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,15.976055,15.976055,0.030813,-1.935404,0.058779,22.883333,1664.156,...,0,0,0,0,0,0,0,0,0,0
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,16.083777,16.083777,0.027668,-1.934865,0.053531,23.411765,1650.129,...,0,0,0,0,0,0,0,0,0,0
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,15.668220,15.668220,0.003714,-4.150777,0.085546,24.018349,1587.863,...,0,1,0,0,0,0,0,0,1,0
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,16.048909,16.048909,0.025704,-1.891709,0.101375,24.159292,1574.031,...,0,0,0,0,0,0,0,0,0,0
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,15.511700,15.511700,0.033138,-4.150544,0.085338,23.366972,1567.445,...,0,1,0,0,0,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,13.038711,13.038711,0.105820,-0.784997,0.662387,22.258065,430.549,...,0,0,0,0,0,0,0,0,0,0
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,13.057052,13.057052,0.142991,-0.802728,0.571252,24.322581,430.549,...,0,0,0,0,0,0,0,0,0,0
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,12.835172,12.835172,0.168936,-0.728726,0.606745,24.965517,402.539,...,0,0,0,0,0,0,0,0,0,0
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,12.763992,12.763992,0.179945,-0.726122,0.611430,25.000000,388.512,...,0,0,0,0,0,0,0,0,0,0
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,12.673271,12.673271,0.196704,-0.722720,0.611202,25.037037,374.485,...,0,0,0,0,0,0,0,0,0,0

In [100]:
#2D RDKit test dataset descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
test_2d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_2d_rdkit.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Test_2d_RDKit_des_Caco2.csv',index=False)
print("Shape: ",test_2d_rdkit.shape, '\n')
test_2d_rdkit

Shape:  (252, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,16.271931,16.271931,0.025756,-1.930898,0.058792,23.408333,1664.156,...,0,0,0,0,0,0,0,0,0,0
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,15.516152,15.516152,0.000091,-1.679143,0.049536,24.360360,1572.049,...,0,0,0,0,0,0,0,0,0,0
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,15.993973,15.993973,0.020362,-1.750211,0.057933,24.294643,1552.024,...,0,0,0,0,0,0,0,0,0,0
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,15.804049,15.804049,0.002346,-2.970606,0.165351,26.981481,1537.344,...,0,0,0,0,0,0,0,0,0,0
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,15.545371,15.545371,0.013183,-2.948188,0.126607,27.422018,1530.953,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,12.958074,12.958074,0.156212,-0.733388,0.586385,24.903226,430.593,...,0,0,0,0,0,0,0,0,0,0
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,13.040403,13.040403,0.016783,-0.701825,0.680196,22.838710,430.593,...,0,0,0,0,0,0,0,0,0,0
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,13.114656,13.114656,0.186152,-0.689890,0.586385,24.903226,430.593,...,0,0,0,0,0,0,0,0,0,0
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,13.101637,13.101637,0.172241,-0.755076,0.586385,24.903226,430.593,...,0,0,0,0,0,0,0,0,0,0
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,12.903074,12.903074,0.161549,-0.731330,0.598056,24.933333,416.566,...,0,0,0,0,0,0,0,0,0,0

In [101]:
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=True)

def calculate_mordred_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Return None if the SMILES is invalid
    return calc(mol)

In [102]:
print('start')
#2D Mordred train descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
train_mordred_2d = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_mordred_2d.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Train_2d_Mordred_desc_Caco2.csv', index=False)
print('Shape: ',train_mordred_2d.shape)
train_mordred_2d

start

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (1007, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,150.071798,2.429231,4.858462,...,11.569599,162.262107,1663.015310,6.547304,94190,208,600.0,698.0,50.000000,26.805556
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,148.508426,2.439658,4.878720,...,11.569485,161.240399,1648.999660,6.569720,90388,207,596.0,694.0,49.750000,26.555556
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,130.882818,2.423927,4.847855,...,11.437501,150.677817,1585.815201,6.894849,69754,181,540.0,618.0,48.506944,24.125000
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,140.033288,2.434167,4.866917,...,11.543988,155.034166,1572.968359,6.526840,79884,202,566.0,663.0,49.750000,25.222222
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,132.454775,2.413793,4.827585,...,11.409840,150.603018,1565.869824,6.720471,69806,179,536.0,612.0,47.284722,24.347222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,37.874256,2.316794,4.629331,...,9.934744,65.834243,430.258006,6.619354,2632,45,148.0,164.0,11.750000,7.000000
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,37.883498,2.320955,4.638096,...,9.935228,65.834728,430.258006,6.619354,2620,45,148.0,164.0,11.750000,7.000000
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,35.896500,2.304816,4.609632,...,9.859065,63.474076,402.263091,6.385128,2286,42,138.0,153.0,10.638889,6.583333
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,34.487329,2.307278,4.602399,...,9.845805,62.359842,388.247441,6.470791,2069,41,134.0,149.0,10.388889,6.333333
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,33.357653,2.311467,4.622934,...,9.832367,61.242657,374.231791,6.565470,1880,40,130.0,145.0,10.138889,6.083333

In [103]:
#2D Mordred test descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
test_mordred_2d = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_mordred_2d.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Test_2d_Mordred_desc_Caco2.csv', index=False)
print('Shape: ',test_mordred_2d.shape)
test_mordred_2d

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (252, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,150.002370,2.434280,4.865870,...,11.590451,162.312312,1663.015310,6.547304,91297,211,602.0,703.0,50.611111,26.777778
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,133.544218,2.399797,4.799594,...,11.363578,152.529489,1571.020120,6.309318,74798,175,538.0,606.0,48.763889,24.777778
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,138.687365,2.431377,4.862754,...,11.482930,153.892806,1550.951647,6.516604,73336,187,562.0,647.0,45.645833,24.736111
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,131.842973,2.484317,4.905149,...,11.534364,163.933604,1535.873430,6.736287,67356,187,554.0,645.0,46.569444,23.486111
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,133.583282,2.474028,4.901032,...,11.515712,164.907694,1529.943702,6.538221,69591,185,556.0,644.0,46.208333,23.763889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.436032,2.302525,4.605049,...,9.885069,65.694305,430.294391,6.236151,2750,44,146.0,161.0,11.138889,7.083333
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.421813,2.317144,4.634288,...,9.891162,65.702291,430.294391,6.236151,2714,44,146.0,161.0,11.138889,7.083333
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.475166,2.317701,4.635401,...,9.885578,65.694814,430.294391,6.236151,2660,44,146.0,161.0,11.138889,7.083333
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,38.446535,2.317849,4.635698,...,9.885069,65.694305,430.294391,6.236151,2660,44,146.0,161.0,11.138889,7.083333
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,37.048032,2.303371,4.602630,...,9.872152,64.585516,416.278741,6.307254,2503,43,142.0,157.0,10.888889,6.833333

In [104]:
#RDKit 3d descriptors
def generate_3d_descriptors(smiles):
    # Convert SMILES to a molecule object
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    
    # Add hydrogens
    mol = Chem.AddHs(mol)
    
    # Generate 3D coordinates for the molecule
    AllChem.EmbedMolecule(mol)
    
    try:
        descriptors = Descriptors3D.CalcMolDescriptors3D(mol)
        return descriptors
    except Exception as e:
        print(f"Error calculating descriptors for SMILES '{smiles}': {e}")
        return None

In [105]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Train_Caco2.csv")
descriptor_data = []
for smiles in tqdm(df_train['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors =generate_3d_descriptors(smiles) 
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

3d_descriptors: 100%|██████████| 1007/1007 [28:42<00:00,  1.71s/smiles]

In [106]:
descriptor_df = pd.DataFrame(descriptor_data)
descriptor_df

,PMI1,PMI2,PMI3,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF
0,40359.396070,100703.602332,131887.957261,0.306013,0.763554,9.055872,0.000019,0.952027,0.348751,0.131220,1.614850
1,46241.303376,91821.486727,125376.707133,0.368819,0.732365,8.934423,0.000016,0.929501,0.272792,0.157343,1.734564
2,44278.306580,65633.880188,87002.150360,0.508933,0.754394,7.874394,0.000017,0.860806,0.141224,0.351948,2.235052
3,38096.457056,83986.903799,110868.745062,0.343618,0.757535,8.602243,0.000020,0.939110,0.299424,0.163725,1.680872
4,48480.358351,60718.389783,99805.913198,0.485746,0.608365,8.165200,0.000013,0.874100,0.197419,0.152552,1.562147
...,...,...,...,...,...,...,...,...,...,...,...
1002,2773.420313,5558.268358,7436.905587,0.372927,0.747390,4.279275,0.000269,0.927861,0.265698,0.184515,0.901186
1003,2769.517696,4707.235680,6284.754058,0.440672,0.748993,3.997668,0.000270,0.897668,0.196434,0.302609,1.189194
1004,1345.556715,6066.663542,6605.483068,0.203703,0.918428,4.172722,0.000683,0.979033,0.511420,0.229280,1.056432
1005,1422.443447,5131.034159,5822.340542,0.244308,0.881267,3.990890,0.000620,0.969698,0.438632,0.234841,1.028176
1006,1628.813441,4131.523260,4467.025440,0.364630,0.924894,3.695299,0.000568,0.931152,0.275941,0.368639,1.194703

In [107]:
num_columns = descriptor_df.shape[1]
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
train_3d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , train_3d_rdkit.shape)
train_3d_rdkit.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Train_3d_RDKit_desc_Caco2.csv',index=False)
print('Shape after: ',train_3d_rdkit.shape)
train_3d_rdkit

Shape before: (1007, 14)
Shape after:  (1007, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,2064,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.19,40359.396070,100703.602332,131887.957261,0.306013,0.763554,9.055872,0.000019,0.952027,0.348751,0.131220,1.614850
1,2067,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.24,46241.303376,91821.486727,125376.707133,0.368819,0.732365,8.934423,0.000016,0.929501,0.272792,0.157343,1.734564
2,1914,CCCCN1CC(=O)N(C)[C@@H](CC(C)C)C(=O)N[C@@H](CCC...,-8.00,44278.306580,65633.880188,87002.150360,0.508933,0.754394,7.874394,0.000017,0.860806,0.141224,0.351948,2.235052
3,2026,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[...,-5.64,38096.457056,83986.903799,110868.745062,0.343618,0.757535,8.602243,0.000020,0.939110,0.299424,0.163725,1.680872
4,1920,CCCCN1CC(=O)N(C)[C@@H](Cc2cccc(Cl)c2)C(=O)N[C@...,-7.05,48480.358351,60718.389783,99805.913198,0.485746,0.608365,8.165200,0.000013,0.874100,0.197419,0.152552,1.562147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,5605,CC(C)C[C@@H]1NC(=O)CN(C)C(=O)CCCCNC(=O)[C@H](C...,-5.32,2773.420313,5558.268358,7436.905587,0.372927,0.747390,4.279275,0.000269,0.927861,0.265698,0.184515,0.901186
1003,5602,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)CCCCNC(=O)[C@...,-5.45,2769.517696,4707.235680,6284.754058,0.440672,0.748993,3.997668,0.000270,0.897668,0.196434,0.302609,1.189194
1004,2469,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.19,1345.556715,6066.663542,6605.483068,0.203703,0.918428,4.172722,0.000683,0.979033,0.511420,0.229280,1.056432
1005,2468,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.11,1422.443447,5131.034159,5822.340542,0.244308,0.881267,3.990890,0.000620,0.969698,0.438632,0.234841,1.028176
1006,2467,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-5.33,1628.813441,4131.523260,4467.025440,0.364630,0.924894,3.695299,0.000568,0.931152,0.275941,0.368639,1.194703

In [108]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/Caco2/data/Test_Caco2.csv")
descriptor_data = []
for smiles in tqdm(df_test['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors = generate_3d_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

descriptor_data

3d_descriptors: 100%|██████████| 252/252 [07:11<00:00,  1.71s/smiles]

[{'PMI1': 38360.81131055237,
  'PMI2': 94769.01334446955,
  'PMI3': 121802.79749171948,
  'NPR1': 0.31494195618257664,
  'NPR2': 0.7780528468643114,
  'RadiusOfGyration': 8.751866635610886,
  'InertialShapeFactor': 2.028249195684459e-05,
  'Eccentricity': 0.9491109335772567,
  'Asphericity': 0.33467205409518863,
  'SpherocityIndex': 0.15887823190200706,
  'PBF': 1.7183875699610973},
 {'PMI1': 51411.476132996824,
  'PMI2': 61298.10711497175,
  'PMI3': 99240.40952429858,
  'NPR1': 0.5180498184099991,
  'NPR2': 0.6176728553297957,
  'RadiusOfGyration': 8.210482237560546,
  'InertialShapeFactor': 1.201429917577025e-05,
  'Eccentricity': 0.8553504461011094,
  'Asphericity': 0.1702908412499738,
  'SpherocityIndex': 0.22793069431999707,
  'PBF': 1.9279330244731114},
 {'PMI1': 46406.553548840326,
  'PMI2': 53110.909967086,
  'PMI3': 86105.00641767339,
  'NPR1': 0.5389530235179821,
  'NPR2': 0.6168155857216774,
  'RadiusOfGyration': 7.73305429398572,
  'InertialShapeFactor': 1.3291562043548723e-05,
  'Eccentricity': 0.8423358228407631,
  'Asphericity': 0.1572759137120076,
  'SpherocityIndex': 0.26350130899459556,
  'PBF': 1.9415503231954436},
 {'PMI1': 35517.05017403424,
  'PMI2': 67187.13230979507,
  'PMI3': 88176.59903848854,
  'NPR1': 0.4027945119376998,
  'NPR2': 0.7619610309586594,
  'RadiusOfGyration': 7.879171903652775,
  'InertialShapeFactor': 2.145338723866525e-05,
  'Eccentricity': 0.9152904354099143,
  'Asphericity': 0.23145465579938998,
  'SpherocityIndex': 0.23582983460202817,
  'PBF': 1.8465148076518947},
 {'PMI1': 45705.03532333533,
  'PMI2': 48149.56162296343,
  'PMI3': 76960.88806973807,
  'NPR1': 0.5938735436877981,
  'NPR2': 0.6256367725296093,
  'RadiusOfGyration': 7.469089995669028,
  'InertialShapeFactor': 1.3688574313609202e-05,
  'Eccentricity': 0.804558396953072,
  'Asphericity': 0.12427177501963468,
  'SpherocityIndex': 0.34795219138294387,
  'PBF': 2.2372319824069407},
 {'PMI1': 40271.98810907377,
  'PMI2': 61667.25223455177,
  'PMI3': 90078.83305898585,
  'NPR1': 0.44707493138485344,
  'NPR2': 0.6845920416638893,
  'RadiusOfGyration': 7.955420179087797,
  'InertialShapeFactor': 1.69992114570982e-05,
  'Eccentricity': 0.8944965096227198,
  'Asphericity': 0.20317881798869578,
  'SpherocityIndex': 0.20445254158334958,
  'PBF': 1.7609795811307976},
 {'PMI1': 47778.04085006985,
  'PMI2': 50001.16361621661,
  'PMI3': 76934.39538995463,
  'NPR1': 0.6210231536609729,
  'NPR2': 0.649919497810797,
  'RadiusOfGyration': 7.606299165914369,
  'InertialShapeFactor': 1.3602891333495247e-05,
  'Eccentricity': 0.7837922190331948,
  'Asphericity': 0.10355069225093674,
  'SpherocityIndex': 0.33970786378471224,
  'PBF': 2.0396324208606957},
 {'PMI1': 36582.37583492503,
  'PMI2': 50485.09227572368,
  'PMI3': 72268.63071426627,
  'NPR1': 0.5061999303620879,
  'NPR2': 0.6985754645792343,
  'RadiusOfGyration': 7.280586367378336,
  'InertialShapeFactor': 1.9095956690497597e-05,
  'Eccentricity': 0.8624161585345078,
  'Asphericity': 0.15293189228391296,
  'SpherocityIndex': 0.3203638690719456,
  'PBF': 1.9816380801700573},
 {'PMI1': 34885.49229157833,
  'PMI2': 74781.9200844241,
  'PMI3': 101415.13080624447,
  'NPR1': 0.3439870561152036,
  'NPR2': 0.7373842491737882,
  'RadiusOfGyration': 8.388324663026062,
  'InertialShapeFactor': 2.1137275146086997e-05,
  'Eccentricity': 0.9389743900795142,
  'Asphericity': 0.3019691990722783,
  'SpherocityIndex': 0.14379888743202984,
  'PBF': 1.546539301966477},
 {'PMI1': 43019.448952450184,
  'PMI2': 49825.585662429854,
  'PMI3': 81381.36639975781,
  'NPR1': 0.5286154663603462,
  'NPR2': 0.6122480841336443,
  'RadiusOfGyration': 7.630142466180621,
  'InertialShapeFactor': 1.4231890436587603e-05,
  'Eccentricity': 0.8488614072536422,
  'Asphericity': 0.16562285313277172,
  'SpherocityIndex': 0.23633135173956743,
  'PBF': 1.878534234889927},
 {'PMI1': 36163.10103578995,
  'PMI2': 51571.45281930897,
  'PMI3': 74882.31023196601,
  'NPR1': 0.48293249665730165,
  'NPR2': 0.6887000769548103,
  'RadiusOfGyration': 7.381285634729838,
  'InertialShapeFactor': 1.9044275994838402e-05,
  'Eccentricity': 0.8756575835749643,
  'Asphericity': 0.172437563116948,
  'SpherocityIndex': 0.2882130719861061,
  'PBF': 1.9635549719547891},
 {'PMI1': 41602.95304469093,
  'PMI2': 55490.44988919161,
  'PMI3': 85363.20473545435,
  'NPR1': 0.4873640015463449,
  'NPR2': 0.6500511556608004,
  'RadiusOfGyration': 7.830202006436183,
  'InertialShapeFactor': 1.562512052840334e-05,
  'Eccentricity': 0.8731989063190209,
  'Asphericity': 0.18024430140102776,
  'SpherocityIndex': 0.22132460413814342,
  'PBF': 1.815610243269021},
 {'PMI1': 40095.087751361614,
  'PMI2': 55837.05623812331,
  'PMI3': 87711.8493644294,
  'NPR1': 0.4571228179760823,
  'NPR2': 0.6365964991358103,
  'RadiusOfGyration': 7.858370223253156,
  'InertialShapeFactor': 1.5877169370060593e-05,
  'Eccentricity': 0.8894035806570635,
  'Asphericity': 0.20940879576596885,
  'SpherocityIndex': 0.18105627619291365,
  'PBF': 1.6637614468630146},
 {'PMI1': 47892.044928448035,
  'PMI2': 55549.46112961207,
  'PMI3': 96633.71372977251,
  'NPR1': 0.49560389516203246,
  'NPR2': 0.5748455584036762,
  'RadiusOfGyration': 8.207824804327608,
  'InertialShapeFactor': 1.200294452372018e-05,
  'Eccentricity': 0.8685486624825469,
  'Asphericity': 0.20596015368271378,
  'SpherocityIndex': 0.13081814079263032,
  'PBF': 1.483341711898096},
 {'PMI1': 38284.392803445335,
  'PMI2': 55079.65781033537,
  'PMI3': 74075.2462873484,
  'NPR1': 0.5168311240564052,
  'NPR2': 0.7435636136351617,
  'RadiusOfGyration': 7.511427890283562,
  'InertialShapeFactor': 1.9422108049425457e-05,
  'Eccentricity': 0.8560873724139334,
  'Asphericity': 0.13724526454071723,
  'SpherocityIndex': 0.3796676635880504,
  'PBF': 2.2202154638266443},
 {'PMI1': 36549.381084293644,
  'PMI2': 65563.11938375163,
  'PMI3': 91496.82039635644,
  'NPR1': 0.39946066897149907,
  'NPR2': 0.7165617242188065,
  'RadiusOfGyration': 8.082500080863928,
  'InertialShapeFactor': 1.9605303919270314e-05,
  'Eccentricity': 0.9167503334849911,
  'Asphericity': 0.24189019914225462,
  'SpherocityIndex': 0.22171186400182732,
  'PBF': 1.851505944228188},
 {'PMI1': 46680.29683464786,
  'PMI2': 53766.49508657951,
  'PMI3': 89708.99600349671,
  'NPR1': 0.5203524608928667,
  'NPR2': 0.5993434045843494,
  'RadiusOfGyration': 8.01428459092217,
  'InertialShapeFactor': 1.283932290977838e-05,
  'Eccentricity': 0.8539515890510055,
  'Asphericity': 0.1766380029693801,
  'SpherocityIndex': 0.22230127021348908,
  'PBF': 1.8363322046252548},
 {'PMI1': 45844.701475703674,
  'PMI2': 54580.81301168884,
  'PMI3': 88921.73203126455,
  'NPR1': 0.5155623988473914,
  'NPR2': 0.6138073535555789,
  'RadiusOfGyration': 8.002687434752135,
  'InertialShapeFactor': 1.338883957791455e-05,
  'Eccentricity': 0.8568520367570608,
  'Asphericity': 0.173558851369186,
  'SpherocityIndex': 0.20647360339612963,
  'PBF': 1.830213374434823},
 {'PMI1': 41547.94008519599,
  'PMI2': 56804.978598049594,
  'PMI3': 89009.24742043085,
  'NPR1': 0.466782287113903,
  'NPR2': 0.6381918760613045,
  'RadiusOfGyration': 7.972449826310777,
  'InertialShapeFactor': 1.5360373456606086e-05,
  'Eccentricity': 0.8843722612320638,
  'Asphericity': 0.20068422521448928,
  'SpherocityIndex': 0.18791152182350085,
  'PBF': 1.7101195448143534},
 {'PMI1': 38848.42190483569,
  'PMI2': 49602.631245497825,
  'PMI3': 75234.74703374952,
  'NPR1': 0.516362763702903,
  'NPR2': 0.6593048185999297,
  'RadiusOfGyration': 7.456691727612551,
  'InertialShapeFactor': 1.6971212375498376e-05,
  'Eccentricity': 0.8563699529181882,
  'Asphericity': 0.15650504326684944,
  'SpherocityIndex': 0.26785590675031956,
  'PBF': 1.9747644329939902},
 {'PMI1': 35876.587161033465,
  'PMI2': 65599.64842812825,
  'PMI3': 87727.19151482166,
  'NPR1': 0.40895629441154574,
  'NPR2': 0.7477687054081181,
  'RadiusOfGyration': 8.02143622825104,
  'InertialShapeFactor': 2.0842804864680388e-05,
  'Eccentricity': 0.9125539706018363,
  'Asphericity': 0.22691663631460507,
  'SpherocityIndex': 0.2683429723096699,
  'PBF': 2.0256107396511887},
 {'PMI1': 43232.544226627106,
  'PMI2': 53052.35888466327,
  'PMI3': 84452.53624830453,
  'NPR1': 0.5119152857590472,
  'NPR2': 0.6281914225604841,
  'RadiusOfGyration': 7.840835868215503,
  'InertialShapeFactor': 1.4530521712242379e-05,
  'Eccentricity': 0.8590359365045407,
  'Asphericity': 0.17029852253348324,
  'SpherocityIndex': 0.22799158411199663,
  'PBF': 1.8837862652938542},
 {'PMI1': 43440.14526153446,
  'PMI2': 54028.24742751349,
  'PMI3': 88443.70043508675,
  'NPR1': 0.49116155303132475,
  'NPR2': 0.6108772830821062,
  'RadiusOfGyration': 7.9577472901536215,
  'InertialShapeFactor': 1.4062505532711192e-05,
  'Eccentricity': 0.8710684983535205,
  'Asphericity': 0.19221837493854202,
  'SpherocityIndex': 0.1634786403160841,
  'PBF': 1.6116406080988464},
 {'PMI1': 36685.163770592764,
  'PMI2': 49731.564389915984,
  'PMI3': 72960.26459040295,
  'NPR1': 0.5028101799869056,
  'NPR2': 0.6816253294736211,
  'RadiusOfGyration': 7.370352106862732,
  'InertialShapeFactor': 1.858040851980657e-05,
  'Eccentricity': 0.8643968549812844,
  'Asphericity': 0.1594946626250089,
  'SpherocityIndex': 0.2686054405339104,
  'PBF': 1.872876306897526},
 {'PMI1': 37052.02559680576,
  'PMI2': 60572.97148256201,
  'PMI3': 79595.60199594659,
  'NPR1': 0.4655034281754994,
  'NPR2': 0.7610090251675801,
  'RadiusOfGyration': 7.774987632170911,
  'InertialShapeFactor': 2.0538931756356833e-05,
  'Eccentricity': 0.8850460769682321,
  'Asphericity': 0.1735306809805954,
  'SpherocityIndex': 0.3310371202827691,
  'PBF': 2.127342086121447},
 {'PMI1': 32903.05554792416,
  'PMI2': 70816.34163407696,
  'PMI3': 98640.2701454388,
  'NPR1': 0.33356615406071677,
  'NPR2': 0.7179252604404142,
  'RadiusOfGyration': 8.312508409244261,
  'InertialShapeFactor': 2.1819410036090336e-05,
  'Eccentricity': 0.942726694681519,
  'Asphericity': 0.3190749591020187,
  'SpherocityIndex': 0.1003124905003578,
  'PBF': 1.2936718710230313},
 {'PMI1': 31398.798115699847,
  'PMI2': 54026.55698184108,
  'PMI3': 70587.85939832161,
  'NPR1': 0.44481867538324055,
  'NPR2': 0.7653802997052732,
  'RadiusOfGyration': 7.309819768187475,
  'InertialShapeFactor': 2.4376101813991796e-05,
  'Eccentricity': 0.8956206485059951,
  'Asphericity': 0.1908022177177871,
  'SpherocityIndex': 0.32152112538151,
  'PBF': 2.0904243265750373},
 {'PMI1': 37199.38798687755,
  'PMI2': 60036.60098659361,
  'PMI3': 86739.51813489465,
  'NPR1': 0.42886320775988396,
  'NPR2': 0.6921481958572391,
  'RadiusOfGyration': 7.943281377366019,
  'InertialShapeFactor': 1.860644040975624e-05,
  'Eccentricity': 0.9033694421607931,
  'Asphericity': 0.21796968536012454,
  'SpherocityIndex': 0.18384711103571713,
  'PBF': 1.6673846320962533},
 {'PMI1': 37849.37013436058,
  'PMI2': 60558.922893007635,
  'PMI3': 89112.75996699496,
  'NPR1': 0.4247356960818967,
  'NPR2': 0.6795763358180925,
  'RadiusOfGyration': 8.024034643755147,
  'InertialShapeFactor': 1.795475944264543e-05,
  'Eccentricity': 0.9053173965377154,
  'Asphericity': 0.22517143526101477,
  'SpherocityIndex': 0.1863543276754729,
  'PBF': 1.634773787543396},
 {'PMI1': 35888.23279476054,
  'PMI2': 55791.64584468935,
  'PMI3': 76942.70409674359,
  'NPR1': 0.46642801570421305,
  'NPR2': 0.7251063827252543,
  'RadiusOfGyration': 7.614149387061044,
  'InertialShapeFactor': 2.0204571979680076e-05,
  'Eccentricity': 0.8845591592235256,
  'Asphericity': 0.17788707144695853,
  'SpherocityIndex': 0.24387234161192403,
  'PBF': 1.7940439045673724},
 {'PMI1': 34185.5488614629,
  'PMI2': 49868.661195435554,
  'PMI3': 64960.086446673195,
  'NPR1': 0.5262546700815489,
  'NPR2': 0.7676815706883882,
  'RadiusOfGyration': 7.162621435045064,
  'InertialShapeFactor': 2.245631842271778e-05,
  'Eccentricity': 0.8503270089896946,
  'Asphericity': 0.1279681711620664,
  'SpherocityIndex': 0.49058080903221796,
  'PBF': 2.497500494779734},
 {'PMI1': 40243.20213207312,
  'PMI2': 54137.04611832238,
  'PMI3': 88384.27272858248,
  'NPR1': 0.45532084939653433,
  'NPR2': 0.6125189974077262,
  'RadiusOfGyration': 7.936138068227054,
  'InertialShapeFactor': 1.5220433885889995e-05,
  'Eccentricity': 0.890327425223338,
  'Asphericity': 0.22054835977850293,
  'SpherocityIndex': 0.11707854427923771,
  'PBF': 1.347335161439327},
 {'PMI1': 36545.37124157296,
  'PMI2': 50102.25269566314,
  'PMI3': 76003.24698504033,
  'NPR1': 0.48083960477065096,
  'NPR2': 0.6592120032125041,
  'RadiusOfGyration': 7.489495443513315,
  'InertialShapeFactor': 1.803818050868788e-05,
  'Eccentricity': 0.8768085734548928,
  'Asphericity': 0.18231310688928967,
  'SpherocityIndex': 0.2509583751303358,
  'PBF': 1.8590768300643987},
 {'PMI1': 35558.73629565814,
  'PMI2': 48980.98026567569,
  'PMI3': 74393.10873677679,
  'NPR1': 0.47798427703128654,
  'NPR2': 0.6584074936158915,
  'RadiusOfGyration': 7.407344422769782,
  'InertialShapeFactor': 1.8516054342917848e-05,
  'Eccentricity': 0.8783683913432213,
  'Asphericity': 0.18480398899296105,
  'SpherocityIndex': 0.260563401924016,
  'PBF': 1.8156182555425722},
 {'PMI1': 38530.145775643665,
  'PMI2': 46431.046891908794,
  'PMI3': 68738.7160597593,
  'NPR1': 0.5605304839000302,
  'NPR2': 0.6754715472361033,
  'RadiusOfGyration': 7.285455707711936,
  'InertialShapeFactor': 1.7530988623019793e-05,
  'Eccentricity': 0.8281337914967591,
  'Asphericity': 0.12467280172974614,
  'SpherocityIndex': 0.3545514178191984,
  'PBF': 2.151456621732103},
 {'PMI1': 41108.58941356156,
  'PMI2': 44859.13584746126,
  'PMI3': 68969.8601981503,
  'NPR1': 0.5960370123334547,
  'NPR2': 0.6504165111917152,
  'RadiusOfGyration': 7.316135029298613,
  'InertialShapeFactor': 1.5821912657921205e-05,
  'Eccentricity': 0.802956960196877,
  'Asphericity': 0.11427674144570428,
  'SpherocityIndex': 0.34576531509830905,
  'PBF': 2.0950875856181694},
 {'PMI1': 30193.773046277576,
  'PMI2': 54719.89578031281,
  'PMI3': 69583.94594558659,
  'NPR1': 0.4339186666690126,
  'NPR2': 0.7863867884569639,
  'RadiusOfGyration': 7.3094276349794,
  'InertialShapeFactor': 2.6044667794636985e-05,
  'Eccentricity': 0.9009520468461052,
  'Asphericity': 0.1989195512847654,
  'SpherocityIndex': 0.3371681502117087,
  'PBF': 2.096026393123864},
 {'PMI1': 37476.20829487191,
  'PMI2': 47754.36465904322,
  'PMI3': 71878.50660810938,
  'NPR1': 0.5213826784019998,
  'NPR2': 0.6643761384666211,
  'RadiusOfGyration': 7.375973401846223,
  'InertialShapeFactor': 1.772794443982028e-05,
  'Eccentricity': 0.8533229767575444,
  'Asphericity': 0.15161146735681272,
  'SpherocityIndex': 0.28881044086363594,
  'PBF': 1.956016207632387},
 {'PMI1': 41911.91601067708,
  'PMI2': 53028.33258788604,
  'PMI3': 79587.6494504256,
  'NPR1': 0.5266133162631423,
  'NPR2': 0.6662884625197644,
  'RadiusOfGyration': 7.774128779505712,
  'InertialShapeFactor': 1.589735153959621e-05,
  'Eccentricity': 0.850104943600692,
  'Asphericity': 0.14763190183729644,
  'SpherocityIndex': 0.291298090498697,
  'PBF': 2.0901683843553758},
 {'PMI1': 38165.402128645685,
  'PMI2': 60339.41267945854,
  'PMI3': 88572.89516282454,
  'NPR1': 0.43089256660839415,
  'NPR2': 0.6812401533057706,
  'RadiusOfGyration': 8.04900236045301,
  'InertialShapeFactor': 1.7849678381731352e-05,
  'Eccentricity': 0.9024032336165638,
  'Asphericity': 0.21885387841746295,
  'SpherocityIndex': 0.21231387242768374,
  'PBF': 1.7538589116837904},
 {'PMI1': 35517.90109409067,
  'PMI2': 61683.42456867341,
  'PMI3': 85309.33358321853,
  'NPR1': 0.4163424985549003,
  'NPR2': 0.7230559890437047,
  'RadiusOfGyration': 7.954514233410945,
  'InertialShapeFactor': 2.0357508939738675e-05,
  'Eccentricity': 0.9092078551668274,
  'Asphericity': 0.22347578618848588,
  'SpherocityIndex': 0.23644521600199958,
  'PBF': 1.8965753631096232},
 {'PMI1': 37507.87223649456,
  'PMI2': 49644.29472372809,
  'PMI3': 76295.90370161895,
  'NPR1': 0.49161056382767065,
  'NPR2': 0.6506809974737171,
  'RadiusOfGyration': 7.528457016378707,
  'InertialShapeFactor': 1.7347851495575243e-05,
  'Eccentricity': 0.8708151661133606,
  'Asphericity': 0.17683611188760795,
  'SpherocityIndex': 0.2439256124134048,
  'PBF': 1.8870488535594094},
 {'PMI1': 33972.327331373875,
  'PMI2': 58596.949325376816,
  'PMI3': 85440.72334543832,
  'NPR1': 0.3976128244376299,
  'NPR2': 0.6858199115247227,
  'RadiusOfGyration': 7.861320408275751,
  'InertialShapeFactor': 2.018760460050552e-05,
  'Eccentricity': 0.9175532910096996,
  'Asphericity': 0.25094743726579544,
  'SpherocityIndex': 0.1629476148208455,
  'PBF': 1.5533048739188289},
 {'PMI1': 40497.427950778234,
  'PMI2': 49510.80867995143,
  'PMI3': 79756.56886512777,
  'NPR1': 0.5077629156698221,
  'NPR2': 0.6207740551587244,
  'RadiusOfGyration': 7.680547294866073,
  'InertialShapeFactor': 1.532872793583907e-05,
  'Eccentricity': 0.8614968493677044,
  'Asphericity': 0.17608045349127627,
  'SpherocityIndex': 0.19915178032473949,
  'PBF': 1.617603552335531},
 {'PMI1': 40035.62090555843,
  'PMI2': 50132.55832532909,
  'PMI3': 81993.25420314168,
  'NPR1': 0.48827944804298806,
  'NPR2': 0.6114229617124795,
  'RadiusOfGyration': 7.737809716323889,
  'InertialShapeFactor': 1.5271974004219607e-05,
  'Eccentricity': 0.8726873326792562,
  'Asphericity': 0.1941658486402224,
  'SpherocityIndex': 0.19521953317819457,
  'PBF': 1.6368852571035948},
 {'PMI1': 33842.77818884625,
  'PMI2': 48163.65097202876,
  'PMI3': 67389.5252355965,
  'NPR1': 0.5021964180713624,
  'NPR2': 0.7147053018053872,
  'RadiusOfGyration': 7.2126857540527585,
  'InertialShapeFactor': 2.111839925839589e-05,
  'Eccentricity': 0.8647535820546183,
  'Asphericity': 0.15234502973827313,
  'SpherocityIndex': 0.3078572277463508,
  'PBF': 1.899988150152997},
 {'PMI1': 32413.293776498624,
  'PMI2': 61464.91830898618,
  'PMI3': 85129.86999345246,
  'NPR1': 0.38075112506328984,
  'NPR2': 0.7220135343060384,
  'RadiusOfGyration': 7.899605625915289,
  'InertialShapeFactor': 2.2275228777568327e-05,
  'Eccentricity': 0.9246775550228519,
  'Asphericity': 0.26108339430254485,
  'SpherocityIndex': 0.17956313461803228,
  'PBF': 1.6252927879114138},
 {'PMI1': 33572.06647334029,
  'PMI2': 46799.306479480525,
  'PMI3': 67537.2393369877,
  'NPR1': 0.4970897064037097,
  'NPR2': 0.6929407677735836,
  'RadiusOfGyration': 7.181755741717355,
  'InertialShapeFactor': 2.0640396632237415e-05,
  'Eccentricity': 0.8676991551151089,
  'Asphericity': 0.160776899424469,
  'SpherocityIndex': 0.30707294920499467,
  'PBF': 1.9866994911137759},
 {'PMI1': 37325.172436688175,
  'PMI2': 48853.68132671696,
  'PMI3': 72231.38925765759,
  'NPR1': 0.5167444904533822,
  'NPR2': 0.6763497397571894,
  'RadiusOfGyration': 7.432339323766172,
  'InertialShapeFactor': 1.8120471938995847e-05,
  'Eccentricity': 0.8561396682703555,
  'Asphericity': 0.15126185215638976,
  'SpherocityIndex': 0.30202021046864513,
  'PBF': 1.9645951612103838},
 {'PMI1': 35697.019618747225,
  'PMI2': 49961.604346429966,
  'PMI3': 71428.2404059434,
  'NPR1': 0.4997605907113588,
  'NPR2': 0.6994657023956697,
  'RadiusOfGyration': 7.40376979017414,
  'InertialShapeFactor': 1.959451264744598e-05,
  'Eccentricity': 0.8661635826862232,
  'Asphericity': 0.15731826251269257,
  'SpherocityIndex': 0.30702352154274665,
  'PBF': 2.0030882118536173},
 {'PMI1': 27081.218336887396,
  'PMI2': 44581.427084885094,
  'PMI3': 52892.27292563351,
  'NPR1': 0.5120070823003497,
  'NPR2': 0.8428722121200302,
  'RadiusOfGyration': 6.594964082379344,
  'InertialShapeFactor': 3.1123866054872125e-05,
  'Eccentricity': 0.8589812266134126,
  'Asphericity': 0.1342713495866132,
  'SpherocityIndex': 0.4741158857329761,
  'PBF': 2.3030699215259967},
 {'PMI1': 46389.19347742158,
  'PMI2': 52444.582464324725,
  'PMI3': 93618.23930201212,
  'NPR1': 0.49551448332381254,
  'NPR2': 0.5601962059459235,
  'RadiusOfGyration': 8.2024213996646,
  'InertialShapeFactor': 1.2076006585856695e-05,
  'Eccentricity': 0.8685996758094808,
  'Asphericity': 0.21397182651378083,
  'SpherocityIndex': 0.10452009482070779,
  'PBF': 1.3584149493290911},
 {'PMI1': 40676.898050665994,

In [109]:
descriptor_df = pd.DataFrame(descriptor_data)

In [110]:
num_columns = descriptor_df.shape[1]
print('num_columns',num_columns)
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
print('descriptor_df.columns',descriptor_df.columns)
test_3d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , test_3d_rdkit.shape)
test_3d_rdkit.to_csv('/home/users/akshay/PCPpred/Caco2/features/Descriptors/Test_3d_RDKit_desc_Caco2.csv',index=False)
print('Shape after: ',test_3d_rdkit.shape)
test_3d_rdkit

num_columns 11
descriptor_df.columns Index(['3d_rdkit_1', '3d_rdkit_2', '3d_rdkit_3', '3d_rdkit_4', '3d_rdkit_5',
       '3d_rdkit_6', '3d_rdkit_7', '3d_rdkit_8', '3d_rdkit_9', '3d_rdkit_10',
       '3d_rdkit_11'],
      dtype='object')
Shape before: (252, 14)
Shape after:  (252, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,2065,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-7.22,38360.811311,94769.013344,121802.797492,0.314942,0.778053,8.751867,0.000020,0.949111,0.334672,0.158878,1.718388
1,8066,CC[C@H]1C(=O)N[C@@H](COCCC(C)C)C(=O)N(C)[C@@H]...,-6.21,51411.476133,61298.107115,99240.409524,0.518050,0.617673,8.210482,0.000012,0.855350,0.170291,0.227931,1.927933
2,2068,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-7.24,46406.553549,53110.909967,86105.006418,0.538953,0.616816,7.733054,0.000013,0.842336,0.157276,0.263501,1.941550
3,2231,CC(C)C[C@H]1C(=O)N[C@@H](COC(C)(C)C)C(=O)N(C)[...,-5.92,35517.050174,67187.132310,88176.599038,0.402795,0.761961,7.879172,0.000021,0.915290,0.231455,0.235830,1.846515
4,2230,CC(C)C[C@H]1C(=O)N[C@H](C(=O)N2CCCCC2)CC(=O)N[...,-5.96,45705.035323,48149.561623,76960.888070,0.593874,0.625637,7.469090,0.000014,0.804558,0.124272,0.347952,2.237232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2485,CC(C)C[C@H]1NC(=O)[C@H](C)NC(=O)[C@@H](Cc2cccc...,-6.00,3042.322578,4867.390132,7174.589188,0.424041,0.678421,4.185180,0.000223,0.905643,0.226159,0.185612,0.951829
248,2489,CC(C)CN1CC(=O)NCCCCCCN[C@@H](Cc2ccccc2)C(=O)N[...,-3.99,2236.627781,5679.477413,6589.801379,0.339407,0.861859,4.104157,0.000385,0.940639,0.300654,0.351507,1.144016
249,2478,CC(C)C[C@@H]1NC(=O)[C@H](C)NCCCCCCNC(=O)[C@H](...,-5.24,2990.499642,4863.755105,7259.835582,0.411924,0.669954,4.189310,0.000224,0.911218,0.240571,0.168687,0.922016
250,2479,CC(C)C[C@@H]1NCCCCCCNC(=O)[C@H](C)NC(=O)[C@H](...,-4.77,2486.799820,4734.805218,5907.809024,0.420934,0.801449,3.904579,0.000322,0.907091,0.210380,0.357762,1.218799
251,2470,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2cccc...,-4.71,1628.269643,6418.747349,7212.577157,0.225754,0.889938,4.279712,0.000547,0.974184,0.470364,0.215873,1.053953

In [112]:
import os

#Train MOL structure generator
input_file = '/home/users/akshay/PCPpred/Caco2/data/Train_caco2.smi'
output_dir = '/home/users/akshay/PCPpred/Caco2/data/Train_mol_Caco2'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 1007/1007 [28:35<00:00,  1.70s/it]

3D conformations generated and saved.

In [113]:
directory_path = '/home/users/akshay/PCPpred/Caco2/data/Train_mol_Caco2'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 1007

In [114]:
#Test MOL structure generator
input_file = '/home/users/akshay/PCPpred/Caco2/data/Test_caco2.smi'
output_dir = '/home/users/akshay/PCPpred/Caco2/data/Test_mol_Caco2'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 252/252 [07:15<00:00,  1.73s/it]

3D conformations generated and saved.

In [115]:
directory_path = '/home/users/akshay/PCPpred/Caco2/data/Test_mol_Caco2'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 252