In [1]:
#Monomeric features
import pandas as pd
import numpy as np
import ast

In [2]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,"['L', 'meA', 'L', 'dP', 'meF', 'L', 'meA', 'L'...",1139.494
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,"['L', 'meA', 'L', 'Me_dF', 'P', 'L', 'meA', 'L...",1139.494
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,"['L', 'meF', 'L', 'dP', 'meA', 'L', 'meF', 'L'...",1139.494
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,"['L', 'meA', 'L', 'Me_dA', 'meF', 'L', 'meA', ...",1115.472
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,"['L', 'dP', 'Mono38', 'L', 'meA', 'F', 'dP', '...",1091.406
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,"['L', 'dP', 'meL', 'A', 'Mono38', 'F', 'dP', '...",1091.406
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,"['L', 'dP', 'meL', 'A', 'cHexCH2_Gly', 'F', 'd...",1089.434
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,"['L', 'dP', 'cHexCH2_Gly', 'L', 'meA', 'F', 'd...",1089.434
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,"['L', 'meA', 'Nva', 'dP', 'Me_Abu', 'Cha', 'me...",1048.403
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,"['L', 'meL', 'L', 'Me_dA', 'meA', 'L', 'meL', ...",1047.438
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,"['L', 'meA', 'L', 'dP', 'meV', 'L', 'meA', 'L'...",1043.406
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,"['L', 'meL', 'L', 'Sar', 'P', 'L', 'meL', 'L',...",1043.406
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,"['L', 'meA', 'Nva', 'dP', 'Et_Gly', 'Cha', 'me...",1034.376
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,"['ac-', 'P', 'meL', 'T', 'Me_dL', 'meL', 'L', ...",1030.363
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,"['ac-', 'dP', 'Me_dL', 'T', 'Me_dL', 'meL', 'm...",1030.363
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,"['ac-', 'P', 'Me_dL', 'T', 'meL', 'L', 'Me_dL'...",1030.363
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1016.336
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,"['ac-', 'P', 'meL', 'T', 'meL', 'L', 'meL', 'A...",1016.336
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,"['L', 'dP', 'Mono38', 'L', 'meA', 'A', 'dP', '...",1015.308
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,"['L', 'dP', 'meL', 'A', 'Mono38', 'A', 'dP', '...",1015.308
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,"['L', 'meA', 'L', 'dP', 'Me_Nva', 'Abu', 'meA'...",1008.338
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,"['L', 'Pr_Gly', 'Nva', 'dP', 'meA', 'L', 'meA'...",1008.338
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,"['dAbu', 'iBu_Gly', 'L', 'dP', 'meA', 'dL', 'M...",1008.338
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,"['dAbu', 'meA', 'L', 'dP', 'iBu_Gly', 'dL', 'M...",1008.338
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1002.309
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,"['dAbu', 'iBu_Gly', 'dL', 'Me_dA', 'meA', 'dL'...",996.327
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'L', ...",996.327
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'L', ...",996.327
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,"['dAbu', 'meA', 'dL', 'Me_dA', 'iBu_Gly', 'dL'...",996.327
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,"['L', 'meA', 'L', 'dP', 'Pr_Gly', 'Abu', 'meA'...",994.311
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,"['L', 'Pr_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",994.311
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,"['L', 'meA', 'L', 'dP', 'Me_Abu', 'Abu', 'meA'...",994.311
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,"['ac-', 'dP', 'Me_dL', 'T', 'dL', 'dL', 'L', '...",988.282
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,"['L', 'meA', 'L', 'dP', 'meA', 'L', 'meA', 'L'...",987.298
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,"['L', 'Et_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",980.284
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,"['L', 'meA', 'L', 'dP', 'Et_Gly', 'Abu', 'meA'...",980.284
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,"['L', 'meA', 'L', 'Sar', 'P', 'L', 'meA', 'L',...",959.244
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,"['A', 'meA', 'A', 'Me_dA', 'meA', 'A', 'meA', ...",794.952
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,"['A', 'meA', 'A', 'Sar', 'P', 'A', 'meA', 'A',...",790.920
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']",755.014
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,"['L', 'dF', 'dP', 'F', 'dL', 'L']",730.951
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,"['L', 'dF', 'dP', 'F', 'dL', 'I']",730.951
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,"['L', 'dF', 'P', 'F', 'dL', 'L']",730.951
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,"['L', 'dL', 'L', 'L', 'dP', 'Y']",712.933
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,"['L', 'dF', 'P', 'L', 'dL', 'L']",696.934
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,"['L', 'dF', 'dP', 'L', 'dL', 'L']",696.934
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,"['L', 'F', 'dP', 'L', 'L', 'I']",696.934

In [3]:
df_train = df_train[['ID','SMILES','Sequence','Permeability']]
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)

In [4]:
symbol_list = []

with open('/home/users/akshay/PCPpred/MDCK/data/monomer_list.txt', 'r') as file:
    for line in file:
        symbol_list.append(line.strip())
print(symbol_list)

['A', 'dA', 'meA', 'Me_dA', 'Ala(tBu)', 'Ala(indol-2-yl)', 'dAla(indol-2-yl)', 'Me_Ala(indol-2-yl)', 'Ala(5-Tet)', 'Abu', 'dAbu', 'Me_Abu', 'Me_dAbu', 'Me_Abu(morpholino)', '2Abz', 'Aib', 'Aoc(2)', '5-Ava', 'Bal', 'Me_Bal', 'HOCOCH2_Bal', 'Cys(EtO2H)_NH2', 'Cha', 'dCha', 'Me_Cha', 'D', 'meD', 'Asp_piperidide', 'Asp(OMe)', 'Asp(Ph(2-NH2))', 'dAsp(pyrrol-1-yl)', 'E', 'Glu_NH2', 'Glu(3R-Me)', 'Glu(OMe)', 'dGlu(OMe)', 'F', 'dF', 'meF', 'Me_dF', 'Phe(4-F)', 'dPhe(4-F)', 'Phe(4-CF3)', 'Phe(4-NO2)', 'Phe(CHF2)', 'dPhe(3,4-diF)', 'Et_Phe', 'H2NEt_Phe', 'Me_Phe(3-Cl)', 'Me_Phe(4-Cl)', 'Me_Phe(a,b-dehydro)', 'G', 'Bn_Gly', 'Bn(4-Cl)_Gly', 'Bn(4-OH)_Gly', 'Bu_Gly', 'iBu_Gly', 'Et_Gly', 'EtOEt_Gly', 'HOCOCH2_Gly_ol', 'MeOEt_Gly', 'NH2Bu_Gly', 'Pr_Gly', 'PhEt_Gly', 'PhPr_Gly', 'cHexCH2_Gly', 'isoamyl_Gly', 'pentyl_Gly', '3-pyridylethyl_Gly', '2-pyridylmethyl_Gly', 'd(N->O)Gly(allyl)', 'GABA', 'H', 'Hph', 'Me_Hph', 'bHph', 'Hph(2-Cl)', 'Hph(3-Cl)', 'Hph(4-Cl)', 'Hse(Et)', 'dHyp', 'Hyp(Et)', 'I', 'dI', 'meI', 'Me_dI', '(N->O)xiIle', 'd(N->O)aIle', 'K', 'dK', 'meK', 'Me_dK', 'Lys(Ac)', 'Lys(Cbz)', 'Lys(iPr)', 'Lys(Me)', 'Me_Lys(Me)', 'Lys(Me2)', 'Lys(Tfa)', 'L', 'dL', 'meL', 'Me_dL', 'aMeLeu', 'dLeu(3R-OH)', '(N->O)Leu', 'd(N->O)Leu', 'M', 'meM', 'Met(O2)', 'N', 'dN', 'meN', 'dAsn(Me2)', 'Nal', '1-Nal', 'd1-Nal', 'Nle', 'Me_Nle', 'Me_dNle', 'Nle(CHF2)', 'Nle(OH)', 'Nva', 'dNva', 'Me_Nva', 'Me_dNva', 'Nva(Ph)', 'Orn', 'P', 'dP', '3Pal', '4Pal', 'Phg', 'Pip', 'dPip', 'Pye', 'dPye', 'Q', 'meQ', 'Gln(Me)', 'Gln(Me2)', 'dGln(Me2)', 'Gln(Mes)', 'R', 'dR', 'Arg(Me,Me)', 'S', 'dS', 'meS', 'Ser(Ac)', 'Ser(Bn)', 'Ser(EtNMe2)', 'Ser(EtOH)', 'Ser(isoamyl)', 'Ser(Me)', 'dSer(Me)', 'Ser(Ph(2-Cl))', 'Ser(Ph(3-Cl))', 'Ser(Pr)', 'Ser(tBu)', 'Me_Ser(isoamyl)', 'Me_Ser(Pr)', 'Sar', 'Sta', 'Sta(3R,4R)', 'T', 'dT', 'meT', 'Me_Bmt(E)', 'Tle', 'Tza', 'Me_Tza', 'V', 'dV', 'meV', 'Me_dV', '(N->O)Val', 'd(N->O)Val', '(N->O)Val(3-OH)', 'W', 'meW', 'Me_dW', 'Trp(5-Br)', 'Trp(6-Br)', 'Trp(7-Br)', 'Y', 'dY', 'meY', 'Me_dY', 'Tyr(3-F)', 'Tyr(CHF2)', 'Tyr(Me)', 'Me_Tyr(Me)', 'dTyr(bR-OMe)', '(N->O)Tyr', 'Mono1', 'Mono2', 'Mono3', 'Mono4', 'Mono5', 'Mono6', 'Bal(3-Me)', 'Bal(d3-CF3)', 'Mono9', 'Mono10', 'Mono11', 'Mono12', 'Mono13', 'Mono14', 'Mono15', 'Mono16', 'Mono17', 'Mono18', 'Mono19', 'Mono20', 'Mono23', 'Mono24', 'Mono25', 'Mono26', 'Mono27', 'Mono28', 'Mono29', 'Mono30', 'Mono31', 'Mono32', 'Mono33', 'Mono34', 'Mono35', 'Mono36', 'Mono37', 'Mono38', 'Mono39', 'Mono40', 'Mono41', 'Mono42', 'Mono43', 'Mono44', 'Mono45', 'Mono46', 'Mono47', 'Mono48', 'Mono49', 'Mono50', 'Mono51', 'Mono52', 'Mono53', 'Mono54', 'Mono55', 'Mono56', 'Mono57', 'Mono58', 'Mono59', 'Mono60', 'Mono61', 'Mono62', 'Mono63', 'Mono64', 'Mono65', 'Mono66', 'Mono67', 'Mono68', 'Mono69', 'Mono70', 'Mono71', 'Mono72', 'Mono73', 'Mono74', 'Mono75', 'Mono76', 'Mono77', 'Mono78', 'Mono79', 'Mono80', 'Mono81', 'Mono82', 'Mono83', 'Mono84', 'Mono85', 'Mono86', 'Mono87', 'Mono88', 'Mono89', 'Mono90', 'Mono91', 'Mono92', 'Mono93', 'Mono94', 'Mono95', 'Mono96', 'Mono97', 'Mono98', 'Mono99', 'Mono100', 'Mono101', 'Mono102', 'Mono103', 'Mono104', 'Mono105', 'Mono106', 'Mono107', 'Mono108', 'Mono109', 'Mono110', 'Mono111', 'Mono112', 'ac-', 'deca-', 'glyco-', 'medl-', '-pip', 'Mono21-', 'Mono22-', 'dW', 'Ala(O->S)', 'dAla(O->S)', 'Phe(O->S)', 'Ile(O->S)', 'Lys(O->S)', 'Leu(O->S)', 'dLeu(O->S)', 'Pro(O->S)', 'dPro(O->S)', 'Thr(O->S)', 'dTrp(O->S)', 'Tyr(O->S)', 'Ac3c', 'Abu(5-Tet)', 'Gly(allyl)', '-pyrro', 'Aze', 'Bal(d3-Me)', 'Me_Bal(d3-Me)', 'Bal(d3-EtPh)', 'meH', 'Phe(3-Cl)', 'Phe(3-F)', 'Phe(4-Cl)', 'Mono113', 'Ser(tBuOH)', 'Val(3-OH)', 'Mono114', 'Ac5c', 'Hph(4-CF3,3,5-diF)', 'Hph(4-Me)', 'Phe(3,5-diCl)', 'Hph(4-CF3,3-Cl)', 'Me_Phe(4-Me)', 'Hph(4-tBu)', 'Hph(3,4-diCl)', 'Hch', 'Phe(3-Cl,5-F)', 'Me_Gly(cPent)', 'Phe(3-CF3)', 'Et_Phe(4-Me)', 'Hph(4-CF3)', '-nme2', 'Mono115', 'Chg', 'Me_Chg', 'Et_Leu', 'Me_Ser(Me)', 'Me_Hse(Me)', 'Gly(cPr)', 'Me_Gly(cPr)', 'Gly(cBu)', 'Me_Gly(cBu)', 'Gly(cPent)', 'Ala(cPr)', 'Ala(cBu)', 'Ala(cPent)', 'Me_Nva(F2)', '-mor', '-aze', 'Mono116', 'Mono117', 'Mono118', 'Mono119', 'Mono120', 'Mono121', 'Mono122', 'Mono123', 'Mono124', 'Mono125', 'Mono126', 'Mono127']

In [5]:
def calculate_monomer_composition(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [6]:
df_train_mc = calculate_monomer_composition(df_train, symbol_list)
df_train_mc.shape

(51, 388)

In [7]:
df_train_mc.to_csv("/home/users/akshay/PCPpred/MDCK/features/Monomeric/Train_mon_comp_MDCK.csv", index=False)

In [8]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')

df_test = df_test[['ID','SMILES','Sequence','Permeability']]
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)

df_test_mc = calculate_monomer_composition(df_test, symbol_list)
df_test_mc.shape

df_test_mc.to_csv("/home/users/akshay/PCPpred/MDCK/features/Monomeric/Test_mon_comp_MDCK.csv", index=False)
df_test_mc

,ID,SMILES,Permeability,A,dA,meA,Me_dA,Ala(tBu),Ala(indol-2-yl),dAla(indol-2-yl),...,Mono118,Mono119,Mono120,Mono121,Mono122,Mono123,Mono124,Mono125,Mono126,Mono127
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.0,0.200000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.0,0.400000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.2,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.0,0.222222,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.0,0.222222,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.0,0.222222,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.0,0.000000,0.100000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.0,0.111111,0.222222,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.0,0.111111,0.222222,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.1,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.0,0.400000,0.200000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
#Amino acid composition 20 natural and X as non natural amino acids

In [10]:
mono = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/CycPeptMPDB_Monomer_All.csv')
mono = mono[['Symbol','Natural_Analog']]
mono_dict = mono.set_index('Symbol')['Natural_Analog'].to_dict()
mono_dict

{'A': 'A',
 'dA': 'A',
 'meA': 'A',
 'Me_dA': 'A',
 'Ala(tBu)': 'A',
 'Ala(indol-2-yl)': 'A',
 'dAla(indol-2-yl)': 'A',
 'Me_Ala(indol-2-yl)': 'A',
 'Ala(5-Tet)': 'A',
 'Abu': 'X',
 'dAbu': 'X',
 'Me_Abu': 'X',
 'Me_dAbu': 'X',
 'Me_Abu(morpholino)': 'X',
 '2Abz': 'X',
 'Aib': 'X',
 'Aoc(2)': 'L',
 '5-Ava': 'X',
 'Bal': 'A',
 'Me_Bal': 'A',
 'HOCOCH2_Bal': 'A',
 'Cys(EtO2H)_NH2': 'C',
 'Cha': 'A',
 'dCha': 'A',
 'Me_Cha': 'A',
 'D': 'D',
 'meD': 'D',
 'Asp_piperidide': 'D',
 'Asp(OMe)': 'D',
 'Asp(Ph(2-NH2))': 'D',
 'dAsp(pyrrol-1-yl)': 'D',
 'E': 'E',
 'Glu_NH2': 'E',
 'Glu(3R-Me)': 'E',
 'Glu(OMe)': 'E',
 'dGlu(OMe)': 'E',
 'F': 'F',
 'dF': 'F',
 'meF': 'F',
 'Me_dF': 'F',
 'Phe(4-F)': 'F',
 'dPhe(4-F)': 'F',
 'Phe(4-CF3)': 'F',
 'Phe(4-NO2)': 'F',
 'Phe(CHF2)': 'F',
 'dPhe(3,4-diF)': 'F',
 'Et_Phe': 'F',
 'H2NEt_Phe': 'F',
 'Me_Phe(3-Cl)': 'F',
 'Me_Phe(4-Cl)': 'F',
 'Me_Phe(a,b-dehydro)': 'F',
 'G': 'G',
 'Bn_Gly': 'G',
 'Bn(4-Cl)_Gly': 'G',
 'Bn(4-OH)_Gly': 'G',
 'Bu_Gly': 'G',
 'iBu_Gly': 'G',
 'Et_Gly': 'G',
 'EtOEt_Gly': 'G',
 'HOCOCH2_Gly_ol': 'G',
 'MeOEt_Gly': 'G',
 'NH2Bu_Gly': 'G',
 'Pr_Gly': 'G',
 'PhEt_Gly': 'G',
 'PhPr_Gly': 'G',
 'cHexCH2_Gly': 'G',
 'isoamyl_Gly': 'G',
 'pentyl_Gly': 'G',
 '3-pyridylethyl_Gly': 'G',
 '2-pyridylmethyl_Gly': 'G',
 'd(N->O)Gly(allyl)': 'G',
 'GABA': 'X',
 'H': 'H',
 'Hph': 'F',
 'Me_Hph': 'F',
 'bHph': 'F',
 'Hph(2-Cl)': 'F',
 'Hph(3-Cl)': 'F',
 'Hph(4-Cl)': 'F',
 'Hse(Et)': 'S',
 'dHyp': 'P',
 'Hyp(Et)': 'P',
 'I': 'I',
 'dI': 'I',
 'meI': 'I',
 'Me_dI': 'I',
 '(N->O)xiIle': 'I',
 'd(N->O)aIle': 'I',
 'K': 'K',
 'dK': 'K',
 'meK': 'K',
 'Me_dK': 'K',
 'Lys(Ac)': 'K',
 'Lys(Cbz)': 'K',
 'Lys(iPr)': 'K',
 'Lys(Me)': 'K',
 'Me_Lys(Me)': 'K',
 'Lys(Me2)': 'K',
 'Lys(Tfa)': 'K',
 'L': 'L',
 'dL': 'L',
 'meL': 'L',
 'Me_dL': 'L',
 'aMeLeu': 'L',
 'dLeu(3R-OH)': 'L',
 '(N->O)Leu': 'L',
 'd(N->O)Leu': 'L',
 'M': 'M',
 'meM': 'M',
 'Met(O2)': 'M',
 'N': 'N',
 'dN': 'N',
 'meN': 'N',
 'dAsn(Me2)': 'N',
 'Nal': 'A',
 '1-Nal': 'A',
 'd1-Nal': 'A',
 'Nle': 'L',
 'Me_Nle': 'L',
 'Me_dNle': 'L',
 'Nle(CHF2)': 'L',
 'Nle(OH)': 'L',
 'Nva': 'V',
 'dNva': 'V',
 'Me_Nva': 'V',
 'Me_dNva': 'V',
 'Nva(Ph)': 'V',
 'Orn': 'K',
 'P': 'P',
 'dP': 'P',
 '3Pal': 'A',
 '4Pal': 'A',
 'Phg': 'G',
 'Pip': 'X',
 'dPip': 'X',
 'Pye': 'Q',
 'dPye': 'Q',
 'Q': 'Q',
 'meQ': 'Q',
 'Gln(Me)': 'Q',
 'Gln(Me2)': 'Q',
 'dGln(Me2)': 'Q',
 'Gln(Mes)': 'Q',
 'R': 'R',
 'dR': 'R',
 'Arg(Me,Me)': 'R',
 'S': 'S',
 'dS': 'S',
 'meS': 'S',
 'Ser(Ac)': 'S',
 'Ser(Bn)': 'S',
 'Ser(EtNMe2)': 'S',
 'Ser(EtOH)': 'S',
 'Ser(isoamyl)': 'S',
 'Ser(Me)': 'S',
 'dSer(Me)': 'S',
 'Ser(Ph(2-Cl))': 'S',
 'Ser(Ph(3-Cl))': 'S',
 'Ser(Pr)': 'S',
 'Ser(tBu)': 'S',
 'Me_Ser(isoamyl)': 'S',
 'Me_Ser(Pr)': 'S',
 'Sar': 'G',
 'Sta': 'X',
 'Sta(3R,4R)': 'X',
 'T': 'T',
 'dT': 'T',
 'meT': 'T',
 'Me_Bmt(E)': 'T',
 'Tle': 'G',
 'Tza': 'A',
 'Me_Tza': 'A',
 'V': 'V',
 'dV': 'V',
 'meV': 'V',
 'Me_dV': 'V',
 '(N->O)Val': 'V',
 'd(N->O)Val': 'V',
 '(N->O)Val(3-OH)': 'V',
 'W': 'W',
 'meW': 'W',
 'Me_dW': 'W',
 'Trp(5-Br)': 'W',
 'Trp(6-Br)': 'W',
 'Trp(7-Br)': 'W',
 'Y': 'Y',
 'dY': 'Y',
 'meY': 'Y',
 'Me_dY': 'Y',
 'Tyr(3-F)': 'Y',
 'Tyr(CHF2)': 'Y',
 'Tyr(Me)': 'Y',
 'Me_Tyr(Me)': 'Y',
 'dTyr(bR-OMe)': 'Y',
 '(N->O)Tyr': 'Y',
 'Mono1': 'G',
 'Mono2': 'P',
 'Mono3': 'X',
 'Mono4': 'N',
 'Mono5': 'N',
 'Mono6': 'X',
 'Bal(3-Me)': 'A',
 'Bal(d3-CF3)': 'A',
 'Mono9': 'F',
 'Mono10': 'F',
 'Mono11': 'F',
 'Mono12': 'F',
 'Mono13': 'P',
 'Mono14': 'X',
 'Mono15': 'T',
 'Mono16': 'X',
 'Mono17': 'X',
 'Mono18': 'X',
 'Mono19': 'X',
 'Mono20': 'X',
 'Mono23': 'X',
 'Mono24': 'Q',
 'Mono25': 'X',
 'Mono26': 'I',
 'Mono27': 'V',
 'Mono28': 'X',
 'Mono29': 'X',
 'Mono30': 'X',
 'Mono31': 'X',
 'Mono32': 'G',
 'Mono33': 'G',
 'Mono34': 'G',
 'Mono35': 'X',
 'Mono36': 'X',
 'Mono37': 'X',
 'Mono38': 'G',
 'Mono39': 'G',
 'Mono40': 'G',
 'Mono41': 'G',
 'Mono42': 'G',
 'Mono43': 'G',
 'Mono44': 'G',
 'Mono45': 'G',
 'Mono46': 'P',
 'Mono47': 'P',
 'Mono48': 'X',
 'Mono49': 'S',
 'Mono50': 'S',
 'Mono51': 'X',
 'Mono52': 'X',
 'Mono53': 'X',
 'Mono54': 'S',
 'Mono55': 'S',
 'Mono56': 'S',
 'Mono57': 'S',
 'Mono58': 'G',
 'Mono59': 'P',
 'Mono60': 'P',
 'Mono61': 'X',
 'Mono62': 'S',
 'Mono63': 'X',
 'Mono64': 'S',
 'Mono65': 'X',
 'Mono66': 'S',
 'Mono67': 'X',
 'Mono68': 'X',
 'Mono69': 'X',
 'Mono70': 'X',
 'Mono71': 'H',
 'Mono72': 'Q',
 'Mono73': 'N',
 'Mono74': 'R',
 'Mono75': 'F',
 'Mono76': 'F',
 'Mono77': 'F',
 'Mono78': 'F',
 'Mono79': 'F',
 'Mono80': 'F',
 'Mono81': 'F',
 'Mono82': 'F',
 'Mono83': 'G',
 'Mono84': 'A',
 'Mono85': 'A',
 'Mono86': 'L',
 'Mono87': 'F',
 'Mono88': 'F',
 'Mono89': 'F',
 'Mono90': 'F',
 'Mono91': 'F',
 'Mono92': 'X',
 'Mono93': 'X',
 'Mono94': 'X',
 'Mono95': 'X',
 'Mono96': 'X',
 'Mono97': 'X',
 'Mono98': 'X',
 'Mono99': 'X',
 'Mono100': 'C',
 'Mono101': 'C',
 'Mono102': 'X',
 'Mono103': 'X',
 'Mono104': 'X',
 'Mono105': 'X',
 'Mono106': 'X',
 'Mono107': 'X',
 'Mono108': 'X',
 'Mono109': 'X',
 'Mono110': 'X',
 'Mono111': 'X',
 'Mono112': 'X',
 'ac-': 'X',
 'deca-': 'X',
 'glyco-': 'G',
 'medl-': 'L',
 '-pip': 'X',
 'Mono21-': 'X',
 'Mono22-': 'X',
 'dW': 'W',
 'Ala(O->S)': 'A',
 'dAla(O->S)': 'A',
 'Phe(O->S)': 'F',
 'Ile(O->S)': 'I',
 'Lys(O->S)': 'K',
 'Leu(O->S)': 'L',
 'dLeu(O->S)': 'L',
 'Pro(O->S)': 'P',
 'dPro(O->S)': 'P',
 'Thr(O->S)': 'T',
 'dTrp(O->S)': 'W',
 'Tyr(O->S)': 'Y',
 'Ac3c': 'X',
 'Abu(5-Tet)': 'X',
 'Gly(allyl)': 'G',
 '-pyrro': 'X',
 'Aze': 'X',
 'Bal(d3-Me)': 'A',
 'Me_Bal(d3-Me)': 'A',
 'Bal(d3-EtPh)': 'A',
 'meH': 'H',
 'Phe(3-Cl)': 'F',
 'Phe(3-F)': 'F',
 'Phe(4-Cl)': 'F',
 'Mono113': 'X',
 'Ser(tBuOH)': 'S',
 'Val(3-OH)': 'V',
 'Mono114': 'X',
 'Ac5c': 'X',
 'Hph(4-CF3,3,5-diF)': 'F',
 'Hph(4-Me)': 'F',
 'Phe(3,5-diCl)': 'F',
 'Hph(4-CF3,3-Cl)': 'F',
 'Me_Phe(4-Me)': 'F',
 'Hph(4-tBu)': 'F',
 'Hph(3,4-diCl)': 'F',
 'Hch': 'F',
 'Phe(3-Cl,5-F)': 'F',
 'Me_Gly(cPent)': 'G',
 'Phe(3-CF3)': 'F',
 'Et_Phe(4-Me)': 'F',
 'Hph(4-CF3)': 'F',
 '-nme2': 'X',
 'Mono115': 'C',
 'Chg': 'G',
 'Me_Chg': 'G',
 'Et_Leu': 'L',
 'Me_Ser(Me)': 'S',
 'Me_Hse(Me)': 'S',
 'Gly(cPr)': 'G',
 'Me_Gly(cPr)': 'G',
 'Gly(cBu)': 'G',
 'Me_Gly(cBu)': 'G',
 'Gly(cPent)': 'G',
 'Ala(cPr)': 'A',
 'Ala(cBu)': 'A',
 'Ala(cPent)': 'A',
 'Me_Nva(F2)': 'V',
 '-mor': 'X',
 '-aze': 'X',
 'Mono116': 'X',
 'Mono117': 'F',
 'Mono118': 'F',
 'Mono119': 'F',
 'Mono120': 'F',
 'Mono121': 'F',
 'Mono122': 'F',
 'Mono123': 'F',
 'Mono124': 'F',
 'Mono125': 'F',
 'Mono126': 'X',
 'Mono127': 'X'}

In [11]:
amino_acid_list =  list(set(mono['Natural_Analog'].to_list()))
amino_acid_list

['D',
 'Y',
 'M',
 'L',
 'K',
 'N',
 'G',
 'C',
 'V',
 'T',
 'X',
 'H',
 'R',
 'Q',
 'P',
 'E',
 'A',
 'S',
 'W',
 'I',
 'F']

In [12]:
def seq2seq(sequence):
    seq = ''
    for s in sequence:
        if s in mono_dict.keys():
            seq += mono_dict[s]
    return seq

In [13]:
def calculate_aac(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Natural_analog_sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Natural_analog_sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [14]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)
df_train.loc[:, 'Natural_analog_sequence'] = df_train['Sequence'].apply(lambda x :seq2seq(x))
df_train = calculate_aac(df_train, amino_acid_list)
print('Shape',df_train.shape)
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Monomeric/Train_aac_MDCK.csv',index=False)
df_train

Shape (51, 24)

,ID,SMILES,Permeability,D,Y,M,L,K,N,G,...,H,R,Q,P,E,A,S,W,I,F
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.200000
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.200000
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.200000
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,0.200000
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.100000
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.100000
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.100000
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.100000
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0.0,0.000000,0.0,0.222222,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.111111,0.0,0.333333,0.0,0.0,0.000000,0.000000
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0.0,0.000000,0.0,0.600000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,0.000000
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.000000
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0.0,0.000000,0.0,0.600000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.000000,0.0,0.0,0.000000,0.000000
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0.0,0.000000,0.0,0.222222,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.333333,0.0,0.0,0.000000,0.000000
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.300000,0.0,0.0,0.000000,0.000000
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0.0,0.000000,0.0,0.300000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.300000,0.0,0.0,0.000000,0.000000
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.400000,0.0,0.0,0.000000,0.000000
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0.0,0.000000,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0.0,0.000000,0.0,0.400000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.000000
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.000000,0.000000
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.200000,...,0.0,0.0,0.0,0.200000,0.0,0.600000,0.0,0.0,0.000000,0.000000
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0.0,0.166667,0.0,0.666667,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.000000
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.333333
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.166667,0.333333
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.333333
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0.0,0.166667,0.0,0.666667,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.000000
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0.0,0.000000,0.0,0.666667,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.166667
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0.0,0.000000,0.0,0.666667,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.000000,0.166667
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0.0,0.000000,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.166667,0.166667

In [15]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)
df_test.loc[:, 'Natural_analog_sequence'] = df_test['Sequence'].apply(lambda x :seq2seq(x))
df_test = calculate_aac(df_test, amino_acid_list)
print('Shape',df_test.shape)
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Monomeric/Test_aac_MDCK.csv',index=False)
df_test

Shape (13, 24)

,ID,SMILES,Permeability,D,Y,M,L,K,N,G,...,H,R,Q,P,E,A,S,W,I,F
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.0,0.0,0.600000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.200000,0.0,0.0,0.000000,0.200000
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.0,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.400000,0.0,0.0,0.000000,0.200000
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.0,0.0,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.200000,0.0,0.0,0.000000,0.200000
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.0,0.0,0.222222,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.333333,0.0,0.0,0.000000,0.000000
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.0,0.0,0.333333,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.0,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.111111,0.0,0.222222,0.0,0.0,0.000000,0.000000
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.0,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.0,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.0,0.0,0.333333,0.0,0.0,0.111111,...,0.0,0.0,0.0,0.000000,0.0,0.333333,0.0,0.0,0.000000,0.000000
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.0,0.0,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.200000,0.0,0.100000,0.0,0.0,0.000000,0.000000
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.0,0.0,0.400000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.600000,0.0,0.0,0.000000,0.000000
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.0,0.0,0.333333,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.166667,0.333333
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.0,0.0,0.500000,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.166667,0.0,0.000000,0.0,0.0,0.166667,0.166667

In [16]:
#Atomic features
import pandas as pd
import numpy as np
from rdkit import Chem

In [17]:
def get_unique_atoms(smiles_list):
    unique_atoms = set()
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        if mol is not None:  # Check if the molecule was created successfully
            for atom in mol.GetAtoms():
                unique_atoms.add(atom.GetSymbol())  # Add atomic symbol to the set
    
    return unique_atoms

In [18]:
def get_atomic_composition_frequency(smiles_list):
    atomic_frequencies = []
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        composition = {'Br': 0, 'C': 0, 'Cl': 0, 'F': 0, 'N': 0, 'O': 0, 'S': 0}  
        
        if mol is not None:  # Check if the molecule was created successfully
            total_atoms = mol.GetNumAtoms()  # Get total number of atoms in the molecule
            
            for atom in mol.GetAtoms():
                composition[atom.GetSymbol()] += 1  # Count occurrences of each atom
            
            # Calculate frequency
            frequency = {atom: count / total_atoms for atom, count in composition.items()}
            atomic_frequencies.append(frequency)  # Append the frequency for this SMILES
    
    return atomic_frequencies

In [19]:
#Degree of atoms
target_atoms = {'Br', 'C', 'Cl', 'F', 'N', 'O', 'S'}
def compute_target_atom_degrees(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    # Initialize a dictionary to hold the highest degrees for target atoms
    degrees_dict = {atom: 0 for atom in target_atoms}

    # Get the degree of each atom and update the dictionary for target atoms
    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        if atom_symbol in target_atoms:
            current_degree = atom.GetDegree()
            # Update the degree if the current one is higher
            if current_degree > degrees_dict[atom_symbol]:
                degrees_dict[atom_symbol] = current_degree

    return degrees_dict

In [20]:
#Bond type
def compute_bond_types_for_cyclic_peptides(df):
    
    def compute_bond_types(smiles):
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None  # Handle invalid SMILES

        bond_types = {
            'Single': 0,
            'Double': 0,
            'Triple': 0,
            'Aromatic': 0,
            'Conjugated': 0,
            'No-bond': 0
        }

        # Iterate through the bonds in the molecule
        for bond in mol.GetBonds():
            bond_order = bond.GetBondTypeAsDouble()
            if bond_order == 1.0:
                bond_types['Single'] += 1
            elif bond_order == 2.0:
                bond_types['Double'] += 1
            elif bond_order == 3.0:
                bond_types['Triple'] += 1
            elif bond_order == 1.5:
                bond_types['Aromatic'] += 1
            elif bond_order == 1.4:
                bond_types['Conjugated'] += 1
            else:
                bond_types['No-bond'] += 1

        return bond_types

    df['Bond_Types'] = df['SMILES'].apply(compute_bond_types)

    bond_types_df = df['Bond_Types'].apply(pd.Series)

    df = pd.concat([df, bond_types_df], axis=1)

    df.drop(columns=['Bond_Types'], inplace=True)

    return df

In [21]:
#Formal charges
def calculate_overall_formal_charge(smiles):
   
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    overall_charge = 0
    
    # Define valence electrons for common atoms
    valence_electrons = {
        'C': 4,
        'N': 5,
        'O': 6,
        'S': 6,
        'P': 5,
        'F': 7,
        'Cl': 7,
        'Br': 7,
        'I': 7,
    }

    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        valence = valence_electrons.get(atom_symbol, 0)
        non_bonding = atom.GetNumImplicitHs() 
        bonding = atom.GetDegree() * 2  # 2 electrons for each bond

        # Calculate formal charge
        formal_charge = valence - (non_bonding + bonding // 2)
        overall_charge += formal_charge

    return overall_charge

In [22]:
def check_aromatic_and_ring(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return (None, None)  # Handle invalid SMILES

    # Check if the molecule is aromatic
    is_aromatic = any(atom.GetIsAromatic() for atom in mol.GetAtoms())

    # Check if the molecule contains a ring
    ring_info = mol.GetRingInfo()
    is_in_ring = ring_info.NumRings() > 0

    return (int(is_aromatic), int(is_in_ring))

In [23]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,"['L', 'meA', 'L', 'dP', 'meF', 'L', 'meA', 'L'...",1139.494
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,"['L', 'meA', 'L', 'Me_dF', 'P', 'L', 'meA', 'L...",1139.494
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,"['L', 'meF', 'L', 'dP', 'meA', 'L', 'meF', 'L'...",1139.494
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,"['L', 'meA', 'L', 'Me_dA', 'meF', 'L', 'meA', ...",1115.472
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,"['L', 'dP', 'Mono38', 'L', 'meA', 'F', 'dP', '...",1091.406
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,"['L', 'dP', 'meL', 'A', 'Mono38', 'F', 'dP', '...",1091.406
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,"['L', 'dP', 'meL', 'A', 'cHexCH2_Gly', 'F', 'd...",1089.434
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,"['L', 'dP', 'cHexCH2_Gly', 'L', 'meA', 'F', 'd...",1089.434
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,"['L', 'meA', 'Nva', 'dP', 'Me_Abu', 'Cha', 'me...",1048.403
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,"['L', 'meL', 'L', 'Me_dA', 'meA', 'L', 'meL', ...",1047.438
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,"['L', 'meA', 'L', 'dP', 'meV', 'L', 'meA', 'L'...",1043.406
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,"['L', 'meL', 'L', 'Sar', 'P', 'L', 'meL', 'L',...",1043.406
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,"['L', 'meA', 'Nva', 'dP', 'Et_Gly', 'Cha', 'me...",1034.376
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,"['ac-', 'P', 'meL', 'T', 'Me_dL', 'meL', 'L', ...",1030.363
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,"['ac-', 'dP', 'Me_dL', 'T', 'Me_dL', 'meL', 'm...",1030.363
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,"['ac-', 'P', 'Me_dL', 'T', 'meL', 'L', 'Me_dL'...",1030.363
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1016.336
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,"['ac-', 'P', 'meL', 'T', 'meL', 'L', 'meL', 'A...",1016.336
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,"['L', 'dP', 'Mono38', 'L', 'meA', 'A', 'dP', '...",1015.308
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,"['L', 'dP', 'meL', 'A', 'Mono38', 'A', 'dP', '...",1015.308
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,"['L', 'meA', 'L', 'dP', 'Me_Nva', 'Abu', 'meA'...",1008.338
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,"['L', 'Pr_Gly', 'Nva', 'dP', 'meA', 'L', 'meA'...",1008.338
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,"['dAbu', 'iBu_Gly', 'L', 'dP', 'meA', 'dL', 'M...",1008.338
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,"['dAbu', 'meA', 'L', 'dP', 'iBu_Gly', 'dL', 'M...",1008.338
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1002.309
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,"['dAbu', 'iBu_Gly', 'dL', 'Me_dA', 'meA', 'dL'...",996.327
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'L', ...",996.327
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'L', ...",996.327
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,"['dAbu', 'meA', 'dL', 'Me_dA', 'iBu_Gly', 'dL'...",996.327
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,"['L', 'meA', 'L', 'dP', 'Pr_Gly', 'Abu', 'meA'...",994.311
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,"['L', 'Pr_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",994.311
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,"['L', 'meA', 'L', 'dP', 'Me_Abu', 'Abu', 'meA'...",994.311
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,"['ac-', 'dP', 'Me_dL', 'T', 'dL', 'dL', 'L', '...",988.282
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,"['L', 'meA', 'L', 'dP', 'meA', 'L', 'meA', 'L'...",987.298
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,"['L', 'Et_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",980.284
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,"['L', 'meA', 'L', 'dP', 'Et_Gly', 'Abu', 'meA'...",980.284
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,"['L', 'meA', 'L', 'Sar', 'P', 'L', 'meA', 'L',...",959.244
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,"['A', 'meA', 'A', 'Me_dA', 'meA', 'A', 'meA', ...",794.952
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,"['A', 'meA', 'A', 'Sar', 'P', 'A', 'meA', 'A',...",790.920
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']",755.014
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,"['L', 'dF', 'dP', 'F', 'dL', 'L']",730.951
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,"['L', 'dF', 'dP', 'F', 'dL', 'I']",730.951
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,"['L', 'dF', 'P', 'F', 'dL', 'L']",730.951
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,"['L', 'dL', 'L', 'L', 'dP', 'Y']",712.933
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,"['L', 'dF', 'P', 'L', 'dL', 'L']",696.934
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,"['L', 'dF', 'dP', 'L', 'dL', 'L']",696.934
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,"['L', 'F', 'dP', 'L', 'L', 'I']",696.934

In [24]:
unique_atoms = get_unique_atoms(df_train['SMILES'])
unique_atoms

{'C', 'N', 'O', 'S'}

In [25]:
atomic_frequencies = get_atomic_composition_frequency(df_train['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

     Br         C   Cl    F         N         O         S
0   0.0  0.756098  0.0  0.0  0.121951  0.121951  0.000000
1   0.0  0.756098  0.0  0.0  0.121951  0.121951  0.000000
2   0.0  0.756098  0.0  0.0  0.121951  0.121951  0.000000
3   0.0  0.750000  0.0  0.0  0.125000  0.125000  0.000000
4   0.0  0.730769  0.0  0.0  0.128205  0.141026  0.000000
5   0.0  0.730769  0.0  0.0  0.128205  0.141026  0.000000
6   0.0  0.743590  0.0  0.0  0.128205  0.128205  0.000000
7   0.0  0.743590  0.0  0.0  0.128205  0.128205  0.000000
8   0.0  0.712329  0.0  0.0  0.123288  0.150685  0.013699
9   0.0  0.729730  0.0  0.0  0.135135  0.135135  0.000000
10  0.0  0.729730  0.0  0.0  0.135135  0.135135  0.000000
11  0.0  0.729730  0.0  0.0  0.135135  0.135135  0.000000
12  0.0  0.708333  0.0  0.0  0.125000  0.152778  0.013889
13  0.0  0.726027  0.0  0.0  0.123288  0.150685  0.000000
14  0.0  0.726027  0.0  0.0  0.123288  0.150685  0.000000
15  0.0  0.726027  0.0  0.0  0.123288  0.150685  0.000000
16  0.0  0.722222  0.0  0.0  0.125000  0.152778  0.000000
17  0.0  0.722222  0.0  0.0  0.125000  0.152778  0.000000
18  0.0  0.708333  0.0  0.0  0.138889  0.152778  0.000000
19  0.0  0.708333  0.0  0.0  0.138889  0.152778  0.000000
20  0.0  0.700000  0.0  0.0  0.128571  0.157143  0.014286
21  0.0  0.700000  0.0  0.0  0.128571  0.157143  0.014286
22  0.0  0.700000  0.0  0.0  0.128571  0.157143  0.014286
23  0.0  0.700000  0.0  0.0  0.128571  0.157143  0.014286
24  0.0  0.718310  0.0  0.0  0.126761  0.154930  0.000000
25  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
26  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
27  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
28  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
29  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
30  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
31  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
32  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
33  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
34  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
35  0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
36  0.0  0.714286  0.0  0.0  0.128571  0.157143  0.000000
37  0.0  0.714286  0.0  0.0  0.142857  0.142857  0.000000
38  0.0  0.691176  0.0  0.0  0.132353  0.161765  0.014706
39  0.0  0.691176  0.0  0.0  0.132353  0.161765  0.014706
40  0.0  0.705882  0.0  0.0  0.147059  0.147059  0.000000
41  0.0  0.642857  0.0  0.0  0.178571  0.178571  0.000000
42  0.0  0.642857  0.0  0.0  0.178571  0.178571  0.000000
43  0.0  0.759259  0.0  0.0  0.111111  0.129630  0.000000
44  0.0  0.773585  0.0  0.0  0.113208  0.113208  0.000000
45  0.0  0.773585  0.0  0.0  0.113208  0.113208  0.000000
46  0.0  0.773585  0.0  0.0  0.113208  0.113208  0.000000
47  0.0  0.745098  0.0  0.0  0.117647  0.137255  0.000000
48  0.0  0.760000  0.0  0.0  0.120000  0.120000  0.000000
49  0.0  0.760000  0.0  0.0  0.120000  0.120000  0.000000
50  0.0  0.760000  0.0  0.0  0.120000  0.120000  0.000000

In [26]:
df_train_atomic_comp = pd.concat([df_train[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_train_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0.0,0.712329,0.0,0.0,0.123288,0.150685,0.013699
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.000000
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0.0,0.759259,0.0,0.0,0.111111,0.129630,0.000000
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0.0,0.745098,0.0,0.0,0.117647,0.137255,0.000000
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000

In [27]:
df_train_atomic_comp.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_atomic_comp_MDCK.csv', index=False)

In [28]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')
atomic_frequencies = get_atomic_composition_frequency(df_test['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

     Br         C   Cl    F         N         O         S
0   0.0  0.767442  0.0  0.0  0.116279  0.116279  0.000000
1   0.0  0.750000  0.0  0.0  0.125000  0.125000  0.000000
2   0.0  0.743590  0.0  0.0  0.128205  0.128205  0.000000
3   0.0  0.708333  0.0  0.0  0.125000  0.152778  0.013889
4   0.0  0.704225  0.0  0.0  0.126761  0.154930  0.014085
5   0.0  0.700000  0.0  0.0  0.128571  0.157143  0.014286
6   0.0  0.718310  0.0  0.0  0.126761  0.154930  0.000000
7   0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
8   0.0  0.695652  0.0  0.0  0.130435  0.159420  0.014493
9   0.0  0.714286  0.0  0.0  0.128571  0.157143  0.000000
10  0.0  0.705882  0.0  0.0  0.147059  0.147059  0.000000
11  0.0  0.773585  0.0  0.0  0.113208  0.113208  0.000000
12  0.0  0.760000  0.0  0.0  0.120000  0.120000  0.000000

In [29]:
df_test_atomic_comp = pd.concat([df_test[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_test_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.767442,0.0,0.0,0.116279,0.116279,0.000000
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.704225,0.0,0.0,0.126761,0.154930,0.014085
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000

In [30]:
df_test_atomic_comp.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_atomic_comp_MDCK.csv', index=False)

In [31]:
#Degree of atoms
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_atomic_comp_MDCK.csv')
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_atomic_comp_MDCK.csv')

In [32]:
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_atomic_comp_and_degree_MDCK.csv",index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_C,Degree_Cl,Degree_F,Degree_S,Degree_N,Degree_O,Degree_Br
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,3,0,0,0,3,1,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,3,0,0,0,3,1,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,3,0,0,0,3,1,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000,3,0,0,0,3,1,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000,3,0,0,0,3,2,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000,3,0,0,0,3,2,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,3,0,0,0,3,1,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,3,0,0,0,3,1,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0.0,0.712329,0.0,0.0,0.123288,0.150685,0.013699,3,0,0,2,3,2,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,3,0,0,0,3,1,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,3,0,0,0,3,1,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,3,0,0,0,3,1,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889,3,0,0,2,3,2,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,3,0,0,0,3,2,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,3,0,0,0,3,2,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,3,0,0,0,3,2,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000,3,0,0,0,3,2,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000,3,0,0,0,3,2,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000,3,0,0,0,3,2,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000,3,0,0,0,3,2,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,3,0,0,2,3,2,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,3,0,0,2,3,2,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,3,0,0,2,3,2,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,3,0,0,2,3,2,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000,3,0,0,0,3,2,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000,3,0,0,0,3,2,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.000000,3,0,0,0,3,1,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706,3,0,0,2,3,2,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706,3,0,0,2,3,2,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000,3,0,0,0,3,1,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000,3,0,0,0,3,1,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000,3,0,0,0,3,1,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0.0,0.759259,0.0,0.0,0.111111,0.129630,0.000000,3,0,0,0,3,1,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,3,0,0,0,3,1,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,3,0,0,0,3,1,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,3,0,0,0,3,1,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0.0,0.745098,0.0,0.0,0.117647,0.137255,0.000000,3,0,0,0,3,1,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,3,0,0,0,3,1,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,3,0,0,0,3,1,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,3,0,0,0,3,1,0

In [33]:
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_atomic_comp_and_degree_MDCK.csv",index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_C,Degree_Cl,Degree_F,Degree_S,Degree_N,Degree_O,Degree_Br
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.767442,0.0,0.0,0.116279,0.116279,0.000000,3,0,0,0,3,1,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000,3,0,0,0,3,1,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,3,0,0,0,3,1,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889,3,0,0,2,3,2,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.704225,0.0,0.0,0.126761,0.154930,0.014085,3,0,0,2,3,2,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,3,0,0,2,3,2,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000,3,0,0,0,3,2,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,3,0,0,2,3,2,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000,3,0,0,0,3,2,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000,3,0,0,0,3,1,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,3,0,0,0,3,1,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,3,0,0,0,3,1,0

In [34]:
#CSV with only degree columns
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_atomic_degrees_MDCK.csv",index=False)
df_train

,ID,SMILES,Permeability,Degree_C,Degree_Cl,Degree_F,Degree_S,Degree_N,Degree_O,Degree_Br
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,3,0,0,0,3,1,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,3,0,0,0,3,1,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,3,0,0,0,3,1,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,3,0,0,0,3,1,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,3,0,0,0,3,2,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,3,0,0,0,3,2,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,3,0,0,0,3,1,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,3,0,0,0,3,1,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,3,0,0,2,3,2,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,3,0,0,0,3,1,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,3,0,0,0,3,1,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,3,0,0,0,3,1,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,3,0,0,2,3,2,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,3,0,0,0,3,2,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,3,0,0,0,3,2,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,3,0,0,0,3,2,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,3,0,0,0,3,2,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,3,0,0,0,3,2,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,3,0,0,0,3,2,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,3,0,0,0,3,2,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,3,0,0,2,3,2,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,3,0,0,2,3,2,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,3,0,0,2,3,2,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,3,0,0,2,3,2,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,3,0,0,0,3,2,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,3,0,0,2,3,2,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,3,0,0,2,3,2,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,3,0,0,2,3,2,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,3,0,0,2,3,2,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,3,0,0,2,3,2,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,3,0,0,2,3,2,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,3,0,0,2,3,2,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,3,0,0,2,3,2,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,3,0,0,2,3,2,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,3,0,0,2,3,2,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,3,0,0,2,3,2,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,3,0,0,0,3,2,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,3,0,0,0,3,1,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,3,0,0,2,3,2,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,3,0,0,2,3,2,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,3,0,0,0,3,1,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,3,0,0,0,3,1,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,3,0,0,0,3,1,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,3,0,0,0,3,1,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,3,0,0,0,3,1,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,3,0,0,0,3,1,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,3,0,0,0,3,1,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,3,0,0,0,3,1,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,3,0,0,0,3,1,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,3,0,0,0,3,1,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,3,0,0,0,3,1,0

In [35]:
#CSV with only degree columns
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

# Rename the columns to include the atom symbols
degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

# Concatenate the original DataFrame with the new degrees DataFrame
df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_atomic_degrees_MDCK.csv",index=False)
df_test

,ID,SMILES,Permeability,Degree_C,Degree_Cl,Degree_F,Degree_S,Degree_N,Degree_O,Degree_Br
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,3,0,0,0,3,1,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,3,0,0,0,3,1,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,3,0,0,0,3,1,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,3,0,0,2,3,2,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,3,0,0,2,3,2,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,3,0,0,2,3,2,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,3,0,0,0,3,2,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,3,0,0,2,3,2,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,3,0,0,2,3,2,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,3,0,0,0,3,2,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,3,0,0,0,3,1,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,3,0,0,0,3,1,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,3,0,0,0,3,1,0

In [36]:
#Bond_type
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_bonds_type_MDCK.csv', index=False)

In [37]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_atomic_comp_and_degree_MDCK.csv')
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_MDCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_S,Degree_N,Degree_O,Degree_Br,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,...,0,3,1,0,64,10,0,12,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,...,0,3,1,0,64,10,0,12,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0.0,0.756098,0.0,0.0,0.121951,0.121951,0.000000,...,0,3,1,0,64,10,0,12,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000,...,0,3,1,0,60,10,0,12,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000,...,0,3,2,0,66,10,0,6,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0.0,0.730769,0.0,0.0,0.128205,0.141026,0.000000,...,0,3,2,0,66,10,0,6,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,...,0,3,1,0,66,10,0,6,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,...,0,3,1,0,66,10,0,6,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0.0,0.712329,0.0,0.0,0.123288,0.150685,0.013699,...,2,3,2,0,65,10,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,...,0,3,1,0,64,10,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,...,0,3,1,0,66,10,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0.0,0.729730,0.0,0.0,0.135135,0.135135,0.000000,...,0,3,1,0,66,10,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889,...,2,3,2,0,64,10,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,...,0,3,2,0,65,10,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,...,0,3,2,0,65,10,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0.0,0.726027,0.0,0.0,0.123288,0.150685,0.000000,...,0,3,2,0,65,10,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000,...,0,3,2,0,64,10,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0.0,0.722222,0.0,0.0,0.125000,0.152778,0.000000,...,0,3,2,0,64,10,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000,...,0,3,2,0,65,10,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0.0,0.708333,0.0,0.0,0.138889,0.152778,0.000000,...,0,3,2,0,65,10,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,2,3,2,0,61,10,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,2,3,2,0,61,10,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,2,3,2,0,61,10,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,2,3,2,0,61,10,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000,...,0,3,2,0,63,10,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,60,10,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,60,10,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,60,10,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000,...,0,3,2,0,62,10,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.000000,...,0,3,1,0,62,10,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706,...,2,3,2,0,59,10,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0.0,0.691176,0.0,0.0,0.132353,0.161765,0.014706,...,2,3,2,0,59,10,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000,...,0,3,1,0,60,10,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000,...,0,3,1,0,46,10,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0.0,0.642857,0.0,0.0,0.178571,0.178571,0.000000,...,0,3,1,0,48,10,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0.0,0.759259,0.0,0.0,0.111111,0.129630,0.000000,...,0,3,1,0,44,6,0,6,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,...,0,3,1,0,38,6,0,12,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,...,0,3,1,0,38,6,0,12,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,...,0,3,1,0,38,6,0,12,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0.0,0.745098,0.0,0.0,0.117647,0.137255,0.000000,...,0,3,1,0,41,6,0,6,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,...,0,3,1,0,40,6,0,6,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,...,0,3,1,0,40,6,0,6,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,...,0,3,1,0,40,6,0,6,0,0

In [38]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_bonds_type_MDCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,66,10,0,12,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,60,10,0,12,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,60,10,0,12,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,64,10,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,62,10,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,61,10,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,63,10,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,59,10,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,59,10,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,62,10,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,58,10,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,38,6,0,12,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,40,6,0,6,0,0

In [39]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_atomic_comp_and_degree_MDCK.csv')
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_MDCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_S,Degree_N,Degree_O,Degree_Br,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.767442,0.0,0.0,0.116279,0.116279,0.000000,...,0,3,1,0,66,10,0,12,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000,...,0,3,1,0,60,10,0,12,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,...,0,3,1,0,60,10,0,12,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889,...,2,3,2,0,64,10,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.704225,0.0,0.0,0.126761,0.154930,0.014085,...,2,3,2,0,62,10,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,2,3,2,0,61,10,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000,...,0,3,2,0,63,10,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,2,3,2,0,59,10,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000,...,0,3,2,0,62,10,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000,...,0,3,1,0,58,10,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,...,0,3,1,0,38,6,0,12,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,...,0,3,1,0,40,6,0,6,0,0

In [40]:
#Overall formal charge
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Overall_Formal_Charge'] = df_train['SMILES'].apply(calculate_overall_formal_charge)
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_formal_charge_MDCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Overall_Formal_Charge
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,102
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,102
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,102
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,102
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,98
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,98
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,94
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,94
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,95
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,90
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,90
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,88
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,94
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,92
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,92
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,92
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,92
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,92
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,92
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,92
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,95
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,94
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,94
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,94
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,92
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,94
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,94
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,94
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,94
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,94
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,94
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,94
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,94
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,94
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,94
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,95
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,92
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,90
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,94
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,94
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,88
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,90
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,88
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,64
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,66
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,67
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,66
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,64
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,60
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,60
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,61

In [41]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Overall_Formal_Charge'] = df_test['SMILES'].apply(calculate_overall_formal_charge)
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_formal_charge_MDCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Overall_Formal_Charge
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,102
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,102
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,102
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,94
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,95
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,94
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,92
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,94
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,94
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,92
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,90
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,67
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,61

In [42]:
#Aromatic and ring
df_train = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train[['Is_Aromatic', 'Is_In_Ring']] = df_train['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_is_ring_is_aromatic_MDCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,1,1
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,1,1
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,1,1
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,1,1
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,1,1
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,1,1
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,1,1
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,1,1
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,1
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,1
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,1
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,1
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,1
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,1
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,1
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,1
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,1
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,1
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,1
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,1
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,1
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,1
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,1
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,1
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,1
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,1
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,1
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,1
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,1
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,1
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,1
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,1
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,1
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,1
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,1
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,1
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,1
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,1
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,1
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,1
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,1
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,1
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,1
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,1,1
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,1,1
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,1,1
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,1,1
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,1,1
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,1,1
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,1,1
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,1,1

In [43]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test[['Is_Aromatic', 'Is_In_Ring']] = df_test['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_is_ring_is_aromatic_MDCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,1,1
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,1,1
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,1,1
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,1
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,1
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,1
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,1
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,1
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,1
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,1
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,1
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,1,1
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,1,1

In [44]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_MDCK.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_formal_charge_MDCK.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_is_ring_is_aromatic_MDCK.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_train = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Train_all_atomic_desc_MDCK.csv', index=False)

In [45]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_MDCK.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_formal_charge_MDCK.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_is_ring_is_aromatic_MDCK.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_test = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Atomic/Test_all_atomic_desc_MDCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_Br,Single,Double,Triple,Aromatic,Conjugated,No-bond,Overall_Formal_Charge,Is_Aromatic,Is_In_Ring
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0.0,0.767442,0.0,0.0,0.116279,0.116279,0.000000,...,0,66,10,0,12,0,0,102,1,1
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0.0,0.750000,0.0,0.0,0.125000,0.125000,0.000000,...,0,60,10,0,12,0,0,102,1,1
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0.0,0.743590,0.0,0.0,0.128205,0.128205,0.000000,...,0,60,10,0,12,0,0,102,1,1
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0.0,0.708333,0.0,0.0,0.125000,0.152778,0.013889,...,0,64,10,0,0,0,0,94,0,1
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0.0,0.704225,0.0,0.0,0.126761,0.154930,0.014085,...,0,62,10,0,0,0,0,95,0,1
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0.0,0.700000,0.0,0.0,0.128571,0.157143,0.014286,...,0,61,10,0,0,0,0,94,0,1
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0.0,0.718310,0.0,0.0,0.126761,0.154930,0.000000,...,0,63,10,0,0,0,0,92,0,1
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,0,59,10,0,0,0,0,94,0,1
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0.0,0.695652,0.0,0.0,0.130435,0.159420,0.014493,...,0,59,10,0,0,0,0,94,0,1
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0.0,0.714286,0.0,0.0,0.128571,0.157143,0.000000,...,0,62,10,0,0,0,0,92,0,1
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0.0,0.705882,0.0,0.0,0.147059,0.147059,0.000000,...,0,58,10,0,0,0,0,90,0,1
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0.0,0.773585,0.0,0.0,0.113208,0.113208,0.000000,...,0,38,6,0,12,0,0,67,1,1
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0.0,0.760000,0.0,0.0,0.120000,0.120000,0.000000,...,0,40,6,0,6,0,0,61,1,1

In [46]:
#Fingerprints

In [47]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, rdFingerprintGenerator, rdMolDescriptors
from padelpy import padeldescriptor

In [48]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,"['L', 'meA', 'L', 'dP', 'meF', 'L', 'meA', 'L'...",1139.494
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,"['L', 'meA', 'L', 'Me_dF', 'P', 'L', 'meA', 'L...",1139.494
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,"['L', 'meF', 'L', 'dP', 'meA', 'L', 'meF', 'L'...",1139.494
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,"['L', 'meA', 'L', 'Me_dA', 'meF', 'L', 'meA', ...",1115.472
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,"['L', 'dP', 'Mono38', 'L', 'meA', 'F', 'dP', '...",1091.406
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,"['L', 'dP', 'meL', 'A', 'Mono38', 'F', 'dP', '...",1091.406
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,"['L', 'dP', 'meL', 'A', 'cHexCH2_Gly', 'F', 'd...",1089.434
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,"['L', 'dP', 'cHexCH2_Gly', 'L', 'meA', 'F', 'd...",1089.434
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,"['L', 'meA', 'Nva', 'dP', 'Me_Abu', 'Cha', 'me...",1048.403
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,"['L', 'meL', 'L', 'Me_dA', 'meA', 'L', 'meL', ...",1047.438
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,"['L', 'meA', 'L', 'dP', 'meV', 'L', 'meA', 'L'...",1043.406
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,"['L', 'meL', 'L', 'Sar', 'P', 'L', 'meL', 'L',...",1043.406
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,"['L', 'meA', 'Nva', 'dP', 'Et_Gly', 'Cha', 'me...",1034.376
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,"['ac-', 'P', 'meL', 'T', 'Me_dL', 'meL', 'L', ...",1030.363
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,"['ac-', 'dP', 'Me_dL', 'T', 'Me_dL', 'meL', 'm...",1030.363
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,"['ac-', 'P', 'Me_dL', 'T', 'meL', 'L', 'Me_dL'...",1030.363
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1016.336
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,"['ac-', 'P', 'meL', 'T', 'meL', 'L', 'meL', 'A...",1016.336
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,"['L', 'dP', 'Mono38', 'L', 'meA', 'A', 'dP', '...",1015.308
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,"['L', 'dP', 'meL', 'A', 'Mono38', 'A', 'dP', '...",1015.308
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,"['L', 'meA', 'L', 'dP', 'Me_Nva', 'Abu', 'meA'...",1008.338
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,"['L', 'Pr_Gly', 'Nva', 'dP', 'meA', 'L', 'meA'...",1008.338
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,"['dAbu', 'iBu_Gly', 'L', 'dP', 'meA', 'dL', 'M...",1008.338
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,"['dAbu', 'meA', 'L', 'dP', 'iBu_Gly', 'dL', 'M...",1008.338
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,"['ac-', 'P', 'Me_dL', 'T', 'dL', 'meL', 'dL', ...",1002.309
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,"['dAbu', 'iBu_Gly', 'dL', 'Me_dA', 'meA', 'dL'...",996.327
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'dL',...",996.327
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,"['dAbu', 'iBu_Gly', 'L', 'Me_dA', 'meA', 'L', ...",996.327
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'L', ...",996.327
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,"['dAbu', 'meA', 'dL', 'Me_dA', 'iBu_Gly', 'dL'...",996.327
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,"['dAbu', 'meA', 'L', 'Me_dA', 'iBu_Gly', 'dL',...",996.327
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,"['L', 'meA', 'L', 'dP', 'Pr_Gly', 'Abu', 'meA'...",994.311
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,"['L', 'Pr_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",994.311
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,"['L', 'meA', 'L', 'dP', 'Me_Abu', 'Abu', 'meA'...",994.311
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,"['ac-', 'dP', 'Me_dL', 'T', 'dL', 'dL', 'L', '...",988.282
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,"['L', 'meA', 'L', 'dP', 'meA', 'L', 'meA', 'L'...",987.298
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,"['L', 'Et_Gly', 'L', 'dP', 'meA', 'Abu', 'meA'...",980.284
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,"['L', 'meA', 'L', 'dP', 'Et_Gly', 'Abu', 'meA'...",980.284
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,"['L', 'meA', 'L', 'Sar', 'P', 'L', 'meA', 'L',...",959.244
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,"['A', 'meA', 'A', 'Me_dA', 'meA', 'A', 'meA', ...",794.952
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,"['A', 'meA', 'A', 'Sar', 'P', 'A', 'meA', 'A',...",790.920
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']",755.014
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,"['L', 'dF', 'dP', 'F', 'dL', 'L']",730.951
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,"['L', 'dF', 'dP', 'F', 'dL', 'I']",730.951
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,"['L', 'dF', 'P', 'F', 'dL', 'L']",730.951
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,"['L', 'dL', 'L', 'L', 'dP', 'Y']",712.933
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,"['L', 'dF', 'P', 'L', 'dL', 'L']",696.934
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,"['L', 'dF', 'dP', 'L', 'dL', 'L']",696.934
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,"['L', 'F', 'dP', 'L', 'L', 'I']",696.934

In [49]:
df_train_cmfp = df_train[['ID','SMILES','Permeability']]
df_train_cmfp

      ID                                             SMILES  Permeability
0   1114  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...     -4.940000
1   1113  CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...     -5.820000
2   1117  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...     -5.650000
3   1119  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...     -6.250000
4   2428  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...     -5.510000
5   2446  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...     -6.400000
6   2445  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...     -4.820000
7   2427  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...     -4.610000
8   8145  CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...     -5.744727
9   1107  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...     -4.610000
10  1116  CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...     -5.220000
11  1110  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...     -4.730000
12  8121  CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...     -5.289037
13  5836  CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...     -4.580000
14  6187  CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...     -5.120000
15  6584  CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...     -5.320000
16  6571  CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...     -4.970000
17  5803  CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...     -6.300000
18  2422  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...     -6.400000
19  2440  CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...     -6.520000
20  8140  CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...     -5.185752
21  8131  CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...     -5.501689
22  8346  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...     -7.562400
23  8184  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...     -7.698970
24  6505  CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...     -6.050000
25  8342  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...     -5.897175
26  8160  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...     -5.193142
27  8341  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...     -6.321123
28  8344  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...     -5.917901
29  8343  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...     -6.405218
30  8156  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...     -6.065502
31  8150  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...     -5.903090
32  8152  CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...     -5.044793
33  8116  CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...     -5.402305
34  8128  CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...     -5.585027
35  8138  CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...     -5.129011
36  6666  CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...     -6.400000
37  1115  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...     -5.190000
38  8126  CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...     -5.752027
39  8114  CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...     -5.344862
40  1111  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...     -6.220000
41  1109  C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...     -6.120000
42  1112  C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...     -6.170000
43  1018  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...     -4.960000
44  1845  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...     -4.960000
45  1847  CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...     -4.740000
46  1841  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...     -4.410000
47  1017  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -5.700000
48  1840  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...     -4.480000
49  1844  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...     -5.100000
50  1846  CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...     -4.820000

In [50]:
def generate_count_morgan_fp(smiles, radius=2, nBits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Count Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=nBits)
        count_fp = mfpgen.GetCountFingerprint(mol)
        
        # Convert the count fingerprint to a dense array
        dense_fp = np.zeros((nBits,), dtype=int)
        for bit, count in count_fp.GetNonzeroElements().items():
            dense_fp[bit] = count
            
        return dense_fp
    else:
        return None

In [51]:
df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_train_cmfp['count_morgan_fp']

/tmp/ipykernel_2375093/1551993060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)

0     [0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1     [0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2     [0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3     [0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4     [0, 3, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5     [0, 3, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6     [0, 3, 1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
7     [0, 3, 1, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8     [0, 2, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
9     [0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
10    [0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
11    [0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
12    [0, 2, 1, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
13    [0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
14    [0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
15    [0, 6, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
16    [0, 6, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
17    [0, 6, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
18    [0, 3, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
19    [0, 3, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
20    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
21    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
22    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
23    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
24    [0, 6, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
25    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
26    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
27    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
28    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
29    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
30    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
31    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
32    [0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
33    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
34    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
35    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
36    [0, 6, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
37    [0, 4, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
38    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
39    [0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
40    [0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
41    [0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
42    [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
43    [0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
44    [0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
45    [0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
46    [0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
47    [0, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
48    [0, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
49    [0, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
50    [0, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: count_morgan_fp, dtype: object

In [52]:
df = pd.DataFrame(df_train_cmfp['count_morgan_fp'].tolist(), index=df_train_cmfp.index)

df_train_cmfp = pd.concat([df_train_cmfp, df.add_prefix('count_fp_')], axis=1)
df_train_cmfp.shape

(51, 2052)

In [53]:
df_train_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_train_cmfp.shape

(51, 2051)

In [54]:
df_train_cmfp.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/count_morgan_fp_train_MDCK.csv', index=False)

In [55]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
df_test_cmfp = df_test[['ID','SMILES','Permeability']]
df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_test_cmfp['count_morgan_fp']
df = pd.DataFrame(df_test_cmfp['count_morgan_fp'].tolist(), index=df_test_cmfp.index)

df_test_cmfp = pd.concat([df_test_cmfp, df.add_prefix('count_fp_')], axis=1)
df_test_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_test_cmfp.shape

/tmp/ipykernel_2375093/3600079707.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)

(13, 2051)

In [56]:
df_test_cmfp.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/count_morgan_fp_test_MDCK.csv', index=False)

In [57]:
def generate_fingerprints(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Create a Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
        
        # Generate the Morgan fingerprint as a bit vector
        morgan_fp = mfpgen.GetFingerprint(mol)
        
        # Convert the bit vector to a dense array
        dense_fp = np.zeros((2048,), dtype=int)
        for bit in range(2048):
            dense_fp[bit] = morgan_fp[bit]
        
        return dense_fp
    else:
        print("Invalid SMILES string.")
        return None

In [58]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
df_mfp_train = df_train[['ID','SMILES','Permeability']]
df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_train['Morganfingerprints'].tolist(), index=df_mfp_train.index)

df_mfp_train = pd.concat([df_mfp_train, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_train.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/morgan_fp_train_MDCK.csv', index=False)
print(df_mfp_train.shape)
df_mfp_train

(51, 2051)

/tmp/ipykernel_2375093/1231547062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,1,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,1,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,1,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
df_mfp_test = df_test[['ID','SMILES','Permeability']]
df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_test['Morganfingerprints'].tolist(), index=df_mfp_test.index)

df_mfp_test = pd.concat([df_mfp_test, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_test.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/morgan_fp_test_MDCK.csv', index=False)
print(df_mfp_test.shape)
df_mfp_test

(13, 2051)

/tmp/ipykernel_2375093/1354915269.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,1,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
#Padel fingerprints
import glob
import os
directory = '/home/users/akshay/PCPpred/fingerprints_xml'
pattern = '*.xml'  

xml_files = glob.glob(os.path.join(directory, pattern))
xml_files.sort()
xml_files

['/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml']

In [61]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'Extended',
 'Fingerprinter',
 'Graphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [62]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 'EState': '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 'Extended': '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 'Fingerprinter': '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 'Graphonly': '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 'MACCS': '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 'PubChem': '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 'SubstructureCount': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 'Substructure': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml'}

In [63]:
#Substructure
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,1114,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,1113,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1117,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,1119,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2428,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
5,2446,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
6,2445,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
7,2427,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
8,8145,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
9,1107,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
10,1116,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
11,1110,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
12,8121,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
13,5836,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
14,6187,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
15,6584,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
16,6571,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
17,5803,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
18,2422,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
19,2440,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
20,8140,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
21,8131,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
22,8346,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
23,8184,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
24,6505,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
25,8342,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
26,8160,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
27,8341,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
28,8344,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
29,8343,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
30,8156,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
31,8150,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
32,8152,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
33,8116,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
34,8128,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
35,8138,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
36,6666,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
37,1115,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
38,8126,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
39,8114,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
40,1111,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
41,1109,1,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
42,1112,1,1,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
43,1018,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
44,1845,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
45,1847,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
46,1841,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
47,1017,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
48,1840,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
49,1844,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
50,1846,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [64]:
df_Substructure_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_Substructure_train.head()

,ID,SMILES,Permeability,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.94,1114,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.82,1113,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.65,1117,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.25,1119,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.51,2428,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [65]:
df_Substructure_train.drop(['Name'],axis=1,inplace=True)
df_Substructure_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Substructure_train_MDCK.csv', index=False)
df_Substructure_train

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,1,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,1,1,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [66]:
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_Substructure_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
# df_Substructure_train.head()
df_Substructure_test.drop(['Name'],axis=1,inplace=True)
df_Substructure_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Substructure_test_MDCK.csv', index=False)
df_Substructure_test

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [67]:
#CountSubstructure
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_train.head()

,ID,SMILES,Permeability,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.94,1114,10.0,10.0,4.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.82,1113,10.0,10.0,4.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.65,1117,10.0,10.0,4.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.25,1119,12.0,6.0,4.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,46.0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.51,2428,9.0,10.0,4.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0

In [68]:
df_SubstructureCount_train.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/SubstructureCount_train_MDCK.csv', index=False)
df_SubstructureCount_train

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,10.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,10.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,10.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,12.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,46.0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,9.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,9.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,9.0,13.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,9.0,13.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,9.0,13.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,59.0,59.0,12.0,0.0,0.0,0.0,0.0,31.0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,16.0,6.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,36.0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,14.0,8.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,10.0,0.0,0.0,0.0,0.0,36.0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,12.0,10.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,12.0,0.0,0.0,0.0,0.0,34.0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,9.0,12.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,30.0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,10.0,9.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,59.0,59.0,9.0,0.0,0.0,0.0,0.0,32.0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,10.0,9.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,59.0,59.0,9.0,0.0,0.0,0.0,0.0,32.0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,11.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,11.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,55.0,55.0,13.0,0.0,0.0,0.0,0.0,30.0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,12.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,12.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,11.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,30.0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,11.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,30.0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,11.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,11.0,0.0,0.0,0.0,0.0,31.0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,12.0,8.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,56.0,56.0,8.0,0.0,0.0,0.0,0.0,34.0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,11.0,6.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,11.0,0.0,0.0,0.0,0.0,30.0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,11.0,6.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,11.0,0.0,0.0,0.0,0.0,30.0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,10.0,8.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,8.0,0.0,0.0,0.0,0.0,32.0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,40.0,40.0,0.0,0.0,0.0,0.0,0.0,30.0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,6.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,42.0,0.0,0.0,0.0,0.0,0.0,28.0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,6.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,6.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,6.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0

In [69]:
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_test.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/SubstructureCount_test_MDCK.csv', index=False)
df_SubstructureCount_test

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,14.0,8.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,60.0,60.0,16.0,0.0,0.0,0.0,0.0,48.0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,12.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,46.0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,10.0,10.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,9.0,12.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,30.0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,11.0,9.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,56.0,56.0,13.0,0.0,0.0,0.0,0.0,31.0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,11.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,55.0,55.0,13.0,0.0,0.0,0.0,0.0,30.0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,13.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,13.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,14.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,52.0,52.0,8.0,0.0,0.0,0.0,0.0,34.0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,6.0,7.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0

In [70]:
#MACCS
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_train.head()
df_MACCS_train.drop(['Name'],axis=1,inplace=True)
df_MACCS_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/MACCS_train_MDCK.csv', index=False)
df_MACCS_train

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0

In [71]:
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_test.drop(['Name'],axis=1,inplace=True)
df_MACCS_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/MACCS_test_MDCK.csv', index=False)
df_MACCS_test

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0

In [72]:
#PubChem
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_train.drop(['Name'],axis=1,inplace=True)
df_PubChem_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/PubChem_train_MDCK.csv', index=False)
df_PubChem_train

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_test.drop(['Name'],axis=1,inplace=True)
df_PubChem_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/PubChem_test_MDCK.csv', index=False)
df_PubChem_test

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
#AtomPairs2DCount
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/AtomPairs2DCount_train_MDCK.csv', index=False)
df_AtomPairs2DCount_train

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,50.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,50.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,50.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,46.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,44.0,26.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,44.0,26.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,46.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,46.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,38.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,38.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,40.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,40.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,37.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,39.0,24.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,39.0,24.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,39.0,24.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,39.0,23.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,39.0,23.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,37.0,26.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,37.0,26.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,34.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,34.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,34.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,34.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,39.0,22.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,33.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,33.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,33.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,39.0,21.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,36.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,34.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,20.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,22.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,33.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,37.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,37.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,37.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,33.0,13.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,33.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,33.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,33.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/AtomPairs2DCount_test_MDCK.csv', index=False)
df_AtomPairs2DCount_test

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,52.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,46.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,50.0,22.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,37.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,35.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,34.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,39.0,22.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,32.0,23.0,12.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,39.0,21.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,32.0,26.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,37.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,33.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
#AtomPairs2D
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/AtomPairs2D_train_MDCK.csv', index=False)
df_AtomPairs2D_train

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/AtomPairs2D_test_MDCK.csv', index=False)
df_AtomPairs2D_test

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
#EState
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_train.drop(['Name'],axis=1,inplace=True)
EState_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/EState_train_MDCK.csv', index=False)
EState_train

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [79]:
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_test.drop(['Name'],axis=1,inplace=True)
EState_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/EState_test_MDCK.csv', index=False)
EState_test

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [80]:
#Extended
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_train.drop(['Name'],axis=1,inplace=True)
Extended_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Extended_train_MDCK.csv', index=False)
Extended_train

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [81]:
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_test.drop(['Name'],axis=1,inplace=True)
Extended_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Extended_test_MDCK.csv', index=False)
Extended_test

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [82]:
#Fingerprinter
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_train.drop(['Name'],axis=1,inplace=True)
Fingerprinter_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Fingerprinter_train_MDCK.csv', index=False)
Fingerprinter_train

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0

In [83]:
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_test.drop(['Name'],axis=1,inplace=True)
Fingerprinter_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Fingerprinter_test_MDCK.csv', index=False)
Fingerprinter_test

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,1,0,0,0,1,1,0,...,0,1,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0

In [84]:
#GraphOnly
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_train.drop(['Name'],axis=1,inplace=True)
Graphonly_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Graphonly_train_MDCK.csv', index=False)
Graphonly_train

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_test.drop(['Name'],axis=1,inplace=True)
Graphonly_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Graphonly_test_MDCK.csv', index=False)
Graphonly_test

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [86]:
#KlekotaRothCount
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_train.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/KlekotaRothCount_train_MDCK.csv', index=False)
KlekotaRothCount_train

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,12.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,16.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,11.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,12.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,11.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,11.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,11.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,11.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,11.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,9.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,10.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [87]:
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_test.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/KlekotaRothCount_test_MDCK.csv', index=False)
KlekotaRothCount_test

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,16.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,11.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,12.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,11.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,15.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,9.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,10.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [88]:
#KlekotaRoth
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_train.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_train.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/KlekotaRoth_train_MDCK.csv', index=False)
KlekotaRoth_train

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/MDCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_test.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_test.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/KlekotaRoth_test_MDCK.csv', index=False)
KlekotaRoth_test

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [90]:
df_train_morgan = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/morgan_fp_train_MDCK.csv')
df_train_morganCount = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/count_morgan_fp_train_MDCK.csv')
df_train_AP2d = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/AtomPairs2D_train_MDCK.csv')
df_train_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/AtomPairs2DCount_train_MDCK.csv')
df_train_EState = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/EState_train_MDCK.csv')
df_train_Extended = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Extended_train_MDCK.csv')
df_train_fp= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Fingerprinter_train_MDCK.csv')
df_train_graph= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Graphonly_train_MDCK.csv')
df_train_kr= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/KlekotaRoth_train_MDCK.csv')
df_train_krcount= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/KlekotaRothCount_train_MDCK.csv')
df_train_maccs= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/MACCS_train_MDCK.csv')
df_train_pubchem= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/PubChem_train_MDCK.csv')
df_train_Substr= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/Substructure_train_MDCK.csv')
df_train_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/SubstructureCount_train_MDCK.csv')

df = df_train_morgan.merge(df_train_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,46.0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,0,1,0,0,0,1,0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,0,1,0,0,0,1,0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,0,1,1,0,0,1,0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,0,1,1,0,0,1,0,...,0.0,0.0,60.0,60.0,11.0,0.0,0.0,0.0,0.0,38.0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,0,1,1,0,0,1,0,...,0.0,0.0,59.0,59.0,12.0,0.0,0.0,0.0,0.0,31.0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,36.0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,0,1,0,0,0,1,0,...,0.0,0.0,60.0,60.0,10.0,0.0,0.0,0.0,0.0,36.0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,0,1,0,0,0,1,0,...,0.0,0.0,60.0,60.0,12.0,0.0,0.0,0.0,0.0,34.0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,0,1,1,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,30.0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,0,1,0,0,0,1,0,...,0.0,0.0,59.0,59.0,9.0,0.0,0.0,0.0,0.0,32.0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,0,1,0,0,0,1,0,...,0.0,0.0,59.0,59.0,9.0,0.0,0.0,0.0,0.0,32.0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,0,1,0,0,0,1,0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,0,1,0,0,0,1,0,...,0.0,0.0,55.0,55.0,13.0,0.0,0.0,0.0,0.0,30.0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,0,1,0,0,0,1,0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,0,1,0,0,0,1,0,...,0.0,0.0,55.0,55.0,12.0,0.0,0.0,0.0,0.0,31.0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,30.0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,30.0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,11.0,0.0,0.0,0.0,0.0,31.0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,0,1,0,0,0,1,0,...,0.0,0.0,56.0,56.0,8.0,0.0,0.0,0.0,0.0,34.0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,11.0,0.0,0.0,0.0,0.0,30.0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,11.0,0.0,0.0,0.0,0.0,30.0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,8.0,0.0,0.0,0.0,0.0,32.0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,0,0,0,0,0,1,0,...,0.0,0.0,40.0,40.0,0.0,0.0,0.0,0.0,0.0,30.0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,0,0,0,0,0,1,0,...,0.0,0.0,42.0,42.0,0.0,0.0,0.0,0.0,0.0,28.0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,0,1,0,0,0,1,0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,0,1,0,0,0,1,0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,0,1,0,0,0,1,0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,0,1,0,0,0,1,0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,0,1,0,0,0,1,0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0

In [91]:
df.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Train/All_fingerprints_train_MDCK.csv',index=False)

In [92]:
df_test_morgan = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/morgan_fp_test_MDCK.csv')
df_test_morganCount = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/count_morgan_fp_test_MDCK.csv')
df_test_AP2d = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/AtomPairs2D_test_MDCK.csv')
df_test_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/AtomPairs2DCount_test_MDCK.csv')
df_test_EState = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/EState_test_MDCK.csv')
df_test_Extended = pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Extended_test_MDCK.csv')
df_test_fp= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Fingerprinter_test_MDCK.csv')
df_test_graph= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Graphonly_test_MDCK.csv')
df_test_kr= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/KlekotaRoth_test_MDCK.csv')
df_test_krcount= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/KlekotaRothCount_test_MDCK.csv')
df_test_maccs= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/MACCS_test_MDCK.csv')
df_test_pubchem= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/PubChem_test_MDCK.csv')
df_test_Substr= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/Substructure_test_MDCK.csv')
df_test_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/SubstructureCount_test_MDCK.csv')

df = df_test_morgan.merge(df_test_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,0,1,0,0,0,1,0,...,0.0,0.0,60.0,60.0,16.0,0.0,0.0,0.0,0.0,48.0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,0,1,0,0,0,1,0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,46.0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,46.0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,0,1,1,0,0,1,0,...,0.0,0.0,58.0,58.0,12.0,0.0,0.0,0.0,0.0,30.0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,0,1,0,0,0,1,0,...,0.0,0.0,56.0,56.0,13.0,0.0,0.0,0.0,0.0,31.0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,0,1,0,0,0,1,0,...,0.0,0.0,55.0,55.0,13.0,0.0,0.0,0.0,0.0,30.0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,0,1,0,0,0,1,0,...,0.0,0.0,53.0,53.0,12.0,0.0,0.0,0.0,0.0,31.0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,0,1,0,0,0,1,0,...,0.0,0.0,58.0,58.0,17.0,0.0,0.0,0.0,0.0,34.0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,0,1,0,0,0,1,0,...,0.0,0.0,52.0,52.0,8.0,0.0,0.0,0.0,0.0,34.0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,0,1,0,0,0,1,0,...,0.0,0.0,37.0,37.0,10.0,0.0,0.0,0.0,0.0,33.0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0

In [93]:
df.to_csv('/home/users/akshay/PCPpred/MDCK/features/Fingerprints/Test/All_fingerprints_test_MDCK.csv',index=False)

In [94]:
#Descriptors
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors, Descriptors3D
from rdkit.ML.Descriptors import MoleculeDescriptors
from tqdm import tqdm

In [95]:
calc = MoleculeDescriptors.MolecularDescriptorCalculator([desc[0] for desc in Chem.Descriptors._descList])

def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None 
    return calc.CalcDescriptors(mol)

In [96]:
#2D RDKit train dataset descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
train_2d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_2d_rdkit.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Train_2d_RDKit_des_MDCK.csv',index=False)
print("Shape: ",train_2d_rdkit.shape, '\n')
train_2d_rdkit

Shape:  (51, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,14.922930,14.922930,0.059501,-1.162678,0.238950,27.097561,1139.494,...,0,0,0,0,0,0,0,0,0,0
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,15.128047,15.128047,0.075261,-1.145488,0.238950,27.097561,1139.494,...,0,0,0,0,0,0,0,0,0,0
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,14.908525,14.908525,0.051146,-1.177248,0.238950,27.097561,1139.494,...,0,0,0,0,0,0,0,0,0,0
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,14.724823,14.724823,0.030635,-1.196597,0.240803,26.125000,1115.472,...,0,0,0,0,0,0,0,0,0,0
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,14.918925,14.918925,0.008728,-1.166833,0.250056,27.358974,1091.406,...,0,0,0,0,0,0,0,0,0,0
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,14.912312,14.912312,0.031806,-1.168185,0.250056,27.358974,1091.406,...,0,0,0,0,0,0,0,0,0,0
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,14.926201,14.926201,0.060156,-1.148185,0.252488,27.358974,1089.434,...,0,0,0,0,0,0,0,0,0,0
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,14.950175,14.950175,0.063054,-1.159021,0.252488,27.358974,1089.434,...,0,0,0,0,0,0,0,0,0,0
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,14.598899,14.598899,0.013996,-1.178122,0.218577,28.506849,1048.403,...,1,0,0,0,0,0,0,0,0,0
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,14.543197,14.543197,0.095971,-1.130815,0.222694,27.567568,1047.438,...,0,0,0,0,0,0,0,0,0,0
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,14.603835,14.603835,0.072518,-1.111982,0.249739,29.027027,1043.406,...,0,0,0,0,0,0,0,0,0,0
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,14.585675,14.585675,0.071338,-1.078376,0.223101,27.000000,1043.406,...,0,0,0,0,0,0,0,0,0,0
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,14.473440,14.473440,0.015046,-1.175677,0.218370,27.694444,1034.376,...,1,0,0,0,0,0,0,0,0,0
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,15.282381,15.282381,0.084965,-1.638877,0.214139,27.342466,1030.363,...,0,0,0,0,0,0,0,0,0,0
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,15.305496,15.305496,0.081863,-1.638898,0.214139,27.342466,1030.363,...,0,0,0,0,0,0,0,0,0,0
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,15.222624,15.222624,0.080169,-1.639654,0.214139,27.342466,1030.363,...,0,0,0,0,0,0,0,0,0,0
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,14.914326,14.914326,0.084455,-1.652766,0.184453,27.402778,1016.336,...,0,0,0,0,0,0,0,0,0,0
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,15.189566,15.189566,0.081651,-1.639182,0.184453,27.402778,1016.336,...,0,0,0,0,0,0,0,0,0,0
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,14.803574,14.803574,0.002082,-1.099611,0.252618,28.708333,1015.308,...,0,0,0,0,0,0,0,0,0,0
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,14.509254,14.509254,0.006521,-1.134482,0.252618,28.708333,1015.308,...,0,0,0,0,0,0,0,0,0,0
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,14.444016,14.444016,0.010321,-1.180583,0.217233,27.714286,1008.338,...,1,0,0,0,0,0,0,0,0,0
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,14.284782,14.284782,0.012204,-1.178350,0.205195,26.642857,1008.338,...,1,0,0,0,0,0,0,0,0,0
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,14.378251,14.378251,0.011249,-1.178363,0.216734,26.728571,1008.338,...,1,0,0,0,0,0,0,0,0,0
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,14.499313,14.499313,0.010904,-1.177923,0.216734,26.728571,1008.338,...,1,0,0,0,0,0,0,0,0,0
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,14.881268,14.881268,0.085493,-1.652293,0.157962,27.464789,1002.309,...,0,0,0,0,0,0,0,0,0,0
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,14.235704,14.235704,0.008614,-1.181469,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,14.228063,14.228063,0.008269,-1.181029,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,14.235704,14.235704,0.008614,-1.181469,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,14.235704,14.235704,0.008614,-1.181469,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,14.235704,14.235704,0.008614,-1.181469,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,14.228063,14.228063,0.008269,-1.181029,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,14.228063,14.228063,0.008269,-1.181029,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,14.228063,14.228063,0.008269,-1.181029,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,14.394646,14.394646,0.011348,-1.178110,0.215672,26.855072,994.311,...,1,0,0,0,0,0,0,0,0,0
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,14.337346,14.337346,0.012277,-1.176953,0.215672,26.855072,994.311,...,1,0,0,0,0,0,0,0,0,0
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,14.387844,14.387844,0.010162,-1.180201,0.228031,27.942029,994.311,...,1,0,0,0,0,0,0,0,0,0
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,14.765338,14.765338,0.082043,-1.652577,0.137104,27.528571,988.282,...,0,0,0,0,0,0,0,0,0,0
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,14.414997,14.414997,0.065307,-1.102188,0.273538,29.828571,987.298,...,0,0,0,0,0,0,0,0,0,0
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,14.281173,14.281173,0.011948,-1.176456,0.225535,27.073529,980.284,...,1,0,0,0,0,0,0,0,0,0
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,14.325105,14.325105,0.011213,-1.177756,0.225535,27.073529,980.284,...,1,0,0,0,0,0,0,0,0,0
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,14.151761,14.151761,0.062919,-1.093507,0.266057,28.147059,959.244,...,0,0,0,0,0,0,0,0,0,0
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,13.404198,13.404198,0.619078,-1.140156,0.195237,31.928571,794.952,...,0,0,0,0,0,0,0,0,0,0
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,13.349192,13.349192,0.236703,-1.098933,0.189935,31.178571,790.920,...,0,0,0,0,0,0,0,0,0,0
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,14.519743,14.519743,0.006274,-1.075529,0.329549,25.833333,755.014,...,0,0,0,0,0,0,0,0,0,0
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,14.417881,14.417881,0.004127,-1.060030,0.252294,25.264151,730.951,...,0,0,0,0,0,0,0,0,0,0
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,14.424770,14.424770,0.002738,-1.061047,0.252294,25.773585,730.951,...,0,0,0,0,0,0,0,0,0,0
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,14.417881,14.417881,0.004127,-1.060030,0.252294,25.264151,730.951,...,0,0,0,0,0,0,0,0,0,0
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,14.157239,14.157239,0.000719,-1.126245,0.215270,26.000000,712.933,...,0,0,0,0,0,0,0,0,0,0
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,14.304629,14.304629,0.015186,-1.012534,0.252518,26.280000,696.934,...,0,0,0,0,0,0,0,0,0,0
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,14.304629,14.304629,0.015186,-1.012534,0.252518,26.280000,696.934,...,0,0,0,0,0,0,0,0,0,0
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,14.311518,14.311518,0.013797,-1.013552,0.252518,26.820000,696.934,...,0,0,0,0,0,0,0,0,0,0

In [97]:
#2D RDKit test dataset descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
test_2d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_2d_rdkit.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Test_2d_RDKit_des_MDCK.csv',index=False)
print("Shape: ",test_2d_rdkit.shape, '\n')
test_2d_rdkit

Shape:  (13, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,15.211581,15.211581,0.031713,-1.206465,0.159924,25.279070,1199.634,...,0,0,0,0,0,0,0,0,0,0
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,14.834083,14.834083,0.037197,-1.184826,0.240803,26.125000,1115.472,...,0,0,0,0,0,0,0,0,0,0
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,14.571211,14.571211,0.032067,-1.213008,0.153969,27.307692,1083.386,...,0,0,0,0,0,0,0,0,0,0
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,14.507460,14.507460,0.015782,-1.174377,0.218370,27.694444,1034.376,...,1,0,0,0,0,0,0,0,0,0
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,14.432367,14.432367,0.010248,-1.181980,0.206072,27.492958,1022.365,...,1,0,0,0,0,0,0,0,0,0
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,14.337271,14.337271,0.011275,-1.179506,0.205195,26.642857,1008.338,...,1,0,0,0,0,0,0,0,0,0
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,14.798396,14.798396,0.082911,-1.653049,0.157962,27.464789,1002.309,...,0,0,0,0,0,0,0,0,0,0
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,14.228063,14.228063,0.008269,-1.181029,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,14.235704,14.235704,0.008614,-1.181469,0.216153,26.159420,996.327,...,1,0,0,0,0,0,0,0,0,0
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,14.765338,14.765338,0.082043,-1.652577,0.137104,27.528571,988.282,...,0,0,0,0,0,0,0,0,0,0
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,14.121032,14.121032,0.089106,-1.124048,0.271385,28.764706,963.276,...,0,0,0,0,0,0,0,0,0,0
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,14.424770,14.424770,0.002738,-1.061047,0.252294,25.773585,730.951,...,0,0,0,0,0,0,0,0,0,0
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,14.311518,14.311518,0.013797,-1.013552,0.252518,26.820000,696.934,...,0,0,0,0,0,0,0,0,0,0

In [98]:
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=True)

def calculate_mordred_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Return None if the SMILES is invalid
    return calc(mol)

In [99]:
print('start')
#2D Mordred train descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
train_mordred_2d = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_mordred_2d.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Train_2d_Mordred_desc_MDCK.csv', index=False)
print('Shape: ',train_mordred_2d.shape)
train_mordred_2d

start

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (51, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,101.372024,2.447751,4.856077,...,11.210644,138.066274,1138.715439,6.469974,33296,140,416.0,486.0,34.055556,18.111111
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,101.370874,2.447978,4.860529,...,11.210644,138.066274,1138.715439,6.469974,33296,140,416.0,486.0,34.055556,18.111111
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,101.371868,2.443590,4.850728,...,11.210644,138.066274,1138.715439,6.469974,33296,140,416.0,486.0,34.055556,18.111111
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,97.295643,2.408298,4.816595,...,11.141644,120.163455,1114.715439,6.406411,31648,138,396.0,458.0,36.555556,17.777778
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,96.774478,2.436865,4.825853,...,11.126159,133.738666,1090.679054,6.492137,29794,130,394.0,458.0,31.222222,17.333333
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,96.685868,2.442093,4.836451,...,11.129393,133.743086,1090.679054,6.492137,29704,130,394.0,458.0,31.222222,17.333333
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,96.685868,2.442093,4.836451,...,11.129393,133.743086,1088.699789,6.404116,29704,130,394.0,458.0,31.222222,17.333333
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,96.774478,2.436865,4.825853,...,11.126159,133.738666,1088.699789,6.404116,29794,130,394.0,458.0,31.222222,17.333333
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,89.136837,2.437073,4.831019,...,11.025019,126.223556,1047.640226,6.466915,25439,124,358.0,415.0,31.750000,16.611111
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,86.880063,2.403063,4.806126,...,11.046579,113.682027,1046.746739,6.085737,25829,128,360.0,414.0,38.055556,16.444444
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,87.973946,2.449511,4.859638,...,11.131855,129.565762,1042.715439,6.206640,25478,130,372.0,436.0,35.055556,16.333333
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,88.006678,2.417754,4.806157,...,11.048554,129.372353,1042.715439,6.206640,25892,122,368.0,424.0,33.833333,16.333333
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,88.158274,2.426820,4.806966,...,10.985954,125.096326,1033.624576,6.500783,24771,120,352.0,406.0,30.888889,16.388889
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,87.482787,2.441288,4.866488,...,11.097274,128.448227,1029.683805,6.278560,24099,126,366.0,427.0,34.194444,16.111111
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,87.442154,2.443436,4.875184,...,11.099242,128.450816,1029.683805,6.278560,24029,126,366.0,427.0,34.194444,16.111111
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,87.482740,2.438682,4.857460,...,11.097274,128.448227,1029.683805,6.278560,24150,126,366.0,427.0,34.194444,16.111111
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,86.052907,2.431373,4.834990,...,11.058464,127.323902,1015.668155,6.308498,23535,122,360.0,418.0,33.333333,15.888889
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,86.013833,2.436302,4.850446,...,11.060510,127.326588,1015.668155,6.308498,23419,122,360.0,418.0,33.333333,15.888889
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,88.237229,2.435303,4.820162,...,11.047885,127.327227,1014.647754,6.421821,24373,121,362.0,421.0,30.611111,16.000000
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,88.143569,2.438940,4.828935,...,11.051382,127.332009,1014.647754,6.421821,24463,121,362.0,421.0,30.611111,16.000000
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,84.338717,2.439007,4.830953,...,10.972894,122.961448,1007.608926,6.500703,22840,119,340.0,393.0,32.500000,15.944444
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.968060,2.430758,4.814110,...,10.937792,122.874218,1007.608926,6.500703,22977,116,338.0,388.0,31.888889,15.972222
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.623906,2.432773,4.817253,...,10.947344,122.911611,1007.608926,6.500703,22971,116,340.0,390.0,32.500000,15.805556
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.623870,2.431970,4.813001,...,10.947344,122.911611,1007.608926,6.500703,22919,116,340.0,390.0,32.500000,15.805556
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,84.587504,2.429539,4.829169,...,11.020382,126.198903,1001.652505,6.339573,22812,118,354.0,409.0,32.472222,15.666667
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585744,2.384457,4.768915,...,10.902997,108.140710,995.608926,6.464993,22278,115,330.0,376.0,33.750000,15.638889
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585614,2.381030,4.762061,...,10.902997,108.140710,995.608926,6.464993,22236,115,330.0,376.0,33.750000,15.638889
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585744,2.384457,4.768915,...,10.902997,108.140710,995.608926,6.464993,22278,115,330.0,376.0,33.750000,15.638889
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585744,2.384457,4.768915,...,10.902997,108.140710,995.608926,6.464993,22278,115,330.0,376.0,33.750000,15.638889
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585744,2.384457,4.768915,...,10.902997,108.140710,995.608926,6.464993,22278,115,330.0,376.0,33.750000,15.638889
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585614,2.381030,4.762061,...,10.902997,108.140710,995.608926,6.464993,22236,115,330.0,376.0,33.750000,15.638889
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585614,2.381030,4.762061,...,10.902997,108.140710,995.608926,6.464993,22236,115,330.0,376.0,33.750000,15.638889
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585614,2.381030,4.762061,...,10.902997,108.140710,995.608926,6.464993,22236,115,330.0,376.0,33.750000,15.638889
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,82.935418,2.429881,4.808466,...,10.931516,121.827098,993.593275,6.536798,22190,115,334.0,384.0,31.638889,15.722222
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,82.920959,2.432253,4.813802,...,10.931516,121.827098,993.593275,6.536798,22179,115,334.0,384.0,31.638889,15.722222
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,82.880382,2.438030,4.828399,...,10.966663,121.914793,993.593275,6.536798,22062,118,336.0,389.0,32.250000,15.694444
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.165492,2.427826,4.818625,...,10.978746,125.067539,987.636855,6.371851,22212,114,348.0,400.0,31.611111,15.444444
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,84.418828,2.439188,4.833076,...,11.058244,125.260188,986.652839,6.324698,22502,122,352.0,412.0,32.833333,15.444444
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.889898,2.432179,4.813547,...,10.925201,120.779487,979.577625,6.574346,21415,114,330.0,380.0,31.388889,15.472222
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.893112,2.428751,4.806473,...,10.925201,120.779487,979.577625,6.574346,21417,114,330.0,380.0,31.388889,15.472222
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.469222,2.412411,4.786967,...,10.979530,123.003145,958.621539,6.390810,21211,114,340.0,394.0,31.111111,15.000000
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,67.087415,2.378039,4.756078,...,10.831569,94.473307,794.465038,6.732755,13190,104,276.0,324.0,29.888889,12.444444
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,68.212890,2.402537,4.756729,...,10.834016,110.182557,790.433738,6.933629,13235,98,284.0,334.0,25.666667,12.333333
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,65.330239,2.451132,4.874519,...,10.789999,105.920241,754.499298,6.287494,10372,92,272.0,316.0,23.944444,11.888889
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,65.488617,2.425264,4.803512,...,10.664363,104.620114,730.441784,6.580557,10243,83,266.0,304.0,19.750000,11.722222
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.166214,2.425971,4.807980,...,10.684714,104.660684,730.441784,6.580557,10195,85,266.0,306.0,19.750000,11.833333
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,65.488617,2.425264,4.803512,...,10.664363,104.620114,730.441784,6.580557,10243,83,266.0,304.0,19.750000,11.722222
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,61.346664,2.422289,4.796747,...,10.622229,102.392896,712.452348,6.418490,9286,80,254.0,289.0,21.361111,11.222222
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.265074,2.424017,4.799778,...,10.588477,101.254858,696.457434,6.331431,8739,78,248.0,282.0,20.500000,11.055556
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.265074,2.424017,4.799778,...,10.588477,101.254858,696.457434,6.331431,8739,78,248.0,282.0,20.500000,11.055556
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.942672,2.424731,4.804488,...,10.610414,101.298560,696.457434,6.331431,8694,80,248.0,284.0,20.500000,11.166667

In [100]:
#2D Mordred test descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
test_mordred_2d = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_mordred_2d.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Test_2d_Mordred_desc_MDCK.csv', index=False)
print('Shape: ',test_mordred_2d.shape)
test_mordred_2d

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (13, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,103.838268,2.420071,4.840143,...,11.200910,126.480968,1198.809340,6.243799,37307,146,424.0,488.0,39.277778,19.111111
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,97.302139,2.412394,4.824787,...,11.141934,120.163745,1114.715439,6.406411,31648,138,396.0,458.0,36.555556,17.777778
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,95.621135,2.421653,4.790984,...,11.069213,133.614531,1082.652839,6.601542,30176,124,392.0,450.0,30.611111,17.222222
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,88.159241,2.431154,4.817857,...,10.985954,125.096326,1033.624576,6.500783,24767,120,352.0,406.0,30.888889,16.388889
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,85.381854,2.437654,4.830440,...,10.978917,124.007460,1021.624576,6.465978,23619,120,344.0,397.0,32.750000,16.194444
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.965708,2.427767,4.806183,...,10.937792,122.874218,1007.608926,6.500703,22971,116,338.0,388.0,31.888889,15.972222
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,84.630944,2.429295,4.822808,...,11.018416,126.196276,1001.652505,6.339573,22927,118,354.0,409.0,32.472222,15.666667
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585614,2.381030,4.762061,...,10.902997,108.140710,995.608926,6.464993,22236,115,330.0,376.0,33.750000,15.638889
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,81.585744,2.384457,4.768915,...,10.902997,108.140710,995.608926,6.464993,22278,115,330.0,376.0,33.750000,15.638889
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.165492,2.427826,4.818625,...,10.978746,125.067539,987.636855,6.371851,22212,114,348.0,400.0,31.611111,15.444444
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,80.342595,2.393888,4.787776,...,10.977414,107.307533,962.652839,6.250992,21154,120,332.0,384.0,35.333333,15.111111
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.166214,2.425971,4.807980,...,10.684714,104.660684,730.441784,6.580557,10195,85,266.0,306.0,19.750000,11.833333
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.942672,2.424731,4.804488,...,10.610414,101.298560,696.457434,6.331431,8694,80,248.0,284.0,20.500000,11.166667

In [101]:
#RDKit 3d descriptors
def generate_3d_descriptors(smiles):
    # Convert SMILES to a molecule object
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    
    # Add hydrogens
    mol = Chem.AddHs(mol)
    
    # Generate 3D coordinates for the molecule
    AllChem.EmbedMolecule(mol)
    
    try:
        descriptors = Descriptors3D.CalcMolDescriptors3D(mol)
        return descriptors
    except Exception as e:
        print(f"Error calculating descriptors for SMILES '{smiles}': {e}")
        return None

In [102]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.csv")
descriptor_data = []
for smiles in tqdm(df_train['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors =generate_3d_descriptors(smiles) 
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

3d_descriptors: 100%|██████████| 51/51 [00:38<00:00,  1.33smiles/s]

In [103]:
descriptor_df = pd.DataFrame(descriptor_data)
descriptor_df

,PMI1,PMI2,PMI3,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF
0,24313.755201,30312.376753,46681.937558,0.520839,0.649338,6.667315,0.000027,0.853655,0.156729,0.289553,1.754389
1,20729.202872,33683.486578,45247.431206,0.458130,0.744429,6.612865,0.000036,0.888885,0.181770,0.322778,1.865993
2,20665.252633,38087.030609,54414.093500,0.379778,0.699948,7.046731,0.000034,0.925078,0.266905,0.145286,1.320561
3,23316.296843,27342.847641,44212.952948,0.527363,0.618435,6.521161,0.000027,0.849640,0.163872,0.236521,1.643716
4,17548.732916,32062.570730,44521.068339,0.394167,0.720166,6.566914,0.000041,0.919039,0.246786,0.209742,1.512311
5,19844.954604,31315.006377,42161.230503,0.470692,0.742744,6.538558,0.000037,0.882298,0.171600,0.343405,1.939268
6,20353.342160,32484.579946,45010.234764,0.452194,0.721715,6.701328,0.000035,0.891920,0.190515,0.254171,1.641449
7,20484.932132,27064.776904,40541.969906,0.505277,0.667574,6.358461,0.000033,0.862957,0.161650,0.261797,1.620471
8,21947.274238,24319.601060,39677.159260,0.553146,0.612937,6.402193,0.000028,0.833084,0.150502,0.271579,1.680462
9,19402.624738,30740.712404,46314.848977,0.418929,0.663733,6.785633,0.000034,0.908019,0.235458,0.155923,1.389921
10,22156.658858,24910.695384,42807.634480,0.517587,0.581922,6.562628,0.000026,0.855631,0.186777,0.186481,1.461626
11,20355.057544,27201.919321,41376.027423,0.491953,0.657432,6.528145,0.000032,0.870622,0.174399,0.258362,1.613743
12,20389.498826,26655.282878,41594.868303,0.490193,0.640831,6.545756,0.000031,0.871614,0.181270,0.225096,1.564603
13,16062.036984,26394.478490,38616.635632,0.415936,0.683500,6.272323,0.000043,0.909394,0.232730,0.172582,1.315829
14,16198.084810,28585.492556,37043.812968,0.437268,0.771667,6.301432,0.000048,0.899331,0.197002,0.336431,1.784317
15,13910.311314,32376.313763,41256.057466,0.337170,0.784765,6.517782,0.000056,0.941444,0.304717,0.235748,1.558505
16,12582.204706,34969.312559,42821.428625,0.293830,0.816631,6.667846,0.000065,0.955858,0.361749,0.199380,1.506569
17,12580.184969,29694.187552,36875.591478,0.341152,0.805253,6.240102,0.000064,0.940008,0.298410,0.267261,1.582402
18,16597.097700,21999.344435,31669.666837,0.524069,0.694650,5.882461,0.000042,0.851676,0.141729,0.329091,1.707113
19,18617.488088,26657.668682,41432.231926,0.449348,0.643404,6.534527,0.000035,0.893357,0.213734,0.168441,1.346837
20,14025.692125,29890.105203,34706.744561,0.404120,0.861219,6.243893,0.000061,0.914706,0.227319,0.450244,2.122486
21,18293.419445,25077.278717,38177.522391,0.479167,0.656860,6.359005,0.000036,0.877724,0.184362,0.239563,1.546866
22,22664.513511,24444.080765,43782.366962,0.517663,0.558309,6.713396,0.000025,0.855585,0.199270,0.144659,1.326261
23,18622.047014,23966.939567,38360.071575,0.485454,0.624789,6.335601,0.000034,0.874262,0.190857,0.176448,1.374204
24,14254.699139,29396.162436,38841.464666,0.366997,0.756824,6.414916,0.000053,0.930222,0.271268,0.240783,1.542015
25,18233.355494,22510.624977,33265.802579,0.548111,0.676690,6.094367,0.000037,0.836406,0.131427,0.359381,1.886744
26,18837.729654,26169.690299,41896.104602,0.449630,0.624633,6.603934,0.000033,0.893215,0.220535,0.132474,1.232369
27,16266.534882,22810.542408,33757.636213,0.481862,0.675715,6.045793,0.000042,0.876247,0.176668,0.285194,1.672575
28,18991.639226,24147.664293,37336.372158,0.508663,0.646760,6.355012,0.000034,0.860966,0.165852,0.274506,1.633161
29,21338.749206,23328.847614,41413.696143,0.515258,0.563312,6.572619,0.000026,0.857035,0.198118,0.151198,1.313572
30,15679.404016,27588.484893,38562.427135,0.406598,0.715424,6.408275,0.000046,0.913607,0.234726,0.203349,1.476348
31,20574.181433,23321.767269,39621.844327,0.519264,0.588609,6.474013,0.000029,0.854614,0.182376,0.192915,1.474340
32,18430.318175,24868.594290,38891.511702,0.473891,0.639435,6.422360,0.000035,0.880584,0.194442,0.200369,1.453393
33,17513.520471,26649.970633,40999.202510,0.427167,0.650012,6.544080,0.000037,0.904173,0.231901,0.140612,1.247070
34,19035.998822,25593.816183,41553.755125,0.458105,0.615921,6.583186,0.000032,0.888898,0.216698,0.135371,1.273257
35,13776.013231,21802.757282,27326.005385,0.504136,0.797876,5.624264,0.000058,0.863624,0.140782,0.460470,1.974082
36,13538.596152,25820.847399,33703.994477,0.401691,0.766106,6.079874,0.000057,0.915775,0.232151,0.296765,1.665140
37,17822.645814,21961.442753,34252.959062,0.520324,0.641155,6.123298,0.000036,0.853969,0.159871,0.272966,1.673623
38,15943.132524,24475.704844,34758.087085,0.458688,0.704173,6.192290,0.000044,0.888597,0.188455,0.289531,1.761710
39,13442.215187,25364.521216,33967.291904,0.395740,0.746734,6.092524,0.000056,0.918363,0.240718,0.205836,1.404782
40,16962.186714,20961.585850,31907.125895,0.531611,0.656956,6.033152,0.000039,0.846988,0.147303,0.302078,1.668209
41,10299.347598,18870.763337,27355.124090,0.376505,0.689844,5.962601,0.000067,0.926414,0.273139,0.132020,1.085173
42,10546.629323,16826.116808,24093.127144,0.437744,0.698378,5.703985,0.000066,0.899100,0.208212,0.255377,1.449539
43,8388.314518,14734.381781,19913.538186,0.421237,0.739918,5.338566,0.000088,0.906951,0.215890,0.288141,1.447251
44,9773.473472,11760.929844,19488.310853,0.501504,0.603486,5.297282,0.000062,0.865155,0.187823,0.174020,1.150066
45,8972.668837,11951.576088,18381.643778,0.488132,0.650191,5.185250,0.000072,0.872770,0.179615,0.242122,1.303110
46,9007.136973,12376.145378,19534.592242,0.461087,0.633550,5.290508,0.000070,0.887355,0.207160,0.181336,1.157210
47,8080.619864,11811.133329,17631.530007,0.458305,0.669887,5.129926,0.000083,0.888795,0.197463,0.209506,1.230989
48,8758.661614,9941.696014,15655.129112,0.559476,0.635044,4.964634,0.000073,0.828847,0.138277,0.328220,1.478651
49,8340.773154,11159.107893,15858.002935,0.525966,0.703689,5.036540,0.000084,0.850505,0.138430,0.335943,1.504444
50,8799.299604,9793.014657,14962.518783,0.588089,0.654503,4.906443,0.000074,0.808796,0.116698,0.348411,1.537771

In [104]:
num_columns = descriptor_df.shape[1]
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
train_3d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , train_3d_rdkit.shape)
train_3d_rdkit.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Train_3d_RDKit_desc_MDCK.csv',index=False)
print('Shape after: ',train_3d_rdkit.shape)
train_3d_rdkit

Shape before: (51, 14)
Shape after:  (51, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,1114,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-4.940000,24313.755201,30312.376753,46681.937558,0.520839,0.649338,6.667315,0.000027,0.853655,0.156729,0.289553,1.754389
1,1113,CC(C)C[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@@H](Cc2...,-5.820000,20729.202872,33683.486578,45247.431206,0.458130,0.744429,6.612865,0.000036,0.888885,0.181770,0.322778,1.865993
2,1117,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.650000,20665.252633,38087.030609,54414.093500,0.379778,0.699948,7.046731,0.000034,0.925078,0.266905,0.145286,1.320561
3,1119,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.250000,23316.296843,27342.847641,44212.952948,0.527363,0.618435,6.521161,0.000027,0.849640,0.163872,0.236521,1.643716
4,2428,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-5.510000,17548.732916,32062.570730,44521.068339,0.394167,0.720166,6.566914,0.000041,0.919039,0.246786,0.209742,1.512311
5,2446,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.400000,19844.954604,31315.006377,42161.230503,0.470692,0.742744,6.538558,0.000037,0.882298,0.171600,0.343405,1.939268
6,2445,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-4.820000,20353.342160,32484.579946,45010.234764,0.452194,0.721715,6.701328,0.000035,0.891920,0.190515,0.254171,1.641449
7,2427,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-4.610000,20484.932132,27064.776904,40541.969906,0.505277,0.667574,6.358461,0.000033,0.862957,0.161650,0.261797,1.620471
8,8145,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.744727,21947.274238,24319.601060,39677.159260,0.553146,0.612937,6.402193,0.000028,0.833084,0.150502,0.271579,1.680462
9,1107,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-4.610000,19402.624738,30740.712404,46314.848977,0.418929,0.663733,6.785633,0.000034,0.908019,0.235458,0.155923,1.389921
10,1116,CC(C)C[C@@H]1NC(=O)[C@H](C(C)C)N(C)C(=O)[C@H]2...,-5.220000,22156.658858,24910.695384,42807.634480,0.517587,0.581922,6.562628,0.000026,0.855631,0.186777,0.186481,1.461626
11,1110,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.730000,20355.057544,27201.919321,41376.027423,0.491953,0.657432,6.528145,0.000032,0.870622,0.174399,0.258362,1.613743
12,8121,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.289037,20389.498826,26655.282878,41594.868303,0.490193,0.640831,6.545756,0.000031,0.871614,0.181270,0.225096,1.564603
13,5836,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-4.580000,16062.036984,26394.478490,38616.635632,0.415936,0.683500,6.272323,0.000043,0.909394,0.232730,0.172582,1.315829
14,6187,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-5.120000,16198.084810,28585.492556,37043.812968,0.437268,0.771667,6.301432,0.000048,0.899331,0.197002,0.336431,1.784317
15,6584,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-5.320000,13910.311314,32376.313763,41256.057466,0.337170,0.784765,6.517782,0.000056,0.941444,0.304717,0.235748,1.558505
16,6571,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.970000,12582.204706,34969.312559,42821.428625,0.293830,0.816631,6.667846,0.000065,0.955858,0.361749,0.199380,1.506569
17,5803,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N...,-6.300000,12580.184969,29694.187552,36875.591478,0.341152,0.805253,6.240102,0.000064,0.940008,0.298410,0.267261,1.582402
18,2422,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N(C)[C@@H](C)C(=...,-6.400000,16597.097700,21999.344435,31669.666837,0.524069,0.694650,5.882461,0.000042,0.851676,0.141729,0.329091,1.707113
19,2440,CCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=O...,-6.520000,18617.488088,26657.668682,41432.231926,0.449348,0.643404,6.534527,0.000035,0.893357,0.213734,0.168441,1.346837
20,8140,CCC[C@H]1C(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=...,-5.185752,14025.692125,29890.105203,34706.744561,0.404120,0.861219,6.243893,0.000061,0.914706,0.227319,0.450244,2.122486
21,8131,CCC[C@@H]1NC(=O)CN(CCC)C(=O)[C@H](CC(C)C)NC(=O...,-5.501689,18293.419445,25077.278717,38177.522391,0.479167,0.656860,6.359005,0.000036,0.877724,0.184362,0.239563,1.546866
22,8346,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-7.562400,22664.513511,24444.080765,43782.366962,0.517663,0.558309,6.713396,0.000025,0.855585,0.199270,0.144659,1.326261
23,8184,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-7.698970,18622.047014,23966.939567,38360.071575,0.485454,0.624789,6.335601,0.000034,0.874262,0.190857,0.176448,1.374204
24,6505,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-6.050000,14254.699139,29396.162436,38841.464666,0.366997,0.756824,6.414916,0.000053,0.930222,0.271268,0.240783,1.542015
25,8342,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.897175,18233.355494,22510.624977,33265.802579,0.548111,0.676690,6.094367,0.000037,0.836406,0.131427,0.359381,1.886744
26,8160,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.193142,18837.729654,26169.690299,41896.104602,0.449630,0.624633,6.603934,0.000033,0.893215,0.220535,0.132474,1.232369
27,8341,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.321123,16266.534882,22810.542408,33757.636213,0.481862,0.675715,6.045793,0.000042,0.876247,0.176668,0.285194,1.672575
28,8344,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-5.917901,18991.639226,24147.664293,37336.372158,0.508663,0.646760,6.355012,0.000034,0.860966,0.165852,0.274506,1.633161
29,8343,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(CC(C)C...,-6.405218,21338.749206,23328.847614,41413.696143,0.515258,0.563312,6.572619,0.000026,0.857035,0.198118,0.151198,1.313572
30,8156,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-6.065502,15679.404016,27588.484893,38562.427135,0.406598,0.715424,6.408275,0.000046,0.913607,0.234726,0.203349,1.476348
31,8150,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.903090,20574.181433,23321.767269,39621.844327,0.519264,0.588609,6.474013,0.000029,0.854614,0.182376,0.192915,1.474340
32,8152,CCOC(=O)[C@@H]1CSCC(=O)N[C@H](CC)C(=O)N(C)[C@@...,-5.044793,18430.318175,24868.594290,38891.511702,0.473891,0.639435,6.422360,0.000035,0.880584,0.194442,0.200369,1.453393
33,8116,CCCN1CC(=O)N[C@@H](CC)C(=O)N(C)[C@@H](C)C(=O)N...,-5.402305,17513.520471,26649.970633,40999.202510,0.427167,0.650012,6.544080,0.000037,0.904173,0.231901,0.140612,1.247070
34,8128,CCCN1CC(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C(=...,-5.585027,19035.998822,25593.816183,41553.755125,0.458105,0.615921,6.583186,0.000032,0.888898,0.216698,0.135371,1.273257
35,8138,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.129011,13776.013231,21802.757282,27326.005385,0.504136,0.797876,5.624264,0.000058,0.863624,0.140782,0.460470,1.974082
36,6666,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N...,-6.400000,13538.596152,25820.847399,33703.994477,0.401691,0.766106,6.079874,0.000057,0.915775,0.232151,0.296765,1.665140
37,1115,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.190000,17822.645814,21961.442753,34252.959062,0.520324,0.641155,6.123298,0.000036,0.853969,0.159871,0.272966,1.673623
38,8126,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.752027,15943.132524,24475.704844,34758.087085,0.458688,0.704173,6.192290,0.000044,0.888597,0.188455,0.289531,1.761710
39,8114,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC(C)C)C(=O)N(C...,-5.344862,13442.215187,25364.521216,33967.291904,0.395740,0.746734,6.092524,0.000056,0.918363,0.240718,0.205836,1.404782
40,1111,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C...,-6.220000,16962.186714,20961.585850,31907.125895,0.531611,0.656956,6.033152,0.000039,0.846988,0.147303,0.302078,1.668209
41,1109,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N(C)C(...,-6.120000,10299.347598,18870.763337,27355.124090,0.376505,0.689844,5.962601,0.000067,0.926414,0.273139,0.132020,1.085173
42,1112,C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](C)NC(=O)[...,-6.170000,10546.629323,16826.116808,24093.127144,0.437744,0.698378,5.703985,0.000066,0.899100,0.208212,0.255377,1.449539
43,1018,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-4.960000,8388.314518,14734.381781,19913.538186,0.421237,0.739918,5.338566,0.000088,0.906951,0.215890,0.288141,1.447251
44,1845,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.960000,9773.473472,11760.929844,19488.310853,0.501504,0.603486,5.297282,0.000062,0.865155,0.187823,0.174020,1.150066
45,1847,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.740000,8972.668837,11951.576088,18381.643778,0.488132,0.650191,5.185250,0.000072,0.872770,0.179615,0.242122,1.303110
46,1841,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.410000,9007.136973,12376.145378,19534.592242,0.461087,0.633550,5.290508,0.000070,0.887355,0.207160,0.181336,1.157210
47,1017,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.700000,8080.619864,11811.133329,17631.530007,0.458305,0.669887,5.129926,0.000083,0.888795,0.197463,0.209506,1.230989
48,1840,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.480000,8758.661614,9941.696014,15655.129112,0.559476,0.635044,4.964634,0.000073,0.828847,0.138277,0.328220,1.478651
49,1844,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-5.100000,8340.773154,11159.107893,15858.002935,0.525966,0.703689,5.036540,0.000084,0.850505,0.138430,0.335943,1.504444
50,1846,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.820000,8799.299604,9793.014657,14962.518783,0.588089,0.654503,4.906443,0.000074,0.808796,0.116698,0.348411,1.537771

In [105]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.csv")
descriptor_data = []
for smiles in tqdm(df_test['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors = generate_3d_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

descriptor_data

3d_descriptors: 100%|██████████| 13/13 [00:10<00:00,  1.26smiles/s]

[{'PMI1': 19802.437352189078,
  'PMI2': 46153.6445586442,
  'PMI3': 61555.468385369226,
  'NPR1': 0.3217007013611777,
  'NPR2': 0.749789511302203,
  'RadiusOfGyration': 7.290131834210984,
  'InertialShapeFactor': 3.786349619327627e-05,
  'Eccentricity': 0.9468414116121698,
  'Asphericity': 0.3290344722947237,
  'SpherocityIndex': 0.12708388057852535,
  'PBF': 1.3082242219328482},
 {'PMI1': 19361.572110415542,
  'PMI2': 31647.602402672954,
  'PMI3': 40164.602400348915,
  'NPR1': 0.4820556149772155,
  'NPR2': 0.7879476083746325,
  'RadiusOfGyration': 6.39279294698956,
  'InertialShapeFactor': 4.0696468441772695e-05,
  'Eccentricity': 0.8761406188899923,
  'Asphericity': 0.1578922001575393,
  'SpherocityIndex': 0.4357945259036131,
  'PBF': 2.1393549441352264},
 {'PMI1': 15403.864353984618,
  'PMI2': 37701.556329149644,
  'PMI3': 45366.50781381539,
  'NPR1': 0.3395426515349657,
  'NPR2': 0.8310438282769574,
  'RadiusOfGyration': 6.741392511217924,
  'InertialShapeFactor': 5.3950347080405564e-05,
  'Eccentricity': 0.9405906589949768,
  'Asphericity': 0.2998330253023506,
  'SpherocityIndex': 0.3023997038106236,
  'PBF': 1.8077100325594588},
 {'PMI1': 19224.894747957595,
  'PMI2': 23386.993073793423,
  'PMI3': 35959.41390152672,
  'NPR1': 0.5346275887756159,
  'NPR2': 0.6503719203499166,
  'RadiusOfGyration': 6.162795526972918,
  'InertialShapeFactor': 3.3829673913768015e-05,
  'Eccentricity': 0.8450877713705074,
  'Asphericity': 0.1475456995645937,
  'SpherocityIndex': 0.2944172392290782,
  'PBF': 1.7497190074086306},
 {'PMI1': 21673.942645108287,
  'PMI2': 26981.97675927574,
  'PMI3': 44843.0560966353,
  'NPR1': 0.4833288480250244,
  'NPR2': 0.6016979909025486,
  'RadiusOfGyration': 6.762159987487727,
  'InertialShapeFactor': 2.7761353841099562e-05,
  'Eccentricity': 0.8754388754600761,
  'Asphericity': 0.2022409727636252,
  'SpherocityIndex': 0.15812062709487815,
  'PBF': 1.374396782824598},
 {'PMI1': 16488.70684953936,
  'PMI2': 25907.929011879423,
  'PMI3': 36349.7618912829,
  'NPR1': 0.4536125133048959,
  'NPR2': 0.7127399923379539,
  'RadiusOfGyration': 6.248809472393329,
  'InertialShapeFactor': 4.322594845319028e-05,
  'Eccentricity': 0.8911990169278778,
  'Asphericity': 0.19100647951127436,
  'SpherocityIndex': 0.27356594612334345,
  'PBF': 1.6566343237991528},
 {'PMI1': 12689.812239036413,
  'PMI2': 33609.4417417791,
  'PMI3': 41251.1603691574,
  'NPR1': 0.3076231583663356,
  'NPR2': 0.8147514261661388,
  'RadiusOfGyration': 6.608658189879106,
  'InertialShapeFactor': 6.420516007792453e-05,
  'Eccentricity': 0.9515082723953168,
  'Asphericity': 0.34227384861259424,
  'SpherocityIndex': 0.20523774974760206,
  'PBF': 1.5211343687898036},
 {'PMI1': 19158.68452415011,
  'PMI2': 25259.129335609174,
  'PMI3': 41368.456208857024,
  'NPR1': 0.46312302367348723,
  'NPR2': 0.6105891215297797,
  'RadiusOfGyration': 6.561346075372979,
  'InertialShapeFactor': 3.1870096339866834e-05,
  'Eccentricity': 0.8862940059277883,
  'Asphericity': 0.2146947402201367,
  'SpherocityIndex': 0.14338332813942992,
  'PBF': 1.2712388051772332},
 {'PMI1': 20296.552957892072,
  'PMI2': 28218.35131186846,
  'PMI3': 46436.625132967114,
  'NPR1': 0.43708070730322696,
  'NPR2': 0.6076744645216516,
  'RadiusOfGyration': 6.902954877332103,
  'InertialShapeFactor': 2.9939786612157937e-05,
  'Eccentricity': 0.8994222897523225,
  'Asphericity': 0.2391278883979994,
  'SpherocityIndex': 0.0926568279093969,
  'PBF': 1.0882089583116392},
 {'PMI1': 14710.113691225455,
  'PMI2': 30244.58966573777,
  'PMI3': 41331.34511966092,
  'NPR1': 0.35590696718525133,
  'NPR2': 0.7317591425629821,
  'RadiusOfGyration': 6.607160393971294,
  'InertialShapeFactor': 4.974530842677814e-05,
  'Eccentricity': 0.9345213912527612,
  'Asphericity': 0.2882163576236158,
  'SpherocityIndex': 0.16312416932932086,
  'PBF': 1.343232762176757},
 {'PMI1': 15843.247464211992,
  'PMI2': 22950.337946260894,
  'PMI3': 35241.53745222262,
  'NPR1': 0.4495617560865747,
  'NPR2': 0.6512297591265689,
  'RadiusOfGyration': 6.199098440180677,
  'InertialShapeFactor': 4.1104562722864696e-05,
  'Eccentricity': 0.8932492527085344,
  'Asphericity': 0.2108582194805763,
  'SpherocityIndex': 0.18859823865091757,
  'PBF': 1.3779699450770826},
 {'PMI1': 9113.464204554139,
  'PMI2': 12034.056247265262,
  'PMI3': 18406.708211483612,
  'NPR1': 0.49511645970833684,
  'NPR2': 0.6537864407367219,
  'RadiusOfGyration': 5.201604523240938,
  'InertialShapeFactor': 7.173852072738868e-05,
  'Eccentricity': 0.8688266175284244,
  'Asphericity': 0.17322049227776687,
  'SpherocityIndex': 0.2545147840822967,
  'PBF': 1.3639886624536222},
 {'PMI1': 9179.91042151409,
  'PMI2': 9706.070740216404,
  'PMI3': 14871.265308416969,
  'NPR1': 0.6172918195681953,
  'NPR2': 0.6526728250031877,
  'RadiusOfGyration': 4.9212189018014705,
  'InertialShapeFactor': 7.10979513997849e-05,
  'Eccentricity': 0.7867342686664834,
  'Asphericity': 0.10415955786309665,
  'SpherocityIndex': 0.35791642596145956,
  'PBF': 1.560270185921308}]

In [106]:
descriptor_df = pd.DataFrame(descriptor_data)

In [107]:
num_columns = descriptor_df.shape[1]
print('num_columns',num_columns)
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
print('descriptor_df.columns',descriptor_df.columns)
test_3d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , test_3d_rdkit.shape)
test_3d_rdkit.to_csv('/home/users/akshay/PCPpred/MDCK/features/Descriptors/Test_3d_RDKit_desc_MDCK.csv',index=False)
print('Shape after: ',test_3d_rdkit.shape)
test_3d_rdkit

num_columns 11
descriptor_df.columns Index(['3d_rdkit_1', '3d_rdkit_2', '3d_rdkit_3', '3d_rdkit_4', '3d_rdkit_5',
       '3d_rdkit_6', '3d_rdkit_7', '3d_rdkit_8', '3d_rdkit_9', '3d_rdkit_10',
       '3d_rdkit_11'],
      dtype='object')
Shape before: (13, 14)
Shape after:  (13, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,1120,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C...,-6.300000,19802.437352,46153.644559,61555.468385,0.321701,0.749790,7.290132,0.000038,0.946841,0.329034,0.127084,1.308224
1,1118,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](Cc2...,-5.350000,19361.572110,31647.602403,40164.602400,0.482056,0.787948,6.392793,0.000041,0.876141,0.157892,0.435795,2.139355
2,1121,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-6.200000,15403.864354,37701.556329,45366.507814,0.339543,0.831044,6.741393,0.000054,0.940591,0.299833,0.302400,1.807710
3,8133,CCC[C@@H]1NC(=O)CN(CC)C(=O)[C@H](CC(C)C)NC(=O)...,-5.355561,19224.894748,23386.993074,35959.413902,0.534628,0.650372,6.162796,0.000034,0.845088,0.147546,0.294417,1.749719
4,8143,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.406714,21673.942645,26981.976759,44843.056097,0.483329,0.601698,6.762160,0.000028,0.875439,0.202241,0.158121,1.374397
5,8119,CCC[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC(C)C)...,-5.073658,16488.706850,25907.929012,36349.761891,0.453613,0.712740,6.248809,0.000043,0.891199,0.191006,0.273566,1.656634
6,6496,CC(=O)N1CCC[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N[...,-4.860000,12689.812239,33609.441742,41251.160369,0.307623,0.814751,6.608658,0.000064,0.951508,0.342274,0.205238,1.521134
7,8168,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(C)[C@...,-6.031517,19158.684524,25259.129336,41368.456209,0.463123,0.610589,6.561346,0.000032,0.886294,0.214695,0.143383,1.271239
8,8345,CCOC(=O)[C@@H]1CSCC(=O)N[C@@H](CC)C(=O)N(CC(C)...,-7.534591,20296.552958,28218.351312,46436.625133,0.437081,0.607674,6.902955,0.000030,0.899422,0.239128,0.092657,1.088209
9,6423,CC(=O)N1CCC[C@@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)...,-6.300000,14710.113691,30244.589666,41331.345120,0.355907,0.731759,6.607160,0.000050,0.934521,0.288216,0.163124,1.343233
10,1108,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@@H](C)N...,-5.180000,15843.247464,22950.337946,35241.537452,0.449562,0.651230,6.199098,0.000041,0.893249,0.210858,0.188598,1.377970
11,1843,CC[C@H](C)[C@@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@...,-4.400000,9113.464205,12034.056247,18406.708211,0.495116,0.653786,5.201605,0.000072,0.868827,0.173220,0.254515,1.363989
12,1842,CC[C@H](C)[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H...,-4.400000,9179.910422,9706.070740,14871.265308,0.617292,0.652673,4.921219,0.000071,0.786734,0.104160,0.357916,1.560270

In [108]:
import os

#Train MOL structure generator
input_file = '/home/users/akshay/PCPpred/MDCK/data/Train_MDCK.smi'
output_dir = '/home/users/akshay/PCPpred/MDCK/data/Train_mol_MDCK'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 51/51 [00:39<00:00,  1.30it/s]

3D conformations generated and saved.

In [109]:
directory_path = '/home/users/akshay/PCPpred/MDCK/data/Train_mol_MDCK'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 51

In [110]:
#Test MOL structure generator
input_file = '/home/users/akshay/PCPpred/MDCK/data/Test_MDCK.smi'
output_dir = '/home/users/akshay/PCPpred/MDCK/data/Test_mol_MDCK'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 13/13 [00:12<00:00,  1.08it/s]

3D conformations generated and saved.

In [111]:
directory_path = '/home/users/akshay/PCPpred/MDCK/data/Test_mol_MDCK'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 13