In [1]:
#Starts from here
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression  # LogisticRegression is not used for regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from scipy.stats import pearsonr, spearmanr
from sklearn.model_selection import train_test_split
from tqdm import tqdm

def remove_low_variance_columns(df, threshold=0.005):
    # df = df.drop(['ID','SMILES','Permeability'],axis=1)
    variances = df.var()
    
    # Identify columns with variance below the threshold
    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

def features(df, target_column='Permeability', threshold=0.9):
    correlation_matrix = df.corr()
    
    features_to_drop = set()
    
    for feature in correlation_matrix.columns:
        if feature == target_column:
            continue 
        target_corr = correlation_matrix[target_column][feature]
        
        for other_feature in correlation_matrix.columns:
            if other_feature == feature or other_feature == target_column:
                continue
            
            if abs(correlation_matrix[feature][other_feature]) > threshold:
                other_target_corr = correlation_matrix[target_column][other_feature]

                if abs(other_target_corr) < abs(target_corr):
                    features_to_drop.add(other_feature)
                else:
                    features_to_drop.add(feature)
    selected_features = [col for col in df.columns if col not in features_to_drop and col != target_column]
    
    return selected_features

In [2]:
#Combined features and then selection

df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]

print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)

/tmp/ipykernel_369462/3312508411.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
/tmp/ipykernel_369462/3312508411.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)

In [3]:
merge_keys = ['ID', 'SMILES', 'Permeability']

merged_train = df_desc_train.merge(df_fp_train, on=merge_keys)
merged_train = merged_train.merge(df_emb_train, on=merge_keys)
merged_train = merged_train.merge(df_atomic_train, on=merge_keys)

merged_test = df_desc_test.merge(df_fp_test, on=merge_keys)
merged_test = merged_test.merge(df_emb_test, on=merge_keys)
merged_test = merged_test.merge(df_atomic_test, on=merge_keys)

In [4]:
X_train = merged_train.drop(columns=['ID', 'SMILES']).select_dtypes(include=['number'])
selected_final_features = features(X_train, target_column='Permeability')

train = pd.concat([merged_train[['ID', 'SMILES', 'Permeability']], X_train[selected_final_features]], axis=1)
test = merged_test[train.columns] 

print('selected_final_features', selected_final_features )
print("Final Train shape:", train.shape)
print("Final Test shape:", test.shape)

selected_final_features ['MinEStateIndex', 'qed', 'SPS', 'FpDensityMorgan1', 'BCUT2D_MWHI', 'AvgIpc', 'BalabanJ_x', 'Ipc', 'EState_VSA11', 'VSA_EState10', 'fr_Ar_N', 'fr_alkyl_halide', 'fr_allylic_oxid', 'fr_aryl_methyl', 'fr_methoxy', 'fr_para_hydroxylation', 'fr_piperdine', 'fr_priamide', 'AdjacencyMatrix.6', 'AdjacencyMatrix.9', 'AdjacencyMatrix.11', 'AATS', 'AATS.3', 'AATS.4', 'AATS.10', 'AATS.18', 'AATS.23', 'AATS.24', 'AATS.26', 'AATS.27', 'AATS.28', 'AATS.32', 'AATS.33', 'AATS.34', 'AATS.40', 'AATS.48', 'AATS.96', 'AATS.97', 'ATSC.2', 'ATSC.5', 'ATSC.7', 'ATSC.8', 'ATSC.12', 'ATSC.13', 'ATSC.14', 'ATSC.15', 'ATSC.16', 'ATSC.17', 'ATSC.20', 'ATSC.21', 'ATSC.22', 'ATSC.23', 'ATSC.24', 'ATSC.25', 'ATSC.26', 'ATSC.29', 'ATSC.30', 'ATSC.32', 'ATSC.37', 'ATSC.44', 'ATSC.50', 'ATSC.73', 'ATSC.76', 'ATSC.80', 'ATSC.84', 'ATSC.92', 'ATSC.105', 'ATSC.106', 'AATSC.9', 'AATSC.11', 'AATSC.15', 'AATSC.16', 'AATSC.36', 'AATSC.43', 'AATSC.57', 'AATSC.60', 'GATS.1', 'GATS.4', 'GATS.5', 'GATS.12', 'GATS.13', 'GATS.18', 'GATS.27', 'GATS.59', 'GATS.70', 'GATS.71', 'GATS.77', 'BCUT.3', 'BCUT.4', 'Chi.4', 'AtomTypeEState.10', 'AtomTypeEState.31', 'AtomTypeEState.96', 'AtomTypeEState.106', 'AtomTypeEState.127', 'AtomTypeEState.129', 'AtomTypeEState.131', 'AtomTypeEState.148', 'AtomTypeEState.170', 'AtomTypeEState.173', 'AtomTypeEState.271', 'EtaVEMCount.6', 'EtaFunctionalityIndex.1', 'ModifiedIC', 'LogS', 'MolecularDistanceEdge.7', 'RingCount.52', 'RingCount.64', 'RingCount.72', 'ALogP', 'AATS3m', 'AATS5v', 'AATS3i', 'AATS4i', 'AATS5i', 'AATS8i', 'AATS2s', 'AATS3s', 'AATS4s', 'AATS7s', 'ATSC6c', 'ATSC3m', 'ATSC6m', 'ATSC1e', 'ATSC5e', 'ATSC3p', 'ATSC4p', 'ATSC5p', 'ATSC6p', 'ATSC2i', 'ATSC3i', 'ATSC8i', 'ATSC1s', 'ATSC4s', 'ATSC6s', 'ATSC7s', 'AATSC1m', 'AATSC5v', 'AATSC8v', 'AATSC1i', 'GATS4c', 'GATS7c', 'GATS8c', 'GATS6s', 'VE3_DzZ', 'VE1_Dzm', 'VE1_Dzp', 'VE3_Dzp', 'VR2_Dzi', 'VE1_Dzs', 'VE3_Dzs', 'VR1_Dzs', 'BCUTp-1l', 'BCUTp-1h', 'SpMax1_Bhs', 'SpMax2_Bhs', 'SpMax4_Bhs', 'SpMax5_Bhs', 'SpMax7_Bhs', 'SpMin7_Bhs', 'SCH-6', 'CrippenLogP', 'EE_Dt', 'VE1_Dt', 'VE3_Dt', 'VR2_Dt', 'VR3_Dt', 'nHBint4', 'nHBint7', 'nHBint10', 'SHBint6', 'SssCH2', 'minHBint2', 'minHBint3', 'minHBint4', 'minHBint5', 'minHBint7', 'minHBint8', 'minHBint9', 'minHBint10', 'minHsOH', 'minHCsatu', 'minsCH3', 'minssCH2', 'mindsCH', 'minssssC', 'minsNH2', 'minssNH', 'minsssN', 'maxHBint2', 'maxHBint3', 'maxHBint5', 'maxHBint6', 'maxHBint7', 'maxHBint8', 'maxHBint9', 'maxHBint10', 'maxsCH3', 'maxssCH2', 'maxssNH', 'maxsssN', 'hmin', 'LipoaffinityIndex', 'IC1', 'IC5', 'MIC1', 'nAtomLAC', 'MDEC-11', 'MDEC-12', 'MDEC-13', 'MDEC-22', 'MDEC-23', 'MDEC-33', 'MDEN-12', 'MDEN-22', 'MLFER_A', 'nFRing', 'nTRing', 'nHeteroRing', 'RotBtFrac', 'LipinskiFailures', 'VR2_D', 'XLogP', '3d_rdkit_5', '3d_rdkit_9', '3d_rdkit_10', '3d_rdkit_11', 'TDB9u', 'TDB1m', 'TDB3m', 'TDB4m', 'TDB5m', 'TDB7m', 'TDB10m', 'TDB3v', 'TDB5e', 'TDB8p', 'TDB9p', 'TDB2s', 'TDB4s', 'TDB5s', 'TDB6s', 'TDB7s', 'TDB8s', 'TDB9s', 'TDB10s', 'RNCS', 'LOBMAX', 'LOBMIN', 'MOMI-XY', 'geomShape', 'RDF20i', 'Ku', 'Dm', 'Dv', 'L3p', 'Morgan_fp_2', 'Morgan_fp_5', 'Morgan_fp_13', 'Morgan_fp_19', 'Morgan_fp_42', 'Morgan_fp_84', 'Morgan_fp_94', 'Morgan_fp_109', 'Morgan_fp_113', 'Morgan_fp_115', 'Morgan_fp_126', 'Morgan_fp_130', 'Morgan_fp_160', 'Morgan_fp_167', 'Morgan_fp_174', 'Morgan_fp_216', 'Morgan_fp_219', 'Morgan_fp_231', 'Morgan_fp_250', 'Morgan_fp_253', 'Morgan_fp_298', 'Morgan_fp_328', 'Morgan_fp_334', 'Morgan_fp_355', 'Morgan_fp_370', 'Morgan_fp_400', 'Morgan_fp_444', 'Morgan_fp_460', 'Morgan_fp_476', 'Morgan_fp_523', 'Morgan_fp_534', 'Morgan_fp_545', 'Morgan_fp_561', 'Morgan_fp_562', 'Morgan_fp_619', 'Morgan_fp_632', 'Morgan_fp_668', 'Morgan_fp_675', 'Morgan_fp_684', 'Morgan_fp_687', 'Morgan_fp_689', 'Morgan_fp_695', 'Morgan_fp_725', 'Morgan_fp_749', 'Morgan_fp_752', 'Morgan_fp_784', 'Morgan_fp_809', 'Morgan_fp_820', 'Morgan_fp_832', 'Morgan_fp_878', 'Morgan_fp_893', 'Morgan_fp_914', 'Morgan_fp_963', 'Morgan_fp_978', 'Morgan_fp_979', 'Morgan_fp_999', 'Morgan_fp_1039', 'Morgan_fp_1052', 'Morgan_fp_1065', 'Morgan_fp_1089', 'Morgan_fp_1118', 'Morgan_fp_1139', 'Morgan_fp_1145', 'Morgan_fp_1160', 'Morgan_fp_1184', 'Morgan_fp_1222', 'Morgan_fp_1240', 'Morgan_fp_1248', 'Morgan_fp_1309', 'Morgan_fp_1315', 'Morgan_fp_1340', 'Morgan_fp_1345', 'Morgan_fp_1352', 'Morgan_fp_1373', 'Morgan_fp_1421', 'Morgan_fp_1454', 'Morgan_fp_1456', 'Morgan_fp_1480', 'Morgan_fp_1506', 'Morgan_fp_1518', 'Morgan_fp_1535', 'Morgan_fp_1539', 'Morgan_fp_1543', 'Morgan_fp_1580', 'Morgan_fp_1599', 'Morgan_fp_1613', 'Morgan_fp_1620', 'Morgan_fp_1662', 'Morgan_fp_1676', 'Morgan_fp_1689', 'Morgan_fp_1709', 'Morgan_fp_1722', 'Morgan_fp_1734', 'Morgan_fp_1738', 'Morgan_fp_1739', 'Morgan_fp_1783', 'Morgan_fp_1840', 'Morgan_fp_1866', 'Morgan_fp_1876', 'Morgan_fp_1928', 'Morgan_fp_1946', 'Morgan_fp_1978', 'count_fp_5', 'count_fp_19', 'count_fp_61', 'count_fp_80', 'count_fp_113', 'count_fp_115', 'count_fp_149', 'count_fp_160', 'count_fp_173', 'count_fp_231', 'count_fp_253', 'count_fp_269', 'count_fp_276', 'count_fp_294', 'count_fp_296', 'count_fp_310', 'count_fp_314', 'count_fp_316', 'count_fp_322', 'count_fp_340', 'count_fp_358', 'count_fp_476', 'count_fp_486', 'count_fp_533', 'count_fp_552', 'count_fp_573', 'count_fp_628', 'count_fp_668', 'count_fp_684', 'count_fp_701', 'count_fp_715', 'count_fp_736', 'count_fp_759', 'count_fp_779', 'count_fp_798', 'count_fp_807', 'count_fp_811', 'count_fp_823', 'count_fp_849', 'count_fp_875', 'count_fp_878', 'count_fp_893', 'count_fp_896', 'count_fp_926', 'count_fp_935', 'count_fp_951', 'count_fp_999', 'count_fp_1028', 'count_fp_1052', 'count_fp_1104', 'count_fp_1118', 'count_fp_1152', 'count_fp_1190', 'count_fp_1243', 'count_fp_1260', 'count_fp_1274', 'count_fp_1309', 'count_fp_1312', 'count_fp_1315', 'count_fp_1325', 'count_fp_1345', 'count_fp_1349', 'count_fp_1380', 'count_fp_1410', 'count_fp_1419', 'count_fp_1433', 'count_fp_1441', 'count_fp_1456', 'count_fp_1480', 'count_fp_1482', 'count_fp_1495', 'count_fp_1519', 'count_fp_1530', 'count_fp_1531', 'count_fp_1573', 'count_fp_1575', 'count_fp_1597', 'count_fp_1657', 'count_fp_1662', 'count_fp_1663', 'count_fp_1665', 'count_fp_1683', 'count_fp_1689', 'count_fp_1693', 'count_fp_1765', 'count_fp_1783', 'count_fp_1796', 'count_fp_1802', 'count_fp_1823', 'count_fp_1879', 'count_fp_1893', 'count_fp_1898', 'count_fp_1911', 'count_fp_1946', 'count_fp_1979', 'count_fp_1994', 'count_fp_2008', 'AD2D491', 'AD2D501', 'AD2D637', 'AD2D638', 'AD2D657', 'AD2D716', 'AD2D735', 'APC2D2_C_X', 'APC2D2_N_N', 'APC2D3_N_F', 'APC2D4_N_O', 'APC2D4_O_O', 'APC2D5_N_X', 'APC2D6_C_N', 'APC2D6_N_F', 'APC2D6_O_O', 'APC2D7_C_F', 'APC2D7_N_N', 'APC2D7_N_X', 'APC2D7_O_F', 'APC2D8_C_C', 'APC2D8_N_S', 'APC2D8_O_X', 'APC2D9_C_S', 'APC2D9_N_Cl', 'APC2D9_N_X', 'APC2D10_N_N', 'APC2D10_N_O', 'APC2D10_N_S', 'APC2D10_O_O', 'APC2D10_O_X', 'ExtFP1', 'ExtFP3', 'ExtFP4', 'ExtFP5', 'ExtFP6', 'ExtFP11', 'ExtFP12', 'ExtFP13', 'ExtFP21', 'ExtFP22', 'ExtFP26', 'ExtFP29', 'ExtFP30', 'ExtFP35', 'ExtFP36', 'ExtFP38', 'ExtFP42', 'ExtFP43', 'ExtFP46', 'ExtFP49', 'ExtFP55', 'ExtFP58', 'ExtFP59', 'ExtFP60', 'ExtFP61', 'ExtFP62', 'ExtFP64', 'ExtFP65', 'ExtFP70', 'ExtFP78', 'ExtFP82', 'ExtFP83', 'ExtFP86', 'ExtFP87', 'ExtFP89', 'ExtFP90', 'ExtFP95', 'ExtFP96', 'ExtFP99', 'ExtFP101', 'ExtFP106', 'ExtFP107', 'ExtFP108', 'ExtFP112', 'ExtFP113', 'ExtFP116', 'ExtFP120', 'ExtFP121', 'ExtFP122', 'ExtFP125', 'ExtFP128', 'ExtFP131', 'ExtFP138', 'ExtFP148', 'ExtFP152', 'ExtFP155', 'ExtFP158', 'ExtFP160', 'ExtFP161', 'ExtFP168', 'ExtFP169', 'ExtFP171', 'ExtFP173', 'ExtFP177', 'ExtFP179', 'ExtFP180', 'ExtFP181', 'ExtFP187', 'ExtFP191', 'ExtFP195', 'ExtFP196', 'ExtFP199', 'ExtFP200', 'ExtFP205', 'ExtFP206', 'ExtFP209', 'ExtFP214', 'ExtFP217', 'ExtFP221', 'ExtFP222', 'ExtFP223', 'ExtFP230', 'ExtFP232', 'ExtFP233', 'ExtFP234', 'ExtFP235', 'ExtFP236', 'ExtFP237', 'ExtFP239', 'ExtFP258', 'ExtFP259', 'ExtFP263', 'ExtFP265', 'ExtFP267', 'ExtFP269', 'ExtFP273', 'ExtFP275', 'ExtFP277', 'ExtFP278', 'ExtFP279', 'ExtFP281', 'ExtFP283', 'ExtFP284', 'ExtFP285', 'ExtFP288', 'ExtFP289', 'ExtFP291', 'ExtFP292', 'ExtFP294', 'ExtFP301', 'ExtFP302', 'ExtFP304', 'ExtFP305', 'ExtFP308', 'ExtFP311', 'ExtFP312', 'ExtFP313', 'ExtFP314', 'ExtFP315', 'ExtFP316', 'ExtFP317', 'ExtFP319', 'ExtFP321', 'ExtFP324', 'ExtFP325', 'ExtFP327', 'ExtFP330', 'ExtFP331', 'ExtFP332', 'ExtFP333', 'ExtFP334', 'ExtFP335', 'ExtFP336', 'ExtFP340', 'ExtFP341', 'ExtFP348', 'ExtFP352', 'ExtFP354', 'ExtFP359', 'ExtFP362', 'ExtFP363', 'ExtFP365', 'ExtFP367', 'ExtFP370', 'ExtFP375', 'ExtFP379', 'ExtFP380', 'ExtFP384', 'ExtFP385', 'ExtFP387', 'ExtFP388', 'ExtFP394', 'ExtFP399', 'ExtFP403', 'ExtFP405', 'ExtFP407', 'ExtFP408', 'ExtFP409', 'ExtFP412', 'ExtFP416', 'ExtFP418', 'ExtFP421', 'ExtFP422', 'ExtFP429', 'ExtFP430', 'ExtFP438', 'ExtFP441', 'ExtFP442', 'ExtFP446', 'ExtFP448', 'ExtFP451', 'ExtFP454', 'ExtFP456', 'ExtFP457', 'ExtFP459', 'ExtFP463', 'ExtFP465', 'ExtFP469', 'ExtFP473', 'ExtFP475', 'ExtFP481', 'ExtFP486', 'ExtFP495', 'ExtFP497', 'ExtFP501', 'ExtFP509', 'ExtFP511', 'ExtFP512', 'ExtFP517', 'ExtFP522', 'ExtFP525', 'ExtFP527', 'ExtFP538', 'ExtFP541', 'ExtFP544', 'ExtFP545', 'ExtFP548', 'ExtFP551', 'ExtFP552', 'ExtFP554', 'ExtFP555', 'ExtFP556', 'ExtFP561', 'ExtFP566', 'ExtFP568', 'ExtFP573', 'ExtFP574', 'ExtFP576', 'ExtFP584', 'ExtFP587', 'ExtFP590', 'ExtFP592', 'ExtFP593', 'ExtFP594', 'ExtFP596', 'ExtFP597', 'ExtFP602', 'ExtFP610', 'ExtFP615', 'ExtFP618', 'ExtFP619', 'ExtFP620', 'ExtFP622', 'ExtFP624', 'ExtFP625', 'ExtFP629', 'ExtFP630', 'ExtFP632', 'ExtFP638', 'ExtFP639', 'ExtFP643', 'ExtFP645', 'ExtFP652', 'ExtFP654', 'ExtFP657', 'ExtFP659', 'ExtFP660', 'ExtFP661', 'ExtFP662', 'ExtFP672', 'ExtFP673', 'ExtFP676', 'ExtFP678', 'ExtFP679', 'ExtFP684', 'ExtFP687', 'ExtFP688', 'ExtFP689', 'ExtFP690', 'ExtFP694', 'ExtFP698', 'ExtFP701', 'ExtFP702', 'ExtFP704', 'ExtFP710', 'ExtFP724', 'ExtFP725', 'ExtFP731', 'ExtFP732', 'ExtFP740', 'ExtFP741', 'ExtFP746', 'ExtFP749', 'ExtFP760', 'ExtFP761', 'ExtFP762', 'ExtFP763', 'ExtFP767', 'ExtFP768', 'ExtFP773', 'ExtFP776', 'ExtFP789', 'ExtFP792', 'ExtFP802', 'ExtFP806', 'ExtFP807', 'ExtFP811', 'ExtFP813', 'ExtFP816', 'ExtFP820', 'ExtFP828', 'ExtFP829', 'ExtFP837', 'ExtFP838', 'ExtFP839', 'ExtFP848', 'ExtFP849', 'ExtFP850', 'ExtFP853', 'ExtFP856', 'ExtFP857', 'ExtFP859', 'ExtFP860', 'ExtFP863', 'ExtFP864', 'ExtFP865', 'ExtFP866', 'ExtFP867', 'ExtFP870', 'ExtFP875', 'ExtFP881', 'ExtFP883', 'ExtFP892', 'ExtFP896', 'ExtFP898', 'ExtFP900', 'ExtFP901', 'ExtFP903', 'ExtFP905', 'ExtFP912', 'ExtFP916', 'ExtFP917', 'ExtFP919', 'ExtFP920', 'ExtFP923', 'ExtFP924', 'ExtFP926', 'ExtFP930', 'ExtFP932', 'ExtFP933', 'ExtFP936', 'ExtFP938', 'ExtFP939', 'ExtFP940', 'ExtFP942', 'ExtFP945', 'ExtFP946', 'ExtFP948', 'ExtFP949', 'ExtFP951', 'ExtFP952', 'ExtFP959', 'ExtFP960', 'ExtFP961', 'ExtFP963', 'ExtFP974', 'ExtFP978', 'ExtFP979', 'ExtFP981', 'ExtFP985', 'ExtFP991', 'ExtFP992', 'ExtFP993', 'ExtFP998', 'ExtFP1011', 'ExtFP1012', 'ExtFP1013', 'ExtFP1016', 'ExtFP1017', 'FP2', 'FP7', 'FP10', 'FP13', 'FP14', 'FP16', 'FP20', 'FP23', 'FP25', 'FP26', 'FP31', 'FP35', 'FP37', 'FP38', 'FP39', 'FP43', 'FP44', 'FP46', 'FP47', 'FP48', 'FP56', 'FP60', 'FP63', 'FP66', 'FP70', 'FP71', 'FP74', 'FP75', 'FP76', 'FP80', 'FP84', 'FP88', 'FP90', 'FP93', 'FP95', 'FP97', 'FP98', 'FP101', 'FP102', 'FP105', 'FP106', 'FP111', 'FP117', 'FP121', 'FP126', 'FP131', 'FP133', 'FP135', 'FP137', 'FP140', 'FP141', 'FP145', 'FP153', 'FP157', 'FP161', 'FP163', 'FP169', 'FP173', 'FP179', 'FP182', 'FP184', 'FP192', 'FP193', 'FP194', 'FP195', 'FP200', 'FP202', 'FP205', 'FP206', 'FP207', 'FP215', 'FP218', 'FP219', 'FP220', 'FP222', 'FP225', 'FP229', 'FP230', 'FP234', 'FP236', 'FP237', 'FP238', 'FP244', 'FP248', 'FP250', 'FP251', 'FP252', 'FP256', 'FP265', 'FP266', 'FP267', 'FP268', 'FP269', 'FP275', 'FP276', 'FP280', 'FP281', 'FP282', 'FP283', 'FP284', 'FP286', 'FP294', 'FP296', 'FP300', 'FP301', 'FP302', 'FP305', 'FP309', 'FP311', 'FP316', 'FP319', 'FP321', 'FP324', 'FP325', 'FP326', 'FP329', 'FP334', 'FP336', 'FP338', 'FP339', 'FP340', 'FP341', 'FP344', 'FP346', 'FP347', 'FP363', 'FP365', 'FP366', 'FP370', 'FP379', 'FP380', 'FP381', 'FP383', 'FP389', 'FP391', 'FP393', 'FP412', 'FP413', 'FP414', 'FP415', 'FP417', 'FP420', 'FP423', 'FP427', 'FP428', 'FP429', 'FP430', 'FP434', 'FP436', 'FP440', 'FP445', 'FP446', 'FP448', 'FP450', 'FP459', 'FP461', 'FP464', 'FP465', 'FP466', 'FP475', 'FP480', 'FP483', 'FP486', 'FP488', 'FP491', 'FP494', 'FP505', 'FP508', 'FP513', 'FP517', 'FP520', 'FP522', 'FP524', 'FP531', 'FP532', 'FP533', 'FP534', 'FP541', 'FP546', 'FP551', 'FP560', 'FP566', 'FP567', 'FP569', 'FP572', 'FP574', 'FP578', 'FP581', 'FP582', 'FP583', 'FP593', 'FP594', 'FP600', 'FP601', 'FP606', 'FP609', 'FP611', 'FP612', 'FP620', 'FP623', 'FP633', 'FP635', 'FP637', 'FP639', 'FP645', 'FP653', 'FP654', 'FP658', 'FP659', 'FP661', 'FP666', 'FP670', 'FP672', 'FP681', 'FP696', 'FP704', 'FP713', 'FP714', 'FP717', 'FP718', 'FP724', 'FP728', 'FP731', 'FP734', 'FP735', 'FP737', 'FP744', 'FP745', 'FP749', 'FP750', 'FP755', 'FP759', 'FP762', 'FP765', 'FP774', 'FP777', 'FP780', 'FP782', 'FP786', 'FP792', 'FP798', 'FP802', 'FP808', 'FP812', 'FP817', 'FP819', 'FP820', 'FP821', 'FP831', 'FP833', 'FP835', 'FP837', 'FP839', 'FP840', 'FP851', 'FP852', 'FP859', 'FP861', 'FP862', 'FP872', 'FP875', 'FP877', 'FP879', 'FP883', 'FP885', 'FP887', 'FP891', 'FP894', 'FP899', 'FP901', 'FP910', 'FP912', 'FP917', 'FP918', 'FP920', 'FP922', 'FP925', 'FP927', 'FP932', 'FP934', 'FP935', 'FP936', 'FP941', 'FP943', 'FP944', 'FP950', 'FP956', 'FP958', 'FP961', 'FP962', 'FP966', 'FP969', 'FP970', 'FP977', 'FP980', 'FP982', 'FP984', 'FP990', 'FP994', 'FP996', 'FP997', 'FP998', 'FP1001', 'FP1002', 'FP1009', 'FP1015', 'FP1016', 'FP1017', 'FP1019', 'FP1021', 'FP1022', 'GraphFP6', 'GraphFP12', 'GraphFP27', 'GraphFP41', 'GraphFP45', 'GraphFP59', 'GraphFP101', 'GraphFP122', 'GraphFP124', 'GraphFP129', 'GraphFP131', 'GraphFP138', 'GraphFP148', 'GraphFP156', 'GraphFP170', 'GraphFP174', 'GraphFP180', 'GraphFP183', 'GraphFP197', 'GraphFP235', 'GraphFP255', 'GraphFP264', 'GraphFP270', 'GraphFP308', 'GraphFP359', 'GraphFP395', 'GraphFP411', 'GraphFP412', 'GraphFP455', 'GraphFP464', 'GraphFP478', 'GraphFP484', 'GraphFP487', 'GraphFP497', 'GraphFP501', 'GraphFP534', 'GraphFP550', 'GraphFP552', 'GraphFP554', 'GraphFP558', 'GraphFP579', 'GraphFP581', 'GraphFP669', 'GraphFP672', 'GraphFP703', 'GraphFP714', 'GraphFP716', 'GraphFP725', 'GraphFP731', 'GraphFP746', 'GraphFP751', 'GraphFP764', 'GraphFP768', 'GraphFP771', 'GraphFP777', 'GraphFP782', 'GraphFP808', 'GraphFP813', 'GraphFP833', 'GraphFP834', 'GraphFP836', 'GraphFP840', 'GraphFP847', 'GraphFP851', 'GraphFP852', 'GraphFP867', 'GraphFP882', 'GraphFP886', 'GraphFP889', 'GraphFP892', 'GraphFP896', 'GraphFP899', 'GraphFP905', 'GraphFP910', 'GraphFP912', 'GraphFP926', 'GraphFP946', 'GraphFP953', 'GraphFP965', 'GraphFP973', 'GraphFP1001', 'KRFP14', 'KRFP299', 'KRFP303', 'KRFP314', 'KRFP344', 'KRFP346', 'KRFP347', 'KRFP348', 'KRFP382', 'KRFP383', 'KRFP481', 'KRFP507', 'KRFP605', 'KRFP610', 'KRFP647', 'KRFP682', 'KRFP841', 'KRFP842', 'KRFP1240', 'KRFP2265', 'KRFP3054', 'KRFP3058', 'KRFP3385', 'KRFP3398', 'KRFP3660', 'KRFP3734', 'KRFP3757', 'KRFP3764', 'KRFP3897', 'KRFPC2', 'KRFPC16', 'KRFPC98', 'KRFPC297', 'KRFPC302', 'KRFPC303', 'KRFPC314', 'KRFPC344', 'KRFPC347', 'KRFPC360', 'KRFPC363', 'KRFPC382', 'KRFPC444', 'KRFPC504', 'KRFPC508', 'KRFPC554', 'KRFPC555', 'KRFPC566', 'KRFPC605', 'KRFPC610', 'KRFPC630', 'KRFPC647', 'KRFPC690', 'KRFPC697', 'KRFPC791', 'KRFPC842', 'KRFPC848', 'KRFPC1566', 'KRFPC1591', 'KRFPC1645', 'KRFPC3013', 'KRFPC3385', 'KRFPC3400', 'KRFPC3405', 'KRFPC3408', 'KRFPC3435', 'KRFPC3440', 'KRFPC3529', 'KRFPC3548', 'KRFPC3648', 'KRFPC3660', 'KRFPC3682', 'KRFPC3706', 'KRFPC3712', 'KRFPC3713', 'KRFPC3729', 'KRFPC3737', 'KRFPC3738', 'KRFPC3741', 'KRFPC3753', 'KRFPC3758', 'KRFPC3759', 'KRFPC3760', 'KRFPC3778', 'KRFPC3788', 'KRFPC3934', 'KRFPC4521', 'KRFPC4522', 'MACCSFP53', 'MACCSFP54', 'MACCSFP74', 'MACCSFP75', 'MACCSFP76', 'MACCSFP82', 'MACCSFP87', 'MACCSFP90', 'MACCSFP91', 'MACCSFP94', 'MACCSFP100', 'MACCSFP104', 'MACCSFP106', 'MACCSFP108', 'MACCSFP115', 'MACCSFP116', 'MACCSFP128', 'MACCSFP129', 'MACCSFP131', 'MACCSFP132', 'MACCSFP138', 'MACCSFP141', 'MACCSFP144', 'MACCSFP149', 'MACCSFP153', 'PubchemFP0', 'PubchemFP1', 'PubchemFP13', 'PubchemFP17', 'PubchemFP157', 'PubchemFP192', 'PubchemFP193', 'PubchemFP199', 'PubchemFP200', 'PubchemFP206', 'PubchemFP261', 'PubchemFP377', 'PubchemFP421', 'PubchemFP432', 'PubchemFP493', 'PubchemFP545', 'PubchemFP549', 'PubchemFP577', 'PubchemFP600', 'PubchemFP637', 'PubchemFP665', 'PubchemFP672', 'PubchemFP682', 'PubchemFP697', 'SubFP16', 'SubFP23', 'SubFP101', 'SubFP287', 'SubFPC2', 'SubFPC100', 'SubFPC101', 'SubFPC127', 'SubFPC135', 'SubFPC137', 'SubFPC143', 'SubFPC275', 'SubFPC302', 'x_fine_emb_MFXL0', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL3', 'x_fine_emb_MFXL4', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL6', 'x_fine_emb_MFXL7', 'x_fine_emb_MFXL8', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL10', 'x_fine_emb_MFXL11', 'x_fine_emb_MFXL12', 'x_fine_emb_MFXL13', 'x_fine_emb_MFXL14', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL16', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL18', 'x_fine_emb_MFXL19', 'x_fine_emb_MFXL20', 'x_fine_emb_MFXL21', 'x_fine_emb_MFXL22', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL26', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL29', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL31', 'x_fine_emb_MFXL32', 'x_fine_emb_MFXL33', 'x_fine_emb_MFXL34', 'x_fine_emb_MFXL35', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL37', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL43', 'x_fine_emb_MFXL44', 'x_fine_emb_MFXL45', 'x_fine_emb_MFXL46', 'x_fine_emb_MFXL47', 'x_fine_emb_MFXL48', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL51', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL53', 'x_fine_emb_MFXL54', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL56', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL58', 'x_fine_emb_MFXL59', 'x_fine_emb_MFXL60', 'x_fine_emb_MFXL61', 'x_fine_emb_MFXL62', 'x_fine_emb_MFXL63', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL66', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL68', 'x_fine_emb_MFXL69', 'x_fine_emb_MFXL70', 'x_fine_emb_MFXL71', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL73', 'x_fine_emb_MFXL74', 'x_fine_emb_MFXL75', 'x_fine_emb_MFXL76', 'x_fine_emb_MFXL78', 'x_fine_emb_MFXL79', 'x_fine_emb_MFXL80', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL83', 'x_fine_emb_MFXL84', 'x_fine_emb_MFXL85', 'x_fine_emb_MFXL86', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL88', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL94', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL96', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL98', 'x_fine_emb_MFXL99', 'x_fine_emb_MFXL100', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL102', 'x_fine_emb_MFXL103', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL105', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL107', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL110', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL112', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL116', 'x_fine_emb_MFXL117', 'x_fine_emb_MFXL118', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL120', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL122', 'x_fine_emb_MFXL123', 'x_fine_emb_MFXL124', 'x_fine_emb_MFXL125', 'x_fine_emb_MFXL126', 'x_fine_emb_MFXL127', 'x_fine_emb_MFXL128', 'x_fine_emb_MFXL129', 'x_fine_emb_MFXL130', 'x_fine_emb_MFXL131', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL133', 'x_fine_emb_MFXL134', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL137', 'x_fine_emb_MFXL138', 'x_fine_emb_MFXL139', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL142', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL144', 'x_fine_emb_MFXL145', 'x_fine_emb_MFXL146', 'x_fine_emb_MFXL147', 'x_fine_emb_MFXL148', 'x_fine_emb_MFXL149',

In [5]:
def train_and_test_predict(models, X_train, y_train, X_test, y_test):
    kf = KFold(n_splits=5, shuffle=True, random_state=101)
    results = {}
    predictions = []  

    for model in models:
        model_name = model.__class__.__name__
        predictions_train = []
        actual_y_train = []

        test_predictions_folds = []

        

        for train_index, val_index in kf.split(X_train):
            X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
            y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

            model.fit(X_train_fold, y_train_fold)

            y_pred_fold = model.predict(X_val_fold)
            y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
            predictions_train.extend(y_pred_fold)
            actual_y_train.extend(y_val_fold)

            predictions_test_fold = model.predict(X_test)
            predictions_test_fold = np.clip(predictions_test_fold, -10, -3.9)
            test_predictions_folds.append(predictions_test_fold)


        mse_train = mean_squared_error(actual_y_train, predictions_train)
        mae_train = mean_absolute_error(actual_y_train, predictions_train)
        rmse_train = np.sqrt(mse_train)
        r2_train = r2_score(actual_y_train, predictions_train)
        pearson_train, _ = pearsonr(actual_y_train, predictions_train)
        spearman_train, _ = spearmanr(actual_y_train, predictions_train)


        predictions_test_mean = np.mean(test_predictions_folds, axis=0)
        predictions_test_std = np.std(test_predictions_folds, axis=0)

        mse_test = mean_squared_error(y_test, predictions_test_mean)
        mae_test = mean_absolute_error(y_test, predictions_test_mean)
        rmse_test = np.sqrt(mse_test)
        r2_test = r2_score(y_test, predictions_test_mean)
        print(r2_test)
        pearson_test, _ = pearsonr(y_test, predictions_test_mean)
        spearman_test, _ = spearmanr(y_test, predictions_test_mean)
        
        

        predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_test,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

        results[model_name] = {
            'Train MSE (5 fold cv)': f"{mse_train:.4f}",
            'Train MAE (5 fold cv)': f"{mae_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train R2 (5 fold cv)': f"{r2_train:.4f}",
            'Train PCC (5 fold cv)': f"{pearson_train:.4f}",
            'Train SCC (5 fold cv)': f"{spearman_train:.4f}",
            'Test MSE': f"{mse_test:.4f}",
            'Test MAE': f"{mae_test:.4f}",
            'Test RMSE': f"{rmse_test:.4f}",
            'Test R2': f"{r2_test:.4f}",
            'Test Pearson Correlation': f"{pearson_test:.4f}",
            'Test Spearman Correlation': f"{spearman_test:.4f}",
        }

    results_df = pd.DataFrame(results).T
    predictions_df = pd.DataFrame(predictions)

    return results_df, predictions_df

In [6]:
X_train = train.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test[X_train.columns]
y_test = test['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 2141)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 2141)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 21.557835 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 254463
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 2107
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 25.463228 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 254476
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 2109
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 24.227690 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 254467
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 2111
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 24.146494 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 254486
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 2112
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 24.274338 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 254458
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 2107
[LightGBM] [Info] Start training from score -5.729056
0.6763718693215905
0.6260524943671443
0.6749730549133907
0.6717004788441543
0.6349753191082461
0.6781353520201625
0.6767006533190019
0.32696352432168097
0.6502309595077205
0.6621624848682695
0.5579541479464443

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1320,0.2630,0.3633,0.7880,0.8877,0.8681,0.2058,0.3241,0.4536,0.6764,0.8227,0.8041
DecisionTreeRegressor,0.2824,0.3850,0.5314,0.5465,0.7793,0.7550,0.2377,0.3482,0.4876,0.6261,0.7954,0.7723
RandomForestRegressor,0.1344,0.2668,0.3666,0.7842,0.8856,0.8652,0.2066,0.3233,0.4546,0.6750,0.8217,0.8033
GradientBoostingRegressor,0.1321,0.2646,0.3634,0.7879,0.8876,0.8666,0.2087,0.3278,0.4569,0.6717,0.8199,0.7988
AdaBoostRegressor,0.1655,0.3177,0.4069,0.7341,0.8654,0.8425,0.2321,0.3677,0.4817,0.6350,0.8032,0.7831
XGBRegressor,0.1503,0.2828,0.3877,0.7585,0.8723,0.8517,0.2046,0.3213,0.4524,0.6781,0.8242,0.8079
ExtraTreesRegressor,0.1358,0.2676,0.3685,0.7819,0.8843,0.8652,0.2055,0.3208,0.4534,0.6767,0.8228,0.8062
LinearRegression,0.6649,0.4650,0.8154,-0.0680,0.6023,0.7230,0.4279,0.4247,0.6541,0.3270,0.6660,0.7017
KNeighborsRegressor,0.1974,0.3254,0.4443,0.6829,0.8300,0.8023,0.2224,0.3366,0.4716,0.6502,0.8096,0.7939
SVR,0.1558,0.2832,0.3948,0.7497,0.8664,0.8515,0.2148,0.3291,0.4635,0.6622,0.8144,0.8060
MLPRegressor,0.2739,0.3882,0.5234,0.5600,0.7907,0.7690,0.2810,0.3784,0.5301,0.5580,0.7662,0.7510

In [7]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_features_pampa.csv')

In [8]:
X = train.drop(columns=['ID', 'SMILES', 'Permeability'])
y = train['Permeability']

rf = RandomForestRegressor(n_estimators=100, random_state=101, n_jobs=-1)
rf.fit(X, y)

importances = rf.feature_importances_
feature_names = X.columns

In [9]:
#Top 10 features
n = 10  
top_10_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_10_features = feature_names[top_10_indices].tolist()  # convert to list

# Output the list
print("Top", 10, "features:\n")
print(top_10_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_10_features]], axis=1)
test_df = test[train.columns]

Top 10 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571']

In [10]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 10)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 10)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571'],
      dtype='object')
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.073656 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 10
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.097085 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 10
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.089374 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 10
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.159030 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 10
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.158548 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 10
[LightGBM] [Info] Start training from score -5.729056
0.6588854003062458
0.6007185511905646
0.6591062132920823
0.6586028429085606
0.5940335459063336
0.6497734612063931
0.6587647131047039
0.6545515648782421
0.6369915805450885
0.6525522717401634
0.6608613800431291

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1382,0.2728,0.3717,0.7781,0.8821,0.8589,0.2169,0.3351,0.4657,0.6589,0.8121,0.7900
DecisionTreeRegressor,0.2851,0.3913,0.5340,0.5420,0.7729,0.7477,0.2539,0.3577,0.5038,0.6007,0.7792,0.7597
RandomForestRegressor,0.1402,0.2751,0.3744,0.7749,0.8804,0.8578,0.2167,0.3334,0.4655,0.6591,0.8122,0.7899
GradientBoostingRegressor,0.1375,0.2733,0.3708,0.7792,0.8827,0.8601,0.2170,0.3368,0.4659,0.6586,0.8120,0.7887
AdaBoostRegressor,0.1938,0.3408,0.4403,0.6887,0.8429,0.8337,0.2581,0.3888,0.5080,0.5940,0.7811,0.7743
XGBRegressor,0.1534,0.2896,0.3917,0.7535,0.8690,0.8432,0.2227,0.3380,0.4719,0.6498,0.8071,0.7832
ExtraTreesRegressor,0.1406,0.2751,0.3750,0.7741,0.8801,0.8582,0.2169,0.3327,0.4658,0.6588,0.8121,0.7935
LinearRegression,0.1369,0.2762,0.3701,0.7800,0.8832,0.8594,0.2196,0.3393,0.4686,0.6546,0.8094,0.7862
KNeighborsRegressor,0.1697,0.3038,0.4120,0.7274,0.8555,0.8313,0.2308,0.3434,0.4804,0.6370,0.8012,0.7792
SVR,0.1357,0.2705,0.3684,0.7820,0.8846,0.8617,0.2209,0.3352,0.4700,0.6526,0.8093,0.7891
MLPRegressor,0.1383,0.2784,0.3719,0.7778,0.8825,0.8583,0.2156,0.3367,0.4643,0.6609,0.8130,0.7898

In [11]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_10_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_10_features_pampa.csv')

In [12]:
#Top 20 features
n = 20  
top_20_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_20_features = feature_names[top_20_indices].tolist()  # convert to list

# Output the list
print("Top", 20, "features:\n")
print(top_20_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_20_features]], axis=1)
test_df = test[train.columns]

Top 20 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658']

In [13]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 20)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 20)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452',
       'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538',
       'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207',
       'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658'],
      dtype='object')
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.228162 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 20
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.157447 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 20
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.149840 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 20
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.150223 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 20
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.154088 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 5100
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 20
[LightGBM] [Info] Start training from score -5.729056
0.6632930258090344
0.6302102853313111
0.6668800283664349
0.6601742800718273
0.6173589940020555
0.6598661483278759
0.6642447311071804
0.6518550417819046
0.6450876340785346
0.659485463103425
0.660181797034286

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1345,0.2689,0.3667,0.7840,0.8854,0.8633,0.2141,0.3324,0.4627,0.6633,0.8149,0.7946
DecisionTreeRegressor,0.2637,0.3769,0.5135,0.5764,0.7878,0.7594,0.2351,0.3480,0.4849,0.6302,0.7979,0.7788
RandomForestRegressor,0.1363,0.2707,0.3692,0.7811,0.8839,0.8625,0.2118,0.3281,0.4602,0.6669,0.8169,0.7966
GradientBoostingRegressor,0.1350,0.2704,0.3674,0.7832,0.8850,0.8625,0.2161,0.3354,0.4648,0.6602,0.8131,0.7898
AdaBoostRegressor,0.1766,0.3256,0.4202,0.7164,0.8534,0.8293,0.2433,0.3731,0.4932,0.6174,0.7906,0.7716
XGBRegressor,0.1551,0.2886,0.3939,0.7508,0.8680,0.8439,0.2162,0.3322,0.4650,0.6599,0.8132,0.7907
ExtraTreesRegressor,0.1379,0.2711,0.3714,0.7784,0.8825,0.8622,0.2135,0.3292,0.4620,0.6642,0.8155,0.7982
LinearRegression,0.1350,0.2736,0.3674,0.7832,0.8850,0.8612,0.2213,0.3406,0.4705,0.6519,0.8078,0.7847
KNeighborsRegressor,0.1645,0.2978,0.4056,0.7358,0.8603,0.8347,0.2256,0.3408,0.4750,0.6451,0.8063,0.7870
SVR,0.1337,0.2656,0.3656,0.7853,0.8865,0.8646,0.2165,0.3316,0.4653,0.6595,0.8135,0.7937
MLPRegressor,0.1384,0.2760,0.3720,0.7777,0.8821,0.8579,0.2160,0.3343,0.4648,0.6602,0.8135,0.7912

In [14]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_20_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_20_features_pampa.csv')

In [15]:
#Top 50 features
n = 50  
top_50_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_50_features = feature_names[top_50_indices].tolist()  # convert to list

# Output the list
print("Top", 50, "features:\n")
print(top_50_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_50_features]], axis=1)
test_df = test[train.columns]

Top 50 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192', 'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457']

In [16]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 50)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 50)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452',
       'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538',
       'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207',
       'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486',
       'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259',
       'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192',
       'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136',
       'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651',
       'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472',
       'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106',
       'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615',
       'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141',
       'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15',
       'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457'],
      dtype='object')
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.204500 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 50
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.143464 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 50
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.166747 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 50
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.192761 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 50
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.159151 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 12750
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 50
[LightGBM] [Info] Start training from score -5.729056
0.6694516048578074
0.6198003686909717
0.6712725922302336
0.6641668898187878
0.6232707358507484
0.6743469943509619
0.6714395378345481
0.660283020165084
0.64973431044067
0.664360031457448

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.6473060745476737

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1314,0.2649,0.3624,0.7890,0.8883,0.8666,0.2102,0.3285,0.4584,0.6695,0.8185,0.7981
DecisionTreeRegressor,0.2757,0.3823,0.5251,0.5571,0.7823,0.7563,0.2417,0.3499,0.4916,0.6198,0.7915,0.7710
RandomForestRegressor,0.1319,0.2659,0.3631,0.7882,0.8879,0.8658,0.2090,0.3256,0.4572,0.6713,0.8196,0.8013
GradientBoostingRegressor,0.1323,0.2665,0.3638,0.7875,0.8874,0.8640,0.2135,0.3321,0.4621,0.6642,0.8155,0.7939
AdaBoostRegressor,0.1691,0.3178,0.4112,0.7284,0.8599,0.8355,0.2395,0.3688,0.4894,0.6233,0.7938,0.7725
XGBRegressor,0.1524,0.2845,0.3904,0.7552,0.8702,0.8471,0.2070,0.3251,0.4550,0.6743,0.8218,0.8022
ExtraTreesRegressor,0.1343,0.2671,0.3664,0.7844,0.8857,0.8647,0.2089,0.3248,0.4570,0.6714,0.8197,0.8023
LinearRegression,0.1312,0.2693,0.3623,0.7892,0.8884,0.8637,0.2160,0.3349,0.4647,0.6603,0.8129,0.7889
KNeighborsRegressor,0.1673,0.3001,0.4090,0.7314,0.8578,0.8297,0.2227,0.3373,0.4719,0.6497,0.8087,0.7887
SVR,0.1321,0.2634,0.3635,0.7878,0.8879,0.8659,0.2134,0.3267,0.4619,0.6644,0.8162,0.7981
MLPRegressor,0.1603,0.3006,0.4004,0.7425,0.8641,0.8379,0.2242,0.3428,0.4735,0.6473,0.8072,0.7747

In [17]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_50_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_50_features_pampa.csv')

In [18]:
#Top 100 features
n = 100  
top_100_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_100_features = feature_names[top_100_indices].tolist()  # convert to list

# Output the list
print("Top", 100, "features:\n")
print(top_100_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_100_features]], axis=1)
test_df = test[train.columns]

Top 100 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192', 'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457', '3d_rdkit_9', 'x_fine_emb_MFXL758', 'x_fine_emb_MFXL514', 'x_fine_emb_MFXL227', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL347', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL432', 'L3p', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL471', 'geomShape', 'TDB9u', 'x_fine_emb_MFXL745', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL726', 'x_fine_emb_MFXL516', 'LOBMIN', 'x_fine_emb_MFXL265', 'Ku', 'x_fine_emb_MFXL264', 'x_fine_emb_MFXL369', 'x_fine_emb_MFXL561', 'LOBMAX', 'x_fine_emb_MFXL386', 'x_fine_emb_MFXL764', '3d_rdkit_10', '3d_rdkit_5', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL595', 'x_fine_emb_MFXL161', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL552', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL497', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL59', 'x_fine_emb_MFXL442', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL546']

In [19]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 100)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 100)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452',
       'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538',
       'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207',
       'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486',
       'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259',
       'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192',
       'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136',
       'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651',
       'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472',
       'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106',
       'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615',
       'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141',
       'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15',
       'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457', '3d_rdkit_9',
       'x_fine_emb_MFXL758', 'x_fine_emb_MFXL514', 'x_fine_emb_MFXL227',
       'x_fine_emb_MFXL562', 'x_fine_emb_MFXL347', 'x_fine_emb_MFXL135',
       'x_fine_emb_MFXL432', 'L3p', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL234',
       'x_fine_emb_MFXL121', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL471',
       'geomShape', 'TDB9u', 'x_fine_emb_MFXL745', 'x_fine_emb_MFXL216',
       'x_fine_emb_MFXL365', 'x_fine_emb_MFXL726', 'x_fine_emb_MFXL516',
       'LOBMIN', 'x_fine_emb_MFXL265', 'Ku', 'x_fine_emb_MFXL264',
       'x_fine_emb_MFXL369', 'x_fine_emb_MFXL561', 'LOBMAX',
       'x_fine_emb_MFXL386', 'x_fine_emb_MFXL764', '3d_rdkit_10', '3d_rdkit_5',
       'x_fine_emb_MFXL189', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL595',
       'x_fine_emb_MFXL161', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL478',
       'x_fine_emb_MFXL552', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL497',
       'x_fine_emb_MFXL759', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL59',
       'x_fine_emb_MFXL442', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL143',
       'x_fine_emb_MFXL280', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL546'],
      dtype='object')
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.198989 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 100
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.162799 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 100
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.143208 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 100
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.161581 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.166863 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 100
[LightGBM] [Info] Start training from score -5.729056
0.669902116225403
0.6221747324866388
0.6719807303152572
0.663617817450054
0.6279267418146082
0.6660586001559623
0.6724872353269093
0.6635770204354938
0.6437104440852243
0.664514057538858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

0.5980503368840411

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1311,0.2642,0.3621,0.7894,0.8885,0.8676,0.2099,0.3281,0.4581,0.6699,0.8188,0.7989
DecisionTreeRegressor,0.2605,0.3731,0.5104,0.5815,0.7932,0.7611,0.2402,0.3533,0.4901,0.6222,0.7932,0.7761
RandomForestRegressor,0.1322,0.2654,0.3635,0.7877,0.8876,0.8662,0.2085,0.3256,0.4567,0.6720,0.8199,0.8007
GradientBoostingRegressor,0.1329,0.2660,0.3646,0.7865,0.8869,0.8650,0.2139,0.3316,0.4625,0.6636,0.8151,0.7937
AdaBoostRegressor,0.1684,0.3184,0.4103,0.7296,0.8629,0.8423,0.2366,0.3683,0.4864,0.6279,0.7985,0.7800
XGBRegressor,0.1491,0.2822,0.3862,0.7605,0.8730,0.8526,0.2123,0.3303,0.4608,0.6661,0.8167,0.7990
ExtraTreesRegressor,0.1325,0.2653,0.3640,0.7872,0.8873,0.8661,0.2082,0.3235,0.4563,0.6725,0.8203,0.8036
LinearRegression,0.1299,0.2671,0.3604,0.7913,0.8896,0.8654,0.2139,0.3336,0.4625,0.6636,0.8149,0.7932
KNeighborsRegressor,0.1702,0.3021,0.4126,0.7266,0.8547,0.8244,0.2265,0.3424,0.4759,0.6437,0.8048,0.7859
SVR,0.1326,0.2646,0.3641,0.7870,0.8873,0.8666,0.2133,0.3301,0.4618,0.6645,0.8159,0.8004
MLPRegressor,0.1974,0.3380,0.4443,0.6829,0.8313,0.7982,0.2555,0.3699,0.5055,0.5981,0.7776,0.7528

In [20]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_100_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_100_features_pampa.csv')

In [21]:
#Top 200 features
n = 200  
top_200_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_200_features = feature_names[top_200_indices].tolist()  # convert to list

# Output the list
print("Top", 200, "features:\n")
print(top_200_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_200_features]], axis=1)
test_df = test[train.columns]

Top 200 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192', 'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457', '3d_rdkit_9', 'x_fine_emb_MFXL758', 'x_fine_emb_MFXL514', 'x_fine_emb_MFXL227', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL347', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL432', 'L3p', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL471', 'geomShape', 'TDB9u', 'x_fine_emb_MFXL745', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL726', 'x_fine_emb_MFXL516', 'LOBMIN', 'x_fine_emb_MFXL265', 'Ku', 'x_fine_emb_MFXL264', 'x_fine_emb_MFXL369', 'x_fine_emb_MFXL561', 'LOBMAX', 'x_fine_emb_MFXL386', 'x_fine_emb_MFXL764', '3d_rdkit_10', '3d_rdkit_5', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL595', 'x_fine_emb_MFXL161', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL552', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL497', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL59', 'x_fine_emb_MFXL442', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL546', 'Dv', 'x_fine_emb_MFXL648', 'TDB9s', 'x_fine_emb_MFXL728', 'x_fine_emb_MFXL663', 'x_fine_emb_MFXL520', 'x_fine_emb_MFXL720', 'x_fine_emb_MFXL354', 'x_fine_emb_MFXL381', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL110', 'x_fine_emb_MFXL173', 'x_fine_emb_MFXL232', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL69', 'x_fine_emb_MFXL580', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL348', 'x_fine_emb_MFXL16', 'RDF20i', 'x_fine_emb_MFXL148', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL68', 'x_fine_emb_MFXL388', 'x_fine_emb_MFXL329', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL33', 'x_fine_emb_MFXL421', 'x_fine_emb_MFXL99', 'TDB5e', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL186', 'x_fine_emb_MFXL763', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL657', 'x_fine_emb_MFXL716', 'x_fine_emb_MFXL199', 'x_fine_emb_MFXL37', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL371', 'x_fine_emb_MFXL408', 'x_fine_emb_MFXL79', 'x_fine_emb_MFXL142', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL401', 'TDB9p', 'x_fine_emb_MFXL10', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL268', '3d_rdkit_11', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL378', 'x_fine_emb_MFXL71', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL584', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL413', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL453', 'x_fine_emb_MFXL460', 'x_fine_emb_MFXL297', 'x_fine_emb_MFXL757', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL531', 'x_fine_emb_MFXL139', 'x_fine_emb_MFXL183', 'TDB8s', 'x_fine_emb_MFXL499', 'x_fine_emb_MFXL601', 'TDB5s', 'Dm', 'x_fine_emb_MFXL693', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL714', 'x_fine_emb_MFXL218', 'x_fine_emb_MFXL154', 'x_fine_emb_MFXL390', 'RNCS', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL638', 'x_fine_emb_MFXL470', 'x_fine_emb_MFXL302', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL251', 'x_fine_emb_MFXL733', 'TDB10m', 'x_fine_emb_MFXL468', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL732', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL704', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL198']

In [22]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 200)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 200)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571',
       ...
       'x_fine_emb_MFXL251', 'x_fine_emb_MFXL733', 'TDB10m',
       'x_fine_emb_MFXL468', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL732',
       'x_fine_emb_MFXL108', 'x_fine_emb_MFXL704', 'x_fine_emb_MFXL17',
       'x_fine_emb_MFXL198'],
      dtype='object', length=200)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.186657 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 200
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.144546 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 200
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.138594 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 200
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.153876 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 200
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.254671 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 51000
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 200
[LightGBM] [Info] Start training from score -5.729056
0.6716852892277763
0.6274832811912329
0.6741211423206077
0.6659339639896513
0.628957665977562
0.669686793844336
0.6762874714733129
0.6648744027237292
0.6527710050620003
0.6643237375581039
0.5687203829233527

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1309,0.2635,0.3619,0.7897,0.8887,0.8691,0.2087,0.3271,0.4569,0.6717,0.8199,0.8012
DecisionTreeRegressor,0.2635,0.3754,0.5133,0.5768,0.7891,0.7655,0.2368,0.3484,0.4867,0.6275,0.7957,0.7723
RandomForestRegressor,0.1312,0.2642,0.3622,0.7893,0.8885,0.8675,0.2072,0.3244,0.4552,0.6741,0.8212,0.8026
GradientBoostingRegressor,0.1330,0.2666,0.3647,0.7864,0.8868,0.8655,0.2124,0.3305,0.4609,0.6659,0.8165,0.7943
AdaBoostRegressor,0.1644,0.3145,0.4054,0.7360,0.8659,0.8424,0.2359,0.3708,0.4857,0.6290,0.7986,0.7748
XGBRegressor,0.1518,0.2850,0.3896,0.7562,0.8708,0.8489,0.2100,0.3261,0.4583,0.6697,0.8190,0.8010
ExtraTreesRegressor,0.1329,0.2653,0.3645,0.7866,0.8870,0.8669,0.2058,0.3223,0.4537,0.6763,0.8226,0.8061
LinearRegression,0.1296,0.2664,0.3600,0.7918,0.8899,0.8665,0.2131,0.3325,0.4616,0.6649,0.8158,0.7953
KNeighborsRegressor,0.1756,0.3034,0.4191,0.7179,0.8503,0.8222,0.2208,0.3383,0.4698,0.6528,0.8105,0.7929
SVR,0.1350,0.2667,0.3674,0.7832,0.8852,0.8661,0.2134,0.3290,0.4620,0.6643,0.8156,0.7981
MLPRegressor,0.2253,0.3551,0.4746,0.6382,0.8182,0.7946,0.2742,0.3791,0.5236,0.5687,0.7650,0.7368

In [23]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_200_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_200_features_pampa.csv')

In [24]:
#Top 500 features
n = 500  
top_500_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_500_features = feature_names[top_500_indices].tolist()  # convert to list

# Output the list
print("Top", 500, "features:\n")
print(top_500_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_500_features]], axis=1)
test_df = test[train.columns]

Top 500 features:

['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL640', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL315', 'x_fine_emb_MFXL27', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL192', 'MOMI-XY', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL50', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL270', 'CrippenLogP', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL615', 'x_fine_emb_MFXL38', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL15', 'x_fine_emb_MFXL394', 'x_fine_emb_MFXL457', '3d_rdkit_9', 'x_fine_emb_MFXL758', 'x_fine_emb_MFXL514', 'x_fine_emb_MFXL227', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL347', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL432', 'L3p', 'x_fine_emb_MFXL765', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL471', 'geomShape', 'TDB9u', 'x_fine_emb_MFXL745', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL726', 'x_fine_emb_MFXL516', 'LOBMIN', 'x_fine_emb_MFXL265', 'Ku', 'x_fine_emb_MFXL264', 'x_fine_emb_MFXL369', 'x_fine_emb_MFXL561', 'LOBMAX', 'x_fine_emb_MFXL386', 'x_fine_emb_MFXL764', '3d_rdkit_10', '3d_rdkit_5', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL595', 'x_fine_emb_MFXL161', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL552', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL497', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL59', 'x_fine_emb_MFXL442', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL143', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL546', 'Dv', 'x_fine_emb_MFXL648', 'TDB9s', 'x_fine_emb_MFXL728', 'x_fine_emb_MFXL663', 'x_fine_emb_MFXL520', 'x_fine_emb_MFXL720', 'x_fine_emb_MFXL354', 'x_fine_emb_MFXL381', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL110', 'x_fine_emb_MFXL173', 'x_fine_emb_MFXL232', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL69', 'x_fine_emb_MFXL580', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL348', 'x_fine_emb_MFXL16', 'RDF20i', 'x_fine_emb_MFXL148', 'x_fine_emb_MFXL248', 'x_fine_emb_MFXL68', 'x_fine_emb_MFXL388', 'x_fine_emb_MFXL329', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL33', 'x_fine_emb_MFXL421', 'x_fine_emb_MFXL99', 'TDB5e', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL186', 'x_fine_emb_MFXL763', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL657', 'x_fine_emb_MFXL716', 'x_fine_emb_MFXL199', 'x_fine_emb_MFXL37', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL371', 'x_fine_emb_MFXL408', 'x_fine_emb_MFXL79', 'x_fine_emb_MFXL142', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL401', 'TDB9p', 'x_fine_emb_MFXL10', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL268', '3d_rdkit_11', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL378', 'x_fine_emb_MFXL71', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL584', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL413', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL453', 'x_fine_emb_MFXL460', 'x_fine_emb_MFXL297', 'x_fine_emb_MFXL757', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL531', 'x_fine_emb_MFXL139', 'x_fine_emb_MFXL183', 'TDB8s', 'x_fine_emb_MFXL499', 'x_fine_emb_MFXL601', 'TDB5s', 'Dm', 'x_fine_emb_MFXL693', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL714', 'x_fine_emb_MFXL218', 'x_fine_emb_MFXL154', 'x_fine_emb_MFXL390', 'RNCS', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL638', 'x_fine_emb_MFXL470', 'x_fine_emb_MFXL302', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL251', 'x_fine_emb_MFXL733', 'TDB10m', 'x_fine_emb_MFXL468', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL732', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL704', 'x_fine_emb_MFXL17', 'x_fine_emb_MFXL198', 'x_fine_emb_MFXL319', 'x_fine_emb_MFXL363', 'x_fine_emb_MFXL400', 'x_fine_emb_MFXL570', 'x_fine_emb_MFXL53', 'x_fine_emb_MFXL397', 'x_fine_emb_MFXL412', 'x_fine_emb_MFXL738', 'x_fine_emb_MFXL19', 'x_fine_emb_MFXL120', 'x_fine_emb_MFXL231', 'x_fine_emb_MFXL411', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL396', 'x_fine_emb_MFXL356', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL303', 'x_fine_emb_MFXL730', 'TDB10s', 'x_fine_emb_MFXL574', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL750', 'x_fine_emb_MFXL656', 'x_fine_emb_MFXL682', 'x_fine_emb_MFXL445', 'x_fine_emb_MFXL673', 'x_fine_emb_MFXL669', 'x_fine_emb_MFXL29', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL98', 'x_fine_emb_MFXL667', 'x_fine_emb_MFXL686', 'x_fine_emb_MFXL525', 'x_fine_emb_MFXL290', 'x_fine_emb_MFXL86', 'x_fine_emb_MFXL727', 'x_fine_emb_MFXL534', 'x_fine_emb_MFXL361', 'x_fine_emb_MFXL332', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL709', 'x_fine_emb_MFXL544', 'TDB7s', 'x_fine_emb_MFXL250', 'x_fine_emb_MFXL7', 'x_fine_emb_MFXL539', 'x_fine_emb_MFXL734', 'x_fine_emb_MFXL559', 'x_fine_emb_MFXL257', 'x_fine_emb_MFXL323', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL608', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL526', 'x_fine_emb_MFXL585', 'x_fine_emb_MFXL31', 'x_fine_emb_MFXL641', 'x_fine_emb_MFXL404', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL766', 'x_fine_emb_MFXL392', 'x_fine_emb_MFXL741', 'x_fine_emb_MFXL70', 'x_fine_emb_MFXL60', 'x_fine_emb_MFXL748', 'x_fine_emb_MFXL579', 'x_fine_emb_MFXL308', 'x_fine_emb_MFXL646', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL61', 'x_fine_emb_MFXL626', 'x_fine_emb_MFXL364', 'x_fine_emb_MFXL724', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL420', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL245', 'x_fine_emb_MFXL389', 'x_fine_emb_MFXL650', 'x_fine_emb_MFXL622', 'x_fine_emb_MFXL443', 'x_fine_emb_MFXL102', 'x_fine_emb_MFXL196', 'x_fine_emb_MFXL557', 'x_fine_emb_MFXL221', 'x_fine_emb_MFXL487', 'x_fine_emb_MFXL426', 'x_fine_emb_MFXL665', 'x_fine_emb_MFXL493', 'x_fine_emb_MFXL519', 'x_fine_emb_MFXL384', 'x_fine_emb_MFXL165', 'x_fine_emb_MFXL176', 'x_fine_emb_MFXL423', 'x_fine_emb_MFXL324', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL605', 'x_fine_emb_MFXL672', 'x_fine_emb_MFXL187', 'x_fine_emb_MFXL242', 'x_fine_emb_MFXL631', 'x_fine_emb_MFXL177', 'x_fine_emb_MFXL253', 'x_fine_emb_MFXL200', 'x_fine_emb_MFXL700', 'x_fine_emb_MFXL739', 'x_fine_emb_MFXL729', 'x_fine_emb_MFXL627', 'x_fine_emb_MFXL589', 'x_fine_emb_MFXL710', 'x_fine_emb_MFXL599', 'x_fine_emb_MFXL225', 'x_fine_emb_MFXL623', 'x_fine_emb_MFXL383', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL330', 'x_fine_emb_MFXL697', 'TDB8p', 'x_fine_emb_MFXL583', 'x_fine_emb_MFXL336', 'x_fine_emb_MFXL296', 'x_fine_emb_MFXL377', 'x_fine_emb_MFXL602', 'x_fine_emb_MFXL610', 'x_fine_emb_MFXL558', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL652', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL145', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL45', 'x_fine_emb_MFXL277', 'x_fine_emb_MFXL20', 'x_fine_emb_MFXL197', 'x_fine_emb_MFXL505', 'x_fine_emb_MFXL373', 'x_fine_emb_MFXL684', 'x_fine_emb_MFXL629', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL683', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL614', 'x_fine_emb_MFXL78', 'x_fine_emb_MFXL185', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL278', 'x_fine_emb_MFXL349', 'x_fine_emb_MFXL485', 'x_fine_emb_MFXL166', 'x_fine_emb_MFXL54', 'x_fine_emb_MFXL639', 'x_fine_emb_MFXL754', 'x_fine_emb_MFXL127', 'x_fine_emb_MFXL313', 'x_fine_emb_MFXL529', 'x_fine_emb_MFXL635', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL517', 'x_fine_emb_MFXL674', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL690', 'x_fine_emb_MFXL708', 'x_fine_emb_MFXL743', 'x_fine_emb_MFXL122', 'x_fine_emb_MFXL436', 'x_fine_emb_MFXL628', 'x_fine_emb_MFXL181', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL240', 'x_fine_emb_MFXL309', 'x_fine_emb_MFXL398', 'x_fine_emb_MFXL376', 'x_fine_emb_MFXL451', 'x_fine_emb_MFXL409', 'x_fine_emb_MFXL677', 'x_fine_emb_MFXL172', 'x_fine_emb_MFXL712', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL26', 'x_fine_emb_MFXL761', 'x_fine_emb_MFXL247', 'x_fine_emb_MFXL513', 'x_fine_emb_MFXL316', 'x_fine_emb_MFXL518', 'x_fine_emb_MFXL502', 'x_fine_emb_MFXL564', 'x_fine_emb_MFXL572', 'x_fine_emb_MFXL467', 'x_fine_emb_MFXL75', 'x_fine_emb_MFXL73', 'SpMin7_Bhs', 'x_fine_emb_MFXL481', 'TDB7m', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL317', 'x_fine_emb_MFXL241', 'x_fine_emb_MFXL21', 'x_fine_emb_MFXL662', 'x_fine_emb_MFXL630', 'x_fine_emb_MFXL233', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL333', 'x_fine_emb_MFXL565', 'x_fine_emb_MFXL419', 'x_fine_emb_MFXL326', 'x_fine_emb_MFXL366', 'x_fine_emb_MFXL150', 'x_fine_emb_MFXL706', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL163', 'x_fine_emb_MFXL260', 'x_fine_emb_MFXL13', 'x_fine_emb_MFXL249', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL465', 'x_fine_emb_MFXL699', 'x_fine_emb_MFXL252', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL263', 'x_fine_emb_MFXL343', 'x_fine_emb_MFXL554', 'x_fine_emb_MFXL744', 'x_fine_emb_MFXL47', 'x_fine_emb_MFXL255', 'x_fine_emb_MFXL407', 'x_fine_emb_MFXL636', 'x_fine_emb_MFXL618', 'x_fine_emb_MFXL226', 'x_fine_emb_MFXL299', 'x_fine_emb_MFXL688', 'x_fine_emb_MFXL542', 'x_fine_emb_MFXL395', 'x_fine_emb_MFXL429', 'x_fine_emb_MFXL375', 'x_fine_emb_MFXL649', 'x_fine_emb_MFXL66', 'x_fine_emb_MFXL462', 'x_fine_emb_MFXL491', 'x_fine_emb_MFXL488', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL511', 'x_fine_emb_MFXL276', 'x_fine_emb_MFXL447', 'x_fine_emb_MFXL171', 'x_fine_emb_MFXL431', 'x_fine_emb_MFXL306', 'x_fine_emb_MFXL3', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL254', 'x_fine_emb_MFXL301', 'x_fine_emb_MFXL246', 'x_fine_emb_MFXL449', 'x_fine_emb_MFXL322', 'x_fine_emb_MFXL703', 'x_fine_emb_MFXL215', 'x_fine_emb_MFXL692', 'x_fine_emb_MFXL202', 'x_fine_emb_MFXL51', 'x_fine_emb_MFXL374', 'x_fine_emb_MFXL168', 'x_fine_emb_MFXL195', 'x_fine_emb_MFXL170', 'x_fine_emb_MFXL405', 'x_fine_emb_MFXL223', 'x_fine_emb_MFXL58', 'x_fine_emb_MFXL116', 'x_fine_emb_MFXL243', 'x_fine_emb_MFXL328', 'x_fine_emb_MFXL695', 'x_fine_emb_MFXL536', 'x_fine_emb_MFXL625', 'x_fine_emb_MFXL385', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL591', 'x_fine_emb_MFXL438', 'x_fine_emb_MFXL286', 'x_fine_emb_MFXL417', 'x_fine_emb_MFXL294', 'x_fine_emb_MFXL320', 'x_fine_emb_MFXL160', 'x_fine_emb_MFXL130', 'x_fine_emb_MFXL567', 'x_fine_emb_MFXL403', 'x_fine_emb_MFXL659', 'x_fine_emb_MFXL474', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL598', 'x_fine_emb_MFXL307', 'x_fine_emb_MFXL547', 'x_fine_emb_MFXL350', 'x_fine_emb_MFXL367', 'x_fine_emb_MFXL742', 'x_fine_emb_MFXL437']

In [25]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
print('Features: ', X_train.columns)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (5568, 500)
y_train shape:  (5568,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (1392, 500)
y_test shape:  (1392,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Features:  Index(['x_fine_emb_MFXL339', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL338',
       'x_fine_emb_MFXL190', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL427',
       'x_fine_emb_MFXL480', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL687',
       'x_fine_emb_MFXL571',
       ...
       'x_fine_emb_MFXL474', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL524',
       'x_fine_emb_MFXL598', 'x_fine_emb_MFXL307', 'x_fine_emb_MFXL547',
       'x_fine_emb_MFXL350', 'x_fine_emb_MFXL367', 'x_fine_emb_MFXL742',
       'x_fine_emb_MFXL437'],
      dtype='object', length=500)
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.200678 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 500
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.148841 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 500
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.139655 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127500
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 500
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.189914 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127500
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 500
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.158020 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 127500
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 500
[LightGBM] [Info] Start training from score -5.729056
0.6752323561517093
0.6220373896281799
0.6751883739727296
0.6696317808664031
0.6311315392794533
0.6750004135979759
0.678046511779934
0.6653715095254072
0.6582463307987854
0.6712437947337282
0.5695343773485667

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1316,0.2627,0.3628,0.7886,0.8881,0.8689,0.2065,0.3257,0.4544,0.6752,0.8220,0.8030
DecisionTreeRegressor,0.2685,0.3755,0.5182,0.5688,0.7884,0.7585,0.2403,0.3471,0.4902,0.6220,0.7936,0.7700
RandomForestRegressor,0.1330,0.2657,0.3647,0.7864,0.8869,0.8665,0.2065,0.3234,0.4544,0.6752,0.8218,0.8033
GradientBoostingRegressor,0.1330,0.2654,0.3647,0.7864,0.8868,0.8658,0.2100,0.3287,0.4583,0.6696,0.8187,0.7959
AdaBoostRegressor,0.1656,0.3175,0.4070,0.7340,0.8666,0.8422,0.2345,0.3705,0.4843,0.6311,0.8019,0.7790
XGBRegressor,0.1509,0.2844,0.3884,0.7577,0.8716,0.8506,0.2066,0.3227,0.4546,0.6750,0.8222,0.8050
ExtraTreesRegressor,0.1336,0.2659,0.3655,0.7854,0.8863,0.8665,0.2047,0.3209,0.4524,0.6780,0.8236,0.8068
LinearRegression,0.1351,0.2727,0.3676,0.7830,0.8852,0.8627,0.2127,0.3348,0.4612,0.6654,0.8164,0.7932
KNeighborsRegressor,0.1714,0.3010,0.4140,0.7247,0.8539,0.8278,0.2173,0.3349,0.4661,0.6582,0.8138,0.7974
SVR,0.1361,0.2665,0.3689,0.7814,0.8841,0.8666,0.2090,0.3245,0.4572,0.6712,0.8197,0.8026
MLPRegressor,0.2382,0.3630,0.4881,0.6174,0.8216,0.7927,0.2737,0.3751,0.5231,0.5695,0.7766,0.7493

In [26]:
result_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/combined_top_500_features_pampa.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/combined_features/prediction_data_combined_top_500_features_pampa.csv')