In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression  # LogisticRegression is not used for regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from scipy.stats import pearsonr, spearmanr
from sklearn.model_selection import train_test_split
from tqdm import tqdm

In [3]:
def remove_low_variance_columns(df, threshold=0.01):
    variances = df.var()
    
    # Identify columns with variance below the threshold
    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

In [4]:
def features(df, target_column='Permeability', threshold=0.9):
    correlation_matrix = df.corr()
    
    features_to_drop = set()
    
    for feature in correlation_matrix.columns:
        if feature == target_column:
            continue 
        target_corr = correlation_matrix[target_column][feature]
        
        for other_feature in correlation_matrix.columns:
            if other_feature == feature or other_feature == target_column:
                continue
            
            if abs(correlation_matrix[feature][other_feature]) > threshold:
                other_target_corr = correlation_matrix[target_column][other_feature]

                if abs(other_target_corr) < abs(target_corr):
                    features_to_drop.add(other_feature)
                else:
                    features_to_drop.add(feature)
    selected_features = [col for col in df.columns if col not in features_to_drop and col != target_column]
    
    return selected_features

In [7]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]


#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    DecisionTreeRegressor(random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=42)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\427161072.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\427161072.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 242)
(1392, 242)
(5568, 662)
(1392, 662)
(5568, 770)
(1392, 770)
(5568, 11)
(1392, 11)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...     TDB10s      RNCS    LOBMAX    LOBMIN  \
4765  3.524800    2.105859  ...  21.926720  4.059403  1.229311  1.116345
4772  3.524800    2.105859  ...  21.182247  2.430700  1.301900  1.013546
4766  3.524800    2.105859  ...  21.728716  2.379031  1.318982  1.318982
4767  3.524800    2.105859  ...  20.981887  2.392510  1.171389  1.057402
4585  3.555194    2.111795  ...  21.124408  1.876242  1.482892  1.461695
...        ...         ...  ...        ...       ...       ...       ...
607   3.466151    4.234460  ...  21.040312  0.625185  1.354079  1.354079
726   4.111830    1.340817  ...  21.430905  1.277461  1.176213  1.033796
772   4.065966    1.511740  ...  21.631850  0.778508  1.247251  1.204229
5468  3.609789    1.643135  ...  22.540737  0.000000  1.360702  1.170716
5397  3.023866    2.051939  ...  25.872538  0.919946  1.936361  1.704628

       MOMI-XY   MOMI-XZ  geomShape     RDF55p        Dv       L3p
4765  1.445284  1.926076   0.832252  35.580478  1.216361  2.697051
4772  1.331807  2.032731   0.905135  38.960678  0.913940  3.825470
4766  1.416716  2.219593   0.765706  32.692290  1.189531  2.451943
4767  1.316650  1.782627   0.859830  40.512780  0.988930  3.888022
4585  1.319991  2.485087   0.833525  44.236785  0.992478  2.726084
...        ...       ...        ...        ...       ...       ...
607   1.385853  2.461352   0.782432  76.013922  1.272322  3.465821
726   1.547430  2.194043   0.829074  68.967821  1.033432  2.674361
772   1.549481  2.180596   0.904516  48.286030  1.120753  2.906278
5468  1.386263  2.127293   0.920917  22.088272  1.076762  2.195044
5397  1.082969  3.011435   0.901215  34.586426  0.989737  2.917641

[5568 rows x 242 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...     TDB10s      RNCS    LOBMAX    LOBMIN  \
1192  3.524800    2.105859  ...  21.477849  2.419467  1.150893  1.015666
1145  3.555194    2.111795  ...  21.276519  1.758568  1.242915  1.241792
841   3.969702    1.549820  ...  23.115664  1.571209  1.199839  1.008213
1146  3.555194    2.111795  ...  21.345639  1.928541  1.208494  1.074378
755   3.862771    1.798149  ...  22.573648  1.689117  1.206602  1.156762
...        ...         ...  ...        ...       ...       ...       ...
1147  3.547997    2.146757  ...  21.152466  2.299245  1.067795  1.010859
174   4.118337    1.352048  ...  21.778211  1.384929  1.235104  1.200599
1193  3.524800    2.105859  ...  20.762676  2.405988  1.084460  1.007445
122   1.621178    4.382718  ...  21.820139  1.176240  1.101137  1.084997
201   4.060393    1.513753  ...  22.213764  0.688547  1.111835  1.004241

       MOMI-XY   MOMI-XZ  geomShape     RDF55p        Dv       L3p
1192  1.562053  2.133614   0.745882  39.414328  1.128459  1.562507
1145  1.325082  2.043220   0.787200  39.934832  1.215016  3.482162
841   1.565738  2.209992   0.690480  48.632791  1.036948  1.689512
1146  1.526981  2.079398   0.771384  40.759570  0.991921  2.430374
755   1.543384  2.231920   0.757646  46.517665  1.042262  1.866171
...        ...       ...        ...        ...       ...       ...
1147  1.466799  1.765983   0.714699  46.871562  1.109375  3.498353
174   1.633772  1.833436   0.859816  57.763793  1.233429  4.228185
1193  1.542899  1.729313   0.818768  42.734317  0.977114  2.536672
122   1.412328  1.886035   0.491025  81.795576  1.361869  6.133363
201   1.721602  2.033337   0.832274  50.640449  1.047451  2.011146

[1392 rows x 242 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFP101  SubFP287  SubFPC2  SubFPC100  \
4765             0             0  ...         0         0      7.0        0.0
4772             0             0  ...         0         0      7.0        0.0
4766             0             0  ...         0         0      7.0        0.0
4767             0             0  ...         0         0      7.0        0.0
4585             0             0  ...         0         0      7.0        0.0
...            ...           ...  ...       ...       ...      ...        ...
607              0             0  ...         0         0      7.0        0.0
726              0             0  ...         0         0     22.0        0.0
772              0             0  ...         0         0     18.0        0.0
5468             0             0  ...         0         0      5.0        0.0
5397             0             0  ...         0         0      6.0        0.0

      SubFPC101  SubFPC127  SubFPC137  SubFPC182  SubFPC275  SubFPC302
4765        0.0        6.0        0.0        0.0        6.0       10.0
4772        0.0        6.0        0.0        0.0        6.0       10.0
4766        0.0        6.0        0.0        0.0        6.0       10.0
4767        0.0        6.0        0.0        0.0        6.0       10.0
4585        0.0        6.0        0.0        0.0        6.0       11.0
...         ...        ...        ...        ...        ...        ...
607         0.0       11.0        0.0        0.0       11.0       14.0
726         0.0        6.0        0.0        0.0       12.0        9.0
772         0.0        6.0        0.0        0.0       12.0       10.0
5468        0.0        2.0        0.0        1.0        8.0        5.0
5397        0.0        5.0        0.0        0.0        5.0       11.0

[5568 rows x 662 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFP101  SubFP287  SubFPC2  SubFPC100  \
1192             0             0  ...         0         0      7.0        0.0
1145             0             0  ...         0         0      7.0        0.0
841              0             0  ...         0         0     10.0        0.0
1146             0             0  ...         0         0      7.0        0.0
755              0             0  ...         0         0      9.0        0.0
...            ...           ...  ...       ...       ...      ...        ...
1147             0             0  ...         0         0      7.0        0.0
174              0             0  ...         0         0     21.0        0.0
1193             0             0  ...         0         0      7.0        0.0
122              0             0  ...         0         0     10.0        0.0
201              0             0  ...         0         0     17.0        0.0

      SubFPC101  SubFPC127  SubFPC137  SubFPC182  SubFPC275  SubFPC302
1192        0.0        6.0        0.0        0.0        6.0       10.0
1145        0.0        6.0        0.0        0.0        6.0       11.0
841         0.0        7.0        0.0        0.0        7.0        9.0
1146        0.0        6.0        0.0        0.0        6.0       11.0
755         0.0        7.0        0.0        0.0        7.0       11.0
...         ...        ...        ...        ...        ...        ...
1147        0.0        6.0        0.0        0.0        6.0       10.0
174         0.0        6.0        0.0        0.0       12.0        9.0
1193        0.0        6.0        0.0        0.0        6.0       10.0
122         0.0       11.0        0.0        0.0       11.0       18.0
201         0.0        6.0        0.0        0.0       12.0        9.0

[1392 rows x 662 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL5  x_fine_emb_MFXL6  x_fine_emb_MFXL7  ...  \
4765         -0.339157         -0.094716         -0.133514  ...
4772         -0.351874         -0.149570          0.192562  ...
4766         -0.147806         -0.181123          0.291289  ...
4767         -0.332812         -0.083156         -0.136583  ...
4585         -0.313935          0.076244         -0.186443  ...
...                ...               ...               ...  ...
607          -0.428047         -0.057039         -0.544092  ...
726           0.091023          0.073532         -0.066729  ...
772           0.078197          0.078757         -0.059384  ...
5468         -0.432866          0.220133         -0.797908  ...
5397         -0.356712          0.010048          0.278202  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613
...                  ...                 ...                 ...
607            -1.573230           -0.602913            0.695327
726            -1.956501           -0.880823            0.291396
772            -1.988949           -0.906367            0.335933
5468           -1.508068           -0.433091            0.609673
5397           -2.484966           -0.806733            0.208965

      x_fine_emb_MFXL767

In [8]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006217 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50454
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 234
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005590 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50463
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 234
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005160 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50477
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 234
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006678 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50459
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 234
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007181 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 50466
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 235
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [03:49, 28.63s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:49<11:27, 229.07s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007771 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2165
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 650
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004606 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2179
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 652
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007346 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2180
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 651
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004469 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2182
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 653
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005689 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2170
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 651
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:29, 18.67s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:18<06:04, 182.19s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.036922 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195585
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 767
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034890 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195585
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 767
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042207 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195585
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 767
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.035415 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195585
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 767
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.044314 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195585
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 767
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [20:21, 152.69s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [26:40<10:56, 656.79s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000140 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 143
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 8
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000096 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 8
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000162 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 141
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 8
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000124 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 141
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 8
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000109 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 142
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 8
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [00:10,  1.37s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [26:51<00:00, 402.75s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000810 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7944
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001002 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7934
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.749693

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000835 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7945
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000839 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7937
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.739382

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001065 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7934
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.738471
LGBMRegressor Evaluation completed: Test R2 score: 0.6674620770137487
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6061789443348841
RandomForestRegressor Evaluation completed: Test R2 score: 0.6594759331851443
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6694396915150453
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6326070551865912
XGBRegressor Evaluation completed: Test R2 score: 0.6603229592333578
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6633507443399618
LinearRegression Evaluation completed: Test R2 score: 0.6654166430468198
KNeighborsRegressor Evaluation completed: Test R2 score: 0.660647360480358
SVR Evaluation completed: Test R2 score: 0.6632181183327327
MLPRegressor Evaluation completed: Test R2 score: 0.6620285296735369

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.139854,0.274897,0.373971,0.775446,0.880600,0.857633,0.210439,0.324723,0.458737,0.667462,0.817593,0.799203
DecisionTreeRegressor,0.278683,0.389184,0.527904,0.552539,0.779151,0.748681,0.249221,0.358376,0.499221,0.606179,0.783021,0.762477
RandomForestRegressor,0.141212,0.274568,0.375782,0.773265,0.879415,0.856509,0.215493,0.328771,0.464213,0.659476,0.812712,0.793090
GradientBoostingRegressor,0.140850,0.276621,0.375300,0.773846,0.879750,0.858143,0.209188,0.324902,0.457371,0.669440,0.819029,0.799242
AdaBoostRegressor,0.185896,0.336574,0.431157,0.701519,0.854756,0.836498,0.232497,0.368584,0.482179,0.632607,0.809397,0.794546
XGBRegressor,0.157700,0.292415,0.397114,0.746793,0.865213,0.839843,0.214957,0.327760,0.463635,0.660323,0.813823,0.795251
ExtraTreesRegressor,0.140210,0.274267,0.374447,0.774874,0.880364,0.857029,0.213041,0.326172,0.461564,0.663351,0.814998,0.796188
LinearRegression,0.137706,0.271505,0.371088,0.778895,0.882557,0.858014,0.211734,0.326595,0.460145,0.665417,0.816148,0.798344
KNeighborsRegressor,0.160528,0.294167,0.400660,0.742251,0.861833,0.836248,0.214752,0.328740,0.463413,0.660647,0.813544,0.799016
SVR,0.144804,0.275743,0.380531,0.767499,0.876465,0.855489,0.213125,0.322923,0.461655,0.663218,0.816445,0.801944
MLPRegressor,0.146585,0.284991,0.382865,0.764638,0.875691,0.849925,0.213878,0.331566,0.462469,0.662029,0.814482,0.796865

In [9]:
prediction_df

,Model,Y Train pred,Y Test actual,Test prediction folds,Test Predictions Mean,Test Predictions Std
0,LGBMRegressor,"[-6.801526954630438, -5.162059182414915, -4.73...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.072831052393405, -6.984510282640211, -6.9...","[-7.041278060857093, -6.974839340760829, -7.01...","[0.04579768593261748, 0.06206531342613228, 0.0..."
1,DecisionTreeRegressor,"[-7.2, -5.28, -4.74, -4.59, -5.28, -6.36, -4.7...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.3, -6.47, -7.254760117, -6.23, -6.7, -4.2...","[-7.212901910800001, -7.2920144396, -7.0765113...","[0.09042727027501542, 0.6167456740707313, 0.22..."
2,RandomForestRegressor,"[-6.7484403834, -5.092300000000002, -4.6213000...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.095568848140001, -7.018527983524998, -7.1...","[-7.084956050285001, -7.062435776778, -7.11853...","[0.02387141535452694, 0.10001653008701361, 0.0..."
3,GradientBoostingRegressor,"[-6.767274073204197, -5.175848727111651, -4.51...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.984314672140103, -6.928329462894377, -7.0...","[-7.018147100190548, -6.946825753246107, -7.00...","[0.03446280968686167, 0.0904489465441728, 0.08..."
4,AdaBoostRegressor,"[-6.785536489173845, -5.322483024353474, -5.16...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.971554916278127, -6.934259241460626, -6.9...","[-6.904518333974252, -6.841106016939415, -6.91...","[0.1307640680127278, 0.12425766732244001, 0.12..."
5,XGBRegressor,"[-6.623746, -5.218319, -4.649134, -4.503969, -...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.254066, -6.8700514, -7.1008883, -6.704618...","[-7.149386, -7.0257607, -7.01859, -6.5788026, ...","[0.06717497, 0.16027357, 0.11415545, 0.1459433..."
6,ExtraTreesRegressor,"[-6.807464970749999, -5.180950000000003, -4.63...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.020395683450002, -7.040681547650001, -7.0...","[-7.070601131871003, -7.107678958256999, -7.10...","[0.0335619394950426, 0.082417698425587, 0.0601..."
7,LinearRegression,"[-6.770045375305667, -4.997317743447743, -4.80...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.966196462172827, -6.9488433382903985, -7....","[-6.973659364686716, -6.940298677778053, -7.10...","[0.02241823790282409, 0.02224682082457343, 0.0..."
8,KNeighborsRegressor,"[-6.8000705457, -5.21, -4.448, -4.642, -5.426,...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.976000000000001, -7.064, -7.022, -6.66999...","[-6.9388000000000005, -6.825999999999999, -7.0...","[0.09208344042226099, 0.12608568515101162, 0.0..."
9,SVR,"[-6.710076953172685, -5.199172857841371, -4.68...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.021410054941192, -7.066902727675867, -7.1...","[-6.995210759537974, -7.051373087140398, -7.07...","[0.03983578728153767, 0.043624102868411105, 0...."
10,MLPRegressor,"[-6.739294677977655, -4.978817260094323, -4.87...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.173131498143659, -6.952258384022558, -6.9...","[-7.1389384210613684, -6.8983020973174645, -6....","[0.024597005908330093, 0.035623400536682455, 0..."

In [10]:
results_df.to_csv('stacked_model_results/Results_5_fold_stacked_prediction_LVR_threshold_0.01.csv')
prediction_df.to_csv('stacked_model_results/Prediction_data_Meta_learners_5_fold_stacked_prediction_LVR_threshold_0.01.csv')

In [3]:
def remove_low_variance_columns(df, threshold=0.005):
    # df = df.drop(['ID','SMILES','Permeability'],axis=1)
    variances = df.var()
    
    # Identify columns with variance below the threshold
    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

In [12]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    DecisionTreeRegressor(random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=42)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2263795127.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2263795127.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 271)
(1392, 271)
(5568, 822)
(1392, 822)
(5568, 771)
(1392, 771)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765  3.524800    2.105859  ...  4.059403  1.229311  1.116345  1.445284
4772  3.524800    2.105859  ...  2.430700  1.301900  1.013546  1.331807
4766  3.524800    2.105859  ...  2.379031  1.318982  1.318982  1.416716
4767  3.524800    2.105859  ...  2.392510  1.171389  1.057402  1.316650
4585  3.555194    2.111795  ...  1.876242  1.482892  1.461695  1.319991
...        ...         ...  ...       ...       ...       ...       ...
607   3.466151    4.234460  ...  0.625185  1.354079  1.354079  1.385853
726   4.111830    1.340817  ...  1.277461  1.176213  1.033796  1.547430
772   4.065966    1.511740  ...  0.778508  1.247251  1.204229  1.549481
5468  3.609789    1.643135  ...  0.000000  1.360702  1.170716  1.386263
5397  3.023866    2.051939  ...  0.919946  1.936361  1.704628  1.082969

      geomShape     RDF55p       P1m        Dv       L3p        Ki
4765   0.832252  35.580478  0.532075  1.216361  2.697051  0.361574
4772   0.905135  38.960678  0.562820  0.913940  3.825470  0.285387
4766   0.765706  32.692290  0.579772  1.189531  2.451943  0.374559
4767   0.859830  40.512780  0.517578  0.988930  3.888022  0.269237
4585   0.833525  44.236785  0.627460  0.992478  2.726084  0.375665
...         ...        ...       ...       ...       ...       ...
607    0.782432  76.013922  0.618173  1.272322  3.465821  0.407764
726    0.829074  68.967821  0.566761  1.033432  2.674361  0.411379
772    0.904516  48.286030  0.563706  1.120753  2.906278  0.407451
5468   0.920917  22.088272  0.570890  1.076762  2.195044  0.395831
5397   0.901215  34.586426  0.705175  0.989737  2.917641  0.539314

[5568 rows x 271 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192  3.524800    2.105859  ...  2.419467  1.150893  1.015666  1.562053
1145  3.555194    2.111795  ...  1.758568  1.242915  1.241792  1.325082
841   3.969702    1.549820  ...  1.571209  1.199839  1.008213  1.565738
1146  3.555194    2.111795  ...  1.928541  1.208494  1.074378  1.526981
755   3.862771    1.798149  ...  1.689117  1.206602  1.156762  1.543384
...        ...         ...  ...       ...       ...       ...       ...
1147  3.547997    2.146757  ...  2.299245  1.067795  1.010859  1.466799
174   4.118337    1.352048  ...  1.384929  1.235104  1.200599  1.633772
1193  3.524800    2.105859  ...  2.405988  1.084460  1.007445  1.542899
122   1.621178    4.382718  ...  1.176240  1.101137  1.084997  1.412328
201   4.060393    1.513753  ...  0.688547  1.111835  1.004241  1.721602

      geomShape     RDF55p       P1m        Dv       L3p        Ki
1192   0.745882  39.414328  0.557076  1.128459  1.562507  0.408108
1145   0.787200  39.934832  0.560880  1.215016  3.482162  0.351511
841    0.690480  48.632791  0.567719  1.036948  1.689512  0.421941
1146   0.771384  40.759570  0.551536  0.991921  2.430374  0.378168
755    0.757646  46.517665  0.572634  1.042262  1.866171  0.415839
...         ...        ...       ...       ...       ...       ...
1147   0.714699  46.871562  0.497007  1.109375  3.498353  0.315953
174    0.859816  57.763793  0.494014  1.233429  4.228185  0.368291
1193   0.818768  42.734317  0.477615  0.977114  2.536672  0.355842
122    0.491025  81.795576  0.526458  1.361869  6.133363  0.314560
201    0.832274  50.640449  0.526102  1.047451  2.011146  0.432148

[1392 rows x 271 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 822 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
1192             0             0  ...      7.0        0.0        0.0
1145             0             0  ...      7.0        0.0        0.0
841              0             0  ...     10.0        0.0        0.0
1146             0             0  ...      7.0        0.0        0.0
755              0             0  ...      9.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
1147             0             0  ...      7.0        0.0        0.0
174              0             0  ...     21.0        0.0        0.0
1193             0             0  ...      7.0        0.0        0.0
122              0             0  ...     10.0        0.0        0.0
201              0             0  ...     17.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192        6.0        0.0        0.0        0.0        0.0        6.0
1145        6.0        0.0        0.0        0.0        0.0        6.0
841         7.0        0.0        0.0        0.0        0.0        7.0
1146        6.0        0.0        0.0        0.0        0.0        6.0
755         7.0        0.0        0.0        0.0        0.0        7.0
...         ...        ...        ...        ...        ...        ...
1147        6.0        0.0        0.0        0.0        0.0        6.0
174         6.0        0.0        0.0        0.0        0.0       12.0
1193        6.0        0.0        0.0        0.0        0.0        6.0
122        11.0        0.0        0.0        0.0        0.0       11.0
201         6.0        0.0        0.0        0.0        0.0       12.0

      SubFPC302
1192       10.0
1145       11.0
841         9.0
1146       11.0
755        11.0
...         ...
1147       10.0
174         9.0
1193       10.0
122        18.0
201         9.0

[1392 rows x 822 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -0.832013         -0.339157         -0.094716  ...
4772         -0.605726         -0.351874         -0.149570  ...
4766         -0.614279         -0.147806         -0.181123  ...
4767         -0.812609         -0.332812         -0.083156  ...
4585         -0.700132         -0.313935          0.076244  ...
...                ...               ...               ...  ...
607          -0.384116         -0.428047         -0.057039  ...
726          -0.483824          0.091023          0.073532  ...
772          -0.510908          0.078197          0.078757  ...
5468         -0.638301         -0.432866          0.220133  ...
5397         -1.021350         -0.356712          0.010048  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613
...                  ...                 ...                 ...
607            -1.573230           -0.602913            0.695327
726            -1.956501           -0.880823            0.291396
772            -1.988949           -0.906367            0.335933

In [13]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008716 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56780
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007546 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56791
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006947 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56820
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007378 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56796
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 261
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007404 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56811
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [03:57, 29.71s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:57<11:53, 237.69s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009610 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2441
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 790
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008898 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2459
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 795
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008751 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2447
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 792
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:55, 21.95s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:53<06:42, 201.18s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037323 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032683 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033306 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.036855 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.036468 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [19:43, 147.95s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [26:36<10:49, 649.78s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000137 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 146
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000147 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000130 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000158 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000131 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [00:10,  1.34s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [26:47<00:00, 401.92s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000983 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7919
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000846 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7935
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.749693

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000905 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7934
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000913 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7919
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.739382

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000914 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7929
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.738471
LGBMRegressor Evaluation completed: Test R2 score: 0.6684171758183655
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.5978841083168853
RandomForestRegressor Evaluation completed: Test R2 score: 0.6615153933513593
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6680555754585535
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6324661237909459
XGBRegressor Evaluation completed: Test R2 score: 0.6586411972859053
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6623618757849025
LinearRegression Evaluation completed: Test R2 score: 0.6638094085973403
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6519527934854233
SVR Evaluation completed: Test R2 score: 0.6679020469217163
MLPRegressor Evaluation completed: Test R2 score: 0.660545957826105

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.139745,0.274583,0.373825,0.775621,0.880708,0.856912,0.209835,0.324513,0.458078,0.668417,0.818049,0.799935
DecisionTreeRegressor,0.281398,0.388952,0.530470,0.548178,0.775030,0.744182,0.254470,0.357805,0.504451,0.597884,0.778785,0.760954
RandomForestRegressor,0.141247,0.274424,0.375828,0.773210,0.879417,0.855421,0.214203,0.327352,0.462820,0.661515,0.813957,0.794501
GradientBoostingRegressor,0.139735,0.274066,0.373811,0.775638,0.880736,0.858013,0.210064,0.325267,0.458327,0.668056,0.817903,0.796955
AdaBoostRegressor,0.181188,0.331789,0.425662,0.709079,0.857276,0.832995,0.232586,0.367542,0.482272,0.632466,0.807855,0.789139
XGBRegressor,0.158213,0.293673,0.397761,0.745968,0.865040,0.840928,0.216022,0.329144,0.464781,0.658641,0.813345,0.793889
ExtraTreesRegressor,0.141634,0.275451,0.376342,0.772589,0.879105,0.855422,0.213667,0.326192,0.462241,0.662362,0.814439,0.796968
LinearRegression,0.137465,0.271652,0.370763,0.779282,0.882778,0.858343,0.212751,0.326704,0.461249,0.663809,0.815182,0.798591
KNeighborsRegressor,0.159373,0.293667,0.399215,0.744106,0.862909,0.838440,0.220254,0.334148,0.469312,0.651953,0.808250,0.792420
SVR,0.144693,0.275405,0.380385,0.767677,0.876506,0.856146,0.210161,0.320793,0.458433,0.667902,0.819060,0.804430
MLPRegressor,0.153671,0.293999,0.392009,0.753261,0.870703,0.845275,0.214816,0.333251,0.463483,0.660546,0.814418,0.797123

In [14]:
prediction_df

,Model,Y Train pred,Y Test actual,Test prediction folds,Test Predictions Mean,Test Predictions Std
0,LGBMRegressor,"[-6.765410736512545, -5.17373976745991, -4.724...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.058699665572529, -7.024150456166168, -7.0...","[-7.031372855092568, -6.960245638216368, -7.11...","[0.03256454945200799, 0.05878934532034309, 0.0..."
1,DecisionTreeRegressor,"[-7.529999999999999, -4.55, -5.14, -4.15, -5.4...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.0, -6.61, -6.9, -6.61, -6.73, -4.46, -4.6...","[-6.8185626118, -6.736, -7.077011879599999, -6...","[0.2502473331380224, 0.4290734202907469, 0.326..."
2,RandomForestRegressor,"[-6.72073436633, -5.449550000000003, -4.649300...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.047494311150001, -6.945573735795, -7.0573...","[-7.058796266393999, -6.939987815947001, -7.09...","[0.023183449891602818, 0.03671315445134553, 0...."
3,GradientBoostingRegressor,"[-6.68130763119159, -5.012235931756559, -4.626...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.9468783171576, -6.880417580554255, -7.059...","[-6.992936523966347, -6.953255766503733, -7.06...","[0.032196318875915265, 0.06696835257800869, 0...."
4,AdaBoostRegressor,"[-6.6801359140313, -5.158220742150339, -5.0926...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.801135622192467, -6.801135622192467, -6.8...","[-6.908168958132781, -6.923272908719698, -6.91...","[0.106520762966616, 0.08784525894345581, 0.093..."
5,XGBRegressor,"[-6.5757294, -5.332572, -4.367157, -4.37689, -...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.268792, -6.6970787, -6.892537, -6.5415998...","[-7.0839906, -6.764984, -7.1242037, -6.5782976...","[0.10336285, 0.09645266, 0.17053583, 0.0864135..."
6,ExtraTreesRegressor,"[-6.790998577689996, -5.292499999999999, -4.59...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.04922318597, -6.911453657940001, -7.09256...","[-7.071630200078, -6.978934482788001, -7.12286...","[0.028186096399063925, 0.05550427154844899, 0...."
7,LinearRegression,"[-6.777645375904114, -4.942439391180375, -4.83...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.979163490914826, -6.945240333073956, -7.1...","[-7.001224704607859, -6.938660133428563, -7.13...","[0.025838593987611996, 0.027681807185243264, 0..."
8,KNeighborsRegressor,"[-6.656000000000001, -5.132, -4.60199999999999...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.976000000000001, -7.064, -7.022, -6.514, ...","[-7.0588, -6.8584000000000005, -7.0084, -6.668...","[0.12702503690217928, 0.10499828570029157, 0.0..."
9,SVR,"[-6.741068672572704, -5.145326430853023, -4.65...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.031084699270954, -7.130533886006942, -7.0...","[-7.002555564701095, -7.078713079738277, -7.05...","[0.018251148376883446, 0.0553196618692776, 0.0..."
10,MLPRegressor,"[-6.58862587600732, -4.832667228011261, -4.744...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.052449061840125, -6.829225273961191, -6.7...","[-7.177082808643837, -6.941640266723394, -6.87...","[0.09135824046442757, 0.08757843399580828, 0.0..."

In [15]:
results_df.to_csv('stacked_model_results/Results_5_fold_stacked_prediction_LVR_threshold_0.005.csv')
prediction_df.to_csv('stacked_model_results/Prediction_data_Meta_learners_5_fold_stacked_prediction_LVR_threshold_0.005.csv')

In [5]:
#Removal of constant columns
def remove_constant_columns(df):
    # Identify columns with only one unique value
    constant_columns = [col for col in df.columns if df[col].nunique() <= 1]
    
    # Drop the constant columns from the DataFrame
    df_cleaned = df.drop(columns=constant_columns)
    
    return df_cleaned, constant_columns

In [17]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_constant_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_constant_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_constant_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_constant_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    DecisionTreeRegressor(random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=42)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\3142377301.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\3142377301.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 403)
(1392, 403)
(5568, 1090)
(1392, 1090)
(5568, 771)
(1392, 771)
(5568, 17)
(1392, 17)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinAbsEStateIndex  MinEStateIndex       qed        SPS  \
4765           0.000719       -1.126245  0.215270  26.000000
4772           0.000719       -1.126245  0.215270  26.000000
4766           0.000719       -1.126245  0.215270  26.000000
4767           0.000719       -1.126245  0.215270  26.000000
4585           0.001050       -1.057909  0.233167  25.673077
...                 ...             ...       ...        ...
607            0.109276       -1.208204  0.194882  26.621951
726            0.000939       -1.044795  0.274599  29.051282
772            0.007321       -1.052167  0.264032  28.118421
5468           0.108635       -0.845231  0.429454  25.300000
5397           0.016990       -1.583104  0.118757  23.086957

      MinPartialCharge  FpDensityMorgan1  BCUT2D_MWHI  ...       E3u  \
4765         -0.507967          0.568627    16.254973  ...  0.384468
4772         -0.507967          0.568627    16.254973  ...  0.363884
4766         -0.507967          0.568627    16.254973  ...  0.417246
4767         -0.507967          0.568627    16.254973  ...  0.336796
4585         -0.496768          0.576923    16.465390  ...  0.328724
...                ...               ...          ...  ...       ...
607          -0.342808          0.378049    16.190089  ...  0.417051
726          -0.342506          0.564103    16.183951  ...  0.379420
772          -0.342677          0.552632    16.183876  ...  0.301777
5468         -0.421286          0.925000    16.366728  ...  0.377386
5397         -0.507967          0.630435    16.257835  ...  0.292699

           E1m       E2m       E3m       E1v        Dv       L3p       P1p  \
4765  0.385306  0.326881  0.321215  0.426540  1.216361  2.697051  0.508527
4772  0.320926  0.255099  0.141204  0.347922  0.913940  3.825470  0.518559
4766  0.375022  0.366043  0.179855  0.467523  1.189531  2.451943  0.579364
4767  0.372599  0.252943  0.205958  0.395699  0.988930  3.888022  0.486885
4585  0.318760  0.296803  0.145291  0.363977  0.992478  2.726084  0.596468
...        ...       ...       ...       ...       ...       ...       ...
607   0.412592  0.420969  0.219779  0.480090  1.272322  3.465821  0.611225
726   0.345309  0.325917  0.202371  0.386265  1.033432  2.674361  0.561660
772   0.380091  0.368999  0.139542  0.452848  1.120753  2.906278  0.552756
5468  0.275277  0.391544  0.184883  0.377092  1.076762  2.195044  0.594093
5397  0.328737  0.358318  0.219011  0.352654  0.989737  2.917641  0.699981

           E3p        Ki
4765  0.338452  0.361574
4772  0.285933  0.285387
4766  0.332276  0.374559
4767  0.276795  0.269237
4585  0.256491  0.375665
...        ...       ...
607   0.339449  0.407764
726   0.304160  0.411379
772   0.236552  0.407451
5468  0.293743  0.395831
5397  0.268400  0.539314

[5568 rows x 403 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinAbsEStateIndex  MinEStateIndex       qed        SPS  \
1192           0.000719       -1.126245  0.215270  26.000000
1145           0.001050       -1.057909  0.233167  25.673077
841            0.014413       -1.090876  0.292940  28.206897
1146           0.001050       -1.057909  0.233167  25.673077
755            0.004529       -1.109218  0.224862  26.932203
...                 ...             ...       ...        ...
1147           0.005302       -1.125961  0.246302  25.942308
174            0.000274       -1.049404  0.271350  28.911392
1193           0.000719       -1.126245  0.215270  26.000000
122            0.088068       -1.456022  0.132042  25.724138
201            0.007033       -1.050097  0.279880  28.333333

      MinPartialCharge  FpDensityMorgan1  BCUT2D_MWHI  ...       E3u  \
1192         -0.507967          0.568627    16.254973  ...  0.431888
1145         -0.496768          0.576923    16.465390  ...  0.451932
841          -0.496768          0.517241    16.465422  ...  0.367907
1146         -0.496768          0.576923    16.465390  ...  0.360977
755          -0.496768          0.508475    16.465419  ...  0.330322
...                ...               ...          ...  ...       ...
1147         -0.507967          0.615385    16.254985  ...  0.434720
174          -0.342506          0.518987    16.183972  ...  0.331621
1193         -0.507967          0.568627    16.254973  ...  0.343061
122          -0.369679          0.413793    16.191299  ...  0.405730
201          -0.342677          0.586667    16.183920  ...  0.394386

           E1m       E2m       E3m       E1v        Dv       L3p       P1p  \
1192  0.434797  0.282876  0.229758  0.464788  1.128459  1.562507  0.515823
1145  0.359757  0.362726  0.253348  0.441882  1.215016  3.482162  0.564136
841   0.364424  0.286336  0.176934  0.433672  1.036948  1.689512  0.548595
1146  0.331459  0.284489  0.146320  0.380461  0.991921  2.430374  0.521264
755   0.363273  0.290288  0.168279  0.429246  1.042262  1.866171  0.548859
...        ...       ...       ...       ...       ...       ...       ...
1147  0.409372  0.322173  0.215358  0.435312  1.109375  3.498353  0.497056
174   0.360075  0.447365  0.167239  0.466340  1.233429  4.228185  0.506115
1193  0.305917  0.301600  0.252506  0.339640  0.977114  2.536672  0.495102
122   0.477753  0.434506  0.225154  0.565716  1.361869  6.133363  0.529865
201   0.383487  0.326944  0.186382  0.411712  1.047451  2.011146  0.516660

           E3p        Ki
1192  0.307108  0.408108
1145  0.370359  0.351511
841   0.255738  0.421941
1146  0.278956  0.378168
755   0.239232  0.415839
...        ...       ...
1147  0.362601  0.315953
174   0.281430  0.368291
1193  0.287738  0.355842
122   0.346890  0.314560
201   0.296589  0.432148

[1392 rows x 403 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_27  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_42  Morgan_fp_84  ...  SubFP137  SubFP287  SubFPC2  SubFPC100  \
4765             0             0  ...         0         0      7.0        0.0
4772             0             0  ...         0         0      7.0        0.0
4766             0             0  ...         0         0      7.0        0.0
4767             0             0  ...         0         0      7.0        0.0
4585             0             0  ...         0         0      7.0        0.0
...            ...           ...  ...       ...       ...      ...        ...
607              0             0  ...         0         0      7.0        0.0
726              0             0  ...         0         0     22.0        0.0
772              0             0  ...         0         0     18.0        0.0
5468             0             0  ...         0         0      5.0        0.0
5397             0             0  ...         0         0      6.0        0.0

      SubFPC101  SubFPC127  SubFPC137  SubFPC182  SubFPC275  SubFPC302
4765        0.0        6.0        0.0        0.0        6.0       10.0
4772        0.0        6.0        0.0        0.0        6.0       10.0
4766        0.0        6.0        0.0        0.0        6.0       10.0
4767        0.0        6.0        0.0        0.0        6.0       10.0
4585        0.0        6.0        0.0        0.0        6.0       11.0
...         ...        ...        ...        ...        ...        ...
607         0.0       11.0        0.0        0.0       11.0       14.0
726         0.0        6.0        0.0        0.0       12.0        9.0
772         0.0        6.0        0.0        0.0       12.0       10.0
5468        0.0        2.0        0.0        1.0        8.0        5.0
5397        0.0        5.0        0.0        0.0        5.0       11.0

[5568 rows x 1090 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_27  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_42  Morgan_fp_84  ...  SubFP137  SubFP287  SubFPC2  SubFPC100  \
1192             0             0  ...         0         0      7.0        0.0
1145             0             0  ...         0         0      7.0        0.0
841              0             0  ...         0         0     10.0        0.0
1146             0             0  ...         0         0      7.0        0.0
755              0             0  ...         0         0      9.0        0.0
...            ...           ...  ...       ...       ...      ...        ...
1147             0             0  ...         0         0      7.0        0.0
174              0             0  ...         0         0     21.0        0.0
1193             0             0  ...         0         0      7.0        0.0
122              0             0  ...         0         0     10.0        0.0
201              0             0  ...         0         0     17.0        0.0

      SubFPC101  SubFPC127  SubFPC137  SubFPC182  SubFPC275  SubFPC302
1192        0.0        6.0        0.0        0.0        6.0       10.0
1145        0.0        6.0        0.0        0.0        6.0       11.0
841         0.0        7.0        0.0        0.0        7.0        9.0
1146        0.0        6.0        0.0        0.0        6.0       11.0
755         0.0        7.0        0.0        0.0        7.0       11.0
...         ...        ...        ...        ...        ...        ...
1147        0.0        6.0        0.0        0.0        6.0       10.0
174         0.0        6.0        0.0        0.0       12.0        9.0
1193        0.0        6.0        0.0        0.0        6.0       10.0
122         0.0       11.0        0.0        0.0       11.0       18.0
201         0.0        6.0        0.0        0.0       12.0        9.0

[1392 rows x 1090 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -0.832013         -0.339157         -0.094716  ...
4772         -0.605726         -0.351874         -0.149570  ...
4766         -0.614279         -0.147806         -0.181123  ...
4767         -0.812609         -0.332812         -0.083156  ...
4585         -0.700132         -0.313935          0.076244  ...
...                ...               ...               ...  ...
607          -0.384116         -0.428047         -0.057039  ...
726          -0.483824          0.091023          0.073532  ...
772          -0.510908          0.078197          0.078757  ...
5468         -0.638301         -0.432866          0.220133  ...
5397         -1.021350         -0.356712          0.010048  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613

In [18]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 86852
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 380
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010022 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 86856
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 380
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008219 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 86881
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 381
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008746 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 86861
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 381
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010831 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 86877
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 381
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [06:03, 45.39s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [06:03<18:09, 363.11s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2449
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 795
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010214 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2477
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 805
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010601 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2488
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 809
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2486
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 811
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009267 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2480
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 809
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [03:47, 28.49s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [09:51<09:27, 283.60s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.029540 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.039703 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.030366 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023985 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037856 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [20:03, 150.43s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [29:54<11:43, 703.63s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000385 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 675
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 680
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000415 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 680
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.738190

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000325 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 678
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 13
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000340 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 683
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 13
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [00:13,  1.65s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [30:07<00:00, 451.94s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000906 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7973
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000958 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7996
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.749693

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000999 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8000
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001047 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7977
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.739382

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000899 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7992
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.738471
LGBMRegressor Evaluation completed: Test R2 score: 0.665436700060918
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6152501873580201
RandomForestRegressor Evaluation completed: Test R2 score: 0.6601993168057538
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6663080715584837
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6195659654121992
XGBRegressor Evaluation completed: Test R2 score: 0.6516450182526473
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6661521277437165
LinearRegression Evaluation completed: Test R2 score: 0.6659009370227114
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6492323915420297
SVR Evaluation completed: Test R2 score: 0.6626300671528192
MLPRegressor Evaluation completed: Test R2 score: 0.6607195612717602

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.139810,0.274027,0.373912,0.775517,0.880647,0.857904,0.211721,0.324476,0.460132,0.665437,0.816413,0.798018
DecisionTreeRegressor,0.292798,0.395851,0.541108,0.529875,0.771247,0.739405,0.243481,0.352277,0.493438,0.615250,0.788859,0.761424
RandomForestRegressor,0.141201,0.274068,0.375768,0.773283,0.879447,0.855262,0.215036,0.327180,0.463719,0.660199,0.813344,0.794178
GradientBoostingRegressor,0.140288,0.274725,0.374550,0.774750,0.880260,0.857670,0.211170,0.324823,0.459532,0.666308,0.817092,0.799007
AdaBoostRegressor,0.191353,0.343062,0.437439,0.692758,0.853451,0.838569,0.240749,0.375407,0.490662,0.619566,0.805327,0.792474
XGBRegressor,0.161855,0.294880,0.402312,0.740120,0.861531,0.835844,0.220449,0.328552,0.469520,0.651645,0.808978,0.792032
ExtraTreesRegressor,0.141798,0.274221,0.376561,0.772325,0.878898,0.854799,0.211268,0.324299,0.459639,0.666152,0.816816,0.798271
LinearRegression,0.137260,0.271781,0.370487,0.779610,0.882959,0.858601,0.211427,0.324707,0.459812,0.665901,0.816457,0.799886
KNeighborsRegressor,0.158868,0.291345,0.398583,0.744916,0.863486,0.838674,0.221976,0.335156,0.471143,0.649232,0.807131,0.793083
SVR,0.143235,0.275373,0.378464,0.770018,0.877829,0.856209,0.213497,0.322410,0.462058,0.662630,0.816007,0.800547
MLPRegressor,0.146872,0.282557,0.383239,0.764178,0.874562,0.848127,0.214706,0.329316,0.463364,0.660720,0.814218,0.796132

In [19]:
prediction_df

,Model,Y Train pred,Y Test actual,Test prediction folds,Test Predictions Mean,Test Predictions Std
0,LGBMRegressor,"[-6.695395446030172, -5.2150961799458075, -4.6...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.981199971451548, -7.041331776590298, -7.0...","[-7.0743653197894645, -6.966841546224238, -7.1...","[0.05558782617011785, 0.049071814403207556, 0...."
1,DecisionTreeRegressor,"[-6.89, -5.27, -4.36, -4.66, -5.27, -5.21, -4....",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-5.53, -5.982325082, -7.3, -5.94, -6.89, -4....","[-6.791342541400001, -6.524465016399999, -7.27...","[0.6575730740819933, 0.5169902582426569, 0.169..."
2,RandomForestRegressor,"[-6.765102223440001, -5.2427, -4.6605, -4.6095...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.975882285450002, -6.935207871950004, -7.2...","[-7.0573588132810015, -6.980032323169001, -7.1...","[0.046753006477858086, 0.041070063593657356, 0..."
3,GradientBoostingRegressor,"[-6.709281983049089, -5.101277482031761, -4.58...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.916891352116333, -7.001657244605822, -7.0...","[-6.985656393760567, -6.96774393600744, -7.049...","[0.04052744213622957, 0.05773735219155542, 0.0..."
4,AdaBoostRegressor,"[-6.642580980392171, -5.390149036401323, -5.28...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.7967930527161595, -6.8411134239295235, -6...","[-6.87541573672536, -6.887820059848851, -6.816...","[0.1253464613067351, 0.1279352393004953, 0.147..."
5,XGBRegressor,"[-6.654461, -5.130814, -4.562169, -4.6832523, ...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.224395, -6.804819, -7.0218506, -6.33964, ...","[-7.187168, -7.010213, -7.138907, -6.6160874, ...","[0.06792679, 0.11990352, 0.08942974, 0.1810198..."
6,ExtraTreesRegressor,"[-6.797732694089998, -5.206600000000001, -4.60...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.111098129000001, -6.869803653429998, -7.1...","[-7.083268748053999, -6.929409064232, -7.13663...","[0.03443546521944396, 0.05447419622134792, 0.0..."
7,LinearRegression,"[-6.738437615693694, -4.937034633378797, -4.83...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.9519183282780945, -6.915319323174992, -7....","[-6.962264166908211, -6.911695176279918, -7.08...","[0.03311081283257845, 0.03044353406146712, 0.0..."
8,KNeighborsRegressor,"[-6.6, -5.0120000000000005, -4.465999999999999...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-6.872, -6.944, -7.156000000000001, -6.236, ...","[-7.3292, -6.8588, -7.1513152164000005, -6.275...","[0.23146351764370982, 0.10332550507982034, 0.0..."
9,SVR,"[-6.687658176340881, -5.133307973153668, -4.64...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.042995998101533, -7.0619574852870475, -7....","[-7.003524424094834, -6.989776415260996, -7.06...","[0.04119211662428986, 0.043011697391415506, 0...."
10,MLPRegressor,"[-6.572416732980778, -4.719641959796255, -4.76...",1192 -7.300000 1145 -6.520000 841 -7.29...,"[[-7.056798506075666, -6.814532814071426, -6.7...","[-7.068524374614118, -6.813355229660674, -6.72...","[0.06554662917715928, 0.05394615743764486, 0.0..."

In [20]:
results_df.to_csv('stacked_model_results/Results_5_fold_stacked_prediction_const_rem.csv')
prediction_df.to_csv('stacked_model_results/Prediction_data_Meta_learners_5_fold_stacked_prediction_const_rem.csv')

In [21]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\4205061013.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\4205061013.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 271)
(1392, 271)
(5568, 822)
(1392, 822)
(5568, 771)
(1392, 771)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765  3.524800    2.105859  ...  4.059403  1.229311  1.116345  1.445284
4772  3.524800    2.105859  ...  2.430700  1.301900  1.013546  1.331807
4766  3.524800    2.105859  ...  2.379031  1.318982  1.318982  1.416716
4767  3.524800    2.105859  ...  2.392510  1.171389  1.057402  1.316650
4585  3.555194    2.111795  ...  1.876242  1.482892  1.461695  1.319991
...        ...         ...  ...       ...       ...       ...       ...
607   3.466151    4.234460  ...  0.625185  1.354079  1.354079  1.385853
726   4.111830    1.340817  ...  1.277461  1.176213  1.033796  1.547430
772   4.065966    1.511740  ...  0.778508  1.247251  1.204229  1.549481
5468  3.609789    1.643135  ...  0.000000  1.360702  1.170716  1.386263
5397  3.023866    2.051939  ...  0.919946  1.936361  1.704628  1.082969

      geomShape     RDF55p       P1m        Dv       L3p        Ki
4765   0.832252  35.580478  0.532075  1.216361  2.697051  0.361574
4772   0.905135  38.960678  0.562820  0.913940  3.825470  0.285387
4766   0.765706  32.692290  0.579772  1.189531  2.451943  0.374559
4767   0.859830  40.512780  0.517578  0.988930  3.888022  0.269237
4585   0.833525  44.236785  0.627460  0.992478  2.726084  0.375665
...         ...        ...       ...       ...       ...       ...
607    0.782432  76.013922  0.618173  1.272322  3.465821  0.407764
726    0.829074  68.967821  0.566761  1.033432  2.674361  0.411379
772    0.904516  48.286030  0.563706  1.120753  2.906278  0.407451
5468   0.920917  22.088272  0.570890  1.076762  2.195044  0.395831
5397   0.901215  34.586426  0.705175  0.989737  2.917641  0.539314

[5568 rows x 271 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192  3.524800    2.105859  ...  2.419467  1.150893  1.015666  1.562053
1145  3.555194    2.111795  ...  1.758568  1.242915  1.241792  1.325082
841   3.969702    1.549820  ...  1.571209  1.199839  1.008213  1.565738
1146  3.555194    2.111795  ...  1.928541  1.208494  1.074378  1.526981
755   3.862771    1.798149  ...  1.689117  1.206602  1.156762  1.543384
...        ...         ...  ...       ...       ...       ...       ...
1147  3.547997    2.146757  ...  2.299245  1.067795  1.010859  1.466799
174   4.118337    1.352048  ...  1.384929  1.235104  1.200599  1.633772
1193  3.524800    2.105859  ...  2.405988  1.084460  1.007445  1.542899
122   1.621178    4.382718  ...  1.176240  1.101137  1.084997  1.412328
201   4.060393    1.513753  ...  0.688547  1.111835  1.004241  1.721602

      geomShape     RDF55p       P1m        Dv       L3p        Ki
1192   0.745882  39.414328  0.557076  1.128459  1.562507  0.408108
1145   0.787200  39.934832  0.560880  1.215016  3.482162  0.351511
841    0.690480  48.632791  0.567719  1.036948  1.689512  0.421941
1146   0.771384  40.759570  0.551536  0.991921  2.430374  0.378168
755    0.757646  46.517665  0.572634  1.042262  1.866171  0.415839
...         ...        ...       ...       ...       ...       ...
1147   0.714699  46.871562  0.497007  1.109375  3.498353  0.315953
174    0.859816  57.763793  0.494014  1.233429  4.228185  0.368291
1193   0.818768  42.734317  0.477615  0.977114  2.536672  0.355842
122    0.491025  81.795576  0.526458  1.361869  6.133363  0.314560
201    0.832274  50.640449  0.526102  1.047451  2.011146  0.432148

[1392 rows x 271 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 822 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
1192             0             0  ...      7.0        0.0        0.0
1145             0             0  ...      7.0        0.0        0.0
841              0             0  ...     10.0        0.0        0.0
1146             0             0  ...      7.0        0.0        0.0
755              0             0  ...      9.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
1147             0             0  ...      7.0        0.0        0.0
174              0             0  ...     21.0        0.0        0.0
1193             0             0  ...      7.0        0.0        0.0
122              0             0  ...     10.0        0.0        0.0
201              0             0  ...     17.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192        6.0        0.0        0.0        0.0        0.0        6.0
1145        6.0        0.0        0.0        0.0        0.0        6.0
841         7.0        0.0        0.0        0.0        0.0        7.0
1146        6.0        0.0        0.0        0.0        0.0        6.0
755         7.0        0.0        0.0        0.0        0.0        7.0
...         ...        ...        ...        ...        ...        ...
1147        6.0        0.0        0.0        0.0        0.0        6.0
174         6.0        0.0        0.0        0.0        0.0       12.0
1193        6.0        0.0        0.0        0.0        0.0        6.0
122        11.0        0.0        0.0        0.0        0.0       11.0
201         6.0        0.0        0.0        0.0        0.0       12.0

      SubFPC302
1192       10.0
1145       11.0
841         9.0
1146       11.0
755        11.0
...         ...
1147       10.0
174         9.0
1193       10.0
122        18.0
201         9.0

[1392 rows x 822 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -0.832013         -0.339157         -0.094716  ...
4772         -0.605726         -0.351874         -0.149570  ...
4766         -0.614279         -0.147806         -0.181123  ...
4767         -0.812609         -0.332812         -0.083156  ...
4585         -0.700132         -0.313935          0.076244  ...
...                ...               ...               ...  ...
607          -0.384116         -0.428047         -0.057039  ...
726          -0.483824          0.091023          0.073532  ...
772          -0.510908          0.078197          0.078757  ...
5468         -0.638301         -0.432866          0.220133  ...
5397         -1.021350         -0.356712          0.010048  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613
...                  ...                 ...                 ...
607            -1.573230           -0.602913            0.695327
726            -1.956501           -0.880823            0.291396
772            -1.988949           -0.906367            0.335933

In [22]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007391 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56780
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006788 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56791
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005419 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56820
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008067 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56796
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 261
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006668 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56811
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [03:58, 29.87s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:59<11:57, 239.00s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008974 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2441
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 790
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009119 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010367 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009291 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2459
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 795
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007243 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2447
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 792
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:59, 22.41s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:58<06:47, 203.89s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037183 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.040441 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.029629 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024669 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.022589 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [20:23, 152.88s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [27:21<11:09, 669.26s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000306 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 146
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000147 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000085 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000364 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000167 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [00:11,  1.39s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [27:32<00:00, 413.13s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000570 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7925
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000840 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7942
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.749693

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000680 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7931
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000429 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7928
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.739382

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000835 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7925
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.738471
LGBMRegressor Evaluation completed: Test R2 score: 0.6672489560297785
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6107097295944703
RandomForestRegressor Evaluation completed: Test R2 score: 0.6613097610209558
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6702429243994883
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6175639539288706
XGBRegressor Evaluation completed: Test R2 score: 0.6610525180498967
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6636363448130684
LinearRegression Evaluation completed: Test R2 score: 0.6627932513469735
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6537069057229441
SVR Evaluation completed: Test R2 score: 0.666054006737546
MLPRegressor Evaluation completed: Test R2 score: 0.6667346079529057

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.139846,0.275151,0.373959,0.775460,0.880621,0.856664,0.210574,0.325055,0.458884,0.667249,0.817436,0.798631
DecisionTreeRegressor,0.278341,0.390145,0.527580,0.553088,0.778284,0.739447,0.246354,0.355497,0.496341,0.610710,0.786580,0.761389
RandomForestRegressor,0.140935,0.274878,0.375414,0.773710,0.879688,0.855541,0.214333,0.327046,0.462961,0.661310,0.813912,0.794335
GradientBoostingRegressor,0.140157,0.274736,0.374375,0.774960,0.880334,0.857776,0.208680,0.324561,0.456815,0.670243,0.819175,0.798941
AdaBoostRegressor,0.187307,0.340538,0.432790,0.699255,0.853316,0.829191,0.242016,0.378673,0.491952,0.617564,0.799089,0.780316
XGBRegressor,0.163979,0.296157,0.404943,0.736711,0.859390,0.834774,0.214496,0.328257,0.463137,0.661053,0.814364,0.794850
ExtraTreesRegressor,0.141985,0.274195,0.376809,0.772025,0.878769,0.856043,0.212860,0.326100,0.461368,0.663636,0.815213,0.796876
LinearRegression,0.138379,0.272292,0.371993,0.777815,0.881949,0.858061,0.213394,0.327614,0.461946,0.662793,0.814555,0.797204
KNeighborsRegressor,0.161958,0.294251,0.402440,0.739955,0.860612,0.834933,0.219144,0.334717,0.468128,0.653707,0.809538,0.793099
SVR,0.144844,0.275538,0.380583,0.767435,0.876354,0.855738,0.211331,0.321450,0.459707,0.666054,0.817934,0.803290
MLPRegressor,0.144380,0.279699,0.379974,0.768179,0.876547,0.852169,0.210900,0.327352,0.459238,0.666735,0.817204,0.799368

In [23]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008422 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56797
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005603 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56804
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008211 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56789
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007724 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56807
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 261
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003796 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56797
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [04:08, 31.03s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [04:08<12:24, 248.25s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009296 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008303 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2458
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009379 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 795
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008480 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2463
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 796
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009412 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2442
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 790
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [02:52, 21.58s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [07:00<06:47, 203.78s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.035934 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.041172 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024454 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.035898 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032438 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [20:03, 150.44s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [27:04<11:00, 660.28s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000174 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 143
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000099 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.741644

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000110 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 146
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000130 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [00:11,  1.39s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [27:15<00:00, 408.89s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001415 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7922
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000947 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7921
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.747251

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000921 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7908
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000956 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7927
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.751882

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000890 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7896
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.726702
LGBMRegressor Evaluation completed: Test R2 score: 0.6722265867212722
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6136045187330268
RandomForestRegressor Evaluation completed: Test R2 score: 0.6662080971552956
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6710639055913041
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6278342957975301
XGBRegressor Evaluation completed: Test R2 score: 0.6599207056879053
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6689389290341685
LinearRegression Evaluation completed: Test R2 score: 0.6615546303798725
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6601383205537777
SVR Evaluation completed: Test R2 score: 0.6656922730062033
MLPRegressor Evaluation completed: Test R2 score: 0.6656945578848321

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.139585,0.275532,0.373610,0.775879,0.880874,0.858344,0.207424,0.322777,0.455439,0.672227,0.820666,0.801682
DecisionTreeRegressor,0.299442,0.399590,0.547213,0.519207,0.757480,0.726459,0.244522,0.355400,0.494492,0.613605,0.788244,0.767639
RandomForestRegressor,0.140599,0.276568,0.374966,0.774249,0.880075,0.856016,0.211233,0.325489,0.459601,0.666208,0.816677,0.796451
GradientBoostingRegressor,0.146858,0.286396,0.383220,0.764201,0.874910,0.849605,0.208160,0.324792,0.456246,0.671064,0.819674,0.799921
AdaBoostRegressor,0.189439,0.338871,0.435246,0.695830,0.849374,0.833984,0.235517,0.369350,0.485301,0.627834,0.803929,0.791952
XGBRegressor,0.157929,0.294388,0.397403,0.746425,0.865015,0.838441,0.215212,0.327545,0.463909,0.659921,0.813805,0.796398
ExtraTreesRegressor,0.137955,0.273310,0.371423,0.778496,0.882446,0.858609,0.209505,0.324070,0.457717,0.668939,0.818349,0.797600
LinearRegression,0.137056,0.270815,0.370211,0.779939,0.883142,0.858545,0.214178,0.328300,0.462794,0.661555,0.813817,0.796992
KNeighborsRegressor,0.157354,0.291520,0.396678,0.747348,0.864685,0.840668,0.215074,0.331556,0.463761,0.660138,0.813481,0.796015
SVR,0.142293,0.273347,0.377217,0.771530,0.878768,0.858166,0.211559,0.323212,0.459956,0.665692,0.817789,0.803548
MLPRegressor,0.146494,0.281054,0.382745,0.764786,0.874938,0.849642,0.211558,0.327839,0.459954,0.665695,0.817354,0.800987

In [24]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_constant_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\4221868159.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\4221868159.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 271)
(1392, 271)
(5568, 822)
(1392, 822)
(5568, 771)
(1392, 771)
(5568, 17)
(1392, 17)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765  3.524800    2.105859  ...  4.059403  1.229311  1.116345  1.445284
4772  3.524800    2.105859  ...  2.430700  1.301900  1.013546  1.331807
4766  3.524800    2.105859  ...  2.379031  1.318982  1.318982  1.416716
4767  3.524800    2.105859  ...  2.392510  1.171389  1.057402  1.316650
4585  3.555194    2.111795  ...  1.876242  1.482892  1.461695  1.319991
...        ...         ...  ...       ...       ...       ...       ...
607   3.466151    4.234460  ...  0.625185  1.354079  1.354079  1.385853
726   4.111830    1.340817  ...  1.277461  1.176213  1.033796  1.547430
772   4.065966    1.511740  ...  0.778508  1.247251  1.204229  1.549481
5468  3.609789    1.643135  ...  0.000000  1.360702  1.170716  1.386263
5397  3.023866    2.051939  ...  0.919946  1.936361  1.704628  1.082969

      geomShape     RDF55p       P1m        Dv       L3p        Ki
4765   0.832252  35.580478  0.532075  1.216361  2.697051  0.361574
4772   0.905135  38.960678  0.562820  0.913940  3.825470  0.285387
4766   0.765706  32.692290  0.579772  1.189531  2.451943  0.374559
4767   0.859830  40.512780  0.517578  0.988930  3.888022  0.269237
4585   0.833525  44.236785  0.627460  0.992478  2.726084  0.375665
...         ...        ...       ...       ...       ...       ...
607    0.782432  76.013922  0.618173  1.272322  3.465821  0.407764
726    0.829074  68.967821  0.566761  1.033432  2.674361  0.411379
772    0.904516  48.286030  0.563706  1.120753  2.906278  0.407451
5468   0.920917  22.088272  0.570890  1.076762  2.195044  0.395831
5397   0.901215  34.586426  0.705175  0.989737  2.917641  0.539314

[5568 rows x 271 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192  3.524800    2.105859  ...  2.419467  1.150893  1.015666  1.562053
1145  3.555194    2.111795  ...  1.758568  1.242915  1.241792  1.325082
841   3.969702    1.549820  ...  1.571209  1.199839  1.008213  1.565738
1146  3.555194    2.111795  ...  1.928541  1.208494  1.074378  1.526981
755   3.862771    1.798149  ...  1.689117  1.206602  1.156762  1.543384
...        ...         ...  ...       ...       ...       ...       ...
1147  3.547997    2.146757  ...  2.299245  1.067795  1.010859  1.466799
174   4.118337    1.352048  ...  1.384929  1.235104  1.200599  1.633772
1193  3.524800    2.105859  ...  2.405988  1.084460  1.007445  1.542899
122   1.621178    4.382718  ...  1.176240  1.101137  1.084997  1.412328
201   4.060393    1.513753  ...  0.688547  1.111835  1.004241  1.721602

      geomShape     RDF55p       P1m        Dv       L3p        Ki
1192   0.745882  39.414328  0.557076  1.128459  1.562507  0.408108
1145   0.787200  39.934832  0.560880  1.215016  3.482162  0.351511
841    0.690480  48.632791  0.567719  1.036948  1.689512  0.421941
1146   0.771384  40.759570  0.551536  0.991921  2.430374  0.378168
755    0.757646  46.517665  0.572634  1.042262  1.866171  0.415839
...         ...        ...       ...       ...       ...       ...
1147   0.714699  46.871562  0.497007  1.109375  3.498353  0.315953
174    0.859816  57.763793  0.494014  1.233429  4.228185  0.368291
1193   0.818768  42.734317  0.477615  0.977114  2.536672  0.355842
122    0.491025  81.795576  0.526458  1.361869  6.133363  0.314560
201    0.832274  50.640449  0.526102  1.047451  2.011146  0.432148

[1392 rows x 271 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 822 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
1192             0             0  ...      7.0        0.0        0.0
1145             0             0  ...      7.0        0.0        0.0
841              0             0  ...     10.0        0.0        0.0
1146             0             0  ...      7.0        0.0        0.0
755              0             0  ...      9.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
1147             0             0  ...      7.0        0.0        0.0
174              0             0  ...     21.0        0.0        0.0
1193             0             0  ...      7.0        0.0        0.0
122              0             0  ...     10.0        0.0        0.0
201              0             0  ...     17.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192        6.0        0.0        0.0        0.0        0.0        6.0
1145        6.0        0.0        0.0        0.0        0.0        6.0
841         7.0        0.0        0.0        0.0        0.0        7.0
1146        6.0        0.0        0.0        0.0        0.0        6.0
755         7.0        0.0        0.0        0.0        0.0        7.0
...         ...        ...        ...        ...        ...        ...
1147        6.0        0.0        0.0        0.0        0.0        6.0
174         6.0        0.0        0.0        0.0        0.0       12.0
1193        6.0        0.0        0.0        0.0        0.0        6.0
122        11.0        0.0        0.0        0.0        0.0       11.0
201         6.0        0.0        0.0        0.0        0.0       12.0

      SubFPC302
1192       10.0
1145       11.0
841         9.0
1146       11.0
755        11.0
...         ...
1147       10.0
174         9.0
1193       10.0
122        18.0
201         9.0

[1392 rows x 822 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -0.832013         -0.339157         -0.094716  ...
4772         -0.605726         -0.351874         -0.149570  ...
4766         -0.614279         -0.147806         -0.181123  ...
4767         -0.812609         -0.332812         -0.083156  ...
4585         -0.700132         -0.313935          0.076244  ...
...                ...               ...               ...  ...
607          -0.384116         -0.428047         -0.057039  ...
726          -0.483824          0.091023          0.073532  ...
772          -0.510908          0.078197          0.078757  ...
5468         -0.638301         -0.432866          0.220133  ...
5397         -1.021350         -0.356712          0.010048  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613
...                  ...                 ...                 ...
607            -1.573230           -0.602913            0.695327
726            -1.956501           -0.880823            0.291396
772            -1.988949           -0.906367            0.335933

In [25]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008726 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56797
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005220 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56804
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 260
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008483 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56789
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007025 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56807
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 261
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007350 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56797
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [03:58, 29.87s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:59<11:57, 239.01s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010484 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007484 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2458
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009520 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 795
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008398 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2463
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 796
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008809 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2442
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 790
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [02:52, 21.59s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:51<06:40, 200.04s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032425 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.030092 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.039929 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037487 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032429 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [20:00, 150.10s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [26:52<10:57, 657.02s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000460 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 685
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000443 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 677
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.747251
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000291 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 674
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 13
[LightGBM] [Info] Start training from score -5.741644

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000381 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 682
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 13
[LightGBM] [Info] Start training from score -5.751882
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000270 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 668
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 13
[LightGBM] [Info] Start training from score -5.726702

Training models: 8it [00:13,  1.65s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [27:05<00:00, 406.45s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001132 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7980
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.747051
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001006 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7979
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.747251

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000992 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7979
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 32
[LightGBM] [Info] Start training from score -5.741644
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000872 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7975
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.751882

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000985 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7966
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 32
[LightGBM] [Info] Start training from score -5.726702
LGBMRegressor Evaluation completed: Test R2 score: 0.6717412298131484
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6206567001391181
RandomForestRegressor Evaluation completed: Test R2 score: 0.6647182557152593
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.669301044036135
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6213917166018106
XGBRegressor Evaluation completed: Test R2 score: 0.6602131718726123
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6689886425452414
LinearRegression Evaluation completed: Test R2 score: 0.6612435556523203
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6556103670366625
SVR Evaluation completed: Test R2 score: 0.6637754299777204
MLPRegressor Evaluation completed: Test R2 score: 0.6669029414788055

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.140421,0.275016,0.374729,0.774535,0.880196,0.857763,0.207731,0.322300,0.455776,0.671741,0.820758,0.801640
DecisionTreeRegressor,0.291168,0.395887,0.539600,0.532492,0.765085,0.725533,0.240059,0.348807,0.489958,0.620657,0.793150,0.773862
RandomForestRegressor,0.140606,0.276096,0.374975,0.774238,0.880048,0.855931,0.212176,0.326070,0.460625,0.664718,0.815885,0.795304
GradientBoostingRegressor,0.143395,0.280308,0.378675,0.769761,0.877655,0.854281,0.209276,0.324948,0.457467,0.669301,0.818829,0.799737
AdaBoostRegressor,0.193817,0.342455,0.440247,0.688801,0.848451,0.837015,0.239594,0.373556,0.489483,0.621392,0.803762,0.793933
XGBRegressor,0.154561,0.292431,0.393142,0.751832,0.867838,0.840919,0.215027,0.325207,0.463710,0.660213,0.814852,0.796327
ExtraTreesRegressor,0.138944,0.274038,0.372752,0.776907,0.881495,0.857593,0.209473,0.322872,0.457683,0.668989,0.818539,0.797525
LinearRegression,0.137162,0.270890,0.370354,0.779768,0.883045,0.859166,0.214375,0.327860,0.463006,0.661244,0.813661,0.796843
KNeighborsRegressor,0.158821,0.291483,0.398524,0.744992,0.863454,0.840507,0.217940,0.330807,0.466840,0.655610,0.811283,0.792139
SVR,0.142996,0.274036,0.378149,0.770401,0.878098,0.858070,0.212772,0.322082,0.461273,0.663775,0.816756,0.800928
MLPRegressor,0.143721,0.279375,0.379106,0.769237,0.877190,0.852857,0.210793,0.327340,0.459122,0.666903,0.817504,0.800596

In [26]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_2d_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_2d_test =  df_desc_test[df_2d_train.columns]

df_desc_train = pd.read_csv('Descriptors/Train_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_3d_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_3d_test =  df_desc_test[df_3d_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_2d_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_2d_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_2d_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_2d_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_2d_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_2d_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_2d_train.shape)
print(df_2d_test.shape)
print(df_3d_train.shape)
print(df_3d_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_2d_train)
print(df_2d_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_3d_train)
print(df_3d_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    DecisionTreeRegressor(random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=42)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2831346891.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2831346891.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 238)
(1392, 238)
(5568, 39)
(1392, 39)
(5568, 822)
(1392, 822)
(5568, 771)
(1392, 771)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...   MDEN-22   MDEN-33  MLFER_A  nFRing  nTRing  \
4765  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4772  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4766  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4767  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4585  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
...        ...         ...  ...       ...       ...      ...     ...     ...
607   3.466151    4.234460  ...  0.722483  2.640759    1.326     0.0     1.0
726   4.111830    1.340817  ...  2.032309  1.807025    1.326     3.0     9.0
772   4.065966    1.511740  ...  2.032309  1.807025    1.326     3.0     8.0
5468  3.609789    1.643135  ...  3.145476  0.000000    1.791     3.0     7.0
5397  3.023866    2.051939  ...  2.357023  0.000000    2.910     0.0     3.0

      nHeteroRing  RotBtFrac  LipinskiFailures      VR2_D  XLogP
4765          2.0   0.358491                 3  15.737601  6.411
4772          2.0   0.358491                 3  15.737601  6.411
4766          2.0   0.358491                 3  15.737601  6.411
4767          2.0   0.358491                 3  15.737601  6.411
4585          2.0   0.370370                 3  16.117492  6.732
...           ...        ...               ...        ...    ...
607           1.0   0.463415                 3  18.513367  8.274
726           3.0   0.216867                 2  18.648133  8.853
772           3.0   0.262500                 2  18.358190  8.266
5468          3.0   0.186047                 1  30.760537  3.602
5397          1.0   0.312500                 3  18.257054  0.416

[5568 rows x 238 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...   MDEN-22   MDEN-33  MLFER_A  nFRing  nTRing  \
1192  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
1145  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
841   3.969702    1.549820  ...  0.980561  0.436790    1.326     7.0    12.0
1146  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
755   3.862771    1.798149  ...  1.744702  0.111111    1.928     3.0     7.0
...        ...         ...  ...       ...       ...      ...     ...     ...
1147  3.547997    2.146757  ...  1.100642  0.111111    2.024     1.0     4.0
174   4.118337    1.352048  ...  2.032309  1.807025    1.326     3.0     9.0
1193  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
122   1.621178    4.382718  ...  0.722483  2.640759    1.778     0.0     1.0
201   4.060393    1.513753  ...  2.032309  1.807025    1.326     3.0     8.0

      nHeteroRing  RotBtFrac  LipinskiFailures      VR2_D  XLogP
1192          2.0   0.358491                 3  15.737601  6.411
1145          2.0   0.370370                 3  16.117492  6.732
841           4.0   0.258065                 2  14.280421  5.016
1146          2.0   0.370370                 3  16.117492  6.732
755           3.0   0.322581                 3  21.248642  6.655
...           ...        ...               ...        ...    ...
1147          2.0   0.370370                 2  17.377281  6.124
174           3.0   0.226190                 2  18.093977  9.361
1193          2.0   0.358491                 3  15.737601  6.411
122           1.0   0.482759                 3  53.766941  7.801
201           3.0   0.253165                 2  19.812561  7.486

[1392 rows x 238 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

        3d_rdkit_1  3d_rdkit_5  3d_rdkit_9  3d_rdkit_10  3d_rdkit_11  \
4765   7872.823921    0.738700    0.125304     0.353724     1.558591
4772   9930.533159    0.658530    0.095292     0.386270     1.544223
4766   8494.098132    0.694647    0.177124     0.290417     1.442573
4767   8533.399061    0.639215    0.207182     0.161452     1.082209
4585   7643.473123    0.717251    0.219270     0.194355     1.211932
...            ...         ...         ...          ...          ...
607   23696.437001    0.672397    0.149641     0.334144     1.885021
726   22614.121230    0.629869    0.193420     0.191026     1.556504
772   22065.114361    0.602169    0.194118     0.174295     1.412802
5468   4655.717280    0.743657    0.179673     0.264126     1.190452
5397   6090.169966    0.781359    0.161647     0.371661     1.483705

         TDB9u       TDB1m  ...    LOBMIN   MOMI-XY  geomShape    RDF150m  \
4765  7.418416  112.511420  ...  1.116345  1.445284   0.832252   0.138733
4772  7.454631  112.452932  ...  1.013546  1.331807   0.905135   1.306304
4766  7.632072  112.356145  ...  1.318982  1.416716   0.765706   0.164775
4767  7.418938  112.347660  ...  1.057402  1.316650   0.859830   0.034096
4585  7.483836  112.059155  ...  1.461695  1.319991   0.833525   2.526850
...        ...         ...  ...       ...       ...        ...        ...
607   7.513506  105.619540  ...  1.354079  1.385853   0.782432  27.830373
726   7.704122  113.893041  ...  1.033796  1.547430   0.829074  19.454686
772   7.670509  113.201079  ...  1.204229  1.549481   0.904516  15.284387
5468  7.567642  124.851674  ...  1.170716  1.386263   0.920917   0.013053
5397  7.276432  126.900345  ...  1.704628  1.082969   0.901215   1.586138

         RDF35p     RDF55p       P1m        Dv       L3p        Ki
4765  33.726722  35.580478  0.532075  1.216361  2.697051  0.361574
4772  23.896915  38.960678  0.562820  0.913940  3.825470  0.285387
4766  26.457296  32.692290  0.579772  1.189531  2.451943  0.374559
4767  28.244842  40.512780  0.517578  0.988930  3.888022  0.269237
4585  26.626298  44.236785  0.627460  0.992478  2.726084  0.375665
...         ...        ...       ...       ...       ...       ...
607   59.680918  76.013922  0.618173  1.272322  3.465821  0.407764
726   57.510022  68.967821  0.566761  1.033432  2.674361  0.411379
772   49.392095  48.286030  0.563706  1.120753  2.906278  0.407451
5468  17.061388  22.088272  0.570890  1.076762  2.195044  0.395831
5397  17.836463  34.586426  0.705175  0.989737  2.917641  0.539314

[5568 rows x 39 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

        3d_rdkit_1  3d_rdkit_5  3d_rdkit_9  3d_rdkit_10  3d_rdkit_11  \
1192   7759.823403    0.755252    0.165415     0.361420     1.604014
1145   9177.558755    0.810720    0.048930     0.594448     1.886363
841   10682.206206    0.692050    0.196219     0.226588     1.391743
1146   9825.979598    0.681641    0.094963     0.379913     1.549860
755   10614.460706    0.715119    0.183646     0.298168     1.597707
...            ...         ...         ...          ...          ...
1147   8449.126991    0.670211    0.162360     0.319128     1.450707
174   21572.747575    0.633871    0.228897     0.131442     1.296285
1193   6821.711395    0.830470    0.176732     0.440726     1.675953
122   25578.896487    0.687869    0.138897     0.388782     2.027297
201   23034.833884    0.572401    0.200664     0.146334     1.263818

         TDB9u       TDB1m  ...    LOBMIN   MOMI-XY  geomShape    RDF150m  \
1192  7.354996  112.187325  ...  1.015666  1.562053   0.745882   0.020147
1145  7.629573  112.168246  ...  1.241792  1.325082   0.787200   0.545653
841   7.822703  117.198827  ...  1.008213  1.565738   0.690480   4.889455
1146  7.562573  111.790418  ...  1.074378  1.526981   0.771384   3.210320
755   7.564643  113.831085  ...  1.156762  1.543384   0.757646   6.870795
...        ...         ...  ...       ...       ...        ...        ...
1147  7.448699  111.731005  ...  1.010859  1.466799   0.714699   0.052668
174   7.864254  113.225298  ...  1.200599  1.633772   0.859816  16.792121
1193  7.279925  112.137229  ...  1.007445  1.542899   0.818768   0.156156
122   7.642301  106.475011  ...  1.084997  1.412328   0.491025  25.704373
201   7.794277  113.877897  ...  1.004241  1.721602   0.832274  22.656425

         RDF35p     RDF55p       P1m        Dv       L3p        Ki
1192  29.159978  39.414328  0.557076  1.128459  1.562507  0.408108
1145  24.950898  39.934832  0.560880  1.215016  3.482162  0.351511
841   28.916882  48.632791  0.567719  1.036948  1.689512  0.421941
1146  24.988490  40.759570  0.551536  0.991921  2.430374  0.378168
755   24.634239  46.517665  0.572634  1.042262  1.866171  0.415839
...         ...        ...       ...       ...       ...       ...
1147  29.405904  46.871562  0.497007  1.109375  3.498353  0.315953
174   46.903268  57.763793  0.494014  1.233429  4.228185  0.368291
1193  28.802920  42.734317  0.477615  0.977114  2.536672  0.355842
122   54.861889  81.795576  0.526458  1.361869  6.133363  0.314560
201   43.629009  50.640449  0.526102  1.047451  2.011146  0.432148

[1392 rows x 39 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 822 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0

In [27]:
dataframes = [(df_2d_train, df_2d_test),(df_3d_train, df_3d_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/5 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004956 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48365
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 227
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005965 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48376
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 227
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006232 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48405
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 228
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006419 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48381
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 228
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005935 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48396
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 229
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:50, 21.27s/it]
Processing dataframe pairs:  20%|██        | 1/5 [02:50<11:20, 170.14s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001257 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9180
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 36
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001211 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9180
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 36
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001164 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9180
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 36
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001148 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9180
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 36
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001160 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9180
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 36
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [01:05,  8.20s/it]
Processing dataframe pairs:  40%|████      | 2/5 [03:55<05:25, 108.64s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009358 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2441
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 790
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009428 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005710 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014609 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2459
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 795
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009353 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2447
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 792
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:56, 22.11s/it]
Processing dataframe pairs:  60%|██████    | 3/5 [06:52<04:39, 139.81s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034070 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.038093 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037423 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.033588 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.039194 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [19:57, 149.74s/it]
Processing dataframe pairs:  80%|████████  | 4/5 [26:50<09:17, 557.54s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000128 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 146
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000106 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000154 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000088 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 144
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000133 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 145
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [00:11,  1.38s/it]
Processing dataframe pairs: 100%|██████████| 5/5 [27:01<00:00, 324.32s/it]
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 40)
Dimensions of meta_features_test: (1392, 40)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001437 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9958
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001304 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9968
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.749693

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000753 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9973
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001227 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9950
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.739382

c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Python312\Lib\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001052 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9968
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.738471
LGBMRegressor Evaluation completed: Test R2 score: 0.6689635914346409
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6143027445460536
RandomForestRegressor Evaluation completed: Test R2 score: 0.6625867183354615
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6701699880215923
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6354933861352046
XGBRegressor Evaluation completed: Test R2 score: 0.662207495198201
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6641714559168439
LinearRegression Evaluation completed: Test R2 score: 0.6669955283658906
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6558222399874865
SVR Evaluation completed: Test R2 score: 0.670648088070187
MLPRegressor Evaluation completed: Test R2 score: 0.6513697438079337

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.138941,0.274063,0.372748,0.776912,0.881437,0.857714,0.209489,0.324114,0.457700,0.668964,0.818436,0.799359
DecisionTreeRegressor,0.291258,0.393287,0.539684,0.532347,0.770680,0.741587,0.244080,0.351169,0.494045,0.614303,0.788748,0.766001
RandomForestRegressor,0.141239,0.275376,0.375818,0.773222,0.879411,0.854859,0.213525,0.326864,0.462087,0.662587,0.814565,0.794928
GradientBoostingRegressor,0.140695,0.275712,0.375094,0.774096,0.879833,0.856779,0.208726,0.324827,0.456865,0.670170,0.819018,0.799002
AdaBoostRegressor,0.184471,0.335987,0.429501,0.703808,0.852562,0.827950,0.230670,0.365468,0.480281,0.635493,0.807809,0.788149
XGBRegressor,0.160469,0.296943,0.400585,0.742347,0.862475,0.836202,0.213765,0.326741,0.462347,0.662207,0.814775,0.795518
ExtraTreesRegressor,0.139730,0.273668,0.373804,0.775646,0.880793,0.856780,0.212522,0.325326,0.461001,0.664171,0.815488,0.797830
LinearRegression,0.137568,0.272023,0.370901,0.779117,0.882688,0.858186,0.210735,0.324765,0.459058,0.666996,0.817060,0.800150
KNeighborsRegressor,0.160267,0.293571,0.400334,0.742670,0.861881,0.836184,0.217805,0.332617,0.466696,0.655822,0.810535,0.794184
SVR,0.145955,0.276934,0.382041,0.765650,0.875383,0.854981,0.208423,0.318884,0.456534,0.670648,0.820677,0.806685
MLPRegressor,0.156836,0.290820,0.396026,0.748179,0.869054,0.840703,0.220623,0.333496,0.469705,0.651370,0.813310,0.795987

In [28]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_2d_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_2d_test =  df_desc_test[df_2d_train.columns]



# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_2d_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_2d_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_2d_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_2d_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_2d_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_2d_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_2d_train.shape)
print(df_2d_test.shape)

print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_2d_train)
print(df_2d_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=42),
    DecisionTreeRegressor(random_state=42),
    RandomForestRegressor(n_jobs=-1, random_state=42),
    GradientBoostingRegressor(random_state=42),
    AdaBoostRegressor(random_state=42),
    xgb.XGBRegressor(random_state=42),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=42),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=42)
]

C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2290020924.py:3: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('Descriptors/Train_2d_all_descriptors.csv')
C:\Users\aksha\AppData\Local\Temp\ipykernel_24892\2290020924.py:11: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('Descriptors/Test_2d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 238)
(1392, 238)
(5568, 822)
(1392, 822)
(5568, 771)
(1392, 771)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...   MDEN-22   MDEN-33  MLFER_A  nFRing  nTRing  \
4765  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4772  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4766  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4767  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
4585  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
...        ...         ...  ...       ...       ...      ...     ...     ...
607   3.466151    4.234460  ...  0.722483  2.640759    1.326     0.0     1.0
726   4.111830    1.340817  ...  2.032309  1.807025    1.326     3.0     9.0
772   4.065966    1.511740  ...  2.032309  1.807025    1.326     3.0     8.0
5468  3.609789    1.643135  ...  3.145476  0.000000    1.791     3.0     7.0
5397  3.023866    2.051939  ...  2.357023  0.000000    2.910     0.0     3.0

      nHeteroRing  RotBtFrac  LipinskiFailures      VR2_D  XLogP
4765          2.0   0.358491                 3  15.737601  6.411
4772          2.0   0.358491                 3  15.737601  6.411
4766          2.0   0.358491                 3  15.737601  6.411
4767          2.0   0.358491                 3  15.737601  6.411
4585          2.0   0.370370                 3  16.117492  6.732
...           ...        ...               ...        ...    ...
607           1.0   0.463415                 3  18.513367  8.274
726           3.0   0.216867                 2  18.648133  8.853
772           3.0   0.262500                 2  18.358190  8.266
5468          3.0   0.186047                 1  30.760537  3.602
5397          1.0   0.312500                 3  18.257054  0.416

[5568 rows x 238 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...   MDEN-22   MDEN-33  MLFER_A  nFRing  nTRing  \
1192  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
1145  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
841   3.969702    1.549820  ...  0.980561  0.436790    1.326     7.0    12.0
1146  3.555194    2.111795  ...  2.027881  0.000000    2.083     1.0     4.0
755   3.862771    1.798149  ...  1.744702  0.111111    1.928     3.0     7.0
...        ...         ...  ...       ...       ...      ...     ...     ...
1147  3.547997    2.146757  ...  1.100642  0.111111    2.024     1.0     4.0
174   4.118337    1.352048  ...  2.032309  1.807025    1.326     3.0     9.0
1193  3.524800    2.105859  ...  2.027881  0.000000    2.626     1.0     4.0
122   1.621178    4.382718  ...  0.722483  2.640759    1.778     0.0     1.0
201   4.060393    1.513753  ...  2.032309  1.807025    1.326     3.0     8.0

      nHeteroRing  RotBtFrac  LipinskiFailures      VR2_D  XLogP
1192          2.0   0.358491                 3  15.737601  6.411
1145          2.0   0.370370                 3  16.117492  6.732
841           4.0   0.258065                 2  14.280421  5.016
1146          2.0   0.370370                 3  16.117492  6.732
755           3.0   0.322581                 3  21.248642  6.655
...           ...        ...               ...        ...    ...
1147          2.0   0.370370                 2  17.377281  6.124
174           3.0   0.226190                 2  18.093977  9.361
1193          2.0   0.358491                 3  15.737601  6.411
122           1.0   0.482759                 3  53.766941  7.801
201           3.0   0.253165                 2  19.812561  7.486

[1392 rows x 238 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 822 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
1192             0             0  ...      7.0        0.0        0.0
1145             0             0  ...      7.0        0.0        0.0
841              0             0  ...     10.0        0.0        0.0
1146             0             0  ...      7.0        0.0        0.0
755              0             0  ...      9.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
1147             0             0  ...      7.0        0.0        0.0
174              0             0  ...     21.0        0.0        0.0
1193             0             0  ...      7.0        0.0        0.0
122              0             0  ...     10.0        0.0        0.0
201              0             0  ...     17.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192        6.0        0.0        0.0        0.0        0.0        6.0
1145        6.0        0.0        0.0        0.0        0.0        6.0
841         7.0        0.0        0.0        0.0        0.0        7.0
1146        6.0        0.0        0.0        0.0        0.0        6.0
755         7.0        0.0        0.0        0.0        0.0        7.0
...         ...        ...        ...        ...        ...        ...
1147        6.0        0.0        0.0        0.0        0.0        6.0
174         6.0        0.0        0.0        0.0        0.0       12.0
1193        6.0        0.0        0.0        0.0        0.0        6.0
122        11.0        0.0        0.0        0.0        0.0       11.0
201         6.0        0.0        0.0        0.0        0.0       12.0

      SubFPC302
1192       10.0
1145       11.0
841         9.0
1146       11.0
755        11.0
...         ...
1147       10.0
174         9.0
1193       10.0
122        18.0
201         9.0

[1392 rows x 822 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.505000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.036619         -0.694462         -1.115429          0.257369
4772         -0.187120         -0.576553         -1.113646          0.217452
4766         -0.308213         -0.500752         -1.136903          0.376348
4767          0.016274         -0.636620         -1.141914          0.276852
4585          0.083832         -0.721305         -1.134139          0.267341
...                ...               ...               ...               ...
607          -0.324350         -0.645759         -0.695893          0.243541
726          -0.241778         -0.571686         -1.426816          0.452932
772          -0.212002         -0.550634         -1.535163          0.439341
5468         -0.309093         -0.459309         -0.734528         -0.333036
5397          0.470620         -0.238479         -1.655452          0.852223

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -0.832013         -0.339157         -0.094716  ...
4772         -0.605726         -0.351874         -0.149570  ...
4766         -0.614279         -0.147806         -0.181123  ...
4767         -0.812609         -0.332812         -0.083156  ...
4585         -0.700132         -0.313935          0.076244  ...
...                ...               ...               ...  ...
607          -0.384116         -0.428047         -0.057039  ...
726          -0.483824          0.091023          0.073532  ...
772          -0.510908          0.078197          0.078757  ...
5468         -0.638301         -0.432866          0.220133  ...
5397         -1.021350         -0.356712          0.010048  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765            0.021458            0.275162            0.175341
4772           -0.055546            0.116104            0.052370
4766           -0.093762           -0.096864           -0.072894
4767           -0.008930            0.194468            0.144780
4585            0.142364            0.188423            0.013624
...                  ...                 ...                 ...
607             0.624158           -0.028039           -0.414469
726             0.225410           -0.037392            0.016631
772             0.220768           -0.067465            0.068838
5468            0.609599           -0.183258           -0.256352
5397            0.160611            0.209532            0.331793

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765           -0.178369            0.351235            0.145575
4772           -0.108203            0.296143            0.213482
4766           -0.121652            0.248491            0.267429
4767           -0.135560            0.389658            0.121689
4585           -0.238020            0.360796            0.542700
...                  ...                 ...                 ...
607            -0.179497            1.160695            0.025081
726            -0.262916            0.763308            0.094736
772            -0.261989            0.783335            0.188507
5468            0.282944            1.274662            0.546863
5397            0.576527           -0.101150            0.322451

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.600566           -0.426487            0.784893
4772           -1.792063           -0.521749            0.804875
4766           -1.887597           -0.543360            0.720520
4767           -1.618654           -0.425099            0.809852
4585           -1.777168           -0.492099            0.860613
...                  ...                 ...                 ...
607            -1.573230           -0.602913            0.695327
726            -1.956501           -0.880823            0.291396

In [29]:
dataframes = [(df_2d_train, df_2d_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=42)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005036 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48365
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 227
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005453 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48376
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 227
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005200 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48405
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 228
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005227 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48381
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 228
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007047 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 48396
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 229
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:50, 21.26s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [02:50<08:30, 170.10s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2441
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 790
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009360 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2457
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009040 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2460
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 794
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008264 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2459
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 795
[LightGBM] [Info] Start training from score -5.739382

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008164 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2447
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 792
[LightGBM] [Info] Start training from score -5.738471

Training models: 8it [02:55, 21.88s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [05:45<05:46, 173.02s/it]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.037638 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.748795
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032363 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.749693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.036073 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 768
[LightGBM] [Info] Start training from score -5.738190
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.030687 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.739382
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.034317 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 768
[LightGBM] [Info] Start training from score -5.738471

Training models: 2it [09:05, 272.85s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [14:50<14:50, 445.44s/it]

KeyboardInterrupt:

In [ ]:
from tqdm import tqdm
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('Atomic_features/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('Atomic_features/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),   
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101)
]

In [ ]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 10-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=10, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=10, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (10 fold CV)': mse_train,
        'Train MAE (10 fold CV)': mae_train,
        'Train RMSE (10 fold CV)': rmse_train,
        'Train R2 (10 fold CV)': r2_train,
        'Train PCC (10 fold CV)': pearson_train,
        'Train SCC (10 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

In [ ]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 15-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=15, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=15, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (15 fold CV)': mse_train,
        'Train MAE (15 fold CV)': mae_train,
        'Train RMSE (15 fold CV)': rmse_train,
        'Train R2 (15 fold CV)': r2_train,
        'Train PCC (15 fold CV)': pearson_train,
        'Train SCC (15 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

In [ ]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 20-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=20, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=20, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (20 fold CV)': mse_train,
        'Train MAE (20 fold CV)': mae_train,
        'Train RMSE (20 fold CV)': rmse_train,
        'Train R2 (20 fold CV)': r2_train,
        'Train PCC (20 fold CV)': pearson_train,
        'Train SCC (20 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

In [46]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 25-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=25, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=25, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (25 fold CV)': mse_train,
        'Train MAE (25 fold CV)': mae_train,
        'Train RMSE (25 fold CV)': rmse_train,
        'Train R2 (25 fold CV)': r2_train,
        'Train PCC (25 fold CV)': pearson_train,
        'Train SCC (25 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004673 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56933
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.744996
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004566 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.744315
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004598 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56933
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.743163
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004530 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56938
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.740339
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004640 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56936
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.745291
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004580 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56935
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.741411
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004739 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56940
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.743497
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004626 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56940
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.744014
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004614 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.746274
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004566 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56935
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.742870
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004600 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56930
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.741741
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004511 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56922
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.740183
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004597 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56935
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.741071
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004563 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56926
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.747438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004639 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56938
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.742863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005154 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56937
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.744785
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56930
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 262
[LightGBM] [Info] Start training from score -5.746944
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004635 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 263
[LightGBM] [Info] Start training from score -5.744125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56935
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.741579
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004590 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.744585
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004713 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56924
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.742189
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004604 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56927
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.740668
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004580 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56936
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.741549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004655 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56936
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.739085
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004599 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 263
[LightGBM] [Info] Start training from score -5.737672

ining models: 1it [00:09,  9.16s/it]
ining models: 2it [02:57, 102.60s/it]
ining models: 3it [15:33, 400.90s/it]
ining models: 4it [19:10, 328.61s/it]
ining models: 5it [19:35, 219.04s/it]
ining models: 6it [20:26, 161.83s/it]
ining models: 7it [20:27, 109.22s/it]
Training models: 8it [22:06, 165.79s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [22:06<1:06:19, 1326.34s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010763 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.744996
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2494
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.744315
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010128 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.743163
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010350 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2501
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.740339
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009250 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2501
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.745291
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.741411
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009665 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.743497
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009674 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.744014
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2501
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.746274
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009811 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2490
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.742870
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011773 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2499
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.741741
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009167 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2494
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.740183
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009525 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2492
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.741071
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009338 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.747438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012049 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2493
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.742863
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009442 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2503
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.744785
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009705 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2494
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 800
[LightGBM] [Info] Start training from score -5.746944
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009365 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2498
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 801
[LightGBM] [Info] Start training from score -5.744125
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009935 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 800
[LightGBM] [Info] Start training from score -5.741579
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009318 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2502
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 801
[LightGBM] [Info] Start training from score -5.744585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009575 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2498
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 801
[LightGBM] [Info] Start training from score -5.742189
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008354 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 800
[LightGBM] [Info] Start training from score -5.740668
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008439 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2490
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 799
[LightGBM] [Info] Start training from score -5.741549
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008576 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2499
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 801
[LightGBM] [Info] Start training from score -5.739085
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.008504 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2494
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 801
[LightGBM] [Info] Start training from score -5.737672

ining models: 1it [00:08,  8.02s/it]
ining models: 2it [00:48, 27.35s/it]
ining models: 3it [03:45, 95.38s/it]
ining models: 4it [05:58, 110.32s/it]
ining models: 5it [06:21, 78.68s/it]
ining models: 6it [07:11, 69.10s/it]
ining models: 7it [07:13, 47.25s/it]
Training models: 8it [13:09, 98.71s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [35:16<33:41, 1010.66s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016580 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.744996
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020931 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.744315
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015977 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.743163
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016145 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.740339
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019123 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.745291
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013677 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.741411
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014557 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.743497
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021268 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.744014
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013612 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.746274
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013561 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.742870
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013710 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.741741
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013922 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.740183
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013657 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.741071
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.030629 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.747438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013668 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.742863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013801 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.744785
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016834 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.746944
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013639 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 768
[LightGBM] [Info] Start training from score -5.744125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013918 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.741579
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.019393 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.744585
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013514 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.742189
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013590 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.740668
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013895 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.741549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013807 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.739085
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014642 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 768
[LightGBM] [Info] Start training from score -5.737672

ining models: 1it [00:27, 27.98s/it]
ining models: 2it [14:38, 511.57s/it]
ining models: 3it [1:32:23, 2408.20s/it]
ining models: 4it [1:48:09, 1831.14s/it]
ining models: 5it [1:49:34, 1201.55s/it]
ining models: 6it [1:52:23, 850.42s/it]
ining models: 7it [1:52:25, 573.04s/it]
Training models: 8it [1:55:59, 869.98s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [2:31:15<1:02:07, 3727.18s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000370 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.744996
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000177 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.744315
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000189 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.743163
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000193 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.740339
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000322 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.745291
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000184 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.741411
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.743497
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000187 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.744014
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000421 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.746274
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000177 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.742870
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000175 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.741741
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000177 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.740183
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.741071
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000210 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.747438
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.742863
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.744785
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.746944
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000169 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 9
[LightGBM] [Info] Start training from score -5.744125
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000156 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.741579
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.744585
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.742189
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000387 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.740668
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000253 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.741549
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000154 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.739085

ining models: 1it [00:01,  1.98s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.005511 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 9
[LightGBM] [Info] Start training from score -5.737672

ining models: 2it [00:08,  4.42s/it]
ining models: 3it [00:12,  4.32s/it]
ining models: 4it [00:14,  3.49s/it]
ining models: 5it [00:15,  2.75s/it]
ining models: 6it [00:20,  3.22s/it]
ining models: 7it [00:20,  2.40s/it]
Training models: 8it [00:48,  6.02s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [2:32:04<00:00, 2281.00s/it]

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000777 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.744996
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000647 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.744315
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000630 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.743163
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000685 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.740339
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000653 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.745291
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000656 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8155
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.741411
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000707 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8155
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.743497
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000651 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.744014
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000627 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.746274
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000649 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8155
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.742870
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000623 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.741741
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000625 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.740183
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000633 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.741071
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.747438
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000697 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.742863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000680 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.744785
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000580 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.746944
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000597 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8152
[LightGBM] [Info] Number of data points in the train set: 5345, number of used features: 32
[LightGBM] [Info] Start training from score -5.744125
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000564 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.741579
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000570 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.744585
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000581 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.742189
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000587 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.740668
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000555 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8154
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.741549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000584 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.739085
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000776 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 8153
[LightGBM] [Info] Number of data points in the train set: 5346, number of used features: 32
[LightGBM] [Info] Start training from score -5.737672
LGBMRegressor Evaluation completed: Test R2 score: 0.6734085056296877
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6134595036520918
RandomForestRegressor Evaluation completed: Test R2 score: 0.6667398731230871
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.670705203707308
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6400564543377263
XGBRegressor Evaluation completed: Test R2 score: 0.6659458723839302
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6707421774643382
LinearRegression Evaluation completed: Test R2 score: 0.6670753109025302
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6544102669942723
SVR Evaluation completed: Test R2 score: 0.6723519221836805
MLPRegressor Evaluation completed: Test R2 score: 0.6694561448471208

,Train MSE (25 fold CV),Train MAE (25 fold CV),Train RMSE (25 fold CV),Train R2 (25 fold CV),Train PCC (25 fold CV),Train SCC (25 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.133449,0.267803,0.365307,0.785731,0.886434,0.863422,0.206676,0.319437,0.454617,0.673409,0.822245,0.805433
DecisionTreeRegressor,0.275470,0.380663,0.524853,0.557697,0.780985,0.756471,0.244614,0.344756,0.494584,0.613460,0.788282,0.773575
RandomForestRegressor,0.134759,0.268222,0.367096,0.783626,0.885259,0.860490,0.210896,0.322679,0.459235,0.666740,0.817497,0.798132
GradientBoostingRegressor,0.134163,0.269166,0.366282,0.784585,0.885770,0.861046,0.208387,0.322093,0.456494,0.670705,0.822391,0.803513
AdaBoostRegressor,0.182120,0.330497,0.426755,0.707583,0.856202,0.835310,0.227782,0.361378,0.477266,0.640056,0.811216,0.796206
XGBRegressor,0.147650,0.281319,0.384253,0.762929,0.873854,0.848798,0.211399,0.322629,0.459781,0.665946,0.818530,0.800110
ExtraTreesRegressor,0.134501,0.266670,0.366743,0.784042,0.885500,0.861532,0.208364,0.321473,0.456469,0.670742,0.819652,0.800284
LinearRegression,0.134629,0.268502,0.366918,0.783836,0.885347,0.861079,0.210684,0.325082,0.459003,0.667075,0.817216,0.799905
KNeighborsRegressor,0.151853,0.284143,0.389684,0.756180,0.869758,0.848461,0.218699,0.334398,0.467653,0.654410,0.810607,0.797005
SVR,0.138544,0.269204,0.372214,0.777550,0.882180,0.861306,0.207345,0.320383,0.455352,0.672352,0.821922,0.805806
MLPRegressor,0.142621,0.278535,0.377652,0.771003,0.878118,0.851979,0.209178,0.326126,0.457359,0.669456,0.818786,0.800422

In [47]:
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
target_column = 'Permeability'


meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 30-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=30, shuffle=True, random_state=101)

    # Storing predictions for the current dataframe
    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models"):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)

            # Predictions for validation set
            fold_predictions[val_index] =  np.clip( model.predict(X_val), -10, -3.9)

            # Predictions for test set
            test_predictions_fold =  np.clip( model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        # Store predictions for the meta-learner
        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

# Convert lists to arrays for the meta-learner
meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=30, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        # Predictions for test set
        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test}')

    predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_eval,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

    results[model_name] = {
        'Train MSE (30 fold CV)': mse_train,
        'Train MAE (30 fold CV)': mae_train,
        'Train RMSE (30 fold CV)': rmse_train,
        'Train R2 (30 fold CV)': r2_train,
        'Train PCC (30 fold CV)': pearson_train,
        'Train SCC (30 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
prediction_df = pd.DataFrame(predictions)
results_df

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004873 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56930
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.744894
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004383 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56926
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.745640
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004728 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56937
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.742769
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004304 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56943
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.741234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004326 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56933
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.741738
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004253 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56928
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.744863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004509 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.743177
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004904 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56946
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.742620
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004511 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56933
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.740358
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004438 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56928
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.747150
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004447 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56940
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.743301
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005065 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56932
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.744275
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005120 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.743229
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004995 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.738549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004963 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.741500
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004961 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56924
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.744356
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005136 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56933
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.745007
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005034 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56927
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 263
[LightGBM] [Info] Start training from score -5.743531
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005012 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56939
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.745309
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004923 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 262
[LightGBM] [Info] Start training from score -5.745688
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005029 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56949
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.745191
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005738 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56939
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.741821
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005081 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56937
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.742663
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005059 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56926
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.744151
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005148 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56926
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.741604
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005102 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56927
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.740102
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005111 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56934
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.741895
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005093 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56928
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.742704
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005024 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56931
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.739302
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005029 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 56935
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 263
[LightGBM] [Info] Start training from score -5.738554

ining models: 1it [00:11, 11.16s/it]
ining models: 2it [03:22, 116.91s/it]
ining models: 3it [16:33, 424.92s/it]
ining models: 4it [20:16, 345.31s/it]
ining models: 5it [20:44, 230.74s/it]
ining models: 6it [21:40, 171.41s/it]
ining models: 7it [21:41, 115.68s/it]
Training models: 8it [23:33, 176.68s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [23:33<1:10:40, 1413.45s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010836 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2496
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.744894
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.011017 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2493
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.745640
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010983 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2499
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.742769
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010931 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2502
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.741234
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010853 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2496
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.741738
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010599 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2503
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.744863
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009376 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.743177
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009438 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.742620
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009365 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2499
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.740358
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009426 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2501
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.747150
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009580 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.743301
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009396 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.744275
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009561 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.743229
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009434 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2493
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.738549
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009748 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.741500
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009420 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.744356
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 801
[LightGBM] [Info] Start training from score -5.745007
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011927 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 800
[LightGBM] [Info] Start training from score -5.743531
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010288 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2503
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.745309
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009722 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2496
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 800
[LightGBM] [Info] Start training from score -5.745688
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2501
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.745191
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010311 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.741821
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009474 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2496
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 800
[LightGBM] [Info] Start training from score -5.742663
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009609 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2502
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.744151
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010046 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2498
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.741604
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009807 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2503
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.740102
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009473 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2497
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.741895
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009313 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2500
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.742704
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.009332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2499
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.739302

ining models: 1it [00:09,  9.19s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.007977 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2495
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 801
[LightGBM] [Info] Start training from score -5.738554

ining models: 2it [00:54, 30.44s/it]
ining models: 3it [03:46, 94.89s/it]
ining models: 4it [05:56, 108.82s/it]
ining models: 5it [06:21, 78.67s/it]
ining models: 6it [07:17, 70.92s/it]
ining models: 7it [07:20, 48.66s/it]
Training models: 8it [11:53, 89.18s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [35:26<33:23, 1001.69s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016331 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.744894
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015980 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.745640
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016382 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.742769
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015629 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.741234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016215 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.741738
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015877 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.744863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016236 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.743177
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015867 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.742620
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015647 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.740358
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012096 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.747150
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012257 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.743301
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014021 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.744275
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014757 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.743229
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014042 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.738549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012779 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.741500
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011724 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.744356
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013789 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.745007
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015226 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 768
[LightGBM] [Info] Start training from score -5.743531
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013885 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.745309
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.014651 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.745688
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.745191
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015421 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.741821
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012333 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.742663
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013259 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.744151
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012854 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.741604
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011541 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.740102
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.016456 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.741895
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015653 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.742704
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012664 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.739302
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.012601 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 195840
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 768
[LightGBM] [Info] Start training from score -5.738554

ining models: 1it [00:31, 31.63s/it]
ining models: 2it [16:24, 573.32s/it]
ining models: 3it [1:38:22, 2557.48s/it]
ining models: 4it [1:54:23, 1926.96s/it]
ining models: 5it [1:55:55, 1265.50s/it]
ining models: 6it [1:59:02, 898.65s/it]
ining models: 7it [1:59:04, 605.57s/it]
Training models: 8it [2:03:03, 922.95s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [2:38:30<1:05:15, 3915.82s/it]
ining models: 0it [00:00, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000339 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.744894
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000174 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.745640
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.742769
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000183 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.741234
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000187 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.741738
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.744863
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000168 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.743177
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000168 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.742620
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.740358
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000399 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.747150
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000173 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 146
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.743301
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000221 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.744275
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.743229
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000182 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.738549
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000172 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.741500
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000167 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.744356
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.745007
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000170 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 9
[LightGBM] [Info] Start training from score -5.743531
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000158 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.745309
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000154 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.745688
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000157 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.745191
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000153 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.741821
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000159 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.742663
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.744151
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000138 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.741604
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.740102
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000405 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.741895
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000132 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.742704
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.739302
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000142 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 147
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 9
[LightGBM] [Info] Start training from score -5.738554

ining models: 1it [00:02,  2.18s/it]
ining models: 2it [00:09,  5.08s/it]
ining models: 3it [00:14,  5.00s/it]
ining models: 4it [00:16,  3.96s/it]
ining models: 5it [00:18,  3.20s/it]
ining models: 6it [00:23,  3.80s/it]
ining models: 7it [00:23,  2.73s/it]
Training models: 8it [00:53,  6.66s/it]
Processing dataframe pairs: 100%|██████████| 4/4 [2:39:23<00:00, 2390.95s/it]

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 32)
Dimensions of meta_features_test: (1392, 32)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000928 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.744894
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000626 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8157
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.745640
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000629 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.742769
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000634 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.741234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000619 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.741738
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000650 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.744863
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000715 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.743177
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.742620
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000694 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.740358
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000626 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.747150
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000652 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.743301
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000663 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8157
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.744275
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000757 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.743229
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000652 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.738549
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000620 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.741500
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000614 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.744356
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000600 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.745007
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000625 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5382, number of used features: 32
[LightGBM] [Info] Start training from score -5.743531
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000604 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.745309
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000601 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.745688
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000605 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8160
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.745191
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000503 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.741821
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000477 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.742663
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000516 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.744151
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000484 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.741604
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000456 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8159
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.740102
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000468 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.741895
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000478 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.742704
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000474 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.739302
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000536 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 8158
[LightGBM] [Info] Number of data points in the train set: 5383, number of used features: 32
[LightGBM] [Info] Start training from score -5.738554
LGBMRegressor Evaluation completed: Test R2 score: 0.6740068475880657
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6496222424790848
RandomForestRegressor Evaluation completed: Test R2 score: 0.6677100726289182
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6670562294998656
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6293288913258704
XGBRegressor Evaluation completed: Test R2 score: 0.6668068501959625
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6669499075648786
LinearRegression Evaluation completed: Test R2 score: 0.6677807755896799
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6472270591169734
SVR Evaluation completed: Test R2 score: 0.6738858718916096
MLPRegressor Evaluation completed: Test R2 score: 0.670298459911871

,Train MSE (30 fold CV),Train MAE (30 fold CV),Train RMSE (30 fold CV),Train R2 (30 fold CV),Train PCC (30 fold CV),Train SCC (30 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.134439,0.268956,0.366659,0.784141,0.885521,0.862703,0.206298,0.320948,0.454200,0.674007,0.821974,0.805519
DecisionTreeRegressor,0.277885,0.384169,0.527148,0.553820,0.779953,0.750418,0.221729,0.333390,0.470881,0.649622,0.807894,0.786375
RandomForestRegressor,0.134388,0.268095,0.366590,0.784222,0.885619,0.860434,0.210282,0.324089,0.458566,0.667710,0.817758,0.798369
GradientBoostingRegressor,0.133770,0.269651,0.365746,0.785214,0.886129,0.860793,0.210696,0.323398,0.459017,0.667056,0.821171,0.802957
AdaBoostRegressor,0.187217,0.339016,0.432686,0.699399,0.855508,0.835744,0.234571,0.369689,0.484326,0.629329,0.809846,0.797981
XGBRegressor,0.145399,0.280670,0.381312,0.766543,0.876133,0.851271,0.210854,0.323227,0.459189,0.666807,0.818290,0.800905
ExtraTreesRegressor,0.133667,0.266135,0.365604,0.785381,0.886281,0.862894,0.210764,0.324057,0.459090,0.666950,0.817272,0.799563
LinearRegression,0.134531,0.268763,0.366785,0.783992,0.885435,0.861054,0.210238,0.325075,0.458517,0.667781,0.817620,0.800658
KNeighborsRegressor,0.155000,0.287133,0.393701,0.751127,0.866916,0.844189,0.223245,0.334087,0.472488,0.647227,0.806659,0.793900
SVR,0.141156,0.270519,0.375708,0.773355,0.879828,0.860480,0.206374,0.319248,0.454284,0.673886,0.822989,0.809155
MLPRegressor,0.141480,0.277780,0.376138,0.772835,0.879144,0.854993,0.208644,0.325893,0.456776,0.670298,0.819232,0.800820

In [1]:
#Starts from here
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression  # LogisticRegression is not used for regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from scipy.stats import pearsonr, spearmanr
from sklearn.model_selection import train_test_split
from tqdm import tqdm

def remove_low_variance_columns(df, threshold=0.005):
  
    variances = df.var()

    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

def features(df, target_column='Permeability', threshold=0.9):
    correlation_matrix = df.corr()
    
    features_to_drop = set()
    
    for feature in correlation_matrix.columns:
        if feature == target_column:
            continue 
        target_corr = correlation_matrix[target_column][feature]
        
        for other_feature in correlation_matrix.columns:
            if other_feature == feature or other_feature == target_column:
                continue
            
            if abs(correlation_matrix[feature][other_feature]) > threshold:
                other_target_corr = correlation_matrix[target_column][other_feature]

                if abs(other_target_corr) < abs(target_corr):
                    features_to_drop.add(other_feature)
                else:
                    features_to_drop.add(feature)
    selected_features = [col for col in df.columns if col not in features_to_drop and col != target_column]
    
    return selected_features

In [2]:
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]

# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]

print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)

def scale_features(df_train, df_test):
    scaler = StandardScaler()
    train_features = df_train.drop(columns=['ID', 'SMILES', target_column])
    test_features = df_test.drop(columns=['ID', 'SMILES', target_column])
    scaler.fit(train_features)
    train_scaled = pd.DataFrame(scaler.transform(train_features), columns=train_features.columns, index=df_train.index)
    test_scaled = pd.DataFrame(scaler.transform(test_features), columns=test_features.columns, index=df_test.index)
    df_train_scaled = pd.concat([df_train[['ID', 'SMILES', target_column]], train_scaled], axis=1)
    df_test_scaled = pd.concat([df_test[['ID', 'SMILES', target_column]], test_scaled], axis=1)
    return df_train_scaled, df_test_scaled

target_column = 'Permeability'
df_desc_train, df_desc_test = scale_features(df_desc_train, df_desc_test)
df_fp_train, df_fp_test = scale_features(df_fp_train, df_fp_test)
df_emb_train, df_emb_test = scale_features(df_emb_train, df_emb_test)
df_atomic_train, df_atomic_test = scale_features(df_atomic_train, df_atomic_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

/tmp/ipykernel_3837683/1337071642.py:2: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
/tmp/ipykernel_3837683/1337071642.py:10: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      MinEStateIndex       qed       SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4772        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4766        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4767        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4585        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
...              ...       ...       ...               ...          ...
607         0.192516 -0.775650  0.259993         -2.407555    -0.272146
726         0.653737 -0.018994  1.601452         -0.588614    -0.273699
772         0.632929 -0.119292  1.086333         -0.700759    -0.273718
5468        1.217004  1.450851 -0.469980          2.939673    -0.227462
5397       -0.865635 -1.498214 -1.692007          0.059878    -0.255008

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765 -0.023178    0.366371  ...  2.549183 -0.862324 -0.893728  0.489529
4772 -0.023178    0.366371  ...  4.965360 -0.427135  0.080585 -0.614519
4766 -0.023178    0.366371  ...  2.254608 -1.028595 -0.946363  0.326385
4767 -0.023178    0.366371  ...  2.446578 -0.126274  0.365179 -0.523457
4585  0.013981    0.379551  ...  1.369481 -1.176065 -0.916734  1.360742
...        ...         ...  ...       ...       ...       ...       ...
607  -0.094881    5.092978  ... -0.752000  0.319684  0.215975 -0.247991
726   0.694517   -1.332423  ...  0.016586 -0.171336  0.322553  1.340127
772   0.638444   -0.952883  ...  1.100970  0.171495 -0.903842  1.601925
5468  0.080729   -0.661118  ... -1.032055  1.128882  1.552470  0.054608
5397 -0.635613    0.246641  ...  2.214886 -0.752716 -0.227393  0.794083

      geomShape    RDF20i        Ku        Dm        Dv       L3p
4765  -1.020308 -0.804191 -1.025186 -0.939644 -0.249057  0.330472
4772   0.470831 -1.149778 -1.063426 -0.466831 -0.824736  0.134428
4766  -0.808816 -0.940742 -0.420312  0.312775 -0.090662 -0.600289
4767   0.462356 -0.831144 -1.760088 -0.203608  0.073430  0.976861
4585   0.285862 -1.019144  0.279728 -0.945914 -1.143574 -1.097882
...         ...       ...       ...       ...       ...       ...
607    0.462584  1.790214  1.102156  0.900813  1.346589 -0.223530
726   -0.535731  0.806143  0.429713  2.272960  2.625210 -0.313984
772    0.628743  1.051476 -0.268428  0.441640  1.239930  0.543089
5468   1.020392 -1.222162  0.024310  0.414281  0.667103 -1.301598
5397  -0.415407 -1.544547  0.272665 -0.052120 -1.523564 -1.453719

[5568 rows x 272 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed       SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
1145        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
841         0.523673  0.155095  1.135189         -1.046749    -0.202495
1146        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
755         0.471903 -0.491085  0.431312         -1.132457    -0.202496
...              ...       ...       ...               ...          ...
1147        0.424645 -0.287590 -0.115302         -0.087259    -0.255729
174         0.640728 -0.049837  1.524206         -1.029680    -0.273694
1193        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
122        -0.506947 -1.372119 -0.235774         -2.058103    -0.271840
201         0.638770  0.031128  1.205006         -0.368018    -0.273707

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192 -0.023178    0.366371  ...  2.353903  0.614132  0.622580 -0.006415
1145  0.013981    0.379551  ...  1.424061  1.350508  1.575779 -1.453956
841   0.520753   -0.868326  ...  1.021738 -0.007526 -0.963853  0.615437
1146  0.013981    0.379551  ...  1.427272  0.854581  1.293000 -0.707309
755   0.390021   -0.316906  ...  0.638439 -0.775371 -1.133743 -1.324360
...        ...         ...  ...       ...       ...       ...       ...
1147  0.005182    0.457186  ...  2.716801 -0.890349 -0.465073 -1.462677
174   0.702472   -1.307483  ...  0.426959 -0.412873 -0.339536  0.984877
1193 -0.023178    0.366371  ...  2.274467 -0.351070 -0.530575 -1.484212
122  -2.350518    5.422188  ...  1.105510  0.171519 -1.029480  0.030957
201   0.631631   -0.948414  ...  0.380814 -0.424656 -0.455166  0.815036

      geomShape    RDF20i        Ku        Dm        Dv       L3p
1192   1.137043 -1.156626 -0.365331 -0.870643 -0.493169 -0.485308
1145   0.991383 -0.762205 -0.701714 -0.497383 -0.448249  1.156991
841    0.335906 -0.705307  0.680107 -0.258616 -0.236403 -1.538582
1146   0.655610 -1.065680  1.125261 -0.942912 -0.781599 -1.020320
755   -0.003376 -0.475084 -2.423851 -0.460538 -0.739462  2.192682
...         ...       ...       ...       ...       ...       ...
1147  -0.911785 -0.487920 -2.124744 -0.168864 -0.267079  1.046081
174   -1.327195  0.965695  0.643079 -0.372127 -0.206290 -0.695965
1193  -0.072194 -0.745729 -2.755939  0.249652  0.200575  1.681682
122    0.006484  2.158762 -0.030856  1.376912  1.271913  0.600539
201   -0.718497  1.013471  0.555556  0.810642  0.919984 -0.668591

[1392 rows x 272 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4772    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4766    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4767    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4585    -0.429745     0.122258     -0.181197      1.300944     -0.296163
...           ...          ...           ...           ...           ...
607     -0.429745     0.122258     -0.181197      1.300944     -0.296163
726      2.326961     0.122258     -0.181197     -0.768672     -0.296163
772      2.326961     0.122258     -0.181197     -0.768672     -0.296163
5468    -0.429745     0.122258     -0.181197     -0.768672     -0.296163
5397    -0.429745    -8.179391     -0.181197     -0.768672     -0.296163

      Morgan_fp_84  Morgan_fp_94  ...   SubFPC2  SubFPC100  SubFPC101  \
4765     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4772     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4766     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4767     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4585     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
...            ...           ...  ...       ...        ...        ...
607      -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
726      -0.373919     -0.406921  ...  6.363355   -0.50779  -0.605817
772      -0.373919     -0.406921  ...  4.495903   -0.50779  -0.605817
5468     -0.373919     -0.406921  ... -1.573315   -0.50779  -0.605817
5397     -0.373919     -0.406921  ... -1.106452   -0.50779  -0.605817

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4772  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4766  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4767  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4585  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
...         ...        ...        ...        ...        ...        ...
607    2.434504  -0.060896  -0.040882   -0.05219  -0.093837   1.818822
726   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
772   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
5468  -2.323232  -0.060896  -0.040882   -0.05219   9.581758   0.161704
5397  -0.737320  -0.060896  -0.040882   -0.05219  -0.093837  -1.495414

      SubFPC302
4765  -0.421116
4772  -0.421116
4766  -0.421116
4767  -0.421116
4585  -0.196025
...         ...
607    0.479248
726   -0.646207
772   -0.421116
5468  -1.546572
5397  -0.196025

[5568 rows x 1125 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192    -0.429745     0.122258     -0.181197      1.300944     -0.296163
1145    -0.429745     0.122258     -0.181197      1.300944     -0.296163
841     -0.429745     0.122258     -0.181197      1.300944     -0.296163
1146    -0.429745     0.122258     -0.181197      1.300944     -0.296163
755     -0.429745     0.122258     -0.181197      1.300944     -0.296163
...           ...          ...           ...           ...           ...
1147    -0.429745     0.122258     -0.181197      1.300944     -0.296163
174      2.326961     0.122258     -0.181197     -0.768672     -0.296163
1193    -0.429745     0.122258     -0.181197      1.300944     -0.296163
122     -0.429745     0.122258     -0.181197      1.300944     -0.296163
201      2.326961     0.122258     -0.181197     -0.768672     -0.296163

      Morgan_fp_84  Morgan_fp_94  ...   SubFPC2  SubFPC100  SubFPC101  \
1192     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
1145     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
841      -0.373919     -0.406921  ...  0.761000   -0.50779  -0.605817
1146     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
755      -0.373919     -0.406921  ...  0.294137   -0.50779  -0.605817
...            ...           ...  ...       ...        ...        ...
1147     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
174      -0.373919     -0.406921  ...  5.896492   -0.50779  -0.605817
1193     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
122      -0.373919     -0.406921  ...  0.761000   -0.50779  -0.605817
201      -0.373919     -0.406921  ...  4.029040   -0.50779  -0.605817

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
1145  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
841    0.319955  -0.060896  -0.040882   -0.05219  -0.093837  -0.390669
1146  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
755    0.319955  -0.060896  -0.040882   -0.05219  -0.093837  -0.390669
...         ...        ...        ...        ...        ...        ...
1147  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
174   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
1193  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
122    2.434504  -0.060896  -0.040882   -0.05219  -0.093837   1.818822
201   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194

      SubFPC302
1192  -0.421116
1145  -0.196025
841   -0.646207
1146  -0.196025
755   -0.196025
...         ...
1147  -0.421116
174   -0.646207
1193  -0.421116
122    1.379613
201   -0.646207

[1392 rows x 1125 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765         -1.362835          0.676766          2.263783         -0.029669
4772         -1.456499          0.942374          2.453267         -0.553083
4766         -1.408479          0.817561          2.605919         -0.529222
4767         -1.330524          0.999033          2.326873         -0.147679
4585         -0.894590          0.494381          1.352529         -0.675206
...                ...               ...               ...               ...
607          -2.747507          1.750885          1.810705          0.230750
726          -1.373444         -2.027777         -0.250508         -2.129512
772          -0.927683         -1.112633          0.068899         -1.012287
5468         -2.390418          2.349158          3.353966         -3.869338
5397         -1.046327          0.956775          1.171487          0.283242

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -1.132996         -3.127902         -2.510145  ...
4772          0.116345         -2.304301         -0.861316  ...
4766         -0.206309         -1.355997          0.071421  ...
4767         -0.758140         -3.103643         -2.145222  ...
4585          0.282418         -1.659310          0.314493  ...
...                ...               ...               ...  ...
607           1.450898         -2.019132          1.725549  ...
726          -1.432930         -0.702973         -1.229294  ...
772          -1.162808         -0.852733         -1.057444  ...
5468          2.022765         -2.097583         -2.313748  ...
5397         -4.903409          1.467003         -0.387383  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765           -1.105586            3.960163            0.980052
4772           -0.932800            3.926889            0.758840
4766           -1.258645            3.572499            0.279440
4767           -1.162212            3.601063            0.980804
4585           -0.671984            1.538951           -0.029645
...                  ...                 ...                 ...
607            -0.437313            1.255007           -2.375371
726            -0.358299           -0.054864            0.181493
772            -0.395752           -0.441349            0.819312
5468            0.721880            2.183873           -1.349979
5397           -0.650120            3.373594            1.599388

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765            1.599023           -1.054547            1.401074
4772            1.676068           -0.686548            1.818805
4766            1.500911           -1.071328            1.778308
4767            1.372863           -1.059771            1.355451
4585           -1.113566           -0.229579            1.102657
...                  ...                 ...                 ...
607            -1.491044            0.921095            2.804574
726            -1.270647            0.459133            0.219489
772            -0.341048            0.290987            0.545666
5468            0.246066            0.634043            5.432239
5397            5.554441           -0.465011            0.593758

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765            1.480165            1.386261           -1.362624
4772            2.307867            1.854912           -1.461679
4766            1.812858            1.742596           -1.043169
4767            1.474285            1.301570           -1.320077
4585            1.643638            1.026417           -2.035947
...                  ...                 ...                 ...
607             1.898821            1.917739            0.379968

In [3]:
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101, eval_metric='rmse'),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101, max_iter=500),
    DecisionTreeRegressor(random_state=101)
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101, eval_metric='rmse'),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101, max_iter=500)
]
target_column = 'Permeability'
dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]

meta_features_train = []
meta_features_test = []

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1: Training weak learners with 5-fold CV')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 1: Train weak learners with 5-fold cross-validation
for df_train, df_test in tqdm(dataframes, desc="Processing dataframe pairs"):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_eval = df_test[target_column]
    
    kf = KFold(n_splits=5, shuffle=True, random_state=101)

    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models", total=len(models_weak)):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for train_index, val_index in kf.split(X_weak):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]

            model.fit(X_train, y_train)

            fold_predictions[val_index] = np.clip(model.predict(X_val), -10, -3.9)
            test_predictions_fold = np.clip(model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)
        print(f'Model training done {i}')

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)

meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 2: Training meta-learners with 5-fold CV')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')


results = {}
predictions = []

kf = KFold(n_splits=5, shuffle=True, random_state=101)

for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    test_predictions_folds = []

    for train_index, val_index in kf.split(meta_features_train):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]

        model.fit(X_fold_train, y_fold_train)
        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)

        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    
    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)

    print(f'{model_name} Evaluation completed: Test R2 score: {r2_test:.4f}, Test RMSE: {rmse_test:.4f}')

    predictions.append({
        'Model': model_name,
        'Y Train pred': predictions_train,
        'Y Train actual': actual_y_train,
        'Y Test actual': y_eval,
        'Test Predictions folds': test_predictions_folds,
        'Test Predictions Mean': predictions_test_mean,
        'Test Predictions Std': predictions_test_std,
    })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T
predictions_df = pd.DataFrame(predictions)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stacked Ensemble Training and Evaluation complete')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

results_df

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1: Training weak learners with 5-fold CV
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]
Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010164 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57086
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008969 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57104
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009071 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 262
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008758 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57103
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008777 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 263
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:04<00:41,  4.62s/it]

Model training done 0

Training models:  20%|██        | 2/10 [00:11<00:46,  5.80s/it]

Model training done 1

Training models:  30%|███       | 3/10 [02:03<06:19, 54.18s/it]

Model training done 2

Training models:  40%|████      | 4/10 [02:36<04:36, 46.06s/it]

Model training done 3

Training models:  50%|█████     | 5/10 [02:41<02:35, 31.03s/it]

Model training done 4

Training models:  60%|██████    | 6/10 [02:43<01:25, 21.34s/it]

Model training done 5

Training models:  70%|███████   | 7/10 [02:44<00:44, 14.71s/it]

Model training done 6

Training models:  80%|████████  | 8/10 [02:58<00:28, 14.46s/it]

Model training done 7

Training models:  90%|█████████ | 9/10 [03:13<00:14, 14.67s/it]

Model training done 8

Training models: 100%|██████████| 10/10 [03:18<00:00, 19.85s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:18<09:55, 198.48s/it]

Model training done 9

Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.041458 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4154
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1096
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.040631 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1098
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042442 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1099
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.041327 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4165
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.041476 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4137
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1094
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:06<01:01,  6.88s/it]

Model training done 0

Training models:  20%|██        | 2/10 [00:10<00:37,  4.71s/it]

Model training done 1

Training models:  30%|███       | 3/10 [00:41<01:57, 16.83s/it]

Model training done 2

Training models:  40%|████      | 4/10 [01:10<02:11, 21.89s/it]

Model training done 3

Training models:  50%|█████     | 5/10 [01:15<01:17, 15.53s/it]

Model training done 4

Training models:  60%|██████    | 6/10 [01:18<00:44, 11.21s/it]

Model training done 5

Training models:  70%|███████   | 7/10 [01:19<00:23,  7.87s/it]

Model training done 6

Training models:  80%|████████  | 8/10 [02:30<00:56, 28.09s/it]

Model training done 7

Training models:  90%|█████████ | 9/10 [03:03<00:29, 29.74s/it]

Model training done 8

Training models: 100%|██████████| 10/10 [03:05<00:00, 18.52s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:23<06:21, 190.67s/it]

Model training done 9

Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020044 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019606 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019515 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020004 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020011 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:04<00:40,  4.52s/it]

Model training done 0

Training models:  20%|██        | 2/10 [00:31<02:22, 17.86s/it]

Model training done 1

Training models:  30%|███       | 3/10 [10:53<34:15, 293.68s/it]

Model training done 2

Training models:  40%|████      | 4/10 [13:21<23:37, 236.31s/it]

Model training done 3

Training models:  50%|█████     | 5/10 [13:36<13:02, 156.50s/it]

Model training done 4

Training models:  60%|██████    | 6/10 [13:43<07:01, 105.43s/it]

Model training done 5

Training models:  70%|███████   | 7/10 [13:44<03:33, 71.26s/it]

Model training done 6

Training models:  80%|████████  | 8/10 [14:17<01:58, 59.31s/it]

Model training done 7

Training models:  90%|█████████ | 9/10 [14:39<00:47, 47.50s/it]

Model training done 8

Training models: 100%|██████████| 10/10 [15:02<00:00, 90.29s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [21:26<08:35, 515.90s/it]

Model training done 9

Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001017 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001064 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001181 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001036 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001039 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:02<00:25,  2.85s/it]

Model training done 0

Training models:  20%|██        | 2/10 [00:04<00:19,  2.38s/it]

Model training done 1

Training models:  30%|███       | 3/10 [00:05<00:11,  1.58s/it]

Model training done 2

Training models:  40%|████      | 4/10 [00:05<00:06,  1.08s/it]

Model training done 3

Training models:  50%|█████     | 5/10 [00:06<00:05,  1.05s/it]

Model training done 4

Training models:  60%|██████    | 6/10 [00:08<00:04,  1.20s/it]

Model training done 5

Training models:  70%|███████   | 7/10 [00:08<00:02,  1.12it/s]

Model training done 6

Training models:  80%|████████  | 8/10 [00:12<00:03,  1.72s/it]

Model training done 7

Training models: 100%|██████████| 10/10 [00:18<00:00,  1.84s/it][A
Processing dataframe pairs: 100%|██████████| 4/4 [21:45<00:00, 326.26s/it]

Model training done 8
Model training done 9
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 40)
Dimensions of meta_features_test: (1392, 40)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 2: Training meta-learners with 5-fold CV
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.032079 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 9974
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004766 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9965
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001637 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9958
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001645 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9969
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001531 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9960
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

LGBMRegressor Evaluation completed: Test R2 score: 0.6828, Test RMSE: 0.4491
DecisionTreeRegressor Evaluation completed: Test R2 score: 0.6279, Test RMSE: 0.4864
RandomForestRegressor Evaluation completed: Test R2 score: 0.6760, Test RMSE: 0.4539
GradientBoostingRegressor Evaluation completed: Test R2 score: 0.6837, Test RMSE: 0.4484
AdaBoostRegressor Evaluation completed: Test R2 score: 0.6457, Test RMSE: 0.4746
XGBRegressor Evaluation completed: Test R2 score: 0.6799, Test RMSE: 0.4511
ExtraTreesRegressor Evaluation completed: Test R2 score: 0.6799, Test RMSE: 0.4511
LinearRegression Evaluation completed: Test R2 score: 0.6841, Test RMSE: 0.4482
KNeighborsRegressor Evaluation completed: Test R2 score: 0.6729, Test RMSE: 0.4560
SVR Evaluation completed: Test R2 score: 0.6838, Test RMSE: 0.4483
MLPRegressor Evaluation completed: Test R2 score: 0.6847, Test RMSE: 0.4477
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stacked Ensemble Training and Evaluation complete
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.130804,0.263265,0.361669,0.789909,0.888776,0.869515,0.201693,0.319754,0.449103,0.682756,0.826496,0.808945
DecisionTreeRegressor,0.270973,0.378354,0.520551,0.564778,0.784394,0.762136,0.236596,0.347319,0.486411,0.627858,0.795004,0.770803
RandomForestRegressor,0.131933,0.263568,0.363226,0.788097,0.887827,0.868264,0.205993,0.321869,0.453865,0.675993,0.822472,0.804549
GradientBoostingRegressor,0.132535,0.263729,0.364053,0.787130,0.887212,0.869571,0.201084,0.318528,0.448424,0.683714,0.827135,0.810621
AdaBoostRegressor,0.179677,0.326289,0.423884,0.711412,0.855398,0.844066,0.225232,0.362888,0.474586,0.645732,0.812755,0.802958
XGBRegressor,0.148944,0.283138,0.385932,0.760775,0.873051,0.851295,0.203508,0.322258,0.451118,0.679902,0.824879,0.808516
ExtraTreesRegressor,0.129376,0.261755,0.359689,0.792203,0.890148,0.870762,0.203513,0.320260,0.451125,0.679893,0.824734,0.806362
LinearRegression,0.130094,0.260845,0.360685,0.791050,0.889418,0.870665,0.200851,0.318182,0.448164,0.684081,0.827305,0.809476
KNeighborsRegressor,0.156627,0.289646,0.395761,0.748434,0.865125,0.846564,0.207948,0.324723,0.456013,0.672919,0.820607,0.802593
SVR,0.139158,0.267421,0.373039,0.776492,0.881567,0.868309,0.201015,0.316555,0.448348,0.683822,0.828109,0.812628
MLPRegressor,0.140628,0.274075,0.375004,0.774131,0.881120,0.862041,0.200436,0.316549,0.447701,0.684733,0.829986,0.811817

In [4]:
results_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/Stacked_architecture/Results_5_fold_stacked_prediction_LVR_scaled.csv')
predictions_df.to_csv('/home/users/akshay/PCPpred/PAMPA/Results/Stacked_architecture/Prediction_data_Meta_learners_5_fold_stacked_prediction_LVR_scaled.csv')

In [5]:
# Ensure the models directory exists
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from scipy.stats import pearsonr, spearmanr
import lightgbm as lgb
import xgboost as xgb
from tqdm import tqdm
import joblib
os.makedirs('/home/users/akshay/PCPpred/PAMPA/pampa_models/', exist_ok=True)

# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'], axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features_desc = features(train, "Permeability")
joblib.dump(selected_features_desc, '/home/users/akshay/PCPpred/PAMPA/pampa_models/selected_features_descriptors.joblib')
df_desc_train = pd.concat([df_train[['ID','SMILES','Permeability']], df_train[selected_features_desc]], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test = df_desc_test.dropna()
df_desc_test = df_desc_test[df_desc_train.columns]

# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'], axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features_fp = features(train, "Permeability")
joblib.dump(selected_features_fp, '/home/users/akshay/PCPpred/PAMPA/pampa_models/selected_features_fingerprints.joblib')
df_fp_train = pd.concat([df_train[['ID','SMILES','Permeability']], df_train[selected_features_fp]], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test = df_fp_test[df_fp_train.columns]

# Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'], axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features_emb = features(train, "Permeability")
joblib.dump(selected_features_emb, '/home/users/akshay/PCPpred/PAMPA/pampa_models/selected_features_embeddings.joblib')
df_emb_train = pd.concat([df_train[['ID','SMILES','Permeability']], df_train[selected_features_emb]], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test = df_emb_test[df_emb_train.columns]

# Atomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'], axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features_atomic = features(train, "Permeability")
joblib.dump(selected_features_atomic, '/home/users/akshay/PCPpred/PAMPA/pampa_models/selected_features_atomic.joblib')
df_atomic_train = pd.concat([df_train[['ID','SMILES','Permeability']], df_train[selected_features_atomic]], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test = df_atomic_test[df_atomic_train.columns]

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Filter dataframes to have consistent IDs
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]
df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]
df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

target_column = 'Permeability'

def scale_features(df_train, df_test, feature_type):
    scaler = StandardScaler()
    train_features = df_train.drop(columns=['ID', 'SMILES', target_column])
    test_features = df_test.drop(columns=['ID', 'SMILES', target_column])
    scaler.fit(train_features)
    train_scaled = pd.DataFrame(scaler.transform(train_features), columns=train_features.columns, index=df_train.index)
    test_scaled = pd.DataFrame(scaler.transform(test_features), columns=test_features.columns, index=df_test.index)
    df_train_scaled = pd.concat([df_train[['ID', 'SMILES', target_column]], train_scaled], axis=1)
    df_test_scaled = pd.concat([df_test[['ID', 'SMILES', target_column]], test_scaled], axis=1)
    # Save the scaler
    joblib.dump(scaler, f'/home/users/akshay/PCPpred/PAMPA/pampa_models/scaler_{feature_type}.joblib')
    return df_train_scaled, df_test_scaled

df_desc_train, df_desc_test = scale_features(df_desc_train, df_desc_test, 'Descriptor')
df_fp_train, df_fp_test = scale_features(df_fp_train, df_fp_test, 'Fingerprints')
df_emb_train, df_emb_test = scale_features(df_emb_train, df_emb_test, 'Embeddings')
df_atomic_train, df_atomic_test = scale_features(df_atomic_train, df_atomic_test , 'Atomic')

models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101, max_iter=500),
    DecisionTreeRegressor(random_state=101),
]

models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101)
]

dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]
data_names = ['descriptors', 'fingerprints', 'embeddings', 'atomic']

meta_features_train = []
meta_features_test = []

# Stage 1: Train weak learners with 5-fold cross-validation
for df_idx, (df_train, df_test) in enumerate(tqdm(dataframes, desc="Processing dataframe pairs")):
    X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
    X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
    y_weak = df_train[target_column]
    y_eval = df_test[target_column]

    kf = KFold(n_splits=5, shuffle=True, random_state=101)

    fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
    fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

    for i, model in tqdm(enumerate(models_weak), desc="Training models", total=len(models_weak)):
        fold_predictions = np.zeros(X_weak.shape[0])
        test_predictions_folds = []

        for fold_idx, (train_index, val_index) in enumerate(kf.split(X_weak)):
            X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
            y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
            
            model.fit(X_train, y_train)
            
            model_name = model.__class__.__name__
            joblib.dump(model, f'/home/users/akshay/PCPpred/PAMPA/pampa_models/weak_{data_names[df_idx]}_{model_name}_fold_{fold_idx}.joblib')

            fold_predictions[val_index] = np.clip(model.predict(X_val), -10, -3.9)

            test_predictions_fold = np.clip(model.predict(X_eval), -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        fold_meta_features_train[:, i] = fold_predictions
        fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)

    meta_features_train.append(fold_meta_features_train)
    meta_features_test.append(fold_meta_features_test)
    
    joblib.dump(fold_meta_features_train, f'/home/users/akshay/PCPpred/PAMPA/pampa_models/meta_features_train_{data_names[df_idx]}.joblib')
    joblib.dump(fold_meta_features_test, f'/home/users/akshay/PCPpred/PAMPA/pampa_models/meta_features_test_{data_names[df_idx]}.joblib')

meta_features_train = np.hstack(meta_features_train)
meta_features_test = np.hstack(meta_features_test)

joblib.dump(meta_features_train, '/home/users/akshay/PCPpred/PAMPA/pampa_models/meta_features_train_combined.joblib')
joblib.dump(meta_features_test, '/home/users/akshay/PCPpred/PAMPA/pampa_models/meta_features_test_combined.joblib')

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print("Dimensions of meta_features_train:", meta_features_train.shape)
print("Dimensions of meta_features_test:", meta_features_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Stage 1 completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

# Stage 2: Train the meta-learner using predictions from weak learners
kf = KFold(n_splits=5, shuffle=True, random_state=101)
results = {}
predictions = []
for model in models_meta:
    model_name = model.__class__.__name__
    predictions_train = []
    actual_y_train = []
    
    test_predictions_folds = []

    for fold_idx, (train_index, val_index) in enumerate(kf.split(meta_features_train)):
        X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
        y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]
        
        model.fit(X_fold_train, y_fold_train)
        
        joblib.dump(model, f'/home/users/akshay/PCPpred/PAMPA/pampa_models/meta_{model_name}_fold_{fold_idx}.joblib')

        y_pred_fold = model.predict(X_fold_val)
        y_pred_fold = np.clip(y_pred_fold, -10, -3.9)
        predictions_train.extend(y_pred_fold)
        actual_y_train.extend(y_fold_val)

        test_predictions_fold = model.predict(meta_features_test)
        test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
        test_predictions_folds.append(test_predictions_fold)

    # Metrics
    predictions_test_mean = np.mean(test_predictions_folds, axis=0)
    predictions_test_std = np.std(test_predictions_folds, axis=0)

    mse_train = mean_squared_error(actual_y_train, predictions_train)
    mae_train = mean_absolute_error(actual_y_train, predictions_train)
    rmse_train = np.sqrt(mse_train)
    r2_train = r2_score(actual_y_train, predictions_train)
    pearson_train, _ = pearsonr(actual_y_train, predictions_train)
    spearman_train, _ = spearmanr(actual_y_train, predictions_train)

    mse_test = mean_squared_error(y_eval, predictions_test_mean)
    mae_test = mean_absolute_error(y_eval, predictions_test_mean)
    rmse_test = np.sqrt(mse_test)
    r2_test = r2_score(y_eval, predictions_test_mean)
    pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
    spearman_test, _ = spearmanr(y_eval, predictions_test_mean)
    

    predictions.append({
        'Model': model_name,
        'Y Train pred': predictions_train,
        'Y Test actual': y_eval,
        'Test prediction folds': test_predictions_folds,
        'Test Predictions Mean': predictions_test_mean,
        'Test Predictions Std': predictions_test_mean,
    })

    results[model_name] = {
        'Train MSE (5 fold CV)': mse_train,
        'Train MAE (5 fold CV)': mae_train,
        'Train RMSE (5 fold CV)': rmse_train,
        'Train R2 (5 fold CV)': r2_train,
        'Train PCC (5 fold CV)': pearson_train,
        'Train SCC (5 fold CV)': spearman_train,
        'Test MSE': mse_test,
        'Test MAE': mae_test,
        'Test RMSE': rmse_test,
        'Test R2': r2_test,
        'Test PCC': pearson_test,
        'Test SCC': spearman_test,
    }

results_df = pd.DataFrame(results).T

/tmp/ipykernel_3837683/4144008987.py:22: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
/tmp/ipykernel_3837683/4144008987.py:31: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765       -1.126245  0.215270  26.000000          0.568627    16.254973
4772       -1.126245  0.215270  26.000000          0.568627    16.254973
4766       -1.126245  0.215270  26.000000          0.568627    16.254973
4767       -1.126245  0.215270  26.000000          0.568627    16.254973
4585       -1.057909  0.233167  25.673077          0.576923    16.465390
...              ...       ...        ...               ...          ...
607        -1.208204  0.194882  26.621951          0.378049    16.190089
726        -1.044795  0.274599  29.051282          0.564103    16.183951
772        -1.052167  0.264032  28.118421          0.552632    16.183876
5468       -0.845231  0.429454  25.300000          0.925000    16.366728
5397       -1.583104  0.118757  23.086957          0.630435    16.257835

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765  3.524800    2.105859  ...  2.430700  1.142238  1.048267  1.480800
4772  3.524800    2.105859  ...  4.070636  1.210992  1.210992  1.316793
4766  3.524800    2.105859  ...  2.230762  1.115970  1.039476  1.456565
4767  3.524800    2.105859  ...  2.361059  1.258523  1.258523  1.330320
4585  3.555194    2.111795  ...  1.629998  1.092672  1.044424  1.610220
...        ...         ...  ...       ...       ...       ...       ...
607   3.466151    4.234460  ...  0.190083  1.328978  1.233604  1.371241
726   4.111830    1.340817  ...  0.711746  1.251404  1.251404  1.607157
772   4.065966    1.511740  ...  1.447752  1.305566  1.046577  1.646048
5468  3.609789    1.643135  ...  0.000000  1.456819  1.456819  1.416192
5397  3.023866    2.051939  ...  2.203802  1.159555  1.159555  1.526042

      geomShape     RDF20i        Ku        Dm        Dv       L3p
4765   0.673083  37.497234  0.306387  0.830750  1.116415  3.731616
4772   0.837583  32.555148  0.303578  0.878246  1.056768  3.491131
4766   0.696414  35.544485  0.350821  0.956561  1.132826  2.589863
4767   0.836648  37.111802  0.252402  0.904688  1.149828  4.524533
4585   0.817177  34.423287  0.402246  0.830120  1.023732  1.979472
...         ...        ...       ...       ...       ...       ...
607    0.836673  74.598684  0.462660  1.015632  1.281742  3.052028
726    0.726541  60.525912  0.413263  1.153470  1.414222  2.941070
772    0.855003  64.034324  0.361978  0.969506  1.270691  3.992431
5468   0.898209  31.520026  0.383483  0.966758  1.211339  1.729576
5397   0.739815  26.909732  0.401727  0.919906  0.984361  1.542971

[5568 rows x 272 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed        SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192       -1.126245  0.215270  26.000000          0.568627    16.254973
1145       -1.057909  0.233167  25.673077          0.576923    16.465390
841        -1.090876  0.292940  28.206897          0.517241    16.465422
1146       -1.057909  0.233167  25.673077          0.576923    16.465390
755        -1.109218  0.224862  26.932203          0.508475    16.465419
...              ...       ...        ...               ...          ...
1147       -1.125961  0.246302  25.942308          0.615385    16.254985
174        -1.049404  0.271350  28.911392          0.518987    16.183972
1193       -1.126245  0.215270  26.000000          0.568627    16.254973
122        -1.456022  0.132042  25.724138          0.413793    16.191299
201        -1.050097  0.279880  28.333333          0.586667    16.183920

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192  3.524800    2.105859  ...  2.298157  1.375496  1.301513  1.407127
1145  3.555194    2.111795  ...  1.667044  1.491832  1.460711  1.192094
841   3.969702    1.549820  ...  1.393975  1.277283  1.036555  1.499504
1146  3.555194    2.111795  ...  1.669223  1.413483  1.413483  1.303009
755   3.862771    1.798149  ...  1.133817  1.155976  1.008181  1.211346
...        ...         ...  ...       ...       ...       ...       ...
1147  3.547997    2.146757  ...  2.544467  1.137811  1.119858  1.190799
174   4.118337    1.352048  ...  0.990279  1.213245  1.140825  1.554385
1193  3.524800    2.105859  ...  2.244241  1.223009  1.108919  1.187600
122   1.621178    4.382718  ...  1.450833  1.305570  1.025594  1.412679
201   4.060393    1.513753  ...  0.958959  1.211383  1.121513  1.529155

      geomShape     RDF20i        Ku        Dm        Dv       L3p
1192   0.911078  32.457227  0.354860  0.837682  1.091122  2.730909
1145   0.895009  38.097663  0.330150  0.875177  1.095776  4.745496
841    0.822698  38.911337  0.431657  0.899162  1.117726  1.438870
1146   0.857967  33.757802  0.464358  0.830422  1.061237  2.074616
755    0.785269  42.203657  0.203643  0.878878  1.065603  6.015966
...         ...        ...       ...       ...       ...       ...
1147   0.685055  42.020096  0.225615  0.908178  1.114547  4.609444
174    0.639228  62.807597  0.428937  0.887760  1.120846  2.472498
1193   0.777677  38.333275  0.179248  0.950220  1.163002  5.389128
122    0.786357  79.869122  0.379430  1.063458  1.274005  4.062904
201    0.706378  63.490823  0.422508  1.006574  1.237541  2.506078

[1392 rows x 272 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765            0            1             0             1             0
4772            0            1             0             1             0
4766            0            1             0             1             0
4767            0            1             0             1             0
4585            0            1             0             1             0
...           ...          ...           ...           ...           ...
607             0            1             0             1             0
726             1            1             0             0             0
772             1            1             0             0             0
5468            0            1             0             0             0
5397            0            0             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
4765             0             0  ...      7.0        0.0        0.0
4772             0             0  ...      7.0        0.0        0.0
4766             0             0  ...      7.0        0.0        0.0
4767             0             0  ...      7.0        0.0        0.0
4585             0             0  ...      7.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
607              0             0  ...      7.0        0.0        0.0
726              0             0  ...     22.0        0.0        0.0
772              0             0  ...     18.0        0.0        0.0
5468             0             0  ...      5.0        0.0        0.0
5397             0             0  ...      6.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765        6.0        0.0        0.0        0.0        0.0        6.0
4772        6.0        0.0        0.0        0.0        0.0        6.0
4766        6.0        0.0        0.0        0.0        0.0        6.0
4767        6.0        0.0        0.0        0.0        0.0        6.0
4585        6.0        0.0        0.0        0.0        0.0        6.0
...         ...        ...        ...        ...        ...        ...
607        11.0        0.0        0.0        0.0        0.0       11.0
726         6.0        0.0        0.0        0.0        0.0       12.0
772         6.0        0.0        0.0        0.0        0.0       12.0
5468        2.0        0.0        0.0        0.0        1.0        8.0
5397        5.0        0.0        0.0        0.0        0.0        5.0

      SubFPC302
4765       10.0
4772       10.0
4766       10.0
4767       10.0
4585       11.0
...         ...
607        14.0
726         9.0
772        10.0
5468        5.0
5397       11.0

[5568 rows x 1125 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192            0            1             0             1             0
1145            0            1             0             1             0
841             0            1             0             1             0
1146            0            1             0             1             0
755             0            1             0             1             0
...           ...          ...           ...           ...           ...
1147            0            1             0             1             0
174             1            1             0             0             0
1193            0            1             0             1             0
122             0            1             0             1             0
201             1            1             0             0             0

      Morgan_fp_84  Morgan_fp_94  ...  SubFPC2  SubFPC100  SubFPC101  \
1192             0             0  ...      7.0        0.0        0.0
1145             0             0  ...      7.0        0.0        0.0
841              0             0  ...     10.0        0.0        0.0
1146             0             0  ...      7.0        0.0        0.0
755              0             0  ...      9.0        0.0        0.0
...            ...           ...  ...      ...        ...        ...
1147             0             0  ...      7.0        0.0        0.0
174              0             0  ...     21.0        0.0        0.0
1193             0             0  ...      7.0        0.0        0.0
122              0             0  ...     10.0        0.0        0.0
201              0             0  ...     17.0        0.0        0.0

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192        6.0        0.0        0.0        0.0        0.0        6.0
1145        6.0        0.0        0.0        0.0        0.0        6.0
841         7.0        0.0        0.0        0.0        0.0        7.0
1146        6.0        0.0        0.0        0.0        0.0        6.0
755         7.0        0.0        0.0        0.0        0.0        7.0
...         ...        ...        ...        ...        ...        ...
1147        6.0        0.0        0.0        0.0        0.0        6.0
174         6.0        0.0        0.0        0.0        0.0       12.0
1193        6.0        0.0        0.0        0.0        0.0        6.0
122        11.0        0.0        0.0        0.0        0.0       11.0
201         6.0        0.0        0.0        0.0        0.0       12.0

      SubFPC302
1192       10.0
1145       11.0
841         9.0
1146       11.0
755        11.0
...         ...
1147       10.0
174         9.0
1193       10.0
122        18.0
201         9.0

[1392 rows x 1125 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765          0.521369          0.212180         -0.414645          1.520529
4772          0.505053          0.268161         -0.370972          1.451195
4766          0.513418          0.241855         -0.335789          1.454356
4767          0.526997          0.280103         -0.400104          1.504897
4585          0.602933          0.173739         -0.624672          1.435018
...                ...               ...               ...               ...
607           0.280170          0.438568         -0.519071          1.555026
726           0.519521         -0.357846         -0.994143          1.242372
772           0.597169         -0.164965         -0.920525          1.390366
5468          0.342372          0.564664         -0.163378          1.011905
5397          0.576502          0.271196         -0.666399          1.561979

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -1.481548         -0.630109         -0.864465  ...
4772         -1.263419         -0.528332         -0.601857  ...
4766         -1.319753         -0.411146         -0.453301  ...
4767         -1.416100         -0.627111         -0.806344  ...
4585         -1.234424         -0.448628         -0.414587  ...
...                ...               ...               ...  ...
607          -1.030414         -0.493093         -0.189849  ...
726          -1.533915         -0.330448         -0.660465  ...
772          -1.486753         -0.348955         -0.633094  ...
5468         -0.930568         -0.502787         -0.833185  ...
5397         -2.139842         -0.062293         -0.526374  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765           -0.053632           -0.967271            0.084066
4772           -0.019566           -0.973913            0.048744
4766           -0.083808           -1.044659           -0.027806
4767           -0.064796           -1.038957            0.084186
4585            0.031855           -1.450609           -0.077160
...                  ...                 ...                 ...
607             0.078122           -1.507292           -0.451719
726             0.093700           -1.768777           -0.043446
772             0.086316           -1.845930            0.058400
5468            0.306663           -1.321866           -0.287987
5397            0.036166           -1.084366            0.182960

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765            1.655962           -0.825284            0.554005
4772            1.667660           -0.763745            0.638149
4766            1.641066           -0.828090            0.629992
4767            1.621625           -0.826157            0.544815
4585            1.244119           -0.687328            0.493893
...                  ...                 ...                 ...
607             1.186808           -0.494905            0.836716
726             1.220270           -0.572157            0.315994
772             1.361408           -0.600276            0.381697
5468            1.450547           -0.542908            1.366015
5397            2.256500           -0.726698            0.391384

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765           -1.794645            0.453423           -0.944748
4772           -1.510309            0.554446           -0.961709
4766           -1.680357            0.530235           -0.890050
4767           -1.796665            0.435166           -0.937463
4585           -1.738488            0.375854           -1.060037
...                  ...                 ...                 ...
607            -1.650827            0.567989           -0.646376
726            -2.349651            0.216360           -0.551080
772            -2.347519            0.220011           -0.757118

Processing dataframe pairs:   0%|          | 0/4 [00:00<?, ?it/s]
Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009032 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57086
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008863 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57104
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007781 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 262
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008808 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57103
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008277 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 263
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:04<00:37,  4.12s/it]
Training models:  20%|██        | 2/10 [00:17<01:15,  9.41s/it]
Training models:  30%|███       | 3/10 [02:08<06:32, 56.10s/it]
Training models:  40%|████      | 4/10 [02:42<04:43, 47.25s/it]
Training models:  50%|█████     | 5/10 [02:46<02:38, 31.65s/it]
Training models:  60%|██████    | 6/10 [02:54<01:33, 23.46s/it]
Training models:  70%|███████   | 7/10 [02:55<00:48, 16.26s/it]
Training models:  80%|████████  | 8/10 [03:10<00:31, 15.72s/it]
Training models:  90%|█████████ | 9/10 [03:24<00:15, 15.27s/it]
Training models: 100%|██████████| 10/10 [03:29<00:00, 20.93s/it]
Processing dataframe pairs:  25%|██▌       | 1/4 [03:29<10:27, 209.26s/it]
Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.043609 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4154
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1096
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042692 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1098
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042144 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1099
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042845 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4165
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.042217 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4137
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1094
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:06<00:59,  6.56s/it]
Training models:  20%|██        | 2/10 [00:10<00:39,  4.96s/it]
Training models:  30%|███       | 3/10 [00:41<01:59, 17.09s/it]
Training models:  40%|████      | 4/10 [01:22<02:38, 26.36s/it]
Training models:  50%|█████     | 5/10 [01:27<01:32, 18.50s/it]
Training models:  60%|██████    | 6/10 [01:30<00:53, 13.41s/it]
Training models:  70%|███████   | 7/10 [01:33<00:30, 10.11s/it]
Training models:  80%|████████  | 8/10 [02:36<00:53, 26.68s/it]
Training models:  90%|█████████ | 9/10 [03:10<00:29, 29.10s/it]
Training models: 100%|██████████| 10/10 [03:11<00:00, 19.19s/it]
Processing dataframe pairs:  50%|█████     | 2/4 [06:41<06:38, 199.07s/it]
Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.078332 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020002 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020227 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.019530 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020054 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:05<00:46,  5.18s/it]
Training models:  20%|██        | 2/10 [00:35<02:39, 19.91s/it]
Training models:  30%|███       | 3/10 [10:57<34:25, 295.03s/it]
Training models:  40%|████      | 4/10 [13:25<23:40, 236.72s/it]
Training models:  50%|█████     | 5/10 [13:40<13:03, 156.80s/it]
Training models:  60%|██████    | 6/10 [13:53<07:11, 107.90s/it]
Training models:  70%|███████   | 7/10 [13:56<03:40, 73.54s/it]
Training models:  80%|████████  | 8/10 [14:31<02:02, 61.38s/it]
Training models:  90%|█████████ | 9/10 [14:51<00:48, 48.34s/it]
Training models: 100%|██████████| 10/10 [15:14<00:00, 91.46s/it]
Processing dataframe pairs:  75%|███████▌  | 3/4 [21:55<08:45, 525.80s/it]
Training models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.156286 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000717 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001059 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001073 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001096 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.729056

Training models:  10%|█         | 1/10 [00:03<00:33,  3.72s/it]
Training models:  20%|██        | 2/10 [00:05<00:22,  2.77s/it]
Training models:  30%|███       | 3/10 [00:06<00:12,  1.81s/it]
Training models:  40%|████      | 4/10 [00:06<00:07,  1.23s/it]
Training models:  50%|█████     | 5/10 [00:07<00:05,  1.13s/it]
Training models:  60%|██████    | 6/10 [00:09<00:05,  1.38s/it]
Training models:  70%|███████   | 7/10 [00:09<00:03,  1.01s/it]
Training models:  80%|████████  | 8/10 [00:13<00:03,  1.80s/it]
Training models: 100%|██████████| 10/10 [00:19<00:00,  1.99s/it][A
Processing dataframe pairs: 100%|██████████| 4/4 [22:15<00:00, 333.93s/it]
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Dimensions of meta_features_train: (5568, 40)
Dimensions of meta_features_test: (1392, 40)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002680 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9974
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001754 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9965
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001625 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9958
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 40
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002354 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9969
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001513 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9960
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 40
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [8]:
#Ablations study

In [9]:
# 2D and 3D descriptors dataframes
df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Train/All_fingerprints_train.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Fingerprints/Test/All_fingerprints_test.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Train_all_atomic_desc.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Atomic/Test_all_atomic_desc.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]

print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)

def scale_features(df_train, df_test):
    scaler = StandardScaler()
    train_features = df_train.drop(columns=['ID', 'SMILES', target_column])
    test_features = df_test.drop(columns=['ID', 'SMILES', target_column])
    scaler.fit(train_features)
    train_scaled = pd.DataFrame(scaler.transform(train_features), columns=train_features.columns, index=df_train.index)
    test_scaled = pd.DataFrame(scaler.transform(test_features), columns=test_features.columns, index=df_test.index)
    df_train_scaled = pd.concat([df_train[['ID', 'SMILES', target_column]], train_scaled], axis=1)
    df_test_scaled = pd.concat([df_test[['ID', 'SMILES', target_column]], test_scaled], axis=1)
    return df_train_scaled, df_test_scaled

target_column = 'Permeability'
df_desc_train, df_desc_test = scale_features(df_desc_train, df_desc_test)
df_fp_train, df_fp_test = scale_features(df_fp_train, df_fp_test)
df_emb_train, df_emb_test = scale_features(df_emb_train, df_emb_test)
df_atomic_train, df_atomic_test = scale_features(df_atomic_train, df_atomic_test)

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train)
print(df_desc_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_fp_train)
print(df_fp_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_emb_train)
print(df_emb_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_atomic_train)
print(df_atomic_test)
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

/tmp/ipykernel_3837683/3482494709.py:2: DtypeWarning: Columns (1275,1277,1280,1285,1292,1298,1304,1354,1356,1359,1364,1371,1377,1383,1579,1580,1581,1583,1584,1590,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Train_2d_3d_all_descriptors.csv')
/tmp/ipykernel_3837683/3482494709.py:10: DtypeWarning: Columns (1275,1277,1292,1298,1354,1356,1371,1377,1579,1580,1581,1583,1584,1595,1596,1597) have mixed types. Specify dtype option on import or set low_memory=False.
  df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/PAMPA/features/Descriptors/Test_2d_3d_all_descriptors.csv')

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(5568, 272)
(1392, 272)
(5568, 1125)
(1392, 1125)
(5568, 763)
(1392, 763)
(5568, 12)
(1392, 12)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      MinEStateIndex       qed       SPS  FpDensityMorgan1  BCUT2D_MWHI  \
4765        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4772        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4766        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4767        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
4585        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
...              ...       ...       ...               ...          ...
607         0.192516 -0.775650  0.259993         -2.407555    -0.272146
726         0.653737 -0.018994  1.601452         -0.588614    -0.273699
772         0.632929 -0.119292  1.086333         -0.700759    -0.273718
5468        1.217004  1.450851 -0.469980          2.939673    -0.227462
5397       -0.865635 -1.498214 -1.692007          0.059878    -0.255008

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
4765 -0.023178    0.366371  ...  2.549183 -0.862324 -0.893728  0.489529
4772 -0.023178    0.366371  ...  4.965360 -0.427135  0.080585 -0.614519
4766 -0.023178    0.366371  ...  2.254608 -1.028595 -0.946363  0.326385
4767 -0.023178    0.366371  ...  2.446578 -0.126274  0.365179 -0.523457
4585  0.013981    0.379551  ...  1.369481 -1.176065 -0.916734  1.360742
...        ...         ...  ...       ...       ...       ...       ...
607  -0.094881    5.092978  ... -0.752000  0.319684  0.215975 -0.247991
726   0.694517   -1.332423  ...  0.016586 -0.171336  0.322553  1.340127
772   0.638444   -0.952883  ...  1.100970  0.171495 -0.903842  1.601925
5468  0.080729   -0.661118  ... -1.032055  1.128882  1.552470  0.054608
5397 -0.635613    0.246641  ...  2.214886 -0.752716 -0.227393  0.794083

      geomShape    RDF20i        Ku        Dm        Dv       L3p
4765  -1.020308 -0.804191 -1.025186 -0.939644 -0.249057  0.330472
4772   0.470831 -1.149778 -1.063426 -0.466831 -0.824736  0.134428
4766  -0.808816 -0.940742 -0.420312  0.312775 -0.090662 -0.600289
4767   0.462356 -0.831144 -1.760088 -0.203608  0.073430  0.976861
4585   0.285862 -1.019144  0.279728 -0.945914 -1.143574 -1.097882
...         ...       ...       ...       ...       ...       ...
607    0.462584  1.790214  1.102156  0.900813  1.346589 -0.223530
726   -0.535731  0.806143  0.429713  2.272960  2.625210 -0.313984
772    0.628743  1.051476 -0.268428  0.441640  1.239930  0.543089
5468   1.020392 -1.222162  0.024310  0.414281  0.667103 -1.301598
5397  -0.415407 -1.544547  0.272665 -0.052120 -1.523564 -1.453719

[5568 rows x 272 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      MinEStateIndex       qed       SPS  FpDensityMorgan1  BCUT2D_MWHI  \
1192        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
1145        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
841         0.523673  0.155095  1.135189         -1.046749    -0.202495
1146        0.616720 -0.412259 -0.263969         -0.463275    -0.202503
755         0.471903 -0.491085  0.431312         -1.132457    -0.202496
...              ...       ...       ...               ...          ...
1147        0.424645 -0.287590 -0.115302         -0.087259    -0.255729
174         0.640728 -0.049837  1.524206         -1.029680    -0.273694
1193        0.423845 -0.582130 -0.083445         -0.544377    -0.255732
122        -0.506947 -1.372119 -0.235774         -2.058103    -0.271840
201         0.638770  0.031128  1.205006         -0.368018    -0.273707

        AvgIpc  BalabanJ_x  ...      RNCS    LOBMAX    LOBMIN   MOMI-XY  \
1192 -0.023178    0.366371  ...  2.353903  0.614132  0.622580 -0.006415
1145  0.013981    0.379551  ...  1.424061  1.350508  1.575779 -1.453956
841   0.520753   -0.868326  ...  1.021738 -0.007526 -0.963853  0.615437
1146  0.013981    0.379551  ...  1.427272  0.854581  1.293000 -0.707309
755   0.390021   -0.316906  ...  0.638439 -0.775371 -1.133743 -1.324360
...        ...         ...  ...       ...       ...       ...       ...
1147  0.005182    0.457186  ...  2.716801 -0.890349 -0.465073 -1.462677
174   0.702472   -1.307483  ...  0.426959 -0.412873 -0.339536  0.984877
1193 -0.023178    0.366371  ...  2.274467 -0.351070 -0.530575 -1.484212
122  -2.350518    5.422188  ...  1.105510  0.171519 -1.029480  0.030957
201   0.631631   -0.948414  ...  0.380814 -0.424656 -0.455166  0.815036

      geomShape    RDF20i        Ku        Dm        Dv       L3p
1192   1.137043 -1.156626 -0.365331 -0.870643 -0.493169 -0.485308
1145   0.991383 -0.762205 -0.701714 -0.497383 -0.448249  1.156991
841    0.335906 -0.705307  0.680107 -0.258616 -0.236403 -1.538582
1146   0.655610 -1.065680  1.125261 -0.942912 -0.781599 -1.020320
755   -0.003376 -0.475084 -2.423851 -0.460538 -0.739462  2.192682
...         ...       ...       ...       ...       ...       ...
1147  -0.911785 -0.487920 -2.124744 -0.168864 -0.267079  1.046081
174   -1.327195  0.965695  0.643079 -0.372127 -0.206290 -0.695965
1193  -0.072194 -0.745729 -2.755939  0.249652  0.200575  1.681682
122    0.006484  2.158762 -0.030856  1.376912  1.271913  0.600539
201   -0.718497  1.013471  0.555556  0.810642  0.919984 -0.668591

[1392 rows x 272 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
4765    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4772    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4766    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4767    -0.429745     0.122258     -0.181197      1.300944     -0.296163
4585    -0.429745     0.122258     -0.181197      1.300944     -0.296163
...           ...          ...           ...           ...           ...
607     -0.429745     0.122258     -0.181197      1.300944     -0.296163
726      2.326961     0.122258     -0.181197     -0.768672     -0.296163
772      2.326961     0.122258     -0.181197     -0.768672     -0.296163
5468    -0.429745     0.122258     -0.181197     -0.768672     -0.296163
5397    -0.429745    -8.179391     -0.181197     -0.768672     -0.296163

      Morgan_fp_84  Morgan_fp_94  ...   SubFPC2  SubFPC100  SubFPC101  \
4765     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4772     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4766     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4767     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
4585     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
...            ...           ...  ...       ...        ...        ...
607      -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
726      -0.373919     -0.406921  ...  6.363355   -0.50779  -0.605817
772      -0.373919     -0.406921  ...  4.495903   -0.50779  -0.605817
5468     -0.373919     -0.406921  ... -1.573315   -0.50779  -0.605817
5397     -0.373919     -0.406921  ... -1.106452   -0.50779  -0.605817

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
4765  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4772  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4766  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4767  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
4585  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
...         ...        ...        ...        ...        ...        ...
607    2.434504  -0.060896  -0.040882   -0.05219  -0.093837   1.818822
726   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
772   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
5468  -2.323232  -0.060896  -0.040882   -0.05219   9.581758   0.161704
5397  -0.737320  -0.060896  -0.040882   -0.05219  -0.093837  -1.495414

      SubFPC302
4765  -0.421116
4772  -0.421116
4766  -0.421116
4767  -0.421116
4585  -0.196025
...         ...
607    0.479248
726   -0.646207
772   -0.421116
5468  -1.546572
5397  -0.196025

[5568 rows x 1125 columns]
        ID                                             SMILES  Permeability  \
1192     8  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -7.300000
1145    15  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -6.520000
841     17  COc1ccc(C[C@@H]2NC(=O)[C@@H](CC(C)C)NC(=O)[C@@...     -7.290000
1146    18  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.750000
755     19  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@H]...     -6.950000
...    ...                                                ...           ...
1147  8475  CC(C)C[C@@H]1NC(=O)[C@@H](CC(C)C)N(C)C(=O)[C@H...     -5.960000
174   8483  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H](CC2C...     -6.009141
1193  8487  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...     -6.495000
122   8513  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC...     -8.200000
201   8515  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.566211

      Morgan_fp_2  Morgan_fp_5  Morgan_fp_13  Morgan_fp_19  Morgan_fp_42  \
1192    -0.429745     0.122258     -0.181197      1.300944     -0.296163
1145    -0.429745     0.122258     -0.181197      1.300944     -0.296163
841     -0.429745     0.122258     -0.181197      1.300944     -0.296163
1146    -0.429745     0.122258     -0.181197      1.300944     -0.296163
755     -0.429745     0.122258     -0.181197      1.300944     -0.296163
...           ...          ...           ...           ...           ...
1147    -0.429745     0.122258     -0.181197      1.300944     -0.296163
174      2.326961     0.122258     -0.181197     -0.768672     -0.296163
1193    -0.429745     0.122258     -0.181197      1.300944     -0.296163
122     -0.429745     0.122258     -0.181197      1.300944     -0.296163
201      2.326961     0.122258     -0.181197     -0.768672     -0.296163

      Morgan_fp_84  Morgan_fp_94  ...   SubFPC2  SubFPC100  SubFPC101  \
1192     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
1145     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
841      -0.373919     -0.406921  ...  0.761000   -0.50779  -0.605817
1146     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
755      -0.373919     -0.406921  ...  0.294137   -0.50779  -0.605817
...            ...           ...  ...       ...        ...        ...
1147     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
174      -0.373919     -0.406921  ...  5.896492   -0.50779  -0.605817
1193     -0.373919     -0.406921  ... -0.639589   -0.50779  -0.605817
122      -0.373919     -0.406921  ...  0.761000   -0.50779  -0.605817
201      -0.373919     -0.406921  ...  4.029040   -0.50779  -0.605817

      SubFPC127  SubFPC135  SubFPC137  SubFPC143  SubFPC182  SubFPC275  \
1192  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
1145  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
841    0.319955  -0.060896  -0.040882   -0.05219  -0.093837  -0.390669
1146  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
755    0.319955  -0.060896  -0.040882   -0.05219  -0.093837  -0.390669
...         ...        ...        ...        ...        ...        ...
1147  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
174   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194
1193  -0.208683  -0.060896  -0.040882   -0.05219  -0.093837  -0.943041
122    2.434504  -0.060896  -0.040882   -0.05219  -0.093837   1.818822
201   -0.208683  -0.060896  -0.040882   -0.05219  -0.093837   2.371194

      SubFPC302
1192  -0.421116
1145  -0.196025
841   -0.646207
1146  -0.196025
755   -0.196025
...         ...
1147  -0.421116
174   -0.646207
1193  -0.421116
122    1.379613
201   -0.646207

[1392 rows x 1125 columns]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        ID                                             SMILES  Permeability  \
4765     3  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.000000
4772     4  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.100000
4766     6  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc...     -7.300000
4767     7  CC(C)C[C@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C@...     -7.300000
4585    11  COc1ccc(C[C@@H]2NC(=O)[C@H](CC(C)C)NC(=O)[C@@H...     -6.470000
...    ...                                                ...           ...
607   8512  CCC[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](C(...     -6.640000
726   8514  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -5.929053
772   8516  CCC[C@H]1C(=O)N[C@@H](CC2CCCCC2)C(=O)N(C)[C@@H...     -6.199359
5468  8517  CC[C@@H]1c2nnc(o2)[C@H](Cc2ccccc2)NC(=O)CNC(=O...     -6.780000
5397  8518  NCCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H](...     -5.525000

      x_fine_emb_MFXL0  x_fine_emb_MFXL1  x_fine_emb_MFXL2  x_fine_emb_MFXL3  \
4765         -1.362835          0.676766          2.263783         -0.029669
4772         -1.456499          0.942374          2.453267         -0.553083
4766         -1.408479          0.817561          2.605919         -0.529222
4767         -1.330524          0.999033          2.326873         -0.147679
4585         -0.894590          0.494381          1.352529         -0.675206
...                ...               ...               ...               ...
607          -2.747507          1.750885          1.810705          0.230750
726          -1.373444         -2.027777         -0.250508         -2.129512
772          -0.927683         -1.112633          0.068899         -1.012287
5468         -2.390418          2.349158          3.353966         -3.869338
5397         -1.046327          0.956775          1.171487          0.283242

      x_fine_emb_MFXL4  x_fine_emb_MFXL5  x_fine_emb_MFXL6  ...  \
4765         -1.132996         -3.127902         -2.510145  ...
4772          0.116345         -2.304301         -0.861316  ...
4766         -0.206309         -1.355997          0.071421  ...
4767         -0.758140         -3.103643         -2.145222  ...
4585          0.282418         -1.659310          0.314493  ...
...                ...               ...               ...  ...
607           1.450898         -2.019132          1.725549  ...
726          -1.432930         -0.702973         -1.229294  ...
772          -1.162808         -0.852733         -1.057444  ...
5468          2.022765         -2.097583         -2.313748  ...
5397         -4.903409          1.467003         -0.387383  ...

      x_fine_emb_MFXL758  x_fine_emb_MFXL759  x_fine_emb_MFXL760  \
4765           -1.105586            3.960163            0.980052
4772           -0.932800            3.926889            0.758840
4766           -1.258645            3.572499            0.279440
4767           -1.162212            3.601063            0.980804
4585           -0.671984            1.538951           -0.029645
...                  ...                 ...                 ...
607            -0.437313            1.255007           -2.375371
726            -0.358299           -0.054864            0.181493
772            -0.395752           -0.441349            0.819312
5468            0.721880            2.183873           -1.349979
5397           -0.650120            3.373594            1.599388

      x_fine_emb_MFXL761  x_fine_emb_MFXL762  x_fine_emb_MFXL763  \
4765            1.599023           -1.054547            1.401074
4772            1.676068           -0.686548            1.818805
4766            1.500911           -1.071328            1.778308
4767            1.372863           -1.059771            1.355451
4585           -1.113566           -0.229579            1.102657
...                  ...                 ...                 ...
607            -1.491044            0.921095            2.804574
726            -1.270647            0.459133            0.219489
772            -0.341048            0.290987            0.545666
5468            0.246066            0.634043            5.432239
5397            5.554441           -0.465011            0.593758

      x_fine_emb_MFXL764  x_fine_emb_MFXL765  x_fine_emb_MFXL766  \
4765            1.480165            1.386261           -1.362624
4772            2.307867            1.854912           -1.461679
4766            1.812858            1.742596           -1.043169
4767            1.474285            1.301570           -1.320077
4585            1.643638            1.026417           -2.035947
...                  ...                 ...                 ...
607             1.898821            1.917739            0.379968

In [10]:
models_weak = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101, eval_metric='rmse'),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101, max_iter=500),
    DecisionTreeRegressor(random_state=101),

]
models_meta = [
    lgb.LGBMRegressor(objective='regression', metric='rmse', boosting_type='gbdt', num_leaves=31, learning_rate=0.05, random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101, eval_metric='rmse'),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(),
    KNeighborsRegressor(),
    SVR(),
    MLPRegressor(random_state=101, max_iter=500)
]

dataframes = [(df_desc_train, df_desc_test), (df_fp_train, df_fp_test), (df_emb_train, df_emb_test), (df_atomic_train, df_atomic_test)]

In [11]:
ablation_results = {}

for ablation_idx in range(len(dataframes)):
    print(f"========== Ablation: Excluding feature at index {ablation_idx} ==========")
    feature_names = ['Descriptor', 'Fingerprints', 'Embeddings', 'Atomic']
    print(f"========== Ablation: Excluding feature :-- {feature_names[ablation_idx]} ==========")

    ablated_dataframes = [pair for i, pair in enumerate(dataframes) if i != ablation_idx]

    meta_features_train = []
    meta_features_test = []

    # Stage 1
    for df_train, df_test in tqdm(ablated_dataframes, desc="Processing ablated dataframes"):
        X_weak = df_train.drop(columns=['ID', 'SMILES', target_column])
        y_weak = df_train[target_column]
        X_eval = df_test.drop(columns=['ID', 'SMILES', target_column])
        y_eval = df_test[target_column]

        kf = KFold(n_splits=5, shuffle=True, random_state=101)

        fold_meta_features_train = np.zeros((X_weak.shape[0], len(models_weak)))
        fold_meta_features_test = np.zeros((X_eval.shape[0], len(models_weak)))

        for i, model in tqdm(enumerate(models_weak), desc="Training weak models", total=len(models_weak)):
            fold_predictions = np.zeros(X_weak.shape[0])
            test_predictions_folds = []

            for train_index, val_index in kf.split(X_weak):
                X_train, X_val = X_weak.iloc[train_index], X_weak.iloc[val_index]
                y_train, y_val = y_weak.iloc[train_index], y_weak.iloc[val_index]

                model.fit(X_train, y_train)

                fold_predictions[val_index] = np.clip(model.predict(X_val), -10, -3.9)
                test_predictions_fold = np.clip(model.predict(X_eval), -10, -3.9)
                test_predictions_folds.append(test_predictions_fold)

            fold_meta_features_train[:, i] = fold_predictions
            fold_meta_features_test[:, i] = np.mean(test_predictions_folds, axis=0)
            print(f'Model training done {i}: {model.__class__.__name__}')

        meta_features_train.append(fold_meta_features_train)
        meta_features_test.append(fold_meta_features_test)
        print('Dataframe training completed')

    # Stack all meta-features
    meta_features_train = np.hstack(meta_features_train)
    meta_features_test = np.hstack(meta_features_test)

    print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
    print('Stage 1 completed (Weak Learners)')
    print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

    # Stage 2
    results = {}
    kf = KFold(n_splits=5, shuffle=True, random_state=101)

    for model in models_meta:
        model_name = model.__class__.__name__
        predictions_train = []
        actual_y_train = []
        test_predictions_folds = []

        for train_index, val_index in kf.split(meta_features_train):
            X_fold_train, X_fold_val = meta_features_train[train_index], meta_features_train[val_index]
            y_fold_train, y_fold_val = y_weak.iloc[train_index], y_weak.iloc[val_index]

            model.fit(X_fold_train, y_fold_train)
            y_pred_fold = np.clip(model.predict(X_fold_val), -10, -3.9)

            predictions_train.extend(y_pred_fold)
            actual_y_train.extend(y_fold_val)

            test_predictions_fold = model.predict(meta_features_test)
            test_predictions_fold = np.clip(test_predictions_fold, -10, -3.9)
            test_predictions_folds.append(test_predictions_fold)

        predictions_test_mean = np.mean(test_predictions_folds, axis=0)
        predictions_test_std = np.std(test_predictions_folds, axis=0)

        mse_train = mean_squared_error(actual_y_train, predictions_train)
        mae_train = mean_absolute_error(actual_y_train, predictions_train)
        rmse_train = np.sqrt(mse_train)
        r2_train = r2_score(actual_y_train, predictions_train)
        pearson_train, _ = pearsonr(actual_y_train, predictions_train)
        spearman_train, _ = spearmanr(actual_y_train, predictions_train)

        mse_test = mean_squared_error(y_eval, predictions_test_mean)
        mae_test = mean_absolute_error(y_eval, predictions_test_mean)
        rmse_test = np.sqrt(mse_test)
        r2_test = r2_score(y_eval, predictions_test_mean)
        pearson_test, _ = pearsonr(y_eval, predictions_test_mean)
        spearman_test, _ = spearmanr(y_eval, predictions_test_mean)

        results[model_name] = {
            'Train MSE (5 fold CV)': mse_train,
            'Train MAE (5 fold CV)': mae_train,
            'Train RMSE (5 fold CV)': rmse_train,
            'Train R2 (5 fold CV)': r2_train,
            'Train PCC (5 fold CV)': pearson_train,
            'Train SCC (5 fold CV)': spearman_train,
            'Test MSE': mse_test,
            'Test MAE': mae_test,
            'Test RMSE': rmse_test,
            'Test R2': r2_test,
            'Test PCC': pearson_test,
            'Test SCC': spearman_test,
        }

    ablation_results[f"Ablation_{feature_names[ablation_idx]}"] = pd.DataFrame(results).T

print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Ablation Study Completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')

ablation_results_df = {key: value for key, value in ablation_results.items()}

========== Ablation: Excluding feature at index 0 ==========
========== Ablation: Excluding feature :-- Descriptor ==========

Processing ablated dataframes:   0%|          | 0/3 [00:00<?, ?it/s]
Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 45.635450 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4154
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1096
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.534393 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1098
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.892732 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1099
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 48.568217 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4165
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 46.718478 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4137
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1094
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:19:15<11:53:15, 4755.08s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:19:25<4:21:54, 1964.29s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:20:01<2:06:24, 1083.44s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:20:33<1:06:51, 668.63s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:36:33<1:04:28, 773.64s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:36:44<34:16, 514.16s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:36:54<17:28, 349.56s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:37:53<08:33, 256.96s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:40:14<03:40, 220.67s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:40:16<00:00, 601.61s/it]
Processing ablated dataframes:  33%|███▎      | 1/3 [1:40:16<3:20:33, 6016.76s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.267482 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.182396 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.195436 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.183260 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.222177 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:01:00<9:09:05, 3660.65s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:02:28<3:27:50, 1558.81s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:13:09<2:12:59, 1139.98s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:15:44<1:15:06, 751.07s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:32:33<1:10:20, 844.15s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:33:32<38:28, 577.01s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:33:43<19:35, 391.89s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:34:17<09:15, 277.99s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:35:57<03:42, 222.50s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:36:22<00:00, 578.25s/it]
Processing ablated dataframes:  67%|██████▋   | 2/3 [3:16:39<1:37:59, 5879.07s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.816331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.696040 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.550013 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.760843 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.725721 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:00:06<9:00:56, 3606.31s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:00:09<3:18:14, 1486.75s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:00:10<1:34:17, 808.19s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:00:10<48:55, 489.25s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:16:00<54:37, 655.56s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:16:03<28:53, 433.48s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:16:03<14:35, 291.89s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:16:07<06:40, 200.15s/it]

Model training done 7: SVR

Training weak models: 100%|██████████| 10/10 [1:16:36<00:00, 459.69s/it][A
Processing ablated dataframes: 100%|██████████| 3/3 [4:33:16<00:00, 5465.44s/it]

Model training done 8: MLPRegressor
Model training done 9: DecisionTreeRegressor
Dataframe training completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed (Weak Learners)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.385981 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7445
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.211875 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7434
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.186733 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7437
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.264167 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7448
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.184370 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7441
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

========== Ablation: Excluding feature at index 1 ==========
========== Ablation: Excluding feature :-- Fingerprints ==========

Processing ablated dataframes:   0%|          | 0/3 [00:00<?, ?it/s]
Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.625840 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57086
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.573775 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57104
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.761281 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 262
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.487258 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57103
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.915539 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 263
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:01:41<9:15:14, 3701.57s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:02:12<3:25:39, 1542.40s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:04:09<1:44:01, 891.63s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:04:45<55:21, 553.66s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:20:58<58:45, 705.07s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:21:40<31:58, 479.52s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:21:51<16:18, 326.27s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:22:05<07:34, 227.07s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:23:34<03:03, 183.88s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:23:40<00:00, 502.06s/it]
Processing ablated dataframes:  33%|███▎      | 1/3 [1:23:40<2:47:21, 5020.90s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.234904 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.184650 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.233021 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.147014 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.199720 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:01:44<9:15:36, 3704.11s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:02:40<3:27:45, 1558.21s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:13:21<2:12:55, 1139.31s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:15:55<1:15:02, 750.43s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:32:08<1:09:13, 830.76s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:32:29<37:01, 555.46s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:32:39<18:51, 377.01s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:33:14<08:56, 268.13s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:34:44<03:32, 212.59s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:35:09<00:00, 570.92s/it]
Processing ablated dataframes:  67%|██████▋   | 2/3 [2:58:50<1:30:25, 5425.77s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.859638 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.631529 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.700032 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.633011 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.625979 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:01:20<9:12:05, 3680.64s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:01:22<3:22:14, 1516.78s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:01:23<1:36:11, 824.51s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:01:23<49:54, 499.13s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:17:25<55:29, 665.94s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:17:29<29:23, 440.82s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:17:29<14:50, 296.80s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:17:33<06:47, 203.54s/it]

Model training done 7: SVR

Training weak models: 100%|██████████| 10/10 [1:18:13<00:00, 469.32s/it][A
Processing ablated dataframes: 100%|██████████| 3/3 [4:17:03<00:00, 5141.11s/it]

Model training done 8: MLPRegressor
Model training done 9: DecisionTreeRegressor
Dataframe training completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed (Weak Learners)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.203338 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7438
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.152918 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7432
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.293553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7428
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.139293 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7437
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.207306 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7427
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

========== Ablation: Excluding feature at index 2 ==========
========== Ablation: Excluding feature :-- Embeddings ==========

Processing ablated dataframes:   0%|          | 0/3 [00:00<?, ?it/s]
Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.488372 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57086
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.629937 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57104
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.445704 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 262
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.640646 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57103
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.677835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 263
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:00:40<9:06:02, 3640.27s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:00:58<3:21:18, 1509.77s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:02:54<1:41:52, 873.23s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:03:29<54:15, 542.51s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:19:17<57:22, 688.54s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:19:39<30:48, 462.02s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:19:50<15:43, 314.44s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:20:05<07:18, 219.01s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:21:28<02:56, 176.68s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:21:34<00:00, 489.44s/it]
Processing ablated dataframes:  33%|███▎      | 1/3 [1:21:34<2:43:08, 4894.43s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.441923 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4154
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1096
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.189556 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1098
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.077745 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1099
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 46.061332 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4165
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 47.830863 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4137
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1094
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:18:14<11:44:06, 4694.03s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:18:25<4:18:35, 1939.43s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:19:01<2:04:53, 1070.48s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:19:37<1:06:11, 661.89s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:35:23<1:03:41, 764.39s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:35:35<33:54, 508.63s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:35:45<17:16, 345.54s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:36:47<08:30, 255.35s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:38:47<03:33, 213.14s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:38:49<00:00, 592.99s/it]
Processing ablated dataframes:  67%|██████▋   | 2/3 [3:00:24<1:31:43, 5503.60s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.616124 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.755097 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 148
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.609321 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 9
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.771135 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 151
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.713059 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 150
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 9
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:00:07<9:01:03, 3607.01s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:00:09<3:18:12, 1486.52s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:00:09<1:34:16, 808.06s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:00:10<48:55, 489.18s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:16:00<54:37, 655.50s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:16:02<28:53, 433.29s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:16:02<14:35, 291.73s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:16:06<06:40, 200.01s/it]

Model training done 7: SVR

Training weak models: 100%|██████████| 10/10 [1:16:52<00:00, 461.30s/it][A
Processing ablated dataframes: 100%|██████████| 3/3 [4:17:17<00:00, 5145.82s/it]

Model training done 8: MLPRegressor
Model training done 9: DecisionTreeRegressor
Dataframe training completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed (Weak Learners)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.216240 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7441
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.191299 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7435
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.147420 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7424
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.191100 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7437
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.164872 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7429
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

========== Ablation: Excluding feature at index 3 ==========
========== Ablation: Excluding feature :-- Atomic ==========

Processing ablated dataframes:   0%|          | 0/3 [00:00<?, ?it/s]
Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.670835 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57086
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.324007 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57104
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 261
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.291333 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 262
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.840900 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57103
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 262
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.396844 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 57090
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 263
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [50:33<7:35:00, 3033.44s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [50:49<2:47:46, 1258.27s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [52:46<1:26:00, 737.22s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [53:21<46:01, 460.28s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:06:36<48:23, 580.74s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:06:42<25:42, 385.53s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:06:50<13:06, 262.06s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:07:05<06:06, 183.35s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:07:54<02:21, 141.35s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:07:59<00:00, 407.99s/it][A
Processing ablated dataframes:  33%|███▎      | 1/3 [1:07:59<2:15:59, 4079.90s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 37.687918 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4154
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1096
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 38.498787 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1098
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 39.505600 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4158
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 1099
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 39.291387 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4165
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1100
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 39.929643 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4137
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 1094
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [1:05:53<9:52:59, 3953.31s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [1:05:59<3:37:29, 1631.23s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:06:35<1:45:21, 903.05s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:07:07<55:55, 559.25s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:20:36<54:05, 649.03s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:20:42<28:41, 430.45s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:20:49<14:36, 292.28s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:21:51<07:17, 218.89s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:23:04<02:53, 173.34s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:23:06<00:00, 498.69s/it]
Processing ablated dataframes:  67%|██████▋   | 2/3 [2:31:06<1:16:53, 4613.43s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed

Training weak models:   0%|          | 0/10 [00:00<?, ?it/s]

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.185430 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749858
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.197165 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.749513
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.178803 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 760
[LightGBM] [Info] Start training from score -5.745012
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.184541 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.754268
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.181268 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 193800
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 760
[LightGBM] [Info] Start training from score -5.729056

Training weak models:  10%|█         | 1/10 [50:56<7:38:25, 3056.21s/it]

Model training done 0: LGBMRegressor

Training weak models:  20%|██        | 2/10 [51:45<2:51:37, 1287.22s/it]

Model training done 1: RandomForestRegressor

Training weak models:  30%|███       | 3/10 [1:02:39<1:56:27, 998.15s/it]

Model training done 2: GradientBoostingRegressor

Training weak models:  40%|████      | 4/10 [1:05:16<1:06:37, 666.33s/it]

Model training done 3: AdaBoostRegressor

Training weak models:  50%|█████     | 5/10 [1:18:44<59:46, 717.20s/it]

Model training done 4: XGBRegressor

Training weak models:  60%|██████    | 6/10 [1:19:03<31:59, 479.85s/it]

Model training done 5: ExtraTreesRegressor

Training weak models:  70%|███████   | 7/10 [1:19:12<16:17, 325.78s/it]

Model training done 6: KNeighborsRegressor

Training weak models:  80%|████████  | 8/10 [1:19:46<07:45, 232.90s/it]

Model training done 7: SVR

Training weak models:  90%|█████████ | 9/10 [1:20:32<02:54, 174.54s/it]

Model training done 8: MLPRegressor

Training weak models: 100%|██████████| 10/10 [1:20:57<00:00, 485.75s/it]
Processing ablated dataframes: 100%|██████████| 3/3 [3:52:04<00:00, 4641.42s/it]

Model training done 9: DecisionTreeRegressor
Dataframe training completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Stage 1 completed (Weak Learners)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.247184 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7598
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749858

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.147151 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7594
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.749513

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.191272 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7585
[LightGBM] [Info] Number of data points in the train set: 4454, number of used features: 30
[LightGBM] [Info] Start training from score -5.745012

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.195380 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7585
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.754268

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.195911 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7583
[LightGBM] [Info] Number of data points in the train set: 4455, number of used features: 30
[LightGBM] [Info] Start training from score -5.729056

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Ablation Study Completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

In [12]:
ablation_results

{'Ablation_Descriptor':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.131690               0.264953
 DecisionTreeRegressor                   0.272993               0.381897
 RandomForestRegressor                   0.132724               0.265274
 GradientBoostingRegressor               0.133771               0.265531
 AdaBoostRegressor                       0.180175               0.324553
 XGBRegressor                            0.152342               0.284421
 ExtraTreesRegressor                     0.131590               0.264263
 LinearRegression                        0.129552               0.260243
 KNeighborsRegressor                     0.152919               0.284954
 SVR                                     0.138795               0.267175
 MLPRegressor                            0.135589               0.267646

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.362891              0.788487
 DecisionTreeRegressor                    0.522487              0.561534
 RandomForestRegressor                    0.364313              0.786827
 GradientBoostingRegressor                0.365748              0.785144
 AdaBoostRegressor                        0.424471              0.710612
 XGBRegressor                             0.390310              0.755316
 ExtraTreesRegressor                      0.362754              0.788647
 LinearRegression                         0.359933              0.791921
 KNeighborsRegressor                      0.391048              0.754391
 SVR                                      0.372552              0.777075
 MLPRegressor                             0.368224              0.782225

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.887977               0.868270
 DecisionTreeRegressor                   0.787784               0.763749
 RandomForestRegressor                   0.887121               0.867932
 GradientBoostingRegressor               0.886101               0.867805
 AdaBoostRegressor                       0.853184               0.845064
 XGBRegressor                            0.869976               0.850433
 ExtraTreesRegressor                     0.888124               0.868513
 LinearRegression                        0.889902               0.871568
 KNeighborsRegressor                     0.868623               0.850359
 SVR                                     0.881968               0.868752
 MLPRegressor                            0.885054               0.864151

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.204452  0.322694   0.452164  0.678417  0.823831
 DecisionTreeRegressor      0.233854  0.348668   0.483584  0.632171  0.797838
 RandomForestRegressor      0.207166  0.323353   0.455155  0.674149  0.821333
 GradientBoostingRegressor  0.202960  0.320985   0.450511  0.680764  0.825326
 AdaBoostRegressor          0.225804  0.360827   0.475189  0.644832  0.809823
 XGBRegressor               0.211476  0.329950   0.459866  0.667368  0.817446
 ExtraTreesRegressor        0.205024  0.322513   0.452796  0.677516  0.823297
 LinearRegression           0.202843  0.319957   0.450381  0.680948  0.825444
 KNeighborsRegressor        0.216014  0.329607   0.464773  0.660230  0.812969
 SVR                        0.204191  0.318035   0.451875  0.678828  0.825092
 MLPRegressor               0.203714  0.323203   0.451347  0.679577  0.825928

                            Test SCC
 LGBMRegressor              0.806814
 DecisionTreeRegressor      0.770922
 RandomForestRegressor      0.804098
 GradientBoostingRegressor  0.808910
 AdaBoostRegressor          0.802468
 XGBRegressor               0.799619
 ExtraTreesRegressor        0.804342
 LinearRegression           0.807687
 KNeighborsRegressor        0.803257
 SVR                        0.811390
 MLPRegressor               0.807370  ,
 'Ablation_Fingerprints':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.130775               0.263279
 DecisionTreeRegressor                   0.265426               0.375744
 RandomForestRegressor                   0.132647               0.264022
 GradientBoostingRegressor               0.131441               0.263806
 AdaBoostRegressor                       0.183996               0.328671
 XGBRegressor                            0.150191               0.284484
 ExtraTreesRegressor                     0.131267               0.263847
 LinearRegression                        0.129740               0.260592
 KNeighborsRegressor                     0.158103               0.293008
 SVR                                     0.137734               0.268107
 MLPRegressor                            0.135930               0.267500

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.361629              0.789956
 DecisionTreeRegressor                    0.515195              0.573688
 RandomForestRegressor                    0.364207              0.786950
 GradientBoostingRegressor                0.362547              0.788887
 AdaBoostRegressor                        0.428947              0.704476
 XGBRegressor                             0.387545              0.758772
 ExtraTreesRegressor                      0.362308              0.789166
 LinearRegression                         0.360194              0.791619
 KNeighborsRegressor                      0.397621              0.746064
 SVR                                      0.371126              0.778779
 MLPRegressor                             0.368687              0.781677

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.888797               0.869389
 DecisionTreeRegressor                   0.789057               0.763464
 RandomForestRegressor                   0.887211               0.867468
 GradientBoostingRegressor               0.888215               0.869597
 AdaBoostRegressor                       0.850955               0.846435
 XGBRegressor                            0.871937               0.848237
 ExtraTreesRegressor                     0.888438               0.869160
 LinearRegression                        0.889731               0.870787
 KNeighborsRegressor                     0.863861               0.843761
 SVR                                     0.882802               0.868356
 MLPRegressor                            0.885583               0.864596

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.202943  0.319406   0.450492  0.680791  0.825299
 DecisionTreeRegressor      0.242621  0.352164   0.492566  0.618380  0.790188
 RandomForestRegressor      0.206547  0.322212   0.454474  0.675122  0.821942
 GradientBoostingRegressor  0.201552  0.318581   0.448945  0.682979  0.826714
 AdaBoostRegressor          0.227956  0.364422   0.477447  0.641448  0.809617
 XGBRegressor               0.208233  0.323575   0.456326  0.672469  0.820382
 ExtraTreesRegressor        0.203961  0.321365   0.451620  0.679190  0.824314
 LinearRegression           0.201478  0.318496   0.448863  0.683095  0.826747
 KNeighborsRegressor        0.208253  0.325352   0.456348  0.672438  0.820400
 SVR                        0.202905  0.317523   0.450450  0.680849  0.826434
 MLPRegressor               0.202597  0.321147   0.450107  0.681335  0.827971

                            Test SCC
 LGBMRegressor              0.807594
 DecisionTreeRegressor      0.769553
 RandomForestRegressor      0.802728
 GradientBoostingRegressor  0.809400
 AdaBoostRegressor          0.802384
 XGBRegressor               0.803693
 ExtraTreesRegressor        0.805064
 LinearRegression           0.809246
 KNeighborsRegressor        0.804172
 SVR                        0.811458
 MLPRegressor               0.809926  ,
 'Ablation_Embeddings':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.203378               0.331623
 DecisionTreeRegressor                   0.417317               0.479592
 RandomForestRegressor                   0.201164               0.331266
 GradientBoostingRegressor               0.201377               0.330723
 AdaBoostRegressor                       0.263449               0.401445
 XGBRegressor                            0.235075               0.358418
 ExtraTreesRegressor                     0.195765               0.326377
 LinearRegression                        0.198980               0.328430
 KNeighborsRegressor                     0.230325               0.354579
 SVR                                     0.212358               0.333858
 MLPRegressor                            0.207095               0.336773

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.450974              0.673346
 DecisionTreeRegressor                    0.646001              0.329728
 RandomForestRegressor                    0.448513              0.676902
 GradientBoostingRegressor                0.448750              0.676560
 AdaBoostRegressor                        0.513273              0.576863
 XGBRegressor                             0.484845              0.622436
 ExtraTreesRegressor                      0.442454              0.685572
 LinearRegression                         0.446072              0.680409
 KNeighborsRegressor                      0.479922              0.630065
 SVR                                      0.460823              0.658922
 MLPRegressor                             0.455077              0.667376

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.820619               0.790158
 DecisionTreeRegressor                   0.680011               0.642023
 RandomForestRegressor                   0.822871               0.792976
 GradientBoostingRegressor               0.822591               0.792726
 AdaBoostRegressor                       0.779831               0.752032
 XGBRegressor                            0.791943               0.760236
 ExtraTreesRegressor                     0.828182               0.799266
 LinearRegression                        0.824912               0.795261
 KNeighborsRegressor                     0.794913               0.763174
 SVR                                     0.812795               0.785595
 MLPRegressor                            0.817209               0.785045

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.204800  0.324125   0.452549  0.677869  0.823455
 DecisionTreeRegressor      0.242558  0.357220   0.492502  0.618479  0.789864
 RandomForestRegressor      0.208734  0.327195   0.456874  0.671682  0.819648
 GradientBoostingRegressor  0.201715  0.323488   0.449127  0.682723  0.826400
 AdaBoostRegressor          0.241054  0.383816   0.490973  0.620845  0.807811
 XGBRegressor               0.214383  0.330332   0.463015  0.662797  0.814277
 ExtraTreesRegressor        0.210159  0.328763   0.458431  0.669440  0.818212
 LinearRegression           0.200950  0.321582   0.448274  0.683925  0.827145
 KNeighborsRegressor        0.229102  0.344010   0.478646  0.639645  0.800058
 SVR                        0.208363  0.321160   0.456468  0.672265  0.821616
 MLPRegressor               0.201654  0.326717   0.449059  0.682818  0.826352

                            Test SCC
 LGBMRegressor              0.808329
 DecisionTreeRegressor      0.765117
 RandomForestRegressor      0.800502
 GradientBoostingRegressor  0.809034
 AdaBoostRegressor          0.787286
 XGBRegressor               0.797032
 ExtraTreesRegressor        0.800025
 LinearRegression           0.808446
 KNeighborsRegressor        0.774035
 SVR                        0.809038
 MLPRegressor               0.807331  ,
 'Ablation_Atomic':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.130497               0.262996
 DecisionTreeRegressor                   0.276634               0.383390
 RandomForestRegressor                   0.131759               0.263166
 GradientBoostingRegressor               0.132820               0.264205
 AdaBoostRegressor                       0.185790               0.330758
 XGBRegressor                            0.149740               0.283264
 ExtraTreesRegressor                     0.130182               0.263089
 LinearRegression                        0.129443               0.259894
 KNeighborsRegressor                     0.156995               0.289993
 SVR                                     0.135908               0.264250
 MLPRegressor                            0.138438               0.270691

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.361243              0.790404
 DecisionTreeRegressor                    0.525960              0.555686
 RandomForestRegressor                    0.362986              0.788376
 GradientBoostingRegressor                0.364445              0.786672
 AdaBoostRegressor                        0.431034              0.701594
 XGBRegressor                             0.386963              0.759496
 ExtraTreesRegressor                      0.360808              0.790909
 LinearRegression                         0.359781              0.792096
 KNeighborsRegressor                      0.396226              0.747843
 SVR                                      0.368658              0.781711
 MLPRegressor                             0.372072              0.777649

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.889057               0.869355
 DecisionTreeRegressor                   0.782244               0.758444
 RandomForestRegressor                   0.887968               0.868488
 GradientBoostingRegressor               0.886950               0.869160
 AdaBoostRegressor                       0.851125               0.837774
 XGBRegressor                            0.872512               0.850426
 ExtraTreesRegressor                     0.889399               0.869711
 LinearRegression                        0.890001               0.871253
 KNeighborsRegressor                     0.864810               0.846335
 SVR                                     0.884553               0.869439
 MLPRegressor                            0.882173               0.862267

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.202347  0.319753   0.449830  0.681728  0.825907
 DecisionTreeRegressor      0.234026  0.345025   0.483763  0.631899  0.797308
 RandomForestRegressor      0.206810  0.322707   0.454763  0.674709  0.821729
 GradientBoostingRegressor  0.201599  0.319197   0.448998  0.682904  0.826643
 AdaBoostRegressor          0.228733  0.365384   0.478260  0.640226  0.811377
 XGBRegressor               0.208645  0.326386   0.456777  0.671822  0.820274
 ExtraTreesRegressor        0.203189  0.320397   0.450765  0.680404  0.825104
 LinearRegression           0.201058  0.318339   0.448395  0.683756  0.827127
 KNeighborsRegressor        0.209734  0.329483   0.457968  0.670108  0.819010
 SVR                        0.200150  0.316087   0.447381  0.685184  0.829017
 MLPRegressor               0.201245  0.320090   0.448603  0.683461  0.827412

                            Test SCC
 LGBMRegressor              0.807819
 DecisionTreeRegressor      0.773570
 RandomForestRegressor      0.803393
 GradientBoostingRegressor  0.809439
 AdaBoostRegressor          0.801066
 XGBRegressor               0.803849
 ExtraTreesRegressor        0.805656
 LinearRegression           0.809459
 KNeighborsRegressor        0.797993
 SVR                        0.810594
 MLPRegressor               0.809617  }

In [13]:
import os
import pickle

ablation_result_dir = '/home/users/akshay/PCPpred/PAMPA/Results/Ablation/'
os.makedirs(ablation_result_dir, exist_ok=True)

pickle_path = os.path.join(ablation_result_dir, 'ablation_results.pkl')
with open(pickle_path, 'wb') as f:
    pickle.dump(ablation_results, f)


with open(pickle_path, 'rb') as f:
    ablation_results = pickle.load(f)


ablation_results

{'Ablation_Descriptor':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.131690               0.264953
 DecisionTreeRegressor                   0.272993               0.381897
 RandomForestRegressor                   0.132724               0.265274
 GradientBoostingRegressor               0.133771               0.265531
 AdaBoostRegressor                       0.180175               0.324553
 XGBRegressor                            0.152342               0.284421
 ExtraTreesRegressor                     0.131590               0.264263
 LinearRegression                        0.129552               0.260243
 KNeighborsRegressor                     0.152919               0.284954
 SVR                                     0.138795               0.267175
 MLPRegressor                            0.135589               0.267646

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.362891              0.788487
 DecisionTreeRegressor                    0.522487              0.561534
 RandomForestRegressor                    0.364313              0.786827
 GradientBoostingRegressor                0.365748              0.785144
 AdaBoostRegressor                        0.424471              0.710612
 XGBRegressor                             0.390310              0.755316
 ExtraTreesRegressor                      0.362754              0.788647
 LinearRegression                         0.359933              0.791921
 KNeighborsRegressor                      0.391048              0.754391
 SVR                                      0.372552              0.777075
 MLPRegressor                             0.368224              0.782225

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.887977               0.868270
 DecisionTreeRegressor                   0.787784               0.763749
 RandomForestRegressor                   0.887121               0.867932
 GradientBoostingRegressor               0.886101               0.867805
 AdaBoostRegressor                       0.853184               0.845064
 XGBRegressor                            0.869976               0.850433
 ExtraTreesRegressor                     0.888124               0.868513
 LinearRegression                        0.889902               0.871568
 KNeighborsRegressor                     0.868623               0.850359
 SVR                                     0.881968               0.868752
 MLPRegressor                            0.885054               0.864151

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.204452  0.322694   0.452164  0.678417  0.823831
 DecisionTreeRegressor      0.233854  0.348668   0.483584  0.632171  0.797838
 RandomForestRegressor      0.207166  0.323353   0.455155  0.674149  0.821333
 GradientBoostingRegressor  0.202960  0.320985   0.450511  0.680764  0.825326
 AdaBoostRegressor          0.225804  0.360827   0.475189  0.644832  0.809823
 XGBRegressor               0.211476  0.329950   0.459866  0.667368  0.817446
 ExtraTreesRegressor        0.205024  0.322513   0.452796  0.677516  0.823297
 LinearRegression           0.202843  0.319957   0.450381  0.680948  0.825444
 KNeighborsRegressor        0.216014  0.329607   0.464773  0.660230  0.812969
 SVR                        0.204191  0.318035   0.451875  0.678828  0.825092
 MLPRegressor               0.203714  0.323203   0.451347  0.679577  0.825928

                            Test SCC
 LGBMRegressor              0.806814
 DecisionTreeRegressor      0.770922
 RandomForestRegressor      0.804098
 GradientBoostingRegressor  0.808910
 AdaBoostRegressor          0.802468
 XGBRegressor               0.799619
 ExtraTreesRegressor        0.804342
 LinearRegression           0.807687
 KNeighborsRegressor        0.803257
 SVR                        0.811390
 MLPRegressor               0.807370  ,
 'Ablation_Fingerprints':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.130775               0.263279
 DecisionTreeRegressor                   0.265426               0.375744
 RandomForestRegressor                   0.132647               0.264022
 GradientBoostingRegressor               0.131441               0.263806
 AdaBoostRegressor                       0.183996               0.328671
 XGBRegressor                            0.150191               0.284484
 ExtraTreesRegressor                     0.131267               0.263847
 LinearRegression                        0.129740               0.260592
 KNeighborsRegressor                     0.158103               0.293008
 SVR                                     0.137734               0.268107
 MLPRegressor                            0.135930               0.267500

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.361629              0.789956
 DecisionTreeRegressor                    0.515195              0.573688
 RandomForestRegressor                    0.364207              0.786950
 GradientBoostingRegressor                0.362547              0.788887
 AdaBoostRegressor                        0.428947              0.704476
 XGBRegressor                             0.387545              0.758772
 ExtraTreesRegressor                      0.362308              0.789166
 LinearRegression                         0.360194              0.791619
 KNeighborsRegressor                      0.397621              0.746064
 SVR                                      0.371126              0.778779
 MLPRegressor                             0.368687              0.781677

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.888797               0.869389
 DecisionTreeRegressor                   0.789057               0.763464
 RandomForestRegressor                   0.887211               0.867468
 GradientBoostingRegressor               0.888215               0.869597
 AdaBoostRegressor                       0.850955               0.846435
 XGBRegressor                            0.871937               0.848237
 ExtraTreesRegressor                     0.888438               0.869160
 LinearRegression                        0.889731               0.870787
 KNeighborsRegressor                     0.863861               0.843761
 SVR                                     0.882802               0.868356
 MLPRegressor                            0.885583               0.864596

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.202943  0.319406   0.450492  0.680791  0.825299
 DecisionTreeRegressor      0.242621  0.352164   0.492566  0.618380  0.790188
 RandomForestRegressor      0.206547  0.322212   0.454474  0.675122  0.821942
 GradientBoostingRegressor  0.201552  0.318581   0.448945  0.682979  0.826714
 AdaBoostRegressor          0.227956  0.364422   0.477447  0.641448  0.809617
 XGBRegressor               0.208233  0.323575   0.456326  0.672469  0.820382
 ExtraTreesRegressor        0.203961  0.321365   0.451620  0.679190  0.824314
 LinearRegression           0.201478  0.318496   0.448863  0.683095  0.826747
 KNeighborsRegressor        0.208253  0.325352   0.456348  0.672438  0.820400
 SVR                        0.202905  0.317523   0.450450  0.680849  0.826434
 MLPRegressor               0.202597  0.321147   0.450107  0.681335  0.827971

                            Test SCC
 LGBMRegressor              0.807594
 DecisionTreeRegressor      0.769553
 RandomForestRegressor      0.802728
 GradientBoostingRegressor  0.809400
 AdaBoostRegressor          0.802384
 XGBRegressor               0.803693
 ExtraTreesRegressor        0.805064
 LinearRegression           0.809246
 KNeighborsRegressor        0.804172
 SVR                        0.811458
 MLPRegressor               0.809926  ,
 'Ablation_Embeddings':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.203378               0.331623
 DecisionTreeRegressor                   0.417317               0.479592
 RandomForestRegressor                   0.201164               0.331266
 GradientBoostingRegressor               0.201377               0.330723
 AdaBoostRegressor                       0.263449               0.401445
 XGBRegressor                            0.235075               0.358418
 ExtraTreesRegressor                     0.195765               0.326377
 LinearRegression                        0.198980               0.328430
 KNeighborsRegressor                     0.230325               0.354579
 SVR                                     0.212358               0.333858
 MLPRegressor                            0.207095               0.336773

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.450974              0.673346
 DecisionTreeRegressor                    0.646001              0.329728
 RandomForestRegressor                    0.448513              0.676902
 GradientBoostingRegressor                0.448750              0.676560
 AdaBoostRegressor                        0.513273              0.576863
 XGBRegressor                             0.484845              0.622436
 ExtraTreesRegressor                      0.442454              0.685572
 LinearRegression                         0.446072              0.680409
 KNeighborsRegressor                      0.479922              0.630065
 SVR                                      0.460823              0.658922
 MLPRegressor                             0.455077              0.667376

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.820619               0.790158
 DecisionTreeRegressor                   0.680011               0.642023
 RandomForestRegressor                   0.822871               0.792976
 GradientBoostingRegressor               0.822591               0.792726
 AdaBoostRegressor                       0.779831               0.752032
 XGBRegressor                            0.791943               0.760236
 ExtraTreesRegressor                     0.828182               0.799266
 LinearRegression                        0.824912               0.795261
 KNeighborsRegressor                     0.794913               0.763174
 SVR                                     0.812795               0.785595
 MLPRegressor                            0.817209               0.785045

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.204800  0.324125   0.452549  0.677869  0.823455
 DecisionTreeRegressor      0.242558  0.357220   0.492502  0.618479  0.789864
 RandomForestRegressor      0.208734  0.327195   0.456874  0.671682  0.819648
 GradientBoostingRegressor  0.201715  0.323488   0.449127  0.682723  0.826400
 AdaBoostRegressor          0.241054  0.383816   0.490973  0.620845  0.807811
 XGBRegressor               0.214383  0.330332   0.463015  0.662797  0.814277
 ExtraTreesRegressor        0.210159  0.328763   0.458431  0.669440  0.818212
 LinearRegression           0.200950  0.321582   0.448274  0.683925  0.827145
 KNeighborsRegressor        0.229102  0.344010   0.478646  0.639645  0.800058
 SVR                        0.208363  0.321160   0.456468  0.672265  0.821616
 MLPRegressor               0.201654  0.326717   0.449059  0.682818  0.826352

                            Test SCC
 LGBMRegressor              0.808329
 DecisionTreeRegressor      0.765117
 RandomForestRegressor      0.800502
 GradientBoostingRegressor  0.809034
 AdaBoostRegressor          0.787286
 XGBRegressor               0.797032
 ExtraTreesRegressor        0.800025
 LinearRegression           0.808446
 KNeighborsRegressor        0.774035
 SVR                        0.809038
 MLPRegressor               0.807331  ,
 'Ablation_Atomic':                            Train MSE (5 fold CV)  Train MAE (5 fold CV)  \
 LGBMRegressor                           0.130497               0.262996
 DecisionTreeRegressor                   0.276634               0.383390
 RandomForestRegressor                   0.131759               0.263166
 GradientBoostingRegressor               0.132820               0.264205
 AdaBoostRegressor                       0.185790               0.330758
 XGBRegressor                            0.149740               0.283264
 ExtraTreesRegressor                     0.130182               0.263089
 LinearRegression                        0.129443               0.259894
 KNeighborsRegressor                     0.156995               0.289993
 SVR                                     0.135908               0.264250
 MLPRegressor                            0.138438               0.270691

                            Train RMSE (5 fold CV)  Train R2 (5 fold CV)  \
 LGBMRegressor                            0.361243              0.790404
 DecisionTreeRegressor                    0.525960              0.555686
 RandomForestRegressor                    0.362986              0.788376
 GradientBoostingRegressor                0.364445              0.786672
 AdaBoostRegressor                        0.431034              0.701594
 XGBRegressor                             0.386963              0.759496
 ExtraTreesRegressor                      0.360808              0.790909
 LinearRegression                         0.359781              0.792096
 KNeighborsRegressor                      0.396226              0.747843
 SVR                                      0.368658              0.781711
 MLPRegressor                             0.372072              0.777649

                            Train PCC (5 fold CV)  Train SCC (5 fold CV)  \
 LGBMRegressor                           0.889057               0.869355
 DecisionTreeRegressor                   0.782244               0.758444
 RandomForestRegressor                   0.887968               0.868488
 GradientBoostingRegressor               0.886950               0.869160
 AdaBoostRegressor                       0.851125               0.837774
 XGBRegressor                            0.872512               0.850426
 ExtraTreesRegressor                     0.889399               0.869711
 LinearRegression                        0.890001               0.871253
 KNeighborsRegressor                     0.864810               0.846335
 SVR                                     0.884553               0.869439
 MLPRegressor                            0.882173               0.862267

                            Test MSE  Test MAE  Test RMSE   Test R2  Test PCC  \
 LGBMRegressor              0.202347  0.319753   0.449830  0.681728  0.825907
 DecisionTreeRegressor      0.234026  0.345025   0.483763  0.631899  0.797308
 RandomForestRegressor      0.206810  0.322707   0.454763  0.674709  0.821729
 GradientBoostingRegressor  0.201599  0.319197   0.448998  0.682904  0.826643
 AdaBoostRegressor          0.228733  0.365384   0.478260  0.640226  0.811377
 XGBRegressor               0.208645  0.326386   0.456777  0.671822  0.820274
 ExtraTreesRegressor        0.203189  0.320397   0.450765  0.680404  0.825104
 LinearRegression           0.201058  0.318339   0.448395  0.683756  0.827127
 KNeighborsRegressor        0.209734  0.329483   0.457968  0.670108  0.819010
 SVR                        0.200150  0.316087   0.447381  0.685184  0.829017
 MLPRegressor               0.201245  0.320090   0.448603  0.683461  0.827412

                            Test SCC
 LGBMRegressor              0.807819
 DecisionTreeRegressor      0.773570
 RandomForestRegressor      0.803393
 GradientBoostingRegressor  0.809439
 AdaBoostRegressor          0.801066
 XGBRegressor               0.803849
 ExtraTreesRegressor        0.805656
 LinearRegression           0.809459
 KNeighborsRegressor        0.797993
 SVR                        0.810594
 MLPRegressor               0.809617  }

In [14]:
ablation_result_dir = '/home/users/akshay/PCPpred/PAMPA/Results/Ablation/'
os.makedirs(ablation_result_dir, exist_ok=True)

for ablation_label, df in ablation_results.items():
    print(f"Results for {ablation_label}: \n")
    safe_label = ablation_label.replace(" ", "_").replace("/", "_")
    file_path = os.path.join(ablation_result_dir, f"{safe_label}.csv")
    df.to_csv(file_path)

Results for Ablation_Descriptor:

Results for Ablation_Fingerprints:

Results for Ablation_Embeddings:

Results for Ablation_Atomic:

In [15]:
from IPython.display import display
for ablation_label, df in ablation_results.items():
    print(f"Results for {ablation_label}: \n")
    display(df)

Results for Ablation_Descriptor:

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.131690,0.264953,0.362891,0.788487,0.887977,0.868270,0.204452,0.322694,0.452164,0.678417,0.823831,0.806814
DecisionTreeRegressor,0.272993,0.381897,0.522487,0.561534,0.787784,0.763749,0.233854,0.348668,0.483584,0.632171,0.797838,0.770922
RandomForestRegressor,0.132724,0.265274,0.364313,0.786827,0.887121,0.867932,0.207166,0.323353,0.455155,0.674149,0.821333,0.804098
GradientBoostingRegressor,0.133771,0.265531,0.365748,0.785144,0.886101,0.867805,0.202960,0.320985,0.450511,0.680764,0.825326,0.808910
AdaBoostRegressor,0.180175,0.324553,0.424471,0.710612,0.853184,0.845064,0.225804,0.360827,0.475189,0.644832,0.809823,0.802468
XGBRegressor,0.152342,0.284421,0.390310,0.755316,0.869976,0.850433,0.211476,0.329950,0.459866,0.667368,0.817446,0.799619
ExtraTreesRegressor,0.131590,0.264263,0.362754,0.788647,0.888124,0.868513,0.205024,0.322513,0.452796,0.677516,0.823297,0.804342
LinearRegression,0.129552,0.260243,0.359933,0.791921,0.889902,0.871568,0.202843,0.319957,0.450381,0.680948,0.825444,0.807687
KNeighborsRegressor,0.152919,0.284954,0.391048,0.754391,0.868623,0.850359,0.216014,0.329607,0.464773,0.660230,0.812969,0.803257
SVR,0.138795,0.267175,0.372552,0.777075,0.881968,0.868752,0.204191,0.318035,0.451875,0.678828,0.825092,0.811390
MLPRegressor,0.135589,0.267646,0.368224,0.782225,0.885054,0.864151,0.203714,0.323203,0.451347,0.679577,0.825928,0.807370

Results for Ablation_Fingerprints:

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.130775,0.263279,0.361629,0.789956,0.888797,0.869389,0.202943,0.319406,0.450492,0.680791,0.825299,0.807594
DecisionTreeRegressor,0.265426,0.375744,0.515195,0.573688,0.789057,0.763464,0.242621,0.352164,0.492566,0.618380,0.790188,0.769553
RandomForestRegressor,0.132647,0.264022,0.364207,0.786950,0.887211,0.867468,0.206547,0.322212,0.454474,0.675122,0.821942,0.802728
GradientBoostingRegressor,0.131441,0.263806,0.362547,0.788887,0.888215,0.869597,0.201552,0.318581,0.448945,0.682979,0.826714,0.809400
AdaBoostRegressor,0.183996,0.328671,0.428947,0.704476,0.850955,0.846435,0.227956,0.364422,0.477447,0.641448,0.809617,0.802384
XGBRegressor,0.150191,0.284484,0.387545,0.758772,0.871937,0.848237,0.208233,0.323575,0.456326,0.672469,0.820382,0.803693
ExtraTreesRegressor,0.131267,0.263847,0.362308,0.789166,0.888438,0.869160,0.203961,0.321365,0.451620,0.679190,0.824314,0.805064
LinearRegression,0.129740,0.260592,0.360194,0.791619,0.889731,0.870787,0.201478,0.318496,0.448863,0.683095,0.826747,0.809246
KNeighborsRegressor,0.158103,0.293008,0.397621,0.746064,0.863861,0.843761,0.208253,0.325352,0.456348,0.672438,0.820400,0.804172
SVR,0.137734,0.268107,0.371126,0.778779,0.882802,0.868356,0.202905,0.317523,0.450450,0.680849,0.826434,0.811458
MLPRegressor,0.135930,0.267500,0.368687,0.781677,0.885583,0.864596,0.202597,0.321147,0.450107,0.681335,0.827971,0.809926

Results for Ablation_Embeddings:

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.203378,0.331623,0.450974,0.673346,0.820619,0.790158,0.204800,0.324125,0.452549,0.677869,0.823455,0.808329
DecisionTreeRegressor,0.417317,0.479592,0.646001,0.329728,0.680011,0.642023,0.242558,0.357220,0.492502,0.618479,0.789864,0.765117
RandomForestRegressor,0.201164,0.331266,0.448513,0.676902,0.822871,0.792976,0.208734,0.327195,0.456874,0.671682,0.819648,0.800502
GradientBoostingRegressor,0.201377,0.330723,0.448750,0.676560,0.822591,0.792726,0.201715,0.323488,0.449127,0.682723,0.826400,0.809034
AdaBoostRegressor,0.263449,0.401445,0.513273,0.576863,0.779831,0.752032,0.241054,0.383816,0.490973,0.620845,0.807811,0.787286
XGBRegressor,0.235075,0.358418,0.484845,0.622436,0.791943,0.760236,0.214383,0.330332,0.463015,0.662797,0.814277,0.797032
ExtraTreesRegressor,0.195765,0.326377,0.442454,0.685572,0.828182,0.799266,0.210159,0.328763,0.458431,0.669440,0.818212,0.800025
LinearRegression,0.198980,0.328430,0.446072,0.680409,0.824912,0.795261,0.200950,0.321582,0.448274,0.683925,0.827145,0.808446
KNeighborsRegressor,0.230325,0.354579,0.479922,0.630065,0.794913,0.763174,0.229102,0.344010,0.478646,0.639645,0.800058,0.774035
SVR,0.212358,0.333858,0.460823,0.658922,0.812795,0.785595,0.208363,0.321160,0.456468,0.672265,0.821616,0.809038
MLPRegressor,0.207095,0.336773,0.455077,0.667376,0.817209,0.785045,0.201654,0.326717,0.449059,0.682818,0.826352,0.807331

Results for Ablation_Atomic:

,Train MSE (5 fold CV),Train MAE (5 fold CV),Train RMSE (5 fold CV),Train R2 (5 fold CV),Train PCC (5 fold CV),Train SCC (5 fold CV),Test MSE,Test MAE,Test RMSE,Test R2,Test PCC,Test SCC
LGBMRegressor,0.130497,0.262996,0.361243,0.790404,0.889057,0.869355,0.202347,0.319753,0.449830,0.681728,0.825907,0.807819
DecisionTreeRegressor,0.276634,0.383390,0.525960,0.555686,0.782244,0.758444,0.234026,0.345025,0.483763,0.631899,0.797308,0.773570
RandomForestRegressor,0.131759,0.263166,0.362986,0.788376,0.887968,0.868488,0.206810,0.322707,0.454763,0.674709,0.821729,0.803393
GradientBoostingRegressor,0.132820,0.264205,0.364445,0.786672,0.886950,0.869160,0.201599,0.319197,0.448998,0.682904,0.826643,0.809439
AdaBoostRegressor,0.185790,0.330758,0.431034,0.701594,0.851125,0.837774,0.228733,0.365384,0.478260,0.640226,0.811377,0.801066
XGBRegressor,0.149740,0.283264,0.386963,0.759496,0.872512,0.850426,0.208645,0.326386,0.456777,0.671822,0.820274,0.803849
ExtraTreesRegressor,0.130182,0.263089,0.360808,0.790909,0.889399,0.869711,0.203189,0.320397,0.450765,0.680404,0.825104,0.805656
LinearRegression,0.129443,0.259894,0.359781,0.792096,0.890001,0.871253,0.201058,0.318339,0.448395,0.683756,0.827127,0.809459
KNeighborsRegressor,0.156995,0.289993,0.396226,0.747843,0.864810,0.846335,0.209734,0.329483,0.457968,0.670108,0.819010,0.797993
SVR,0.135908,0.264250,0.368658,0.781711,0.884553,0.869439,0.200150,0.316087,0.447381,0.685184,0.829017,0.810594
MLPRegressor,0.138438,0.270691,0.372072,0.777649,0.882173,0.862267,0.201245,0.320090,0.448603,0.683461,0.827412,0.809617