In [1]:
#Starts from here
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.linear_model import LinearRegression, LogisticRegression  # LogisticRegression is not used for regression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler 
from scipy.stats import pearsonr, spearmanr
from sklearn.model_selection import train_test_split
from tqdm import tqdm

def remove_low_variance_columns(df, threshold=0.005):
    # df = df.drop(['ID','SMILES','Permeability'],axis=1)
    variances = df.var()
    
    # Identify columns with variance below the threshold
    low_variance_columns = variances[variances < threshold].index.tolist()
    
    df_cleaned = df.drop(columns=low_variance_columns)
    
    return df_cleaned, low_variance_columns

def features(df, target_column='Permeability', threshold=0.9):
    correlation_matrix = df.corr()
    
    features_to_drop = set()
    
    for feature in correlation_matrix.columns:
        if feature == target_column:
            continue 
        target_corr = correlation_matrix[target_column][feature]
        
        for other_feature in correlation_matrix.columns:
            if other_feature == feature or other_feature == target_column:
                continue
            
            if abs(correlation_matrix[feature][other_feature]) > threshold:
                other_target_corr = correlation_matrix[target_column][other_feature]

                if abs(other_target_corr) < abs(target_corr):
                    features_to_drop.add(other_feature)
                else:
                    features_to_drop.add(feature)
    selected_features = [col for col in df.columns if col not in features_to_drop and col != target_column]
    
    return selected_features

In [2]:
df_desc_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Train_2d_3d_all_descriptors_RRCK.csv')
df_train = df_desc_train.sort_values(by='ID')
df_train =df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_desc_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_desc_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Test_2d_3d_all_descriptors_RRCK.csv')
df_desc_test = df_desc_test.sort_values(by='ID')
df_desc_test =df_desc_test.dropna()
df_desc_test =  df_desc_test[df_desc_train.columns]


# Fingerprints
df_fp_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/All_fingerprints_train_RRCK.csv')
df_train = df_fp_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_fp_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_fp_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/All_fingerprints_test_RRCK.csv')
df_fp_test = df_fp_test.sort_values(by='ID')
df_fp_test = df_fp_test.dropna()
df_fp_test =  df_fp_test[df_fp_train.columns]


#Smiles Embeddings
df_emb_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Embeddings/Train_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings_rrck.csv')
df_train = df_emb_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_emb_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
df_emb_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Embeddings/Test_MoLFormer-XL-both-10pct_model_1_fine_tuned_embeddings_rrck.csv')
df_emb_test = df_emb_test.sort_values(by='ID')
df_emb_test = df_emb_test.dropna()
df_emb_test =  df_emb_test[df_emb_train.columns]

#ATomic features
df_atomic_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_all_atomic_desc_RRCK.csv')
df_train = df_atomic_train.sort_values(by='ID')
df_train = df_train.dropna()
train = df_train.drop(['ID','SMILES'],axis=1)
train = train.select_dtypes(include=['number'])
train, _ = remove_low_variance_columns(train)
selected_features = features(train, "Permeability")
df_atomic_train = pd.concat( [df_train[['ID','SMILES','Permeability']],df_train[selected_features] ], axis=1)
# df_atomic_train =pd.concat( [df_train['SMILES'], df_train.select_dtypes(include=['number'])], axis=1)
df_atomic_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_all_atomic_desc_RRCK.csv')
df_atomic_test = df_atomic_test.sort_values(by='ID')
df_atomic_test = df_atomic_test.dropna()
df_atomic_test =  df_atomic_test[df_atomic_train.columns]


print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Loading completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
df_fp_test = df_fp_test[df_fp_test['ID'].isin(df_desc_test['ID'])]
df_fp_train = df_fp_train[df_fp_train['ID'].isin(df_desc_train['ID'])]

df_emb_test = df_emb_test[df_emb_test['ID'].isin(df_desc_test['ID'])]
df_emb_train = df_emb_train[df_emb_train['ID'].isin(df_desc_train['ID'])]

df_atomic_test = df_atomic_test[df_atomic_test['ID'].isin(df_desc_test['ID'])]
df_atomic_train = df_atomic_train[df_atomic_train['ID'].isin(df_desc_train['ID'])]
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print('Data Processing completed')
print('XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
print(df_desc_train.shape)
print(df_desc_test.shape)
print(df_fp_train.shape)
print(df_fp_test.shape)
print(df_emb_train.shape)
print(df_emb_test.shape)
print(df_atomic_train.shape)
print(df_atomic_test.shape)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Loading completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data Processing completed
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
(140, 250)
(35, 250)
(140, 347)
(35, 347)
(140, 637)
(35, 637)
(140, 13)
(35, 13)

In [3]:
merge_keys = ['ID', 'SMILES', 'Permeability']

merged_train = df_desc_train.merge(df_fp_train, on=merge_keys)
merged_train = merged_train.merge(df_emb_train, on=merge_keys)
merged_train = merged_train.merge(df_atomic_train, on=merge_keys)

merged_test = df_desc_test.merge(df_fp_test, on=merge_keys)
merged_test = merged_test.merge(df_emb_test, on=merge_keys)
merged_test = merged_test.merge(df_atomic_test, on=merge_keys)

In [4]:
X_train = merged_train.drop(columns=['ID', 'SMILES']).select_dtypes(include=['number'])
selected_final_features = features(X_train, target_column='Permeability')

train = pd.concat([merged_train[['ID', 'SMILES', 'Permeability']], X_train[selected_final_features]], axis=1)
test = merged_test[train.columns] 

print('selected_final_features', selected_final_features )
print("Final Train shape:", train.shape)
print("Final Test shape:", test.shape)

selected_final_features ['qed', 'SPS', 'MaxAbsPartialCharge', 'FpDensityMorgan1', 'BCUT2D_MRHI', 'AvgIpc', 'BalabanJ_x', 'Ipc', 'PEOE_VSA14', 'EState_VSA11', 'NumSaturatedRings', 'fr_alkyl_halide', 'fr_allylic_oxid', 'fr_morpholine', 'fr_unbrch_alkane', 'AdjacencyMatrix.6', 'AATS.12', 'AATS.67', 'AATS.80', 'AATS.93', 'AATS.95', 'AATS.96', 'ATSC.1', 'ATSC.6', 'ATSC.7', 'ATSC.8', 'ATSC.11', 'ATSC.16', 'ATSC.17', 'ATSC.20', 'ATSC.22', 'ATSC.24', 'ATSC.25', 'ATSC.26', 'ATSC.28', 'ATSC.32', 'ATSC.35', 'ATSC.44', 'ATSC.46', 'ATSC.64', 'ATSC.75', 'ATSC.80', 'ATSC.87', 'ATSC.95', 'ATSC.97', 'ATSC.98', 'ATSC.105', 'ATSC.106', 'AATSC.11', 'AATSC.12', 'AATSC.14', 'AATSC.15', 'AATSC.16', 'AATSC.34', 'AATSC.47', 'AATSC.49', 'AATSC.52', 'GATS.3', 'GATS.4', 'GATS.5', 'GATS.7', 'GATS.13', 'GATS.14', 'GATS.20', 'GATS.22', 'GATS.30', 'GATS.45', 'GATS.82', 'BCUT.3', 'Chi.15', 'AtomTypeEState.96', 'AtomTypeEState.129', 'AtomTypeEState.170', 'AtomTypeEState.173', 'AtomTypeEState.245', 'AtomTypeEState.249', 'AtomTypeEState.252', 'AtomTypeEState.271', 'EtaVEMCount.6', 'InformationContent.4', 'LogS', 'MolecularDistanceEdge.4', 'MolecularDistanceEdge.7', 'RingCount.64', 'ALogP', 'AATS5v', 'AATS7i', 'AATS2s', 'AATS5s', 'ATSC4c', 'ATSC5c', 'ATSC5v', 'ATSC2e', 'ATSC3i', 'ATSC4i', 'ATSC2s', 'ATSC3s', 'ATSC4s', 'AATSC5m', 'AATSC6m', 'AATSC7v', 'AATSC0i', 'AATSC4s', 'GATS7c', 'GATS5e', 'GATS6i', 'GATS8s', 'VR1_DzZ', 'VE3_Dzv', 'VR1_Dzv', 'VE3_Dze', 'VR2_Dze', 'VE3_Dzp', 'VR2_Dzp', 'VE1_Dzi', 'VE3_Dzi', 'VR1_Dzi', 'VE1_Dzs', 'VE3_Dzs', 'VR1_Dzs', 'BCUTp-1l', 'BCUTp-1h', 'SpMax1_Bhs', 'SpMax4_Bhs', 'SpMax7_Bhs', 'SpMax8_Bhs', 'SP-6', 'VP-6', 'EE_Dt', 'VE3_Dt', 'VR1_Dt', 'nHBint4', 'nHBint5', 'nHBint7', 'nHBint9', 'nHBint10', 'SHBd', 'SdssC', 'minHBd', 'minHBint3', 'minHBint4', 'minHBint5', 'minHBint6', 'minHBint7', 'minHBint8', 'minHBint10', 'minHssNH', 'minHCsatu', 'minsCH3', 'minssNH', 'minsssN', 'minsOH', 'maxHBint4', 'maxHBint6', 'maxHBint7', 'maxHBint8', 'maxHBint10', 'maxHssNH', 'maxsCH3', 'maxssCH2', 'maxdssC', 'maxsssN', 'maxsF', 'gmin', 'LipoaffinityIndex', 'MAXDN', 'IC1', 'ZMIC5', 'nAtomLC', 'nAtomP', 'nAtomLAC', 'MDEC-11', 'MDEC-12', 'MDEC-13', 'MDEC-22', 'MDEC-33', 'MDEO-12', 'MDEN-22', 'MDEN-23', 'MDEN-33', 'MLFER_S', 'MLFER_E', 'nFRing', 'LipinskiFailures', 'VE3_D', 'VR2_D', 'XLogP', '3d_rdkit_10', '3d_rdkit_11', 'TDB3m', 'TDB5m', 'TDB6m', 'TDB10m', 'TDB1e', 'TDB5e', 'TDB8e', 'TDB9e', 'TDB4p', 'TDB1i', 'TDB2i', 'TDB3i', 'TDB4i', 'TDB5i', 'TDB7i', 'TDB8i', 'TDB1s', 'TDB3s', 'TDB6s', 'TDB7s', 'TDB8s', 'TDB9s', 'TDB10s', 'PPSA-3', 'DPSA-3', 'RPCS', 'RNCS', 'TPSA_y', 'LOBMAX', 'LOBMIN', 'MOMI-XY', 'MOMI-XZ', 'geomDiameter', 'geomShape', 'RDF20m', 'RDF30m', 'RDF65m', 'RDF70v', 'RDF55p', 'RDF60p', 'RDF10s', 'RDF15s', 'RDF25s', 'RDF30s', 'RDF40s', 'RDF45s', 'RDF55s', 'RDF65s', 'RDF80s', 'L3m', 'Dm', 'Dv', 'De', 'L2s', 'Morgan_fp_42', 'Morgan_fp_65', 'Morgan_fp_84', 'Morgan_fp_109', 'Morgan_fp_160', 'Morgan_fp_269', 'Morgan_fp_355', 'Morgan_fp_400', 'Morgan_fp_444', 'Morgan_fp_476', 'Morgan_fp_530', 'Morgan_fp_668', 'Morgan_fp_675', 'Morgan_fp_684', 'Morgan_fp_794', 'Morgan_fp_807', 'Morgan_fp_811', 'Morgan_fp_832', 'Morgan_fp_893', 'Morgan_fp_919', 'Morgan_fp_957', 'Morgan_fp_1089', 'Morgan_fp_1345', 'Morgan_fp_1352', 'Morgan_fp_1495', 'Morgan_fp_1516', 'Morgan_fp_1662', 'Morgan_fp_1676', 'Morgan_fp_1689', 'Morgan_fp_1783', 'Morgan_fp_1807', 'Morgan_fp_1946', 'Morgan_fp_1994', 'count_fp_19', 'count_fp_61', 'count_fp_80', 'count_fp_115', 'count_fp_160', 'count_fp_219', 'count_fp_227', 'count_fp_231', 'count_fp_269', 'count_fp_340', 'count_fp_355', 'count_fp_444', 'count_fp_458', 'count_fp_476', 'count_fp_552', 'count_fp_668', 'count_fp_675', 'count_fp_684', 'count_fp_701', 'count_fp_743', 'count_fp_807', 'count_fp_893', 'count_fp_999', 'count_fp_1001', 'count_fp_1006', 'count_fp_1019', 'count_fp_1199', 'count_fp_1312', 'count_fp_1345', 'count_fp_1380', 'count_fp_1454', 'count_fp_1480', 'count_fp_1495', 'count_fp_1750', 'count_fp_1754', 'count_fp_1807', 'count_fp_1994', 'AD2D414', 'APC2D3_C_N', 'APC2D5_C_N', 'APC2D5_C_O', 'APC2D6_C_N', 'APC2D7_C_C', 'APC2D8_C_O', 'APC2D8_N_N', 'APC2D8_O_O', 'APC2D9_C_N', 'APC2D9_C_O', 'APC2D9_N_N', 'APC2D9_O_O', 'APC2D10_C_O', 'APC2D10_N_N', 'ExtFP44', 'ExtFP69', 'ExtFP84', 'ExtFP86', 'ExtFP102', 'ExtFP110', 'ExtFP112', 'ExtFP119', 'ExtFP150', 'ExtFP159', 'ExtFP162', 'ExtFP169', 'ExtFP180', 'ExtFP201', 'ExtFP204', 'ExtFP221', 'ExtFP222', 'ExtFP223', 'ExtFP250', 'ExtFP264', 'ExtFP269', 'ExtFP281', 'ExtFP291', 'ExtFP303', 'ExtFP311', 'ExtFP327', 'ExtFP331', 'ExtFP336', 'ExtFP341', 'ExtFP352', 'ExtFP369', 'ExtFP374', 'ExtFP378', 'ExtFP379', 'ExtFP386', 'ExtFP395', 'ExtFP405', 'ExtFP407', 'ExtFP409', 'ExtFP410', 'ExtFP412', 'ExtFP427', 'ExtFP432', 'ExtFP441', 'ExtFP454', 'ExtFP475', 'ExtFP494', 'ExtFP527', 'ExtFP532', 'ExtFP551', 'ExtFP554', 'ExtFP555', 'ExtFP560', 'ExtFP568', 'ExtFP573', 'ExtFP574', 'ExtFP576', 'ExtFP587', 'ExtFP592', 'ExtFP596', 'ExtFP600', 'ExtFP630', 'ExtFP640', 'ExtFP666', 'ExtFP670', 'ExtFP672', 'ExtFP689', 'ExtFP712', 'ExtFP718', 'ExtFP728', 'ExtFP736', 'ExtFP751', 'ExtFP759', 'ExtFP762', 'ExtFP789', 'ExtFP805', 'ExtFP812', 'ExtFP816', 'ExtFP828', 'ExtFP835', 'ExtFP875', 'ExtFP886', 'ExtFP926', 'ExtFP933', 'ExtFP941', 'ExtFP944', 'ExtFP953', 'ExtFP957', 'ExtFP962', 'ExtFP965', 'ExtFP973', 'ExtFP983', 'ExtFP986', 'ExtFP991', 'ExtFP997', 'ExtFP1012', 'ExtFP1016', 'FP10', 'FP11', 'FP25', 'FP44', 'FP48', 'FP56', 'FP70', 'FP76', 'FP123', 'FP153', 'FP179', 'FP182', 'FP188', 'FP207', 'FP215', 'FP220', 'FP226', 'FP251', 'FP269', 'FP275', 'FP276', 'FP298', 'FP326', 'FP334', 'FP344', 'FP345', 'FP352', 'FP355', 'FP427', 'FP430', 'FP463', 'FP464', 'FP476', 'FP481', 'FP483', 'FP489', 'FP509', 'FP524', 'FP525', 'FP531', 'FP546', 'FP549', 'FP610', 'FP618', 'FP622', 'FP637', 'FP645', 'FP676', 'FP690', 'FP695', 'FP712', 'FP713', 'FP714', 'FP717', 'FP728', 'FP746', 'FP766', 'FP774', 'FP783', 'FP784', 'FP795', 'FP811', 'FP820', 'FP825', 'FP835', 'FP836', 'FP841', 'FP870', 'FP873', 'FP917', 'FP949', 'FP950', 'FP952', 'FP959', 'FP961', 'FP967', 'FP985', 'FP1002', 'GraphFP31', 'GraphFP59', 'GraphFP170', 'GraphFP255', 'GraphFP270', 'GraphFP303', 'GraphFP311', 'GraphFP323', 'GraphFP404', 'GraphFP465', 'GraphFP519', 'GraphFP522', 'GraphFP651', 'GraphFP754', 'GraphFP780', 'GraphFP790', 'GraphFP808', 'GraphFP817', 'GraphFP837', 'GraphFP867', 'GraphFP889', 'GraphFP913', 'GraphFP920', 'GraphFP926', 'KRFP2', 'KRFP303', 'KRFP680', 'KRFP697', 'KRFP3393', 'KRFP3660', 'KRFPC1', 'KRFPC2', 'KRFPC98', 'KRFPC297', 'KRFPC298', 'KRFPC302', 'KRFPC605', 'KRFPC680', 'KRFPC842', 'KRFPC3369', 'KRFPC3393', 'KRFPC3659', 'KRFPC3660', 'KRFPC3692', 'KRFPC3697', 'KRFPC3712', 'KRFPC3729', 'KRFPC3735', 'KRFPC3737', 'KRFPC3740', 'KRFPC3742', 'MACCSFP54', 'MACCSFP75', 'MACCSFP86', 'MACCSFP91', 'MACCSFP104', 'MACCSFP109', 'MACCSFP115', 'MACCSFP128', 'MACCSFP129', 'MACCSFP132', 'MACCSFP138', 'PubchemFP1', 'PubchemFP13', 'PubchemFP17', 'PubchemFP21', 'PubchemFP258', 'PubchemFP259', 'PubchemFP464', 'PubchemFP516', 'PubchemFP685', 'PubchemFP688', 'PubchemFP692', 'PubchemFP710', 'SubFPC302', 'SubFPC307', 'x_fine_emb_MFXL0', 'x_fine_emb_MFXL1', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL4', 'x_fine_emb_MFXL5', 'x_fine_emb_MFXL6', 'x_fine_emb_MFXL8', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL10', 'x_fine_emb_MFXL11', 'x_fine_emb_MFXL13', 'x_fine_emb_MFXL14', 'x_fine_emb_MFXL16', 'x_fine_emb_MFXL18', 'x_fine_emb_MFXL20', 'x_fine_emb_MFXL21', 'x_fine_emb_MFXL22', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL25', 'x_fine_emb_MFXL26', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL29', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL31', 'x_fine_emb_MFXL32', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL37', 'x_fine_emb_MFXL39', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL44', 'x_fine_emb_MFXL45', 'x_fine_emb_MFXL46', 'x_fine_emb_MFXL48', 'x_fine_emb_MFXL49', 'x_fine_emb_MFXL51', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL53', 'x_fine_emb_MFXL54', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL58', 'x_fine_emb_MFXL61', 'x_fine_emb_MFXL62', 'x_fine_emb_MFXL63', 'x_fine_emb_MFXL64', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL66', 'x_fine_emb_MFXL67', 'x_fine_emb_MFXL68', 'x_fine_emb_MFXL69', 'x_fine_emb_MFXL70', 'x_fine_emb_MFXL71', 'x_fine_emb_MFXL72', 'x_fine_emb_MFXL73', 'x_fine_emb_MFXL74', 'x_fine_emb_MFXL75', 'x_fine_emb_MFXL76', 'x_fine_emb_MFXL77', 'x_fine_emb_MFXL78', 'x_fine_emb_MFXL79', 'x_fine_emb_MFXL81', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL83', 'x_fine_emb_MFXL84', 'x_fine_emb_MFXL86', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL88', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL93', 'x_fine_emb_MFXL94', 'x_fine_emb_MFXL95', 'x_fine_emb_MFXL96', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL98', 'x_fine_emb_MFXL99', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL102', 'x_fine_emb_MFXL103', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL106', 'x_fine_emb_MFXL107', 'x_fine_emb_MFXL108', 'x_fine_emb_MFXL109', 'x_fine_emb_MFXL110', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL112', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL116', 'x_fine_emb_MFXL117', 'x_fine_emb_MFXL118', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL120', 'x_fine_emb_MFXL121', 'x_fine_emb_MFXL123', 'x_fine_emb_MFXL124', 'x_fine_emb_MFXL125', 'x_fine_emb_MFXL126', 'x_fine_emb_MFXL127', 'x_fine_emb_MFXL128', 'x_fine_emb_MFXL130', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL133', 'x_fine_emb_MFXL134', 'x_fine_emb_MFXL135', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL137', 'x_fine_emb_MFXL138', 'x_fine_emb_MFXL139', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL144', 'x_fine_emb_MFXL145', 'x_fine_emb_MFXL146', 'x_fine_emb_MFXL149', 'x_fine_emb_MFXL150', 'x_fine_emb_MFXL151', 'x_fine_emb_MFXL152', 'x_fine_emb_MFXL153', 'x_fine_emb_MFXL154', 'x_fine_emb_MFXL155', 'x_fine_emb_MFXL156', 'x_fine_emb_MFXL157', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL160', 'x_fine_emb_MFXL162', 'x_fine_emb_MFXL163', 'x_fine_emb_MFXL164', 'x_fine_emb_MFXL165', 'x_fine_emb_MFXL166', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL168', 'x_fine_emb_MFXL169', 'x_fine_emb_MFXL171', 'x_fine_emb_MFXL172', 'x_fine_emb_MFXL173', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL175', 'x_fine_emb_MFXL176', 'x_fine_emb_MFXL177', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL179', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL181', 'x_fine_emb_MFXL182', 'x_fine_emb_MFXL183', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL186', 'x_fine_emb_MFXL187', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL190', 'x_fine_emb_MFXL191', 'x_fine_emb_MFXL192', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL194', 'x_fine_emb_MFXL195', 'x_fine_emb_MFXL196', 'x_fine_emb_MFXL197', 'x_fine_emb_MFXL198', 'x_fine_emb_MFXL199', 'x_fine_emb_MFXL200', 'x_fine_emb_MFXL201', 'x_fine_emb_MFXL203', 'x_fine_emb_MFXL204', 'x_fine_emb_MFXL205', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL208', 'x_fine_emb_MFXL209', 'x_fine_emb_MFXL210', 'x_fine_emb_MFXL211', 'x_fine_emb_MFXL212', 'x_fine_emb_MFXL213', 'x_fine_emb_MFXL214', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL218', 'x_fine_emb_MFXL219', 'x_fine_emb_MFXL220', 'x_fine_emb_MFXL221', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL225', 'x_fine_emb_MFXL226', 'x_fine_emb_MFXL227', 'x_fine_emb_MFXL228', 'x_fine_emb_MFXL229', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL231', 'x_fine_emb_MFXL233', 'x_fine_emb_MFXL234', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL236', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL238', 'x_fine_emb_MFXL239', 'x_fine_emb_MFXL240', 'x_fine_emb_MFXL241', 'x_fine_emb_MFXL242', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL245', 'x_fine_emb_MFXL246', 'x_fine_emb_MFXL247', 'x_fine_emb_MFXL249', 'x_fine_emb_MFXL250', 'x_fine_emb_MFXL251', 'x_fine_emb_MFXL252', 'x_fine_emb_MFXL253', 'x_fine_emb_MFXL254', 'x_fine_emb_MFXL255', 'x_fine_emb_MFXL256', 'x_fine_emb_MFXL257', 'x_fine_emb_MFXL258', 'x_fine_emb_MFXL259', 'x_fine_emb_MFXL260', 'x_fine_emb_MFXL262', 'x_fine_emb_MFXL264', 'x_fine_emb_MFXL265', 'x_fine_emb_MFXL266', 'x_fine_emb_MFXL267', 'x_fine_emb_MFXL269', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL271', 'x_fine_emb_MFXL272', 'x_fine_emb_MFXL273', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL277', 'x_fine_emb_MFXL278', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL281', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL287', 'x_fine_emb_MFXL288', 'x_fine_emb_MFXL289', 'x_fine_emb_MFXL290', 'x_fine_emb_MFXL293', 'x_fine_emb_MFXL294', 'x_fine_emb_MFXL295', 'x_fine_emb_MFXL296', 'x_fine_emb_MFXL297', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL299', 'x_fine_emb_MFXL301', 'x_fine_emb_MFXL302', 'x_fine_emb_MFXL305', 'x_fine_emb_MFXL306', 'x_fine_emb_MFXL308', 'x_fine_emb_MFXL310', 'x_fine_emb_MFXL311', 'x_fine_emb_MFXL312', 'x_fine_emb_MFXL313', 'x_fine_emb_MFXL314', 'x_fine_emb_MFXL316', 'x_fine_emb_MFXL317', 'x_fine_emb_MFXL319', 'x_fine_emb_MFXL320', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL323', 'x_fine_emb_MFXL324', 'x_fine_emb_MFXL325', 'x_fine_emb_MFXL327', 'x_fine_emb_MFXL328', 'x_fine_emb_MFXL329', 'x_fine_emb_MFXL330', 'x_fine_emb_MFXL331', 'x_fine_emb_MFXL333', 'x_fine_emb_MFXL334', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL336', 'x_fine_emb_MFXL337', 'x_fine_emb_MFXL338', 'x_fine_emb_MFXL339', 'x_fine_emb_MFXL340', 'x_fine_emb_MFXL341', 'x_fine_emb_MFXL342', 'x_fine_emb_MFXL343', 'x_fine_emb_MFXL344', 'x_fine_emb_MFXL346', 'x_fine_emb_MFXL347', 'x_fine_emb_MFXL348', 'x_fine_emb_MFXL349', 'x_fine_emb_MFXL350', 'x_fine_emb_MFXL351', 'x_fine_emb_MFXL352', 'x_fine_emb_MFXL353', 'x_fine_emb_MFXL354', 'x_fine_emb_MFXL356', 'x_fine_emb_MFXL357', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL360', 'x_fine_emb_MFXL363', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL367', 'x_fine_emb_MFXL368', 'x_fine_emb_MFXL369', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL371', 'x_fine_emb_MFXL372', 'x_fine_emb_MFXL373', 'x_fine_emb_MFXL374', 'x_fine_emb_MFXL375', 'x_fine_emb_MFXL376', 'x_fine_emb_MFXL377', 'x_fine_emb_MFXL379', 'x_fine_emb_MFXL380', 'x_fine_emb_MFXL382', 'x_fine_emb_MFXL383', 'x_fine_emb_MFXL384', 'x_fine_emb_MFXL385', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL388', 'x_fine_emb_MFXL389', 'x_fine_emb_MFXL390', 'x_fine_emb_MFXL391', 'x_fine_emb_MFXL392', 'x_fine_emb_MFXL393', 'x_fine_emb_MFXL395', 'x_fine_emb_MFXL396', 'x_fine_emb_MFXL397', 'x_fine_emb_MFXL398', 'x_fine_emb_MFXL399', 'x_fine_emb_MFXL400', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL402', 'x_fine_emb_MFXL403', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL407', 'x_fine_emb_MFXL408', 'x_fine_emb_MFXL409', 'x_fine_emb_MFXL410', 'x_fine_emb_MFXL412', 'x_fine_emb_MFXL413', 'x_fine_emb_MFXL414', 'x_fine_emb_MFXL415', 'x_fine_emb_MFXL416', 'x_fine_emb_MFXL417', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL420', 'x_fine_emb_MFXL421', 'x_fine_emb_MFXL422', 'x_fine_emb_MFXL423', 'x_fine_emb_MFXL425', 'x_fine_emb_MFXL427', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL429', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL431', 'x_fine_emb_MFXL433', 'x_fine_emb_MFXL434', 'x_fine_emb_MFXL436', 'x_fine_emb_MFXL437', 'x_fine_emb_MFXL438', 'x_fine_emb_MFXL439', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL441', 'x_fine_emb_MFXL443', 'x_fine_emb_MFXL444', 'x_fine_emb_MFXL446', 'x_fine_emb_MFXL447', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL449', 'x_fine_emb_MFXL451', 'x_fine_emb_MFXL452', 'x_fine_emb_MFXL453', 'x_fine_emb_MFXL454', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL456', 'x_fine_emb_MFXL457', 'x_fine_emb_MFXL459', 'x_fine_emb_MFXL460', 'x_fine_emb_MFXL461', 'x_fine_emb_MFXL463', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL465', 'x_fine_emb_MFXL466', 'x_fine_emb_MFXL467', 'x_fine_emb_MFXL468', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL470', 'x_fine_emb_MFXL471', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL473', 'x_fine_emb_MFXL474', 'x_fine_emb_MFXL475', 'x_fine_emb_MFXL476', 'x_fine_emb_MFXL478', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL483', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL485', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL489', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL492', 'x_fine_emb_MFXL494', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL497', 'x_fine_emb_MFXL498', 'x_fine_emb_MFXL499', 'x_fine_emb_MFXL500', 'x_fine_emb_MFXL501', 'x_fine_emb_MFXL502', 'x_fine_emb_MFXL503', 'x_fine_emb_MFXL504', 'x_fine_emb_MFXL506', 'x_fine_emb_MFXL507', 'x_fine_emb_MFXL508', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL510', 'x_fine_emb_MFXL512', 'x_fine_emb_MFXL514', 'x_fine_emb_MFXL515', 'x_fine_emb_MFXL517', 'x_fine_emb_MFXL518', 'x_fine_emb_MFXL519', 'x_fine_emb_MFXL520', 'x_fine_emb_MFXL521', 'x_fine_emb_MFXL522', 'x_fine_emb_MFXL523', 'x_fine_emb_MFXL524', 'x_fine_emb_MFXL526', 'x_fine_emb_MFXL527', 'x_fine_emb_MFXL529', 'x_fine_emb_MFXL530', 'x_fine_emb_MFXL531', 'x_fine_emb_MFXL532', 'x_fine_emb_MFXL533', 'x_fine_emb_MFXL534', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL537', 'x_fine_emb_MFXL538', 'x_fine_emb_MFXL539', 'x_fine_emb_MFXL543', 'x_fine_emb_MFXL545', 'x_fine_emb_MFXL546', 'x_fine_emb_MFXL547', 'x_fine_emb_MFXL548', 'x_fine_emb_MFXL549', 'x_fine_emb_MFXL550', 'x_fine_emb_MFXL551', 'x_fine_emb_MFXL552', 'x_fine_emb_MFXL554', 'x_fine_emb_MFXL555', 'x_fine_emb_MFXL556', 'x_fine_emb_MFXL557', 'x_fine_emb_MFXL558', 'x_fine_emb_MFXL559', 'x_fine_emb_MFXL561', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL563', 'x_fine_emb_MFXL564', 'x_fine_emb_MFXL565', 'x_fine_emb_MFXL566', 'x_fine_emb_MFXL567', 'x_fine_emb_MFXL568', 'x_fine_emb_MFXL569', 'x_fine_emb_MFXL571', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL574', 'x_fine_emb_MFXL575', 'x_fine_emb_MFXL576', 'x_fine_emb_MFXL577', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL580', 'x_fine_emb_MFXL582', 'x_fine_emb_MFXL583', 'x_fine_emb_MFXL584', 'x_fine_emb_MFXL585', 'x_fine_emb_MFXL586', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL588', 'x_fine_emb_MFXL589', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL591', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL594', 'x_fine_emb_MFXL595', 'x_fine_emb_MFXL596', 'x_fine_emb_MFXL597', 'x_fine_emb_MFXL598', 'x_fine_emb_MFXL600', 'x_fine_emb_MFXL601', 'x_fine_emb_MFXL604', 'x_fine_emb_MFXL606', 'x_fine_emb_MFXL608', 'x_fine_emb_MFXL609', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL614', 'x_fine_emb_MFXL615', 'x_fine_emb_MFXL616', 'x_fine_emb_MFXL618', 'x_fine_emb_MFXL619', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL621', 'x_fine_emb_MFXL622', 'x_fine_emb_MFXL625', 'x_fine_emb_MFXL626', 'x_fine_emb_MFXL627', 'x_fine_emb_MFXL628', 'x_fine_emb_MFXL629', 'x_fine_emb_MFXL630', 'x_fine_emb_MFXL631', 'x_fine_emb_MFXL632', 'x_fine_emb_MFXL633', 'x_fine_emb_MFXL634', 'x_fine_emb_MFXL635', 'x_fine_emb_MFXL636', 'x_fine_emb_MFXL637', 'x_fine_emb_MFXL638', 'x_fine_emb_MFXL639', 'x_fine_emb_MFXL641', 'x_fine_emb_MFXL642', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL644', 'x_fine_emb_MFXL645', 'x_fine_emb_MFXL646', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL648', 'x_fine_emb_MFXL649', 'x_fine_emb_MFXL650', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL652', 'x_fine_emb_MFXL653', 'x_fine_emb_MFXL654', 'x_fine_emb_MFXL655', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL659', 'x_fine_emb_MFXL660', 'x_fine_emb_MFXL661', 'x_fine_emb_MFXL662', 'x_fine_emb_MFXL663', 'x_fine_emb_MFXL664', 'x_fine_emb_MFXL665', 'x_fine_emb_MFXL666', 'x_fine_emb_MFXL667', 'x_fine_emb_MFXL669', 'x_fine_emb_MFXL670', 'x_fine_emb_MFXL671', 'x_fine_emb_MFXL672', 'x_fine_emb_MFXL675', 'x_fine_emb_MFXL676', 'x_fine_emb_MFXL677', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL679', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL681', 'x_fine_emb_MFXL682', 'x_fine_emb_MFXL683', 'x_fine_emb_MFXL684', 'x_fine_emb_MFXL685', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL689', 'x_fine_emb_MFXL690', 'x_fine_emb_MFXL691', 'x_fine_emb_MFXL693', 'x_fine_emb_MFXL694', 'x_fine_emb_MFXL696', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL698', 'x_fine_emb_MFXL699', 'x_fine_emb_MFXL700', 'x_fine_emb_MFXL701', 'x_fine_emb_MFXL702', 'x_fine_emb_MFXL703', 'x_fine_emb_MFXL704', 'x_fine_emb_MFXL705', 'x_fine_emb_MFXL706', 'x_fine_emb_MFXL707', 'x_fine_emb_MFXL708', 'x_fine_emb_MFXL709', 'x_fine_emb_MFXL710', 'x_fine_emb_MFXL711', 'x_fine_emb_MFXL712', 'x_fine_emb_MFXL713', 'x_fine_emb_MFXL715', 'x_fine_emb_MFXL716', 'x_fine_emb_MFXL717', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL719', 'x_f

In [5]:
def train_and_test_predict(models, X_train, y_train, X_test, y_test):
    kf = KFold(n_splits=5, shuffle=True, random_state=101)
    results = {}
    predictions = []  

    for model in models:
        model_name = model.__class__.__name__
        predictions_train = []
        actual_y_train = []

        test_predictions_folds = []

        

        for train_index, val_index in kf.split(X_train):
            X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
            y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

            model.fit(X_train_fold, y_train_fold)

            y_pred_fold = model.predict(X_val_fold)
            y_pred_fold = np.clip(y_pred_fold, -10, -4.0)
            predictions_train.extend(y_pred_fold)
            actual_y_train.extend(y_val_fold)

            predictions_test_fold = model.predict(X_test)
            predictions_test_fold = np.clip(predictions_test_fold, -10, -4.0)
            test_predictions_folds.append(predictions_test_fold)


        mse_train = mean_squared_error(actual_y_train, predictions_train)
        mae_train = mean_absolute_error(actual_y_train, predictions_train)
        rmse_train = np.sqrt(mse_train)
        r2_train = r2_score(actual_y_train, predictions_train)
        pearson_train, _ = pearsonr(actual_y_train, predictions_train)
        spearman_train, _ = spearmanr(actual_y_train, predictions_train)


        predictions_test_mean = np.mean(test_predictions_folds, axis=0)
        predictions_test_std = np.std(test_predictions_folds, axis=0)

        mse_test = mean_squared_error(y_test, predictions_test_mean)
        mae_test = mean_absolute_error(y_test, predictions_test_mean)
        rmse_test = np.sqrt(mse_test)
        r2_test = r2_score(y_test, predictions_test_mean)
        print(r2_test)
        pearson_test, _ = pearsonr(y_test, predictions_test_mean)
        spearman_test, _ = spearmanr(y_test, predictions_test_mean)
        
        

        predictions.append({
            'Model': model_name,
            'Y Train pred': predictions_train,
            'Y Test actual': y_test,
            'Test prediction folds': test_predictions_folds,
            'Test Predictions Mean': predictions_test_mean,
            'Test Predictions Std': predictions_test_std,

        })

        results[model_name] = {
            'Train MSE (5 fold cv)': f"{mse_train:.4f}",
            'Train MAE (5 fold cv)': f"{mae_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train RMSE (5 fold cv)': f"{rmse_train:.4f}",
            'Train R2 (5 fold cv)': f"{r2_train:.4f}",
            'Train PCC (5 fold cv)': f"{pearson_train:.4f}",
            'Train SCC (5 fold cv)': f"{spearman_train:.4f}",
            'Test MSE': f"{mse_test:.4f}",
            'Test MAE': f"{mae_test:.4f}",
            'Test RMSE': f"{rmse_test:.4f}",
            'Test R2': f"{r2_test:.4f}",
            'Test Pearson Correlation': f"{pearson_test:.4f}",
            'Test Spearman Correlation': f"{spearman_test:.4f}",
        }

    results_df = pd.DataFrame(results).T
    predictions_df = pd.DataFrame(predictions)

    return results_df, predictions_df

In [6]:
X_train = train.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test[X_train.columns]
y_test = test['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 1214)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 1214)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 1.022749 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 33481
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 1005
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.837442 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 33489
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 1007
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.932693 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 33421
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 1002
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1483,0.3097,0.3851,0.6212,0.7885,0.7845,0.2291,0.3432,0.4786,0.5040,0.7118,0.6721
DecisionTreeRegressor,0.3475,0.4550,0.5895,0.1120,0.5706,0.5918,0.2947,0.3910,0.5429,0.3620,0.6369,0.5743
RandomForestRegressor,0.1470,0.3036,0.3834,0.6245,0.7911,0.7834,0.2402,0.3444,0.4901,0.4800,0.6940,0.6478
GradientBoostingRegressor,0.1592,0.3089,0.3989,0.5934,0.7710,0.7674,0.2200,0.3345,0.4691,0.5236,0.7252,0.6836
AdaBoostRegressor,0.1498,0.3048,0.3870,0.6173,0.7857,0.7846,0.2239,0.3375,0.4731,0.5153,0.7192,0.6535
XGBRegressor,0.1860,0.3272,0.4312,0.5248,0.7329,0.7250,0.2427,0.3557,0.4926,0.4746,0.6914,0.6535
ExtraTreesRegressor,0.1382,0.2891,0.3718,0.6469,0.8060,0.8083,0.2205,0.3339,0.4696,0.5226,0.7248,0.6797
LinearRegression,0.2615,0.4070,0.5114,0.3319,0.6752,0.6610,0.3341,0.3995,0.5780,0.2767,0.6180,0.5886
KNeighborsRegressor,0.2063,0.3384,0.4542,0.4728,0.7042,0.7116,0.3057,0.3740,0.5529,0.3382,0.6015,0.5306
SVR,0.1544,0.3025,0.3929,0.6056,0.7807,0.7902,0.2567,0.3750,0.5067,0.4442,0.6774,0.6038
MLPRegressor,0.8891,0.7358,0.9429,-1.2716,0.4315,0.4028,0.6670,0.6122,0.8167,-0.4441,0.4583,0.4040

In [7]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_features_rrck.csv')

In [8]:
X = train.drop(columns=['ID', 'SMILES', 'Permeability'])
y = train['Permeability']

rf = RandomForestRegressor(n_estimators=100, random_state=101, n_jobs=-1)
rf.fit(X, y)

importances = rf.feature_importances_
feature_names = X.columns

In [9]:
#Top 10 features
n = 10  
top_10_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_10_features = feature_names[top_10_indices].tolist() 

# Output the list
print("Top", 10, "features:\n")
print(top_10_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_10_features]], axis=1)
test_df = test[train.columns]

Top 10 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440']

In [10]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 10)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 10)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.071393 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 390
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 10
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.080592 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 390
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 10
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.073147 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 390
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 10
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

-3.9167177575230765

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1568,0.3187,0.3960,0.5994,0.7774,0.7856,0.2369,0.3514,0.4867,0.4871,0.6987,0.6511
DecisionTreeRegressor,0.2872,0.4052,0.5359,0.2662,0.6421,0.6412,0.1942,0.3278,0.4407,0.5796,0.7617,0.7300
RandomForestRegressor,0.1534,0.3128,0.3916,0.6082,0.7807,0.7801,0.2402,0.3563,0.4901,0.4800,0.6939,0.6125
GradientBoostingRegressor,0.1663,0.3192,0.4078,0.5752,0.7639,0.7776,0.2239,0.3509,0.4732,0.5152,0.7178,0.6605
AdaBoostRegressor,0.1601,0.3131,0.4001,0.5910,0.7699,0.7692,0.2580,0.3836,0.5079,0.4414,0.6647,0.5976
XGBRegressor,0.1730,0.3220,0.4160,0.5579,0.7570,0.7638,0.2052,0.3281,0.4530,0.5557,0.7494,0.7136
ExtraTreesRegressor,0.1580,0.3147,0.3975,0.5963,0.7731,0.7785,0.2229,0.3432,0.4721,0.5174,0.7198,0.6674
LinearRegression,0.1591,0.3165,0.3989,0.5934,0.7712,0.7619,0.2623,0.3675,0.5122,0.4320,0.6733,0.5814
KNeighborsRegressor,0.1939,0.3522,0.4404,0.5045,0.7255,0.7168,0.2587,0.3496,0.5086,0.4399,0.6818,0.5916
SVR,0.1746,0.3238,0.4178,0.5540,0.7486,0.7651,0.2980,0.3875,0.5459,0.3548,0.6157,0.5543
MLPRegressor,2.0263,1.2424,1.4235,-4.1773,0.2549,0.1973,2.2710,1.2600,1.5070,-3.9167,0.2664,0.0819

In [11]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_10_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/_prediction_data_combined_top_10_features_rrck.csv')

In [12]:
#Top 20 features
n = 20  
top_20_indices = importances.argsort()[::-1][:n]  
top_20_features = feature_names[top_20_indices].tolist()  # convert to list

# Output the list
print("Top", 20, "features:\n")
print(top_20_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_20_features]], axis=1)
test_df = test[train.columns]

Top 20 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL416']

In [13]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 20)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 20)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.065372 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 780
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 20
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.072935 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 780
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 20
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.084130 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 780
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 20
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

-3.8650691917783675

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1457,0.3099,0.3817,0.6277,0.7931,0.7875,0.2383,0.3421,0.4881,0.4842,0.6994,0.6515
DecisionTreeRegressor,0.2104,0.3538,0.4587,0.4624,0.7424,0.7272,0.1968,0.3237,0.4436,0.5740,0.7589,0.7172
RandomForestRegressor,0.1405,0.3030,0.3748,0.6411,0.8008,0.7899,0.2387,0.3488,0.4885,0.4833,0.6972,0.6106
GradientBoostingRegressor,0.1661,0.3215,0.4075,0.5757,0.7634,0.7559,0.2317,0.3450,0.4813,0.4984,0.7081,0.6406
AdaBoostRegressor,0.1580,0.3144,0.3975,0.5962,0.7736,0.7742,0.2523,0.3736,0.5023,0.4537,0.6743,0.6003
XGBRegressor,0.1714,0.3284,0.4140,0.5621,0.7597,0.7602,0.2233,0.3488,0.4726,0.5165,0.7206,0.7149
ExtraTreesRegressor,0.1461,0.3083,0.3823,0.6267,0.7921,0.7843,0.2161,0.3369,0.4649,0.5320,0.7311,0.6909
LinearRegression,0.1674,0.3291,0.4092,0.5722,0.7596,0.7526,0.2404,0.3548,0.4903,0.4795,0.7068,0.6588
KNeighborsRegressor,0.1937,0.3557,0.4401,0.5050,0.7271,0.7094,0.2927,0.3597,0.5410,0.3664,0.6403,0.5784
SVR,0.1612,0.3147,0.4015,0.5881,0.7693,0.7768,0.2678,0.3675,0.5174,0.4203,0.6562,0.6227
MLPRegressor,1.8982,1.1980,1.3777,-3.8499,0.2582,0.2053,2.2471,1.2312,1.4990,-3.8651,0.1754,-0.0216

In [14]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_20_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_top_20_features_rrck.csv')

In [15]:
#Top 50 features
n = 50  
top_50_indices = importances.argsort()[::-1][:n] 
top_50_features = feature_names[top_50_indices].tolist()  # convert to list

# Output the list
print("Top", 50, "features:\n")
print(top_50_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_50_features]], axis=1)
test_df = test[train.columns]

Top 50 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL416', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL569', 'x_fine_emb_MFXL748', 'x_fine_emb_MFXL102', 'DPSA-3', 'x_fine_emb_MFXL339', 'GATS.4', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL719', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL510', 'maxsCH3', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL507', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL421', 'AvgIpc']

In [16]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 50)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 50)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.088446 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1945
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 50
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.073215 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1946
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 50
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.072910 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1942
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 50
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

-1.65627716571962

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1348,0.2953,0.3671,0.6557,0.8100,0.8126,0.2346,0.3393,0.4844,0.4921,0.7048,0.6697
DecisionTreeRegressor,0.2581,0.3836,0.5080,0.3406,0.6639,0.6449,0.2155,0.3204,0.4643,0.5334,0.7338,0.6955
RandomForestRegressor,0.1318,0.2916,0.3630,0.6633,0.8148,0.8005,0.2417,0.3406,0.4917,0.4767,0.6941,0.6454
GradientBoostingRegressor,0.1344,0.2905,0.3666,0.6565,0.8106,0.8037,0.2230,0.3270,0.4722,0.5173,0.7212,0.6696
AdaBoostRegressor,0.1416,0.2971,0.3762,0.6383,0.7990,0.7886,0.2342,0.3507,0.4839,0.4929,0.7029,0.6420
XGBRegressor,0.1650,0.3198,0.4062,0.5785,0.7679,0.7540,0.2402,0.3491,0.4901,0.4800,0.6985,0.6606
ExtraTreesRegressor,0.1227,0.2801,0.3503,0.6865,0.8287,0.8159,0.2233,0.3302,0.4725,0.5166,0.7200,0.6751
LinearRegression,0.2691,0.4250,0.5187,0.3125,0.6642,0.6493,0.3012,0.3796,0.5488,0.3478,0.6416,0.5850
KNeighborsRegressor,0.1773,0.3325,0.4211,0.5470,0.7510,0.7430,0.2586,0.3474,0.5085,0.4402,0.6752,0.6353
SVR,0.1343,0.2931,0.3665,0.6569,0.8105,0.8163,0.2652,0.3671,0.5150,0.4258,0.6612,0.6111
MLPRegressor,1.1597,0.8617,1.0769,-1.9631,0.3671,0.3236,1.2269,0.9245,1.1077,-1.6563,0.1362,-0.0214

In [17]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_50_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_top_50_features_rrck.csv')

In [18]:
#Top 100 features
n = 100  
top_100_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_100_features = feature_names[top_100_indices].tolist()  # convert to list

# Output the list
print("Top", 100, "features:\n")
print(top_100_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_100_features]], axis=1)
test_df = test[train.columns]

Top 100 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL416', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL569', 'x_fine_emb_MFXL748', 'x_fine_emb_MFXL102', 'DPSA-3', 'x_fine_emb_MFXL339', 'GATS.4', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL719', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL510', 'maxsCH3', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL507', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL421', 'AvgIpc', 'x_fine_emb_MFXL434', 'x_fine_emb_MFXL69', 'Ipc', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL555', 'x_fine_emb_MFXL731', 'VR2_D', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL399', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL565', 'x_fine_emb_MFXL501', 'ATSC.64', 'x_fine_emb_MFXL568', 'AATSC7v', 'x_fine_emb_MFXL313', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL650', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL252', 'ATSC.98', 'x_fine_emb_MFXL415', 'x_fine_emb_MFXL767', 'x_fine_emb_MFXL616', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL738', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL715', 'x_fine_emb_MFXL194', 'TDB7s', 'TPSA_y', '3d_rdkit_11', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL530', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL346', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL211', 'RDF15s', 'SP-6', 'AdjacencyMatrix.6', 'x_fine_emb_MFXL324', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL645']

In [19]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 100)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 100)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.163972 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3887
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 100
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000894 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3887
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 100
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.072843 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3880
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 100
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

-1.280222867304622

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1502,0.3145,0.3876,0.6162,0.7855,0.7881,0.2217,0.3450,0.4708,0.5200,0.7242,0.6887
DecisionTreeRegressor,0.3242,0.4364,0.5694,0.1717,0.6075,0.5824,0.2515,0.3611,0.5015,0.4555,0.6793,0.6252
RandomForestRegressor,0.1323,0.2905,0.3637,0.6620,0.8141,0.8022,0.2342,0.3398,0.4839,0.4929,0.7047,0.6553
GradientBoostingRegressor,0.1443,0.2976,0.3799,0.6312,0.7960,0.7958,0.2140,0.3269,0.4626,0.5367,0.7327,0.6873
AdaBoostRegressor,0.1347,0.2959,0.3670,0.6558,0.8104,0.8001,0.2319,0.3484,0.4816,0.4979,0.7067,0.6525
XGBRegressor,0.1723,0.3238,0.4151,0.5598,0.7585,0.7528,0.2268,0.3389,0.4762,0.5090,0.7145,0.6654
ExtraTreesRegressor,0.1241,0.2771,0.3523,0.6829,0.8270,0.8148,0.2188,0.3296,0.4678,0.5262,0.7263,0.6618
LinearRegression,1.8661,1.0321,1.3661,-3.7679,0.2053,0.2067,1.2081,0.7510,1.0991,-1.6156,0.2803,0.4116
KNeighborsRegressor,0.1757,0.3210,0.4192,0.5510,0.7549,0.7646,0.2835,0.3716,0.5324,0.3863,0.6390,0.6113
SVR,0.1381,0.2911,0.3717,0.6471,0.8047,0.8134,0.2514,0.3664,0.5014,0.4557,0.6821,0.6445
MLPRegressor,0.7759,0.7058,0.8809,-0.9824,0.4643,0.4329,1.0532,0.7889,1.0263,-1.2802,0.1891,0.1363

In [20]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_100_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_top_100_features_rrck.csv')

In [21]:
#Top 200 features
n = 200  
top_200_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_200_features = feature_names[top_200_indices].tolist()  # convert to list

# Output the list
print("Top", 200, "features:\n")
print(top_200_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_200_features]], axis=1)
test_df = test[train.columns]

Top 200 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL416', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL569', 'x_fine_emb_MFXL748', 'x_fine_emb_MFXL102', 'DPSA-3', 'x_fine_emb_MFXL339', 'GATS.4', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL719', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL510', 'maxsCH3', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL507', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL421', 'AvgIpc', 'x_fine_emb_MFXL434', 'x_fine_emb_MFXL69', 'Ipc', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL555', 'x_fine_emb_MFXL731', 'VR2_D', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL399', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL565', 'x_fine_emb_MFXL501', 'ATSC.64', 'x_fine_emb_MFXL568', 'AATSC7v', 'x_fine_emb_MFXL313', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL650', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL252', 'ATSC.98', 'x_fine_emb_MFXL415', 'x_fine_emb_MFXL767', 'x_fine_emb_MFXL616', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL738', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL715', 'x_fine_emb_MFXL194', 'TDB7s', 'TPSA_y', '3d_rdkit_11', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL530', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL346', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL211', 'RDF15s', 'SP-6', 'AdjacencyMatrix.6', 'x_fine_emb_MFXL324', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL645', 'RDF30s', 'x_fine_emb_MFXL118', 'x_fine_emb_MFXL290', 'ATSC.6', 'x_fine_emb_MFXL320', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL388', 'VR1_Dt', 'AtomTypeEState.271', 'x_fine_emb_MFXL75', 'GATS5e', 'BCUTp-1h', 'SpMax8_Bhs', 'x_fine_emb_MFXL460', 'TDB1i', 'AATSC0i', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL721', 'maxHBint8', 'MOMI-XY', 'VR2_Dzp', 'AATS.96', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL121', 'AATSC4s', 'x_fine_emb_MFXL433', 'x_fine_emb_MFXL732', 'IC1', 'x_fine_emb_MFXL214', 'ATSC.97', 'x_fine_emb_MFXL682', 'x_fine_emb_MFXL764', 'x_fine_emb_MFXL702', 'x_fine_emb_MFXL349', 'x_fine_emb_MFXL677', 'x_fine_emb_MFXL545', 'x_fine_emb_MFXL747', 'x_fine_emb_MFXL327', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL665', 'x_fine_emb_MFXL733', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL622', 'x_fine_emb_MFXL213', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL751', 'x_fine_emb_MFXL246', 'TDB2i', 'x_fine_emb_MFXL196', 'x_fine_emb_MFXL446', 'count_fp_675', 'x_fine_emb_MFXL684', 'x_fine_emb_MFXL255', 'ATSC.44', 'x_fine_emb_MFXL685', 'x_fine_emb_MFXL363', 'x_fine_emb_MFXL319', 'GraphFP817', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL392', 'x_fine_emb_MFXL558', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL683', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL356', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL308', 'RPCS', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL333', 'x_fine_emb_MFXL725', 'x_fine_emb_MFXL582', 'minssNH', 'LOBMIN', '3d_rdkit_10', 'x_fine_emb_MFXL625', 'RDF45s', 'AtomTypeEState.249', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL724', 'SHBd', 'AATS.80', 'x_fine_emb_MFXL146', 'x_fine_emb_MFXL500', 'VR1_Dzs', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL138', 'x_fine_emb_MFXL704', 'RDF40s', 'x_fine_emb_MFXL644', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL239', 'x_fine_emb_MFXL389', 'x_fine_emb_MFXL408']

In [22]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 200)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 200)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.070258 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7684
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 200
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001554 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7679
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 200
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.091238 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7670
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 200
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1443,0.3025,0.3799,0.6313,0.7952,0.7974,0.2233,0.3392,0.4726,0.5165,0.7209,0.6751
DecisionTreeRegressor,0.3291,0.4314,0.5737,0.1591,0.5935,0.6155,0.2943,0.3994,0.5425,0.3629,0.6350,0.5553
RandomForestRegressor,0.1357,0.2886,0.3684,0.6532,0.8089,0.8018,0.2338,0.3371,0.4835,0.4939,0.7041,0.6511
GradientBoostingRegressor,0.1425,0.2868,0.3775,0.6359,0.7982,0.7942,0.2241,0.3472,0.4734,0.5147,0.7185,0.6702
AdaBoostRegressor,0.1382,0.2988,0.3718,0.6468,0.8049,0.7948,0.2241,0.3441,0.4734,0.5148,0.7187,0.6754
XGBRegressor,0.1679,0.3165,0.4097,0.5711,0.7624,0.7590,0.2360,0.3584,0.4858,0.4890,0.7024,0.6457
ExtraTreesRegressor,0.1253,0.2770,0.3539,0.6799,0.8249,0.8170,0.2162,0.3275,0.4649,0.5320,0.7300,0.6758
LinearRegression,0.6663,0.6331,0.8163,-0.7023,0.5021,0.5043,0.7618,0.5995,0.8728,-0.6493,0.4160,0.4574
KNeighborsRegressor,0.1784,0.3157,0.4224,0.5441,0.7537,0.7611,0.2889,0.3654,0.5375,0.3746,0.6321,0.5829
SVR,0.1372,0.2868,0.3704,0.6495,0.8077,0.8212,0.2326,0.3493,0.4823,0.4965,0.7063,0.6779
MLPRegressor,0.7059,0.6388,0.8402,-0.8036,0.4990,0.4867,0.9026,0.6735,0.9500,-0.9541,0.3270,0.2860

In [23]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_200_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_top_200_features_rrck.csv')

In [24]:
#Top 500 features
n = 500  
top_500_indices = importances.argsort()[::-1][:n]  # indices of top n features
top_500_features = feature_names[top_500_indices].tolist()  # convert to list

# Output the list
print("Top", 500, "features:\n")
print(top_500_features)

train_df = pd.concat([train[['ID', 'SMILES', 'Permeability']], X[top_500_features]], axis=1)
test_df = test[train.columns]

Top 500 features:

['x_fine_emb_MFXL209', 'x_fine_emb_MFXL159', 'x_fine_emb_MFXL359', 'x_fine_emb_MFXL647', 'x_fine_emb_MFXL89', 'x_fine_emb_MFXL469', 'x_fine_emb_MFXL358', 'x_fine_emb_MFXL482', 'x_fine_emb_MFXL158', 'x_fine_emb_MFXL440', 'x_fine_emb_MFXL535', 'x_fine_emb_MFXL718', 'x_fine_emb_MFXL401', 'x_fine_emb_MFXL406', 'x_fine_emb_MFXL484', 'x_fine_emb_MFXL678', 'x_fine_emb_MFXL298', 'x_fine_emb_MFXL184', 'x_fine_emb_MFXL723', 'x_fine_emb_MFXL416', 'x_fine_emb_MFXL455', 'x_fine_emb_MFXL217', 'x_fine_emb_MFXL365', 'x_fine_emb_MFXL193', 'x_fine_emb_MFXL270', 'x_fine_emb_MFXL237', 'x_fine_emb_MFXL569', 'x_fine_emb_MFXL748', 'x_fine_emb_MFXL102', 'DPSA-3', 'x_fine_emb_MFXL339', 'GATS.4', 'x_fine_emb_MFXL285', 'x_fine_emb_MFXL719', 'x_fine_emb_MFXL370', 'x_fine_emb_MFXL464', 'x_fine_emb_MFXL510', 'maxsCH3', 'x_fine_emb_MFXL509', 'x_fine_emb_MFXL36', 'x_fine_emb_MFXL111', 'x_fine_emb_MFXL507', 'x_fine_emb_MFXL224', 'x_fine_emb_MFXL590', 'x_fine_emb_MFXL428', 'x_fine_emb_MFXL697', 'x_fine_emb_MFXL87', 'x_fine_emb_MFXL82', 'x_fine_emb_MFXL421', 'AvgIpc', 'x_fine_emb_MFXL434', 'x_fine_emb_MFXL69', 'Ipc', 'x_fine_emb_MFXL418', 'x_fine_emb_MFXL555', 'x_fine_emb_MFXL731', 'VR2_D', 'x_fine_emb_MFXL680', 'x_fine_emb_MFXL399', 'x_fine_emb_MFXL115', 'x_fine_emb_MFXL565', 'x_fine_emb_MFXL501', 'ATSC.64', 'x_fine_emb_MFXL568', 'AATSC7v', 'x_fine_emb_MFXL313', 'x_fine_emb_MFXL448', 'x_fine_emb_MFXL114', 'x_fine_emb_MFXL650', 'x_fine_emb_MFXL274', 'x_fine_emb_MFXL490', 'x_fine_emb_MFXL252', 'ATSC.98', 'x_fine_emb_MFXL415', 'x_fine_emb_MFXL767', 'x_fine_emb_MFXL616', 'x_fine_emb_MFXL2', 'x_fine_emb_MFXL738', 'x_fine_emb_MFXL180', 'x_fine_emb_MFXL715', 'x_fine_emb_MFXL194', 'TDB7s', 'TPSA_y', '3d_rdkit_11', 'x_fine_emb_MFXL136', 'x_fine_emb_MFXL97', 'x_fine_emb_MFXL174', 'x_fine_emb_MFXL620', 'x_fine_emb_MFXL530', 'x_fine_emb_MFXL207', 'x_fine_emb_MFXL430', 'x_fine_emb_MFXL346', 'x_fine_emb_MFXL593', 'x_fine_emb_MFXL211', 'RDF15s', 'SP-6', 'AdjacencyMatrix.6', 'x_fine_emb_MFXL324', 'x_fine_emb_MFXL113', 'x_fine_emb_MFXL645', 'RDF30s', 'x_fine_emb_MFXL118', 'x_fine_emb_MFXL290', 'ATSC.6', 'x_fine_emb_MFXL320', 'x_fine_emb_MFXL41', 'x_fine_emb_MFXL388', 'VR1_Dt', 'AtomTypeEState.271', 'x_fine_emb_MFXL75', 'GATS5e', 'BCUTp-1h', 'SpMax8_Bhs', 'x_fine_emb_MFXL460', 'TDB1i', 'AATSC0i', 'x_fine_emb_MFXL42', 'x_fine_emb_MFXL721', 'maxHBint8', 'MOMI-XY', 'VR2_Dzp', 'AATS.96', 'x_fine_emb_MFXL759', 'x_fine_emb_MFXL479', 'x_fine_emb_MFXL121', 'AATSC4s', 'x_fine_emb_MFXL433', 'x_fine_emb_MFXL732', 'IC1', 'x_fine_emb_MFXL214', 'ATSC.97', 'x_fine_emb_MFXL682', 'x_fine_emb_MFXL764', 'x_fine_emb_MFXL702', 'x_fine_emb_MFXL349', 'x_fine_emb_MFXL677', 'x_fine_emb_MFXL545', 'x_fine_emb_MFXL747', 'x_fine_emb_MFXL327', 'x_fine_emb_MFXL9', 'x_fine_emb_MFXL188', 'x_fine_emb_MFXL24', 'x_fine_emb_MFXL472', 'x_fine_emb_MFXL665', 'x_fine_emb_MFXL733', 'x_fine_emb_MFXL55', 'x_fine_emb_MFXL104', 'x_fine_emb_MFXL622', 'x_fine_emb_MFXL213', 'x_fine_emb_MFXL30', 'x_fine_emb_MFXL751', 'x_fine_emb_MFXL246', 'TDB2i', 'x_fine_emb_MFXL196', 'x_fine_emb_MFXL446', 'count_fp_675', 'x_fine_emb_MFXL684', 'x_fine_emb_MFXL255', 'ATSC.44', 'x_fine_emb_MFXL685', 'x_fine_emb_MFXL363', 'x_fine_emb_MFXL319', 'GraphFP817', 'x_fine_emb_MFXL736', 'x_fine_emb_MFXL392', 'x_fine_emb_MFXL558', 'x_fine_emb_MFXL235', 'x_fine_emb_MFXL683', 'x_fine_emb_MFXL101', 'x_fine_emb_MFXL356', 'x_fine_emb_MFXL189', 'x_fine_emb_MFXL308', 'RPCS', 'x_fine_emb_MFXL562', 'x_fine_emb_MFXL333', 'x_fine_emb_MFXL725', 'x_fine_emb_MFXL582', 'minssNH', 'LOBMIN', '3d_rdkit_10', 'x_fine_emb_MFXL625', 'RDF45s', 'AtomTypeEState.249', 'x_fine_emb_MFXL643', 'x_fine_emb_MFXL724', 'SHBd', 'AATS.80', 'x_fine_emb_MFXL146', 'x_fine_emb_MFXL500', 'VR1_Dzs', 'x_fine_emb_MFXL52', 'x_fine_emb_MFXL138', 'x_fine_emb_MFXL704', 'RDF40s', 'x_fine_emb_MFXL644', 'x_fine_emb_MFXL57', 'x_fine_emb_MFXL612', 'x_fine_emb_MFXL239', 'x_fine_emb_MFXL389', 'x_fine_emb_MFXL408', 'maxHBint10', 'x_fine_emb_MFXL244', 'x_fine_emb_MFXL699', 'x_fine_emb_MFXL574', 'x_fine_emb_MFXL70', 'RDF65m', 'VE3_Dzi', 'TDB10s', 'x_fine_emb_MFXL646', 'x_fine_emb_MFXL700', 'minHBint6', 'x_fine_emb_MFXL641', 'AATSC.34', 'x_fine_emb_MFXL573', 'x_fine_emb_MFXL483', 'x_fine_emb_MFXL588', 'x_fine_emb_MFXL726', 'x_fine_emb_MFXL561', 'x_fine_emb_MFXL713', 'MDEC-33', 'x_fine_emb_MFXL403', 'x_fine_emb_MFXL323', 'ATSC.16', 'x_fine_emb_MFXL716', 'x_fine_emb_MFXL730', 'x_fine_emb_MFXL357', 'ATSC.28', 'x_fine_emb_MFXL532', 'KRFPC3740', 'RDF10s', 'RDF80s', 'minsCH3', 'TDB1e', 'x_fine_emb_MFXL328', 'x_fine_emb_MFXL301', 'x_fine_emb_MFXL44', 'x_fine_emb_MFXL205', 'VR1_DzZ', 'x_fine_emb_MFXL230', 'x_fine_emb_MFXL108', 'TDB3i', 'x_fine_emb_MFXL701', 'x_fine_emb_MFXL21', 'MOMI-XZ', 'TDB5m', 'x_fine_emb_MFXL587', 'x_fine_emb_MFXL499', 'x_fine_emb_MFXL225', 'x_fine_emb_MFXL752', 'VE3_Dze', 'x_fine_emb_MFXL743', 'x_fine_emb_MFXL637', 'x_fine_emb_MFXL436', 'x_fine_emb_MFXL705', 'x_fine_emb_MFXL496', 'x_fine_emb_MFXL467', 'x_fine_emb_MFXL61', 'x_fine_emb_MFXL548', 'x_fine_emb_MFXL271', 'AATS.67', 'x_fine_emb_MFXL498', 'x_fine_emb_MFXL141', 'x_fine_emb_MFXL608', 'x_fine_emb_MFXL321', 'x_fine_emb_MFXL273', 'x_fine_emb_MFXL168', 'x_fine_emb_MFXL4', 'x_fine_emb_MFXL557', 'x_fine_emb_MFXL443', 'x_fine_emb_MFXL173', 'x_fine_emb_MFXL431', 'x_fine_emb_MFXL578', 'x_fine_emb_MFXL494', 'x_fine_emb_MFXL444', 'x_fine_emb_MFXL296', 'x_fine_emb_MFXL387', 'x_fine_emb_MFXL187', 'x_fine_emb_MFXL451', 'x_fine_emb_MFXL149', 'x_fine_emb_MFXL552', 'TDB8e', 'x_fine_emb_MFXL63', 'x_fine_emb_MFXL728', 'x_fine_emb_MFXL40', 'x_fine_emb_MFXL609', 'GraphFP522', 'GATS.7', 'x_fine_emb_MFXL746', 'VR2_Dze', 'Dv', 'XLogP', 'x_fine_emb_MFXL335', 'x_fine_emb_MFXL757', 'x_fine_emb_MFXL132', 'x_fine_emb_MFXL465', 'x_fine_emb_MFXL681', 'TDB8i', 'x_fine_emb_MFXL741', 'ATSC.17', 'x_fine_emb_MFXL651', 'x_fine_emb_MFXL28', 'x_fine_emb_MFXL619', 'x_fine_emb_MFXL23', 'x_fine_emb_MFXL160', 'x_fine_emb_MFXL720', 'x_fine_emb_MFXL722', 'x_fine_emb_MFXL302', 'AATSC.52', 'TDB4i', 'x_fine_emb_MFXL177', 'x_fine_emb_MFXL486', 'x_fine_emb_MFXL606', 'GATS.22', 'BCUTp-1l', 'x_fine_emb_MFXL672', 'SpMax4_Bhs', 'minHBint3', 'x_fine_emb_MFXL654', 'TDB8s', 'x_fine_emb_MFXL679', 'x_fine_emb_MFXL661', 'x_fine_emb_MFXL140', 'x_fine_emb_MFXL729', 'x_fine_emb_MFXL518', 'x_fine_emb_MFXL245', 'x_fine_emb_MFXL91', 'x_fine_emb_MFXL409', 'GATS.82', 'x_fine_emb_MFXL515', 'x_fine_emb_MFXL181', 'x_fine_emb_MFXL676', 'x_fine_emb_MFXL380', 'VE3_Dt', 'TDB10m', 'x_fine_emb_MFXL156', 'ATSC4c', 'x_fine_emb_MFXL618', 'ATSC.20', 'ATSC.80', 'x_fine_emb_MFXL330', 'x_fine_emb_MFXL256', 'x_fine_emb_MFXL272', 'minHCsatu', 'x_fine_emb_MFXL119', 'x_fine_emb_MFXL123', 'GATS.30', 'geomShape', 'x_fine_emb_MFXL76', 'x_fine_emb_MFXL90', 'x_fine_emb_MFXL92', 'x_fine_emb_MFXL414', 'x_fine_emb_MFXL554', 'maxHBint6', 'x_fine_emb_MFXL331', 'x_fine_emb_MFXL176', 'maxdssC', 'x_fine_emb_MFXL675', 'ATSC.35', 'x_fine_emb_MFXL437', 'x_fine_emb_MFXL260', 'x_fine_emb_MFXL167', 'x_fine_emb_MFXL709', 'x_fine_emb_MFXL236', 'x_fine_emb_MFXL58', 'LipoaffinityIndex', 'x_fine_emb_MFXL687', 'x_fine_emb_MFXL658', 'x_fine_emb_MFXL280', 'x_fine_emb_MFXL154', 'x_fine_emb_MFXL649', 'x_fine_emb_MFXL630', 'x_fine_emb_MFXL604', 'x_fine_emb_MFXL754', 'ATSC.87', 'x_fine_emb_MFXL538', 'TDB7i', 'LOBMAX', 'geomDiameter', 'PPSA-3', 'x_fine_emb_MFXL20', 'x_fine_emb_MFXL598', 'x_fine_emb_MFXL739', 'ATSC.11', 'x_fine_emb_MFXL407', 'x_fine_emb_MFXL144', 'x_fine_emb_MFXL253', 'x_fine_emb_MFXL305', 'ATSC3s', 'x_fine_emb_MFXL614', 'x_fine_emb_MFXL310', 'x_fine_emb_MFXL267', 'x_fine_emb_MFXL717', 'x_fine_emb_MFXL178', 'x_fine_emb_MFXL334', 'x_fine_emb_MFXL210', 'x_fine_emb_MFXL734', 'x_fine_emb_MFXL226', 'MolecularDistanceEdge.4', 'x_fine_emb_MFXL311', 'x_fine_emb_MFXL504', 'x_fine_emb_MFXL760', 'minHBint5', 'x_fine_emb_MFXL116', 'x_fine_emb_MFXL521', 'TDB3s', 'x_fine_emb_MFXL376', 'x_fine_emb_MFXL288', 'x_fine_emb_MFXL452', 'APC2D9_C_O', 'x_fine_emb_MFXL402', 'MolecularDistanceEdge.7', 'AATS7i', 'VE3_Dzp', 'x_fine_emb_MFXL6', 'x_fine_emb_MFXL439', 'maxHssNH', 'x_fine_emb_MFXL382', 'RDF25s', 'x_fine_emb_MFXL547', 'x_fine_emb_MFXL708', 'x_fine_emb_MFXL398', 'x_fine_emb_MFXL744', 'L3m', 'x_fine_emb_MFXL756', 'RDF60p', 'x_fine_emb_MFXL534', 'RDF20m', 'RDF55p', 'x_fine_emb_MFXL526', 'SdssC', 'x_fine_emb_MFXL45', 'x_fine_emb_MFXL78', 'x_fine_emb_MFXL506', 'x_fine_emb_MFXL471', 'x_fine_emb_MFXL698', 'x_fine_emb_MFXL353', 'x_fine_emb_MFXL727', 'MDEC-11', 'AATS5s', 'x_fine_emb_MFXL126', 'L2s', 'x_fine_emb_MFXL652', 'x_fine_emb_MFXL247', 'x_fine_emb_MFXL277', 'x_fine_emb_MFXL216', 'x_fine_emb_MFXL199', 'gmin', 'GATS.20', 'x_fine_emb_MFXL549', 'VE3_D', 'x_fine_emb_MFXL13', 'count_fp_1454', 'x_fine_emb_MFXL341', 'x_fine_emb_MFXL262', 'x_fine_emb_MFXL591', 'x_fine_emb_MFXL740', 'KRFPC3742', 'x_fine_emb_MFXL427', 'ATSC5c', 'x_fine_emb_MFXL438', 'AATSC5m', 'De', 'x_fine_emb_MFXL533', 'AtomTypeEState.245', 'x_fine_emb_MFXL594', 'x_fine_emb_MFXL72', 'PubchemFP21', 'x_fine_emb_MFXL556', 'FP549', 'x_fine_emb_MFXL360', 'ATSC.32', 'x_fine_emb_MFXL663', 'x_fine_emb_MFXL65', 'x_fine_emb_MFXL203', 'x_fine_emb_MFXL559', 'TDB4p', 'ATSC.25', 'x_fine_emb_MFXL340', 'x_fine_emb_MFXL351', 'x_fine_emb_MFXL639', 'x_fine_emb_MFXL480', 'x_fine_emb_MFXL299', 'RDF70v', 'x_fine_emb_MFXL631', 'x_fine_emb_MFXL29', 'TDB3m', 'x_fine_emb_MFXL283', 'x_fine_emb_MFXL212', 'ATSC.95', 'TDB9e', 'x_fine_emb_MFXL476', 'x_fine_emb_MFXL564', 'x_fine_emb_MFXL163', 'APC2D5_C_N', 'RDF55s', 'x_fine_emb_MFXL642', 'x_fine_emb_MFXL375', 'minHBd', 'minsssN', 'x_fine_emb_MFXL615']

In [25]:
X_train = train_df.drop(['ID','SMILES','Permeability'],axis=1)
y_train = train_df['Permeability']
print("X_train shape: ",X_train.shape)
print("y_train shape: ",y_train.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
X_test = test_df[X_train.columns]
y_test = test_df['Permeability']
print("X_test shape: ",X_test.shape)
print("y_test shape: ",y_test.shape)
print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train = pd.DataFrame(X_train_scaled, columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(X_test_scaled, columns=X_test.columns, index=X_test.index)
models = [
    lgb.LGBMRegressor(objective='regression',metric='rmse',boosting_type='gbdt',num_leaves=31,learning_rate=0.05,random_state=101),
    DecisionTreeRegressor(random_state=101),
    RandomForestRegressor(n_jobs=-1, random_state=101),
    GradientBoostingRegressor(random_state=101),
    AdaBoostRegressor(random_state=101),
    xgb.XGBRegressor(random_state=101),
    ExtraTreesRegressor(n_jobs=-1, n_estimators=100, random_state=101),
    LinearRegression(), 
    KNeighborsRegressor(n_neighbors=3),
    SVR(),  
    MLPRegressor(random_state=101)
]
result_df, prediction_df = train_and_test_predict(models, X_train,y_train, X_test,  y_test)
result_df

X_train shape:  (140, 500)
y_train shape:  (140,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
X_test shape:  (35, 500)
y_test shape:  (35,)
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.079920 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18998
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 500
[LightGBM] [Info] Start training from score -5.658237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.073022 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18986
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 500
[LightGBM] [Info] Start training from score -5.688080
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.141866 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 18961
[LightGBM] [Info] Number of data points in the train set: 112, number of used features: 500
[LightGBM] [Info] Start training from score -5.693594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

,Train MSE (5 fold cv),Train MAE (5 fold cv),Train RMSE (5 fold cv),Train R2 (5 fold cv),Train PCC (5 fold cv),Train SCC (5 fold cv),Test MSE,Test MAE,Test RMSE,Test R2,Test Pearson Correlation,Test Spearman Correlation
LGBMRegressor,0.1548,0.3167,0.3935,0.6044,0.7786,0.7746,0.2333,0.3503,0.4830,0.4949,0.7053,0.6654
DecisionTreeRegressor,0.3773,0.4567,0.6143,0.0359,0.5394,0.5592,0.3268,0.4255,0.5716,0.2926,0.5957,0.5476
RandomForestRegressor,0.1455,0.3015,0.3815,0.6282,0.7934,0.7900,0.2373,0.3432,0.4871,0.4863,0.6986,0.6490
GradientBoostingRegressor,0.1544,0.2996,0.3930,0.6054,0.7793,0.7745,0.2149,0.3359,0.4636,0.5347,0.7325,0.6896
AdaBoostRegressor,0.1474,0.3013,0.3839,0.6235,0.7914,0.7931,0.2289,0.3494,0.4785,0.5044,0.7115,0.6667
XGBRegressor,0.1799,0.3184,0.4241,0.5405,0.7430,0.7377,0.2418,0.3565,0.4918,0.4764,0.6918,0.6504
ExtraTreesRegressor,0.1321,0.2879,0.3635,0.6624,0.8155,0.8102,0.2170,0.3344,0.4658,0.5302,0.7291,0.6690
LinearRegression,0.3038,0.4353,0.5512,0.2237,0.6537,0.6648,0.5839,0.5170,0.7641,-0.2641,0.4396,0.4571
KNeighborsRegressor,0.1817,0.3253,0.4263,0.5357,0.7429,0.7577,0.2990,0.3764,0.5468,0.3527,0.6175,0.5612
SVR,0.1442,0.2970,0.3798,0.6315,0.7967,0.8101,0.2544,0.3666,0.5044,0.4493,0.6767,0.6329
MLPRegressor,0.6906,0.6396,0.8310,-0.7644,0.4924,0.4684,0.9368,0.7466,0.9679,-1.0283,0.1108,0.1052

In [26]:
result_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/combined_top_500_features_rrck.csv')
prediction_df.to_csv('/home/users/akshay/PCPpred/RRCK/results/combined_features/prediction_data_combined_top_500_features_rrck.csv')