In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/CycPeptMPDB_Peptide_Assay_RRCK (1).csv')
df.shape

(186, 247)

In [3]:
last_id = df['ID'].max()
print('last_id: ', last_id)

last_id:  5668

In [4]:
#Step 1: Removing unreliable datapoints (datapoints with Permeability value <= -10) and selecting the required Columns
df = df[df['RRCK'] > -10]
selected_columns = ['ID', 'SMILES', 'RRCK', 'Sequence', 'MolWt']
new_df = df[selected_columns]
new_df.shape

(185, 5)

In [5]:
new_df.columns = ['ID', 'SMILES', 'Permeability', 'Sequence', 'MolWt']

In [6]:
new_df.head(10)

,ID,SMILES,Permeability,Sequence,MolWt
0,22,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.96,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
1,23,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.74,"['L', 'dL', 'L', 'L', 'dP', 'Y']",712.933
2,24,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-6.30,"['dL', 'L', 'L', 'L', 'dP', 'Y']",712.933
3,25,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.31,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']",755.014
4,26,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...,-5.39,"['Me_dL', 'meL', 'L', 'meL', 'dP', 'meY']",769.041
5,27,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N(C)[C@...,-5.46,"['meL', 'Me_dL', 'meL', 'meL', 'dP', 'meY']",783.068
6,28,CC(C)C[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N2CCC[...,-5.21,"['Me_dL', 'meL', 'meL', 'meL', 'dP', 'meY']",783.068
7,29,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...,-5.72,"['S', 'Me_dL', 'meL', 'L', 'dP', 'meY']",728.932
8,30,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.80,"['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']",728.932
9,31,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.12,"['L', 'Me_dL', 'meL', 'S', 'dP', 'meY']",728.932

In [7]:
#Step 2: curating duplicate dapaoints based on SMILES representation
duplicates = new_df[new_df.duplicated(subset='SMILES', keep=False)]
non_duplicates = new_df[~new_df.duplicated(subset='SMILES', keep=False)]
print("DataFrame with duplicates:")
print(duplicates)
print("\nDataFrame without duplicates:")
print(non_duplicates)
duplicates.to_csv('/home/users/akshay/PCPpred/RRCK/data/duplicates_RRCK.csv', index=False)

DataFrame with duplicates:
       ID                                             SMILES  Permeability  \
0      22  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...         -5.96
1      23  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...         -5.74
3      25  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.31
8      30  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.80
10     32  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.31
11     33  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.81
14     36  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.26
21     43  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -6.74
39    980  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.31
40    981  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...         -5.96
68   1862  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...         -5.25
122  2326  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.19
124  2328  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -4.88
126  2330  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...         -5.63
142  2346  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...         -5.87
152  2356  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...         -5.87

                                              Sequence     MolWt
0    ['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...  1202.635
1                     ['L', 'dL', 'L', 'L', 'dP', 'Y']   712.933
3              ['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']   755.014
8              ['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']   728.932
10             ['L', 'dP', 'meY', 'L', 'Me_dL', 'meL']   755.014
11             ['L', 'dP', 'meY', 'L', 'Me_dL', 'meS']   728.932
14             ['L', 'dP', 'meY', 'L', 'Me_dL', 'meA']   712.933
21          ['L', 'dP', 'meY', 'L', 'Me_dL', 'Me_Cha']   795.079
39             ['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']   755.014
40   ['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...  1202.635
68   ['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...  1202.635
122            ['L', 'Me_dL', 'meA', 'L', 'dP', 'meY']   712.933
124            ['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']   755.014
126         ['L', 'Me_dL', 'Me_Cha', 'L', 'dP', 'meY']   795.079
142                   ['L', 'dL', 'L', 'L', 'dP', 'Y']   712.933
152  ['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...  1202.635

DataFrame without duplicates:
       ID                                             SMILES  Permeability  \
2      24  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...         -6.30
4      26  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...         -5.39
5      27  CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N(C)[C@...         -5.46
6      28  CC(C)C[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N2CCC[...         -5.21
7      29  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...         -5.72
..    ...                                                ...           ...
181  5664  CCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@...         -5.64
182  5665  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46
183  5666  CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...         -6.46
184  5667  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46
185  5668  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46

                                              Sequence     MolWt
2                     ['dL', 'L', 'L', 'L', 'dP', 'Y']   712.933
4            ['Me_dL', 'meL', 'L', 'meL', 'dP', 'meY']   769.041
5          ['meL', 'Me_dL', 'meL', 'meL', 'dP', 'meY']   783.068
6          ['Me_dL', 'meL', 'meL', 'meL', 'dP', 'meY']   783.068
7              ['S', 'Me_dL', 'meL', 'L', 'dP', 'meY']   728.932
..                                                 ...       ...
181  ['F', 'Me_Nle', 'P', 'meF', 'Nle', 'Me_Nle', '...   947.257
182  ['F', 'Me_Nle', 'Nle', 'Me_Nle', 'Me_Nle', 'Me...  1056.470
183  ['Me_dF', 'Nle', 'Me_Nle', 'Nle', 'Me_Nle', 'N...  1042.443
184  ['Me_dF', 'Nle', 'Me_Nle', 'Nle', 'Me_Nle', 'N...  1076.460
185  ['Me_dF', 'T', 'Me_Nle', 'Nle', 'Me_Nle', 'Nle...  1064.405

[169 rows x 5 columns]

In [8]:
duplicates = new_df[new_df.duplicated(subset='SMILES', keep=False)]

non_duplicates = new_df[~new_df.duplicated(subset='SMILES', keep=False)]
#Permeability and MolWt of duplicate SMILES were averaged, and Most abundandant sequence was chosen
grouped_duplicates = duplicates.groupby('SMILES').agg(
    Permeability=('Permeability', 'mean'),   
    MolWt=('MolWt', 'mean'),   
    Sequence=('Sequence', lambda x: x.mode()[0]), 
).reset_index()

#Unique ID's were given to these curated datapoints, where ID's start from the last documented id in CycPeptMPDB_Peptide_Assay_PAMPA (5)
grouped_duplicates['ID'] = range(last_id + 1, last_id + 1 + len(grouped_duplicates))

grouped_duplicates = grouped_duplicates[['ID', 'SMILES', 'Permeability', 'Sequence', 'MolWt']]

non_duplicates_ordered = non_duplicates[['ID', 'SMILES', 'Permeability', 'Sequence', 'MolWt']]
merged_df = pd.concat([non_duplicates_ordered, grouped_duplicates], ignore_index=True)

print("DataFrame with processed duplicates:")
print(grouped_duplicates)

print("\nDataFrame without duplicates:")
print(non_duplicates)

print("Merged DataFrame:")
print(merged_df)

grouped_duplicates.to_csv('/home/users/akshay/PCPpred/RRCK/data/grouped_duplicates_RRCK.csv', index=False)
non_duplicates.to_csv('/home/users/akshay/PCPpred/RRCK/data/non_duplicates_RRCK.csv', index=False)
merged_df.to_csv('/home/users/akshay/PCPpred/RRCK/data/CycPeptMPDB_data_Main_RRCK.csv', index=False)

DataFrame with processed duplicates:
     ID                                             SMILES  Permeability  \
0  5669  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...       -5.7600
1  5670  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.2250
2  5671  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.2025
3  5672  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -6.1850
4  5673  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.8050
5  5674  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...       -5.8050

                                            Sequence     MolWt
0  ['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...  1202.635
1            ['L', 'Me_dL', 'meA', 'L', 'dP', 'meY']   712.933
2            ['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']   755.014
3         ['L', 'Me_dL', 'Me_Cha', 'L', 'dP', 'meY']   795.079
4            ['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']   728.932
5                   ['L', 'dL', 'L', 'L', 'dP', 'Y']   712.933

DataFrame without duplicates:
       ID                                             SMILES  Permeability  \
2      24  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...         -6.30
4      26  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...         -5.39
5      27  CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N(C)[C@...         -5.46
6      28  CC(C)C[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N2CCC[...         -5.21
7      29  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...         -5.72
..    ...                                                ...           ...
181  5664  CCCC[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=O)[C@@...         -5.64
182  5665  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46
183  5666  CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...         -6.46
184  5667  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46
185  5668  CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...         -6.46

                                              Sequence     MolWt
2                     ['dL', 'L', 'L', 'L', 'dP', 'Y']   712.933
4            ['Me_dL', 'meL', 'L', 'meL', 'dP', 'meY']   769.041
5          ['meL', 'Me_dL', 'meL', 'meL', 'dP', 'meY']   783.068
6          ['Me_dL', 'meL', 'meL', 'meL', 'dP', 'meY']   783.068
7              ['S', 'Me_dL', 'meL', 'L', 'dP', 'meY']   728.932
..                                                 ...       ...
181  ['F', 'Me_Nle', 'P', 'meF', 'Nle', 'Me_Nle', '...   947.257
182  ['F', 'Me_Nle', 'Nle', 'Me_Nle', 'Me_Nle', 'Me...  1056.470
183  ['Me_dF', 'Nle', 'Me_Nle', 'Nle', 'Me_Nle', 'N...  1042.443
184  ['Me_dF', 'Nle', 'Me_Nle', 'Nle', 'Me_Nle', 'N...  1076.460
185  ['Me_dF', 'T', 'Me_Nle', 'Nle', 'Me_Nle', 'Nle...  1064.405

[169 rows x 5 columns]
Merged DataFrame:
       ID                                             SMILES  Permeability  \
0      24  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...       -6.3000
1      26  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...       -5.3900
2      27  CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N(C)[C@...       -5.4600
3      28  CC(C)C[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N2CCC[...       -5.2100
4      29  CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...       -5.7200
..    ...                                                ...           ...
170  5670  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.2250
171  5671  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.2025
172  5672  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -6.1850
173  5673  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...       -5.8050
174  5674  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...       -5.8050

                                        Sequence    MolWt
0               ['dL', 'L', 'L', 'L', 'dP', 'Y']  712.933
1      ['Me_dL', 'meL', 'L', 'meL', 'dP', 'meY']  769.041
2    ['meL', 'Me_dL', 'meL', 'meL', 'dP', 'meY']  783.068
3    ['Me_dL', 'meL', 'meL', 'meL', 'dP', 'meY']  783.068
4        ['S', 'Me_dL', 'meL', 'L', 'dP', 'meY']  728.932
..                                           ...      ...
170      ['L', 'Me_dL', 'meA', 'L', 'dP', 'meY']  712.933
171      ['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']  755.014
172   ['L', 'Me_dL', 'Me_Cha', 'L', 'dP', 'meY']  795.079
173      ['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']  728.932
174             ['L', 'dL', 'L', 'L', 'dP', 'Y']  712.933

[175 rows x 5 columns]

In [9]:
#Step 3: Splitting the Main dataset into Train and Test in ration 0.8:0.2
df = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/CycPeptMPDB_data_Main_RRCK.csv')
df

,ID,SMILES,Permeability,Sequence,MolWt
0,24,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-6.3000,"['dL', 'L', 'L', 'L', 'dP', 'Y']",712.933
1,26,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...,-5.3900,"['Me_dL', 'meL', 'L', 'meL', 'dP', 'meY']",769.041
2,27,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N(C)[C@...,-5.4600,"['meL', 'Me_dL', 'meL', 'meL', 'dP', 'meY']",783.068
3,28,CC(C)C[C@H]1C(=O)N(C)[C@@H](CC(C)C)C(=O)N2CCC[...,-5.2100,"['Me_dL', 'meL', 'meL', 'meL', 'dP', 'meY']",783.068
4,29,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H...,-5.7200,"['S', 'Me_dL', 'meL', 'L', 'dP', 'meY']",728.932
...,...,...,...,...,...
170,5670,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.2250,"['L', 'Me_dL', 'meA', 'L', 'dP', 'meY']",712.933
171,5671,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.2025,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meY']",755.014
172,5672,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.1850,"['L', 'Me_dL', 'Me_Cha', 'L', 'dP', 'meY']",795.079
173,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.8050,"['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']",728.932
174,5674,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.8050,"['L', 'dL', 'L', 'L', 'dP', 'Y']",712.933

In [10]:
#Main dataset is sorted based on Molecular weight in descending order
df_main = df.sort_values(by='MolWt', ascending= False)
df_main

,ID,SMILES,Permeability,Sequence,MolWt
132,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.34,"['T', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1218.634
137,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1216.662
138,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1214.646
169,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
139,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,"['Me_Bmt(E)', 'Abu', 'Sar', 'meL', 'V', 'meL',...",1202.635
...,...,...,...,...,...
90,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.75,"['L', 'Me_dL', 'meA', 'L', 'dP', 'meA']",620.836
115,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,"['L', 'dA', 'A', 'L', 'dP', 'F']",612.772
89,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,"['L', 'Me_dNva', 'meA', 'L', 'dP', 'meA']",606.809
88,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,"['L', 'Me_dAbu', 'meA', 'L', 'dP', 'meA']",592.782
87,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,"['L', 'Me_dA', 'meA', 'L', 'dP', 'meA']",578.755

In [11]:
df_main['MolWt']

132    1218.634
137    1216.662
138    1214.646
169    1202.635
139    1202.635
         ...
90      620.836
115     612.772
89      606.809
88      592.782
87      578.755
Name: MolWt, Length: 175, dtype: float64

In [12]:
#Every fifth datapoint is allocated to test set and remaining datapoints to Train set
test_mask = np.arange(len(df_main)) % 5 == 0
test_df = df_main[test_mask]
test_df.shape

(35, 5)

In [13]:
train_df = df_main[~test_mask]
train_df.shape

(140, 5)

In [14]:
print(train_df["Permeability"].max())
print(train_df["Permeability"].min())
print(train_df.shape)

-4.51
-7.0
(140, 5)

In [15]:
print(test_df["Permeability"].max())
print(test_df["Permeability"].min())
print(test_df.shape)

-4.49
-7.0
(35, 5)

In [16]:
test_df.to_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv",index=False)
train_df.to_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv",index=False)

In [17]:
train_df

,ID,SMILES,Permeability,Sequence,MolWt
137,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1216.662
138,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1214.646
169,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
139,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,"['Me_Bmt(E)', 'Abu', 'Sar', 'meL', 'V', 'meL',...",1202.635
133,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,"['A', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1188.608
...,...,...,...,...,...
116,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,"['L', 'dAbu', 'A', 'L', 'dP', 'F']",626.799
115,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,"['L', 'dA', 'A', 'L', 'dP', 'F']",612.772
89,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,"['L', 'Me_dNva', 'meA', 'L', 'dP', 'meA']",606.809
88,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,"['L', 'Me_dAbu', 'meA', 'L', 'dP', 'meA']",592.782
87,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,"['L', 'Me_dA', 'meA', 'L', 'dP', 'meA']",578.755

In [18]:
test_df

,ID,SMILES,Permeability,Sequence,MolWt
132,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,"['T', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1218.634
136,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
78,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,"['Me_dA', 'Me_Nva', 'Me_dAbu', 'Me_Nle', 'Me_d...",1095.438
77,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,"['Me_dA', 'Me_Nva', 'Me_dAbu', 'meA', 'Me_dAbu...",1039.330
74,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,"['Me_Nva', 'Me_dAbu', 'meA', 'Me_dNle', 'Me_dA...",996.305
63,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,"['Me_dA', 'meA', 'Me_dL', 'Me_dL', 'meL', 'Me_...",953.280
71,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,"['Me_dAbu', 'Me_Nva', 'Me_dNva', 'Me_dNva', 'M...",939.253
55,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,"['Ala(tBu)', 'Tza', 'dP', 'Mono48', 'Ser(Bn)',...",914.089
162,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,"['F', 'Me_Nle', 'P', 'Me_Nle', 'Nle', 'Nle', '...",899.213
49,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,"['Ala(tBu)', 'Tza', 'dP', 'PhPr_Gly', 'Nva(Ph)...",876.137
147,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,"['I', 'L', 'Me_dF', 'P', 'Sar', 'F', 'meF']",864.101
149,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,"['A', 'L', 'Me_dF', 'P', 'Sar', 'F', 'meY']",838.019
113,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,"['L', 'Me_dNva', 'Me_Cha', 'Cha', 'dP', 'meY']",821.117
112,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,"['L', 'Me_dAbu', 'Me_Cha', 'Cha', 'dP', 'meY']",807.090
158,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,"['dF', 'Me_Nle', 'Nle', 'Me_Nle', 'Nle', 'Mono...",802.096
23,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,"['P', 'Sta', 'meL', 'meL', 'Sta', 'meL']",793.104
131,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,"['L', 'dL', 'Cha', 'Cha', 'dP', 'Y']",793.063
28,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,"['P', 'Mono29', 'meL', 'meL', 'Sta(3R,4R)', 'm...",789.116
13,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,"['L', 'dP', 'meY', 'L', 'Me_dL', 'Me_Lys(Me)']",784.056
20,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,"['Mono14', 'Tle', 'meF', 'P', 'I', 'P']",778.033
12,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,"['L', 'dP', 'meY', 'L', 'Me_dL', 'meK']",770.029
159,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,"['F', 'Nle', 'P', 'Nle', 'Nle', 'Mono100']",757.999
128,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,"['L', 'dL', 'Cha', 'L', 'dP', 'Y']",752.998
32,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,"['L', 'iBu_Gly', 'meL', 'L', 'dP', 'meY']",740.987
43,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,"['L', 'Me_dL', 'meL', 'L', 'dP', 'Mono34']",735.024
173,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,"['L', 'Me_dL', 'meS', 'L', 'dP', 'meY']",728.932
37,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,"['L', 'Me_dL', 'iBu_Gly', 'L', 'dP', 'Bn(4-OH)...",726.960
39,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,"['iBu_Gly', 'iBu_Gly', 'iBu_Gly', 'iBu_Gly', '...",712.933
80,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,"['dP', 'dL', 'dL', 'dL', 'dL', 'Y']",712.933
86,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,"['dP', 'dL', 'L', 'L', 'dL', 'Y']",712.933
145,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,"['L', 'dP', 'meL', 'L', 'dP', 'meF']",708.945
119,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,"['L', 'dL', 'L', 'L', 'dP', 'F']",696.934
94,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,"['L', 'Me_dAbu', 'Me_Abu', 'L', 'dP', 'meF']",682.907
93,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,"['L', 'Me_dL', 'meL', 'L', 'dP', 'meA']",662.917
90,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,"['L', 'Me_dL', 'meA', 'L', 'dP', 'meA']",620.836

In [19]:
import pandas as pd

df = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')

with open('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 'w') as f:
    for _, row in df.iterrows():
        smiles = row['SMILES']
        id = row['ID']
        f.write(f"{smiles} {id}\n")
print("train.smi file has been created successfully.")

train.smi file has been created successfully.

In [20]:
df = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')

with open('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 'w') as f:
    for _, row in df.iterrows():
        smiles = row['SMILES']
        id = row['ID']
        f.write(f"{smiles} {id}\n")
print("test.smi file has been created successfully.")

test.smi file has been created successfully.