In [1]:
#Monomeric features
import pandas as pd
import numpy as np
import ast

In [2]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1216.662
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1214.646
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,"['Me_Bmt(E)', 'Abu', 'Sar', 'meL', 'V', 'meL',...",1202.635
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,"['A', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1188.608
...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,"['L', 'dAbu', 'A', 'L', 'dP', 'F']",626.799
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,"['L', 'dA', 'A', 'L', 'dP', 'F']",612.772
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,"['L', 'Me_dNva', 'meA', 'L', 'dP', 'meA']",606.809
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,"['L', 'Me_dAbu', 'meA', 'L', 'dP', 'meA']",592.782
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,"['L', 'Me_dA', 'meA', 'L', 'dP', 'meA']",578.755

In [3]:
df_train = df_train[['ID','SMILES','Sequence','Permeability']]
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)

In [4]:
symbol_list = []

with open('/home/users/akshay/PCPpred/RRCK/data/monomer_list.txt', 'r') as file:
    for line in file:
        symbol_list.append(line.strip())
print(symbol_list)

['A', 'dA', 'meA', 'Me_dA', 'Ala(tBu)', 'Ala(indol-2-yl)', 'dAla(indol-2-yl)', 'Me_Ala(indol-2-yl)', 'Ala(5-Tet)', 'Abu', 'dAbu', 'Me_Abu', 'Me_dAbu', 'Me_Abu(morpholino)', '2Abz', 'Aib', 'Aoc(2)', '5-Ava', 'Bal', 'Me_Bal', 'HOCOCH2_Bal', 'Cys(EtO2H)_NH2', 'Cha', 'dCha', 'Me_Cha', 'D', 'meD', 'Asp_piperidide', 'Asp(OMe)', 'Asp(Ph(2-NH2))', 'dAsp(pyrrol-1-yl)', 'E', 'Glu_NH2', 'Glu(3R-Me)', 'Glu(OMe)', 'dGlu(OMe)', 'F', 'dF', 'meF', 'Me_dF', 'Phe(4-F)', 'dPhe(4-F)', 'Phe(4-CF3)', 'Phe(4-NO2)', 'Phe(CHF2)', 'dPhe(3,4-diF)', 'Et_Phe', 'H2NEt_Phe', 'Me_Phe(3-Cl)', 'Me_Phe(4-Cl)', 'Me_Phe(a,b-dehydro)', 'G', 'Bn_Gly', 'Bn(4-Cl)_Gly', 'Bn(4-OH)_Gly', 'Bu_Gly', 'iBu_Gly', 'Et_Gly', 'EtOEt_Gly', 'HOCOCH2_Gly_ol', 'MeOEt_Gly', 'NH2Bu_Gly', 'Pr_Gly', 'PhEt_Gly', 'PhPr_Gly', 'cHexCH2_Gly', 'isoamyl_Gly', 'pentyl_Gly', '3-pyridylethyl_Gly', '2-pyridylmethyl_Gly', 'd(N->O)Gly(allyl)', 'GABA', 'H', 'Hph', 'Me_Hph', 'bHph', 'Hph(2-Cl)', 'Hph(3-Cl)', 'Hph(4-Cl)', 'Hse(Et)', 'dHyp', 'Hyp(Et)', 'I', 'dI', 'meI', 'Me_dI', '(N->O)xiIle', 'd(N->O)aIle', 'K', 'dK', 'meK', 'Me_dK', 'Lys(Ac)', 'Lys(Cbz)', 'Lys(iPr)', 'Lys(Me)', 'Me_Lys(Me)', 'Lys(Me2)', 'Lys(Tfa)', 'L', 'dL', 'meL', 'Me_dL', 'aMeLeu', 'dLeu(3R-OH)', '(N->O)Leu', 'd(N->O)Leu', 'M', 'meM', 'Met(O2)', 'N', 'dN', 'meN', 'dAsn(Me2)', 'Nal', '1-Nal', 'd1-Nal', 'Nle', 'Me_Nle', 'Me_dNle', 'Nle(CHF2)', 'Nle(OH)', 'Nva', 'dNva', 'Me_Nva', 'Me_dNva', 'Nva(Ph)', 'Orn', 'P', 'dP', '3Pal', '4Pal', 'Phg', 'Pip', 'dPip', 'Pye', 'dPye', 'Q', 'meQ', 'Gln(Me)', 'Gln(Me2)', 'dGln(Me2)', 'Gln(Mes)', 'R', 'dR', 'Arg(Me,Me)', 'S', 'dS', 'meS', 'Ser(Ac)', 'Ser(Bn)', 'Ser(EtNMe2)', 'Ser(EtOH)', 'Ser(isoamyl)', 'Ser(Me)', 'dSer(Me)', 'Ser(Ph(2-Cl))', 'Ser(Ph(3-Cl))', 'Ser(Pr)', 'Ser(tBu)', 'Me_Ser(isoamyl)', 'Me_Ser(Pr)', 'Sar', 'Sta', 'Sta(3R,4R)', 'T', 'dT', 'meT', 'Me_Bmt(E)', 'Tle', 'Tza', 'Me_Tza', 'V', 'dV', 'meV', 'Me_dV', '(N->O)Val', 'd(N->O)Val', '(N->O)Val(3-OH)', 'W', 'meW', 'Me_dW', 'Trp(5-Br)', 'Trp(6-Br)', 'Trp(7-Br)', 'Y', 'dY', 'meY', 'Me_dY', 'Tyr(3-F)', 'Tyr(CHF2)', 'Tyr(Me)', 'Me_Tyr(Me)', 'dTyr(bR-OMe)', '(N->O)Tyr', 'Mono1', 'Mono2', 'Mono3', 'Mono4', 'Mono5', 'Mono6', 'Bal(3-Me)', 'Bal(d3-CF3)', 'Mono9', 'Mono10', 'Mono11', 'Mono12', 'Mono13', 'Mono14', 'Mono15', 'Mono16', 'Mono17', 'Mono18', 'Mono19', 'Mono20', 'Mono23', 'Mono24', 'Mono25', 'Mono26', 'Mono27', 'Mono28', 'Mono29', 'Mono30', 'Mono31', 'Mono32', 'Mono33', 'Mono34', 'Mono35', 'Mono36', 'Mono37', 'Mono38', 'Mono39', 'Mono40', 'Mono41', 'Mono42', 'Mono43', 'Mono44', 'Mono45', 'Mono46', 'Mono47', 'Mono48', 'Mono49', 'Mono50', 'Mono51', 'Mono52', 'Mono53', 'Mono54', 'Mono55', 'Mono56', 'Mono57', 'Mono58', 'Mono59', 'Mono60', 'Mono61', 'Mono62', 'Mono63', 'Mono64', 'Mono65', 'Mono66', 'Mono67', 'Mono68', 'Mono69', 'Mono70', 'Mono71', 'Mono72', 'Mono73', 'Mono74', 'Mono75', 'Mono76', 'Mono77', 'Mono78', 'Mono79', 'Mono80', 'Mono81', 'Mono82', 'Mono83', 'Mono84', 'Mono85', 'Mono86', 'Mono87', 'Mono88', 'Mono89', 'Mono90', 'Mono91', 'Mono92', 'Mono93', 'Mono94', 'Mono95', 'Mono96', 'Mono97', 'Mono98', 'Mono99', 'Mono100', 'Mono101', 'Mono102', 'Mono103', 'Mono104', 'Mono105', 'Mono106', 'Mono107', 'Mono108', 'Mono109', 'Mono110', 'Mono111', 'Mono112', 'ac-', 'deca-', 'glyco-', 'medl-', '-pip', 'Mono21-', 'Mono22-', 'dW', 'Ala(O->S)', 'dAla(O->S)', 'Phe(O->S)', 'Ile(O->S)', 'Lys(O->S)', 'Leu(O->S)', 'dLeu(O->S)', 'Pro(O->S)', 'dPro(O->S)', 'Thr(O->S)', 'dTrp(O->S)', 'Tyr(O->S)', 'Ac3c', 'Abu(5-Tet)', 'Gly(allyl)', '-pyrro', 'Aze', 'Bal(d3-Me)', 'Me_Bal(d3-Me)', 'Bal(d3-EtPh)', 'meH', 'Phe(3-Cl)', 'Phe(3-F)', 'Phe(4-Cl)', 'Mono113', 'Ser(tBuOH)', 'Val(3-OH)', 'Mono114', 'Ac5c', 'Hph(4-CF3,3,5-diF)', 'Hph(4-Me)', 'Phe(3,5-diCl)', 'Hph(4-CF3,3-Cl)', 'Me_Phe(4-Me)', 'Hph(4-tBu)', 'Hph(3,4-diCl)', 'Hch', 'Phe(3-Cl,5-F)', 'Me_Gly(cPent)', 'Phe(3-CF3)', 'Et_Phe(4-Me)', 'Hph(4-CF3)', '-nme2', 'Mono115', 'Chg', 'Me_Chg', 'Et_Leu', 'Me_Ser(Me)', 'Me_Hse(Me)', 'Gly(cPr)', 'Me_Gly(cPr)', 'Gly(cBu)', 'Me_Gly(cBu)', 'Gly(cPent)', 'Ala(cPr)', 'Ala(cBu)', 'Ala(cPent)', 'Me_Nva(F2)', '-mor', '-aze', 'Mono116', 'Mono117', 'Mono118', 'Mono119', 'Mono120', 'Mono121', 'Mono122', 'Mono123', 'Mono124', 'Mono125', 'Mono126', 'Mono127']

In [5]:
def calculate_monomer_composition(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [6]:
df_train_mc = calculate_monomer_composition(df_train, symbol_list)
df_train_mc.shape

(140, 388)

In [7]:
df_train_mc.to_csv("/home/users/akshay/PCPpred/RRCK/features/Monomeric/Train_mon_comp_RRCK.csv", index=False)

In [8]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')

df_test = df_test[['ID','SMILES','Sequence','Permeability']]
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)

df_test_mc = calculate_monomer_composition(df_test, symbol_list)
df_test_mc.shape

df_test_mc.to_csv("/home/users/akshay/PCPpred/RRCK/features/Monomeric/Test_mon_comp_RRCK.csv", index=False)
df_test_mc

,ID,SMILES,Permeability,A,dA,meA,Me_dA,Ala(tBu),Ala(indol-2-yl),dAla(indol-2-yl),...,Mono118,Mono119,Mono120,Mono121,Mono122,Mono123,Mono124,Mono125,Mono126,Mono127
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.090909,0.090909,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.090909,0.090909,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.000000,0.000000,0.000000,0.200000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.000000,0.000000,0.200000,0.100000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.000000,0.000000,0.111111,0.222222,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.000000,0.000000,0.125000,0.125000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.000000,0.000000,0.000000,0.000000,0.166667,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.000000,0.000000,0.000000,0.000000,0.166667,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.142857,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.000000,0.000000,0.166667,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.000000,0.000000,0.333333,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
#Amino acid composition 20 natural and X as non natural amino acids

In [10]:
mono = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/CycPeptMPDB_Monomer_All.csv')
mono = mono[['Symbol','Natural_Analog']]
mono_dict = mono.set_index('Symbol')['Natural_Analog'].to_dict()
mono_dict

{'A': 'A',
 'dA': 'A',
 'meA': 'A',
 'Me_dA': 'A',
 'Ala(tBu)': 'A',
 'Ala(indol-2-yl)': 'A',
 'dAla(indol-2-yl)': 'A',
 'Me_Ala(indol-2-yl)': 'A',
 'Ala(5-Tet)': 'A',
 'Abu': 'X',
 'dAbu': 'X',
 'Me_Abu': 'X',
 'Me_dAbu': 'X',
 'Me_Abu(morpholino)': 'X',
 '2Abz': 'X',
 'Aib': 'X',
 'Aoc(2)': 'L',
 '5-Ava': 'X',
 'Bal': 'A',
 'Me_Bal': 'A',
 'HOCOCH2_Bal': 'A',
 'Cys(EtO2H)_NH2': 'C',
 'Cha': 'A',
 'dCha': 'A',
 'Me_Cha': 'A',
 'D': 'D',
 'meD': 'D',
 'Asp_piperidide': 'D',
 'Asp(OMe)': 'D',
 'Asp(Ph(2-NH2))': 'D',
 'dAsp(pyrrol-1-yl)': 'D',
 'E': 'E',
 'Glu_NH2': 'E',
 'Glu(3R-Me)': 'E',
 'Glu(OMe)': 'E',
 'dGlu(OMe)': 'E',
 'F': 'F',
 'dF': 'F',
 'meF': 'F',
 'Me_dF': 'F',
 'Phe(4-F)': 'F',
 'dPhe(4-F)': 'F',
 'Phe(4-CF3)': 'F',
 'Phe(4-NO2)': 'F',
 'Phe(CHF2)': 'F',
 'dPhe(3,4-diF)': 'F',
 'Et_Phe': 'F',
 'H2NEt_Phe': 'F',
 'Me_Phe(3-Cl)': 'F',
 'Me_Phe(4-Cl)': 'F',
 'Me_Phe(a,b-dehydro)': 'F',
 'G': 'G',
 'Bn_Gly': 'G',
 'Bn(4-Cl)_Gly': 'G',
 'Bn(4-OH)_Gly': 'G',
 'Bu_Gly': 'G',
 'iBu_Gly': 'G',
 'Et_Gly': 'G',
 'EtOEt_Gly': 'G',
 'HOCOCH2_Gly_ol': 'G',
 'MeOEt_Gly': 'G',
 'NH2Bu_Gly': 'G',
 'Pr_Gly': 'G',
 'PhEt_Gly': 'G',
 'PhPr_Gly': 'G',
 'cHexCH2_Gly': 'G',
 'isoamyl_Gly': 'G',
 'pentyl_Gly': 'G',
 '3-pyridylethyl_Gly': 'G',
 '2-pyridylmethyl_Gly': 'G',
 'd(N->O)Gly(allyl)': 'G',
 'GABA': 'X',
 'H': 'H',
 'Hph': 'F',
 'Me_Hph': 'F',
 'bHph': 'F',
 'Hph(2-Cl)': 'F',
 'Hph(3-Cl)': 'F',
 'Hph(4-Cl)': 'F',
 'Hse(Et)': 'S',
 'dHyp': 'P',
 'Hyp(Et)': 'P',
 'I': 'I',
 'dI': 'I',
 'meI': 'I',
 'Me_dI': 'I',
 '(N->O)xiIle': 'I',
 'd(N->O)aIle': 'I',
 'K': 'K',
 'dK': 'K',
 'meK': 'K',
 'Me_dK': 'K',
 'Lys(Ac)': 'K',
 'Lys(Cbz)': 'K',
 'Lys(iPr)': 'K',
 'Lys(Me)': 'K',
 'Me_Lys(Me)': 'K',
 'Lys(Me2)': 'K',
 'Lys(Tfa)': 'K',
 'L': 'L',
 'dL': 'L',
 'meL': 'L',
 'Me_dL': 'L',
 'aMeLeu': 'L',
 'dLeu(3R-OH)': 'L',
 '(N->O)Leu': 'L',
 'd(N->O)Leu': 'L',
 'M': 'M',
 'meM': 'M',
 'Met(O2)': 'M',
 'N': 'N',
 'dN': 'N',
 'meN': 'N',
 'dAsn(Me2)': 'N',
 'Nal': 'A',
 '1-Nal': 'A',
 'd1-Nal': 'A',
 'Nle': 'L',
 'Me_Nle': 'L',
 'Me_dNle': 'L',
 'Nle(CHF2)': 'L',
 'Nle(OH)': 'L',
 'Nva': 'V',
 'dNva': 'V',
 'Me_Nva': 'V',
 'Me_dNva': 'V',
 'Nva(Ph)': 'V',
 'Orn': 'K',
 'P': 'P',
 'dP': 'P',
 '3Pal': 'A',
 '4Pal': 'A',
 'Phg': 'G',
 'Pip': 'X',
 'dPip': 'X',
 'Pye': 'Q',
 'dPye': 'Q',
 'Q': 'Q',
 'meQ': 'Q',
 'Gln(Me)': 'Q',
 'Gln(Me2)': 'Q',
 'dGln(Me2)': 'Q',
 'Gln(Mes)': 'Q',
 'R': 'R',
 'dR': 'R',
 'Arg(Me,Me)': 'R',
 'S': 'S',
 'dS': 'S',
 'meS': 'S',
 'Ser(Ac)': 'S',
 'Ser(Bn)': 'S',
 'Ser(EtNMe2)': 'S',
 'Ser(EtOH)': 'S',
 'Ser(isoamyl)': 'S',
 'Ser(Me)': 'S',
 'dSer(Me)': 'S',
 'Ser(Ph(2-Cl))': 'S',
 'Ser(Ph(3-Cl))': 'S',
 'Ser(Pr)': 'S',
 'Ser(tBu)': 'S',
 'Me_Ser(isoamyl)': 'S',
 'Me_Ser(Pr)': 'S',
 'Sar': 'G',
 'Sta': 'X',
 'Sta(3R,4R)': 'X',
 'T': 'T',
 'dT': 'T',
 'meT': 'T',
 'Me_Bmt(E)': 'T',
 'Tle': 'G',
 'Tza': 'A',
 'Me_Tza': 'A',
 'V': 'V',
 'dV': 'V',
 'meV': 'V',
 'Me_dV': 'V',
 '(N->O)Val': 'V',
 'd(N->O)Val': 'V',
 '(N->O)Val(3-OH)': 'V',
 'W': 'W',
 'meW': 'W',
 'Me_dW': 'W',
 'Trp(5-Br)': 'W',
 'Trp(6-Br)': 'W',
 'Trp(7-Br)': 'W',
 'Y': 'Y',
 'dY': 'Y',
 'meY': 'Y',
 'Me_dY': 'Y',
 'Tyr(3-F)': 'Y',
 'Tyr(CHF2)': 'Y',
 'Tyr(Me)': 'Y',
 'Me_Tyr(Me)': 'Y',
 'dTyr(bR-OMe)': 'Y',
 '(N->O)Tyr': 'Y',
 'Mono1': 'G',
 'Mono2': 'P',
 'Mono3': 'X',
 'Mono4': 'N',
 'Mono5': 'N',
 'Mono6': 'X',
 'Bal(3-Me)': 'A',
 'Bal(d3-CF3)': 'A',
 'Mono9': 'F',
 'Mono10': 'F',
 'Mono11': 'F',
 'Mono12': 'F',
 'Mono13': 'P',
 'Mono14': 'X',
 'Mono15': 'T',
 'Mono16': 'X',
 'Mono17': 'X',
 'Mono18': 'X',
 'Mono19': 'X',
 'Mono20': 'X',
 'Mono23': 'X',
 'Mono24': 'Q',
 'Mono25': 'X',
 'Mono26': 'I',
 'Mono27': 'V',
 'Mono28': 'X',
 'Mono29': 'X',
 'Mono30': 'X',
 'Mono31': 'X',
 'Mono32': 'G',
 'Mono33': 'G',
 'Mono34': 'G',
 'Mono35': 'X',
 'Mono36': 'X',
 'Mono37': 'X',
 'Mono38': 'G',
 'Mono39': 'G',
 'Mono40': 'G',
 'Mono41': 'G',
 'Mono42': 'G',
 'Mono43': 'G',
 'Mono44': 'G',
 'Mono45': 'G',
 'Mono46': 'P',
 'Mono47': 'P',
 'Mono48': 'X',
 'Mono49': 'S',
 'Mono50': 'S',
 'Mono51': 'X',
 'Mono52': 'X',
 'Mono53': 'X',
 'Mono54': 'S',
 'Mono55': 'S',
 'Mono56': 'S',
 'Mono57': 'S',
 'Mono58': 'G',
 'Mono59': 'P',
 'Mono60': 'P',
 'Mono61': 'X',
 'Mono62': 'S',
 'Mono63': 'X',
 'Mono64': 'S',
 'Mono65': 'X',
 'Mono66': 'S',
 'Mono67': 'X',
 'Mono68': 'X',
 'Mono69': 'X',
 'Mono70': 'X',
 'Mono71': 'H',
 'Mono72': 'Q',
 'Mono73': 'N',
 'Mono74': 'R',
 'Mono75': 'F',
 'Mono76': 'F',
 'Mono77': 'F',
 'Mono78': 'F',
 'Mono79': 'F',
 'Mono80': 'F',
 'Mono81': 'F',
 'Mono82': 'F',
 'Mono83': 'G',
 'Mono84': 'A',
 'Mono85': 'A',
 'Mono86': 'L',
 'Mono87': 'F',
 'Mono88': 'F',
 'Mono89': 'F',
 'Mono90': 'F',
 'Mono91': 'F',
 'Mono92': 'X',
 'Mono93': 'X',
 'Mono94': 'X',
 'Mono95': 'X',
 'Mono96': 'X',
 'Mono97': 'X',
 'Mono98': 'X',
 'Mono99': 'X',
 'Mono100': 'C',
 'Mono101': 'C',
 'Mono102': 'X',
 'Mono103': 'X',
 'Mono104': 'X',
 'Mono105': 'X',
 'Mono106': 'X',
 'Mono107': 'X',
 'Mono108': 'X',
 'Mono109': 'X',
 'Mono110': 'X',
 'Mono111': 'X',
 'Mono112': 'X',
 'ac-': 'X',
 'deca-': 'X',
 'glyco-': 'G',
 'medl-': 'L',
 '-pip': 'X',
 'Mono21-': 'X',
 'Mono22-': 'X',
 'dW': 'W',
 'Ala(O->S)': 'A',
 'dAla(O->S)': 'A',
 'Phe(O->S)': 'F',
 'Ile(O->S)': 'I',
 'Lys(O->S)': 'K',
 'Leu(O->S)': 'L',
 'dLeu(O->S)': 'L',
 'Pro(O->S)': 'P',
 'dPro(O->S)': 'P',
 'Thr(O->S)': 'T',
 'dTrp(O->S)': 'W',
 'Tyr(O->S)': 'Y',
 'Ac3c': 'X',
 'Abu(5-Tet)': 'X',
 'Gly(allyl)': 'G',
 '-pyrro': 'X',
 'Aze': 'X',
 'Bal(d3-Me)': 'A',
 'Me_Bal(d3-Me)': 'A',
 'Bal(d3-EtPh)': 'A',
 'meH': 'H',
 'Phe(3-Cl)': 'F',
 'Phe(3-F)': 'F',
 'Phe(4-Cl)': 'F',
 'Mono113': 'X',
 'Ser(tBuOH)': 'S',
 'Val(3-OH)': 'V',
 'Mono114': 'X',
 'Ac5c': 'X',
 'Hph(4-CF3,3,5-diF)': 'F',
 'Hph(4-Me)': 'F',
 'Phe(3,5-diCl)': 'F',
 'Hph(4-CF3,3-Cl)': 'F',
 'Me_Phe(4-Me)': 'F',
 'Hph(4-tBu)': 'F',
 'Hph(3,4-diCl)': 'F',
 'Hch': 'F',
 'Phe(3-Cl,5-F)': 'F',
 'Me_Gly(cPent)': 'G',
 'Phe(3-CF3)': 'F',
 'Et_Phe(4-Me)': 'F',
 'Hph(4-CF3)': 'F',
 '-nme2': 'X',
 'Mono115': 'C',
 'Chg': 'G',
 'Me_Chg': 'G',
 'Et_Leu': 'L',
 'Me_Ser(Me)': 'S',
 'Me_Hse(Me)': 'S',
 'Gly(cPr)': 'G',
 'Me_Gly(cPr)': 'G',
 'Gly(cBu)': 'G',
 'Me_Gly(cBu)': 'G',
 'Gly(cPent)': 'G',
 'Ala(cPr)': 'A',
 'Ala(cBu)': 'A',
 'Ala(cPent)': 'A',
 'Me_Nva(F2)': 'V',
 '-mor': 'X',
 '-aze': 'X',
 'Mono116': 'X',
 'Mono117': 'F',
 'Mono118': 'F',
 'Mono119': 'F',
 'Mono120': 'F',
 'Mono121': 'F',
 'Mono122': 'F',
 'Mono123': 'F',
 'Mono124': 'F',
 'Mono125': 'F',
 'Mono126': 'X',
 'Mono127': 'X'}

In [11]:
amino_acid_list =  list(set(mono['Natural_Analog'].to_list()))
amino_acid_list

['C',
 'Y',
 'G',
 'T',
 'A',
 'S',
 'L',
 'N',
 'P',
 'Q',
 'F',
 'I',
 'E',
 'R',
 'D',
 'V',
 'W',
 'H',
 'K',
 'M',
 'X']

In [12]:
def seq2seq(sequence):
    seq = ''
    for s in sequence:
        if s in mono_dict.keys():
            seq += mono_dict[s]
    return seq

In [13]:
def calculate_aac(df, symbol_list):
    composition_data = []

    for index, row in df.iterrows():
        # print(row['Sequence'])
        composition = {symbol: 0 for symbol in symbol_list}

        for s in row['Natural_analog_sequence']:
            if s in composition:
                # print(s)
                composition[s] += 1

        total_length = len(row['Natural_analog_sequence'])
        # print(total_length)

        frequency = {symbol: count / total_length for symbol, count in composition.items()}

        composition_data.append({
            'ID': row['ID'],
            'SMILES': row['SMILES'],
            'Permeability': row['Permeability'],
            **frequency 
        })

    composition_df = pd.DataFrame(composition_data)

    return composition_df

In [14]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
df_train.loc[:,'Sequence'] = df_train['Sequence'].apply(ast.literal_eval)
df_train.loc[:, 'Natural_analog_sequence'] = df_train['Sequence'].apply(lambda x :seq2seq(x))
df_train = calculate_aac(df_train, amino_acid_list)
print('Shape',df_train.shape)
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Monomeric/Train_aac_RRCK.csv',index=False)
df_train

Shape (140, 24)

,ID,SMILES,Permeability,C,Y,G,T,A,S,L,...,I,E,R,D,V,W,H,K,M,X
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0.0,0.0,0.090909,0.090909,0.181818,0.0,0.363636,...,0.0,0.0,0.0,0.0,0.272727,0.0,0.0,0.0,0.0,0.000000
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0.0,0.0,0.090909,0.000000,0.181818,0.0,0.363636,...,0.0,0.0,0.0,0.0,0.272727,0.0,0.0,0.0,0.0,0.090909
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0.0,0.0,0.090909,0.090909,0.181818,0.0,0.363636,...,0.0,0.0,0.0,0.0,0.181818,0.0,0.0,0.0,0.0,0.090909
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0.0,0.0,0.090909,0.090909,0.181818,0.0,0.363636,...,0.0,0.0,0.0,0.0,0.181818,0.0,0.0,0.0,0.0,0.090909
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0.0,0.0,0.090909,0.090909,0.272727,0.0,0.363636,...,0.0,0.0,0.0,0.0,0.181818,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0.0,0.0,0.000000,0.000000,0.166667,0.0,0.333333,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.166667
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0.0,0.0,0.000000,0.000000,0.333333,0.0,0.333333,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0.0,0.0,0.000000,0.000000,0.333333,0.0,0.333333,...,0.0,0.0,0.0,0.0,0.166667,0.0,0.0,0.0,0.0,0.000000
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0.0,0.0,0.000000,0.000000,0.333333,0.0,0.333333,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.166667
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0.0,0.0,0.000000,0.000000,0.500000,0.0,0.333333,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000

In [15]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
df_test.loc[:,'Sequence'] = df_test['Sequence'].apply(ast.literal_eval)
df_test.loc[:, 'Natural_analog_sequence'] = df_test['Sequence'].apply(lambda x :seq2seq(x))
df_test = calculate_aac(df_test, amino_acid_list)
print('Shape',df_test.shape)
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Monomeric/Test_aac_RRCK.csv',index=False)
df_test

Shape (35, 24)

,ID,SMILES,Permeability,C,Y,G,T,A,S,L,...,I,E,R,D,V,W,H,K,M,X
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.000000,0.000000,0.090909,0.181818,0.181818,0.000000,0.363636,...,0.000000,0.0,0.0,0.0,0.181818,0.0,0.0,0.000000,0.0,0.000000
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.000000,0.000000,0.090909,0.090909,0.181818,0.000000,0.363636,...,0.000000,0.0,0.0,0.0,0.181818,0.0,0.0,0.000000,0.0,0.090909
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.000000,0.100000,0.000000,0.000000,0.200000,0.000000,0.100000,...,0.000000,0.0,0.0,0.0,0.200000,0.0,0.0,0.000000,0.0,0.300000
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.000000,0.100000,0.000000,0.000000,0.300000,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.100000,0.0,0.0,0.000000,0.0,0.400000
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.000000,0.111111,0.000000,0.000000,0.333333,0.000000,0.222222,...,0.000000,0.0,0.0,0.0,0.111111,0.0,0.0,0.000000,0.0,0.111111
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.000000,0.125000,0.000000,0.000000,0.250000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.000000,0.125000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.625000,0.0,0.0,0.000000,0.0,0.125000
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.000000,0.000000,0.000000,0.000000,0.333333,0.166667,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.166667
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.142857,0.000000,0.000000,0.000000,0.000000,0.000000,0.571429,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.000000,0.000000,0.166667,0.000000,0.333333,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.166667,0.0,0.0,0.000000,0.0,0.000000
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.142857,...,0.142857,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.000000,0.142857,0.142857,0.000000,0.142857,0.000000,0.142857,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.000000,0.166667,0.000000,0.000000,0.333333,0.000000,0.166667,...,0.000000,0.0,0.0,0.0,0.166667,0.0,0.0,0.000000,0.0,0.000000
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.000000,0.166667,0.000000,0.000000,0.333333,0.000000,0.166667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.166667
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.166667,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.333333
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.000000,0.166667,0.000000,0.000000,0.333333,0.000000,0.333333,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.333333
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.166667,0.0,0.000000
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,...,0.166667,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.166667
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.166667,0.0,0.000000
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.166667,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.000000,0.166667,0.000000,0.000000,0.166667,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.000000,0.166667,0.166667,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.000000,0.166667,0.000000,0.000000,0.000000,0.166667,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.000000,0.000000,0.833333,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.333333
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.666667,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.500000,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000

In [16]:
#Atomic features
import pandas as pd
import numpy as np
from rdkit import Chem

In [17]:
def get_unique_atoms(smiles_list):
    unique_atoms = set()
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        if mol is not None:  # Check if the molecule was created successfully
            for atom in mol.GetAtoms():
                unique_atoms.add(atom.GetSymbol())  # Add atomic symbol to the set
    
    return unique_atoms

In [18]:
def get_atomic_composition_frequency(smiles_list):
    atomic_frequencies = []
    
    for smiles in smiles_list:
        mol = Chem.MolFromSmiles(smiles)
        composition = {'Br': 0, 'C': 0, 'Cl': 0, 'F': 0, 'N': 0, 'O': 0, 'S': 0}  
        
        if mol is not None:  # Check if the molecule was created successfully
            total_atoms = mol.GetNumAtoms()  # Get total number of atoms in the molecule
            
            for atom in mol.GetAtoms():
                composition[atom.GetSymbol()] += 1  # Count occurrences of each atom
            
            # Calculate frequency
            frequency = {atom: count / total_atoms for atom, count in composition.items()}
            atomic_frequencies.append(frequency)  # Append the frequency for this SMILES
    
    return atomic_frequencies

In [19]:
#Degree of atoms
target_atoms = {'Br', 'C', 'Cl', 'F', 'N', 'O', 'S'}
def compute_target_atom_degrees(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    # Initialize a dictionary to hold the highest degrees for target atoms
    degrees_dict = {atom: 0 for atom in target_atoms}

    # Get the degree of each atom and update the dictionary for target atoms
    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        if atom_symbol in target_atoms:
            current_degree = atom.GetDegree()
            # Update the degree if the current one is higher
            if current_degree > degrees_dict[atom_symbol]:
                degrees_dict[atom_symbol] = current_degree

    return degrees_dict

In [20]:
#Bond type
def compute_bond_types_for_cyclic_peptides(df):
    
    def compute_bond_types(smiles):
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None  # Handle invalid SMILES

        bond_types = {
            'Single': 0,
            'Double': 0,
            'Triple': 0,
            'Aromatic': 0,
            'Conjugated': 0,
            'No-bond': 0
        }

        # Iterate through the bonds in the molecule
        for bond in mol.GetBonds():
            bond_order = bond.GetBondTypeAsDouble()
            if bond_order == 1.0:
                bond_types['Single'] += 1
            elif bond_order == 2.0:
                bond_types['Double'] += 1
            elif bond_order == 3.0:
                bond_types['Triple'] += 1
            elif bond_order == 1.5:
                bond_types['Aromatic'] += 1
            elif bond_order == 1.4:
                bond_types['Conjugated'] += 1
            else:
                bond_types['No-bond'] += 1

        return bond_types

    df['Bond_Types'] = df['SMILES'].apply(compute_bond_types)

    bond_types_df = df['Bond_Types'].apply(pd.Series)

    df = pd.concat([df, bond_types_df], axis=1)

    df.drop(columns=['Bond_Types'], inplace=True)

    return df

In [21]:
#Formal charges
def calculate_overall_formal_charge(smiles):
   
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Handle invalid SMILES

    overall_charge = 0
    
    # Define valence electrons for common atoms
    valence_electrons = {
        'C': 4,
        'N': 5,
        'O': 6,
        'S': 6,
        'P': 5,
        'F': 7,
        'Cl': 7,
        'Br': 7,
        'I': 7,
    }

    for atom in mol.GetAtoms():
        atom_symbol = atom.GetSymbol()
        valence = valence_electrons.get(atom_symbol, 0)
        non_bonding = atom.GetNumImplicitHs() 
        bonding = atom.GetDegree() * 2  # 2 electrons for each bond

        # Calculate formal charge
        formal_charge = valence - (non_bonding + bonding // 2)
        overall_charge += formal_charge

    return overall_charge

In [22]:
def check_aromatic_and_ring(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return (None, None)  # Handle invalid SMILES

    # Check if the molecule is aromatic
    is_aromatic = any(atom.GetIsAromatic() for atom in mol.GetAtoms())

    # Check if the molecule contains a ring
    ring_info = mol.GetRingInfo()
    is_in_ring = ring_info.NumRings() > 0

    return (int(is_aromatic), int(is_in_ring))

In [23]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1216.662
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1214.646
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,"['Me_Bmt(E)', 'Abu', 'Sar', 'meL', 'V', 'meL',...",1202.635
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,"['A', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1188.608
...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,"['L', 'dAbu', 'A', 'L', 'dP', 'F']",626.799
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,"['L', 'dA', 'A', 'L', 'dP', 'F']",612.772
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,"['L', 'Me_dNva', 'meA', 'L', 'dP', 'meA']",606.809
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,"['L', 'Me_dAbu', 'meA', 'L', 'dP', 'meA']",592.782
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,"['L', 'Me_dA', 'meA', 'L', 'dP', 'meA']",578.755

In [24]:
unique_atoms = get_unique_atoms(df_train['SMILES'])
unique_atoms

{'C', 'F', 'N', 'O', 'S'}

In [25]:
atomic_frequencies = get_atomic_composition_frequency(df_train['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

      Br         C   Cl    F         N         O    S
0    0.0  0.732558  0.0  0.0  0.127907  0.139535  0.0
1    0.0  0.732558  0.0  0.0  0.127907  0.139535  0.0
2    0.0  0.729412  0.0  0.0  0.129412  0.141176  0.0
3    0.0  0.729412  0.0  0.0  0.129412  0.141176  0.0
4    0.0  0.726190  0.0  0.0  0.130952  0.142857  0.0
..   ...       ...  ...  ...       ...       ...  ...
135  0.0  0.733333  0.0  0.0  0.133333  0.133333  0.0
136  0.0  0.727273  0.0  0.0  0.136364  0.136364  0.0
137  0.0  0.720930  0.0  0.0  0.139535  0.139535  0.0
138  0.0  0.714286  0.0  0.0  0.142857  0.142857  0.0
139  0.0  0.707317  0.0  0.0  0.146341  0.146341  0.0

[140 rows x 7 columns]

In [26]:
df_train_atomic_comp = pd.concat([df_train[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_train_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0.0,0.726190,0.0,0.0,0.130952,0.142857,0.0
...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0.0,0.733333,0.0,0.0,0.133333,0.133333,0.0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0.0,0.727273,0.0,0.0,0.136364,0.136364,0.0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0.0,0.720930,0.0,0.0,0.139535,0.139535,0.0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0.0,0.707317,0.0,0.0,0.146341,0.146341,0.0

In [27]:
df_train_atomic_comp.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_atomic_comp_RRCK.csv', index=False)

In [28]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')
atomic_frequencies = get_atomic_composition_frequency(df_test['SMILES'])
frequency_df = pd.DataFrame(atomic_frequencies)
frequency_df.fillna(0, inplace=True)
frequency_df

     Br         C   Cl         F         N         O         S
0   0.0  0.720930  0.0  0.000000  0.127907  0.151163  0.000000
1   0.0  0.729412  0.0  0.000000  0.129412  0.141176  0.000000
2   0.0  0.730769  0.0  0.000000  0.128205  0.141026  0.000000
3   0.0  0.716216  0.0  0.000000  0.135135  0.148649  0.000000
4   0.0  0.732394  0.0  0.000000  0.126761  0.140845  0.000000
5   0.0  0.750000  0.0  0.000000  0.117647  0.132353  0.000000
6   0.0  0.746269  0.0  0.000000  0.119403  0.134328  0.000000
7   0.0  0.738462  0.0  0.030769  0.107692  0.107692  0.015385
8   0.0  0.730159  0.0  0.000000  0.126984  0.126984  0.015873
9   0.0  0.777778  0.0  0.000000  0.111111  0.095238  0.015873
10  0.0  0.777778  0.0  0.000000  0.111111  0.111111  0.000000
11  0.0  0.754098  0.0  0.000000  0.114754  0.131148  0.000000
12  0.0  0.779661  0.0  0.000000  0.101695  0.118644  0.000000
13  0.0  0.775862  0.0  0.000000  0.103448  0.120690  0.000000
14  0.0  0.732143  0.0  0.000000  0.125000  0.125000  0.017857
15  0.0  0.750000  0.0  0.000000  0.107143  0.142857  0.000000
16  0.0  0.771930  0.0  0.000000  0.105263  0.122807  0.000000
17  0.0  0.767857  0.0  0.000000  0.107143  0.125000  0.000000
18  0.0  0.750000  0.0  0.000000  0.125000  0.125000  0.000000
19  0.0  0.745455  0.0  0.000000  0.127273  0.109091  0.018182
20  0.0  0.745455  0.0  0.000000  0.127273  0.127273  0.000000
21  0.0  0.716981  0.0  0.000000  0.132075  0.132075  0.018868
22  0.0  0.759259  0.0  0.000000  0.111111  0.129630  0.000000
23  0.0  0.754717  0.0  0.000000  0.113208  0.132075  0.000000
24  0.0  0.750000  0.0  0.000000  0.115385  0.134615  0.000000
25  0.0  0.730769  0.0  0.000000  0.115385  0.153846  0.000000
26  0.0  0.750000  0.0  0.000000  0.115385  0.134615  0.000000
27  0.0  0.745098  0.0  0.000000  0.117647  0.137255  0.000000
28  0.0  0.745098  0.0  0.000000  0.117647  0.137255  0.000000
29  0.0  0.745098  0.0  0.000000  0.117647  0.137255  0.000000
30  0.0  0.764706  0.0  0.000000  0.117647  0.117647  0.000000
31  0.0  0.760000  0.0  0.000000  0.120000  0.120000  0.000000
32  0.0  0.755102  0.0  0.000000  0.122449  0.122449  0.000000
33  0.0  0.744681  0.0  0.000000  0.127660  0.127660  0.000000
34  0.0  0.727273  0.0  0.000000  0.136364  0.136364  0.000000

In [29]:
df_test_atomic_comp = pd.concat([df_test[['ID','SMILES','Permeability']], frequency_df], axis=1)
df_test_atomic_comp

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.0,0.720930,0.0,0.000000,0.127907,0.151163,0.000000
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.0,0.729412,0.0,0.000000,0.129412,0.141176,0.000000
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.0,0.730769,0.0,0.000000,0.128205,0.141026,0.000000
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.0,0.716216,0.0,0.000000,0.135135,0.148649,0.000000
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.0,0.732394,0.0,0.000000,0.126761,0.140845,0.000000
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.0,0.750000,0.0,0.000000,0.117647,0.132353,0.000000
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.0,0.746269,0.0,0.000000,0.119403,0.134328,0.000000
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.0,0.738462,0.0,0.030769,0.107692,0.107692,0.015385
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.0,0.730159,0.0,0.000000,0.126984,0.126984,0.015873
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.0,0.777778,0.0,0.000000,0.111111,0.095238,0.015873
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.0,0.777778,0.0,0.000000,0.111111,0.111111,0.000000
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.0,0.754098,0.0,0.000000,0.114754,0.131148,0.000000
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.0,0.779661,0.0,0.000000,0.101695,0.118644,0.000000
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.0,0.775862,0.0,0.000000,0.103448,0.120690,0.000000
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.0,0.732143,0.0,0.000000,0.125000,0.125000,0.017857
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.0,0.750000,0.0,0.000000,0.107143,0.142857,0.000000
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.0,0.771930,0.0,0.000000,0.105263,0.122807,0.000000
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.0,0.767857,0.0,0.000000,0.107143,0.125000,0.000000
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.0,0.750000,0.0,0.000000,0.125000,0.125000,0.000000
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.0,0.745455,0.0,0.000000,0.127273,0.109091,0.018182
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.0,0.745455,0.0,0.000000,0.127273,0.127273,0.000000
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.0,0.716981,0.0,0.000000,0.132075,0.132075,0.018868
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.0,0.759259,0.0,0.000000,0.111111,0.129630,0.000000
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.0,0.754717,0.0,0.000000,0.113208,0.132075,0.000000
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.0,0.730769,0.0,0.000000,0.115385,0.153846,0.000000
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.0,0.764706,0.0,0.000000,0.117647,0.117647,0.000000
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.0,0.760000,0.0,0.000000,0.120000,0.120000,0.000000
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.0,0.755102,0.0,0.000000,0.122449,0.122449,0.000000
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.0,0.744681,0.0,0.000000,0.127660,0.127660,0.000000
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.0,0.727273,0.0,0.000000,0.136364,0.136364,0.000000

In [30]:
df_test_atomic_comp.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_atomic_comp_RRCK.csv', index=False)

In [31]:
#Degree of atoms
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_atomic_comp_RRCK.csv')
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_atomic_comp_RRCK.csv')

In [32]:
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_atomic_comp_and_degree_RRCK.csv",index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_N,Degree_F,Degree_C,Degree_Br,Degree_S,Degree_O,Degree_Cl
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0,3,0,3,0,0,1,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0,3,0,3,0,0,1,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0,3,0,3,0,0,1,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0,3,0,3,0,0,2,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0.0,0.726190,0.0,0.0,0.130952,0.142857,0.0,3,0,3,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0.0,0.733333,0.0,0.0,0.133333,0.133333,0.0,3,0,3,0,0,1,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0.0,0.727273,0.0,0.0,0.136364,0.136364,0.0,3,0,3,0,0,1,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0.0,0.720930,0.0,0.0,0.139535,0.139535,0.0,3,0,3,0,0,1,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.0,3,0,3,0,0,1,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0.0,0.707317,0.0,0.0,0.146341,0.146341,0.0,3,0,3,0,0,1,0

In [33]:
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_atomic_comp_and_degree_RRCK.csv",index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,Degree_N,Degree_F,Degree_C,Degree_Br,Degree_S,Degree_O,Degree_Cl
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.0,0.720930,0.0,0.000000,0.127907,0.151163,0.000000,3,0,3,0,0,1,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.0,0.729412,0.0,0.000000,0.129412,0.141176,0.000000,3,0,3,0,0,1,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.0,0.730769,0.0,0.000000,0.128205,0.141026,0.000000,3,0,3,0,0,1,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.0,0.716216,0.0,0.000000,0.135135,0.148649,0.000000,3,0,3,0,0,1,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.0,0.732394,0.0,0.000000,0.126761,0.140845,0.000000,3,0,3,0,0,1,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.0,0.750000,0.0,0.000000,0.117647,0.132353,0.000000,3,0,3,0,0,1,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.0,0.746269,0.0,0.000000,0.119403,0.134328,0.000000,3,0,3,0,0,1,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.0,0.738462,0.0,0.030769,0.107692,0.107692,0.015385,3,1,4,0,2,2,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.0,0.730159,0.0,0.000000,0.126984,0.126984,0.015873,3,0,3,0,2,1,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.0,0.777778,0.0,0.000000,0.111111,0.095238,0.015873,3,0,4,0,2,1,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.0,0.777778,0.0,0.000000,0.111111,0.111111,0.000000,3,0,3,0,0,1,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.0,0.754098,0.0,0.000000,0.114754,0.131148,0.000000,3,0,3,0,0,1,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.0,0.779661,0.0,0.000000,0.101695,0.118644,0.000000,3,0,3,0,0,1,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.0,0.775862,0.0,0.000000,0.103448,0.120690,0.000000,3,0,3,0,0,1,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.0,0.732143,0.0,0.000000,0.125000,0.125000,0.017857,3,0,3,0,2,1,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.0,0.750000,0.0,0.000000,0.107143,0.142857,0.000000,3,0,3,0,0,1,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.0,0.771930,0.0,0.000000,0.105263,0.122807,0.000000,3,0,3,0,0,1,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.0,0.767857,0.0,0.000000,0.107143,0.125000,0.000000,3,0,3,0,0,1,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.0,0.750000,0.0,0.000000,0.125000,0.125000,0.000000,3,0,3,0,0,1,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.0,0.745455,0.0,0.000000,0.127273,0.109091,0.018182,3,0,4,0,2,1,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.0,0.745455,0.0,0.000000,0.127273,0.127273,0.000000,3,0,3,0,0,1,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.0,0.716981,0.0,0.000000,0.132075,0.132075,0.018868,3,0,3,0,2,1,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.0,0.759259,0.0,0.000000,0.111111,0.129630,0.000000,3,0,3,0,0,1,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.0,0.754717,0.0,0.000000,0.113208,0.132075,0.000000,3,0,3,0,0,1,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,3,0,3,0,0,2,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.0,0.730769,0.0,0.000000,0.115385,0.153846,0.000000,3,0,3,0,0,1,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,3,0,3,0,0,1,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,3,0,3,0,0,1,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,3,0,3,0,0,1,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,3,0,3,0,0,1,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.0,0.764706,0.0,0.000000,0.117647,0.117647,0.000000,3,0,3,0,0,1,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.0,0.760000,0.0,0.000000,0.120000,0.120000,0.000000,3,0,3,0,0,1,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.0,0.755102,0.0,0.000000,0.122449,0.122449,0.000000,3,0,3,0,0,1,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.0,0.744681,0.0,0.000000,0.127660,0.127660,0.000000,3,0,3,0,0,1,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.0,0.727273,0.0,0.000000,0.136364,0.136364,0.000000,3,0,3,0,0,1,0

In [34]:
#CSV with only degree columns
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Atom_Degrees'] = df_train['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_train['Atom_Degrees'].apply(pd.Series)

degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

df_train = pd.concat([df_train, degrees_df], axis=1)
df_train = df_train.drop('Atom_Degrees', axis=1)
df_train.to_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_atomic_degrees_RRCK.csv",index=False)
df_train

,ID,SMILES,Permeability,Degree_N,Degree_F,Degree_C,Degree_Br,Degree_S,Degree_O,Degree_Cl
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,3,0,3,0,0,1,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,3,0,3,0,0,1,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,3,0,3,0,0,1,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,3,0,3,0,0,2,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,3,0,3,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,3,0,3,0,0,1,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,3,0,3,0,0,1,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,3,0,3,0,0,1,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,3,0,3,0,0,1,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,3,0,3,0,0,1,0

In [35]:
#CSV with only degree columns
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Atom_Degrees'] = df_test['SMILES'].apply(compute_target_atom_degrees)
degrees_df = df_test['Atom_Degrees'].apply(pd.Series)

# Rename the columns to include the atom symbols
degrees_df.columns = [f'Degree_{atom}' for atom in target_atoms]

# Concatenate the original DataFrame with the new degrees DataFrame
df_test = pd.concat([df_test, degrees_df], axis=1)
df_test = df_test.drop('Atom_Degrees', axis=1)
df_test.to_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_atomic_degrees_RRCK.csv",index=False)
df_test

,ID,SMILES,Permeability,Degree_N,Degree_F,Degree_C,Degree_Br,Degree_S,Degree_O,Degree_Cl
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,3,0,3,0,0,1,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,3,0,3,0,0,1,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,3,0,3,0,0,1,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,3,0,3,0,0,1,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,3,0,3,0,0,1,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,3,0,3,0,0,1,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,3,0,3,0,0,1,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,3,1,4,0,2,2,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,3,0,3,0,2,1,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,3,0,4,0,2,1,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,3,0,3,0,0,1,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,3,0,3,0,0,1,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,3,0,3,0,0,1,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,3,0,3,0,0,1,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,3,0,3,0,2,1,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,3,0,3,0,0,1,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,3,0,3,0,0,1,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,3,0,3,0,0,1,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,3,0,3,0,0,1,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,3,0,4,0,2,1,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,3,0,3,0,0,1,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,3,0,3,0,2,1,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,3,0,3,0,0,1,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,3,0,3,0,0,1,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,3,0,3,0,0,2,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,3,0,3,0,0,1,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,3,0,3,0,0,1,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,3,0,3,0,0,1,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,3,0,3,0,0,1,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,3,0,3,0,0,1,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,3,0,3,0,0,1,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,3,0,3,0,0,1,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,3,0,3,0,0,1,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,3,0,3,0,0,1,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,3,0,3,0,0,1,0

In [36]:
#Bond_type
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_bonds_type_RRCK.csv', index=False)

In [37]:
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_atomic_comp_and_degree_RRCK.csv')
df_train = compute_bond_types_for_cyclic_peptides(df_train)
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_RRCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_Br,Degree_S,Degree_O,Degree_Cl,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0,...,0,0,1,0,74,12,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0.0,0.732558,0.0,0.0,0.127907,0.139535,0.0,...,0,0,1,0,73,13,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0,...,0,0,1,0,73,12,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0.0,0.729412,0.0,0.0,0.129412,0.141176,0.0,...,0,0,2,0,73,12,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0.0,0.726190,0.0,0.0,0.130952,0.142857,0.0,...,0,0,1,0,72,12,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0.0,0.733333,0.0,0.0,0.133333,0.133333,0.0,...,0,0,1,0,35,6,0,6,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0.0,0.727273,0.0,0.0,0.136364,0.136364,0.0,...,0,0,1,0,34,6,0,6,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0.0,0.720930,0.0,0.0,0.139535,0.139535,0.0,...,0,0,1,0,38,6,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0.0,0.714286,0.0,0.0,0.142857,0.142857,0.0,...,0,0,1,0,37,6,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0.0,0.707317,0.0,0.0,0.146341,0.146341,0.0,...,0,0,1,0,36,6,0,0,0,0

In [38]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_bonds_type_RRCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,74,12,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,73,12,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,64,10,0,6,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,60,10,0,6,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,58,9,0,6,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,56,8,0,6,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,55,8,0,6,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,41,6,0,23,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,51,8,0,6,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,39,6,0,23,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,42,7,0,18,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,40,7,0,18,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,51,6,0,6,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,50,6,0,6,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,44,7,0,6,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,51,6,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,49,6,0,6,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,50,7,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,46,6,0,6,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,42,6,0,11,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,45,6,0,6,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,42,7,0,6,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,45,6,0,6,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,43,6,0,6,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,47,6,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,42,6,0,6,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,42,6,0,6,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,41,6,0,6,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,41,6,0,6,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,41,6,0,6,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,42,6,0,6,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,40,6,0,6,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,39,6,0,6,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,42,6,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,39,6,0,0,0,0

In [39]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_atomic_comp_and_degree_RRCK.csv')
df_test = compute_bond_types_for_cyclic_peptides(df_test)
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_RRCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_Br,Degree_S,Degree_O,Degree_Cl,Single,Double,Triple,Aromatic,Conjugated,No-bond
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.0,0.720930,0.0,0.000000,0.127907,0.151163,0.000000,...,0,0,1,0,74,12,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.0,0.729412,0.0,0.000000,0.129412,0.141176,0.000000,...,0,0,1,0,73,12,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.0,0.730769,0.0,0.000000,0.128205,0.141026,0.000000,...,0,0,1,0,64,10,0,6,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.0,0.716216,0.0,0.000000,0.135135,0.148649,0.000000,...,0,0,1,0,60,10,0,6,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.0,0.732394,0.0,0.000000,0.126761,0.140845,0.000000,...,0,0,1,0,58,9,0,6,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.0,0.750000,0.0,0.000000,0.117647,0.132353,0.000000,...,0,0,1,0,56,8,0,6,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.0,0.746269,0.0,0.000000,0.119403,0.134328,0.000000,...,0,0,1,0,55,8,0,6,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.0,0.738462,0.0,0.030769,0.107692,0.107692,0.015385,...,0,2,2,0,41,6,0,23,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.0,0.730159,0.0,0.000000,0.126984,0.126984,0.015873,...,0,2,1,0,51,8,0,6,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.0,0.777778,0.0,0.000000,0.111111,0.095238,0.015873,...,0,2,1,0,39,6,0,23,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.0,0.777778,0.0,0.000000,0.111111,0.111111,0.000000,...,0,0,1,0,42,7,0,18,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.0,0.754098,0.0,0.000000,0.114754,0.131148,0.000000,...,0,0,1,0,40,7,0,18,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.0,0.779661,0.0,0.000000,0.101695,0.118644,0.000000,...,0,0,1,0,51,6,0,6,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.0,0.775862,0.0,0.000000,0.103448,0.120690,0.000000,...,0,0,1,0,50,6,0,6,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.0,0.732143,0.0,0.000000,0.125000,0.125000,0.017857,...,0,2,1,0,44,7,0,6,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.0,0.750000,0.0,0.000000,0.107143,0.142857,0.000000,...,0,0,1,0,51,6,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.0,0.771930,0.0,0.000000,0.105263,0.122807,0.000000,...,0,0,1,0,49,6,0,6,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.0,0.767857,0.0,0.000000,0.107143,0.125000,0.000000,...,0,0,1,0,50,7,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.0,0.750000,0.0,0.000000,0.125000,0.125000,0.000000,...,0,0,1,0,46,6,0,6,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.0,0.745455,0.0,0.000000,0.127273,0.109091,0.018182,...,0,2,1,0,42,6,0,11,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.0,0.745455,0.0,0.000000,0.127273,0.127273,0.000000,...,0,0,1,0,45,6,0,6,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.0,0.716981,0.0,0.000000,0.132075,0.132075,0.018868,...,0,2,1,0,42,7,0,6,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.0,0.759259,0.0,0.000000,0.111111,0.129630,0.000000,...,0,0,1,0,45,6,0,6,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.0,0.754717,0.0,0.000000,0.113208,0.132075,0.000000,...,0,0,1,0,43,6,0,6,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,...,0,0,2,0,47,6,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.0,0.730769,0.0,0.000000,0.115385,0.153846,0.000000,...,0,0,1,0,42,6,0,6,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,...,0,0,1,0,42,6,0,6,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,0,1,0,41,6,0,6,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,0,1,0,41,6,0,6,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,0,1,0,41,6,0,6,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.0,0.764706,0.0,0.000000,0.117647,0.117647,0.000000,...,0,0,1,0,42,6,0,6,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.0,0.760000,0.0,0.000000,0.120000,0.120000,0.000000,...,0,0,1,0,40,6,0,6,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.0,0.755102,0.0,0.000000,0.122449,0.122449,0.000000,...,0,0,1,0,39,6,0,6,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.0,0.744681,0.0,0.000000,0.127660,0.127660,0.000000,...,0,0,1,0,42,6,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.0,0.727273,0.0,0.000000,0.136364,0.136364,0.000000,...,0,0,1,0,39,6,0,0,0,0

In [40]:
#Overall formal charge
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train['Overall_Formal_Charge'] = df_train['SMILES'].apply(calculate_overall_formal_charge)
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_formal_charge_RRCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Overall_Formal_Charge
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,106
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,107
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,106
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,106
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,106
...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,60
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,60
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,54
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,54
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,54

In [41]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test['Overall_Formal_Charge'] = df_test['SMILES'].apply(calculate_overall_formal_charge)
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_formal_charge_RRCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Overall_Formal_Charge
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,111
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,106
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,100
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,100
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,91
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,82
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,82
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,97
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,81
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,81
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,81
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,84
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,64
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,64
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,72
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,64
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,64
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,61
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,66
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,72
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,66
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,72
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,64
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,63
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,57
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,68
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,62
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,59
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,64
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,64
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,60
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,60
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,60
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,54
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,54

In [42]:
#Aromatic and ring
df_train = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv')
df_train = df_train[['ID','SMILES','Permeability']]
df_train[['Is_Aromatic', 'Is_In_Ring']] = df_train['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_is_ring_is_aromatic_RRCK.csv', index=False)
df_train

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,1
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,1
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,1
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,1
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,1
...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,1,1
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,1,1
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,1
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,1
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,1

In [43]:
df_test = pd.read_csv('/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv')
df_test = df_test[['ID','SMILES','Permeability']]
df_test[['Is_Aromatic', 'Is_In_Ring']] = df_test['SMILES'].apply(check_aromatic_and_ring).apply(pd.Series)
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_is_ring_is_aromatic_RRCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Is_Aromatic,Is_In_Ring
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,1
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,1
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,1,1
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,1,1
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,1,1
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,1,1
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,1,1
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,1,1
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,1
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,1,1
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,1,1
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,1,1
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,1,1
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,1,1
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,1
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,1
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,1,1
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,1
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,1,1
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,1,1
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,1,1
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,1
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,1,1
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,1,1
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,1
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,1,1
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,1,1
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,1,1
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,1,1
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,1,1
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,1,1
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,1,1
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,1,1
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,1
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,1

In [44]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_Atomic_comp_atomic_degree_bonds_type_RRCK.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_formal_charge_RRCK.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_is_ring_is_aromatic_RRCK.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_train = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Train_all_atomic_desc_RRCK.csv', index=False)

In [45]:
df1 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_Atomic_comp_atomic_degree_bonds_type_RRCK.csv")
df2 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_formal_charge_RRCK.csv")
df3 = pd.read_csv("/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_is_ring_is_aromatic_RRCK.csv")

merged_df = pd.merge(df1, df2, on=['ID', 'SMILES', 'Permeability'], how='inner')

# Merge the result with df3
df_test = pd.merge(merged_df, df3, on=['ID', 'SMILES', 'Permeability'], how='inner')
df_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Atomic/Test_all_atomic_desc_RRCK.csv', index=False)
df_test

,ID,SMILES,Permeability,Br,C,Cl,F,N,O,S,...,Degree_Cl,Single,Double,Triple,Aromatic,Conjugated,No-bond,Overall_Formal_Charge,Is_Aromatic,Is_In_Ring
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0.0,0.720930,0.0,0.000000,0.127907,0.151163,0.000000,...,0,74,12,0,0,0,0,111,0,1
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0.0,0.729412,0.0,0.000000,0.129412,0.141176,0.000000,...,0,73,12,0,0,0,0,106,0,1
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0.0,0.730769,0.0,0.000000,0.128205,0.141026,0.000000,...,0,64,10,0,6,0,0,100,1,1
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0.0,0.716216,0.0,0.000000,0.135135,0.148649,0.000000,...,0,60,10,0,6,0,0,100,1,1
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0.0,0.732394,0.0,0.000000,0.126761,0.140845,0.000000,...,0,58,9,0,6,0,0,91,1,1
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0.0,0.750000,0.0,0.000000,0.117647,0.132353,0.000000,...,0,56,8,0,6,0,0,82,1,1
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0.0,0.746269,0.0,0.000000,0.119403,0.134328,0.000000,...,0,55,8,0,6,0,0,82,1,1
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0.0,0.738462,0.0,0.030769,0.107692,0.107692,0.015385,...,0,41,6,0,23,0,0,97,1,1
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0.0,0.730159,0.0,0.000000,0.126984,0.126984,0.015873,...,0,51,8,0,6,0,0,81,1,1
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0.0,0.777778,0.0,0.000000,0.111111,0.095238,0.015873,...,0,39,6,0,23,0,0,81,1,1
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0.0,0.777778,0.0,0.000000,0.111111,0.111111,0.000000,...,0,42,7,0,18,0,0,81,1,1
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0.0,0.754098,0.0,0.000000,0.114754,0.131148,0.000000,...,0,40,7,0,18,0,0,84,1,1
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0.0,0.779661,0.0,0.000000,0.101695,0.118644,0.000000,...,0,51,6,0,6,0,0,64,1,1
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0.0,0.775862,0.0,0.000000,0.103448,0.120690,0.000000,...,0,50,6,0,6,0,0,64,1,1
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0.0,0.732143,0.0,0.000000,0.125000,0.125000,0.017857,...,0,44,7,0,6,0,0,72,1,1
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0.0,0.750000,0.0,0.000000,0.107143,0.142857,0.000000,...,0,51,6,0,0,0,0,64,0,1
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0.0,0.771930,0.0,0.000000,0.105263,0.122807,0.000000,...,0,49,6,0,6,0,0,64,1,1
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0.0,0.767857,0.0,0.000000,0.107143,0.125000,0.000000,...,0,50,7,0,0,0,0,61,0,1
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0.0,0.750000,0.0,0.000000,0.125000,0.125000,0.000000,...,0,46,6,0,6,0,0,66,1,1
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0.0,0.745455,0.0,0.000000,0.127273,0.109091,0.018182,...,0,42,6,0,11,0,0,72,1,1
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0.0,0.745455,0.0,0.000000,0.127273,0.127273,0.000000,...,0,45,6,0,6,0,0,66,1,1
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0.0,0.716981,0.0,0.000000,0.132075,0.132075,0.018868,...,0,42,7,0,6,0,0,72,1,1
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0.0,0.759259,0.0,0.000000,0.111111,0.129630,0.000000,...,0,45,6,0,6,0,0,64,1,1
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0.0,0.754717,0.0,0.000000,0.113208,0.132075,0.000000,...,0,43,6,0,6,0,0,63,1,1
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,...,0,47,6,0,0,0,0,57,0,1
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0.0,0.730769,0.0,0.000000,0.115385,0.153846,0.000000,...,0,42,6,0,6,0,0,68,1,1
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0.0,0.750000,0.0,0.000000,0.115385,0.134615,0.000000,...,0,42,6,0,6,0,0,62,1,1
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,41,6,0,6,0,0,59,1,1
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,41,6,0,6,0,0,64,1,1
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0.0,0.745098,0.0,0.000000,0.117647,0.137255,0.000000,...,0,41,6,0,6,0,0,64,1,1
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0.0,0.764706,0.0,0.000000,0.117647,0.117647,0.000000,...,0,42,6,0,6,0,0,60,1,1
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0.0,0.760000,0.0,0.000000,0.120000,0.120000,0.000000,...,0,40,6,0,6,0,0,60,1,1
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0.0,0.755102,0.0,0.000000,0.122449,0.122449,0.000000,...,0,39,6,0,6,0,0,60,1,1
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0.0,0.744681,0.0,0.000000,0.127660,0.127660,0.000000,...,0,42,6,0,0,0,0,54,0,1
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0.0,0.727273,0.0,0.000000,0.136364,0.136364,0.000000,...,0,39,6,0,0,0,0,54,0,1

In [46]:
#Fingerprints

In [47]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem, rdFingerprintGenerator, rdMolDescriptors
from padelpy import padeldescriptor

In [48]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
df_train

,ID,SMILES,Permeability,Sequence,MolWt
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1216.662
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,"['V', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1214.646
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,"['Abu', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', '...",1202.635
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,"['Me_Bmt(E)', 'Abu', 'Sar', 'meL', 'V', 'meL',...",1202.635
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,"['A', 'Sar', 'meL', 'V', 'meL', 'A', 'dA', 'me...",1188.608
...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,"['L', 'dAbu', 'A', 'L', 'dP', 'F']",626.799
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,"['L', 'dA', 'A', 'L', 'dP', 'F']",612.772
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,"['L', 'Me_dNva', 'meA', 'L', 'dP', 'meA']",606.809
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,"['L', 'Me_dAbu', 'meA', 'L', 'dP', 'meA']",592.782
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,"['L', 'Me_dA', 'meA', 'L', 'dP', 'meA']",578.755

In [49]:
df_train_cmfp = df_train[['ID','SMILES','Permeability']]
df_train_cmfp

       ID                                             SMILES  Permeability
0    2358  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...         -6.13
1    2359  C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...         -6.66
2    5669  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...         -5.76
3    2360  C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...         -6.78
4    2353  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...         -5.87
..    ...                                                ...           ...
135  2335  CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...         -5.53
136  2334  CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...         -5.58
137  2305  CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...         -4.85
138  2304  CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...         -5.51
139  2303  CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...         -5.31

[140 rows x 3 columns]

In [50]:
def generate_count_morgan_fp(smiles, radius=2, nBits=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Count Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=radius, fpSize=nBits)
        count_fp = mfpgen.GetCountFingerprint(mol)
        
        # Convert the count fingerprint to a dense array
        dense_fp = np.zeros((nBits,), dtype=int)
        for bit, count in count_fp.GetNonzeroElements().items():
            dense_fp[bit] = count
            
        return dense_fp
    else:
        return None

In [51]:
df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_train_cmfp['count_morgan_fp']

/tmp/ipykernel_2001246/1551993060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train_cmfp.loc[:,'count_morgan_fp'] = df_train_cmfp['SMILES'].apply(generate_count_morgan_fp)

0      [0, 9, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1      [0, 8, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2      [0, 8, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3      [0, 7, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4      [0, 8, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                             ...
135    [0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
136    [0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
137    [0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
138    [0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
139    [0, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: count_morgan_fp, Length: 140, dtype: object

In [52]:
df = pd.DataFrame(df_train_cmfp['count_morgan_fp'].tolist(), index=df_train_cmfp.index)

df_train_cmfp = pd.concat([df_train_cmfp, df.add_prefix('count_fp_')], axis=1)
df_train_cmfp.shape

(140, 2052)

In [53]:
df_train_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_train_cmfp.shape

(140, 2051)

In [54]:
df_train_cmfp.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/count_morgan_fp_train_RRCK.csv', index=False)

In [55]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
df_test_cmfp = df_test[['ID','SMILES','Permeability']]
df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)
df_test_cmfp['count_morgan_fp']
df = pd.DataFrame(df_test_cmfp['count_morgan_fp'].tolist(), index=df_test_cmfp.index)

df_test_cmfp = pd.concat([df_test_cmfp, df.add_prefix('count_fp_')], axis=1)
df_test_cmfp.drop('count_morgan_fp', axis=1, inplace=True)
df_test_cmfp.shape

/tmp/ipykernel_2001246/1721296512.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_cmfp.loc[:,'count_morgan_fp'] = df_test_cmfp['SMILES'].apply(generate_count_morgan_fp)

(35, 2051)

In [56]:
df_test_cmfp.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/count_morgan_fp_test_RRCK.csv', index=False)

In [57]:
def generate_fingerprints(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        # Create a Morgan fingerprint generator
        mfpgen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
        
        # Generate the Morgan fingerprint as a bit vector
        morgan_fp = mfpgen.GetFingerprint(mol)
        
        # Convert the bit vector to a dense array
        dense_fp = np.zeros((2048,), dtype=int)
        for bit in range(2048):
            dense_fp[bit] = morgan_fp[bit]
        
        return dense_fp
    else:
        print("Invalid SMILES string.")
        return None

In [58]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
df_mfp_train = df_train[['ID','SMILES','Permeability']]
df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_train['Morganfingerprints'].tolist(), index=df_mfp_train.index)

df_mfp_train = pd.concat([df_mfp_train, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_train.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/morgan_fp_train_RRCK.csv', index=False)
print(df_mfp_train.shape)
df_mfp_train

/tmp/ipykernel_2001246/1927033210.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_train.loc[:,'Morganfingerprints'] = df_mfp_train['SMILES'].apply(generate_fingerprints)

(140, 2051)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
df_mfp_test = df_test[['ID','SMILES','Permeability']]
df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)
df = pd.DataFrame(df_mfp_test['Morganfingerprints'].tolist(), index=df_mfp_test.index)

df_mfp_test = pd.concat([df_mfp_test, df.add_prefix('Morgan_fp_')], axis=1)
df_mfp_test.drop('Morganfingerprints', axis=1, inplace=True)
df_mfp_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/morgan_fp_test_RRCK.csv', index=False)
print(df_mfp_test.shape)
df_mfp_test

(35, 2051)

/tmp/ipykernel_2001246/1041046336.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mfp_test.loc[:,'Morganfingerprints'] = df_mfp_test['SMILES'].apply(generate_fingerprints)

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,Morgan_fp_2038,Morgan_fp_2039,Morgan_fp_2040,Morgan_fp_2041,Morgan_fp_2042,Morgan_fp_2043,Morgan_fp_2044,Morgan_fp_2045,Morgan_fp_2046,Morgan_fp_2047
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
#Padel fingerprints
import glob
import os
directory = '/home/users/akshay/PCPpred/fingerprints_xml'
pattern = '*.xml'  

xml_files = glob.glob(os.path.join(directory, pattern))
xml_files.sort()
xml_files

['/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml']

In [61]:
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'Extended',
 'Fingerprinter',
 'Graphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [62]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': '/home/users/akshay/PCPpred/fingerprints_xml/AtomPairs2DFingerprinter.xml',
 'EState': '/home/users/akshay/PCPpred/fingerprints_xml/EStateFingerprinter.xml',
 'Extended': '/home/users/akshay/PCPpred/fingerprints_xml/ExtendedFingerprinter.xml',
 'Fingerprinter': '/home/users/akshay/PCPpred/fingerprints_xml/Fingerprinter.xml',
 'Graphonly': '/home/users/akshay/PCPpred/fingerprints_xml/GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': '/home/users/akshay/PCPpred/fingerprints_xml/KlekotaRothFingerprinter.xml',
 'MACCS': '/home/users/akshay/PCPpred/fingerprints_xml/MACCSFingerprinter.xml',
 'PubChem': '/home/users/akshay/PCPpred/fingerprints_xml/PubchemFingerprinter.xml',
 'SubstructureCount': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprintCount.xml',
 'Substructure': '/home/users/akshay/PCPpred/fingerprints_xml/SubstructureFingerprinter.xml'}

In [63]:
#Substructure
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,SubFP8,SubFP9,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2358,1,1,1,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2359,1,1,1,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
2,5669,1,1,1,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2360,1,1,1,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2353,1,1,1,0,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
136,2334,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
137,2305,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
138,2304,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
139,2303,1,1,1,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [64]:
df_Substructure_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_Substructure_train.head()

,ID,SMILES,Permeability,Name,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,2358,1,1,1,0,1,0,...,0,0,1,1,1,0,0,0,0,1
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,2359,1,1,1,0,1,0,...,0,0,1,1,1,0,0,0,0,1
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,5669,1,1,1,0,1,0,...,0,0,1,1,1,0,0,0,0,1
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,2360,1,1,1,0,1,0,...,0,0,1,1,1,0,0,0,0,1
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,2353,1,1,1,0,1,0,...,0,0,1,1,1,0,0,0,0,1

In [65]:
df_Substructure_train.drop(['Name'],axis=1,inplace=True)
df_Substructure_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Substructure_train_RRCK.csv', index=False)
df_Substructure_train

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [66]:
fingerprint = 'Substructure'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_Substructure_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_Substructure_test.drop(['Name'],axis=1,inplace=True)
df_Substructure_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Substructure_test_RRCK.csv', index=False)
df_Substructure_test

,ID,SMILES,Permeability,SubFP1,SubFP2,SubFP3,SubFP4,SubFP5,SubFP6,SubFP7,...,SubFP298,SubFP299,SubFP300,SubFP301,SubFP302,SubFP303,SubFP304,SubFP305,SubFP306,SubFP307
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,1,1,1,0,1,0,0,...,0,0,1,1,1,0,0,0,0,1
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,1,1,0,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,1,1,0,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,1,1,1,0,1,0,0,...,0,0,1,1,1,1,0,0,0,1
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,1,1,1,1,0,0,0,...,0,0,1,1,1,0,0,0,0,1
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,1,1,1,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [67]:
#CountSubstructure
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_train.head()

,ID,SMILES,Permeability,Name,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,2358,18.0,5.0,8.0,0.0,1.0,0.0,...,0.0,0.0,67.0,67.0,15.0,0.0,0.0,0.0,0.0,43.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,2359,18.0,5.0,8.0,0.0,1.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,43.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,5669,17.0,6.0,7.0,0.0,1.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,2360,17.0,6.0,7.0,0.0,1.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,2353,17.0,5.0,7.0,0.0,1.0,0.0,...,0.0,0.0,65.0,65.0,14.0,0.0,0.0,0.0,0.0,42.0

In [68]:
df_SubstructureCount_train.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/SubstructureCount_train_RRCK.csv', index=False)
df_SubstructureCount_train

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,18.0,5.0,8.0,0.0,1.0,0.0,0.0,...,0.0,0.0,67.0,67.0,15.0,0.0,0.0,0.0,0.0,43.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,18.0,5.0,8.0,0.0,1.0,0.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,43.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,17.0,6.0,7.0,0.0,1.0,0.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,17.0,6.0,7.0,0.0,1.0,0.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,17.0,5.0,7.0,0.0,1.0,0.0,0.0,...,0.0,0.0,65.0,65.0,14.0,0.0,0.0,0.0,0.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,6.0,6.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,34.0,34.0,7.0,0.0,0.0,0.0,0.0,26.0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,6.0,5.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,33.0,33.0,6.0,0.0,0.0,0.0,0.0,26.0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,7.0,6.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,34.0,34.0,6.0,0.0,0.0,0.0,0.0,20.0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,7.0,5.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,33.0,33.0,5.0,0.0,0.0,0.0,0.0,20.0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,7.0,4.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,32.0,32.0,4.0,0.0,0.0,0.0,0.0,20.0

In [69]:
fingerprint = 'SubstructureCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) #Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_SubstructureCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_SubstructureCount_test.drop(['Name'],axis=1,inplace=True)
df_SubstructureCount_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/SubstructureCount_test_RRCK.csv', index=False)
df_SubstructureCount_test

,ID,SMILES,Permeability,SubFPC1,SubFPC2,SubFPC3,SubFPC4,SubFPC5,SubFPC6,SubFPC7,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,17.0,5.0,7.0,0.0,1.0,0.0,0.0,...,0.0,0.0,67.0,67.0,15.0,0.0,0.0,0.0,0.0,43.0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,17.0,6.0,7.0,0.0,1.0,0.0,0.0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,8.0,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,36.0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,8.0,9.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,50.0,50.0,8.0,0.0,0.0,0.0,0.0,36.0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,7.0,12.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,49.0,49.0,11.0,0.0,0.0,0.0,0.0,33.0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,10.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,48.0,48.0,10.0,0.0,0.0,0.0,0.0,34.0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,6.0,14.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,47.0,47.0,13.0,0.0,0.0,0.0,0.0,30.0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,3.0,7.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,14.0,0.0,0.0,0.0,0.0,39.0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,4.0,15.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,48.0,48.0,16.0,0.0,0.0,0.0,0.0,29.0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,3.0,10.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,37.0,37.0,14.0,0.0,0.0,0.0,0.0,39.0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,4.0,7.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,10.0,0.0,0.0,0.0,0.0,40.0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,3.0,6.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,36.0,36.0,8.0,0.0,0.0,0.0,0.0,39.0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,3.0,18.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,47.0,47.0,10.0,0.0,0.0,0.0,0.0,27.0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,3.0,17.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,46.0,46.0,9.0,0.0,0.0,0.0,0.0,27.0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,4.0,13.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,42.0,16.0,0.0,0.0,0.0,0.0,26.0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,10.0,9.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,47.0,47.0,10.0,0.0,0.0,0.0,0.0,25.0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,4.0,17.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,48.0,48.0,10.0,0.0,0.0,0.0,0.0,28.0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,11.0,8.0,5.0,0.0,1.0,0.0,0.0,...,0.0,0.0,45.0,45.0,10.0,1.0,0.0,0.0,0.0,26.0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,6.0,9.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,42.0,42.0,13.0,0.0,0.0,0.0,0.0,28.0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,7.0,7.0,2.0,1.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,7.0,0.0,0.0,0.0,0.0,30.0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,6.0,9.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,41.0,41.0,12.0,0.0,0.0,0.0,0.0,27.0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,3.0,12.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,41.0,41.0,13.0,0.0,0.0,0.0,0.0,26.0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,6.0,12.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,44.0,44.0,10.0,0.0,0.0,0.0,0.0,28.0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,8.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,27.0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,10.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,43.0,43.0,13.0,0.0,0.0,0.0,0.0,22.0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,6.0,6.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,9.0,0.0,0.0,0.0,0.0,27.0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,8.0,5.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,10.0,0.0,0.0,0.0,0.0,26.0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,8.0,2.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,35.0,35.0,10.0,0.0,0.0,0.0,0.0,23.0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,6.0,8.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,8.0,0.0,0.0,0.0,0.0,27.0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,8.0,7.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,6.0,7.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,35.0,35.0,8.0,0.0,0.0,0.0,0.0,26.0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,9.0,6.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,38.0,38.0,8.0,0.0,0.0,0.0,0.0,22.0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,8.0,5.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,35.0,35.0,6.0,0.0,0.0,0.0,0.0,21.0

In [70]:
#MACCS
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_train.head()
df_MACCS_train.drop(['Name'],axis=1,inplace=True)
df_MACCS_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/MACCS_train_RRCK.csv', index=False)
df_MACCS_train

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0

In [71]:
fingerprint = 'MACCS'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_MACCS_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_MACCS_test.drop(['Name'],axis=1,inplace=True)
df_MACCS_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/MACCS_test_RRCK.csv', index=False)
df_MACCS_test

,ID,SMILES,Permeability,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,0,0,0,0,0,0,...,1,1,1,1,1,0,0,1,1,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,0,0,0,0,0,0,...,0,1,1,1,1,1,1,1,1,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,0,0,0,0,0,0,...,0,1,1,1,1,0,0,1,1,0

In [72]:
#PubChem
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_train.drop(['Name'],axis=1,inplace=True)
df_PubChem_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/PubChem_train_RRCK.csv', index=False)
df_PubChem_train

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [73]:
fingerprint = 'PubChem'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_PubChem_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_PubChem_test.drop(['Name'],axis=1,inplace=True)
df_PubChem_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/PubChem_test_RRCK.csv', index=False)
df_PubChem_test

,ID,SMILES,Permeability,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [74]:
#AtomPairs2DCount
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/AtomPairs2DCount_train_RRCK.csv', index=False)
df_AtomPairs2DCount_train

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,45.0,29.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,45.0,29.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,44.0,29.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,44.0,28.0,13.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,43.0,29.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,28.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,27.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,22.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,21.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,20.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
fingerprint = 'AtomPairs2DCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2DCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2DCount_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2DCount_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/AtomPairs2DCount_test_RRCK.csv', index=False)
df_AtomPairs2DCount_test

,ID,SMILES,Permeability,APC2D1_C_C,APC2D1_C_N,APC2D1_C_O,APC2D1_C_S,APC2D1_C_P,APC2D1_C_F,APC2D1_C_Cl,...,APC2D10_I_I,APC2D10_I_B,APC2D10_I_Si,APC2D10_I_X,APC2D10_B_B,APC2D10_B_Si,APC2D10_B_X,APC2D10_Si_Si,APC2D10_Si_X,APC2D10_X_X
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,44.0,29.0,13.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,44.0,29.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,39.0,30.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,35.0,30.0,11.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,36.0,27.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,37.0,24.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,36.0,24.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,42.0,16.0,8.0,2.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,36.0,19.0,8.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,44.0,16.0,6.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,42.0,18.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,39.0,18.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,40.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,39.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,32.0,16.0,7.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,33.0,16.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,41.0,13.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,34.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,33.0,18.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,34.0,17.0,6.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,33.0,17.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,31.0,15.0,7.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,37.0,13.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,32.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,29.0,16.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,30.0,16.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,31.0,16.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,28.0,18.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,33.0,13.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,33.0,13.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,32.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,33.0,13.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,29.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,26.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,23.0,16.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
#AtomPairs2D
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_train.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/AtomPairs2D_train_RRCK.csv', index=False)
df_AtomPairs2D_train

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
fingerprint = 'AtomPairs2D'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
df_AtomPairs2D_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
df_AtomPairs2D_test.drop(['Name'],axis=1,inplace=True)
df_AtomPairs2D_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/AtomPairs2D_test_RRCK.csv', index=False)
df_AtomPairs2D_test

,ID,SMILES,Permeability,AD2D1,AD2D2,AD2D3,AD2D4,AD2D5,AD2D6,AD2D7,...,AD2D771,AD2D772,AD2D773,AD2D774,AD2D775,AD2D776,AD2D777,AD2D778,AD2D779,AD2D780
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,1,1,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
#EState
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_train.drop(['Name'],axis=1,inplace=True)
EState_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/EState_train_RRCK.csv', index=False)
EState_train

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [79]:
fingerprint = 'EState'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
EState_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
EState_test.drop(['Name'],axis=1,inplace=True)
EState_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/EState_test_RRCK.csv', index=False)
EState_test

,ID,SMILES,Permeability,EStateFP1,EStateFP2,EStateFP3,EStateFP4,EStateFP5,EStateFP6,EStateFP7,...,EStateFP70,EStateFP71,EStateFP72,EStateFP73,EStateFP74,EStateFP75,EStateFP76,EStateFP77,EStateFP78,EStateFP79
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [80]:
#Extended
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_train.drop(['Name'],axis=1,inplace=True)
Extended_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Extended_train_RRCK.csv', index=False)
Extended_train

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [81]:
fingerprint = 'Extended'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Extended_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Extended_test.drop(['Name'],axis=1,inplace=True)
Extended_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Extended_test_RRCK.csv', index=False)
Extended_test

,ID,SMILES,Permeability,ExtFP1,ExtFP2,ExtFP3,ExtFP4,ExtFP5,ExtFP6,ExtFP7,...,ExtFP1015,ExtFP1016,ExtFP1017,ExtFP1018,ExtFP1019,ExtFP1020,ExtFP1021,ExtFP1022,ExtFP1023,ExtFP1024
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,1,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,1,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,1,0,1,0,0,1,...,1,1,1,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,1,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,1,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [82]:
#Fingerprinter
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_train.drop(['Name'],axis=1,inplace=True)
Fingerprinter_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Fingerprinter_train_RRCK.csv', index=False)
Fingerprinter_train

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,0,0,0,0,1,0,...,1,1,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [83]:
fingerprint = 'Fingerprinter'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Fingerprinter_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Fingerprinter_test.drop(['Name'],axis=1,inplace=True)
Fingerprinter_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Fingerprinter_test_RRCK.csv', index=False)
Fingerprinter_test

,ID,SMILES,Permeability,FP1,FP2,FP3,FP4,FP5,FP6,FP7,...,FP1015,FP1016,FP1017,FP1018,FP1019,FP1020,FP1021,FP1022,FP1023,FP1024
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,1,0,0,...,0,1,0,1,1,0,0,1,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,0,0,0,0,1,1,...,1,1,1,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [84]:
#GraphOnly
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_train.drop(['Name'],axis=1,inplace=True)
Graphonly_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Graphonly_train_RRCK.csv', index=False)
Graphonly_train

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [85]:
fingerprint = 'Graphonly'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
Graphonly_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
Graphonly_test.drop(['Name'],axis=1,inplace=True)
Graphonly_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Graphonly_test_RRCK.csv', index=False)
Graphonly_test

,ID,SMILES,Permeability,GraphFP1,GraphFP2,GraphFP3,GraphFP4,GraphFP5,GraphFP6,GraphFP7,...,GraphFP1015,GraphFP1016,GraphFP1017,GraphFP1018,GraphFP1019,GraphFP1020,GraphFP1021,GraphFP1022,GraphFP1023,GraphFP1024
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,0,0,0,1,1,0,...,1,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [86]:
#KlekotaRothCount
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_train.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/KlekotaRothCount_train_RRCK.csv', index=False)
KlekotaRothCount_train

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,19.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,18.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,18.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,18.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,18.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,8.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [87]:
fingerprint = 'KlekotaRothCount'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRothCount_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRothCount_test.drop(['Name'],axis=1,inplace=True)
KlekotaRothCount_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/KlekotaRothCount_test_RRCK.csv', index=False)
KlekotaRothCount_test

,ID,SMILES,Permeability,KRFPC1,KRFPC2,KRFPC3,KRFPC4,KRFPC5,KRFPC6,KRFPC7,...,KRFPC4851,KRFPC4852,KRFPC4853,KRFPC4854,KRFPC4855,KRFPC4856,KRFPC4857,KRFPC4858,KRFPC4859,KRFPC4860
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,19.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,18.0,4.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,10.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,10.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,9.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,12.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,8.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,8.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,9.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,13.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,12.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,8.0,2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,6.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,8.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,10.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,9.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [88]:
#KlekotaRoth
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_train.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_train = pd.concat([df_train[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_train.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_train.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/KlekotaRoth_train_RRCK.csv', index=False)
KlekotaRoth_train

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
fingerprint = 'KlekotaRoth'
fingerprint_output_file = ''.join(['/home/users/akshay/PCPpred/RRCK/features/Fingerprints/',fingerprint,'_test.csv']) 
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

descriptors = pd.read_csv(fingerprint_output_file)
KlekotaRoth_test = pd.concat([df_test[['ID','SMILES','Permeability']], descriptors], axis=1)
KlekotaRoth_test.drop(['Name'],axis=1,inplace=True)
KlekotaRoth_test.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/KlekotaRoth_test_RRCK.csv', index=False)
KlekotaRoth_test

,ID,SMILES,Permeability,KRFP1,KRFP2,KRFP3,KRFP4,KRFP5,KRFP6,KRFP7,...,KRFP4851,KRFP4852,KRFP4853,KRFP4854,KRFP4855,KRFP4856,KRFP4857,KRFP4858,KRFP4859,KRFP4860
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [90]:
df_train_morgan = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/morgan_fp_train_RRCK.csv')
df_train_morganCount = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/count_morgan_fp_train_RRCK.csv')
df_train_AP2d = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/AtomPairs2D_train_RRCK.csv')
df_train_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/AtomPairs2DCount_train_RRCK.csv')
df_train_EState = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/EState_train_RRCK.csv')
df_train_Extended = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Extended_train_RRCK.csv')
df_train_fp= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Fingerprinter_train_RRCK.csv')
df_train_graph= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Graphonly_train_RRCK.csv')
df_train_kr= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/KlekotaRoth_train_RRCK.csv')
df_train_krcount= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/KlekotaRothCount_train_RRCK.csv')
df_train_maccs= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/MACCS_train_RRCK.csv')
df_train_pubchem= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/PubChem_train_RRCK.csv')
df_train_Substr= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/Substructure_train_RRCK.csv')
df_train_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/SubstructureCount_train_RRCK.csv')

df = df_train_morgan.merge(df_train_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_train_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_train_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,0,1,0,0,0,1,0,...,0.0,0.0,67.0,67.0,15.0,0.0,0.0,0.0,0.0,43.0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,0,1,0,0,0,1,0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,43.0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,0,1,0,0,0,1,0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,0,1,0,0,0,1,0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,0,1,0,0,0,1,0,...,0.0,0.0,65.0,65.0,14.0,0.0,0.0,0.0,0.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,0,1,0,0,0,1,0,...,0.0,0.0,34.0,34.0,7.0,0.0,0.0,0.0,0.0,26.0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,0,1,0,0,0,1,0,...,0.0,0.0,33.0,33.0,6.0,0.0,0.0,0.0,0.0,26.0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,0,1,0,0,0,1,0,...,0.0,0.0,34.0,34.0,6.0,0.0,0.0,0.0,0.0,20.0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,0,1,0,0,0,1,0,...,0.0,0.0,33.0,33.0,5.0,0.0,0.0,0.0,0.0,20.0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,0,1,0,0,0,1,0,...,0.0,0.0,32.0,32.0,4.0,0.0,0.0,0.0,0.0,20.0

In [91]:
df.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Train/All_fingerprints_train_RRCK.csv',index=False)

In [92]:
df_test_morgan = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/morgan_fp_test_RRCK.csv')
df_test_morganCount = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/count_morgan_fp_test_RRCK.csv')
df_test_AP2d = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/AtomPairs2D_test_RRCK.csv')
df_test_AP2dCount = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/AtomPairs2DCount_test_RRCK.csv')
df_test_EState = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/EState_test_RRCK.csv')
df_test_Extended = pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Extended_test_RRCK.csv')
df_test_fp= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Fingerprinter_test_RRCK.csv')
df_test_graph= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Graphonly_test_RRCK.csv')
df_test_kr= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/KlekotaRoth_test_RRCK.csv')
df_test_krcount= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/KlekotaRothCount_test_RRCK.csv')
df_test_maccs= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/MACCS_test_RRCK.csv')
df_test_pubchem= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/PubChem_test_RRCK.csv')
df_test_Substr= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/Substructure_test_RRCK.csv')
df_test_Substrcount= pd.read_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/SubstructureCount_test_RRCK.csv')

df = df_test_morgan.merge(df_test_morganCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2d, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_AP2dCount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_EState, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Extended, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_fp, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_graph, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_kr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_krcount, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_maccs, on=['ID', 'SMILES', 'Permeability'], how='inner')
df = df.merge(df_test_pubchem, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substr, on=['ID', 'SMILES', 'Permeability'], how='inner').merge(df_test_Substrcount, on=['ID', 'SMILES', 'Permeability'], how='inner')
df

,ID,SMILES,Permeability,Morgan_fp_0,Morgan_fp_1,Morgan_fp_2,Morgan_fp_3,Morgan_fp_4,Morgan_fp_5,Morgan_fp_6,...,SubFPC298,SubFPC299,SubFPC300,SubFPC301,SubFPC302,SubFPC303,SubFPC304,SubFPC305,SubFPC306,SubFPC307
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,0,1,0,0,0,1,0,...,0.0,0.0,67.0,67.0,15.0,0.0,0.0,0.0,0.0,43.0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,0,1,0,0,0,1,0,...,0.0,0.0,66.0,66.0,15.0,0.0,0.0,0.0,0.0,42.0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,0,0,0,0,0,1,0,...,0.0,0.0,54.0,54.0,12.0,0.0,0.0,0.0,0.0,36.0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,0,0,0,0,0,1,0,...,0.0,0.0,50.0,50.0,8.0,0.0,0.0,0.0,0.0,36.0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,0,0,0,0,0,1,0,...,0.0,0.0,49.0,49.0,11.0,0.0,0.0,0.0,0.0,33.0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,0,1,0,0,0,1,0,...,0.0,0.0,48.0,48.0,10.0,0.0,0.0,0.0,0.0,34.0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,0,0,0,0,0,1,0,...,0.0,0.0,47.0,47.0,13.0,0.0,0.0,0.0,0.0,30.0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,0,0,0,0,0,1,0,...,0.0,0.0,37.0,37.0,14.0,0.0,0.0,0.0,0.0,39.0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,0,0,0,0,0,1,0,...,0.0,0.0,48.0,48.0,16.0,0.0,0.0,0.0,0.0,29.0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,0,0,0,0,0,1,0,...,0.0,0.0,37.0,37.0,14.0,0.0,0.0,0.0,0.0,39.0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,10.0,0.0,0.0,0.0,0.0,40.0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,0,1,0,0,0,1,0,...,0.0,0.0,36.0,36.0,8.0,0.0,0.0,0.0,0.0,39.0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,0,1,1,0,0,1,0,...,0.0,0.0,47.0,47.0,10.0,0.0,0.0,0.0,0.0,27.0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,0,1,1,0,0,1,0,...,0.0,0.0,46.0,46.0,9.0,0.0,0.0,0.0,0.0,27.0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,0,0,0,0,0,1,0,...,0.0,0.0,42.0,42.0,16.0,0.0,0.0,0.0,0.0,26.0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,0,1,0,0,0,1,0,...,0.0,0.0,47.0,47.0,10.0,0.0,0.0,0.0,0.0,25.0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,0,1,1,0,0,1,0,...,0.0,0.0,48.0,48.0,10.0,0.0,0.0,0.0,0.0,28.0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,0,1,0,0,0,1,0,...,0.0,0.0,45.0,45.0,10.0,1.0,0.0,0.0,0.0,26.0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,0,1,0,0,0,1,0,...,0.0,0.0,42.0,42.0,13.0,0.0,0.0,0.0,0.0,28.0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,7.0,0.0,0.0,0.0,0.0,30.0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,0,1,0,0,0,1,0,...,0.0,0.0,41.0,41.0,12.0,0.0,0.0,0.0,0.0,27.0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,0,0,0,0,0,1,0,...,0.0,0.0,41.0,41.0,13.0,0.0,0.0,0.0,0.0,26.0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,0,1,1,0,0,1,0,...,0.0,0.0,44.0,44.0,10.0,0.0,0.0,0.0,0.0,28.0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,27.0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,0,1,0,0,0,1,0,...,0.0,0.0,43.0,43.0,13.0,0.0,0.0,0.0,0.0,22.0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,9.0,0.0,0.0,0.0,0.0,27.0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,10.0,0.0,0.0,0.0,0.0,26.0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,0,1,0,0,0,1,0,...,0.0,0.0,35.0,35.0,10.0,0.0,0.0,0.0,0.0,23.0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,0,1,0,0,0,1,0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,0,1,0,0,0,1,0,...,0.0,0.0,40.0,40.0,10.0,0.0,0.0,0.0,0.0,28.0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,8.0,0.0,0.0,0.0,0.0,27.0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,0,1,0,0,0,1,0,...,0.0,0.0,39.0,39.0,10.0,0.0,0.0,0.0,0.0,28.0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,0,1,0,0,0,1,0,...,0.0,0.0,35.0,35.0,8.0,0.0,0.0,0.0,0.0,26.0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,0,1,0,0,0,1,0,...,0.0,0.0,38.0,38.0,8.0,0.0,0.0,0.0,0.0,22.0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,0,1,0,0,0,1,0,...,0.0,0.0,35.0,35.0,6.0,0.0,0.0,0.0,0.0,21.0

In [93]:
df.to_csv('/home/users/akshay/PCPpred/RRCK/features/Fingerprints/Test/All_fingerprints_test_RRCK.csv',index=False)

In [94]:
#Descriptors
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Descriptors, Descriptors3D
from rdkit.ML.Descriptors import MoleculeDescriptors
from tqdm import tqdm

In [95]:
calc = MoleculeDescriptors.MolecularDescriptorCalculator([desc[0] for desc in Chem.Descriptors._descList])

def calculate_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None 
    return calc.CalcDescriptors(mol)

In [96]:
#2D RDKit train dataset descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
train_2d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_2d_rdkit.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Train_2d_RDKit_des_RRCK.csv',index=False)
print("Shape: ",train_2d_rdkit.shape, '\n')
train_2d_rdkit

Shape:  (140, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,15.193873,15.193873,0.130769,-1.621791,0.147476,26.802326,1216.662,...,0,0,0,0,0,0,0,0,0,0
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,15.152762,15.152762,0.128114,-1.816236,0.134993,26.372093,1214.646,...,0,0,0,0,0,0,0,0,0,0
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,15.129540,15.129540,0.022871,-1.609940,0.147925,26.905882,1202.635,...,0,0,0,0,0,0,0,0,0,0
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,15.028142,15.028142,0.097424,-1.231351,0.116062,27.411765,1202.635,...,0,0,0,0,0,0,0,0,0,0
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,15.068092,15.068092,0.128760,-1.611421,0.157205,27.083333,1188.608,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,13.851851,13.851851,0.023647,-1.031406,0.304960,27.600000,626.799,...,0,0,0,0,0,0,0,0,0,0
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,13.805528,13.805528,0.023859,-1.030988,0.318688,27.954545,612.772,...,0,0,0,0,0,0,0,0,0,0
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,13.850263,13.850263,0.054388,-0.925132,0.468423,29.209302,606.809,...,0,0,0,0,0,0,0,0,0,0
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,13.811409,13.811409,0.054806,-0.925415,0.488135,29.619048,592.782,...,0,0,0,0,0,0,0,0,0,0
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,13.765086,13.765086,0.055018,-0.926897,0.500804,30.048780,578.755,...,0,0,0,0,0,0,0,0,0,0

In [97]:
#2D RDKit test dataset descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.GetDescriptorNames()))

descriptor_df = pd.DataFrame(descriptor_data, columns=calc.GetDescriptorNames())
test_2d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_2d_rdkit.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Test_2d_RDKit_des_RRCK.csv',index=False)
print("Shape: ",test_2d_rdkit.shape, '\n')
test_2d_rdkit

Shape:  (35, 220)

,ID,SMILES,Permeability,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,15.144490,15.144490,0.113131,-1.744209,0.128505,27.116279,1218.634,...,0,0,0,0,0,0,0,0,0,0
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,15.129540,15.129540,0.022871,-1.609940,0.147925,26.905882,1202.635,...,0,0,0,0,0,0,0,0,0,0
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,14.943135,14.943135,0.009186,-1.218040,0.319427,27.500000,1095.438,...,0,0,0,0,0,0,0,0,1,0
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,14.843366,14.843366,0.011626,-1.216334,0.396119,28.337838,1039.330,...,0,0,0,0,0,0,0,0,0,0
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,14.986472,14.986472,0.005159,-1.183490,0.343286,27.394366,996.305,...,0,0,0,0,0,0,0,0,2,0
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,15.005167,15.005167,0.011136,-1.161318,0.363344,26.720588,953.280,...,0,0,0,0,0,0,0,0,0,0
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,14.929116,14.929116,0.022583,-1.148701,0.304153,26.582090,939.253,...,0,0,0,0,0,0,0,0,0,0
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,14.694489,14.694489,0.002536,-1.355433,0.153787,21.769231,914.089,...,0,0,0,0,0,1,0,0,0,0
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,14.686202,14.686202,0.009566,-1.067138,0.175293,25.412698,899.213,...,1,0,0,0,0,0,0,0,4,0
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,14.705070,14.705070,0.072633,-1.128302,0.149796,22.047619,876.137,...,0,0,0,0,0,1,0,0,0,0
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,14.778628,14.778628,0.047935,-1.135289,0.281092,24.412698,864.101,...,0,0,0,0,0,0,0,0,0,0
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,14.654702,14.654702,0.010614,-1.196147,0.265502,24.278689,838.019,...,0,0,0,0,0,0,0,0,0,0
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,14.877726,14.877726,0.003145,-1.061357,0.293685,28.118644,821.117,...,0,0,0,0,0,0,0,0,0,0
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,14.838872,14.838872,0.002727,-1.060863,0.323959,28.396552,807.090,...,0,0,0,0,0,0,0,0,0,0
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,14.334852,14.334852,0.040927,-1.023896,0.179230,24.053571,802.096,...,1,0,0,0,0,0,0,0,4,0
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,14.399084,14.399084,0.000047,-1.294682,0.260642,29.071429,793.104,...,0,0,0,0,0,0,0,0,0,0
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,14.663245,14.663245,0.009622,-1.116681,0.202888,28.210526,793.063,...,0,0,0,0,0,0,0,0,0,0
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,14.467265,14.467265,0.023223,-1.277705,0.296709,28.571429,789.116,...,0,0,0,0,0,0,0,0,0,0
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,14.614770,14.614770,0.002135,-1.078423,0.221482,25.232143,784.056,...,0,0,0,0,0,0,0,0,1,0
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,14.720048,14.720048,0.045076,-1.033591,0.398562,27.454545,778.033,...,0,0,0,0,0,1,0,0,0,0
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,14.546251,14.546251,0.005632,-1.082485,0.233964,25.472727,770.029,...,0,0,0,0,0,0,0,0,1,0
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,14.160363,14.160363,0.044469,-1.015622,0.185524,25.547170,757.999,...,1,0,0,0,0,0,0,0,3,0
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,14.325039,14.325039,0.008354,-1.122769,0.211352,27.166667,752.998,...,0,0,0,0,0,0,0,0,0,0
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,14.419488,14.419488,0.007170,-1.069250,0.332485,24.679245,740.987,...,0,0,0,0,0,0,0,0,0,0
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,14.415313,14.415313,0.001350,-0.943068,0.275707,25.134615,735.024,...,0,0,0,0,0,0,0,0,0,0
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,14.346221,14.346221,0.036362,-1.360212,0.295672,26.250000,728.932,...,0,0,0,0,0,0,0,0,0,0
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,14.381097,14.381097,0.006916,-0.979013,0.334247,23.480769,726.960,...,0,0,0,0,0,0,0,0,0,0
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,14.366527,14.366527,0.004921,-0.835156,0.393409,19.725490,712.933,...,0,0,0,0,0,0,0,0,0,0
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,14.322183,14.322183,0.000719,-1.098513,0.215270,26.000000,712.933,...,0,0,0,0,0,0,0,0,0,0
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,14.322183,14.322183,0.000719,-1.098513,0.215270,26.000000,712.933,...,0,0,0,0,0,0,0,0,0,0
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,14.375946,14.375946,0.041143,-0.968617,0.426120,27.588235,708.945,...,0,0,0,0,0,0,0,0,0,0
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,14.149007,14.149007,0.013343,-1.040266,0.252518,26.280000,696.934,...,0,0,0,0,0,0,0,0,0,0
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,14.285259,14.285259,0.023988,-0.981187,0.432506,27.000000,682.907,...,0,0,0,0,0,0,0,0,0,0
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,14.310395,14.310395,0.043619,-0.929433,0.409958,28.000000,662.917,...,0,0,0,0,0,0,0,0,0,0
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,13.929912,13.929912,0.048761,-0.934108,0.462849,28.954545,620.836,...,0,0,0,0,0,0,0,0,0,0

In [98]:
from mordred import Calculator, descriptors
calc = Calculator(descriptors, ignore_3D=True)

def calculate_mordred_descriptors(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None  # Return None if the SMILES is invalid
    return calc(mol)

In [99]:
print('start')
#2D Mordred train descriptors
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
descriptor_data = []
for smiles in df_train['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
train_mordred_2d = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
train_mordred_2d.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Train_2d_Mordred_desc_RRCK.csv', index=False)
print('Shape: ',train_mordred_2d.shape)
train_mordred_2d

start

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (140, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,100.888651,2.446436,4.892748,...,11.228478,126.484444,1215.857018,6.109834,38268,152,418.0,484.0,44.111111,19.277778
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,100.888651,2.446436,4.892748,...,11.228478,126.484444,1213.841368,6.161631,38268,152,418.0,484.0,44.111111,19.277778
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,100.134733,2.444935,4.889759,...,11.208585,125.402718,1201.841368,6.131844,37337,150,412.0,477.0,43.250000,19.166667
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,100.268636,2.427280,4.854560,...,11.184019,125.341576,1201.841368,6.131844,37826,148,410.0,473.0,42.638889,19.277778
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,98.550044,2.444219,4.888335,...,11.198475,124.353468,1187.825718,6.154537,36408,148,408.0,472.0,43.000000,18.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,55.201917,2.419901,4.786578,...,10.503834,95.786335,626.379183,6.593465,6693,72,224.0,257.0,18.027778,10.055556
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,53.640751,2.419606,4.784653,...,10.483550,94.692583,612.363533,6.656125,6341,70,220.0,252.0,17.777778,9.722222
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,52.045329,2.439503,4.844153,...,10.570008,93.767368,606.410483,6.251654,5725,76,214.0,251.0,20.250000,9.638889
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,50.591075,2.439146,4.842060,...,10.560671,92.694207,592.394833,6.302073,5381,75,210.0,247.0,20.000000,9.388889
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,49.505456,2.438018,4.835411,...,10.538608,91.594554,578.379183,6.355815,5079,73,206.0,242.0,19.750000,9.055556

In [100]:
#2D Mordred test descriptors
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
descriptor_data = []
for smiles in df_test['SMILES']:
    descriptors = calculate_mordred_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append([np.nan] * len(calc.descriptors))

descriptor_df = pd.DataFrame(descriptor_data, columns=[desc.__class__.__name__ for desc in calc.descriptors])
test_mordred_2d = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
test_mordred_2d.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Test_2d_Mordred_desc_RRCK.csv', index=False)
print('Shape: ',test_mordred_2d.shape)
test_mordred_2d

/home/users/akshay/anaconda3/envs/py312/lib/python3.12/site-packages/numpy/core/fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

Shape:  (35, 1616)

,ID,SMILES,Permeability,ABCIndex,ABCGGIndex,AcidicGroupCount,BasicGroupCount,AdjacencyMatrix,AdjacencyMatrix,AdjacencyMatrix,...,WalkCount,WalkCount,Weight,Weight,WienerIndex,WienerIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex,ZagrebIndex
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,100.888651,2.446436,4.892748,...,11.228478,126.484444,1217.836283,6.181910,38268,152,418.0,484.0,44.111111,19.277778
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,100.134733,2.444935,4.889759,...,11.208585,125.402718,1201.841368,6.131844,37337,150,412.0,477.0,43.250000,19.166667
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,96.282174,2.460904,4.898232,...,11.232960,131.870970,1094.710354,6.364595,28969,148,388.0,464.0,36.055556,18.000000
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,91.172927,2.459349,4.893348,...,11.208477,127.699425,1038.647754,6.491548,25441,143,372.0,447.0,35.055556,16.916667
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,87.929966,2.459011,4.889438,...,11.129422,124.389878,995.641940,6.382320,22326,133,354.0,422.0,32.472222,16.250000
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,82.784106,2.466654,4.910608,...,11.091041,121.222371,952.636126,6.267343,19257,124,344.0,406.0,32.333333,15.000000
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,83.484783,2.465318,4.908864,...,11.066935,120.067649,938.620476,6.299466,18483,125,332.0,396.0,29.638889,15.583333
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,82.177160,2.435750,4.819009,...,10.908540,119.586829,913.400825,7.486892,18371,100,334.0,383.0,21.673611,14.208333
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,78.841373,2.449488,4.853049,...,10.792633,115.248549,898.535032,6.558650,16763,102,302.0,347.0,24.361111,14.777778
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,80.291949,2.435508,4.818260,...,10.844022,117.353041,875.440404,7.060003,16811,95,322.0,368.0,19.951389,13.847222
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,80.009058,2.447582,4.854570,...,10.925309,115.690579,863.494547,6.746051,15977,106,320.0,373.0,23.194444,14.055556
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,76.824453,2.446416,4.849177,...,10.898053,113.561453,837.442512,6.978688,15071,102,312.0,363.0,22.694444,13.444444
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,75.030552,2.453245,4.878329,...,10.894645,111.451905,820.546249,6.263712,13242,101,302.0,354.0,21.583333,13.138889
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,73.576426,2.452878,4.876711,...,10.887904,110.399974,806.530599,6.301020,12711,100,298.0,350.0,21.333333,12.888889
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,69.504133,2.385416,4.768577,...,10.601000,93.849281,801.482268,6.516116,12212,89,262.0,297.0,22.277778,13.277778
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.106765,2.433530,4.834709,...,10.764160,107.913804,792.572463,6.004337,11789,93,276.0,317.0,26.555556,12.388889
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,71.793798,2.426303,4.807978,...,10.764118,109.080516,792.514949,6.340120,12506,90,290.0,333.0,19.861111,12.555556
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.093178,2.432345,4.836354,...,10.764160,107.913804,788.577549,5.974072,11786,93,276.0,317.0,26.555556,12.388889
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,68.265699,2.450533,4.872487,...,10.787193,107.980387,783.525848,6.268207,11648,94,278.0,322.0,23.833333,12.555556
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,69.724357,2.468021,4.894327,...,10.929332,110.616713,777.424754,6.819515,10928,97,290.0,346.0,21.284722,12.083333
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,1,67.133329,2.450525,4.872457,...,10.781973,106.926610,769.510197,6.307461,11008,93,274.0,318.0,23.583333,12.305556
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.862333,2.415786,4.770523,...,10.563362,104.281698,757.419668,6.762676,10741,82,254.0,289.0,19.416667,12.388889
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,66.570060,2.423031,4.800221,...,10.695688,105.748529,752.483648,6.376980,10857,85,272.0,311.0,20.611111,11.888889
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,63.904799,2.446985,4.856035,...,10.737070,104.751389,740.483648,6.328920,9989,88,266.0,307.0,23.083333,11.666667
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,61.918466,2.439051,4.851143,...,10.652944,103.440388,734.530599,6.020743,9672,84,254.0,290.0,23.722222,11.583333
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,63.127463,2.449972,4.870575,...,10.763610,103.757713,728.447263,6.503993,9414,90,262.0,306.0,22.833333,11.555556
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,62.730767,2.436298,4.835279,...,10.687138,103.583529,726.467998,6.372526,9648,84,260.0,298.0,22.222222,11.444444
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,61.347217,2.424840,4.802272,...,10.622229,102.392896,712.452348,6.418490,9274,80,254.0,289.0,21.361111,11.222222
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,61.347217,2.424840,4.802272,...,10.622229,102.392896,712.452348,6.418490,9274,80,254.0,289.0,21.361111,11.222222
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,61.347217,2.424840,4.802272,...,10.622229,102.392896,712.452348,6.418490,9274,80,254.0,289.0,21.361111,11.222222
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,63.288991,2.460618,4.875306,...,10.769095,104.792112,708.457434,6.382499,8878,87,262.0,308.0,20.472222,11.222222
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.264895,2.421940,4.795383,...,10.588477,101.254858,696.457434,6.331431,8748,78,248.0,282.0,20.500000,11.055556
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,60.134361,2.448576,4.864839,...,10.706453,100.458005,682.441784,6.377961,8021,86,246.0,289.0,20.861111,11.055556
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,56.045508,2.443546,4.859796,...,10.644162,98.177432,662.473084,6.077735,7129,81,234.0,272.0,22.472222,10.388889
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,0,52.776707,2.440186,4.848090,...,10.592903,94.894677,620.426134,6.204261,6071,77,220.0,257.0,21.111111,9.722222

In [101]:
#RDKit 3d descriptors
def generate_3d_descriptors(smiles):
    # Convert SMILES to a molecule object
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles}")
        return None
    
    # Add hydrogens
    mol = Chem.AddHs(mol)
    
    # Generate 3D coordinates for the molecule
    AllChem.EmbedMolecule(mol)
    
    try:
        descriptors = Descriptors3D.CalcMolDescriptors3D(mol)
        return descriptors
    except Exception as e:
        print(f"Error calculating descriptors for SMILES '{smiles}': {e}")
        return None

In [102]:
df_train = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.csv")
descriptor_data = []
for smiles in tqdm(df_train['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors =generate_3d_descriptors(smiles) 
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

3d_descriptors: 100%|██████████| 140/140 [01:20<00:00,  1.73smiles/s]

In [103]:
descriptor_df = pd.DataFrame(descriptor_data)
descriptor_df

,PMI1,PMI2,PMI3,NPR1,NPR2,RadiusOfGyration,InertialShapeFactor,Eccentricity,Asphericity,SpherocityIndex,PBF
0,25557.550768,38719.861789,59078.304374,0.432605,0.655399,7.119995,0.000026,0.901584,0.224932,0.159022,1.434147
1,25195.527353,38098.222481,54940.535676,0.458596,0.693445,6.976408,0.000028,0.888645,0.190983,0.276159,1.867453
2,24627.941709,37770.489101,52166.145232,0.472106,0.724042,6.901496,0.000029,0.881542,0.173457,0.300184,1.966338
3,27053.583076,35398.003591,54685.502768,0.494712,0.647301,6.978552,0.000024,0.869057,0.175665,0.268855,1.757097
4,25621.505581,37274.558430,58032.092029,0.441506,0.642309,7.132297,0.000025,0.897258,0.221165,0.149807,1.434163
...,...,...,...,...,...,...,...,...,...,...,...
135,7624.940741,7922.483693,14006.527516,0.544385,0.565628,4.855440,0.000074,0.838836,0.178213,0.186149,1.117525
136,6232.953683,8749.353631,12635.210560,0.493300,0.692458,4.747094,0.000111,0.869859,0.163679,0.271461,1.309583
137,5787.868928,7241.500975,11269.076352,0.513606,0.642599,4.474538,0.000111,0.858026,0.163878,0.237706,1.199945
138,5518.344689,6698.311541,10323.461033,0.534544,0.648844,4.360292,0.000118,0.845141,0.148106,0.299445,1.277044
139,4660.905348,6970.443953,9546.416992,0.488236,0.730163,4.277379,0.000157,0.872712,0.159813,0.348263,1.364826

In [104]:
num_columns = descriptor_df.shape[1]
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
train_3d_rdkit = pd.concat([df_train[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , train_3d_rdkit.shape)
train_3d_rdkit.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Train_3d_RDKit_desc_RRCK.csv',index=False)
print('Shape after: ',train_3d_rdkit.shape)
train_3d_rdkit

Shape before: (140, 14)
Shape after:  (140, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,2358,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C(...,-6.13,25557.550768,38719.861789,59078.304374,0.432605,0.655399,7.119995,0.000026,0.901584,0.224932,0.159022,1.434147
1,2359,C/C=C/C[C@@H](C)C(=O)[C@H]1C(=O)N[C@@H](C(C)C)...,-6.66,25195.527353,38098.222481,54940.535676,0.458596,0.693445,6.976408,0.000028,0.888645,0.190983,0.276159,1.867453
2,5669,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.76,24627.941709,37770.489101,52166.145232,0.472106,0.724042,6.901496,0.000029,0.881542,0.173457,0.300184,1.966338
3,2360,C/C=C/C[C@@H](C)[C@H]1OC(=O)[C@H](C(C)C)N(C)C(...,-6.78,27053.583076,35398.003591,54685.502768,0.494712,0.647301,6.978552,0.000024,0.869057,0.175665,0.268855,1.757097
4,2353,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](C)...,-5.87,25621.505581,37274.558430,58032.092029,0.441506,0.642309,7.132297,0.000025,0.897258,0.221165,0.149807,1.434163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,2335,CC[C@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@H](Cc2cccc...,-5.53,7624.940741,7922.483693,14006.527516,0.544385,0.565628,4.855440,0.000074,0.838836,0.178213,0.186149,1.117525
136,2334,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.58,6232.953683,8749.353631,12635.210560,0.493300,0.692458,4.747094,0.000111,0.869859,0.163679,0.271461,1.309583
137,2305,CCC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)...,-4.85,5787.868928,7241.500975,11269.076352,0.513606,0.642599,4.474538,0.000111,0.858026,0.163878,0.237706,1.199945
138,2304,CC[C@@H]1C(=O)N(C)[C@@H](C)C(=O)N[C@@H](CC(C)C...,-5.51,5518.344689,6698.311541,10323.461033,0.534544,0.648844,4.360292,0.000118,0.845141,0.148106,0.299445,1.277044
139,2303,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-5.31,4660.905348,6970.443953,9546.416992,0.488236,0.730163,4.277379,0.000157,0.872712,0.159813,0.348263,1.364826

In [105]:
df_test = pd.read_csv("/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.csv")
descriptor_data = []
for smiles in tqdm(df_test['SMILES'],desc='3d_descriptors', unit='smiles'):
    descriptors = generate_3d_descriptors(smiles)
    if descriptors is not None:
        descriptor_data.append(descriptors)
    else:
        descriptor_data.append({'PMI1': np.nan,
  'PMI2': np.nan,
  'PMI3': np.nan,
  'NPR1': np.nan,
  'NPR2': np.nan,
  'RadiusOfGyration': np.nan,
  'InertialShapeFactor': np.nan,
  'Eccentricity': np.nan,
  'Asphericity': np.nan,
  'SpherocityIndex': np.nan,
  'PBF': np.nan})

descriptor_data

3d_descriptors: 100%|██████████| 35/35 [00:19<00:00,  1.81smiles/s]

[{'PMI1': 25465.77229741613,
  'PMI2': 41635.23635727709,
  'PMI3': 57764.58127438965,
  'NPR1': 0.4408544429059432,
  'NPR2': 0.7207744856576391,
  'RadiusOfGyration': 7.157638221080254,
  'InertialShapeFactor': 2.830365705149936e-05,
  'Eccentricity': 0.8975786094655388,
  'Asphericity': 0.20072845751791388,
  'SpherocityIndex': 0.2746179634758924,
  'PBF': 1.8948536483847755},
 {'PMI1': 23425.027477352316,
  'PMI2': 36819.01451869982,
  'PMI3': 51958.19174897247,
  'NPR1': 0.45084377821550287,
  'NPR2': 0.7086277116144627,
  'RadiusOfGyration': 6.829970600182565,
  'InertialShapeFactor': 3.025088070012191e-05,
  'Eccentricity': 0.8926028723034508,
  'Asphericity': 0.1942492485392814,
  'SpherocityIndex': 0.2791227585288796,
  'PBF': 1.8494523457490875},
 {'PMI1': 19228.307860212684,
  'PMI2': 26584.788949910257,
  'PMI3': 41557.971167824624,
  'NPR1': 0.4626863949292066,
  'NPR2': 0.6397037247692439,
  'RadiusOfGyration': 6.315022804780913,
  'InertialShapeFactor': 3.3268851810560103e-05,
  'Eccentricity': 0.8865220245134434,
  'Asphericity': 0.20355201408850154,
  'SpherocityIndex': 0.19040207748532303,
  'PBF': 1.4027169037595946},
 {'PMI1': 18709.773342070992,
  'PMI2': 27134.585977822495,
  'PMI3': 41923.42092784172,
  'NPR1': 0.4462845094219318,
  'NPR2': 0.647241693957331,
  'RadiusOfGyration': 6.497941959779899,
  'InertialShapeFactor': 3.4593775249106656e-05,
  'Eccentricity': 0.8948911311718458,
  'Asphericity': 0.21512159701100894,
  'SpherocityIndex': 0.17647948779508946,
  'PBF': 1.4038793620150283},
 {'PMI1': 15494.460333200677,
  'PMI2': 25480.222142659917,
  'PMI3': 35133.289000402954,
  'NPR1': 0.44101935156207456,
  'NPR2': 0.7252444296452768,
  'RadiusOfGyration': 6.180219793366349,
  'InertialShapeFactor': 4.680669181431655e-05,
  'Eccentricity': 0.8974975941738047,
  'Asphericity': 0.19977156292234524,
  'SpherocityIndex': 0.2637026431025132,
  'PBF': 1.586356809781902},
 {'PMI1': 12652.784434557363,
  'PMI2': 21781.115461433397,
  'PMI3': 29110.712318664595,
  'NPR1': 0.43464358742073506,
  'NPR2': 0.7482165061096165,
  'RadiusOfGyration': 5.773167103415649,
  'InertialShapeFactor': 5.913453358662169e-05,
  'Eccentricity': 0.900602549360168,
  'Asphericity': 0.20204116763983457,
  'SpherocityIndex': 0.3004523623414111,
  'PBF': 1.566055432420201},
 {'PMI1': 14906.294394610353,
  'PMI2': 19726.009636551644,
  'PMI3': 30917.986108038793,
  'NPR1': 0.4821237173249994,
  'NPR2': 0.6380108189330872,
  'RadiusOfGyration': 5.907191034619728,
  'InertialShapeFactor': 4.280143689928543e-05,
  'Eccentricity': 0.8761031452932492,
  'Asphericity': 0.1884474233381038,
  'SpherocityIndex': 0.22812986586229664,
  'PBF': 1.409108262594617},
 {'PMI1': 14125.144457417142,
  'PMI2': 25108.70624902147,
  'PMI3': 32442.299465548913,
  'NPR1': 0.4353928263444118,
  'NPR2': 0.773949647918295,
  'RadiusOfGyration': 6.261495836640699,
  'InertialShapeFactor': 5.4792335062590635e-05,
  'Eccentricity': 0.9002405716072925,
  'Asphericity': 0.19851730003793158,
  'SpherocityIndex': 0.306027954399931,
  'PBF': 1.6077858959902274},
 {'PMI1': 12577.621435547526,
  'PMI2': 20415.61093857065,
  'PMI3': 26519.2175102789,
  'NPR1': 0.47428327893432054,
  'NPR2': 0.7698421316789427,
  'RadiusOfGyration': 5.752513255660024,
  'InertialShapeFactor': 6.12072907126283e-05,
  'Eccentricity': 0.8803722913195924,
  'Asphericity': 0.16548751813541507,
  'SpherocityIndex': 0.3385831680373399,
  'PBF': 1.7327094521890487},
 {'PMI1': 11732.937028301161,
  'PMI2': 20116.819627012483,
  'PMI3': 25872.34890055097,
  'NPR1': 0.45349330566778573,
  'NPR2': 0.7775412933838443,
  'RadiusOfGyration': 5.739447317386027,
  'InertialShapeFactor': 6.62699622019898e-05,
  'Eccentricity': 0.8912596825361866,
  'Asphericity': 0.18208463727335916,
  'SpherocityIndex': 0.3828890604717082,
  'PBF': 1.762875661278937},
 {'PMI1': 10266.273214124167,
  'PMI2': 19616.437504393438,
  'PMI3': 26001.300946462903,
  'NPR1': 0.39483690586338693,
  'NPR2': 0.7544406160593271,
  'RadiusOfGyration': 5.686519537542908,
  'InertialShapeFactor': 7.348729186569673e-05,
  'Eccentricity': 0.9187512273560383,
  'Asphericity': 0.24065348226526825,
  'SpherocityIndex': 0.27765679933452725,
  'PBF': 1.446506475946901},
 {'PMI1': 9808.644671360298,
  'PMI2': 17318.156622314407,
  'PMI3': 20384.624039397917,
  'NPR1': 0.48117859090277376,
  'NPR2': 0.8495695868044039,
  'RadiusOfGyration': 5.324233567792877,
  'InertialShapeFactor': 8.661437081975389e-05,
  'Eccentricity': 0.8766225890637436,
  'Asphericity': 0.15739559212949955,
  'SpherocityIndex': 0.40804210000425306,
  'PBF': 1.7586739303185062},
 {'PMI1': 10024.864053905041,
  'PMI2': 15376.444255405866,
  'PMI3': 18777.557490935935,
  'NPR1': 0.5338747629314471,
  'NPR2': 0.8188735016696495,
  'RadiusOfGyration': 5.186683666621811,
  'InertialShapeFactor': 8.16842500074272e-05,
  'Eccentricity': 0.8455635620725926,
  'Asphericity': 0.11970313471049537,
  'SpherocityIndex': 0.5225929633075206,
  'PBF': 1.8700297677410291},
 {'PMI1': 9743.628585180213,
  'PMI2': 16537.59158930592,
  'PMI3': 23433.241972677075,
  'NPR1': 0.4158036944500119,
  'NPR2': 0.7057321222811844,
  'RadiusOfGyration': 5.549647409545077,
  'InertialShapeFactor': 7.243011329009228e-05,
  'Eccentricity': 0.9094543901052549,
  'Asphericity': 0.2274815183434996,
  'SpherocityIndex': 0.20161517324798683,
  'PBF': 1.27231193958387},
 {'PMI1': 9995.59199817343,
  'PMI2': 15392.146554914454,
  'PMI3': 20702.728428179675,
  'NPR1': 0.482815201525218,
  'NPR2': 0.7434839619479005,
  'RadiusOfGyration': 5.360155403205419,
  'InertialShapeFactor': 7.438118343403401e-05,
  'Eccentricity': 0.8757222625788174,
  'Asphericity': 0.16190305520537926,
  'SpherocityIndex': 0.33641123457069383,
  'PBF': 1.6360447111609637},
 {'PMI1': 10098.569836880433,
  'PMI2': 14107.357828207669,
  'PMI3': 21397.35022985712,
  'NPR1': 0.47195422463054515,
  'NPR2': 0.6593039641199475,
  'RadiusOfGyration': 5.361890765954885,
  'InertialShapeFactor': 6.528686485012359e-05,
  'Eccentricity': 0.8816230542887254,
  'Asphericity': 0.18933566803659915,
  'SpherocityIndex': 0.21724615792055846,
  'PBF': 1.3570989169745742},
 {'PMI1': 10566.583667565066,
  'PMI2': 16459.574684703297,
  'PMI3': 20204.58981603693,
  'NPR1': 0.522979370715959,
  'NPR2': 0.8146453273522478,
  'RadiusOfGyration': 5.45686953322248,
  'InertialShapeFactor': 7.709637788161029e-05,
  'Eccentricity': 0.8523453395223908,
  'Asphericity': 0.1269923138846717,
  'SpherocityIndex': 0.4875580974931408,
  'PBF': 1.9271717803034856},
 {'PMI1': 10723.120380648252,
  'PMI2': 14014.52437530419,
  'PMI3': 21446.755825908636,
  'NPR1': 0.4999879920157549,
  'NPR2': 0.6534566108303439,
  'RadiusOfGyration': 5.409563626571293,
  'InertialShapeFactor': 6.093903524664526e-05,
  'Eccentricity': 0.866032336486377,
  'Asphericity': 0.16977764535694087,
  'SpherocityIndex': 0.26508861871477246,
  'PBF': 1.4442386601327184},
 {'PMI1': 9134.080001919621,
  'PMI2': 15847.757858725983,
  'PMI3': 20863.258947252074,
  'NPR1': 0.43780696127163216,
  'NPR2': 0.7596012635798355,
  'RadiusOfGyration': 5.407019152671354,
  'InertialShapeFactor': 8.316122296062629e-05,
  'Eccentricity': 0.8990689988327367,
  'Asphericity': 0.19774006995194907,
  'SpherocityIndex': 0.359196760352143,
  'PBF': 1.638616249267011},
 {'PMI1': 10090.87313446227,
  'PMI2': 12354.63696351092,
  'PMI3': 15504.338681364927,
  'NPR1': 0.6508418928303441,
  'NPR2': 0.7968503021905916,
  'RadiusOfGyration': 4.9384540599614954,
  'InertialShapeFactor': 7.896742844473931e-05,
  'Eccentricity': 0.7592132971286889,
  'Asphericity': 0.06159024202155718,
  'SpherocityIndex': 0.6339626077950937,
  'PBF': 1.982655715491467},
 {'PMI1': 8790.920321230555,
  'PMI2': 13002.427406092831,
  'PMI3': 16253.514818361044,
  'NPR1': 0.5408627253533956,
  'NPR2': 0.7999763467409788,
  'RadiusOfGyration': 4.970394799043067,
  'InertialShapeFactor': 9.100029547634415e-05,
  'Eccentricity': 0.841110879922081,
  'Asphericity': 0.1160524749830127,
  'SpherocityIndex': 0.45316190474837875,
  'PBF': 1.7192018418001611},
 {'PMI1': 9490.619186483535,
  'PMI2': 13648.84678929963,
  'PMI3': 19660.48785417321,
  'NPR1': 0.48272551814979603,
  'NPR2': 0.6942272689536783,
  'RadiusOfGyration': 5.313397854864903,
  'InertialShapeFactor': 7.314878569170611e-05,
  'Eccentricity': 0.8757717020588247,
  'Asphericity': 0.1712564986284244,
  'SpherocityIndex': 0.28448908145844654,
  'PBF': 1.4532665337464041},
 {'PMI1': 8520.177192557161,
  'PMI2': 15320.309313969672,
  'PMI3': 22556.45947959836,
  'NPR1': 0.3777267084075586,
  'NPR2': 0.679198316909018,
  'RadiusOfGyration': 5.550508705657115,
  'InertialShapeFactor': 7.971645443035324e-05,
  'Eccentricity': 0.9259171311492143,
  'Asphericity': 0.27465424854224185,
  'SpherocityIndex': 0.1170315647990226,
  'PBF': 1.0031985432871187},
 {'PMI1': 8676.975276792351,
  'PMI2': 11089.452014012331,
  'PMI3': 17443.985236062515,
  'NPR1': 0.4974193201479074,
  'NPR2': 0.6357178055325768,
  'RadiusOfGyration': 5.010856321489572,
  'InertialShapeFactor': 7.32649091709277e-05,
  'Eccentricity': 0.8675102419819569,
  'Asphericity': 0.1777542751477352,
  'SpherocityIndex': 0.21988467415164148,
  'PBF': 1.265298897380761},
 {'PMI1': 9048.405962415194,
  'PMI2': 10501.768095562567,
  'PMI3': 15945.859999564096,
  'NPR1': 0.5674454662628762,
  'NPR2': 0.6585890065414878,
  'RadiusOfGyration': 4.913875608664142,
  'InertialShapeFactor': 7.278508604466921e-05,
  'Eccentricity': 0.8234109805059119,
  'Asphericity': 0.12591628205117816,
  'SpherocityIndex': 0.3745882850156504,
  'PBF': 1.516048712502185},
 {'PMI1': 8610.991975404038,
  'PMI2': 11841.724849033131,
  'PMI3': 18076.18864354008,
  'NPR1': 0.4763721017307132,
  'NPR2': 0.6551007561688083,
  'RadiusOfGyration': 5.140848790114335,
  'InertialShapeFactor': 7.607726938313284e-05,
  'Eccentricity': 0.8792437777389517,
  'Asphericity': 0.18713144516622693,
  'SpherocityIndex': 0.21873108161559865,
  'PBF': 1.2761747852915495},
 {'PMI1': 8529.317553287596,
  'PMI2': 12455.406511787332,
  'PMI3': 17586.62434724712,
  'NPR1': 0.48498889752101354,
  'NPR2': 0.7082317939961575,
  'RadiusOfGyration': 5.15065137566081,
  'InertialShapeFactor': 8.303498956058589e-05,
  'Eccentricity': 0.8745203081011623,
  'Asphericity': 0.16639686417331048,
  'SpherocityIndex': 0.28489055103460165,
  'PBF': 1.4823112652616737},
 {'PMI1': 8362.862827144867,
  'PMI2': 11136.81955973979,
  'PMI3': 16436.228236421863,
  'NPR1': 0.508806686476474,
  'NPR2': 0.6775775682562714,
  'RadiusOfGyration': 5.020245673782226,
  'InertialShapeFactor': 8.102220283428952e-05,
  'Eccentricity': 0.8608808023163435,
  'Asphericity': 0.1563552806282699,
  'SpherocityIndex': 0.33922189457923513,
  'PBF': 1.4659538435575716},
 {'PMI1': 8225.955641591217,
  'PMI2': 11564.36604261153,
  'PMI3': 16247.807202642432,
  'NPR1': 0.5062809731182313,
  'NPR2': 0.7117493393650547,
  'RadiusOfGyration': 5.027380547897571,
  'InertialShapeFactor': 8.652482099057064e-05,
  'Eccentricity': 0.8623685849208892,
  'Asphericity': 0.15003650064661928,
  'SpherocityIndex': 0.34829160912397183,
  'PBF': 1.5457615687813298},
 {'PMI1': 7625.504753821946,
  'PMI2': 12895.120129900968,
  'PMI3': 17092.561199961216,
  'NPR1': 0.4461300249045912,
  'NPR2': 0.7544287821494082,
  'RadiusOfGyration': 5.1360672856991005,
  'InertialShapeFactor': 9.893493040854566e-05,
  'Eccentricity': 0.8949681563489446,
  'Asphericity': 0.19086389374753132,
  'SpherocityIndex': 0.2650295451522719,
  'PBF': 1.3891147551800516},
 {'PMI1': 7560.694122150821,
  'PMI2': 11213.812039293229,
  'PMI3': 16609.65666998715,
  'NPR1': 0.455198699911277,
  'NPR2': 0.675138099606601,
  'RadiusOfGyration': 4.995548648809908,
  'InertialShapeFactor': 8.929578272828496e-05,
  'Eccentricity': 0.8903898829159522,
  'Asphericity': 0.19862661633531986,
  'SpherocityIndex': 0.23652730251140058,
  'PBF': 1.265086392597331},
 {'PMI1': 8319.860202636795,
  'PMI2': 10488.625286220995,
  'PMI3': 16163.827529272266,
  'NPR1': 0.5147209216115272,
  'NPR2': 0.6488949023507192,
  'RadiusOfGyration': 5.009003723550588,
  'InertialShapeFactor': 7.799348625413998e-05,
  'Eccentricity': 0.8573577857903784,
  'Asphericity': 0.1609717763322444,
  'SpherocityIndex': 0.2730926520932758,
  'PBF': 1.34160733975691},
 {'PMI1': 8405.004579127486,
  'PMI2': 8860.278527027103,
  'PMI3': 15644.27736489803,
  'NPR1': 0.5372574509568772,
  'NPR2': 0.5663590794489123,
  'RadiusOfGyration': 4.908686102401857,
  'InertialShapeFactor': 6.738355394301348e-05,
  'Eccentricity': 0.843418301551086,
  'Asphericity': 0.18214850905241567,
  'SpherocityIndex': 0.19197543007469262,
  'PBF': 1.1509707961114064},
 {'PMI1': 7051.834075399217,
  'PMI2': 9160.971460399302,
  'PMI3': 14927.399488626455,
  'NPR1': 0.47240874612970457,
  'NPR2': 0.6137017681733021,
  'RadiusOfGyration': 4.846365426801462,
  'InertialShapeFactor': 8.702725583323645e-05,
  'Eccentricity': 0.8813795871133846,
  'Asphericity': 0.20567889300653452,
  'SpherocityIndex': 0.15939264194464775,
  'PBF': 1.033241686896335},
 {'PMI1': 6158.886702598419,
  'PMI2': 7098.307150811411,
  'PMI3': 9745.810909179088,
  'NPR1': 0.6319522059265149,
  'NPR2': 0.7283444360823657,
  'RadiusOfGyration': 4.3041642977324015,
  'InertialShapeFactor': 0.00011825910611005054,
  'Eccentricity': 0.7750073608841478,
  'Asphericity': 0.07845893980134587,
  'SpherocityIndex': 0.5514477621409433,
  'PBF': 1.6478194772180603}]

In [106]:
descriptor_df = pd.DataFrame(descriptor_data)

In [107]:
num_columns = descriptor_df.shape[1]
print('num_columns',num_columns)
descriptor_df.columns = [f'3d_rdkit_{i+1}' for i in range(num_columns)]
print('descriptor_df.columns',descriptor_df.columns)
test_3d_rdkit = pd.concat([df_test[['ID','SMILES','Permeability']], descriptor_df], axis=1)
print('Shape before:' , test_3d_rdkit.shape)
test_3d_rdkit.to_csv('/home/users/akshay/PCPpred/RRCK/features/Descriptors/Test_3d_RDKit_desc_RRCK.csv',index=False)
print('Shape after: ',test_3d_rdkit.shape)
test_3d_rdkit

num_columns 11
descriptor_df.columns Index(['3d_rdkit_1', '3d_rdkit_2', '3d_rdkit_3', '3d_rdkit_4', '3d_rdkit_5',
       '3d_rdkit_6', '3d_rdkit_7', '3d_rdkit_8', '3d_rdkit_9', '3d_rdkit_10',
       '3d_rdkit_11'],
      dtype='object')
Shape before: (35, 14)
Shape after:  (35, 14)

,ID,SMILES,Permeability,3d_rdkit_1,3d_rdkit_2,3d_rdkit_3,3d_rdkit_4,3d_rdkit_5,3d_rdkit_6,3d_rdkit_7,3d_rdkit_8,3d_rdkit_9,3d_rdkit_10,3d_rdkit_11
0,2352,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H]([C...,-6.340,25465.772297,41635.236357,57764.581274,0.440854,0.720774,7.157638,0.000028,0.897579,0.200728,0.274618,1.894854
1,2357,C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...,-5.950,23425.027477,36819.014519,51958.191749,0.450844,0.708628,6.829971,0.000030,0.892603,0.194249,0.279123,1.849452
2,1883,CCCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@H](C)C...,-6.240,19228.307860,26584.788950,41557.971168,0.462686,0.639704,6.315023,0.000033,0.886522,0.203552,0.190402,1.402717
3,1882,CCC[C@H]1C(=O)N(C)[C@H](CC)C(=O)N(C)[C@@H](C)C...,-7.000,18709.773342,27134.585978,41923.420928,0.446285,0.647242,6.497942,0.000035,0.894891,0.215122,0.176479,1.403879
4,1879,CCCC[C@H]1C(=O)N(C)[C@H](C)C(=O)N2CCC[C@@H]2C(...,-6.210,15494.460333,25480.222143,35133.289000,0.441019,0.725244,6.180220,0.000047,0.897498,0.199772,0.263703,1.586357
5,1868,CC(C)C[C@H]1C(=O)N(C)[C@H](CC(C)C)C(=O)N2CCC[C...,-4.990,12652.784435,21781.115461,29110.712319,0.434644,0.748217,5.773167,0.000059,0.900603,0.202041,0.300452,1.566055
6,1876,CCC[C@H]1C(=O)N(C)[C@H](CCC)C(=O)N(C)[C@H](CCC...,-5.140,14906.294395,19726.009637,30917.986108,0.482124,0.638011,5.907191,0.000043,0.876103,0.188447,0.228130,1.409108
7,1859,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.210,14125.144457,25108.706249,32442.299466,0.435393,0.773950,6.261496,0.000055,0.900241,0.198517,0.306028,1.607786
8,5662,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@H](CCCC)N...,-6.100,12577.621436,20415.610939,26519.217510,0.474283,0.769842,5.752513,0.000061,0.880372,0.165488,0.338583,1.732709
9,1853,CC(C)(C)C[C@@H]1NC(=O)[C@@H](Cc2ccccc2)NC(=O)[...,-5.400,11732.937028,20116.819627,25872.348901,0.453493,0.777541,5.739447,0.000066,0.891260,0.182085,0.382889,1.762876
10,2368,CC[C@H](C)[C@@H]1NC(=O)[C@H](Cc2ccccc2)N(C)C(=...,-6.540,10266.273214,19616.437504,26001.300946,0.394837,0.754441,5.686520,0.000073,0.918751,0.240653,0.277657,1.446506
11,2370,CC(C)C[C@@H]1NC(=O)[C@H](C)NC(=O)[C@H](Cc2ccc(...,-6.230,9808.644671,17318.156622,20384.624039,0.481179,0.849570,5.324234,0.000087,0.876623,0.157396,0.408042,1.758674
12,2332,CCC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@...,-6.220,10024.864054,15376.444255,18777.557491,0.533875,0.818874,5.186684,0.000082,0.845564,0.119703,0.522593,1.870030
13,2331,CC[C@@H]1C(=O)N(C)[C@@H](CC2CCCCC2)C(=O)N[C@@H...,-5.900,9743.628585,16537.591589,23433.241973,0.415804,0.705732,5.549647,0.000072,0.909454,0.227482,0.201615,1.272312
14,5646,CCCC[C@@H]1NC(=O)[C@H](CCCC)N(C)C(=O)[C@H](CCC...,-5.820,9995.591998,15392.146555,20702.728428,0.482815,0.743484,5.360155,0.000074,0.875722,0.161903,0.336411,1.636045
15,967,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-5.440,10098.569837,14107.357828,21397.350230,0.471954,0.659304,5.361891,0.000065,0.881623,0.189336,0.217246,1.357099
16,2351,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.960,10566.583668,16459.574685,20204.589816,0.522979,0.814645,5.456870,0.000077,0.852345,0.126992,0.487558,1.927172
17,977,C/C1=C\[C@@H](CC(C)C)NC(=O)[C@@H]2CCCN2C(=O)[C...,-5.020,10723.120381,14014.524375,21446.755826,0.499988,0.653457,5.409564,0.000061,0.866032,0.169778,0.265089,1.444239
18,42,CNCCCC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@...,-6.630,9134.080002,15847.757859,20863.258947,0.437807,0.759601,5.407019,0.000083,0.899069,0.197740,0.359197,1.638616
19,930,CC[C@H](C)[C@@H]1NC(=O)[C@@H]2CCCN2C(=O)[C@H](...,-5.020,10090.873134,12354.636964,15504.338681,0.650842,0.796850,4.938454,0.000079,0.759213,0.061590,0.633963,1.982656
20,41,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-6.560,8790.920321,13002.427406,16253.514818,0.540863,0.799976,4.970395,0.000091,0.841111,0.116052,0.453162,1.719202
21,5659,CCCC[C@@H]1NC(=O)[C@H](CCCC)NC(=O)[C@@H]2CCCN2...,-6.220,9490.619186,13648.846789,19660.487854,0.482726,0.694227,5.313398,0.000073,0.875772,0.171256,0.284489,1.453267
22,2348,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)NC(=O)[C...,-5.750,8520.177193,15320.309314,22556.459480,0.377727,0.679198,5.550509,0.000080,0.925917,0.274654,0.117032,1.003199
23,1033,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.130,8676.975277,11089.452014,17443.985236,0.497419,0.635718,5.010856,0.000073,0.867510,0.177754,0.219885,1.265299
24,1044,CC(C)C[C@@H]1NC(=O)CN(CCCOC(C)C)C(=O)[C@H]2CCC...,-5.040,9048.405962,10501.768096,15945.860000,0.567445,0.658589,4.913876,0.000073,0.823411,0.125916,0.374588,1.516049
25,5673,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccc(O)cc2)N(C)C(=O...,-5.805,8610.991975,11841.724849,18076.188644,0.476372,0.655101,5.140849,0.000076,0.879244,0.187131,0.218731,1.276175
26,1038,CC(C)C[C@@H]1NC(=O)CN(Cc2ccc(O)cc2)C(=O)[C@H]2...,-5.440,8529.317553,12455.406512,17586.624347,0.484989,0.708232,5.150651,0.000083,0.874520,0.166397,0.284891,1.482311
27,1040,CC(C)CN1CC(=O)N(CC(C)C)CC(=O)N(CC(C)C)CC(=O)N2...,-6.400,8362.862827,11136.819560,16436.228236,0.508807,0.677578,5.020246,0.000081,0.860881,0.156355,0.339222,1.465954
28,2296,CC(C)C[C@H]1NC(=O)[C@@H](CC(C)C)NC(=O)[C@@H](C...,-6.310,8225.955642,11564.366043,16247.807203,0.506281,0.711749,5.027381,0.000087,0.862369,0.150037,0.348292,1.545762
29,2302,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](C...,-4.710,7625.504754,12895.120130,17092.561200,0.446130,0.754429,5.136067,0.000099,0.894968,0.190864,0.265030,1.389115
30,2366,CC(C)C[C@@H]1NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@H]...,-4.570,7560.694122,11213.812039,16609.656670,0.455199,0.675138,4.995549,0.000089,0.890390,0.198627,0.236527,1.265086
31,2338,CC(C)C[C@@H]1NC(=O)[C@H](Cc2ccccc2)NC(=O)[C@H]...,-5.060,8319.860203,10488.625286,16163.827529,0.514721,0.648895,5.009004,0.000078,0.857358,0.160972,0.273093,1.341607
32,2310,CC[C@H]1C(=O)N[C@@H](CC(C)C)C(=O)N2CCC[C@@H]2C...,-4.490,8405.004579,8860.278527,15644.277365,0.537257,0.566359,4.908686,0.000067,0.843418,0.182149,0.191975,1.150971
33,2309,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.600,7051.834075,9160.971460,14927.399489,0.472409,0.613702,4.846365,0.000087,0.881380,0.205679,0.159393,1.033242
34,2306,CC(C)C[C@@H]1NC(=O)[C@H](C)N(C)C(=O)[C@H]2CCCN...,-4.750,6158.886703,7098.307151,9745.810909,0.631952,0.728344,4.304164,0.000118,0.775007,0.078459,0.551448,1.647819

In [112]:
import os

#Train MOL structure generator
input_file = '/home/users/akshay/PCPpred/RRCK/data/Train_RRCK.smi'
output_dir = '/home/users/akshay/PCPpred/RRCK/data/Train_mol_RRCK'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 140/140 [01:16<00:00,  1.82it/s]

3D conformations generated and saved.

In [113]:
directory_path = '/home/users/akshay/PCPpred/RRCK/data/Train_mol_RRCK'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 140

In [114]:
#Test MOL structure generator
input_file = '/home/users/akshay/PCPpred/RRCK/data/Test_RRCK.smi'
output_dir = '/home/users/akshay/PCPpred/RRCK/data/Test_mol_RRCK'

os.makedirs(output_dir, exist_ok=True)

# Read the .smi file
with open(input_file, 'r') as f:
    lines = f.readlines()

for line in tqdm(lines, desc="Processing molecules"):
    parts = line.strip().split()
    if len(parts) != 2:
        continue  
    smiles, ID = parts

    # Generate 3D conformation
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"Invalid SMILES: {smiles} for id: {ID}")
        continue

    # Add hydrogens and generate 3D coordinates
    mol = Chem.AddHs(mol)
    AllChem.EmbedMolecule(mol)
    

    # Save the 3D conformation in MDL format
    output_file = os.path.join(output_dir, f"{ID}.mdl")
    with open(output_file, 'w') as out:
        out.write(Chem.MolToMolBlock(mol))

print("3D conformations generated and saved.")

Processing molecules: 100%|██████████| 35/35 [00:21<00:00,  1.64it/s]

3D conformations generated and saved.

In [115]:
directory_path = '/home/users/akshay/PCPpred/RRCK/data/Test_mol_RRCK'
files = os.listdir(directory_path)
file_count = sum(os.path.isfile(os.path.join(directory_path, f)) for f in files)

print(f"Number of files in the directory: {file_count}")

Number of files in the directory: 35